### ISSUE TITLE
All OptimizeIndexJob are timing out after 1m (instead of 1h)

### ISSUE THREAD

**Issue by aim4r** [Graylog2/graylog2-server#10054]
## Environment & Context

* Graylog Version: 4.0.2
* Elasticsearch Version: 7.10.2 (OSS), recently upgraded from 6 (DEB packages)
* Operating System: Ubuntu Server 20.04

## The problem

Shortly after upgrading GL from 4.0.1 to 4.0.2 and **ES from 6 to 7.10.2 (OSS)**, all new OptimizeIndexJob are failing with the following error in the logs (timeout after 60 seconds).

```
2021-02-12T11:44:40.808+01:00 ERROR [SystemJobManager] Unhandled error while running SystemJob <07c50bec-6d1f-11eb-b130-005056afb272> [org.graylog2.indexer.indices.jobs.OptimizeIndexJob]
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: An error occurred: 
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:134) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:97) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:90) ~[?:?]
        at org.graylog.storage.elasticsearch7.IndicesAdapterES7.optimizeIndex(IndicesAdapterES7.java:394) ~[?:?]
        at org.graylog2.indexer.indices.Indices.optimizeIndex(Indices.java:326) ~[graylog.jar:?]
        at org.graylog2.indexer.indices.jobs.OptimizeIndexJob.execute(OptimizeIndexJob.java:71) ~[graylog.jar:?]
        at org.graylog2.system.jobs.SystemJobManager$1.run(SystemJobManager.java:89) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_282]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.net.SocketTimeoutException: 60,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:834) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:259) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesClient.forcemerge(IndicesClient.java:897) ~[?:?]
        at org.graylog.storage.elasticsearch7.IndicesAdapterES7.lambda$optimizeIndex$22(IndicesAdapterES7.java:394) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:95) ~[?:?]
        ... 13 more
Caused by: java.net.SocketTimeoutException: 60,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
        at org.graylog.shaded.elasticsearch7.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[?:?]
        ... 1 more
```
Reading in the docs and the forums, I was under the impression that timeout for these optimize jobs is controlled via the `elasticsearch_index_optimization_timeout`, which is set to 1 hour (and not 60 seconds).

Here is an excerpt of my server.conf setup :
```
$ cat /etc/graylog/server/server.conf | grep elasticsearch_index_optimization_timeout
elasticsearch_index_optimization_timeout = 1h
```
I have also doubled `elasticsearch_socket_timeout` and `elasticsearch_request_timeout` from 1m to 2m, but the timeouts did not disappear and the OptimizeIndexJob are still failing after 120 seconds. 

Any ideas ?

**Comment by dennisoelkers** [comment]
Hey @aim4r,

thanks for reporting this issue! I can confirm that we are using the default timeout of 60s for the optimize index request, instead of the `elasticsearch_index_optimization_timeout` setting which defaults to 1h.

I will prepare a PR that fixes this, so it should go into `4.0.3`. There is no workaround at the moment, unfortunately. I am sorry for the inconvenience.

**Comment by aim4r** [comment]
Thanks for the quick response, I'll be updating as soon as as a new release is available.

Meanwhile, I will be increasing `elasticsearch_socket_timeout` to 1H. I appreciate this workaround might have some indesirable side effects, but I really don't want to run into a disk space issue (caused by the optimizers not running properly).

**Comment by HenryTheSir** [comment]
Hi @aim4r, 

the force merge in elastic Runs independent of the success in graylog. Once triggered elastic will force merge the Index. You can Check this directly against ES. Call :9200/_cat/thread_pool there should be a Pool for forcemerge which continues even if the graylog Job fails.

**Comment by aim4r** [comment]
Hello @HenryTheSir, 
Without optimization, my indices are usually at 11-12 Gb. With optimization, the get reduced to 7-8 Gb. That's **~30%** of otimized disk space.
So in my case, if all optimizers jobs stop working all the sudden, I will be looking at at ~30% increase in disk space usage, in a matter of a few days.

**Comment by dennisoelkers** [comment]
Hey @aim4r,

I think @HenryTheSir's point is that the force merge requests are timing out, but not cancelled. So the tasks continue to run, even after the request itself from Graylog has timed out and logged an exception. I have not validated this yet, but it seems plausible.
