### ISSUE TITLE
deleted input continue to fill the server log of errors

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/graylog2-server#1005]
2015-02-27T16:56:27.538+01:00 ERROR [ExtractorFilter] Could not load extractors into cache. Returning empty list.
java.util.concurrent.ExecutionException: org.graylog2.database.NotFoundException: Input <54f08472e4b0e9a8aafe9256> not found!
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
        at org.graylog2.filters.ExtractorFilter.loadExtractors(ExtractorFilter.java:73)
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:59)
        at org.graylog2.buffers.processors.ServerProcessBufferProcessor.handleMessage(ServerProcessBufferProcessor.java:97)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:71)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:33)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.graylog2.database.NotFoundException: Input <54f08472e4b0e9a8aafe9256> not found!
        at org.graylog2.inputs.InputServiceImpl.find(InputServiceImpl.java:115)
        at org.graylog2.filters.ExtractorFilter$1.call(ExtractorFilter.java:78)
        at org.graylog2.filters.ExtractorFilter$1.call(ExtractorFilter.java:73)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        ... 14 more
2015-02-27T16:56:27.539+01:00 ERROR [StaticFieldFilter] Could not load static fields into cache. Returning empty list.
java.util.concurrent.ExecutionException: org.graylog2.database.NotFoundException: Input <54f08472e4b0e9a8aafe9256> not found!
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
        at org.graylog2.filters.StaticFieldFilter.loadStaticFields(StaticFieldFilter.java:74)
        at org.graylog2.filters.StaticFieldFilter.filter(StaticFieldFilter.java:61)
        at org.graylog2.buffers.processors.ServerProcessBufferProcessor.handleMessage(ServerProcessBufferProcessor.java:97)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:71)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:33)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.graylog2.database.NotFoundException: Input <54f08472e4b0e9a8aafe9256> not found!
        at org.graylog2.inputs.InputServiceImpl.find(InputServiceImpl.java:115)
        at org.graylog2.filters.StaticFieldFilter$1.call(StaticFieldFilter.java:78)
        at org.graylog2.filters.StaticFieldFilter$1.call(StaticFieldFilter.java:74)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        ... 14 more

**Comment by bernd** [comment]
Thank you for the report! This happens when you delete an input and still have messages in the journal that came in through the deleted input. Once such a message is read from the journal and is processed, some database lookups will done for the input id to load extractors and static fields.

We are going to change the exceptions to a WARN message to avoid spamming the logs too much. If you have lots of messages in the journal, you might still see a lot of WARN messages, but I think that is better than being completely silent. Otherwise you would have a hard time debugging missing extracted fields in messages.

**Comment by lordraiden** [comment]
This should be fixed, if you delete an input with extractors the log get full of this messages

```
Graylog             | 2023-06-16 13:32:38,217 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,217 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,217 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,217 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,217 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,221 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,221 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,221 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,221 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,221 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,225 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,225 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,225 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,225 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,225 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,228 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,228 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not found!
Graylog             | 2023-06-16 13:32:38,228 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <648c479dab384e7079e53c5d>: Input <648c479dab384e7079e53c5d> not f
```
