### ISSUE TITLE
Error executing action `run` on resource 'ruby_block[add node to server list]'

### ISSUE THREAD

**Issue by dejuid00** [Graylog2/graylog2-server#1007]
I raised this per Marius on 18 Feb in the newsgroup in somewhat of a follow-up to https://github.com/Graylog2/graylog2-server/issues/939, but I've had no response.

I brought three new OVA-based systems online on 16 Feb. The first is the graylog server, the second web server and third is elasticsearch.

On the first, when running reconfigure, I'm getting below. The system is working as expected (even the SMTP port setting change has taken effect, which is what the reconfigure was meant to do).

Please let me know if there's a way to recover the reconfigure process. Thanks.

```
ubuntu@st-inf-07:/var/log$ sudo graylog2-ctl reconfigure
Starting Chef Client, version 12.0.3
Compiling Cookbooks...
Recipe: graylog2::default
  * directory[/etc/graylog2] action create (up to date)
  Converging 74 resources
  * directory[/etc/graylog2] action nothing (skipped due to action :nothing)
Recipe: graylog2::users
  * group[graylog2] action create (up to date)
  * user[graylog2] action create (up to date)
  * directory[/var/opt/graylog2] action create (up to date)
  * template[/var/opt/graylog2/.gitconfig] action create (up to date)
  * directory[/var/opt/graylog2/data] action create (up to date)
Recipe: graylog2::authbind
  * directory[/etc/authbind/byport] action create (up to date)
  * file[/etc/authbind/byport/!514] action create (up to date)
Recipe: runit::upstart
  * cookbook_file[/etc/init/graylog2-runsvdir.conf] action create (up to date)
  * execute[initctl status graylog2-runsvdir] action run
    - execute initctl status graylog2-runsvdir
  * execute[initctl start graylog2-runsvdir] action run (skipped due to only_if)
Recipe: timezone-ii::default
  * apt_package[tzdata] action install (up to date)
Recipe: timezone-ii::debian
  * template[/etc/timezone] action create (up to date)
  * bash[dpkg-reconfigure tzdata] action nothing (skipped due to action :nothing)
Recipe: graylog2::etcd
  * directory[/var/log/graylog2/etcd] action create (up to date)
  * directory[/var/opt/graylog2/data/etcd] action create (up to date)
  * directory[/opt/graylog2/sv/etcd] action create (up to date)
  * directory[/opt/graylog2/sv/etcd/log] action create (up to date)
  * directory[/opt/graylog2/sv/etcd/log/main] action create (up to date)
  * template[/opt/graylog2/sv/etcd/run] action create (up to date)
  * template[/opt/graylog2/sv/etcd/log/run] action create (up to date)
  * template[/var/log/graylog2/etcd/config] action create (up to date)
  * ruby_block[reload etcd svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog2/sv/etcd/down] action delete (up to date)
  * link[/opt/graylog2/init/etcd] action create (up to date)
  * link[/opt/graylog2/service/etcd] action create (up to date)
  * ruby_block[supervise_etcd_sleep] action run (skipped due to not_if)
  * service[etcd] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog2/embedded/bin/graylog2-ctl start etcd] action run
    - execute /opt/graylog2/embedded/bin/graylog2-ctl start etcd
Recipe: graylog2::elasticsearch_disable
  * link[/opt/graylog2/service/elasticsearch] action delete (up to date)
Recipe: graylog2::mongodb
  * directory[/var/log/graylog2/mongodb] action create (up to date)
  * directory[/var/opt/graylog2/data/mongodb] action create (up to date)
  * directory[/opt/graylog2/sv/mongodb] action create (up to date)
  * directory[/opt/graylog2/sv/mongodb/log] action create (up to date)
  * directory[/opt/graylog2/sv/mongodb/log/main] action create (up to date)
  * template[/opt/graylog2/sv/mongodb/run] action create (up to date)
  * template[/opt/graylog2/sv/mongodb/log/run] action create (up to date)
  * template[/var/log/graylog2/mongodb/config] action create (up to date)
  * ruby_block[reload mongodb svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog2/sv/mongodb/down] action delete (up to date)
  * link[/opt/graylog2/init/mongodb] action create (up to date)
  * link[/opt/graylog2/service/mongodb] action create (up to date)
  * ruby_block[supervise_mongodb_sleep] action run (skipped due to not_if)
  * service[mongodb] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog2/embedded/bin/graylog2-ctl start mongodb] action run
    - execute /opt/graylog2/embedded/bin/graylog2-ctl start mongodb
Recipe: graylog2::graylog2-server
  * directory[/var/log/graylog2/server] action create (up to date)
  * directory[/var/opt/graylog2/data/spool] action create (up to date)
  * file[/var/opt/graylog2/graylog2-server-node-id] action create (up to date)
  * template[/opt/graylog2/conf/graylog2.conf] action create
    - update content in file /opt/graylog2/conf/graylog2.conf from 74f487 to e70009
    --- /opt/graylog2/conf/graylog2.conf        2015-02-16 10:16:00.504786107 -0500
    +++ /tmp/chef-rendered-template20150218-8018-nt33nc 2015-02-18 08:52:44.878983013 -0500
    @@ -222,7 +222,7 @@
     # Email transport
     transport_email_enabled = true
     transport_email_hostname = smtp.server.name
    -transport_email_port = 587
    +transport_email_port = 25
     transport_email_use_auth = false
     transport_email_use_tls = true
     transport_email_use_ssl = true
  * directory[/opt/graylog2/sv/graylog2-server] action create (up to date)
  * directory[/opt/graylog2/sv/graylog2-server/log] action create (up to date)
  * directory[/opt/graylog2/sv/graylog2-server/log/main] action create (up to date)
  * template[/opt/graylog2/sv/graylog2-server/run] action create (up to date)
  * template[/opt/graylog2/sv/graylog2-server/log/run] action create (up to date)
  * template[/var/log/graylog2/server/config] action create (up to date)
  * ruby_block[reload graylog2-server svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog2/sv/graylog2-server/down] action delete (up to date)
  * link[/opt/graylog2/init/graylog2-server] action create (up to date)
  * link[/opt/graylog2/service/graylog2-server] action create (up to date)
  * ruby_block[supervise_graylog2-server_sleep] action run (skipped due to not_if)
  * service[graylog2-server] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog2/embedded/bin/graylog2-ctl start graylog2-server] action run
    - execute /opt/graylog2/embedded/bin/graylog2-ctl start graylog2-server
  * ruby_block[add node to server list] action run
    
    ================================================================================
    Error executing action `run` on resource 'ruby_block[add node to server list]'
    ================================================================================
    
    Net::HTTPFatalError
    -------------------
    500 "Internal Server Error"
    
    Cookbook Trace:
    ---------------
    /opt/graylog2/embedded/cookbooks/graylog2/libraries/registry.rb:15:in `set_master'
    /opt/graylog2/embedded/cookbooks/graylog2/recipes/graylog2-server.rb:73:in `block (2 levels) in from_file'
    
    Resource Declaration:
    ---------------------
    # In /opt/graylog2/embedded/cookbooks/graylog2/recipes/graylog2-server.rb
    
     71: ruby_block "add node to server list" do
     72:   block do
     73:     $registry.set_master
     74:     $registry.add_gl2_server(node['ipaddress'])
     75:     $registry.add_es_node(node['ipaddress'])
     76:   end
     77: end
    
    Compiled Resource:
    ------------------
    # Declared in /opt/graylog2/embedded/cookbooks/graylog2/recipes/graylog2-server.rb:71:in `from_file'
    
    ruby_block("add node to server list") do
      action "run"
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "add node to server list"
      declared_type :ruby_block
      cookbook_name :graylog2
      recipe_name "graylog2-server"
      block #<Proc:0x00000003926528@/opt/graylog2/embedded/cookbooks/graylog2/recipes/graylog2-server.rb:72>
    end
    
  * service[graylog2-server] action restart
    - restart service service[graylog2-server]

Running handlers:
[2015-02-18T08:57:50-05:00] ERROR: Running exception handlers
Running handlers complete
[2015-02-18T08:57:50-05:00] ERROR: Exception handlers complete
[2015-02-18T08:57:50-05:00] FATAL: Stacktrace dumped to /opt/graylog2/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 6 resources updated in 308.400802314 seconds
[2015-02-18T08:57:50-05:00] ERROR: ruby_block[add node to server list] (graylog2::graylog2-server line 71) had an error: Net::HTTPFatalError: 500 "Internal Server Error"
[2015-02-18T08:57:50-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ubuntu@st-inf-07:/var/log$ 
```

**Comment by bernd** [comment]
There have been lots of changes since Feb. I am closing this issue now, please re-open if this is still an issue with the latest OVA. Thank you!
