### ISSUE TITLE
Elasticsearch too_many_buckets_exception

### ISSUE THREAD

**Issue by aim4r** [Graylog2/graylog2-server#10148]
## The problem
Since upgrading to GL4/ES7, I started noticing the following error in GL's logs : 
```
2021-02-24T17:14:19.723+01:00 ERROR [PivotAggregationSearch] Aggregation search query <query-1> returned an error: Elasticsearch exception [type=too_many_buckets_exception, reason=Trying to create too many buckets. Must be less than or equal to: [65535] but was [65536]. This limit can be set by changing the [search.max_buckets] cluster level setting.].
ElasticsearchException{message=Search type returned error: , errorDetails=[]}
        at org.graylog.storage.elasticsearch7.views.ElasticsearchBackend.doRun(ElasticsearchBackend.java:255)
        at org.graylog.storage.elasticsearch7.views.ElasticsearchBackend.doRun(ElasticsearchBackend.java:69)
        at org.graylog.plugins.views.search.engine.QueryBackend.run(QueryBackend.java:83)
        at org.graylog.plugins.views.search.engine.QueryEngine.prepareAndRun(QueryEngine.java:164)
        at org.graylog.plugins.views.search.engine.QueryEngine.lambda$execute$6(QueryEngine.java:104)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: ElasticsearchException[Elasticsearch exception [type=search_phase_execution_exception, reason=]]; nested: ElasticsearchException[Elasticsearch exception [type=too_many_buckets_exception, reason=Trying to create too many buckets. Must be less than or equal to: [65535] but was [65536]. This limit can be set by changing the [search.max_buckets] cluster level setting.]];
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:496)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:603)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.action.search.MultiSearchResponse.itemFromXContent(MultiSearchResponse.java:215)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.action.search.MultiSearchResponse.lambda$static$1(MultiSearchResponse.java:56)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareObjectArray$13(AbstractObjectParser.java:254)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareFieldArray$22(AbstractObjectParser.java:300)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.AbstractObjectParser.parseArray(AbstractObjectParser.java:382)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareFieldArray$23(AbstractObjectParser.java:300)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.ObjectParser.lambda$declareField$9(ObjectParser.java:386)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:529)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.ObjectParser.parseArray(ObjectParser.java:523)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.ObjectParser.parseSub(ObjectParser.java:555)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:324)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:171)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:163)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.action.search.MultiSearchResponse.fromXContext(MultiSearchResponse.java:194)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$8(RestHighLevelClient.java:1554)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1630)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.msearch(RestHighLevelClient.java:1118)
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.lambda$msearch$2(ElasticsearchClient.java:73)
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:97)
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.msearch(ElasticsearchClient.java:73)
        at org.graylog.storage.elasticsearch7.views.ElasticsearchBackend.doRun(ElasticsearchBackend.java:239)
        ... 8 more
Caused by: ElasticsearchException[Elasticsearch exception [type=too_many_buckets_exception, reason=Trying to create too many buckets. Must be less than or equal to: [65535] but was [65536]. This limit can be set by changing the [search.max_buckets] cluster level setting.]]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:496)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:407)
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:437)
        ... 33 more
```
Should I simply increase `search.max_buckets` in ES ? Or is something wrong with my aggregation searches ?

## Environment

* Graylog Version: 4.0.5
* Elasticsearch Version: 7.10.2 (OSS), recently upgraded from 6 (DEB packages)
* Operating System: Ubuntu Server 20.04

**Comment by dennisoelkers** [comment]
Hey @aim4r,

thanks for reporting this. Can you isolate this to a specific search or even aggregation widget? E.g. is there a particularly large aggregation you are doing?

**Comment by aim4r** [comment]
Hi @dennisoelkers  : it will be tricky for me to isolate, as I have 50+ aggregation type event definitions which are running at different time intervals.
In all cases, I will keep an eye on the logs and see if I can catch the widget or the event definition that causes these errors.
Meanwhile I'm open to any other suggestions :)

**Comment by dennisoelkers** [comment]
Raising the bucket limit is an option to make this work. In general, I would assume that the bucket limit is enough for most visualization tasks, but maybe not for scripted consumption of the API and/or alerting. This boils down to the actual use case.

**Comment by aim4r** [comment]
Thanks for the feedback. 
I have tried to isolate the issue with no luck. The error seems random in time and it even happens very early at mornings (like 06AM) where we have no active GL user. 
I will increase the bucket limit if the errors become very frequent. 
I'll close this issue for the time being.

**Comment by aim4r** [comment]
A note to anyone else who is having the same issue: 

I have managed to track down the offending `Event Definition` which caused these errors, by matching the timestamp in the `server.log` error logs with the event's `Last execution` time in the UI (both timestamps should be seconds apart).

From there, I was able to do adjustments on the queries to avoid the `too_many_buckets_exception` error.
