### ISSUE TITLE
Indices retention fails - Uncaught exception in periodical java.lang.NumberFormatException

### ISSUE THREAD

**Issue by c0rnflex** [Graylog2/graylog2-server#1014]
Hi,
Could you please point me to why the graylog2 indices retention fails?
Running graylog2 v0.90.1

> 2015-03-02 12:10:08,961 INFO : org.graylog2.periodical.IndexRetentionThread - Number of indices (69) higher than limit (20). Running retention for 49 indices.
> 2015-03-02 12:10:08,965 ERROR: org.graylog2.periodical.IndexRetentionThread - Uncaught exception in periodical
java.lang.NumberFormatException
        at org.graylog2.indexer.Deflector.extractIndexNumber(Deflector.java:246)
        at org.graylog2.indexer.IndexHelper.getOldestIndices(IndexHelper.java:47)
        at org.graylog2.periodical.IndexRetentionThread.runRetention(IndexRetentionThread.java:109)
        at org.graylog2.periodical.IndexRetentionThread.doRun(IndexRetentionThread.java:91)
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

**Comment by joschi** [comment]
Looks like there are indices managed by Graylog2 that do not end in a number. There should be only indices named "graylog2_<NUMBER>" (or whatever you chose as your prefix) and the deflector alias in the Elasticsearch cluster if they start with the `elasticsearch_index_prefix`. So for example an index named "graylog2_foobar" would cause this exception.

In general I also recommend upgrading to Graylog 1.0.0 as the 0.90.x series isn't supported anymore and won't get bug fixes.

**Comment by c0rnflex** [comment]
Thanks :)
