### ISSUE TITLE
Slash character breaks scheme and host validator for server config

### ISSUE THREAD

**Issue by madarve** [Graylog2/graylog2-server#10265]
When using a `/` in a password on the `elasticsearch_hosts` entry  in `server.conf` file, I'm getting a:

```
ERROR [CmdLineTool] Invalid configuration
com.github.joschi.jadconfig.ValidationException: Parameter elasticsearch_hosts must not contain URIs without host or scheme.
	at org.graylog2.configuration.validators.ListOfURIsWithHostAndSchemeValidator.validate(ListOfURIsWithHostAndSchemeValidator.java:34) ~[graylog.jar:?]
	at org.graylog2.configuration.validators.ListOfURIsWithHostAndSchemeValidator.validate(ListOfURIsWithHostAndSchemeValidator.java:26) ~[graylog.jar:?]
	at com.github.joschi.jadconfig.JadConfig.validateParameter(JadConfig.java:215) ~[graylog.jar:?]
	at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:148) ~[graylog.jar:?]
	at com.github.joschi.jadconfig.JadConfig.process(JadConfig.java:99) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.processConfiguration(CmdLineTool.java:353) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.readConfiguration(CmdLineTool.java:346) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:180) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:50) [graylog.jar:?]
```
## Expected Behavior
`/` should be usable as part of a secure password for ES

## Current Behavior
`/` causes the validator to interpret it as the beginning of a URL

## Your Environment

* Graylog Version: 4.0
* Java Version: 1.8.0_282
* Operating System: Ubuntu 19.04

**Comment by bernd** [comment]
@madarve Have you tried to URL-encode the `/` character? That should work.
