### ISSUE TITLE
Can not connect to Ryuk at <Container IP>:32768

### ISSUE THREAD

**Issue by ManirajDeivendran** [Graylog2/graylog2-server#10516]
I am running into an issue within docker environment. The issue may be relevant to Docker-in-Docker.

Command used to build and test: mvn clean package

According to the testcontainers [Docker-in-Docker](https://www.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/) requirement added the options -v $PWD:$PWD -w $PWD -v /var/run/docker.sock:/var/run/docker.sock in docker run command.
`docker run -v /var/run/docker.sock:/var/run/docker.sock`

Build failure with below error,
```
[INFO] Running org.graylog.security.entities.EntityDependencyResolverTest
2021-04-26 17:52:55,762 WARN : org.testcontainers.utility.TestcontainersConfiguration - Attempted to read Testcontainers configuration file at file:/root/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /root/.testcontainers.properties (No such file or directory)
2021-04-26 17:53:00,235 WARN : org.testcontainers.utility.ResourceReaper - Can not connect to Ryuk at <Container IP>:32768
java.net.NoRouteToHostException: No route to host (Host unreachable)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_292]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_292]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_292]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_292]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_292]
        at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_292]
        at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:163) ~[testcontainers-1.15.2.jar:?]
        at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27) ~[duct-tape-1.0.8.jar:?]
        at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:159) ~[testcontainers-1.15.2.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
...
2021-04-26 17:53:29,239 ERROR: org.testcontainers.utility.ResourceReaper - Timed out waiting for Ryuk container to start. Ryuk's logs:
2021/04/26 17:52:59 Pinging Docker...
2021/04/26 17:52:59 Docker daemon is available!
2021/04/26 17:52:59 Starting on port 8080...
2021/04/26 17:52:59 Started!

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 34.405 s <<< FAILURE! - in org.graylog.security.authzroles.PaginatedAuthzRolesServiceTest
[ERROR] org.graylog.security.authzroles.PaginatedAuthzRolesServiceTest  Time elapsed: 34.405 s  <<< ERROR!
org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=mongo:3.6, imagePullPolicy=DefaultPullPolicy())
Caused by: java.lang.IllegalStateException: Could not connect to Ryuk at <Container IP>:32768

[ERROR] Tests run: 3267, Failures: 3, Errors: 549, Skipped: 60
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Graylog Parent POM 4.1.0-SNAPSHOT:
[INFO]
[INFO] Graylog Parent POM ................................. SUCCESS [  0.364 s]
[INFO] Graylog Project Parent POM ......................... SUCCESS [  0.095 s]
[INFO] Graylog ............................................ FAILURE [09:21 min]
```

Unable to run the graylog tests in docker container environment. The environment is ppc64le/UBI 8.3 (RHEL 8.3 based docker container environment)

docker version
Client:  Version:           18.06.3-ce  API version:       1.38  OS/Arch:           linux/ppc64le
Server:  Engine:  Version:          18.06.3-ce  API version:      1.38 (minimum version 1.12)  OS/Arch:          linux/ppc64le
* Graylog Version: master
* Java Version: 1.8.0_292
* Operating System: Linux/ppc64le

Any pointers help would be great, thanks in advance!!

**Comment by bernd** [comment]
@ManirajDeivendran This doesn't look like a Graylog problem but more like problem with testcontainers and running docker inside docker. Please check with the testcontainers community. Thank you!
