### ISSUE TITLE
After upgrade to Graylog 4.x, the Streams page does not load (StreamDTO - Null matchingType)

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#10514]
## Expected Behavior

The Streams page should load successfully.

## Current Behavior

  After upgrading to Graylog 4.x, the Stream page does not load. The following stacktrace is displayed in the Graylog server log:

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.graylog2.streams.StreamDTO`, problem: Null matchingType
at org.graylog2.streams.StreamDTO.create(StreamDTO.java:141) ~[graylog.jar:?]
at org.graylog2.streams.$AutoValue_StreamDTO.<init>($AutoValue_StreamDTO.java:71) ~[graylog.jar:?]
at org.graylog2.streams.AutoValue_StreamDTO.<init>(AutoValue_StreamDTO.java:19) ~[graylog.jar:?]
at org.graylog2.database.PaginatedDbService.findPaginatedWithQueryFilterAndSort(PaginatedDbService.java:159) ~[graylog.jar:?]
at org.graylog2.streams.PaginatedStreamService.findPaginated(PaginatedStreamService.java:48) ~[graylog.jar:?]
```

This indicates that the `streams.matching_type` collection value is null, but the `StreamDTO` requires a value.

## Possible Solution

Allow the [StreamDTO.matchingType()](https://github.com/Graylog2/graylog2-server/blob/29aa0ab4bd8dca7ef60ab7b5f1b17b805d9e7027/graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java#L66) to be Optional or nullable. Also, provide a default value in the create or builder methods. The default can use the same logic as [StreamImpl](https://github.com/Graylog2/graylog2-server/blob/29aa0ab4bd8dca7ef60ab7b5f1b17b805d9e7027/graylog2-server/src/main/java/org/graylog2/streams/StreamImpl.java#L223) uses currently.

## Steps to Reproduce (for bugs)

This issue occurs mostly for older Graylog installations that are upgraded to 4.1 or beyond.

## Workaround
To workaround the issue, provide a `streams.matching_type` value equal to `AND` in MongoDB for any that currently have a null value.

See user suggestions here: 
https://github.com/Graylog2/graylog2-server/issues/9637#issuecomment-827091749
https://github.com/Graylog2/graylog2-server/issues/9637#issuecomment-769005192

## Your Environment

* Graylog Version: 4.x

**Comment by danotorrey** [comment]
Several users have experienced this issue after upgrading to 4.x. See https://github.com/Graylog2/graylog2-server/issues/9637

**Comment by thll** [comment]
https://github.com/Graylog2/graylog2-server/issues/9274#issuecomment-767680018 looks like another encounter of this bug.
