### ISSUE TITLE
Error showing system overview after cycling deflector

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1055]
On the current 1.0 branch, I cycled the deflector manually and went to the system overview page. There I found an error message (expected HTTP 200 but got 500), and this stack-trace on the server logs:

```
2015-03-10 18:15:45,223 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.NullPointerException: Null startedAt
	at org.graylog2.rest.models.system.AutoValue_SystemJobSummary.<init>(AutoValue_SystemJobSummary.java:52)
	at org.graylog2.rest.models.system.SystemJobSummary.create(SystemJobSummary.java:67)
	at org.graylog2.rest.resources.system.jobs.SystemJobResource.list(SystemJobResource.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I guess this is related to #1054.

**Comment by joschi** [comment]
I'm pretty sure that's related to my changes regarding #920 in #1054 and Graylog2/graylog2-web-interface#1161. I'll take care of it.

**Comment by crosdorff** [comment]
Hereby the ElasticSearch logs:

```
[2015-03-10 13:55:41,667][INFO ][cluster.metadata         ] [Pyro] [graylog2_18] creating index, cause [api], shards [1]/[0], mappings []
[2015-03-10 13:55:41,822][INFO ][cluster.metadata         ] [Pyro] [graylog2_18] create_mapping [message]
[2015-03-10 13:55:42,544][INFO ][cluster.metadata         ] [Pyro] [graylog2_18] update_mapping [message] (dynamic)
[2015-03-10 13:55:49,656][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624541793 [595.6mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:49,682][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624541806 [595.6mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:49,721][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624541799 [595.6mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:49,743][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624541824 [595.6mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:50,881][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624542028 [595.6mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:50,882][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624541991 [595.6mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:50,927][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624542003 [595.6mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:50,927][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624541997 [595.6mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:50,940][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 623985760 [595mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:50,940][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 623985766 [595mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:50,940][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 623985766 [595mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:50,943][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 623985766 [595mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:51,707][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624346122 [595.4mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:51,715][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624346097 [595.4mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:51,728][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624346110 [595.4mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:55:51,751][WARN ][indices.breaker          ] [Pyro] [FIELDDATA] New used memory 624346103 [595.4mb] from field [timestamp] would be larger than configured breaker: 623326003 [594.4mb], breaking
[2015-03-10 13:56:02,119][INFO ][cluster.metadata         ] [Pyro] [graylog2_18] update_mapping [message] (dynamic)
[2015-03-10 13:56:19,613][INFO ][cluster.metadata         ] [Pyro] [graylog2_18] update_mapping [message] (dynamic)
[2015-03-10 13:56:21,586][INFO ][cluster.metadata         ] [Pyro] [graylog2_18] update_mapping [message] (dynamic)
[2015-03-10 13:56:22,558][INFO ][cluster.metadata         ] [Pyro] [graylog2_18] update_mapping [message] (dynamic)
[2015-03-10 14:00:04,141][INFO ][cluster.metadata         ] [Pyro] [graylog2_18] update_mapping [message] (dynamic)
[2015-03-10 14:06:13,318][INFO ][cluster.metadata         ] [Pyro] [graylog2_18] update_mapping [message] (dynamic)
```
