### ISSUE TITLE
Message decoding errors should log message source

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#1059]
If a message written to the disk journal can't be decoded (e. g. because it's an invalid message format) the log message doesn't contain the source of the message, which might be useful to detect a broken producer:
```
2015-03-13 09:57:56,959  ERROR: org.graylog2.inputs.codecs.GelfCodec - Could not parse JSON! com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
2015-03-13 09:57:56,959 WARN : org.graylog2.shared.buffers.ProcessBuffer - Unable to process event MessageEvent{raw=null, message=null}, sequence 39708
```
Additionally, the disk journal utilities (e. g. `JournalDecode`) don't print the source address in error cases either.

**Comment by plista-ld** [comment]
hi !
Is there an estimated release date for this feature ?

**Comment by tonybeltramelli** [comment]
We are having the same problem, some badly formatted messages are written to the disk journal but cannot be processed further, leading Graylog to complain:

```
ERROR [GelfCodec] Could not parse JSON!
...
WARN  [ProcessBuffer] Unable to process event MessageEvent{raw=null, message=null}, sequence 19320400
java.lang.IllegalStateException: JSON is null/could not be parsed (invalid JSON)
```

In this case, Graylog should then remove these messages from the disk journal, in order to avoid the journal to obviously become saturated at some point.

Will this feature be added to the 1.2.0 milestone?

**Comment by kroepke** [comment]
The journal should not grow without bound, at the very least it will be limited in size by whatever is specified in the config file, the oldest messages will be lost in that case.

We'll improve the log output for now.

**Comment by kroepke** [comment]
```
2015-08-25 15:12:18,508 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Unable to decode raw message e9a0b040-4b2a-11e5-9fd5-fe3742453b88 (journal offset 342459) encoded as gelf received from /127.0.0.1:51205.
2015-08-25 15:12:18,510 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=e9a0b040-4b2a-11e5-9fd5-fe3742453b88, journalOffset=342459, codec=gelf, payloadSize=181, timestamp=2015-08-25T15:12:18.500+02:00, remoteAddress=/127.0.0.1:51205}
com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input: expected close marker for OBJECT (from [Source: {"version": "1.1","host":"example.org","short_message":"Short message","full_message":"Backtrace here

more stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"; line: 1, column: 0])
 at [Source: {"version": "1.1","host":"example.org","short_message":"Short message","full_message":"Backtrace here

more stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"; line: 1, column: 363]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1576)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:470)
	at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:501)
	at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:509)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2018)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:743)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:219)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2262)
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:114)
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136)
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82)
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58)
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by tonybeltramelli** [comment]
Ok thank you for your time @kroepke!
