### ISSUE TITLE
Attribute type automaticaly detected by ES?

### ISSUE THREAD

**Issue by razvanphp** [Graylog2/graylog2-server#1063]
Ok, so I have two cases when this is really frustrating:
- sending a message with a numeric field for the first time, ES decides this field is an integer, and then all subsequent messages will fail parsing because of this:
````
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [ctxt_label]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:416)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:709)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:500)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:542)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:413)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:435)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:150)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "[15,576]"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:441)
	at java.lang.Long.parseLong(Long.java:483)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:145)
	at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:300)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:235)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:406)
	... 12 more
````
- the second case is the exact opposite of the first one, when ES decides a field is a string, just because it was wrapped in quotes, and then drawing graphs for that attribute or statistics is not possible anymore:
````
Error
Line charts are only available for numeric field types.
````

A temporary fix that sometimes works, is to manual cycle the index, but this will just switch from one problem to another.
I read that is possible to change the field type index in ES, but adding a new index conflicts with the one graylog is setting I guess.

What would be the solution? currently I have the logs full of failed to parse messages, and it's not really the fault of the messages.

Thank you for your support!

**Comment by reighnman** [comment]
You need to override the auto type by using templates:  http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html  http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-dynamic-mapping.html


View any templates:

curl -XGET localhost:9200/_template/*

Something like this would override the ThreadID field to type string for indexes graylog*:

curl -XPUT localhost:9200/_template/graylog -d '
  {
  "template" : "graylog*",
    "mappings" : {
      "message" : {
        "properties" : {
          "ThreadID" : {
            "index": "not_analyzed",
            "type" : "String"
           }
        }
      }
    }

If you mess up delete your template with:

curl -XDELETE localhost:9200/_template/graylog

Anyway this is part ES, not really an issue with Graylog so you should close this.

**Comment by razvanphp** [comment]
Currently graylog sets no template, so I guess ES uses dynamic guessing. The reality is, applications have no idea that another application / team sends the same field but as a string/integer.

Also, templates apply only for new indices anyway, so the hassle is really big to maintain such a thing. I really think graylog should manage this somehow, as it is part of ES cluster and can control it.

In my searches, I found out that "other" systems had this problem too, and they seem to include their own template:
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json
http://untergeek.com/2012/09/20/using-templates-to-improve-elasticsearch-caching-with-logstash/

**Comment by reighnman** [comment]
> Currently graylog sets no template, so I guess ES uses dynamic guessing. The reality is, applications have no idea that another application / team sends the same field but as a string/integer.

Which is exactly why you should make your own templates..

> Also, templates apply only for new indices anyway, so the hassle is really big to maintain such a thing. I really think graylog should manage this somehow, as it is part of ES cluster and can control it.

They apply for all new indices going forward, so once you set them and your logs roll around a few times you'll be set.  You can also manually roll your logs or if you really want go back through your old indicies and manually update the field type.

**Comment by betweenbrain** [comment]
I'm also running into this issue. It would be great if Graylog were to manage this and update indices dynamically.
