### ISSUE TITLE
Input does not start after ContentPack ReST creation

### ISSUE THREAD

**Issue by gianluca-valentini** [Graylog2/graylog2-server#10640]
## Expected Behavior
When I create a contentPack using graylog ReST API and apply it in a new and empty environment, the input should start without error

## Current Behavior
When I create a contentPack using graylog ReST API and apply it in a new and empty environment, the input start fails. The log tell me that the port is already in use (it is a new installation). Restarting the application the input become magically green

## Possible Solution
Maybe something change in ReST input creation with content pack and UI one

## Steps to Reproduce (for bugs)

1. Create a stream and an input
2. Export it using content pack 
3. Import content pack using rest client
4. The input does not start and the log describe the error (port already in use

## Your Environment
ContentPack creation and installation work fine but I have this problem on the input view

![image](https://user-images.githubusercontent.com/3224592/118298333-a2627400-b4df-11eb-8ba0-a7fe6ab43ede.png)

Looking the Graylog log I see:

![image](https://user-images.githubusercontent.com/3224592/118298376-abebdc00-b4df-11eb-8ee4-a6850011de78.png)

If I create another input using the UI it works fine
![image](https://user-images.githubusercontent.com/3224592/118298419-ba39f800-b4df-11eb-9b1b-912e6545dd8b.png)

I'm sure that the 12201 is not used. If I restart the application it become green

![image](https://user-images.githubusercontent.com/3224592/118298445-c2923300-b4df-11eb-965b-8c3f393810fc.png)

* Graylog Version: Applicance: Graylog 4.0.7+c3e766c on graylog (Private Build 1.8.0_292 on Linux 4.15.0-142-generic)
* Java Version: openjdk version "1.8.0_292"
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.0.24
* Operating System: ubuntu 18.04
* Browser version:

**Comment by gianluca-valentini** [comment]
I add other additional info
currently I’m using graylog OVA 4.0.7.
Now I have an empty environment where I delete all input

![image](https://user-images.githubusercontent.com/3224592/118963313-9a368880-b966-11eb-93d9-7e5efc195a8f.png)

using the command `ss-tulpn` I see
![image](https://user-images.githubusercontent.com/3224592/118963893-39f41680-b967-11eb-8539-2f67e1e4cd8f.png)

Then I create and install my content-pack (without parameters but with required inputs)
Content pack is uploaded with success but looking the input I see
![image](https://user-images.githubusercontent.com/3224592/118963970-51330400-b967-11eb-8835-9c5ccd426469.png)

`running ss -tulpn`

![image](https://user-images.githubusercontent.com/3224592/118964025-5d1ec600-b967-11eb-8baa-a979eec715ab.png)

When I try to start the input I have and error:
![image](https://user-images.githubusercontent.com/3224592/118964099-6dcf3c00-b967-11eb-8b5c-7c37b3bfd0c2.png)

where the log say

```
2021-05-19T13:04:51.627Z WARN [AbstractTcpTransport] Failed to start channel for input BeatsInput{title=AX-Beat, type=org.graylog.plugins.beats.BeatsInput, nodeId=null}
io.netty.channel.unix.Errors$NativeIoException: bind(…) failed: Address already in use
2021-05-19T13:04:51.627Z ERROR [InputLauncher] The [org.graylog.plugins.beats.BeatsInput] input with ID <60a50c20a010fd30e2204d1a> misfired. Reason: bind(…) failed: Address already in use.
org.graylog2.plugin.inputs.MisfireException: org.graylog2.plugin.inputs.MisfireException: io.netty.channel.unix.Errors$NativeIoException: bind(…) failed: Address already in use
at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:158) ~[graylog.jar:?]
at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84) [graylog.jar:?]
at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: org.graylog2.plugin.inputs.MisfireException: io.netty.channel.unix.Errors$NativeIoException: bind(…) failed: Address already in use
at org.graylog2.plugin.inputs.transports.AbstractTcpTransport.launch(AbstractTcpTransport.java:199) ~[graylog.jar:?]
at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:155) ~[graylog.jar:?]
… 7 more
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(…) failed: Address already in use
2021-05-19T13:04:51.631Z INFO [InputStateListener] Input [Beats (deprecated)/60a50c20a010fd30e2204d1a] is now FAILED
```

At the end the strange, very strange, situation is that is I restart Graylog, I don’t have input error anymore

Other point of this strange scenario is that if I delete all and run `running ss -tulpn` again

![image](https://user-images.githubusercontent.com/3224592/118964388-bc7cd600-b967-11eb-97fc-152d533786ed.png)

So the input ports seem to be used again

**Comment by losarenio** [comment]
I'm facing the same problem using the docker images on Kubernetes cluster (AKS). In my case, the content pack includes three inputs but only one is failing.

**Comment by gianluca-valentini** [comment]
Hi, any news about this issue?

**Comment by gianluca-valentini** [comment]
Any news about this?

**Comment by gianluca-valentini** [comment]
Hi any news about this?

**Comment by gianluca-valentini** [comment]
Hi all,
is there any update about this issue? 
So, how did you create an input installation that have to be the same in different client environments?
Did you use content pack or exist something different that can be used?
