### ISSUE TITLE
Change mongo port in graylog docker image

### ISSUE THREAD

**Issue by diegoturcios** [Graylog2/graylog2-server#10722]
For some specific reasons we are using port 27018 to connect to mongoDB.
So at the moment we're running graylog, 

```
$ docker run --name graylog --link mongo --link elasticsearch \
    -p 9000:9000 -p 12201:12201 -p 1514:1514 \
    -e GRAYLOG_HTTP_EXTERNAL_URI="http://127.0.0.1:9000/" \
    -d graylog/graylog:4.0
```

We're getting this error, which makes sense, as it's expected to be in 27017. Is there any way we can change this configuration?
```
2021-05-26 21:27:06,684 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017
com.mongodb.MongoSocketException: mongo: Temporary failure in name resolution
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:211) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:75) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[graylog.jar:?]
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:128) ~[graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Comment by asachs01** [comment]
Hi @diegoturcios, 

Presently, we are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

I'll note that for Docker, all of the configuration can be changed by[ prefixing the environment variable  `GRAYLOG_` when starting the image, or using a compose file](https://github.com/graylog2/graylog-docker#configuration).
