### ISSUE TITLE
Error when trying to generate content pack (0.92.4)

### ISSUE THREAD

**Issue by olafkewl** [Graylog2/graylog2-server#1073]
I have this error when trying to generate a content pack in order to import it into a new server :
"Oops, an error has occured"
![image](https://cloud.githubusercontent.com/assets/2979677/6777882/193eebb6-d14e-11e4-83fa-25d1d282b40b.png)

I have these infos in logfiles (same info in server and web-interface logs) :
```
2015-03-23 08:48:53,227 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception in transport layer. This is likely a bug, closing channel.
java.lang.StackOverflowError
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
```

**Comment by joschi** [comment]
@olafkewl Could you please try to reproduce this with Graylog 1.0.1? I wasn't able to trigger this error with either Graylog 1.0.1 or 1.1.0-SNAPSHOT.

**Comment by joschi** [comment]
@olafkewl I'm closing this issue now. Please leave a comment if the problem still occurs on Graylog 1.0.2 or 1.1.0.
