### ISSUE TITLE
Some valid grok patterns are refused with error

### ISSUE THREAD

**Issue by jimbocoder** [Graylog2/graylog2-server#1076]
This happens with the patterns-file import or when adding individual patterns through the web interface.
Version: `1.0.1 (e1b89b8) (Jever)`

Here's an example of a pattern that works with plain Logstash but cannot be imported into Graylog:
```
HAPROXYCAPTUREDREQUESTHEADERS %{DATA:haproxy.req.header.x_forwarded_for}
```

But the same pattern with `.` replaced with `_` works:
```
HAPROXYCAPTUREDREQUESTHEADERS %{DATA:haproxy_req_header_x_forwarded_for}
```

And here's the error and stack trace from the server log:
```
2015-03-24T14:21:40.821-05:00 WARN  [GrokPatternServiceImpl] Invalid regular expression syntax for 'HAPROXYCAPTUREDREQUESTHEADERS' with pattern %{DATA:haproxy.req.header.x_forwarded_for}
java.util.regex.PatternSyntaxException: Illegal repetition near index 1
(%{DATA:haproxy.req.header.x_forwarded_for})
 ^
	at java.util.regex.Pattern.error(Pattern.java:1924)
	at java.util.regex.Pattern.closure(Pattern.java:3104)
	at java.util.regex.Pattern.sequence(Pattern.java:2101)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.group0(Pattern.java:2854)
	at java.util.regex.Pattern.sequence(Pattern.java:2018)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.compile(Pattern.java:1665)
	at java.util.regex.Pattern.<init>(Pattern.java:1337)
	at java.util.regex.Pattern.compile(Pattern.java:1047)
	at com.google.code.regexp.Pattern.buildStandardPattern(Unknown Source)
	at com.google.code.regexp.Pattern.<init>(Unknown Source)
	at com.google.code.regexp.Pattern.compile(Unknown Source)
	at oi.thekraken.grok.api.Grok.compile(Grok.java:376)
	at org.graylog2.grok.GrokPatternServiceImpl.validate(GrokPatternServiceImpl.java:106)
	at org.graylog2.grok.GrokPatternServiceImpl.save(GrokPatternServiceImpl.java:78)
	at org.graylog2.rest.resources.system.GrokResource.createPattern(GrokResource.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

This is possibly an issue with the underlying [java-grok library](https://github.com/thekrakken/java-grok/) rather than Graylog, however [the pattern they're using](https://github.com/thekrakken/java-grok/blob/master/src/main/java/oi/thekraken/grok/api/GrokUtils.java) looks fine to me, and should allow `.` characters.

**Comment by kroepke** [comment]
I just tested this in 1.1.0-SNAPSHOT (after beta.2) and this seems to be fixed.

Please retry it in a 1.1.0 beta version and reopen if it is not fixed. We have updated java-grok in the meantime.

Thanks,
Kay
