### ISSUE TITLE
Okta Auth creation dialog form is not validated before testing

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#10829]
## Expected Behavior

As a user, I would want to test my Okta configuration before I save it. Therefore, the next step after entering my details in the `Create Okta Authentication Service` form is pressing the `Test Server Connection` button. Before the actual test is performed, I would expect the form to get validated and missing/invalid fields are highlighted.

## Current Behavior

When a user misses e.g. the `Token Verifier Connect Timeout` input (which is required), testing the server connection returns a long stack trace in a temporary notification instead of marking the input as missing.

In addition, for every validation error an exception is logged unnecessarily in the server log:

<details>

```
2021-06-11 11:39:13,870 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.IllegalArgumentException: Your client ID is missing. You can copy it from the Okta Developer Console in the details for the Application you created. Follow these instructions to find it: https://bit.ly/finding-okta-app-credentials
	at com.okta.commons.configcheck.ValidationResponse.lambda$ifInvalidThrow$0(ValidationResponse.java:44) ~[?:?]
	at com.okta.commons.configcheck.ValidationResponse.ifInvalid(ValidationResponse.java:50) ~[?:?]
	at com.okta.commons.configcheck.ValidationResponse.ifInvalidThrow(ValidationResponse.java:43) ~[?:?]
	at com.okta.commons.configcheck.ConfigurationValidator.assertClientId(ConfigurationValidator.java:187) ~[?:?]
	at com.okta.jwt.impl.jjwt.JjwtIdTokenVerifierBuilder.validate(JjwtIdTokenVerifierBuilder.java:42) ~[?:?]
	at com.okta.jwt.impl.jjwt.JjwtIdTokenVerifierBuilder.build(JjwtIdTokenVerifierBuilder.java:47) ~[?:?]
	at com.okta.jwt.impl.jjwt.JjwtIdTokenVerifierBuilder.build(JjwtIdTokenVerifierBuilder.java:25) ~[?:?]
	at org.graylog.plugins.security.authservice.backend.OktaIdTokenVerifier.createJwtVerifier(OktaIdTokenVerifier.java:40) ~[?:?]
	at org.graylog.plugins.security.authservice.backend.OktaIdTokenVerifier.<init>(OktaIdTokenVerifier.java:24) ~[?:?]
	at org.graylog.plugins.security.authservice.backend.OktaAuthServiceBackend.<init>(OktaAuthServiceBackend.java:70) ~[?:?]
	at org.graylog.plugins.security.authservice.backend.OktaAuthServiceBackend$$FastClassByGuice$$1172333757.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at org.graylog.plugins.security.authservice.backend.OktaAuthServiceBackend$$FastClassByGuice$$1172333757.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[graylog.jar:?]
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:878) ~[graylog.jar:?]
	at com.sun.proxy.$Proxy232.create(Unknown Source) ~[?:?]
	at org.graylog.security.authservice.test.AuthServiceBackendTestService.createNewBackend(AuthServiceBackendTestService.java:81) ~[graylog.jar:?]
	at org.graylog.security.authservice.test.AuthServiceBackendTestService.testConnection(AuthServiceBackendTestService.java:40) ~[graylog.jar:?]
	at org.graylog.security.authservice.rest.AuthServiceTestResource.backendConnection(AuthServiceTestResource.java:64) ~[graylog.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

</details>

## Steps to Reproduce (for bugs)

![oktaformvalidation](https://user-images.githubusercontent.com/41929/121657847-12452980-caa1-11eb-8ccb-1c8b88f75de9.gif)

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by edmundoa** [comment]
Since https://github.com/Graylog2/graylog-plugin-enterprise/pull/2364, we now do validation and also provide a default value for the token verifier timeout, so I think we can close this issue. Please reopen if still needed.
