### ISSUE TITLE
unable to send alert email

### ISSUE THREAD

**Issue by ovadm** [Graylog2/graylog2-server#1086]
hi, 
emails are not being sent, it was working fine with the VM appliance but when I moved to production server - installed everything using apt-get with same config file it stopped working 
Graylog Version 1.0.1/ Debian 7

```
ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.NullPointerException
        at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:92)
        at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:171)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by joschi** [comment]
The exception looks like one of the variables in https://github.com/Graylog2/graylog2-server/blob/1.0.1/graylog2-server/src/main/java/org/graylog2/alarmcallbacks/EmailAlarmCallback.java#L92-92 was `null` at the time of execution. Unfortunately it's hard to tell now.

Is there any exception before the one you've posted in your Graylog server logs?

**Comment by ovadm** [comment]
following service restart
2015-03-31T21:39:31.822+03:00 INFO  [RestApiService] Started REST API at <http://127.0.0.1:12900/>
2015-03-31T21:39:31.823+03:00 INFO  [ServiceManagerListener] Services are healthy
2015-03-31T21:39:31.825+03:00 INFO  [ServerBootstrap] Services started, startup times in ms: {MetricsReporterService [RUNNING]=3, InputSetupService [RUNNING]=4, KafkaJournal [RUNNING]=5, GroovyShellSetupService [RUNNING]=6, BufferSynchronizerService [RUNNING]=7, JournalReader [RUNNING]=7, OutputSetupService [RUNNING]=9, DashboardRegistryService [RUNNING]=22, PeriodicalsService [RUNNING]=69, IndexerSetupService [RUNNING]=3690, RestApiService [RUNNING]=7465}
2015-03-31T21:39:31.826+03:00 INFO  [InputSetupService] Triggering launching persisted inputs, node transitioned from Uninitialized?[LB:DEAD] to Running?[LB:ALIVE]
2015-03-31T21:39:31.831+03:00 INFO  [ServerBootstrap] Graylog server up and running.
2015-03-31T21:39:31.865+03:00 INFO  [InputStateListener] Input [Syslog UDP/5516ff21e4b028da85f09127] is now STARTING
2015-03-31T21:39:31.888+03:00 INFO  [InputStateListener] Input [Syslog UDP/5516ff21e4b028da85f09127] is now RUNNING
2015-03-31T21:39:35.074+03:00 INFO  [Version] HV000001: Hibernate Validator 5.1.2.Final
2015-03-31T21:40:19.429+03:00 INFO  [AbstractValidatingSessionManager] Enabling session validation scheduler...
2015-03-31T21:40:23.734+03:00 ERROR [EmailAlarmCallback] Stream [55191b2fe4b04b732ba92bf8: "BigIP service Down"] has alert receivers and is triggered, but sending emails failed
java.lang.NullPointerException
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:673)
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:633)
        at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:111)
        at org.apache.commons.mail.Email.createInternetAddress(Email.java:1884)
        at org.apache.commons.mail.Email.setFrom(Email.java:749)
        at org.apache.commons.mail.Email.setFrom(Email.java:732)
        at org.apache.commons.mail.Email.setFrom(Email.java:712)
        at org.graylog2.alerts.StaticEmailAlertSender.sendEmail(StaticEmailAlertSender.java:89)
        at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:211)
        at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:64)
        at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:79)
        at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:171)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2015-03-31T21:40:23.739+03:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.NullPointerException
        at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:92)
        at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:171)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ovadm** [comment]
Unfortunately I was not able to find a file named EmailAlarmCallbacl.java in order to eliminate variables.

**Comment by ovadm** [comment]
Also found this, however mail server hostname is being resolved correctly

2015-04-01T00:26:30.044+03:00 ERROR [EmailAlarmCallback] Stream [55191b2fe4b04b732ba92bf8: "BigIP service Down"] has alert receivers and is triggered, but sending emails failed
org.apache.commons.mail.EmailException: Cannot find valid hostname for mail session
        at org.apache.commons.mail.Email.getMailSession(Email.java:639)
        at org.apache.commons.mail.Email.buildMimeMessage(Email.java:1268)
        at org.apache.commons.mail.Email.send(Email.java:1436)
        at org.graylog2.alerts.StaticEmailAlertSender.sendEmail(StaticEmailAlertSender.java:94)
        at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:211)
        at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:64)
        at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:79)
        at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:92)

**Comment by ovadm** [comment]
solved, fortunately the t letter in transport was missing probably removed when line unremarked

thank you

**Comment by gbaltrons** [comment]
if someone could look a this https://github.com/gbaltrons/graylog/issues/1 i would appreciate a lot, thank you. I know it doesn't fit with this issue but i though no one would answer me if i won't link it here.

**Comment by joschi** [comment]
@gbaltrons Please open an issue in [this project](https://github.com/Graylog2/graylog2-server/issues) or better write a mail to [our mailing list](https://groups.google.com/forum/#!forum/graylog2).

**Comment by gbaltrons** [comment]
@joschi https://github.com/Graylog2/graylog2-server/issues/1567 thank you! I've just created my user, i'm novice here.
