### ISSUE TITLE
Unable to access API Browser

### ISSUE THREAD

**Issue by waab76** [Graylog2/graylog2-server#10908]
## Current Behavior
When clicking on an API in the API Browser, nothing happens.  It does not expand to show the list of operations as expected.

## Your Environment
This was reported from the 4.1 Sales/Support Preview Day environment.

**Comment by mpfz0r** [comment]
That's because the URL changes from e.g. `https://172.16.1.1:9000/api/api-browser` to `https://172.16.1.1:9000/api/api-browser/#!`
And that reloads the page, ignoring the `onClick` action.

Once you're on a URL with `/#!` it works.

**Comment by waab76** [comment]
I'm not seeing it work even after the `/#!` appears in the URL

https://user-images.githubusercontent.com/6466251/122955263-f584dd80-d34d-11eb-9fde-ff8332695f4b.mov

**Comment by mpfz0r** [comment]
hmm, works for me locally.

This looks like the reverse proxy is messing things up.
```
Internal Server Error
Reason

java.net.URISyntaxException: Illegal character in path at index 43: http://localhost:9000/api/api-docs/cluster/{nodeId}/shutdown
Stacktrace

java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 43: http://localhost:9000/api/api-docs/cluster/{nodeId}/shutdown
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:463)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:339)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in path at index 43: http://localhost:9000/api/api-docs/cluster/{nodeId}/shutdown
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.parseHierarchical(URI.java:3104)
	at java.net.URI$Parser.parse(URI.java:3052)
	at java.net.URI.<init>(URI.java:588)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:461)
	... 6 more


```

**Comment by juju2112** [comment]
This is the nginx configuration for the snapshot instance:

https://github.com/Graylog2/ci-infrastructure/blob/master/ansible/graylog-ansible-graylog-snapshot/templates/nginx.conf.j2

**Comment by juju2112** [comment]
I think this might be fixed now. I changed this line:

`                 proxy_pass           http://localhost:9000/;`

to:

`                 proxy_pass           http://localhost:9000;`


@waab76, can you try it again?

**Comment by waab76** [comment]
Working now, thanks!
