### ISSUE TITLE
Cannot launch input

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#1091]
Getting this when trying to launch input on current master:

```
[error] o.g.r.m.Node - Could not launch input 551b0766d4c6aa5a22095087
org.graylog2.restclient.lib.APIException: API call failed POST http://@127.0.0.1:12900/system/inputs/551b0766d4c6aa5a22095087/launch returned 500 Internal Server Error body: {"type":"ApiError","message":"A metric named org.graylog2.inputs.syslog.udp.SyslogUDPInput.551b0766d4c6aa5a22095087.written_bytes_total already exists"}
	at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:481) ~[graylog2-rest-client-1.1.0-SNAPSHOT.jar:na]
	at org.graylog2.restclient.models.Node.launchExistingInput(Node.java:302) ~[graylog2-rest-client-1.1.0-SNAPSHOT.jar:na]
	at controllers.InputsController.launch(InputsController.java:274) [classes/:2.3.6]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$50$$anonfun$apply$516.apply(routes_routing.scala:1750) [classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$50$$anonfun$apply$516.apply(routes_routing.scala:1750) [classes/:na]
```

**Comment by lennartkoopmann** [comment]
The input then however exists and is properly started.

**Comment by kroepke** [comment]
duplicate (or at least the same reason as) of #1069
