### ISSUE TITLE
Unable to connect using ldap

### ISSUE THREAD

**Issue by ovadm** [Graylog2/graylog2-server#1092]
hello, graylog v1.0.1 debian 7

ldap configuration is okay test user authentication passed, but when trying to login the web interface getting : Sorry, those credentials are invalid. I saw that it was reported as bug on earlier version but supposed to be solved for 1.0.1

```
 WARN  [SessionsResource] Unable to log in user ovadm
org.apache.shiro.authc.AuthenticationException: No account information found for authentication token [org.apache.shiro.authc.UsernamePasswordToken - ovadm, rememberMe=false] by this Authenticator instance.  Please check that it is configured correctly.
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:202)
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270)
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
        at org.graylog2.rest.resources.system.SessionsResource.newSession(SessionsResource.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by joschi** [comment]
@ovadm Which bug report are you referring to?

**Comment by fwdchrisull** [comment]
I had a similar issue when I did my install a couple of weeks ago.  Appending the domain after the username on the login page got me past it.  e.g. try "username@yourdomain.local" instead of just "username" on the login page. 

It is a bit of a pain because i have to give users more detailed login instructions.

**Comment by ovadm** [comment]
I am referring to #661 
Using user@domain did not solve the issue.

**Comment by fwdchrisull** [comment]
not just user@domain, that didn't work for me either. Try user@domain.com or .local, or whatever the FQDN is?

**Comment by ovadm** [comment]
Yes  - that's what I did, I opened wireshark and I can see the DC sending all the group I am member in and "Access enabled" but I am unable to connect.
did you configure the ldap qwery same as in the example :  (&(objectClass=user)(sAMAccountName={0})) or something else?
I tried few options with no success though I can see in wireshark that binding is successful.

**Comment by fwdchrisull** [comment]
When I had the issue it wasn't even making the call to the DC from the login page, only when I ran the test.  Must be the way your performing the look up.  Here's what I configured:

Search base DSN --> cn=users,dc=yourdomain,dc=local
Search Pattern --> (&(objectClass=user)(UserPrincipalName={0}))
Display name attribute --> displayName

hope this helps...

**Comment by ovadm** [comment]
no luck, though test passed ok. I will try to work it out with our AD experts.
Unable to log in user ovadm@corp.amdocs.com
org.apache.shiro.authc.AuthenticationException: No account information found for authentication token [org.apache.shiro.authc.UsernamePasswordToken - ovadm@corp.amdocs.com, rememberMe=false] by this Authenticator instance.  Please check that it is configured correctly.

**Comment by ovadm** [comment]
Solved with default setting as in the eample after restarting graylog-server service.
No need to add domain if using sAMcountName.

Thanks,
Ovad
