### ISSUE TITLE
Error editing heatmap aggregation

### ISSUE THREAD

**Issue by trogper** [Graylog2/graylog2-server#10967]
## Expected Behavior
When editing heatmap aggregation created in older graylog version, the gui should show editing dialog/form.

## Current Behavior
When editing heatmap aggregation created in older graylog version, the gui crashes with following error:
```
Cannot read property 'autoScale' of undefined

Stack Trace:

TypeError: Cannot read property 'autoScale' of undefined
    at fromConfig (https://graylog.domain.com/assets/app.4f3ef1e898f30873ecc4.js:2:988792)
    at am (https://graylog.domain.com/assets/app.4f3ef1e898f30873ecc4.js:2:1009439)
    at Object.fromConfig (https://graylog.domain.com/assets/app.4f3ef1e898f30873ecc4.js:2:1011795)
    at https://graylog.domain.com/assets/app.4f3ef1e898f30873ecc4.js:2:1040852
    at Array.reduce (<anonymous>)
    at https://graylog.domain.com/assets/app.4f3ef1e898f30873ecc4.js:2:1040796
    at Mg (https://graylog.domain.com/assets/app.4f3ef1e898f30873ecc4.js:2:1040876)
    at Zi (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:275335)
    at Ls (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:321385)
    at _c (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:314127)
    at mc (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:314052)
    at sc (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:311082)
    at https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:262723
    at exports.unstable_runWithPriority (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:771162)
    at Ua (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:262432)
    at Qa (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:262668)
    at Va (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:262603)
    at Oc (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:319610)
    at exports.unstable_runWithPriority (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:771162)
    at Ua (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:262432)
    at Ac (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:319262)
    at https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:319173
    at W (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:770011)
    at MessagePort.L.port1.onmessage (https://graylog.domain.com/assets/vendor.53480e037b0a599cf54a.js:2:768761)
```

## Possible Solution
delete the aggregation and create it again from scratch.

## Steps to Reproduce (for bugs)
1. install graylog 4.0.8
2. create heatmap aggregation
3. upgrade to graylog 4.1.0
4. try editing the heatmap aggregation

## Your Environment

* Graylog Version: 4.1.0
* Java Version: openjdk 11.0.11
* Elasticsearch Version: 6.8.16
* MongoDB Version: v4.2.14
* Operating System: Debian 10
* Browser version: Chrome 91.0.4472.106

**Comment by bernd** [comment]
Refs https://github.com/Graylog2/graylog2-server/issues/10928
