### ISSUE TITLE
Cannot connect to ElasticSearch

### ISSUE THREAD

**Issue by TheGameSquid** [Graylog2/graylog2-server#1097]
Previous issues regarding this issue seem to have been closed, the solutions given did not help me.

### Details

I am running:
* graylog-server 1.0.1
* ElasticSearch 1.5
* MongoDB 3.0
* CentOS Linux release 7.1.1503 (Core)

All of this is on the same development box. Each component was installed using the yum repos available for them (including graylog).

### The problem

Whenever I try to get my graylog-server instance running on my dev box, it fails to connect to my ElasticSearch instance.

I have configured it like this:
```
################################### Cluster ###################################

# Cluster name identifies your cluster for auto-discovery. If you're running
# multiple clusters on the same network, make sure you're using unique names.
#
cluster.name: graylog-dev
```

It seems to run just fine:

```
[2015-04-04 16:09:43,717][INFO ][node                     ] [graylog-dev-node1] version[1.5.0], pid[9557], build[5448160/2015-03-23T14:30:58Z]
[2015-04-04 16:09:43,717][INFO ][node                     ] [graylog-dev-node1] initializing ...
[2015-04-04 16:09:43,720][INFO ][plugins                  ] [graylog-dev-node1] loaded [], sites []
[2015-04-04 16:09:46,045][INFO ][node                     ] [graylog-dev-node1] initialized
[2015-04-04 16:09:46,045][INFO ][node                     ] [graylog-dev-node1] starting ...
[2015-04-04 16:09:46,157][INFO ][transport                ] [graylog-dev-node1] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.33.129:9300]}
[2015-04-04 16:09:46,171][INFO ][discovery                ] [graylog-dev-node1] graylog-dev/EgUpMih_Q2Kz3vWxrGJ4tw
[2015-04-04 16:09:49,944][INFO ][cluster.service          ] [graylog-dev-node1] new_master [graylog-dev-node1][EgUpMih_Q2Kz3vWxrGJ4tw][localhost.localdomain][inet[/192.168.33.129:9300]], reason: zen-disco-join (elected_as_master)
[2015-04-04 16:09:49,971][INFO ][gateway                  ] [graylog-dev-node1] recovered [0] indices into cluster_state
[2015-04-04 16:09:49,972][INFO ][http                     ] [graylog-dev-node1] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.33.129:9200]}
[2015-04-04 16:09:49,972][INFO ][node                     ] [graylog-dev-node1] started
```

I can query the REST API:
```
[robin@localhost graylog-server]$ curl -X GET http://127.0.0.1:9200
{
  "status" : 200,
  "name" : "graylog-dev-node1",
  "cluster_name" : "graylog-dev",
  "version" : {
    "number" : "1.5.0",
    "build_hash" : "544816042d40151d3ce4ba4f95399d7860dc2e92",
    "build_timestamp" : "2015-03-23T14:30:58Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

Furthermore, it seems to be bound to the right ports:
```
[robin@localhost graylog-server]$ netstat -tulnp
tcp6       0      0 :::9200                 :::*                    LISTEN      -
tcp6       0      0 :::9300                 :::*                    LISTEN      -
```

I have defined the correct cluster name in /etc/graylog/server/server.conf
```
# settings to be passed to elasticsearch's client (overriding those in the provided elasticsearch_config_file)
# all these
# this must be the same as for your Elasticsearch cluster
elasticsearch_cluster_name = graylog-dev
```

This is what I get when I start the graylog-server service
```
2015-04-05T07:02:41.253-07:00 WARN  [PluginLoader] Plugin directory /plugin does not exist, not loading plugins.
2015-04-05T07:02:41.256-07:00 INFO  [CmdLineTool] Loaded plugins: []
2015-04-05T07:02:41.305-07:00 INFO  [CmdLineTool] Running with JVM arguments: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:PermSize=128m -XX:MaxPermSize=256m -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Djava.library.path=/usr/share/graylog-server/lib/sigar -Dlog4j.configuration=file:///etc/graylog/server/log4j.xml
2015-04-05T07:02:43.391-07:00 INFO  [InputBufferImpl] Message journal is enabled.
2015-04-05T07:02:43.612-07:00 INFO  [LogManager] Found clean shutdown file. Skipping recovery for all logs in data directory '/usr/share/graylog-server/data/journal'
2015-04-05T07:02:43.612-07:00 INFO  [LogManager] Loading log 'messagejournal-0'
2015-04-05T07:02:43.635-07:00 INFO  [Log] Completed load of log messagejournal-0 with log end offset 0
2015-04-05T07:02:43.644-07:00 INFO  [KafkaJournal] Initialized Kafka based journal at /usr/share/graylog-server/data/journal
2015-04-05T07:02:43.650-07:00 INFO  [InputBufferImpl] Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
2015-04-05T07:02:43.789-07:00 INFO  [NodeId] Node ID: a6f7dded-cdbc-4afd-be6e-50f29a2b647c
2015-04-05T07:02:43.905-07:00 INFO  [node] [graylog2-server] version[1.3.7], pid[12772], build[3042293/2014-12-16T13:59:32Z]
2015-04-05T07:02:43.906-07:00 INFO  [node] [graylog2-server] initializing ...
2015-04-05T07:02:43.920-07:00 INFO  [plugins] [graylog2-server] loaded [graylog2-monitor], sites []
2015-04-05T07:02:46.000-07:00 INFO  [node] [graylog2-server] initialized
2015-04-05T07:02:46.023-07:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2015-04-05T07:02:46.975-07:00 INFO  [KieRepositoryImpl] KieModule was added:MemoryKieModule[ ReleaseId=org.graylog2:dynamic-rules:0]
2015-04-05T07:02:47.007-07:00 INFO  [KieRepositoryImpl] Adding KieModule from resource :[ByteArrayResource resource=[B@240906be]
2015-04-05T07:02:47.109-07:00 INFO  [KieRepositoryImpl] KieModule was added:MemoryKieModule[ ReleaseId=org.graylog2:dynamic-rules:0]
2015-04-05T07:02:47.330-07:00 INFO  [RulesEngineProvider] No static rules file loaded.
2015-04-05T07:02:47.400-07:00 INFO  [OutputBuffer] Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2015-04-05T07:02:47.819-07:00 INFO  [ServerBootstrap] Graylog server 1.0.1 (e1b89b8) starting up. (JRE: Oracle Corporation 1.7.0_75 on Linux 3.10.0-229.el7.x86_64)
2015-04-05T07:02:47.879-07:00 INFO  [PeriodicalsService] Starting 14 periodicals ...
2015-04-05T07:02:47.893-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ThroughputCounterManagerThread] periodical in [0s], polling every [1s].
2015-04-05T07:02:47.893-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.AlertScannerThread] periodical in [10s], polling every [60s].
2015-04-05T07:02:47.893-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] periodical in [0s], polling every [1s].
2015-04-05T07:02:47.894-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ClusterHealthCheckThread] periodical in [0s], polling every [20s].
2015-04-05T07:02:47.894-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ContentPackLoaderPeriodical] periodical, running forever.
2015-04-05T07:02:47.945-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.DeadLetterThread] periodical, running forever.
2015-04-05T07:02:47.948-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.GarbageCollectionWarningThread] periodical, running forever.
2015-04-05T07:02:47.949-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.IndexerClusterCheckerThread] periodical in [0s], polling every [30s].
2015-04-05T07:02:47.951-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRetentionThread] periodical in [0s], polling every [300s].
2015-04-05T07:02:47.979-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRotationThread] periodical in [0s], polling every [10s].
2015-04-05T07:02:47.980-07:00 INFO  [IndexRetentionThread] Elasticsearch cluster not available, skipping index retention checks.
2015-04-05T07:02:47.981-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.NodePingThread] periodical in [0s], polling every [1s].
2015-04-05T07:02:47.983-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.StreamThroughputCounterManagerThread] periodical in [0s], polling every [1s].
2015-04-05T07:02:47.999-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.VersionCheckThread] periodical in [0s], polling every [1800s].
2015-04-05T07:02:48.001-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
2015-04-05T07:02:48.034-07:00 INFO  [node] [graylog2-server] starting ...
2015-04-05T07:02:48.165-07:00 INFO  [Reflections] Reflections took 223 ms to scan 1 urls, producing 2 keys and 2 values
2015-04-05T07:02:49.187-07:00 INFO  [transport] [graylog2-server] bound_address {inet[/0:0:0:0:0:0:0:0:9350]}, publish_address {inet[/192.168.33.129:9350]}
2015-04-05T07:02:49.344-07:00 INFO  [discovery] [graylog2-server] graylog-dev/Del5q41eSqus7F-KdKhxzg
2015-04-05T07:02:49.713-07:00 WARN  [ClusterStateMonitor] No Elasticsearch data nodes in cluster, cluster is completely offline.
2015-04-05T07:02:52.374-07:00 WARN  [discovery] [graylog2-server] waited for 3s and no initial state was set by the discovery
2015-04-05T07:02:52.386-07:00 INFO  [node] [graylog2-server] started
2015-04-05T07:02:55.180-07:00 INFO  [RestApiService] Adding security context factory: <org.graylog2.security.ShiroSecurityContextFactory@5cb528d2>
2015-04-05T07:02:55.201-07:00 INFO  [RestApiService] Started REST API at <http://127.0.0.1:12900/>
2015-04-05T07:02:57.389-07:00 ERROR [UI]

################################################################################

ERROR: Could not successfully connect to Elasticsearch, if you use multicast check that it is working in your network and that Elasticsearch is running properly and is reachable. Also check that the clust
er.name setting is correct.

Need help?

* Official documentation: https://www.graylog.org/documentation/intro/
* Community support: https://www.graylog.org/community-support/
* Commercial support: https://www.graylog.com/support/

But we also got some specific help pages that might help you in this case:

* https://www.graylog.org/documentation/setup/elasticsearch/

Terminating. :(

################################################################################

2015-04-05T07:02:57.396-07:00 ERROR [ServiceManager] Service IndexerSetupService [FAILED] has failed in the STARTING state.
java.lang.IllegalStateException
        at org.graylog2.UI.exitHardWithWall(UI.java:36)
        at org.graylog2.initializers.IndexerSetupService.startUp(IndexerSetupService.java:171)
        at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
        at java.lang.Thread.run(Thread.java:745)
2015-04-05T07:02:57.405-07:00 ERROR [InputSetupService] Not starting any inputs because lifecycle is: Uninitialized<C2><A0>[LB:DEAD]
2015-04-05T07:02:57.411-07:00 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.AlertScannerThread].
2015-04-05T07:02:57.411-07:00 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.AlertScannerThread] complete, took <0ms>.
2015-04-05T07:02:57.411-07:00 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread].
2015-04-05T07:02:57.411-07:00 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] complete, took <0ms>.
2015-04-05T07:02:57.411-07:00 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.ClusterHealthCheckThread].
2015-04-05T07:02:57.411-07:00 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.ClusterHealthCheckThread] complete, took <0ms>.
2015-04-05T07:02:57.411-07:00 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.IndexerClusterCheckerThread].
2015-04-05T07:02:57.411-07:00 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.IndexerClusterCheckerThread] complete, took <0ms>.
2015-04-05T07:02:57.411-07:00 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.IndexRetentionThread].
2015-04-05T07:02:57.412-07:00 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.IndexRetentionThread] complete, took <0ms>.
2015-04-05T07:02:57.412-07:00 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.IndexRotationThread].
2015-04-05T07:02:57.412-07:00 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.IndexRotationThread] complete, took <0ms>.
2015-04-05T07:02:57.412-07:00 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.VersionCheckThread].
2015-04-05T07:02:57.412-07:00 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.VersionCheckThread] complete, took <0ms>.
2015-04-05T07:02:57.412-07:00 INFO  [PeriodicalsService] Shutting down periodical [org.graylog2.periodical.ThrottleStateUpdaterThread].
2015-04-05T07:02:57.412-07:00 INFO  [PeriodicalsService] Shutdown of periodical [org.graylog2.periodical.ThrottleStateUpdaterThread] complete, took <0ms>.
2015-04-05T07:02:57.412-07:00 INFO  [RestApiService] Shutting down REST API at <http://127.0.0.1:12900/>
2015-04-05T07:02:57.426-07:00 WARN  [BufferSynchronizerService] Elasticsearch is unavailable. Not waiting to clear buffers and caches, as we have no healthy cluster.
2015-04-05T07:02:57.436-07:00 INFO  [node] [graylog2-server] stopping ...
2015-04-05T07:02:57.436-07:00 INFO  [OutputSetupService] Stopping output org.graylog2.outputs.BlockingBatchedESOutput
2015-04-05T07:02:57.440-07:00 INFO  [JournalReader] Stopping.
2015-04-05T07:02:57.453-07:00 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2015-04-05T07:02:57.465-07:00 INFO  [node] [graylog2-server] stopped
2015-04-05T07:02:57.465-07:00 INFO  [node] [graylog2-server] closing ...
2015-04-05T07:02:57.475-07:00 INFO  [node] [graylog2-server] closed
2015-04-05T07:02:57.492-07:00 INFO  [ServiceManagerListener] Services are now stopped.
2015-04-05T07:02:57.492-07:00 ERROR [ServerBootstrap] Graylog startup failed. Exiting. Exception was:
java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {FAILED=[IndexerSetupService [FAILED]]}
        at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:710)
        at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:535)
        at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:301)
        at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:113)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:196)
        at org.graylog2.bootstrap.Main.main(Main.java:58)
2015-04-05T07:02:57.492-07:00 INFO  [Server] SIGNAL received. Shutting down.
2015-04-05T07:02:57.519-07:00 INFO  [GracefulShutdown] Graceful shutdown initiated.
2015-04-05T07:02:57.519-07:00 INFO  [GracefulShutdown] Node status: [Halting<C2><A0>[LB:DEAD]]. Waiting <3sec> for possible load balancers to recognize state change.
2015-04-05T07:03:01.524-07:00 INFO  [GracefulShutdown] Goodbye.
```

I have tried disabling multicast settings, like so:
```
# Unicast discovery allows to explicitly control which nodes will be used
# to discover the cluster. It can be used when multicast is not present,
# or to restrict the cluster communication-wise.
#
# 1. Disable multicast discovery (enabled by default):
#
discovery.zen.ping.multicast.enabled: false
#
# 2. Configure an initial list of master nodes in the cluster
#    to perform discovery when new nodes (master or data) are started:
#
discovery.zen.ping.unicast.hosts: ["localhost"]
```

But this had no impact on the results.

My ES cluster health has always been green:
```
[robin@localhost graylog-server]$ curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
{
  "cluster_name" : "graylog-dev",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "number_of_pending_tasks" : 0
}
```

**Comment by joschi** [comment]
Your Elasticsearch node published the IP address 192.168.33.129 but you restricted the Zen unicast discovery to localhost (127.0.0.1 or ::1) which won't work.

You could force ES to bind to 127.0.0.1 using the `network.host` setting (http://www.elastic.co/guide/en/elasticsearch/reference/1.x/modules-network.html). Additionally you'll have to disable Zen multicast discovery in Graylog as well if you did so in Elasticsearch (see https://github.com/Graylog2/graylog2-server/blob/1.0.1/misc/graylog2.conf#L167-168).

Also kindly use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or the [#graylog IRC channel on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general support questions.

**Comment by TheGameSquid** [comment]
Thanks for pointing out the correct place to post questions joschi. I apologise.
Configuring unicast in the graylog configuration file resolved my problems.

I would like to point out that the graylog error output when it cannot connect to ES mentions that you should look at the documentation found here: https://www.graylog.org/documentation/setup/elasticsearch/. However, while this page tells you how to change the ElasticSearch multicast configuration, it does not mention what you need to change in the graylog configuration. It might be interesting to include that. I had no idea I needed to change anything at all in the graylog config.

**Comment by joschi** [comment]
@TheGameSquid Good point regarding the documentation. Thanks for the update!

**Comment by hepin1989** [comment]
in my cause the e don't have enough memory ,so it can't start up.

**Comment by kentonbmax** [comment]
Should the docker hub image readme be updated since the docker commands do not work out of the box?

**Comment by joschi** [comment]
@kentonbmax Could you please elaborate?

The instructions work and the docs are up-to-date: http://docs.graylog.org/en/2.3/pages/installation/docker.html

**Comment by kentonbmax** [comment]
- Mongo:2 but your .yml files use :3.x image? Also there is an issue connecting to elastic search container through port 9200. An I believe you have to expose the udp ports on the graylog container for inputs to work. 

`Couldn't read cluster health for indices [graylog_*] (Could not connect to http://127.0.0.1:9200)`

**Comment by joschi** [comment]
@kentonbmax What instructions are you referring to?
