### ISSUE TITLE
syslog TLS input broken since 4.1.0

### ISSUE THREAD

**Issue by imrejonk** [Graylog2/graylog2-server#10997]
## Expected Behavior

After updating from Graylog Server 4.0.9 to 4.1.0 or 4.1.1, syslog TLS inputs should still function. Clients should still be provided with the server certificate when connecting to the syslog TCP port (6514 by default).

In other words, `openssl s_client` should report something like this:

```
imre@silicon:~$ openssl s_client -connect syslog.ciphermail.com:6514
CONNECTED(00000003)
depth=2 C = NL, O = CipherMail B.V., CN = CipherMail B.V. Internal Root CA
verify return:1
depth=1 C = NL, O = CipherMail B.V., CN = CipherMail B.V. Internal Domain CA
verify return:1
depth=0 CN = syslog.ciphermail.com
verify return:1
---
Certificate chain
 0 s:CN = syslog.ciphermail.com
   i:C = NL, O = CipherMail B.V., CN = CipherMail B.V. Internal Domain CA
 1 s:C = NL, O = CipherMail B.V., CN = CipherMail B.V. Internal Domain CA
   i:C = NL, O = CipherMail B.V., CN = CipherMail B.V. Internal Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIF0zCCA7ugAwIBAgIRAP5IjBgGd1KslaAGrHWm4tAwDQYJKoZIhvcNAQELBQAw
VDELMAkGA1UEBhMCTkwxGDAWBgNVBAoMD0NpcGhlck1haWwgQi5WLjErMCkGA1UE
AwwiQ2lwaGVyTWFpbCBCLlYuIEludGVybmFsIERvbWFpbiBDQTAeFw0yMDAyMTgw
ODQzNTFaFw0yMzAyMTcwODQzNTFaMCAxHjAcBgNVBAMTFXN5c2xvZy5jaXBoZXJt
YWlsLmNvbTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMCWfF7AoXvO
VkUWRXuQyGQAK1MElaFkUF9HKGJ/aNtM3d20201QUVpZBl/YlkRkPbda10f1J0Gk
Yd5OBvBnKvxd0GEGDpwVQPWndc7vLTxnEz478mXhLaSsFS6vcX/4nhU0YcLyWT2+
cH9repXww3BU6soUsgfvhTIdBbsB6ENyKY8gSt7o3hni4U8ZfN2A0S2cGhqdwEfc
pR6Oj+Y3K/MZbXVsEoZlTNVRRxmhXqqWKGAigsmG2Rs5Sf9VIW+ZXVtd/4Lnz0fY
sfCcWXkWIpUvz2f5QS7NjJS4PA88Htu5lPbIEl+FS4xlTt5I/I4t8D7ZbafX/gmS
XG4hgeMF6+9RMqcFSlp5LJN7AayPLDmEUBFIOFhYMUcbwPwv+1Fkt3wB7FaZHiyc
k9fhwO8CX0sCcns+Qr72np5BZzImkjoysvIa82KIVnNSs4p5unF4UTK+uyu/pPv5
4ldZoca6C13w0Nl3y7ZuthXgWIUnYYPC5syxWLzO+RLa+UN5LsBK6QIDAQABo4IB
UjCCAU4wQAYIKwYBBQUHAQEENDAyMDAGCCsGAQUFBzAChiRodHRwOi8vZG9tYWlu
LWNhLmNpcGhlcm1haWwubmV0L2NydC8wgYsGA1UdIwSBgzCBgIAUBW9V8puU4LJj
+taRe+UsOz0dViGhVqRUMFIxCzAJBgNVBAYTAk5MMRgwFgYDVQQKDA9DaXBoZXJN
YWlsIEIuVi4xKTAnBgNVBAMMIENpcGhlck1haWwgQi5WLiBJbnRlcm5hbCBSb290
IENBghAHC2XRqMcrlPa++cAt4sytMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYI
KwYBBQUHAwIGCCsGAQUFBwMBMA4GA1UdDwEB/wQEAwIFoDAdBgNVHQ4EFgQUno6C
EhYAC9XX4z8/TH/4DjrcdM4wIAYDVR0RBBkwF4IVc3lzbG9nLmNpcGhlcm1haWwu
Y29tMA0GCSqGSIb3DQEBCwUAA4ICAQCUDoOD0vSpCmIt3ToQQxJFDzM4+b6pRZ3N
GslI5EHzcMrcZfT+rfYUqbFB9taP3d+Gs7t+J9QUS+Y4/Mte+KjeUV8LB7DiBDF3
ud8jCZ+/DtUahQn9g1wcdhOJJ70e5kwfjshm2uO6VKaya+tc57jKXSm1d4pp9oLG
aF9deGbp1hDAPB/QBjh9126miTDQq9kAczb1CincMtgyhe1MSW+AjV25KcxBIqit
k/2zMPDp2UpfIkMisdKxj7ghaHbxnrSGAky7cpOLvZ2+SgciePh09wmqWXLaSIQm
gPURYLp0ibmQLmgbgvNr6O98rM314Elj6QuvnXlbt2tUkHfajt9U98GQaSF8HVE9
kLf571BhAlvk5kVnpmrXB8GW+DX73bKScK4+ohJyNDqogel1dfnZCHbN5LJBjNp5
Z+X1d7Ym7vu+fvmyULXHO4FIctygdHKyU+5OXGCRx0U9VtcBMYHaujDwkApeaimF
hRvUMglbeEcju6eLT3tz5OhTu/SklxF7oEA4lCXavXfn9a1sdkGBtYZPwOqH/H8m
DS4NneRhPoT7EWwT+leNxZWbNrpSBDur1S68OVyRsMmluYEED1/ca0Ai0BGT+0xM
7et5gqaYFeoPuuLrtMtwXV+Ht6MqH6iXAKdOpkHT8dZabmLAnoul50sUxmBBmBgJ
onSGVeapww==
-----END CERTIFICATE-----
subject=CN = syslog.ciphermail.com

issuer=C = NL, O = CipherMail B.V., CN = CipherMail B.V. Internal Domain CA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3709 bytes and written 393 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 3072 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

## Current Behavior

After updating to 4.1.0 or 4.1.1, the server certificate is no longer sent. Clients can no longer connect to the syslog TCP service. `openssl s_client` reports this:

```
imre@silicon:~$ openssl s_client -connect syslog.ciphermail.com:6514
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 313 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

## Steps to Reproduce (for bugs)

1. Run Graylog Server 4.0.9.
2. Configure an input for syslog over TLS, and configure some clients to send log traffic to this input.
3. Notice log messages coming in and `openssl s_client` reporting that all is well.
4. Update to Graylog Server 4.1.0 or 4.1.1 and restart the Graylog Server.
5. Notice that log messages are no longer coming in and that `openssl s_client` reports that no server certificate is being sent.

## Context

We ended up downgrading to 4.0.9 again. The Graylog 4.1.0 release notes don't mention any changes regarding the syslog TLS input, so unfortunately I can't point towards a certain change that caused this issue for us.

## Your Environment

* Graylog Version: 4.1.0, 4.1.1
* Java Version: OpenJDK 8 JRE 8u292-b10-0+deb9u1
* Elasticsearch Version: 6.8.17
* MongoDB Version: 4.2.14
* Operating System: Debian 9.13
* Browser version: Firefox ESR 78.11.0esr-1~deb10u1

**Comment by imrejonk** [comment]
Here are two log messages from Graylog 4.1.1 that might be useful:
```
2021-07-08T11:18:13.408+02:00 WARN  [AbstractTcpTransport] receiveBufferSize (SO_RCVBUF) for input SyslogTCPInput{title=syslog, type=org.graylog2.inputs.syslog.tcp.SyslogTCPInput, nodeId=651655b9-2dd9-404b-908a-8e56a3a766c4} (channel [id: 0x38b6a1aa, L:/0:0:0:0:0:0:0:0:6514]) should be 262144 but is 212992.
2021-07-08T11:18:13.680+02:00 WARN  [ChannelInitializer] Failed to initialize a channel. Closing: [id: 0xdebb5977, L:/2a00:1fb8:a17:6:0:0:1:9fa9:6514 - R:/2001:9a8:136:1:0:0:0:2:52562]
java.security.cert.CertificateParsingException: signed fields invalid
        at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1842) ~[?:1.8.0_292]
        at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195) ~[?:1.8.0_292]
        at sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:471) ~[?:1.8.0_292]
        at sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:356) ~[?:1.8.0_292]
        at java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:462) ~[?:1.8.0_292]
        at org.graylog2.plugin.inputs.transports.util.KeyUtil.loadCertificates(KeyUtil.java:111) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.util.KeyUtil.loadX509Certificates(KeyUtil.java:91) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$3.createSslEngine(AbstractTcpTransport.java:361) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$3.call(AbstractTcpTransport.java:337) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$3.call(AbstractTcpTransport.java:333) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.NettyTransport$1.initChannel(NettyTransport.java:105) ~[graylog.jar:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [graylog.jar:?]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [graylog.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) [graylog.jar:?]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) [graylog.jar:?]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [graylog.jar:?]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) [graylog.jar:?]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) [graylog.jar:?]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) [graylog.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502) [graylog.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417) [graylog.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474) [graylog.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [graylog.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [graylog.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [graylog.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [graylog.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

The last one is repeated many times.

The first message, about the receive buffer that should be 262144 but is 212992, is interesting. The Graylog web interface tells me that the receive buffer is set to 262144.

The second message tells me that it might be some certificate parsing issue. Here are the contents of the file at the tls_cert_file path:

```
-----BEGIN CERTIFICATE-----
MIIF0zCCA7ugAwIBAgIRAP5IjBgGd1KslaAGrHWm4tAwDQYJKoZIhvcNAQELBQAw
VDELMAkGA1UEBhMCTkwxGDAWBgNVBAoMD0NpcGhlck1haWwgQi5WLjErMCkGA1UE
AwwiQ2lwaGVyTWFpbCBCLlYuIEludGVybmFsIERvbWFpbiBDQTAeFw0yMDAyMTgw
ODQzNTFaFw0yMzAyMTcwODQzNTFaMCAxHjAcBgNVBAMTFXN5c2xvZy5jaXBoZXJt
YWlsLmNvbTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMCWfF7AoXvO
VkUWRXuQyGQAK1MElaFkUF9HKGJ/aNtM3d20201QUVpZBl/YlkRkPbda10f1J0Gk
Yd5OBvBnKvxd0GEGDpwVQPWndc7vLTxnEz478mXhLaSsFS6vcX/4nhU0YcLyWT2+
cH9repXww3BU6soUsgfvhTIdBbsB6ENyKY8gSt7o3hni4U8ZfN2A0S2cGhqdwEfc
pR6Oj+Y3K/MZbXVsEoZlTNVRRxmhXqqWKGAigsmG2Rs5Sf9VIW+ZXVtd/4Lnz0fY
sfCcWXkWIpUvz2f5QS7NjJS4PA88Htu5lPbIEl+FS4xlTt5I/I4t8D7ZbafX/gmS
XG4hgeMF6+9RMqcFSlp5LJN7AayPLDmEUBFIOFhYMUcbwPwv+1Fkt3wB7FaZHiyc
k9fhwO8CX0sCcns+Qr72np5BZzImkjoysvIa82KIVnNSs4p5unF4UTK+uyu/pPv5
4ldZoca6C13w0Nl3y7ZuthXgWIUnYYPC5syxWLzO+RLa+UN5LsBK6QIDAQABo4IB
UjCCAU4wQAYIKwYBBQUHAQEENDAyMDAGCCsGAQUFBzAChiRodHRwOi8vZG9tYWlu
LWNhLmNpcGhlcm1haWwubmV0L2NydC8wgYsGA1UdIwSBgzCBgIAUBW9V8puU4LJj
+taRe+UsOz0dViGhVqRUMFIxCzAJBgNVBAYTAk5MMRgwFgYDVQQKDA9DaXBoZXJN
YWlsIEIuVi4xKTAnBgNVBAMMIENpcGhlck1haWwgQi5WLiBJbnRlcm5hbCBSb290
IENBghAHC2XRqMcrlPa++cAt4sytMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYI
KwYBBQUHAwIGCCsGAQUFBwMBMA4GA1UdDwEB/wQEAwIFoDAdBgNVHQ4EFgQUno6C
EhYAC9XX4z8/TH/4DjrcdM4wIAYDVR0RBBkwF4IVc3lzbG9nLmNpcGhlcm1haWwu
Y29tMA0GCSqGSIb3DQEBCwUAA4ICAQCUDoOD0vSpCmIt3ToQQxJFDzM4+b6pRZ3N
GslI5EHzcMrcZfT+rfYUqbFB9taP3d+Gs7t+J9QUS+Y4/Mte+KjeUV8LB7DiBDF3
ud8jCZ+/DtUahQn9g1wcdhOJJ70e5kwfjshm2uO6VKaya+tc57jKXSm1d4pp9oLG
aF9deGbp1hDAPB/QBjh9126miTDQq9kAczb1CincMtgyhe1MSW+AjV25KcxBIqit
k/2zMPDp2UpfIkMisdKxj7ghaHbxnrSGAky7cpOLvZ2+SgciePh09wmqWXLaSIQm
gPURYLp0ibmQLmgbgvNr6O98rM314Elj6QuvnXlbt2tUkHfajt9U98GQaSF8HVE9
kLf571BhAlvk5kVnpmrXB8GW+DX73bKScK4+ohJyNDqogel1dfnZCHbN5LJBjNp5
Z+X1d7Ym7vu+fvmyULXHO4FIctygdHKyU+5OXGCRx0U9VtcBMYHaujDwkApeaimF
hRvUMglbeEcju6eLT3tz5OhTu/SklxF7oEA4lCXavXfn9a1sdkGBtYZPwOqH/H8m
DS4NneRhPoT7EWwT+leNxZWbNrpSBDur1S68OVyRsMmluYEED1/ca0Ai0BGT+0xM
7et5gqaYFeoPuuLrtMtwXV+Ht6MqH6iXAKdOpkHT8dZabmLAnoul50sUxmBBmBgJ
onSGVeapww==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIGLzCCBBegAwIBAgIQBwtl0ajHK5T2vvnALeLMrTANBgkqhkiG9w0BAQsFADBS
MQswCQYDVQQGEwJOTDEYMBYGA1UECgwPQ2lwaGVyTWFpbCBCLlYuMSkwJwYDVQQD
DCBDaXBoZXJNYWlsIEIuVi4gSW50ZXJuYWwgUm9vdCBDQTAeFw0xOTAzMjYxMzQw
MzRaFw0yOTAzMjMxMzQwMzRaMFQxCzAJBgNVBAYTAk5MMRgwFgYDVQQKDA9DaXBo
ZXJNYWlsIEIuVi4xKzApBgNVBAMMIkNpcGhlck1haWwgQi5WLiBJbnRlcm5hbCBE
b21haW4gQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC5fZt2jbN0
8619u50NZHV42lfs/AsuU4W4awSSyhpx0MsGEP3iaqxF9+lWmvc+QpiW28Qcjk18
0QE+CvV6mEmCJOSXJ/z+iZPxKj0E9TluZiIAOYxdpeGEIM0SdbexzX+prNRdoAoa
/SDbRzQqtpPj0KFKqT7wymQb6RnDJ87vEAPMa0NqWlLn7MLhgfWJlEWPmeL1narV
eipvsn5NtHx5fDTeWEscpOtS/zEo1b1byjgrGYpxZh2PGmfZc1yYbiXiLX9awtQ4
atkkPiV2+yhZEQXZcpwRM7c7bFouRpwmJz1/1W5ErL5/AAY01rkw5ctTnU18Zf0F
cxFoMyE/Z8E7xoUNtLNX4/GJiIohjrg/S7HlPh6/7+KvxVuFe09xD2Tq0gz81Gf5
omYJUSeNSQSxbMBAICuTrZ2waEVfujlXN3TtTzWiEL0fUQtmXZTl4Pa1of4G/gBI
jw4BVwa3h303OIWA95WmU1DvgQyz0RxCGVQVyE1t2XKKqB5zLEoS44ztLC7+jtPx
5kCtAN17L3TWKtPfUscPh3uzP9099AVwg0zIQuVvwsjA6ToffXttwjtverkwameG
8RoEAGvWnqSui6V/830jOerjFXm4mG/Za0VFNOYQQXsf5H+Uu0jM/ecnjMVnvi+j
MqrADZXj2Xsx9v48ylogzUARe95NFffDywIDAQABo4H+MIH7MD4GCCsGAQUFBwEB
BDIwMDAuBggrBgEFBQcwAoYiaHR0cDovL3Jvb3QtY2EuY2lwaGVybWFpbC5uZXQv
Y3J0LzAfBgNVHSMEGDAWgBSI844xpaQWZf+v2fnTY6qQV694iDASBgNVHRMBAf8E
CDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUBW9V8puU4LJj+taR
e+UsOz0dViEwVQYDVR0eBE4wTKBKMBCCDmNpcGhlcm1haWwubmV0MBGCDy5jaXBo
ZXJtYWlsLm5ldDAQgg5jaXBoZXJtYWlsLmNvbTARgg8uY2lwaGVybWFpbC5jb20w
DQYJKoZIhvcNAQELBQADggIBAG3QVlAAS00FlC5Vehvl63AEqmuWb4aIy7D3HpDb
bDvum/+xgFiGOgbZDDfeskerVwyZ7foY6LzoOZMXUY3lv5F7MlDKc2+7lH4fLU8a
SuPIWoYvwyEzIdbjoft4wRE7UuDfbYKO36qfHZFMM+Rn/D1RleuVmbg5FEwSvinv
xXQwgJgKNACWhp1ahZNmu3xyLIDvepE3IyDAloziRySww/K2GVnM2+phvIaIob4a
NQIK68WNj4t+Y6nIKWY+d02/gRp4WLhsD9Ue+18REZOPBCrNXmPvkrsI5GTjx6hC
3dQHdUClplWGywfZwUtaeLis9mdJDoXm32O1JM7Jl8xhfjantanQ0flRW+dSzOnM
dcbjgXxJ2LCO6iSWx3pk7iiMXDJMpMpw3cLsKAw4njS5x/zqcNLal+MS6BkagI+T
sYEDDyF/45SdMdLDJM9HZIocmBzu8Oj9sf4+onIyVE/RIoOvD9xaniUXzjfGfod2
HVQx1gFz7/n7Ul8ub6D/yWWOnFXHnBB1GI5fHzQQucHobOj5MYWqbAyd6qQB6pvc
wm13yZiDX1PyK8WP+1uITSP7p2NDalS0MBGbI5YKoFuTQex3vsHIB+Mw1lZXCYD7
2tGcAPeQ9LBK4EihxG3YSgggRNTEf//3U1ET5wr6Uo+ghzHv+FQCE9yGDSs8u6BX
NH4Y
-----END CERTIFICATE-----
-----BEGIN DH PARAMETERS-----
MIIBjAKCAYEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
+8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
ssbzSibBsu/6iGtCOGEfz9zeNVs7ZRkDW7w09N75nAI4YbRvydbmyQd62R0mkff3
7lmMsPrBhtkcrv4TCYUTknC0EwyTvEN5RPT9RFLi103TZPLiHnH1S/9croKrnJ32
nuhtK8UiNjoNq8Uhl5sN6todv5pC1cRITgq80Gv6U93vPBsg7j/VnXwl5B0rZsYu
N///////////AgECAgIBFA==
-----END DH PARAMETERS-----
```

**Comment by imrejonk** [comment]
Okay we found it! It turns out that Graylog 4.1.0+ does not like the DH parameters I added to the TLS certificate file. Removing them solved the issue for me. I hope you enjoyed this live debugging session :)

I still see the warning message about the receive buffer size though. On Graylog 4.0.9 the warning looks a bit different:

```
2021-07-08T11:32:09.501+02:00 WARN  [AbstractTcpTransport] receiveBufferSize (SO_RCVBUF) for input SyslogTCPInput{title=syslog, type=org.graylog2.inputs.syslog.tcp.SyslogTCPInput, nodeId=651655b9-2dd9-404b-908a-8e56a3a766c4} (channel [id: 0x230bf80b, L:/0:0:0:0:0:0:0:0%0:6514]) should be 262144 but is 425984.
```
