### ISSUE TITLE
Suppressed: org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=security_exception, reason=action [indices:data/read/search] is unauthorized for user [elastic] with roles [superuser], this action is granted by the index privileges [read,all]]

### ISSUE THREAD

**Issue by fengjian1993** [Graylog2/graylog2-server#11009]
## Expected Behavior
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: Unable to perform search query
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:136) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.firstResponseFrom(ElasticsearchClient.java:85) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.search(ElasticsearchClient.java:61) ~[?:?]
...
	Suppressed: org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=security_exception, reason=action [indices:data/read/search] is unauthorized for user [elastic] with roles [superuser], this action is granted by the index privileges [read,all]]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:496) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:407) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:469) ~[?:?]
...
Caused by: org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=string_index_out_of_bounds_exception, reason=String index out of range: 0]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:496) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:407) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:437) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:603) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.action.search.MultiSearchResponse.itemFromXContent(MultiSearchResponse.java:215) ~[?:?]

## Current Behavior
exception occure when go to alert page

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: Graylog server 4.2.0-SNAPSHOT
* Java Version: Oracle Corporation 1.8.0_271
* Elasticsearch Version: Elasticsearch cluster is running v7.13.2
* MongoDB Version:  latest
* Operating System: Windows 10 10.0
* Browser version: chrome latest

**Comment by fengjian1993** [comment]
i have opened security for elasticsearch via https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html#add-built-in-users
is there any relativity？ thanks!

**Comment by dennisoelkers** [comment]
It looks like your Elasticsearch user does not have the required permissions to search in the specified indices.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by fengjian1993** [comment]
> We are using GitHub issues for tracking bugs in Graylog itself

thanks for your kindly replay! could you please tell me what index does alert page query for? in my elasticsearch, seems no index about alert
![image](https://user-images.githubusercontent.com/48206006/125252779-53905980-e32b-11eb-84b8-2c77753c873e.png)
i am newer about graylog :) thanks again

**Comment by mpfz0r** [comment]
@fengjian1993 FYI: You shouldn't be using ES 7.13

https://docs.graylog.org/en/4.1/pages/installation.html#system-requirements

**Comment by fengjian1993** [comment]
> @fengjian1993 FYI: You shouldn't be using ES 7.13
> 
> https://docs.graylog.org/en/4.1/pages/installation.html#system-requirements

tried, now ok, many thanks
