### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#1106]
Hi,

Something weird is happening, from today on we have issues logging in to the dashboard. We have 2 nodes in AWS.
The error we are getting is : 
```
2015-04-10_11:37:07.94162 2015-04-10 11:37:07,940 WARN : org.graylog2.rest.resources.system.SessionsResource - Unable to log in user dashboard
2015-04-10_11:37:07.94164 org.apache.shiro.authc.AuthenticationException: No account information found for authentication token [org.apache.shiro.authc.UsernamePasswordToken - dashboard, rememberMe=false] by this Authenticator instance.  Please check that it is configured correctly.
2015-04-10_11:37:07.94165 	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:202)
2015-04-10_11:37:07.94165 	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
2015-04-10_11:37:07.94165 	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270)
2015-04-10_11:37:07.94165 	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
2015-04-10_11:37:07.94166 	at org.graylog2.rest.resources.system.SessionsResource.newSession(SessionsResource.java:95)
2015-04-10_11:37:07.94166 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-04-10_11:37:07.94166 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-04-10_11:37:07.94166 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-04-10_11:37:07.94167 	at java.lang.reflect.Method.invoke(Method.java:497)
2015-04-10_11:37:07.94167 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
2015-04-10_11:37:07.94167 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
2015-04-10_11:37:07.94168 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
2015-04-10_11:37:07.94168 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195)
2015-04-10_11:37:07.94168 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
2015-04-10_11:37:07.94168 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
2015-04-10_11:37:07.94168 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
2015-04-10_11:37:07.94169 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
2015-04-10_11:37:07.94169 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
2015-04-10_11:37:07.94169 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
2015-04-10_11:37:07.94170 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
2015-04-10_11:37:07.94170 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
2015-04-10_11:37:07.94170 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
2015-04-10_11:37:07.94170 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
2015-04-10_11:37:07.94170 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
2015-04-10_11:37:07.94171 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
2015-04-10_11:37:07.94171 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
2015-04-10_11:37:07.94172 	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
```
And sometimes the 2nd attempt works.... what is going wrong??

**Comment by joschi** [comment]
Please make sure that all nodes are using the same `password_secret` (https://github.com/Graylog2/graylog2-server/blob/1.0.1/misc/graylog2.conf#L9-11).

Also kindly use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or the [#graylog IRC channel on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general support questions.
