### ISSUE TITLE
Check file extensions to load as plugins

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#11122]
While investigating https://github.com/Graylog2/graylog2-server/issues/11107 with @edward-marrufo, we found that Graylog is loading a `.bak` file in the `plugin` directory during startup. This loaded an old plugin and created an issue on the search page.

## Expected Behavior
Graylog should only try to load jar files (or other file types if needed) in the plugin directory.

## Current Behavior
Graylog loads any file type in the plugin directory.

## Steps to Reproduce (for bugs)
1. Move an existing plugin in the `plugin` directory, changing its extension
2. Restart Graylog
3. Check log file and see that Graylog loaded renamed plugin

Alternatively:

1. Create a new text file in the `plugin` directory
2. Restart Graylog in debug mode
3. Check log file to see that Graylog tried to load the file:

```
2021-08-06T09:26:24.074Z DEBUG [PluginLoader] Loading <foobar.bak>
2021-08-06T09:26:24.115Z DEBUG [PluginProperties] Unable to load properties from plugin <foobar.bak>
java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_292]
        at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_292]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_292]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_292]
        at java.util.jar.JarFile.<init>(JarFile.java:103) ~[?:1.8.0_292]
        at org.graylog2.shared.plugins.PluginProperties.fromJarFile(PluginProperties.java:61) ~[graylog.jar:?]
        at org.graylog2.shared.plugins.PluginLoader.lambda$loadJarPlugins$1(PluginLoader.java:110) ~[graylog.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_292]
        at org.graylog2.shared.plugins.PluginLoader.loadJarPlugins(PluginLoader.java:109) [graylog.jar:?]
        at org.graylog2.shared.plugins.PluginLoader.loadPlugins(PluginLoader.java:65) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.loadPlugins(CmdLineTool.java:372) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:240) [graylog.jar:?]
        at org.graylog2.bootstrap.Main.main(Main.java:45) [graylog.jar:?]
2021-08-06T09:26:24.116Z DEBUG [PluginLoader] Creating isolated class loader for <file:/usr/share/graylog-server/plugin/foobar.bak>
```

## Context
This makes it more likely to accidentally load an older plugin, since it is not uncommon to create a backup of a file during testing or before upgrading.

## Your Environment
* Graylog Version: 4.1.3

**Comment by mcouillard** [comment]
Agreed; I got bit by this, too
