### ISSUE TITLE
graylog-server loses contact with elasticsearch; graylog-web fails to restart

### ISSUE THREAD

**Issue by durist** [Graylog2/graylog2-server#1126]
OS: Debian stable (wheezy)
Package versions:
 graylog-server 1.0.1-1
 graylog-web 1.0.1-1
 mongodb 1:2.4.8-2~bpo70+1
openjdk-7-jre:amd64 7u75-2.5.4-1~deb7u1

Configuration: 2-node elasticsearch cluster (v. 1.5.1); graylog-web/graylog-server/mongodb on a separate node

graylog-web is periodically crashing with errors like this:

```javascript
2015-04-21T22:16:15.430Z - [ERROR] - from org.graylog2.restclient.lib.ApiClient in servernodes-refresh-0
API call failed to execute.
java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: /127.0.0.1:12900 to http://127.0.0.1:12900/system/cluster/node
        at com.ning.http.client.providers.netty.NettyResponseFuture.abort(NettyResponseFuture.java:342) ~[com.ning.async-http-client-1.8.14.jar:na]
        at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:108) ~[com.ning.async-http-client-1.8.14.\
jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:431) ~[io.netty.netty-3.9.3.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:422) ~[io.netty.netty-3.9.3.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:384) ~[io.netty.netty-3.9.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109) ~[io.netty.netty-3.9.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[io.netty.netty-3.9.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) ~[io.netty.netty-3.9.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[io.netty.netty-3.9.3.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[io.netty.netty-3.9.3.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[io.netty.netty-3.9.3.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:12900 to http://127.0.0.1:12900/system/cluster/node
        at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:104) ~[com.ning.async-http-client-1.8.14.\
jar:na]
        ... 12 common frames omitted
Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:12900
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.7.0_75]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739) ~[na:1.7.0_75]
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[io.netty.netty-3.9.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[io.netty.netty-3.9.3.Final.jar:na]
        ... 8 common frames omitted
```

This seems to roughly correlate with graylog-server restarts, though there's no indication why graylog-server is restarting (note the two restarts; though graylog-server apparently does recover eventually):
```javascript
2015-04-21T21:31:03.109Z INFO  [CmdLineTool] Loaded plugins: []
2015-04-21T21:31:03.181Z INFO  [CmdLineTool] Running with JVM arguments: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:PermSize=256m -XX:MaxPermSize=512m -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -\
XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configuration=file:///etc/graylog/server/log4j.xml -Djava.library.pat\
h=/usr/share/graylog-server/lib/sigar
2015-04-21T21:31:05.303Z INFO  [InputBufferImpl] Message journal is enabled.
2015-04-21T21:31:05.596Z INFO  [LogManager] Loading log 'messagejournal-0'
2015-04-21T21:31:05.645Z INFO  [Log] Recovering unflushed segment 27100285 in log messagejournal-0.
2015-04-21T21:31:06.301Z INFO  [Log] Completed load of log messagejournal-0 with log end offset 27173306
2015-04-21T21:31:06.314Z INFO  [KafkaJournal] Initialized Kafka based journal at /var/lib/graylog-server/journal
2015-04-21T21:31:06.321Z INFO  [InputBufferImpl] Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
2015-04-21T21:31:06.480Z INFO  [NodeId] Node ID: 096ad5cc-a0d9-4310-9fbc-07f6dd223c75
2015-04-21T21:31:06.607Z INFO  [node] [graylog2-server] version[1.3.7], pid[24984], build[3042293/2014-12-16T13:59:32Z]
2015-04-21T21:31:06.607Z INFO  [node] [graylog2-server] initializing ...
2015-04-21T21:31:06.614Z INFO  [plugins] [graylog2-server] loaded [graylog2-monitor], sites []
2015-04-21T21:31:08.910Z INFO  [node] [graylog2-server] initialized
2015-04-21T21:31:08.927Z INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2015-04-21T21:31:10.485Z INFO  [KieRepositoryImpl] KieModule was added:MemoryKieModule[ ReleaseId=org.graylog2:dynamic-rules:0]
2015-04-21T21:31:10.537Z INFO  [KieRepositoryImpl] Adding KieModule from resource :[ByteArrayResource resource=[B@1e2dc38]
2015-04-21T21:31:10.631Z INFO  [KieRepositoryImpl] KieModule was added:MemoryKieModule[ ReleaseId=org.graylog2:dynamic-rules:0]
2015-04-21T21:31:10.895Z INFO  [RulesEngineProvider] No static rules file loaded.
2015-04-21T21:31:10.943Z INFO  [OutputBuffer] Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2015-04-21T21:31:11.323Z INFO  [ServerBootstrap] Graylog server 1.0.1 (e1b89b8) starting up. (JRE: Oracle Corporation 1.7.0_75 on Linux 3.2.68-vs2.3.2.17-beng)
2015-04-21T21:31:11.342Z INFO  [PeriodicalsService] Starting 14 periodicals ...
2015-04-21T21:31:11.343Z INFO  [Periodicals] Starting [org.graylog2.periodical.ThroughputCounterManagerThread] periodical in [0s], polling every [1s].
2015-04-21T21:31:11.343Z INFO  [Periodicals] Starting [org.graylog2.periodical.AlertScannerThread] periodical in [10s], polling every [60s].
2015-04-21T21:31:11.348Z INFO  [Periodicals] Starting [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] periodical in [0s], polling every [1s].
2015-04-21T21:31:11.350Z INFO  [Periodicals] Starting [org.graylog2.periodical.ClusterHealthCheckThread] periodical in [0s], polling every [20s].
2015-04-21T21:31:11.352Z INFO  [node] [graylog2-server] starting ...
2015-04-21T21:31:11.353Z INFO  [Periodicals] Starting [org.graylog2.periodical.ContentPackLoaderPeriodical] periodical, running forever.
2015-04-21T21:31:11.354Z INFO  [Periodicals] Starting [org.graylog2.periodical.DeadLetterThread] periodical, running forever.
2015-04-21T21:31:11.354Z INFO  [Periodicals] Starting [org.graylog2.periodical.GarbageCollectionWarningThread] periodical, running forever.
2015-04-21T21:31:11.355Z INFO  [Periodicals] Starting [org.graylog2.periodical.IndexerClusterCheckerThread] periodical in [0s], polling every [30s].
2015-04-21T21:31:11.356Z INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRetentionThread] periodical in [0s], polling every [300s].
2015-04-21T21:31:11.356Z INFO  [IndexRetentionThread] Elasticsearch cluster not available, skipping index retention checks.
2015-04-21T21:31:11.356Z INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRotationThread] periodical in [0s], polling every [10s].
2015-04-21T21:31:11.357Z INFO  [Periodicals] Starting [org.graylog2.periodical.NodePingThread] periodical in [0s], polling every [1s].
2015-04-21T21:31:11.358Z INFO  [Periodicals] Starting [org.graylog2.periodical.StreamThroughputCounterManagerThread] periodical in [0s], polling every [1s].
2015-04-21T21:31:11.358Z INFO  [Periodicals] Starting [org.graylog2.periodical.VersionCheckThread] periodical in [0s], polling every [1800s].
2015-04-21T21:31:11.359Z INFO  [Periodicals] Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
2015-04-21T21:31:11.539Z INFO  [transport] [graylog2-server] bound_address {inet[/0.0.0.0:9350]}, publish_address {inet[/128.117.224.121:9350]}
2015-04-21T21:31:11.545Z INFO  [discovery] [graylog2-server] dev.graylog/dO8bVkUMT1Ce8snsD4r7bQ
2015-04-21T21:31:11.550Z WARN  [ClusterStateMonitor] No Elasticsearch data nodes in cluster, cluster is completely offline.
2015-04-21T21:31:11.903Z INFO  [Reflections] Reflections took 494 ms to scan 1 urls, producing 2 keys and 2 values
2015-04-21T21:31:14.548Z WARN  [discovery] [graylog2-server] waited for 3s and no initial state was set by the discovery
2015-04-21T21:31:14.549Z INFO  [node] [graylog2-server] started
2015-04-21T21:31:14.608Z INFO  [service] [graylog2-server] detected_master [Xorr the God-Jewel][rj5t05ApQMCxHPZD9DrC2Q][dev.esearch.ucar.edu][inet[/128.117.224.119:9300]], added {[Ju\
de the Entropic Man][GCyd-zCPT0aNVAn6Z-6uHg][dev.esearch2.ucar.edu][inet[/128.117.224.96:9300]],[Xorr the God-Jewel][rj5t05ApQMCxHPZD9DrC2Q][dev.esearch.ucar.edu][inet[/128.117.224.1\
19:9300]],}, reason: zen-disco-receive(from master [[Xorr the God-Jewel][rj5t05ApQMCxHPZD9DrC2Q][dev.esearch.ucar.edu][inet[/128.117.224.119:9300]]])
2015-04-21T21:31:19.104Z INFO  [RestApiService] Adding security context factory: <org.graylog2.security.ShiroSecurityContextFactory@5a90ec97>
2015-04-21T21:31:19.123Z INFO  [RestApiService] Started REST API at <http://127.0.0.1:12900/>
2015-04-21T21:31:19.123Z INFO  [ServiceManagerListener] Services are healthy
2015-04-21T21:31:19.125Z INFO  [ServerBootstrap] Services started, startup times in ms: {OutputSetupService [RUNNING]=1, BufferSynchronizerService [RUNNING]=2, MetricsReporterService\
 [RUNNING]=2, GroovyShellSetupService [RUNNING]=3, InputSetupService [RUNNING]=3, JournalReader [RUNNING]=4, KafkaJournal [RUNNING]=6, PeriodicalsService [RUNNING]=19, DashboardRegis\
tryService [RUNNING]=86, IndexerSetupService [RUNNING]=3277, RestApiService [RUNNING]=7780}
2015-04-21T21:31:19.126Z INFO  [InputSetupService] Triggering launching persisted inputs, node transitioned from Uninitialized?[LB:DEAD] to Running?[LB:ALIVE]
2015-04-21T21:31:19.172Z INFO  [InputStateListener] Input [Syslog UDP/55087efde4b06f837ed1cad7] is now STARTING
2015-04-21T21:31:19.181Z INFO  [ServerBootstrap] Graylog server up and running.
2015-04-21T21:31:19.181Z INFO  [InputStateListener] Input [Syslog TCP/550880cee4b06f837ed1ccce] is now STARTING
2015-04-21T21:31:19.194Z WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for [id: 0xf7a07bc5, /0.0.0.0:5140] should be 1048576 but is 131071.
2015-04-21T21:31:19.195Z INFO  [InputStateListener] Input [Syslog TCP/550880cee4b06f837ed1ccce] is now RUNNING
2015-04-21T21:31:19.206Z INFO  [InputStateListener] Input [Syslog UDP/55087efde4b06f837ed1cad7] is now RUNNING
2015-04-21T21:31:19.477Z INFO  [Version] HV000001: Hibernate Validator 5.1.2.Final
2015-04-21T22:16:03.005Z INFO  [CmdLineTool] Loaded plugins: []
2015-04-21T22:16:03.073Z INFO  [CmdLineTool] Running with JVM arguments: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:PermSize=256m -XX:MaxPermSize=512m -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -\
XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configuration=file:///etc/graylog/server/log4j.xml -Djava.library.pat\
h=/usr/share/graylog-server/lib/sigar
2015-04-21T22:16:05.231Z INFO  [InputBufferImpl] Message journal is enabled.
2015-04-21T22:16:05.545Z INFO  [LogManager] Loading log 'messagejournal-0'
2015-04-21T22:16:05.630Z INFO  [Log] Recovering unflushed segment 27100285 in log messagejournal-0.
2015-04-21T22:16:06.753Z INFO  [Log] Completed load of log messagejournal-0 with log end offset 27228974
2015-04-21T22:16:06.767Z INFO  [KafkaJournal] Initialized Kafka based journal at /var/lib/graylog-server/journal
2015-04-21T22:16:06.773Z INFO  [InputBufferImpl] Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
2015-04-21T22:16:06.936Z INFO  [NodeId] Node ID: 096ad5cc-a0d9-4310-9fbc-07f6dd223c75
2015-04-21T22:16:07.069Z INFO  [node] [graylog2-server] version[1.3.7], pid[405], build[3042293/2014-12-16T13:59:32Z]
2015-04-21T22:16:07.069Z INFO  [node] [graylog2-server] initializing ...
2015-04-21T22:16:07.076Z INFO  [plugins] [graylog2-server] loaded [graylog2-monitor], sites []
2015-04-21T22:16:09.498Z INFO  [node] [graylog2-server] initialized
```
It seems the elasticsearch cluster is losing contact with graylog-server periodically, which I'm guessing is the root cause? This is from the elasticsearch log on one of the cluster nodes:

```javascript
[2015-04-21 21:31:14,598][INFO ][cluster.service          ] [Xorr the God-Jewel] added {[graylog2-server][dO8bVkUMT1Ce8snsD4r7bQ][dev.graylog\
.ucar.edu][inet[/128.117.224.121:9350]]{client=true, data=false, master=false},}, reason: zen-disco-receive(join from node[[graylog2-server][\
dO8bVkUMT1Ce8snsD4r7bQ][dev.graylog.ucar.edu][inet[/128.117.224.121:9350]]{client=true, data=false, master=false}])
[2015-04-21 22:15:34,067][INFO ][cluster.service          ] [Xorr the God-Jewel] removed {[graylog2-server][dO8bVkUMT1Ce8snsD4r7bQ][dev.grayl\
og.ucar.edu][inet[/128.117.224.121:9350]]{client=true, data=false, master=false},}, reason: zen-disco-node_failed([graylog2-server][dO8bVkUMT\
1Ce8snsD4r7bQ][dev.graylog.ucar.edu][inet[/128.117.224.121:9350]]{client=true, data=false, master=false}), reason transport disconnected
[2015-04-21 22:16:15,561][INFO ][cluster.service          ] [Xorr the God-Jewel] added {[graylog2-server][R2XEXSsoQTKecSKMu1vbGA][dev.graylog\
.ucar.edu][inet[/128.117.224.121:9350]]{client=true, data=false, master=false},}, reason: zen-disco-receive(join from node[[graylog2-server][\
R2XEXSsoQTKecSKMu1vbGA][dev.graylog.ucar.edu][inet[/128.117.224.121:9350]]{client=true, data=false, master=false}])
```

It appears graylog-web is failing to restart because the process is checking for the existence of a PID file, then erroring out if it finds one, even if the process isn't running. There are entries in the console log like this:

```javascript
This application is already running (Or delete /var/run/graylog-web/application.pid file).
```

There is code in the Debian package init script to check for the existence of the PID file and whether the process is actually running, but since it doesn't delete a bogus PID file, it will be subverted by the check in the process itself. I'm unclear whether the attempted restarts are happening via the init script (I suspect not?).

So, I think there are really two issues here: 

First, why is the elasticsearch cluster periodically losing contact with graylog-server, which (I am guessing) causes graylog-server to restart, and (presumably) triggers a restart of graylog-web, which fails?

Second, the PID file check in the graylog-web process should not error out if the PID file contains a bogus PID.

**Comment by neilferreira** [comment]
I ran into this issue continuously and could never come up with the answer to this,  I've ended up doing a fresh install of Graylog on a brand new EC2 VM and it has been more stable ever since.   The worst part of this is that it appear as if everything is ok but you end up losing your logging information from the period in which it loses contact.

I think this desperately needs to be fixed!

**Comment by joschi** [comment]
```
2015-04-21T21:31:19.477Z INFO  [Version] HV000001: Hibernate Validator 5.1.2.Final
2015-04-21T22:16:03.005Z INFO  [CmdLineTool] Loaded plugins: []
```
There's almost an hour gap between those messages, the second one being the first message of a (re-) starting Graylog server.

Did you check you other system logs, if an external process (e. g. the kernel OOM killer) killed the `java` process running Graylog?

**Comment by durist** [comment]
I've had a little bit more time to debug this.  I've also upgraded to v.1.0.2-1 (current debian packages). The behavior is repeatable, and what's happening is this:

1) Start gray-log server (/etc/init.d/graylog-server start). 
It appears to start correctly, and the elasticsearch cluster status (via curl to _cluster/health?pretty=true on one of the elasticsearch nodes) now shows three nodes in the cluster, with two data nodes.

graylog-server appears to be up and listening; I can curl to http://127.0.0.1:12900/system/cluster/node and I get this:
```javascript
{"id":"5508606be4b03e6a21a8b95c","transport_address":"http://127.0.0.1:12900/","short_node_id":"096ad5cc"
,"last_seen":"2015-05-12T19:07:38.000Z","type":"SERVER","node_id":"096ad5cc-a0d9-4310-9fbc-07f6dd223c75",
"is_master":true}
```

2) Start graylog-web (/etc/init.d/graylog-web start). graylog-web immediately throws errors like this in its application.log:
```javascript
2015-05-12T19:13:56.345Z - [INFO] - from play in main 
Application started (Prod)

2015-05-12T19:13:56.542Z - [INFO] - from play in main 
Listening for HTTP on /127.0.0.1:9000

2015-05-12T19:14:16.029Z - [ERROR] - from org.graylog2.restclient.lib.ApiClient in servernodes-refresh-0 
API call failed to execute.
java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: /127.0.0.1:12900 to http://127.0.0.1:12900/system/cluster/node

```
Then, graylog-server dies (or is killed by graylog-web???), with no messages in its logs.

**Comment by joschi** [comment]
> Then, graylog-server dies (or is killed by graylog-web???), with no messages in its logs.

Are there any messages in your system logs or the kernel log? The kernel OOM killer usually leaves a detailed explanation in the kernel log which processes it killed.

**Comment by bernd** [comment]
Closing this. Please re-open if you still see the problem with 1.1 or the upcoming 1.2. Thank you!
