### ISSUE TITLE
One of two nodes is constantly out of service

### ISSUE THREAD

**Issue by khadersyed** [Graylog2/graylog2-server#1139]
Not sure, what's happening or why it's running out of heap space:

```
2015-05-02 12:15:38,401 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception in transport layer. This is likely a bug, closing channel.
java.lang.OutOfMemoryError: Java heap space
2015-05-02 12:15:55,933 WARN : org.jboss.netty.channel.socket.nio.AbstractNioSelector - Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: Java heap space
2015-05-02 12:15:57,483 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception in transport layer. This is likely a bug, closing channel.
java.lang.OutOfMemoryError: Java heap space
2015-05-02 12:16:04,905 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception in transport layer. This is likely a bug, closing channel.
java.lang.OutOfMemoryError: Java heap space
Exception in thread "restapi-execution-handler-13799" java.lang.OutOfMemoryError: Java heap space
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "scheduled-daemon-2"

Exception in thread "restapi-boss-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "metrics-meter-tick-thread-2" java.lang.OutOfMemoryError: Java heap space
Exception in thread "restapi-execution-handler-13803" java.lang.OutOfMemoryError: Java heap space
Exception in thread "udp-transport-worker-0" java.lang.OutOfMemoryError: Java heap space
2015-05-02 12:16:35,218 WARN : org.jboss.netty.channel.socket.nio.AbstractNioSelector - Failed to accept a connection.
2015-05-02 12:16:36,685 WARN : org.jboss.netty.channel.socket.nio.AbstractNioSelector - Unexpected exception in the selector loop.
2015-05-02 12:16:36,685 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception in transport layer. This is likely a bug, closing channel.
2015-05-02 12:20:02,913 WARN : org.jboss.netty.channel.DefaultChannelPipeline - An exception was thrown by a user handler while handling an exception event ([id: 0x41e7019a, /xx.x.x.xxx:51141 :> /x.xx.x.xx:12900] EXCEPTION: java.lang.OutOfMemoryError: Java heap space)
2015-05-02 12:20:04,483 WARN : org.jboss.netty.channel.DefaultChannelPipeline - An exception was thrown by a user handler while handling an exception event ([id: 0xb6f3668b, /x.x.x.xxx:50240 :> /x.xx.x.xx:12900] EXCEPTION: java.lang.OutOfMemoryError: Java heap space)
java.lang.OutOfMemoryError: Java heap space
2015-05-02 12:20:11,317 WARN : org.jboss.netty.channel.DefaultChannelPipeline - An exception was thrown by a user handler while handling an exception event ([id: 0x41e7019a, /xxx.xxx.xx:51141 :> /xx.xxx.x.xx:12900] EXCEPTION: java.lang.OutOfMemoryError: Java heap space)
java.lang.OutOfMemoryError: Java heap space
2015-05-02 12:20:33,535 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception in transport layer. This is likely a bug, closing channel.
java.lang.OutOfMemoryError: Java heap space
2015-05-02 12:21:07,503 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception in transport layer. This is likely a bug, closing channel.
java.lang.OutOfMemoryError: Java heap space
```

I recently updated the config. Relevant parts here:
```
output_batch_size = 1000
output_flush_interval = 1
processbuffer_processors = 20
outputbuffer_processors = 20
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = data/journal
message_journal_max_age = 12h
message_journal_max_size = 5gb
dead_letters_enabled = false
lb_recognition_period_seconds = 3
stream_processing_timeout = 5000
stream_processing_max_faults = 0
```

Let me know if you need any other info.

```
$ free
             total       used       free     shared    buffers     cached
Mem:      61821328    7048576   54772752          0     341276    2558260
-/+ buffers/cache:    4149040   57672288
Swap:      7333664       7876    7325788
```

**Comment by joschi** [comment]
Unfortunately the JVM can't recover from an OutOfMemoryError, so once an OutOfMemoryError occurred, it's just repeating that error message.

Can you find the first occurrence of the OutOfMemoryError in your Graylog logs?

Please also elaborate a little bit on your setup (hardware specs, Graylog JVM startup parameters, etc.).

**Comment by khadersyed** [comment]
This is a c3.8xlarge instance type, with 32vCPU, 60GiB RAM.

And these are the runtime parameters:

```
-Djava.library.path=./bin/../lib/sigar -Xms1g -Xmx1g -XX:NewRatio=1 -XX:PermSize=128m -XX:MaxPermSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow
```

And the first OutOfMemoryError in the last week

```
2015-05-02 11:06:16,771 WARN : org.graylog2.shared.buffers.InputBufferImpl - Unable to process eve
nt <invalid>, sequence 102638748
java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:331)
        at kafka.message.ByteBufferMessageSet$.kafka$message$ByteBufferMessageSet$$create(ByteBufferMessageSet.scala:34)
        at kafka.message.ByteBufferMessageSet.<init>(ByteBufferMessageSet.scala:106)
        at kafka.message.ByteBufferMessageSet.<init>(ByteBufferMessageSet.scala:110)
        at org.graylog2.shared.journal.KafkaJournal.write(KafkaJournal.java:377)
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:62)
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:36)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by joschi** [comment]
You could try giving Graylog a little more heap space to start with. For this you need to change the `-Xms` and `-Xmx` parameters in the JVM parameters, e. g. to `-Xms2g -Xmx2g` for a heap space of 2 gigabytes.

**Comment by khadersyed** [comment]
Updated the server to use Xms2g and Xmx2g. Will monitor and see how this goes. 

No other change required, you think?

**Comment by joschi** [comment]
Depending on your message throughput you could try decreasing `processbuffer_processors ` and `outputbuffer_processors` to reduce cache thrashing.

**Comment by khadersyed** [comment]
graylog has been stable for the last 4 days without any issues. this is looking good. thanks :)
