### ISSUE TITLE
Deleting Kafka works but shows an error message

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1171]
Deleting a Kafka input works but shows an error message in the web inteface because it runs into a timeout.

![rp0odajqoeyaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/461/7769381/56839e2c-0083-11e5-8d6a-7c3a38387d3b.png)

```
[error] o.g.r.l.ApiClient - REST call failed
java.util.concurrent.TimeoutException: No response received after 5000
        at com.ning.http.client.providers.netty.NettyResponseFuture.get(NettyResponseFuture.java:260) ~[async-http-client-1.8.14.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:435) ~[graylog2-rest-client-1.1.0-beta.3-SNAPSHOT.jar:na]
        at org.graylog2.restclient.models.Node.terminateInput(Node.java:322) [graylog2-rest-client-1.1.0-beta.3-SNAPSHOT.jar:na]
        at controllers.InputsController.terminate(InputsController.java:370) [classes/:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$51$$anonfun$apply$593.apply(routes_routing.scala:2018) [classes/:na]
[error] o.g.r.m.Node - Could not terminate input 555f0d79c830648bac67b2d9
org.graylog2.restclient.lib.APIException: API call failed DELETE http://@127.0.0.1:12900/system/inputs/555f0d79c830648bac67b2d9
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:451) ~[graylog2-rest-client-1.1.0-beta.3-SNAPSHOT.jar:na]
        at org.graylog2.restclient.models.Node.terminateInput(Node.java:322) ~[graylog2-rest-client-1.1.0-beta.3-SNAPSHOT.jar:na]
        at controllers.InputsController.terminate(InputsController.java:370) [classes/:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$51$$anonfun$apply$593.apply(routes_routing.scala:2018) [classes/:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$51$$anonfun$apply$593.apply(routes_routing.scala:2018) [classes/:na]
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: No response received after 5000
        at com.ning.http.client.providers.netty.NettyResponseFuture.get(NettyResponseFuture.java:266) ~[async-http-client-1.8.14.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:435) ~[graylog2-rest-client-1.1.0-beta.3-SNAPSHOT.jar:na]
        at org.graylog2.restclient.models.Node.terminateInput(Node.java:322) ~[graylog2-rest-client-1.1.0-beta.3-SNAPSHOT.jar:na]
        at controllers.InputsController.terminate(InputsController.java:370) [classes/:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$51$$anonfun$apply$593.apply(routes_routing.scala:2018) [classes/:na]
Caused by: java.util.concurrent.TimeoutException: No response received after 5000
        at com.ning.http.client.providers.netty.NettyResponseFuture.get(NettyResponseFuture.java:260) ~[async-http-client-1.8.14.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:435) ~[graylog2-rest-client-1.1.0-beta.3-SNAPSHOT.jar:na]
        at org.graylog2.restclient.models.Node.terminateInput(Node.java:322) ~[graylog2-rest-client-1.1.0-beta.3-SNAPSHOT.jar:na]
        at controllers.InputsController.terminate(InputsController.java:370) [classes/:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$51$$anonfun$apply$593.apply(routes_routing.scala:2018) [classes/:na]
```

This is because the Kafka consumer threads are blocking and are only terminated after a 5 second timeout. Since the REST client also has a default timeout of 5 seconds, it is running into this.

**Comment by bernd** [comment]
Closed via 60bfcdf.
