### ISSUE TITLE
NPE in MongoProbe with MongoDB replica set 

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#1195]
This error occurs when running Graylog with a 3 node MongoDB replica set. (MongoDB 2.6):
```
2015-05-29T16:30:54.618Z ERROR [UsageStatsClusterPeriodical] Uncaught exception in periodical
java.lang.NullPointerException: Null hostInfo
	at org.graylog2.system.stats.mongo.AutoValue_MongoStats.<init>(AutoValue_MongoStats.java:32)
	at org.graylog2.system.stats.mongo.MongoStats.create(MongoStats.java:49)
	at org.graylog2.system.stats.mongo.MongoProbe.mongoStats(MongoProbe.java:227)
	at org.graylog2.system.stats.ClusterStatsService.mongoStats(ClusterStatsService.java:92)
	at org.graylog.plugins.usagestatistics.collectors.MongoCollector.getMongoStats(MongoCollector.java:36)
	at org.graylog.plugins.usagestatistics.collectors.ClusterCollector.buildClusterStats(ClusterCollector.java:82)
	at org.graylog.plugins.usagestatistics.collectors.ClusterCollector.getClusterDataSet(ClusterCollector.java:74)
	at org.graylog.plugins.usagestatistics.UsageStatsClusterService$1.get(UsageStatsClusterService.java:52)
	at org.graylog.plugins.usagestatistics.UsageStatsClusterService$1.get(UsageStatsClusterService.java:49)
	at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:192)
	at org.graylog.plugins.usagestatistics.UsageStatsClusterService.buildClusterDataSet(UsageStatsClusterService.java:58)
	at org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical.buildPayload(UsageStatsClusterPeriodical.java:87)
	at org.graylog.plugins.usagestatistics.UsageStatsPeriodical.doRun(UsageStatsPeriodical.java:80)
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bernd** [comment]
Closed in #1202
