### ISSUE TITLE
Cache rDNS results to improve throughput

### ISSUE THREAD

**Issue by defnull** [Graylog2/graylog2-server#11977]
## What?
Cache the results of rDNS lookups to reduce resolver overhead and improve throughput.

## Why?
Currently Graylog calls `InetAddress.getCanonicalHostName()` for every single event if rDNS is enabled for an input. Java has no built-in cache for these requests and calls down to the operating system every single time. This introduces significant overhead and limits throughput, even with a caching resolver running on localhost.

In our tests we saw less than 1k events per second average throughput and a full processing buffer, while input and output buffers were empty and the CPU was idling. We investigated and found that all `processbufferprocessor` threads were blocked within `Inet6AddressImpl.getHostByAddr()` most of the time. Increasing pool size did not help much. After installing as local resolver witch caching enabled, throughput was much better, but still clearly and severely bottle-necked by rDNS. Disabling rDNS more than doubled throughput.

This seems like an obvious and very rewarding opportunity to introduce an internal caching layer. There is usually a limited number of hosts logging to Graylog, so even a small cache with a short retention time would have an incredible hit-rate. I'm a little surprised that this was not done already.

Here is the stacktrace of the blocking calls:

        at java.net.Inet6AddressImpl.getHostByAddr(java.base@11.0.12/Native Method)
        at java.net.InetAddress$PlatformNameService.getHostByAddr(java.base@11.0.12/InetAddress.java:935)
        at java.net.InetAddress.getHostFromNameService(java.base@11.0.12/InetAddress.java:659)
        at java.net.InetAddress.getCanonicalHostName(java.base@11.0.12/InetAddress.java:632)
        at org.graylog2.plugin.Tools.rdnsLookup(Tools.java:310)
        at org.graylog2.inputs.codecs.SyslogCodec.parseHost(SyslogCodec.java:197)
        at org.graylog2.inputs.codecs.SyslogCodec.parse(SyslogCodec.java:145)
        at org.graylog2.inputs.codecs.SyslogCodec.decode(SyslogCodec.java:96)
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:153)
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:94)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:90)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:47)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143)
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
        at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)

## Your Environment

* Graylog Version: 4.1.11
* Operating System: Debian 11

**Comment by dennisoelkers** [comment]
Hey @defnull,

we have already considered this some time ago and came to the conclusion that implementing this could either result in reimplementing the DNS protocol (when considering refresh/expiration times from the responses) or JVM's own [name service caching](https://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html). Our expectation is that in most cases a local caching resolver would be the best way to speed this up while retaining correctness of results. Maybe you can experiment with tuning both and find out if there is some unrealized potential.

Another thing you can do is realize reverse lookups through pipelines and a DNS lookup table. Caching is local and configurable there. If this results in performance improvements magnitudes above of what you can do with JVM settings and/or tuning the local resolver, we should revisit a DNS caching layer though.

**Comment by defnull** [comment]
AFAIK the JVM does not cache reverse dns lookups, only forward lookups. The default of 30 seconds is not applied to reverse lookups. This matches my observations: the local resolver cache statistics show thousands of hits per second and the resolver process eats up 2 CPUs just answering cached results when Graylog is under pressure.

I understand that correctness is important, but DNS ttl is usually in the range of minutes or hours, not seconds. A ttl below 30s is considered bad practice and should be extremely rare. So, in most scenarios a 'stupid' cache with a fixed retention time of one seconds would be perfectly fine and still reduce rDNS lookups from "one lookup per event" to "one lookup per host per second". 

A special case would be a ttl of zero (no caching allowed) but this should only be possible in very specialized scenarios. I cannot imagine a real-world scenario where this would be a good idea, but if that's a concern, make the cache optional?

**Comment by defnull** [comment]
Same test, this time looking at metrics `org.graylog2.inputs.codecs.SyslogCodec.decodeTime` and `resolveTime`. Note that `decodeTime` includes `resolveTime` (resolving is part of decoding) so both should go down. 

| Metric  | Current | Patched |
| ------------- | ------------- |
| `decodeTime` (mean) | 33μs | 11μs |
| `resolveTime` (mean) | 32μs | 0μs |

In the current implementation, decode time for Syslog messages is absolutely dominated by resolving rDNS hostnames. Again, this is with a local resolver cache. Without one, we would see results an order of magnitude worse than that.
In the patched version, resolve time is so low it is barely measurable and decoding time is down to one third of the original. 

On first glace, these numbers do not add up. Resolve time is included in decode time, so the raw message parsing time (decoding without resolving) seems to go up from 1μs to 11μs in the patched version. This is actually correct. Parsing is CPU bound and CPUs were idling in the unpatched test, so parsing was fast. In the patched version however, throughput was 6 times as much, all CPUs were busy and throughput was limited by CPU, not IO. Most of CPU was used by elasticsearch. With a separate cluster these numbers should be even more promising.

**Comment by defnull** [comment]
Digging more, there is also a small bug in `SyslogCodec.parseHost()`: `Tools.rdnsLookup()` never throws `UnknownHostException` but returns the string representation of the IP on DNS errors. The code accidentally behaves correct and the catch block with the log line can be removed without changing functionality. Good thing it is that way, because having a `warn` level log line in a hot path would be bad. I first thought my trivial caching approach would be incorrect in case of DNS errors, but turns out, it is not.

**Comment by dennisoelkers** [comment]
Hey @defnull,

thanks for the extensive tests. The numbers look really promising and I think we should work on this. It could be optional and disabled by default. Also, we should allow the user to configure the default caching time, so we can avoid errors due to caching being too aggressive.

**Comment by defnull** [comment]
Great! But these numbers are with a cache time of just 1 second. I do not really see a need to reduce or increase this parameter. Increasing caching time should not have much of an effect. One query per host per second should be fine, even without a local resolver cache. Decreasing it even further also seems useless. Users that need sub-second correctness for rDNS should disable caching completely. A simple yes/no config parameter should be fine.

Cache size however might be interesting. The cache should be large enough to fit all active hosts. The optimal size is different for each environment.

I'd also say one-second caching is 'correct and safe enough' to make it the new default and get some free throughput out of the box. But that's on you. I'm just happy I can eventually enable this and not worry about log storms clogging the processing pipeline for several hours anymore. Thanks for considering this change!

**Comment by defnull** [comment]
Real world example. Graph shows a log-storm from a misbehaving server. I applied the patch to our production system and restarted Graylog. Nothing else changed. This is really nice, I'm keeping this workaround until the change officially lands in Graylog.

![image](https://user-images.githubusercontent.com/62740/150652858-335113aa-af23-4e39-97d7-18deb98f8575.png)

**Comment by defnull** [comment]
Any news on this? I am currently patching every new Graylog release with a custom implementation of `Tools.class` to get some decent throughput. There is no Plugin API to achieve the same or I would have written a plugin already. The Pipeline workaround is not really feasible, because rDNS lookups return a value with a tailing `.` and cleaning that up properly or handling unresolvable IPs introduces some absurd amount of overhead. We also do not use pipelines yet (because of their limitations) and missing Plugin support.
