### ISSUE TITLE
Server 1.1.RC3 Errors on search results pages that have results

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-server#1212]
On searches that would have no results, everything works fine - no results page.

In any search that had results an error occurs.  This does not occur if I revert Graylog server to 1.1.RC1 but leave the web-interface at 1.1.RC3.  I have redownloaded and reinstalled -- still broken. And rebuilt the graylog.conf file from the RC3 graylog.conf.example file as well to test rather than copying previous configs -- still broken.

UPDATE - Might be a corner case bug related to our data, it goes away if I add a Random HTTP data, then the search works.  But if I do a search that would have the other test data in the system and exclude the Random HTTP Input I started up it crashes again.  This is not present when I use the RC 1.1.RC1 release.

Oops, an error occured
This exception has been logged with id 6mc0ijce2.

2015-06-03 17:29:28,629 [play-akka.actor.default-dispatcher-42] ERROR play - Cannot invoke the action, eventually got an error: java.lang.NullPointerException
2015-06-03 17:29:28,630 [play-akka.actor.default-dispatcher-42] ERROR application -

! @6mc0ijce2 - Internal server error, for (GET) [/search?rangetype=relative&fields=message%2Csource&width=1419&relative=1209600&q=] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
        at play.api.Application$class.handleError(Application.scala:296) 

...much more stacktrace.

**Comment by kroepke** [comment]
Unfortunately it is the "more stacktrace" that contains the interesting information.
Could you please update the issue with that?

**Comment by NickMeves** [comment]
2015-06-03 17:29:28,629 [play-akka.actor.default-dispatcher-42] ERROR play - Can
not invoke the action, eventually got an error: java.lang.NullPointerException2015-06-03 17:29:28,630 [play-akka.actor.default-dispatcher-42] ERROR applicatio
n -
! @6mc0ijce2 - Internal server error, for (GET) [/search?rangetype=relative&fields=message%2Csource&width=1419&relative=1209600&q=] ->
play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]        at play.api.DefaultApplication.handleError(Application.scala:402) [com.t
ypesafe.play.play_2.10-2.3.9.jar:2.3.9]        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.pl
ay_2.10-2.3.9.jar:2.3.9]        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun
$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10
.4.jar:na]        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrE
lse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrE
lse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344
) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala
:40) [org.scala-lang.scala-library-2.10.4.jar:na]        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.s
cala-lang.scala-library-2.10.4.jar:na]        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExe
cutor.scala:59) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.10.4.jar:na]
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: null        at controllers.SearchController.renderSearch(SearchController.java:224)
~[graylog-web-interface.graylog-web-interface-1.1.0-rc.3.jar:1.1.0-rc.3]        at controllers.SearchController.index(SearchController.java:126) ~[grayl
og-web-interface.graylog-web-interface-1.1.0-rc.3.jar:1.1.0-rc.3]        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$459.ap
ply(routes_routing.scala:1659) ~[graylog-web-interface.graylog-web-interface-1.1.0-rc.3.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$459.apply(routes_routing.scala:1659) ~[graylog-web-interface.graylog-web-interface-1.1
.0-rc.3.jar:na]        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scal
a:264) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon
$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.GlobalSettings$1.call(GlobalSettings.java:67) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.mvc.Security$AuthenticatedAction.call(Security.java:44) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(
Future.scala:24) ~[org.scala-lang.scala-library-2.10.4.jar:na]        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang.scala-library-2.10.4.jar:na]        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:
46) [com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:3
2) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesaf
e.play.play_2.10-2.3.9.jar:2.3.9]        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon
$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.
9]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.sc
ala:129) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.ty
pesafe.play.play_2.10-2.3.9.jar:2.3.9]        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.sc
ala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.sc
ala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.
apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.9.jar:2.3.9]        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang.scala-library-2.10.4.jar:na]        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        ... 6 common frames omitted

**Comment by NickMeves** [comment]
I will hit the REST API directly and see if I notice something peculiar with the result compared to healthy cases.

**Comment by dkerwin** [comment]
Same problem here. Historical data cannot be searched after upgrade to 1.1.

```
[error] play - Cannot invoke the action, eventually got an error: java.lang.NullPointerException
[error] application -
 
! @6mcag17e7 - Internal server error, for (GET) [/search?rangetype=relative&fields=message%2Csource&width=1436&relative=86400&q=Exception] ->
 
play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: null
	at controllers.SearchController.renderSearch(SearchController.java:224) ~[graylog-web-interface.graylog-web-interface-1.1.0.jar:1.1.0]
	at controllers.SearchController.index(SearchController.java:126) ~[graylog-web-interface.graylog-web-interface-1.1.0.jar:1.1.0]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$459.apply(routes_routing.scala:1659) ~[graylog-web-interface.graylog-web-interface-1.1.0.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$459.apply(routes_routing.scala:1659) ~[graylog-web-interface.graylog-web-interface-1.1.0.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.9.jar:2.3.9]
```
