### ISSUE TITLE
Error rendering System Jobs on System/Overview

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#12140]
As part of reviewing a PR I spent some time on the System/Overview page, where I could see an error occurring a few times. The page loaded fine but eventually it threw an error with `Date time null is not valid` (full stack trace below).

Investigating a bit I could see why this seems to happen: System jobs may have a `null` `started_at` field (meaning the job has not yet started), which the `RelativeTime` component cannot handle. The moment a system job was queued on my Graylog instance, but did not yet start, the error appears.

<details>
<summary>Full error details</summary>

```
Date time null is not valid.


Stack Trace:

Error: Date time null is not valid.
    at validateDateTime (http://localhost:8080/app.js:43924:11)
    at toDateObject (http://localhost:8080/app.js:43947:10)
    at relativeDifference (http://localhost:8080/app.js:43966:20)
    at RelativeTime (http://localhost:8080/app.js:20522:87)
    at renderWithHooks (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:14803:18)
    at mountIndeterminateComponent (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:17482:13)
    at beginWork (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:18596:16)
    at HTMLUnknownElement.callCallback (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:188:14)
    at Object.invokeGuardedCallbackDev (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:237:16)
    at invokeGuardedCallback (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:292:31)
    at beginWork$1 (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:23203:7)
    at performUnitOfWork (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:22154:12)
    at workLoopSync (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:22130:22)
    at performSyncWorkOnRoot (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:21756:9)
    at eval (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:11089:24)
    at unstable_runWithPriority (webpack://__%5Bname%5D/./node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js?:653:12)
    at runWithPriority$1 (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:11039:10)
    at flushSyncCallbackQueueImpl (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:11084:7)
    at flushSyncCallbackQueue (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:11072:3)
    at discreteUpdates$1 (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:21893:7)
    at discreteUpdates (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:806:12)
    at dispatchDiscreteEvent (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:4168:3)

Component Stack:

    in RelativeTime (created by SystemJob)
    in div (created by SystemJob__JobWrap)
    in SystemJob__JobWrap (created by SystemJob)
    in div (created by SystemJob)
    in SystemJob (created by SystemJobsList)
    in div (created by SystemJobsList__SystemJobWrap)
    in SystemJobsList__SystemJobWrap (created by SystemJobsList)
    in span (created by SystemJobsList)
    in SystemJobsList (created by SystemJobsComponent)
    in div (created by Col)
    in Col (created by SystemJobsComponent)
    in div (created by Row)
    in Row (created by Row)
    in Row (created by SystemJobsComponent)
    in SystemJobsComponent (created by ConnectStoresWrapper[SystemJobsComponent] stores=systemJobsStore)
    in ConnectStoresWrapper[SystemJobsComponent] stores=systemJobsStore (created by SystemOverviewPage)
    in IfPermitted (created by SystemOverviewPage)
    in HideOnCloud (created by SystemOverviewPage)
    in span (created by SystemOverviewPage)
    in DocumentTitle (created by SystemOverviewPage)
    in SystemOverviewPage (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by AppRouter)
    in Switch (created by AppRouter)
    in div (created by Grid)
    in Grid (created by PageContentLayout__StyledGrid)
    in PageContentLayout__StyledGrid (created by PageContentLayout)
    in WithGlobalNotifications (created by PageContentLayout)
    in div (created by PageContentLayout__Container)
    in PageContentLayout__Container (created by PageContentLayout)
    in PageContentLayout (created by AppRouter)
    in Route (created by AppRouter)
    in Switch (created by AppRouter)
    in div (created by App__PageContent)
    in App__PageContent (created by Context.Consumer)
    in RuntimeErrorBoundary (created by Context.Consumer)
    in ReportedErrorBoundary (created by Context.Consumer)
    in div (created by App__AppLayout)
    in App__AppLayout (created by Context.Consumer)
    in ScratchpadProvider (created by Context.Consumer)
    in App (created by AppRouter)
    in Route (created by AppRouter)
    in Switch (created by AppRouter)
    in RouterErrorBoundary (created by AppRouter)
    in Router (created by AppRouter)
    in AppRouter (created by LoggedInPage)
    in StreamsProvider (created by ConnectStoresWrapper[StreamsProvider] stores=streams)
    in ConnectStoresWrapper[StreamsProvider] stores=streams (created by LoggedInPage)
    in LicenseCheckProvider (created by GlobalContextProviders)
    in ErrorBoundary (created by GlobalContextProviders)
    in GlobalContextProviders (created by LoggedInPage)
    in Fe (created by GraylogThemeProvider)
    in GraylogThemeProvider (created by ThemeAndUserProvider)
    in CurrentUserPreferencesProvider (created by ThemeAndUserProvider)
    in UserDateTimeProvider (created by ThemeAndUserProvider)
    in CurrentUserProvider (created by ThemeAndUserProvider)
    in ThemeAndUserProvider (created by LoggedInPage)
    in QueryClientProvider (created by DefaultQueryClientProvider)
    in DefaultQueryClientProvider (created by LoggedInPage)
    in LoggedInPage (created by LoadableComponent)
    in LoadableComponent (created by AppFacade)
    in AppFacade
    in Fe (created by GraylogThemeProvider)
    in GraylogThemeProvider
    in CustomizationProvider
```

</details>

Here is an example of system job showing this issue:

```json
{
  "3e308965-dec0-4ecd-adb8-bf7d1f04a256": {
    "jobs": [
      {
        "id": "64cb6760-8e81-11ec-962b-16afd066a24b",
        "description": "Makes index graylog_9 read only and calculates and adds its index range afterwards.",
        "name": "org.graylog2.indexer.indices.jobs.SetIndexReadOnlyAndCalculateRangeJob",
        "info": "No further information available.",
        "node_id": "3e308965-dec0-4ecd-adb8-bf7d1f04a256",
        "started_at": null,
        "percent_complete": 0,
        "provides_progress": false,
        "is_cancelable": false
      }
    ]
  }
}
```

## Expected Behavior
Rendering system jobs that has not been started should work fine.

## Current Behavior
Rendering system jobs that has not started fails and it is not possible to see the System/Overview page.

## Steps to Reproduce (for bugs)
1. Go to the System/Overview page
2. Leave the page open for a while
3. The error occurs in the background
4. Reload the page and see that it works again

## Your Environment
* Graylog Version: Graylog-4.3.0-SNAPSHOT (884e5c10ed6770bbb57529ceb998af5aadd54350)

**Comment by edmundoa** [comment]
Fixed in #12122
