### ISSUE TITLE
Cisco Meraki Syslog messages fail to ingest: Invalid format date format

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#12546]
HS864297133

## Expected Behavior

[Cisco Meraki](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples) log events should successfully be parsed when sent to a Syslog Graylog input.

## Current Behavior

When attempting to ingest Cisco Merkai syslog messages, the following exception occurs:

Log message:
> <134>1 1650972789.426960608 Another_Device urls src=10.10.10.1:53347 dst=10.10.10.2:443 mac=02:AA:AA:AA:AA:AA request: UNKNOWN https://test/testurl

```
java.lang.IllegalArgumentException: Invalid format: "1650972789.426960608" is malformed at "9.426960608"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945) ~[joda-time-2.10.6.jar:2.10.6]
	at org.joda.time.DateTime.parse(DateTime.java:160) ~[joda-time-2.10.6.jar:2.10.6]
	at org.joda.time.DateTime.parse(DateTime.java:149) ~[joda-time-2.10.6.jar:2.10.6]
	at org.graylog2.syslog4j.server.impl.event.SyslogServerEvent.parseDate(SyslogServerEvent.java:108) ~[syslog4j-0.9.60.jar:?]
	at org.graylog2.syslog4j.server.impl.event.structured.StructuredSyslogServerEvent.parseDate(StructuredSyslogServerEvent.java:113) ~[syslog4j-0.9.60.jar:?]
	at org.graylog2.syslog4j.server.impl.event.SyslogServerEvent.parsePriority(SyslogServerEvent.java:136) ~[syslog4j-0.9.60.jar:?]
	at org.graylog2.syslog4j.server.impl.event.SyslogServerEvent.parse(SyslogServerEvent.java:152) ~[syslog4j-0.9.60.jar:?]
	at org.graylog2.syslog4j.server.impl.event.structured.StructuredSyslogServerEvent.<init>(StructuredSyslogServerEvent.java:50) ~[syslog4j-0.9.60.jar:?]
	at org.graylog2.inputs.codecs.SyslogCodec.parse(SyslogCodec.java:126) ~[classes/:?]
	at org.graylog2.inputs.codecs.SyslogCodec.decode(SyslogCodec.java:96) ~[classes/:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:156) ~[classes/:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:94) [classes/:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:95) [classes/:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:49) [class
```

## Root Cause
This is occurring, because the Graylog Syslog codec (and underlying Graylog [syslog4j](https://github.com/graylog-labs/syslog4j-graylog2) dependency) does not support parsing the nanos timestamp that is being used on Cisco Merkai log messages: `1650972789.426960608`. I believe the nine digits after the dot are seconds to the nanosecond precision.

## Workaround
Use a Raw TCP or Raw UDP input to ingest the message, and use [Processing Pipelines](https://docs.graylog.org/docs/pipelines) to parse the message.

## Possible Solution

Add explicit support for Cisco Merkai log messages in the [Graylog syslog4j dependency](https://github.com/graylog-labs/syslog4j-graylog2). Adding a new syslog message [Event type](https://github.com/graylog-labs/syslog4j-graylog2/tree/master/src/main/java/org/graylog2/syslog4j/server/impl/event) will probably be needed.

## Your Environment

* Graylog Version: 4.2.7

**Comment by patrickmann** [comment]
@danotorrey There are several different [Meraki syslog message formats](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples). At a glance I see the following:
1. `<epoch nanos> <host>` ...
2. `<date-time> <priority> <epoch nanos> <host>` ....
3. `signature=<signature> priority=<priority> timestamp=<epoch nanos>` ...

Currently we only provide built-in support for a very small number of syslog formats. Is Meraki such a common device that it deserves being added to the built-in formats? I am leaning towards no.

**Comment by patrickmann** [comment]
Closing this per discussion on team-seccon:
```
[Michael Wenthold](https://app.slack.com/team/UU70L516Y)
  [vor 4 Tagen](https://graylog.slack.com/archives/CKFFJ75U5/p1660830873626809?thread_ts=1660736641.851379&cid=CKFFJ75U5)
I'm going to update the Meraki documentation to suggest they use the Raw/Plaintext UDP input for Meraki if they have nanosecond timestamps.
```
