### ISSUE TITLE
Exception in thread "main" java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by Sc0th** [Graylog2/graylog2-server#12818]
Seeing this after updating container to 4.3.1(same on 4.3)

`2022-06-06 10:41:47,292 INFO : org.graylog2.bootstrap.preflight.SearchDbPreflightCheck - Connected to (Elastic/Open)Search version <Elasticsearch:7.10.2>
Exception in thread "main" java.lang.ArithmeticException: / by zero
        at org.graylog2.shared.system.stats.fs.OshiFsProbe.lambda$fsStats$11(OshiFsProbe.java:116)
`

Mongo 5.0.9
Elastic 7.10.2
official docker images

full log:

`Pod name is graylog-84f99dbddb-24lrx.
Defaulted container "graylog-server" out of: graylog-server, check-graylog-elasticsearch-ready (init)
2022-06-06 10:41:45,772 INFO : org.graylog2.featureflag.ImmutableFeatureFlagsCollector - Following feature flags are used: {}
2022-06-06 10:41:46,516 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: AWS plugins 4.3.1 [org.graylog.aws.AWSPlugin]
2022-06-06 10:41:46,517 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Integrations 4.3.1 [org.graylog.integrations.IntegrationsPlugin]
2022-06-06 10:41:46,519 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Collector 4.3.1 [org.graylog.plugins.collector.CollectorPlugin]
2022-06-06 10:41:46,520 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Threat Intelligence Plugin 4.3.1 [org.graylog.plugins.threatintel.ThreatIntelPlugin]
2022-06-06 10:41:46,520 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Elasticsearch 6 Support 4.3.1+78ee2f1 [org.graylog.storage.elasticsearch6.Elasticsearch6Plugin]
2022-06-06 10:41:46,520 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Elasticsearch 7 Support 4.3.1+78ee2f1 [org.graylog.storage.elasticsearch7.Elasticsearch7Plugin]
2022-06-06 10:41:46,544 INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -Dlog4j2.formatMsgNoLookups=true -Djdk.tls.acknowledgeCloseNotify=true -XX:+UnlockExperimentalVMOptions -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -XX:+ResizeTLAB -XX:-OmitStackTraceInFastThrow -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -Dlog4j.configurationFile=/usr/share/graylog/data/config/log4j2.xml -Djava.library.path=/usr/share/graylog/lib/sigar/ -Dgraylog2.installation_source=docker
2022-06-06 10:41:47,037 INFO : org.mongodb.driver.cluster - Cluster created with settings {hosts=[graylog-mongo.<mydomain>:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2022-06-06 10:41:47,080 INFO : org.mongodb.driver.cluster - Cluster description not yet available. Waiting for 30000 ms before timing out
2022-06-06 10:41:47,106 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:25}] to graylog-mongo.<mydomain>:27017
2022-06-06 10:41:47,113 INFO : org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=graylog-mongo.<mydomain>:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[5, 0, 9]}, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=4717821}
2022-06-06 10:41:47,127 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:26}] to graylog-mongo.<mydomain>:27017
2022-06-06 10:41:47,154 INFO : org.mongodb.driver.connection - Closed connection [connectionId{localValue:2, serverValue:26}] to graylog-mongo.<mydomain>:27017 because the pool has been closed.
2022-06-06 10:41:47,156 INFO : org.graylog2.bootstrap.preflight.MongoDBPreflightCheck - Connected to MongoDB version 5.0.9
2022-06-06 10:41:47,292 INFO : org.graylog2.bootstrap.preflight.SearchDbPreflightCheck - Connected to (Elastic/Open)Search version <Elasticsearch:7.10.2>
Exception in thread "main" java.lang.ArithmeticException: / by zero
        at org.graylog2.shared.system.stats.fs.OshiFsProbe.lambda$fsStats$11(OshiFsProbe.java:116)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:440)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1723)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.graylog2.shared.system.stats.fs.OshiFsProbe.fsStats(OshiFsProbe.java:106)
        at org.graylog2.bootstrap.preflight.DiskJournalPreflightCheck.checkJournalDirSizeAndType(DiskJournalPreflightCheck.java:67)
        at org.graylog2.bootstrap.preflight.DiskJournalPreflightCheck.runCheck(DiskJournalPreflightCheck.java:62)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
        at org.graylog2.bootstrap.preflight.PreflightCheckService.runChecks(PreflightCheckService.java:51)
        at org.graylog2.bootstrap.ServerBootstrap.runPreFlightChecks(ServerBootstrap.java:135)
        at org.graylog2.bootstrap.ServerBootstrap.beforeInjectorCreation(ServerBootstrap.java:126)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:292)
        at org.graylog2.bootstrap.Main.main(Main.java:45)
`

**Comment by mpfz0r** [comment]
Will be fixed with 4.3.2
