### ISSUE TITLE
Null Pointer in org.graylog2.periodical.IndexerClusterCheckerThread

### ISSUE THREAD

**Issue by HenryTheSir** [Graylog2/graylog2-server#12858]
## Expected Behavior

No null Pointer
## Current Behavior

```
2022-06-09 10:10:51,556 ERROR: org.graylog2.periodical.IndexerClusterCheckerThread - Uncaught exception in periodical
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: Unable to retrieve nodes list
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:140) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:100) ~[?:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.perform(CatApi.java:89) ~[?:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.nodes(CatApi.java:51) ~[?:?]
        at org.graylog.storage.elasticsearch7.ClusterAdapterES7.nodes(ClusterAdapterES7.java:107) ~[?:?]
        at org.graylog.storage.elasticsearch7.ClusterAdapterES7.fileDescriptorStats(ClusterAdapterES7.java:100) ~[?:?]
        at org.graylog2.indexer.cluster.Cluster.getFileDescriptorStats(Cluster.java:90) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexerClusterCheckerThread.checkOpenFiles(IndexerClusterCheckerThread.java:75) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexerClusterCheckerThread.doRun(IndexerClusterCheckerThread.java:64) ~[graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.graylog.storage.elasticsearch7.cat.NodeResponse`, problem: Null diskUsed
 at [Source: (org.graylog.shaded.elasticsearch7.org.apache.http.nio.entity.ContentInputStream); line: 1, column: 1615] (through reference chain: java.util.ArrayList[8])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:484) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:503) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3078) ~[graylog.jar:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.returnType(CatApi.java:98) ~[?:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.lambda$perform$4(CatApi.java:93) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:98) ~[?:?]
        ... 14 more
Caused by: java.lang.NullPointerException: Null diskUsed
        at org.graylog.storage.elasticsearch7.cat.AutoValue_NodeResponse.<init>(AutoValue_NodeResponse.java:55) ~[?:?]
        at org.graylog.storage.elasticsearch7.cat.NodeResponse.create(NodeResponse.java:58) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor71.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call(AnnotatedMethod.java:109) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3078) ~[graylog.jar:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.returnType(CatApi.java:98) ~[?:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.lambda$perform$4(CatApi.java:93) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:98) ~[?:?]
        ... 14 more
```
## Steps to Reproduce (for bugs)

1. unclear how it can be reproduced
2.
3.
4.

## Your Environment

* Graylog Version: 4.2.7
* Java Version: JDK 11
* Elasticsearch Version: 7.10.2
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Hey @HenryTheSir, thanks for reporting this!

Did this happen once, multiple times or all the time? Does it correlate with e.g. unavailability of an ES node or any other external factor?

**Comment by HenryTheSir** [comment]
Hi @dennisoelkers ,

it occurs multiple times, but not permanent. Find Screen with occurences attached. Error appears in different Graylog Clusters.
![Image showing timegraph of error occurences](https://user-images.githubusercontent.com/11004513/173044519-3da1c1e3-acfd-419e-9e90-40e3e67129ba.png)

**Comment by luk-kaminski** [comment]
Hi @HenryTheSir , @dennisoelkers ,

I'd simply exclude nodes that temporarily do not return their disk/file data from current "open file"/"disk usage" check. 
Periodical runs every 30 seconds, it fails very rarely, so we will get proper notification, if needed, in one of the following runs.

I can also log some information about problematic nodes, maybe it will give us a clue about the problem (is it a single node or multiple ones? does it have a specific role?).

Are you ok with that?
