### ISSUE TITLE
2015-07-08 17:02:28,932 WARN : org.elasticsearch.discovery.zen - [graylog2-server] failed to connect to master [[Centurion][S9r6JSNmQua8n2Dhat6xqQ][inet[/192.168.22.2:9300]]], retrying...

### ISSUE THREAD

**Issue by Fibrewire** [Graylog2/graylog2-server#1294]
Hi, 

Im running into an error when trying to get graylog up and running, im following the instructions [here](https://www.digitalocean.com/community/tutorials/how-to-install-graylog2-and-centralize-logs-on-ubuntu-14-04) verbatim, ive triple checked that i havn't wandered and yet am seeing the below error, any help would be greatly appreciated.

fibrewire@logging:~$ curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
{
  "cluster_name" : "graylog2",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0
}
fibrewire@logging:~$ sudo java -jar /opt/graylog2-server/graylog2-server.jar --debug
2015-07-08 17:02:19,464 INFO : org.graylog2.Main - Graylog2 0.20.2 starting up. (JRE: Oracle Corporation 1.7.0_80 on Linux 3.13.0-32-generic)
2015-07-08 17:02:19,540 INFO : org.graylog2.plugin.system.NodeId - Node ID: e96b1a32-4315-4200-a96d-9cee83e0b411
2015-07-08 17:02:19,763 INFO : org.graylog2.buffers.ProcessBuffer - Initialized ProcessBuffer with ring size <1024> and wait strategy <BlockingWaitStrategy>.
2015-07-08 17:02:19,799 INFO : org.graylog2.buffers.OutputBuffer - Initialized OutputBuffer with ring size <1024> and wait strategy <BlockingWaitStrategy>.
2015-07-08 17:02:20,033 DEBUG: com.ning.http.client.providers.netty.NettyAsyncHttpProvider - Number of application's worker threads is 2
2015-07-08 17:02:20,320 INFO : org.elasticsearch.node - [graylog2-server] version[0.90.10], pid[4557], build[0a5781f/2014-01-10T10:18:37Z]
2015-07-08 17:02:20,329 INFO : org.elasticsearch.node - [graylog2-server] initializing ...
2015-07-08 17:02:20,329 DEBUG: org.elasticsearch.node - [graylog2-server] using home [/home/fibrewire], config [/home/fibrewire/config], data [[/home/fibrewire/data]], logs [/home/fibrewire/logs], work [/home/fibrewire/work], plugins [/home/fibrewire/plugins]
2015-07-08 17:02:20,340 INFO : org.elasticsearch.plugins - [graylog2-server] loaded [], sites []
2015-07-08 17:02:20,363 DEBUG: org.elasticsearch.common.compress.lzf - using [UnsafeChunkDecoder] decoder
2015-07-08 17:02:21,776 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [generic], type [cached], keep_alive [30s]
2015-07-08 17:02:21,788 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [index], type [fixed], size [1], queue_size [200]
2015-07-08 17:02:21,792 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [bulk], type [fixed], size [1], queue_size [50]
2015-07-08 17:02:21,792 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [get], type [fixed], size [1], queue_size [1k]
2015-07-08 17:02:21,793 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [search], type [fixed], size [3], queue_size [1k]
2015-07-08 17:02:21,793 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [suggest], type [fixed], size [1], queue_size [1k]
2015-07-08 17:02:21,793 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [percolate], type [fixed], size [1], queue_size [1k]
2015-07-08 17:02:21,793 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [management], type [scaling], min [1], size [5], keep_alive [5m]
2015-07-08 17:02:21,794 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [flush], type [scaling], min [1], size [1], keep_alive [5m]
2015-07-08 17:02:21,795 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [merge], type [scaling], min [1], size [1], keep_alive [5m]
2015-07-08 17:02:21,795 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [refresh], type [scaling], min [1], size [1], keep_alive [5m]
2015-07-08 17:02:21,795 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [warmer], type [scaling], min [1], size [1], keep_alive [5m]
2015-07-08 17:02:21,796 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [snapshot], type [scaling], min [1], size [1], keep_alive [5m]
2015-07-08 17:02:21,796 DEBUG: org.elasticsearch.threadpool - [graylog2-server] creating thread_pool [optimize], type [fixed], size [1], queue_size [null]
2015-07-08 17:02:21,812 DEBUG: org.elasticsearch.transport.netty - [graylog2-server] using worker_count[2], port[9350], bind_host[null], publish_host[null], compress[false], connect_timeout[30s], connections_per_node[2/3/6/1/1], receive_predictor[512kb->512kb]
2015-07-08 17:02:21,829 DEBUG: org.elasticsearch.discovery.zen.ping.multicast - [graylog2-server] using group [224.2.2.4], with port [54328], ttl [3], and address [null]
2015-07-08 17:02:21,833 DEBUG: org.elasticsearch.discovery.zen.ping.unicast - [graylog2-server] using initial hosts [], with concurrent_connects [10]
2015-07-08 17:02:21,835 DEBUG: org.elasticsearch.discovery.zen - [graylog2-server] using ping.timeout [3s], master_election.filter_client [true], master_election.filter_data [false]
2015-07-08 17:02:21,836 DEBUG: org.elasticsearch.discovery.zen.elect - [graylog2-server] using minimum_master_nodes [-1]
2015-07-08 17:02:21,840 DEBUG: org.elasticsearch.discovery.zen.fd - [graylog2-server] [master] uses ping_interval [1s], ping_timeout [30s], ping_retries [3]
2015-07-08 17:02:21,850 DEBUG: org.elasticsearch.discovery.zen.fd - [graylog2-server] [node  ] uses ping_interval [1s], ping_timeout [30s], ping_retries [3]
2015-07-08 17:02:21,888 DEBUG: org.elasticsearch.monitor.jvm - [graylog2-server] enabled [true], last_gc_enabled [false], interval [1s], gc_threshold [{old=GcThreshold{name='old', warnThreshold=10000, infoThreshold=5000, debugThreshold=2000}, default=GcThreshold{name='default', warnThreshold=10000, infoThreshold=5000, debugThreshold=2000}, young=GcThreshold{name='young', warnThreshold=1000, infoThreshold=700, debugThreshold=400}}]
2015-07-08 17:02:21,889 DEBUG: org.elasticsearch.monitor.os - [graylog2-server] Using probe [org.elasticsearch.monitor.os.JmxOsProbe@4c3b7f48] with refresh_interval [1s]
2015-07-08 17:02:21,890 DEBUG: org.elasticsearch.monitor.process - [graylog2-server] Using probe [org.elasticsearch.monitor.process.JmxProcessProbe@2bfd5f0e] with refresh_interval [1s]
2015-07-08 17:02:21,894 DEBUG: org.elasticsearch.monitor.jvm - [graylog2-server] Using refresh_interval [1s]
2015-07-08 17:02:21,895 DEBUG: org.elasticsearch.monitor.network - [graylog2-server] Using probe [org.elasticsearch.monitor.network.JmxNetworkProbe@5912c08] with refresh_interval [5s]
2015-07-08 17:02:21,896 DEBUG: org.elasticsearch.monitor.network - [graylog2-server] net_info
host [logging]
eth0    display_name [eth0]
                address [/fe80:0:0:0:20c:29ff:fe32:bea5%2] [/192.168.22.2]
                mtu [1500] multicast [true] ptp [false] loopback [false] up [true] virtual [false]
lo      display_name [lo]
                address [/0:0:0:0:0:0:0:1%1] [/127.0.0.1]
                mtu [65536] multicast [false] ptp [false] loopback [true] up [true] virtual [false]

2015-07-08 17:02:21,899 DEBUG: org.elasticsearch.monitor.fs - [graylog2-server] Using probe [org.elasticsearch.monitor.fs.JmxFsProbe@387b30d3] with refresh_interval [1s]
2015-07-08 17:02:22,457 DEBUG: org.elasticsearch.indices.store - [graylog2-server] using indices.store.throttle.type [MERGE], with index.store.throttle.max_bytes_per_sec [20mb]
2015-07-08 17:02:22,463 DEBUG: org.elasticsearch.cache.memory - [graylog2-server] using bytebuffer cache with small_buffer_size [1kb], large_buffer_size [1mb], small_cache_size [10mb], large_cache_size [500mb], direct [true]
2015-07-08 17:02:22,470 DEBUG: org.elasticsearch.script - [graylog2-server] using script cache with max_size [500], expire [null]
2015-07-08 17:02:22,475 DEBUG: org.elasticsearch.cluster.routing.allocation.decider - [graylog2-server] using node_concurrent_recoveries [2], node_initial_primaries_recoveries [4]
2015-07-08 17:02:22,475 DEBUG: org.elasticsearch.cluster.routing.allocation.decider - [graylog2-server] using [cluster.routing.allocation.allow_rebalance] with [indices_all_active]
2015-07-08 17:02:22,476 DEBUG: org.elasticsearch.cluster.routing.allocation.decider - [graylog2-server] using [cluster_concurrent_rebalance] with [2]
2015-07-08 17:02:22,479 DEBUG: org.elasticsearch.gateway.local - [graylog2-server] using initial_shards [quorum], list_timeout [30s]
2015-07-08 17:02:22,638 DEBUG: org.elasticsearch.indices.recovery - [graylog2-server] using max_bytes_per_sec[20mb], concurrent_streams [3], file_chunk_size [512kb], translog_size [512kb], translog_ops [1000], and compress [true]
2015-07-08 17:02:22,720 DEBUG: org.elasticsearch.indices.memory - [graylog2-server] using index_buffer_size [72.6mb], with min_shard_index_buffer_size [4mb], max_shard_index_buffer_size [512mb], shard_inactive_time [30m]
2015-07-08 17:02:22,722 DEBUG: org.elasticsearch.indices.cache.filter - [graylog2-server] using [node] weighted filter cache with size [20%], actual_size [145.3mb], expire [null], clean_interval [1m]
2015-07-08 17:02:22,724 DEBUG: org.elasticsearch.indices.fielddata.cache - [graylog2-server] using size [-1] [-1b], expire [null]
2015-07-08 17:02:22,744 DEBUG: org.elasticsearch.gateway.local.state.meta - [graylog2-server] using gateway.local.auto_import_dangled [YES], with gateway.local.dangling_timeout [2h]
2015-07-08 17:02:22,747 DEBUG: org.elasticsearch.bulk.udp - [graylog2-server] using enabled [false], host [null], port [9700-9800], bulk_actions [1000], bulk_size [5mb], flush_interval [5s], concurrent_requests [4]
2015-07-08 17:02:22,750 DEBUG: org.elasticsearch.cluster.routing.allocation.decider - [graylog2-server] using node_concurrent_recoveries [2], node_initial_primaries_recoveries [4]
2015-07-08 17:02:22,750 DEBUG: org.elasticsearch.cluster.routing.allocation.decider - [graylog2-server] using [cluster.routing.allocation.allow_rebalance] with [indices_all_active]
2015-07-08 17:02:22,750 DEBUG: org.elasticsearch.cluster.routing.allocation.decider - [graylog2-server] using [cluster_concurrent_rebalance] with [2]
2015-07-08 17:02:22,751 DEBUG: org.elasticsearch.cluster.routing.allocation.decider - [graylog2-server] using node_concurrent_recoveries [2], node_initial_primaries_recoveries [4]
2015-07-08 17:02:22,752 DEBUG: org.elasticsearch.cluster.routing.allocation.decider - [graylog2-server] using [cluster.routing.allocation.allow_rebalance] with [indices_all_active]
2015-07-08 17:02:22,752 DEBUG: org.elasticsearch.cluster.routing.allocation.decider - [graylog2-server] using [cluster_concurrent_rebalance] with [2]
2015-07-08 17:02:22,762 INFO : org.elasticsearch.node - [graylog2-server] initialized
2015-07-08 17:02:22,762 INFO : org.elasticsearch.node - [graylog2-server] starting ...
2015-07-08 17:02:22,790 DEBUG: org.elasticsearch.netty.channel.socket.nio.SelectorUtil - Using select timeout of 500
2015-07-08 17:02:22,790 DEBUG: org.elasticsearch.netty.channel.socket.nio.SelectorUtil - Epoll-bug workaround enabled = false
2015-07-08 17:02:22,851 DEBUG: org.elasticsearch.transport.netty - [graylog2-server] Bound to address [/0:0:0:0:0:0:0:0:9350]
2015-07-08 17:02:22,855 INFO : org.elasticsearch.transport - [graylog2-server] bound_address {inet[/0:0:0:0:0:0:0:0:9350]}, publish_address {inet[/192.168.22.2:9350]}
2015-07-08 17:02:25,865 WARN : org.elasticsearch.discovery - [graylog2-server] waited for 3s and no initial state was set by the discovery
2015-07-08 17:02:25,866 INFO : org.elasticsearch.discovery - [graylog2-server] graylog2/L_EoFetnS9aHIkXBoPyI1A
2015-07-08 17:02:25,866 DEBUG: org.elasticsearch.gateway - [graylog2-server] can't wait on start for (possibly) reading state from gateway, will do it asynchronously
2015-07-08 17:02:25,867 INFO : org.elasticsearch.node - [graylog2-server] started
2015-07-08 17:02:25,889 DEBUG: org.elasticsearch.discovery.zen - [graylog2-server] filtered ping responses: (filter_client[true], filter_data[false])
        --> target [[Centurion][S9r6JSNmQua8n2Dhat6xqQ][inet[/192.168.22.2:9300]]], master [[Centurion][S9r6JSNmQua8n2Dhat6xqQ][inet[/192.168.22.2:9300]]]
2015-07-08 17:02:25,911 WARN : org.elasticsearch.discovery.zen - [graylog2-server] failed to connect to master [[Centurion][S9r6JSNmQua8n2Dhat6xqQ][inet[/192.168.22.2:9300]]], retrying...
org.elasticsearch.transport.ConnectTransportException: [Centurion][inet[/192.168.22.2:9300]] connect_timeout[30s]
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:711)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:640)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:608)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:129)
        at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:335)
        at org.elasticsearch.discovery.zen.ZenDiscovery.access$500(ZenDiscovery.java:76)
        at org.elasticsearch.discovery.zen.ZenDiscovery$1.run(ZenDiscovery.java:283)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: /192.168.22.2:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:744)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        ... 3 more
2015-07-08 17:02:28,923 DEBUG: org.elasticsearch.discovery.zen - [graylog2-server] filtered ping responses: (filter_client[true], filter_data[false])
        --> target [[Centurion][S9r6JSNmQua8n2Dhat6xqQ][inet[/192.168.22.2:9300]]], master [[Centurion][S9r6JSNmQua8n2Dhat6xqQ][inet[/192.168.22.2:9300]]]
2015-07-08 17:02:28,932 WARN : org.elasticsearch.discovery.zen - [graylog2-server] failed to connect to master [[Centurion][S9r6JSNmQua8n2Dhat6xqQ][inet[/192.168.22.2:9300]]], retrying...
org.elasticsearch.transport.ConnectTransportException: [Centurion][inet[/192.168.22.2:9300]] connect_timeout[30s]
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:711)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:640)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:608)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:129)
        at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:335)
        at org.elasticsearch.discovery.zen.ZenDiscovery.access$500(ZenDiscovery.java:76)
        at org.elasticsearch.discovery.zen.ZenDiscovery$1.run(ZenDiscovery.java:283)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: /192.168.22.2:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:744)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        ... 3 more
2015-07-08 17:02:30,873 ERROR: org.graylog2.Main -

################################################################################

ERROR: Could not successfully connect to ElasticSearch. Check that your cluster state is not RED and that ElasticSearch is running properly.

Need help?

* Official documentation: http://support.torch.sh/help/kb
* Mailing list: http://support.torch.sh/help/kb/general/forums-mailing-list
* Issue tracker: http://support.torch.sh/help/kb/general/issue-trackers
* Commercial support: http://www.torch.sh/

But we also got some specific help pages that might help you in this case:

* http://support.torch.sh/help/kb/graylog2-server/configuring-and-tuning-elasticsearch-for-graylog2-v0200

Terminating. :(

################################################################################

**Comment by Fibrewire** [comment]
Firewall, sorry guys
