### ISSUE TITLE
Null pointer exception cause server stop processing messages

### ISSUE THREAD

**Issue by tomikiss** [Graylog2/graylog2-server#1298]
Centos 6 , graylog server 1.1.4 , elasticsearch 1.5.2 , openjdk version "1.8.0_45"
```
Stack trace of the issue:
2015-07-10T11:16:34.486+01:00 WARN  [InputBufferImpl] Unable to process event RawMessageEvent{raw=null, uuid=bde580a0-26ec-11e5-9a46-005056b26ca9, encodedLength=350}, sequence 19847516
java.lang.NullPointerException
        at org.graylog2.shared.buffers.JournallingMessageHandler$Converter.apply(JournallingMessageHandler.java:89)
        at org.graylog2.shared.buffers.JournallingMessageHandler$Converter.apply(JournallingMessageHandler.java:72)
        at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:617)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
        at java.util.ArrayList.<init>(ArrayList.java:177)
        at com.google.common.collect.Lists.newArrayList(Lists.java:144)
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:61)
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:36)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
After restarting the server the issue go away for a couple of day.

**Comment by tomikiss** [comment]
After restarting it I got also some weird Outofmemory exception.

**Comment by bernd** [comment]
Thank you for the report. This issue has been addressed in https://github.com/Graylog2/graylog2-server/pull/1286 and will be released in the upcoming 1.1.5 release.

The NullPointerException gets triggered because of another exception that has been thrown before the first NullPointerException. Do you have to old logs by any chance? The exception before the first NullPointerException is interesting. It will probably be a KafkaException.

If you still have that, it would be great if you can post it here.

The OutOfMemoryError is also just a byproduct of the other error because the batch list in the JournallingMessageHandler grows unbounded and fills up the memory.

**Comment by tomikiss** [comment]
HI,

The only thing what I see is that now I cannot even start it up, it just crashes with the following exceptions.

2015-07-10T13:14:24.707+01:00 INFO  [ServerBootstrap] Graylog server up and running.
2015-07-10T13:14:25.417+01:00 ERROR [ServiceManager] Service JournalReader [FAILED] has failed in the RUNNING state.
java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
        at kafka.log.FileMessageSet$$anon$1.makeNext(FileMessageSet.scala:188)
        at kafka.log.FileMessageSet$$anon$1.makeNext(FileMessageSet.scala:165)
        at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
        at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
        at org.graylog2.shared.journal.KafkaJournal.read(KafkaJournal.java:455)
        at org.graylog2.shared.journal.KafkaJournal.read(KafkaJournal.java:420)
        at org.graylog2.shared.journal.JournalReader.run(JournalReader.java:136)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
        at java.lang.Thread.run(Thread.java:745)

Does the full log would help you to figure out what can cause this outofmemory exception?

**Comment by bernd** [comment]
Yes, the full log would be great. Can you upload it somewhere? (private gist maybe)

**Comment by tomikiss** [comment]
I created a private gist for this:

https://gist.github.com/tomikiss/08c3d4a4132a473a1b67

**Comment by bernd** [comment]
That looks strange. Can you please try to stop the Graylog server process, rename the journal directory in the file system and start the server again. I looks like your journal got corrupted.

**Comment by tomikiss** [comment]
It working now, in-deed it seems the journal got corrupted.

**Comment by bernd** [comment]
Okay, thanks for the feedback. Did you maybe run into a full hard disk before? I wonder how the journal got corrupted...

**Comment by tomikiss** [comment]
it can be but I wasn't able to catch that. I will keep monitor it and see whether I able to reproduce it or have all logs.

**Comment by bernd** [comment]
Thank you for the information. I will close the issue now. Feel free to re-open it if you run into issues again.
