### ISSUE TITLE
Occasional `Cause` "Missing required properties: indexUuid index" after switch to ES7

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#13221]
## Expected Behavior

No deserialization exceptions occur.

## Current Behavior

After upgrading from ES 6.8.6 to 7.10.2 we've noticed a new exception that seems to be related to [`graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/errors/Cause.java`](https://github.com/Graylog2/graylog2-server/blob/82fd660051e15e4afa3d2d110341aef25aa32d00/graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/errors/Cause.java) and `index_uuid` + `index` missing from `$.errors.root_cause[0]` in the JSON coming back from ES.  [Searching through the Elasticsearch repo](https://github.com/elastic/elasticsearch/search?q=root_cause), I see "causes" that don't have those fields, so perhaps there's an assumption about its shape in Graylog.

Based upon the stack traces (example below) this seems related to field value suggestions, but I haven't been able to reliably reproduce the issue.  There's nothing in the ES logs around the times these have occurred.

```
2022-08-09 14:12:31,446 WARN : org.graylog.storage.elasticsearch7.ElasticsearchClient - Failed to parse exception
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.graylog.storage.elasticsearch7.errors.Cause$Builder`, problem: Missing required properties: indexUuid index
 at [Source: (ByteArrayInputStream); line: 1, column: 344] (through reference chain: org.graylog.storage.elasticsearch7.errors.AutoValue_ResponseError$Builder["error"]->org.graylog.storage.elasticsearch7.errors.AutoValue_ElasticsearchError$Builder["root_cause"]->java.util.ArrayList[1])
     at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1073) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapInstantiationProblem(BeanDeserializerBase.java:1754) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.finishBuild(BuilderBasedDeserializer.java:178) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:269) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:269) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014) ~[graylog.jar:?]
     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3071) ~[graylog.jar:?]
     at org.graylog.storage.elasticsearch7.ElasticsearchClient.parseResponseException(ElasticsearchClient.java:200) ~[?:?]
     at org.graylog.storage.elasticsearch7.QuerySuggestionsES7.tryResponseException(QuerySuggestionsES7.java:86) ~[?:?]
     at org.graylog.storage.elasticsearch7.QuerySuggestionsES7.suggest(QuerySuggestionsES7.java:79) ~[?:?]
     at org.graylog.plugins.views.search.rest.SuggestionsResource.suggestFieldValue(SuggestionsResource.java:79) ~[graylog.jar:?]
     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
     at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) [graylog.jar:?]
     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) [graylog.jar:?]
     at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) [graylog.jar:?]
     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) [graylog.jar:?]
     at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) [graylog.jar:?]
     at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) [graylog.jar:?]
     at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) [graylog.jar:?]
     at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
     at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
     at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
     at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
     at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
     at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
     at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [graylog.jar:?]
     at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
     at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
     at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
     at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Missing required properties: indexUuid index
     at org.graylog.storage.elasticsearch7.errors.AutoValue_Cause$Builder.build(AutoValue_Cause.java:146) ~[?:?]
     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
     at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.finishBuild(BuilderBasedDeserializer.java:176) ~[graylog.jar:?]
     ... 43 more
```

## Steps to Reproduce (for bugs)
Currently unknown.  Potentially some sort of invalid state when field value suggestions kick in.

## Context

Extremely low impact (no visible issue, happening very infrequently), but I wanted to go ahead and report it in case there's something obvious.

## Your Environment

* Graylog Version: 4.3.4
* Java Version: 11.0.16
* Elasticsearch Version:  7.10.2
* MongoDB Version:  4.4.15
* Operating System:  Ubuntu Server 18.04
* Browser version:  Firefox 103

**Comment by tom-zagar** [comment]
I can confirm that same occurrence in my env and that it happened when constructing search query and autocomplete somehow messed it. Can't reliably reproduce it either.

 ## Environment
 
     * Graylog Version: 5.0.0-14
 
     * Java Version: 17.0.5 (bundled with GL5)
 
     * Elasticsearch Version:  7.10.2
 
     * MongoDB Version:  6.0.3
 
     * Operating System:  Red Hat Enterprise Linux release 9.1 (Plow)
 
     * Browser version:  107.0.1 (64-bit)
