### ISSUE TITLE
Error with grok date converter

### ISSUE THREAD

**Issue by superceu** [Graylog2/graylog2-server#1333]
Log: `<166>2015-07-31T10:05:36.773Z esxi-e1b2.local.xxxx.it Vpxa: [4A2D4B90 verbose 'VpxaHalCnxHostagent' opID=WFU-65ff5b37] [WaitForUpdatesDone] Completed callback`

Grok pattern: `<\d+>%{DATA:timestamp;date;yyyy-MM-dd'T'HH:mm:ss.SSSZ} %{DATA:cst_hostname}`

The error is reproducible even with a simpler pattern, e.g.: `<\d+>%{DATA:timestamp;date;yyyy-} %{DATA:cst_hostname}`. Without the hyphen (yyyy**-**) this pattern works.  

```
2015-07-31_10:25:12.16258 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
2015-07-31_10:25:12.16262 java.util.regex.PatternSyntaxException: Illegal repetition near index 5
2015-07-31_10:25:12.16262 <\d+>%{DATA:timestamp;date;yyyy-MM-dd'T'HH:mm:ss.SSSZ} (.*?)
2015-07-31_10:25:12.16263      ^
2015-07-31_10:25:12.16263       at java.util.regex.Pattern.error(Pattern.java:1955)
2015-07-31_10:25:12.16264       at java.util.regex.Pattern.closure(Pattern.java:3157)
2015-07-31_10:25:12.16264       at java.util.regex.Pattern.sequence(Pattern.java:2134)
2015-07-31_10:25:12.16265       at java.util.regex.Pattern.expr(Pattern.java:1996)
2015-07-31_10:25:12.16265       at java.util.regex.Pattern.compile(Pattern.java:1696)
2015-07-31_10:25:12.16266       at java.util.regex.Pattern.<init>(Pattern.java:1351)
2015-07-31_10:25:12.16266       at java.util.regex.Pattern.compile(Pattern.java:1054)
2015-07-31_10:25:12.16266       at com.google.code.regexp.Pattern.buildStandardPattern(Unknown Source)
2015-07-31_10:25:12.16267       at com.google.code.regexp.Pattern.<init>(Unknown Source)
2015-07-31_10:25:12.16267       at com.google.code.regexp.Pattern.compile(Unknown Source)
2015-07-31_10:25:12.16268       at oi.thekraken.grok.api.Grok.compile(Grok.java:376)
2015-07-31_10:25:12.16268       at org.graylog2.rest.resources.tools.GrokTesterResource.doTestGrok(GrokTesterResource.java:83)
2015-07-31_10:25:12.16269       at org.graylog2.rest.resources.tools.GrokTesterResource.testGrok(GrokTesterResource.java:72)
2015-07-31_10:25:12.16269       at sun.reflect.GeneratedMethodAccessor301.invoke(Unknown Source)
2015-07-31_10:25:12.16272       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-07-31_10:25:12.16272       at java.lang.reflect.Method.invoke(Method.java:497)
2015-07-31_10:25:12.16273       at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
2015-07-31_10:25:12.16273       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164)
2015-07-31_10:25:12.16274       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181)
2015-07-31_10:25:12.16274       at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:203)
2015-07-31_10:25:12.16274       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101)
2015-07-31_10:25:12.16275       at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
2015-07-31_10:25:12.16275       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
2015-07-31_10:25:12.16276       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
2015-07-31_10:25:12.16277       at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305)
2015-07-31_10:25:12.16277       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
2015-07-31_10:25:12.16277       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
2015-07-31_10:25:12.16278       at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
2015-07-31_10:25:12.16278       at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
2015-07-31_10:25:12.16279       at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
2015-07-31_10:25:12.16279       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
2015-07-31_10:25:12.16279       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
2015-07-31_10:25:12.16280       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
2015-07-31_10:25:12.16280       at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
2015-07-31_10:25:12.16281       at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
2015-07-31_10:25:12.16281       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
2015-07-31_10:25:12.16282       at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
2015-07-31_10:25:12.16282       at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
2015-07-31_10:25:12.16283       at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
2015-07-31_10:25:12.16283       at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
2015-07-31_10:25:12.16284       at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
2015-07-31_10:25:12.16284       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-07-31_10:25:12.16285       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-07-31_10:25:12.16286       at java.lang.Thread.run(Thread.java:745)
```

I'm using graylog virtual appliance, version 1.1.4, with a global Raw/Plaintext TCP input.

**Comment by kroepke** [comment]
Will be fixed by upgrading to the java-grok:0.1.3-graylog fork.

Please note that due to Java's slightly "interesting" Date formatter, your pattern will not work, even with the hyphen bug fixed:
In the pattern the timezone format character must be `X` not  `Z`: `yyyy-MM-dd'T'HH:mm:ss.SSSX`

Please compare http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
