### ISSUE TITLE
StreamRouter timeout exception does not log the rule id

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#13499]
## Expected Behavior
The exception text should contain enough information for quickly identify while stream rule led to the error.

## Current Behavior
The only real information on default log levels is
> `2022-09-20T07:49:09.037Z WARN  [StreamRouterEngine] Unexpected error during stream matching
java.util.concurrent.TimeoutException: null`
<details>

```
2022-09-20T07:49:09.037Z WARN  [StreamRouterEngine] Unexpected error during stream matching
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:1.8.0_342]
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:162) ~[graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine$Rule.matchWithTimeOut(StreamRouterEngine.java:311) [graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine$Rule.access$000(StreamRouterEngine.java:268) [graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine.match(StreamRouterEngine.java:195) [graylog.jar:?]
        at org.graylog2.streams.StreamRouter.route(StreamRouter.java:99) [graylog.jar:?]
        at org.graylog2.filters.StreamMatcherFilter.filter(StreamMatcherFilter.java:42) [graylog.jar:?]
        at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:104) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.handleMessage(ProcessBufferProcessor.java:158) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:128) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:98) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:49) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
2022-09-20T07:49:09.037Z WARN  [StreamRouterEngine] Unexpected error during stream matching
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:1.8.0_342]
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:162) ~[graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine$Rule.matchWithTimeOut(StreamRouterEngine.java:311) [graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine$Rule.access$000(StreamRouterEngine.java:268) [graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine.match(StreamRouterEngine.java:195) [graylog.jar:?]
        at org.graylog2.streams.StreamRouter.route(StreamRouter.java:99) [graylog.jar:?]
        at org.graylog2.filters.StreamMatcherFilter.filter(StreamMatcherFilter.java:42) [graylog.jar:?]
        at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:104) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.handleMessage(ProcessBufferProcessor.java:158) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:128) [graylog.jar:?]
```

</details>

## Possible Solution
Add the current stream rule id and, if possible, additional information about the rule.

## Context
Regex stream rules, when they start backtracking, can lead to timeout exceptions. If you don't know which rule triggered it, it can become quite challenging finding the rule, especially if you have lots of them.

## Your Environment

* Graylog Version: 4.3

**Comment by neddy0graylog** [comment]
@bernd I currently I have a client experiencing the error, it would be great were it more verbose.

**Comment by neddy0graylog** [comment]
Such great service!

**Comment by mpfz0r** [comment]
Make sure we create a meaningful `ProcessingError` for this. 
Like here
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/plugin/inputs/Extractor.java#L228-L230
