### ISSUE TITLE
Main search page is showing 500.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-server#1351]
Hi,

With graylog-1.2.0-SNAPSHOT-20150811141408 and graylog-web-interface-1.2.0-SNAPSHOT-20150811093638 main search page fires an error:

```
2015-08-12 00:26:54,362 INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog server up and running.
2015-08-12 00:26:54,386 INFO : org.graylog2.shared.inputs.InputStateListener - Input [GELF UDP/55c9ad9fe4b0670114a9305c] is now STARTING
2015-08-12 00:26:54,407 WARN : org.graylog2.plugin.inputs.transports.NettyTransport - receiveBufferSize (SO_RCVBUF) for input GELFUDPInput{title=GELF, type=org.graylog2.inputs.gelf.udp.GELFUDPInput, nodeId=3e71487b-42d3-486c-8522-09d99f2672c1} should be 262144 but is 212992.
2015-08-12 00:26:54,414 INFO : org.graylog2.shared.inputs.InputStateListener - Input [GELF UDP/55c9ad9fe4b0670114a9305c] is now RUNNING
2015-08-12 00:26:58,811 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Enabling session validation scheduler...
2015-08-12 00:27:03,124 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.NullPointerException
        at org.graylog2.indexer.ranges.IndexRangeComparator.compare(IndexRangeComparator.java:27)
        at org.graylog2.indexer.ranges.IndexRangeComparator.compare(IndexRangeComparator.java:21)
        at java.util.TreeMap.compare(TreeMap.java:1291)
        at java.util.TreeMap.put(TreeMap.java:538)
        at java.util.TreeSet.add(TreeSet.java:255)
        at org.graylog2.indexer.IndexHelper.determineAffectedIndicesWithRanges(IndexHelper.java:120)
        at org.graylog2.indexer.searches.Searches.search(Searches.java:239)
        at org.graylog2.rest.resources.search.RelativeSearchResource.searchRelative(RelativeSearchResource.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Weird, that streams are working, dashboards ok, sources page is also fine. Messages are being saved to elasticsearch. Only page wires 500 is main search page.

Ideas?

**Comment by joschi** [comment]
We refactored/rewrote the index ranges handling in Graylog 1.2.0. Please recalculate all index ranges (e. g. System -> Indices -> Recalculate index ranges). After that the exception should vanish.

**Comment by timukas** [comment]
Index range recalculation fixed the problem.

Thanks,

Closing the case.
