### ISSUE TITLE
Query validation of invalid regex query causes HTTP500 instead of validation error

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#13594]
Query validation in the 4.3 release fails to correctly catch errors in validation of regex query, returning an HTTP500 error instead of 200 with a proper validation response. The stacktrace is:

```
ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.IllegalArgumentException: unexpected end-of-string
	at org.apache.lucene.util.automaton.RegExp.next(RegExp.java:1120) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseCharExp(RegExp.java:1267) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseSimpleExp(RegExp.java:1262) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseCharClassExp(RegExp.java:1194) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseComplExp(RegExp.java:1182) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseRepeatExp(RegExp.java:1151) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseInterExp(RegExp.java:1137) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseUnionExp(RegExp.java:1131) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseSimpleExp(RegExp.java:1223) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseCharClassExp(RegExp.java:1194) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseComplExp(RegExp.java:1182) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseRepeatExp(RegExp.java:1151) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseInterExp(RegExp.java:1137) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseUnionExp(RegExp.java:1131) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.parseUnionExp(RegExp.java:1132) ~[graylog.jar:?]
	at org.apache.lucene.util.automaton.RegExp.<init>(RegExp.java:487) ~[graylog.jar:?]
	at org.apache.lucene.search.RegexpQuery.<init>(RegexpQuery.java:144) ~[graylog.jar:?]
	at org.apache.lucene.search.RegexpQuery.<init>(RegexpQuery.java:126) ~[graylog.jar:?]
	at org.apache.lucene.search.RegexpQuery.<init>(RegexpQuery.java:93) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParserBase.newRegexpQuery(QueryParserBase.java:576) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.validation.TokenCollectingQueryParser.newRegexpQuery(TokenCollectingQueryParser.java:73) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParserBase.getRegexpQuery(QueryParserBase.java:758) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParserBase.handleBareTokenQuery(QueryParserBase.java:824) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParser.Term(QueryParser.java:469) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:355) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:303) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:359) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:303) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.validation.LuceneQueryParser.parse(LuceneQueryParser.java:43) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.validation.QueryValidationServiceImpl.validate(QueryValidationServiceImpl.java:83) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.rest.QueryValidationResource.validateQuery(QueryValidationResource.java:82) ~[graylog.jar:?]
	at sun.reflect.GeneratedMethodAccessor1470.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_342]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
```

## Expected Behavior
The exception should be caught and proper validation response returned. 

## Current Behavior
The exception gets propagated as is, causing troubles on the way. In the current master, we catch all types of exceptions, not just ParseException, which mitigates the problem. 
 
## Possible Solution
Backport the generic error catch to the 4.3 release.

**Comment by todvora** [comment]
Backported, closing.
