### ISSUE TITLE
Search AutoValue_QueryDTO$Builder Error   (Graylog 5.0.0-beta.1+a22c633 )

### ISSUE THREAD

**Issue by B3K7** [Graylog2/graylog2-server#13808]
navigate to graylog : Login : select search : then BOOM - observe the following:

Something went wrong
An unknown error has occurred. Please have a look at the following message and the graylog server log for more information.
There was an error fetching a resource: Bad Request. Additional information: Cannot construct instance of `org.graylog.plugins.views.search.searchtypes.pivot.Pivot$Builder`, problem: Missing required properties: rollup
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 449] (through reference chain: org.graylog.plugins.views.search.rest.AutoValue_SearchDTO$Builder["queries"]->java.util.LinkedHashSet[0]->org.graylog.plugins.views.search.rest.AutoValue_QueryDTO$Builder["search_types"]->java.util.HashSet[0])

Alternatively navigate to graylog server : login : select System/ Inputs : Inputs : Select show received messages.  Boom - observe the same problem as above

The problem seemd to begin after upgrading to graylog-server/stable,now 5.0.0-2.beta.1 - from graylog-server/stable,now 5.0.0-0.beta.1 

FYI  Issues appears to persists through an uninstall and re-install of graylog-enterprise-integrations-plugins graylog-enterprise-plugins graylog-server. 

i.e. is it in elastic search, mongodb or graylog?

## Expected Behavior

Ability to search

Should I remove graylog-plugin-enterprise-integrations-4.3.8.jar?

## Current Behavior

Unable to search

Error logs
2022-10-26T22:13:26.324-04:00 WARN  [Errjava.util.ServiceConfigurationError: io.jsonwebtoken.CompressionCodec: Error accessing configuration file
        at java.util.ServiceLoader.fail(ServiceLoader.java:586) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1180) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1213) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[?:?]
        at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[?:?]
        at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[?:?]
        at io.jsonwebtoken.impl.lang.Services.loadAll(Services.java:80) ~[?:?]
        at io.jsonwebtoken.impl.lang.Services.loadAll(Services.java:68) ~[?:?]
        at io.jsonwebtoken.impl.compression.DefaultCompressionCodecResolver.<init>(DefaultCompressionCodecResolver.java:57) ~[?:?]
        at io.jsonwebtoken.impl.DefaultJwtParser.<init>(DefaultJwtParser.java:51) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:157) ~[?:?]
        at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:137) ~[?:?]
        at io.jsonwebtoken.Jwts.parser(Jwts.java:124) ~[?:?]
        at org.graylog.plugins.license.JwtParserProvider.get(JwtParserProvider.java:22) ~[?:?]
        at org.graylog.plugins.license.JwtParserProvider.get(JwtParserProvider.java:12) ~[?:?]
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86) ~[graylog.jar:?]
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72) ~[graylog.jar:?]
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:59) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[graylog.jar:?]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[graylog.jar:?]
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[graylog.jar:?]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[graylog.jar:?]
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[graylog.jar:?]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[graylog.jar:?]
        at com.google.inject.internal.RealOptionalBinder$RealDirectTypeProvider.doProvision(RealOptionalBinder.java:385) ~[graylog.jar:?]
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[graylog.jar:?]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[graylog.jar:?]
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[graylog.jar:?]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[graylog.jar:?]
        at com.google.inject.internal.RealOptionalBinder$RealDirectTypeProvider.doProvision(RealOptionalBinder.java:385) ~[graylog.jar:?]
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[graylog.jar:?]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:206) ~[graylog.jar:?]
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:159) ~[graylog.jar:?]
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[graylog.jar:?]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[graylog.jar:?]
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60) ~[graylog.jar:?]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[graylog.jar:?]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[graylog.jar:?]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:206) ~[graylog.jar:?]
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:159) ~[graylog.jar:?]
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113) ~[graylog.jar:?]
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50) ~[graylog.jar:?]
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[graylog.jar:?]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[graylog.jar:?]
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:58) ~[graylog.jar:?]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[graylog.jar:?]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[graylog.jar:?]
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213) ~[graylog.jar:?]
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186) ~[graylog.jar:?]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113) ~[graylog.jar:?]
        at com.google.inject.Guice.createInjector(Guice.java:87) ~[graylog.jar:?]
        at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34) ~[graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:502) ~[graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:306) ~[graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:260) [graylog.jar:?]
        at org.graylog2.bootstrap.Main.main(Main.java:45) [graylog.jar:?]
Caused by: java.nio.file.NoSuchFileException: /usr/share/graylog-server/plugin/graylog-plugin-enterprise-integrations-4.3.8.jar
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148) ~[?:?]
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
        at java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1264) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103) ~[?:?]
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72) ~[?:?]
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:168) ~[?:?]
        at sun.net.www.protocol.jar.JarFileFactory.getOrCreate(JarFileFactory.java:91) ~[?:?]
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:132) ~[?:?]
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:175) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1172) ~[?:?]
        ... 136 more
ors] The following warnings have been detected: WARNING: Return type, org.graylog2.rest.models.tools.responses.PageListResponse<? extends org.graylog.plugins.searchfilters.model.usage.SearchFilterUsage>, of method, public org.graylog2.rest.models.tools.responses.PageListResponse<? extends org.graylog.plugins.searchfilters.model.usage.SearchFilterUsage> org.graylog.plugins.searchfilters.rest.SearchFiltersUsageResource.getPage(java.lang.String,int,int,java.lang.String,org.graylog.plugins.searchfilters.model.usage.SearchFilterUsageType,java.lang.String,java.lang.String,org.graylog.plugins.views.search.permissions.SearchUser), is not resolvable to a concrete type.

## Steps to Reproduce (for bugs)

1.
Using a web browser : navigate to graylog : Login : select search : then BOOM - observe problem
2.
Using a web browser : navigate to graylog server : login : select System/ Inputs : Inputs : Select show received messages.  Boom - observe problem
3.
4.

## Context

I was expecting to be able to search.

## Your Environment

* Graylog Version:
https://packages.graylog2.org/repo/debian/ stable 5.0 (latest)

* Java Version:
openjdk 17

* Elasticsearch Version:
https://artifacts.elastic.co/packages/oss-7.x/apt stable main

* MongoDB Version:
http://repo.mongodb.org/.../mongodb-org/5.0 main

* Operating System:
debian bullseye

* Browser version:
Chrome / Firefox / Edge

**Comment by B3K7** [comment]
Extracted the tgz, added the 5.0 plugins to 4.3 production, added the 5.0
binaries to 4.3 production.  Made the necessary symbolic link updates.
Observed that the system failed.  Reverted to graylog 4.3.  undid the
symbolic links.

Changed the package metadata to graylog 5.0.

Upgraded the packages to 5.0. teeny tiny 1.
Verified everything worked.

Upgraded to 5.0. Teeny tiny 2.  Boom

*Verified that all traces of graylog 4.3 are gone*.

**Comment by B3K7** [comment]
FYI Issue persists through uninstall and re-install of graylog-enterprise-integrations-plugins graylog-enterprise-plugins graylog-server packages.  i.e. is it elastic search, mongodb or graylog or some combination?

**Comment by B3K7** [comment]
![boom](https://user-images.githubusercontent.com/79159661/198581234-31839421-f69b-45e5-a5f2-b77c67b01501.png)

**Comment by B3K7** [comment]
Removed graylog completely
Verified that there were no residual artifacts 
installed graylog-enterprise-integrations-plugins graylog-enterprise-plugins graylog-server
started graylog and BOOM.  Issue occured again.

**Comment by bernd** [comment]
@B3K7 Thanks for the update. I will try to reproduce the problem and fix it.

**Comment by B3K7** [comment]
Thx.

Do I need to truncate the elastic search database and the mongo database?

Re migrating to opensearch: I looked into  opensearch 2.3 latest.  I could
find my preferred package type.  Hopefully they consider offering more
install options going forwards.

**Comment by B3K7** [comment]
Correction: I couldn't find my preferred package type.

**Comment by B3K7** [comment]
#stop graylog-server
#truncate mongo database
mongo : show dbs : use graylog : db.dropDatabase() : exit
#truncate elastic search database
curl -X DELETE "localhost:9200/*?pretty" 
{
  "acknowledged" : true
}
#start graylog-server
BOOM.

**Comment by B3K7** [comment]
There is an 80% chance that there is an issue is in 5.0.0-2.beta.1.
Recommend
- rolling forwards to 5.0.0-3+.beta.1 OR 
- rolling back to 5.0.0-1.beta.1

**Comment by B3K7** [comment]
root@mon01:~#  sed 's/^#.*$//g' /etc/graylog/server/server.conf | grep -v -G "^$"
is_leader = true
password_secret = 'Some weak secret"
root_username = '<some name>'
root_password_sha2 = '<some weak hash>'

node_id_file = /etc/graylog/server/node-id
bin_dir = /usr/share/graylog-server/bin
plugin_dir = /usr/share/graylog-server/plugin
data_dir = /var/lib/graylog-server
message_journal_dir = /var/lib/graylog-server/journal

http_bind_address = 127.0.0.1:<someport>

elasticsearch_hosts = http://127.0.0.1:<some port>
elasticsearch_version = 7
elasticsearch_discovery_default_scheme = https
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 4
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard

output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_max_size = 4gb
lb_recognition_period_seconds = 3

mongodb_uri = mongodb://localhost/graylog
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5

proxied_requests_thread_pool_size = 32

**Comment by B3K7** [comment]
Do I need to truncate ?
- graylog data dir 
- graylog message journal dir

**Comment by B3K7** [comment]
graylog data dir

# find . -type f
./journal/recovery-point-offset-checkpoint
./journal/.kafka_cleanshutdown
./journal/.lock
./journal/graylog2-committed-read-offset
./journal/messagejournal-0/00000000000012804224.index
./journal/messagejournal-0/00000000000012804224.log
# find . -type f -print0 | xargs -0 rm

**Comment by B3K7** [comment]
No change.
There was an error fetching a resource: . Additional information: Cannot construct instance of `org.graylog.plugins.views.search.searchtypes.pivot.Pivot$Builder`, problem: Missing required properties: rollup
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 449] (through reference chain: org.graylog.plugins.views.search.rest.AutoValue_SearchDTO$Builder["queries"]->java.util.LinkedHashSet[0]->org.graylog.plugins.views.search.rest.AutoValue_QueryDTO$Builder["search_types"]->java.util.HashSet[0])

**Comment by B3K7** [comment]
upgraded to 5.0.0-5.beta.1.  issue resolved.

**Comment by bernd** [comment]
@B3K7 Thanks for the update!
