### ISSUE TITLE
Unable to send emails through Office365 SMTP server

### ISSUE THREAD

**Issue by kvenkat971** [Graylog2/graylog2-server#1381]
not able to send the email alrets in graylog 1.1.4 even though the credentials are correct it is still saying the crdetials are wrong...

```
2015-08-31T13:01:26.640+01:00 ERROR [EmailAlarmCallback] Stream [55e036ab45ce809bff479bef: "ALL Error messages"] has alert receivers and is triggered, but sending emails failed
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.office365.com:587
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
	at org.apache.commons.mail.Email.send(Email.java:1448)
	at org.graylog2.alerts.StaticEmailAlertSender.sendEmail(StaticEmailAlertSender.java:118)
	at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:247)
	at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:80)
	at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:69)
	at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:158)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.mail.AuthenticationFailedException: 535 5.7.3 Authentication unsuccessful

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:892)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:814)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:728)
	at javax.mail.Service.connect(Service.java:386)
	at javax.mail.Service.connect(Service.java:245)
	at javax.mail.Service.connect(Service.java:194)
	at javax.mail.Transport.send0(Transport.java:253)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
	... 38 more
```

**Comment by kvenkat971** [comment]
any updates on the above bug in graylog.

**Comment by joschi** [comment]
Please set the logging level for `com.sun.mail.smtp` to `TRACE` (see https://github.com/Graylog2/graylog2-server/blob/1.1.6/graylog2-bootstrap/src/main/resources/log4j.xml) and retry sending the test email. There should be some more detailed message in the logs after that.

**Comment by joschi** [comment]
@kvenkat971 Any news?

**Comment by kvenkat971** [comment]
@joschi sorry for the delay though i get the same output as above after changing also.

**Comment by mikkolehtisalo** [comment]
This should work just fine, at least using SMTP client submission (see [here](https://technet.microsoft.com/en-us/library/dn554323(v=exchg.150).aspx)). Couple notes from my testing:

- The SMTP service requires StartTLs instead of SMTPS. Correct configuration is `transport_email_use_ssl = false` and `transport_email_use_tls = true`
- Authentication is required, and the username must be valid email address, for example myuser@mydomain.com
- The SMTP service checks that the sender of emails and the account name (email address) match, or that the user has otherwise rights to use the sender address
- Depending on the used JRE and the default Java trust store it might be necessary to download the server certificate, and add it to either default trust store or configure a new one. Otherwise the StartTLS might whine about invalid certificate chain.
- The SMTP service of Office 365 will throttle email sending to 30 per minute, or maximum 10 000 recipients per day.
- Office 365 requires commonly that users change their passwords regularly. The SMTP service may not notify the user about expired password. 
- 5.7.3 is the most generic "Authentication unsuccessful" error code Exchange is able to provide. It most usually means that the username and password really were wrong, or some of the rules above were broken.

graylog.conf:
```
transport_email_enabled = true
transport_email_hostname = smtp.office365.com
transport_email_port = 587
transport_email_use_auth = true
transport_email_use_tls = true
transport_email_use_ssl = false
transport_email_auth_username = user@mydomain.com
transport_email_auth_password = password
transport_email_subject_prefix = [graylog]
transport_email_from_email = user@mydomain.com
```

Enabling smtp debug logging:
```
<Logger name="com.sun.mail.smtp" level="TRACE"/>
```
Setting up the certificate, if necessary:
```
# Get the certificate
openssl s_client -showcerts -connect 192.168.122.12:587 -starttls smtp </dev/null
# Save the certificate to /tmp/cert.pem
# Create an empty keystore
keytool -genkey -alias foo -keystore /etc/ssl/graylog.jks
keytool -delete -alias foo -keystore /etc/ssl/graylog.jks
# Import the certificate to the keystore
keytool -import -trustcacerts -alias root -file /tmp/cert.pem -keystore /etc/ssl/graylog.jks
# Add the keystore to the command line parameters for Java
-Djavax.net.ssl.trustStore=/etc/ssl/graylog.jks -Djavax.net.ssl.trustStorePassword=password
```

**Comment by haythem11** [comment]
thank you @mikkolehtisalo 
how download and install the server certificate ???
help please !!!!!

**Comment by haythem11** [comment]
help please !!!!!

**Comment by joschi** [comment]
@haythem11 We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by JuliusCaeser** [comment]
having this issue, using gmail. Could it be that if I change to office365 it'd work?

my config:

transport_email_enabled = true
transport_email_hostname = smtp.gmail.com
transport_email_port = 587
transport_email_use_auth = true
transport_email_use_tls = true
transport_email_use_ssl = false
transport_email_auth_username = email
transport_email_auth_password = password
transport_email_subject_prefix = [graylog]
transport_email_from_email = graylog@example.com

**Comment by jaggijaks** [comment]
> having this issue, using gmail. Could it be that if I change to office365 it'd work?
> 
> my config:
> 
> transport_email_enabled = true
> transport_email_hostname = smtp.gmail.com
> transport_email_port = 587
> transport_email_use_auth = true
> transport_email_use_tls = true
> transport_email_use_ssl = false
> transport_email_auth_username = email
> transport_email_auth_password = password
> transport_email_subject_prefix = [graylog]
> transport_email_from_email = [graylog@example.com](mailto:graylog@example.com)
> 
> My Error is: An error occurred while trying to send an email! (triggered 9 minutes ago)
> The Graylog server encountered an error while trying to send an email. This is the detailed error message: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:587 (com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 587; timeout 60000; nested exception is: java.net.SocketTimeoutException: connect timed out)
> 
> Tried to telnet to smtp.gmail.com 587 but nothing

getting same issue
