### ISSUE TITLE
Graylog-web produce lot of stack trace

### ISSUE THREAD

**Issue by rlanore** [Graylog2/graylog2-server#1383]
hi,

application.secret in web.conf and password_secret in server.conf are same 
But i have lot of stack trace server.log on graylog-server with this field equal to:

```
QgfVNwQg1WRA1AHUnJWXDf5cgH9NeL0gpKMQ4dnnmkfUkV05QEt75AKpQgQFGSRu9ODdlqbyGnCcHGRjc7CPxaezC3CZ1DWaHsKkSxualsGjecZTyv2bRFnIMc0nIfZQksmyY1MjkAmOjJRhvlKjJ6L0FlzxqFssfDGwpUizEKUkxNYdwvn4UhujgTaBcHqjFJRjwjijBuIcz5r48N03DN7wF5Eh6bi9XWTyRUEblVuCDZ6eUD5KiX2F5E2FJnFlL98cFEFYnES4XoeiRAunPVUMDygdRLXoOgBA8MX0Sp39f7eCGRxheoDGwTzDu5eqPAJIpa6IZ4MUAP8F3QxLZtSHp6fJWHPl7elOO5EhDOl9IbGPaQw7dPKT1cm9PFnL9LB7vwl9cQmIsuy5V5dTXifF1sjg8zA1SjdSChoOXnr819uyQNXHs78t5iaiaZShqaZ7RSrQ8SEnsZ2BAmWpLzsXBkmNoSypYWIO5s0mzMSiaMSwMbNa2MeaDanPv4Gz7pEzq8eJWD4SrCwqm7XEjNAcbATiY22442DsZa7n1zHNqFpmcLP4HJhJwLmZseQYhPidJ4VFTk363RCOib5bgTemrGG5IGRnOkDRZmNgTt7F7XK5K3quGpOriOALKSfbzZ47pGyFGTCP1TAmLkxwDuOKxdPKeW6iTyjrFZAgH9wABESxc5dyopJm716YVmxaPHpNQVWSxCGOGX9VuiJ8Wl034Yfmla0QivSLMAOE3FFjfXYODNPc8Plx37I3NZA37V88SojqftFe06m4ag9ntiOMErXWFrJrMnVaPzvr7TPAZTMPVFjzA5qF8VHbRozP6wc2x72iVMQpkqgmHiVKXGb3k2C2u4sBL6xQd2URSM21QLEK1buaq4M5eQNYQGqIrydkPGzstLGnrGnh6ib41aIebAqvKaS8A2ijqBAqG00RdXLds2guDcQ55weXMOXhV652Nb1JuI0ZDilaz8cvpc8qkUDtqMeOhHXtA6eCrwUbfL6WziCR4SrjpwIM282zdbQ9wibAH6v8JOPB8pQn6El1d1s7unPfQ7EGdQLdcQYsjWr1PZw9lKgw5fJCYQ35xuD5imvaO7dReanak64fAj6V8YCddrCKarPsgxaasRh88Mq9XZBU7mVZqcBis0RtZd6wSvVMzKP6QqPmspPeXq8uNH3KlJH2FYaYAyW3HvIHqkEObD0W6L0U5l1gX7zYrn2arhgplWXWQrYfqmB0nhP23uBwznLipFlHoTSEYW5iamNwMpNPMKTWnRnSphZcj5TvdlLGAvm6EE9AWAouWMqDupIMPgPAYaqXjjTEYCZkcFhHqX7QsipVz2inINO8lrgtzwPCEvCVoaa72B1XmOHvsbUUi6SaL7eODPkuq9kLxgNkcbFPJvGl50TBKYWt1qukg3lTuc5w7xdlIUbtCR98QORnvj1vdU0qE8lEXOUX65uhDqNsN0M641MMBNaOFX5mshzcs22v8lFk942S0GLmhp3BnGXaXal2bQyYmQNgHZgKDv8BQb3xOBYUbV5wIceMeWZBwUavuCfVAqRo2HY4ZWPNATCcL0jSdYvWHIx66Rg4n1TMuWhBt4AV9Sooz4DbwKIo66GRBq76rvVpdGYMSJU6y3UzPpNr7bkOjnL3vQm04zBE582rPHK7P1KsmDYVIW1NUi353yr2E3hKqubbEtqDIocYfqWBYtNA86aj3OON0mMAlvJEMVJ37aNix7UPztwHtQUwyHCyiqyplBdXLe9Y6OhLqSjf5hsqoiU3cRkkIxrz3AK1rgPjynQBWMxuew4R2DIj27EmaudDlSG2fwu3fc1o6hrizhzgJHCxGfWPZv6lJAnMC2aeb150zl2vakdzKZEjKjnxjigvKQlx69VIwj6ErzHPtvHH3iQ3locPBTkJBq0CjCEG5mbk
```

But no probleme with 

```
totototototototototo
```

```
ii  graylog-server                           1.1.6-1                       all          Graylog server
ii  graylog-web                              1.1.6-1                       all          Graylog web

```

```
2015-09-01T09:20:02.814Z DEBUG [accesslog] 10.1.23.19 d77f4475-f2e1-4d55-94da-811ed6549caa [Tue Sep 01 09:20:02 UTC 2015] "POST system/metrics/multiple" graylog2-web/1.1.6 (2e264c2) 401 -1
2015-09-01T09:20:02.814Z DEBUG [NettyContainer] Closing connection to /10.1.23.19:48204
2015-09-01T09:20:02.818Z DEBUG [MongoDbSessionDAO] Reading session for id d77f4475-f2e1-4d55-94da-811ed6549caa from MongoDB: null
2015-09-01T09:20:02.818Z DEBUG [DefaultSecurityManager] Resolved SubjectContext context session is invalid.  Ignoring and creating an anonymous (session-less) Subject instance.
org.apache.shiro.session.UnknownSessionException: There is no session with id [d77f4475-f2e1-4d55-94da-811ed6549caa]
	at org.apache.shiro.session.mgt.eis.AbstractSessionDAO.readSession(AbstractSessionDAO.java:170)
	at org.apache.shiro.session.mgt.eis.CachingSessionDAO.readSession(CachingSessionDAO.java:261)
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSessionFromDataSource(DefaultSessionManager.java:236)
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSession(DefaultSessionManager.java:222)
	at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:118)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:108)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getSession(AbstractNativeSessionManager.java:100)
	at org.apache.shiro.mgt.SessionsSecurityManager.getSession(SessionsSecurityManager.java:125)
	at org.apache.shiro.mgt.DefaultSecurityManager.resolveContextSession(DefaultSecurityManager.java:456)
	at org.apache.shiro.mgt.DefaultSecurityManager.resolveSession(DefaultSecurityManager.java:442)
	at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:338)
	at org.apache.shiro.subject.Subject$Builder.buildSubject(Subject.java:846)
	at org.graylog2.security.realm.SessionAuthenticator.doGetAuthenticationInfo(SessionAuthenticator.java:52)
	at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:568)
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:219)
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269)
	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270)
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
	at org.graylog2.shared.security.ShiroSecurityContext.loginSubject(ShiroSecurityContext.java:97)
	at org.graylog2.shared.security.ShiroAuthenticationFilter.filter(ShiroAuthenticationFilter.java:47)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:297)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-09-01T09:20:02.819Z DEBUG [SessionAuthenticator] Invalid session d77f4475-f2e1-4d55-94da-811ed6549caa. Either it has expired or did not exist.
2015-09-01T09:20:02.819Z DEBUG [AuthenticatingRealm] Looked up AuthenticationInfo [null] from doGetAuthenticationInfo
2015-09-01T09:20:02.819Z DEBUG [AuthenticatingRealm] No AuthenticationInfo found for submitted AuthenticationToken [org.graylog2.security.SessionIdToken@7f9607f7].  Returning null.
2015-09-01T09:20:02.819Z DEBUG [ModularRealmAuthenticator] Realm [org.graylog2.security.realm.AccessTokenAuthenticator@39c3bb2] does not support token org.graylog2.security.SessionIdToken@7f9607f7.  Skipping realm.
2015-09-01T09:20:02.819Z DEBUG [ModularRealmAuthenticator] Realm [org.graylog2.security.realm.LdapUserAuthenticator@1002c307] does not support token org.graylog2.security.SessionIdToken@7f9607f7.  Skipping realm.
2015-09-01T09:20:02.819Z DEBUG [ModularRealmAuthenticator] Realm [org.graylog2.security.realm.PasswordAuthenticator@34899d1a] does not support token org.graylog2.security.SessionIdToken@7f9607f7.  Skipping realm.
2015-09-01T09:20:02.819Z DEBUG [ModularRealmAuthenticator] Realm [org.graylog2.security.realm.GraylogSimpleAccountRealm@36a930e8] does not support token org.graylog2.security.SessionIdToken@7f9607f7.  Skipping realm.
2015-09-01T09:20:02.819Z DEBUG [ShiroAuthenticationFilter] Unable to authenticate user.
org.apache.shiro.authc.AuthenticationException: No account information found for authentication token [org.graylog2.security.SessionIdToken@7f9607f7] by this Authenticator instance.  Please check that it is configured correctly.
	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:202)
	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270)
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
	at org.graylog2.shared.security.ShiroSecurityContext.loginSubject(ShiroSecurityContext.java:97)
	at org.graylog2.shared.security.ShiroAuthenticationFilter.filter(ShiroAuthenticationFilter.java:47)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:297)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-09-01T09:20:02.819Z DEBUG [accesslog] 10.1.23.19 d77f4475-f2e1-4d55-94da-811ed6549caa [Tue Sep 01 09:20:02 UTC 2015] "POST system/metrics/multiple" graylog2-web/1.1.6 (2e264c2) 401 -1

```

**Comment by edmundoa** [comment]
Hi,

All the stack traces in the logs you shared are only intended for debugging purposes, if you don't experience any problems with Graylog server you should run it without the `--debug` flag.

We keep Github for tracking bugs in the software, please use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general questions about Graylog.
