### ISSUE TITLE
Automated index rotation failed because of closed index

### ISSUE THREAD

**Issue by BaptisteBdn** [Graylog2/graylog2-server#13872]
## Expected Behavior
Graylog should rotate the index daily but fails to do so automatically. 

## Current Behavior
When graylog tries to rotate the current write index, it crashes with the following error :
```
2022-11-03T10:41:33.596+01:00 ERROR [IndexRotationThread] Couldn't point deflector to a new index
org.graylog2.indexer.ElasticsearchException: Couldn't check stats of index graylog_687

closed
```
However the current write-index is graylog_931. When I checked the graylog_deflector index, it is indeed graylog_931.
I have the exact same setup in another index set and it is working perflecty fine. 
I believe Graylog is trying to rotate the wrong index 

Doing a manual rotation works. 

Any idea what to check ?

## Your Environment

* Graylog Version: 4.3.9
* Elasticsearch Version: 6.8.23

**Comment by dennisoelkers** [comment]
Hey @BaptisteBdn,

thanks for reporting this. Are there any additional lines in your log, e.g. a stack trace? Also, what is the current status of the `graylog_687` index?

**Comment by BaptisteBdn** [comment]
Hi @dennisoelkers, 

Here is the full stacktrace : 
```
2022-11-03T10:41:33.596+01:00 ERROR [IndexRotationThread] Couldn't point deflector to a new index
org.graylog2.indexer.ElasticsearchException: Couldn't check stats of index graylog_687

closed
        at org.graylog.storage.elasticsearch6.jest.JestUtils.specificException(JestUtils.java:135) ~[?:?]
        at org.graylog.storage.elasticsearch6.jest.JestUtils.execute(JestUtils.java:72) ~[?:?]
        at org.graylog.storage.elasticsearch6.jest.JestUtils.execute(JestUtils.java:77) ~[?:?]
        at org.graylog.storage.elasticsearch6.IndicesAdapterES6.indexStats(IndicesAdapterES6.java:446) ~[?:?]
        at org.graylog.storage.elasticsearch6.IndicesAdapterES6.numberOfMessages(IndicesAdapterES6.java:438) ~[?:?]
        at org.graylog2.indexer.indices.Indices.numberOfMessages(Indices.java:125) ~[graylog.jar:?]
        at org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategy.isEmptyIndexSet(TimeBasedRotationStrategy.java:243) ~[graylog.jar:?]
        at org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategy.shouldRotate(TimeBasedRotationStrategy.java:224) ~[graylog.jar:?]
        at org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy.rotate(AbstractRotationStrategy.java:71) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexRotationThread.checkForRotation(IndexRotationThread.java:113) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:77) ~[graylog.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_275]
        at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:94) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

The graylog_687 is closed , when doing the following elasticsearch request : `/graylog_687/_stats`
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_closed_exception",
        "reason" : "closed",
        "index_uuid" : "IUrP6o9QSvSDOWUkqbMQbg",
        "index" : "graylog_687"
      }
    ],
    "type" : "index_closed_exception",
    "reason" : "closed",
    "index_uuid" : "IUrP6o9QSvSDOWUkqbMQbg",
    "index" : "graylog_687"
  },
  "status" : 400
}
```

**Comment by dennisoelkers** [comment]
Thanks for that. Can you also do a `GET` on `/_cat/aliases` of your Elasticsearch node and include the results, at least the line with the `graylog_deflector` entry?

**Comment by BaptisteBdn** [comment]
The `graylog_deflector` entry : 
```
graylog_deflector          graylog_932         - - -
```

**Comment by BaptisteBdn** [comment]
I still don't know why this problem happened but I managed to fix it simply by reopening index graylog_687 which allowed graylog to automatically rotate from graylog_932 to graylog_933.

**Comment by dennisoelkers** [comment]
Hey @BaptisteBdn,

thanks for the update. Great to hear that the problem is fixed for you, but it looks like there might be an issue nonetheless. Reopening the index should not be necessary for rotation to work properly, therefore I am reopening the issue for further investigation.
