### ISSUE TITLE
Active Directory User Lookup fails

### ISSUE THREAD

**Issue by octomike** [Graylog2/graylog2-server#1410]
I know we are using LDAP referrals at our site, ist by any chance not yet supported in the apache ldap client library ?

The test connection works fine, but I am unable to actually lookup any users. I double checked baseDN and search pattern, they're fine.

**Update**: Login was actually successfull, but the LDAP Settings page fails to test for users. This is not a dramatic bug, but very misleading.

```
2015-09-10T01:49:46.782+02:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.RuntimeException: ERR_02002_FAILURE_ON_UNDERLYING_CURSOR Failure on underlying Cursor.
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:86)
        at org.graylog2.security.ldap.LdapConnector.search(LdapConnector.java:127)
        at org.graylog2.rest.resources.system.ldap.LdapResource.testLdapConfiguration(LdapResource.java:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.directory.api.ldap.model.cursor.CursorLdapReferralException
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:164)
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:50)
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:80)
        ... 34 more
```

Happens with graylog 1.2.0-4.rc.4

**Comment by kroepke** [comment]
It's possible, we've hit a similar problem yesterday when fixing a performance issue with group resolution.

I'll check with the LDAP library.

**Comment by kroepke** [comment]
There's also https://s3-eu-west-1.amazonaws.com/pre-release-snapshots/graylog-1.2.0-rc.5-SNAPSHOT-20150909154719.tar.gz that requests fewer attributes, if you could give that a try that would be very helpful. It is compatible with 1.2.0-4.rc.4 web interface.

**Comment by kroepke** [comment]
In an ever helpful manner, the apache library chose to have:
    private ReferralsPolicyEnum referralHandling = ReferralsPolicyEnum.THROW;
as its default.
It appears they have more helpful policies, which we'll try to make it use.

**Comment by octomike** [comment]
Group resolution is not working at all for us unfortunately.

I'm quite new to graylog and I set it up with the puppet module so I need figure out how to deploy a new version first, before I can test rc5.

**Comment by kroepke** [comment]
You can simply replace the graylog-server.jar if you quickly want to test it.

**Comment by octomike** [comment]
Ah yis. Success with rc5 for "Login Test".

Group lookup is still failing:

```
2015-09-10T12:53:34.558+02:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.RuntimeException: ERR_02002_FAILURE_ON_UNDERLYING_CURSOR Failure on underlying Cursor.
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:86)
        at org.graylog2.security.ldap.LdapConnector.findGroups(LdapConnector.java:219)
        at org.graylog2.security.ldap.LdapConnector.listGroups(LdapConnector.java:267)
        at org.graylog2.rest.resources.system.ldap.LdapResource.readGroups(LdapResource.java:303)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.directory.api.ldap.model.cursor.CursorLdapReferralException
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:164)
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:50)
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:80)
        ... 35 more

```

**Comment by bonzi316** [comment]
Hi,

I got the same error.  I teste the rc5 and same issue.  I put my base the same as my user (Base of my forest in my AD ex: DC=example,DC=org) But if I put one level under (OU=Groups, DC=example, DC=com) it works.  Since my groups a spreaded in differents OU under my root of my AD, I need to be able to put my ROOT path in the group mapping.  Any idea why it fails ?

Thanks

**Comment by kroepke** [comment]
Apparently there's a referral coming back and the default of the client library we use throws that exception.
I'll put up a snapshot tomorrow to see if we can get rid of this.

**Comment by bonzi316** [comment]
I confirm, with your latest snapshot from this morning, it work as expected.  But still having error in the graylog-server log files, but the group are found and map correctly.

Thanks

**Comment by octomike** [comment]
I can confirm this as well. Although the Error ist just warning with a dead link in my case 8)
