### ISSUE TITLE
Email alert callback encoding problem

### ISSUE THREAD

**Issue by 2fa** [Graylog2/graylog2-server#1435]
We have a standard email callback configuration:

```
body: 
##########
Alert Description: ${check_result.resultDescription}
Date: ${check_result.triggeredAt}
Stream ID: ${stream.id}
Stream title: ${stream.title}
Stream description: ${stream.description}
${if stream_url}Stream URL: ${stream_url}${end}
Triggered condition: ${check_result.triggeredCondition}
##########
${if backlog}Last messages accounting for this alert:
${foreach backlog message}${message}
${end}${else}<No backlog>
${end} 

sender: 
graylog@***

subject: 
Graylog alert for stream: ${stream.title}: ${check_result.resultDescription}
```

Everything works fine, except that ${message} contain question marks instead of cyrillic symbols.

For example, here we've got message from the graylog web interface:
```
arg_0:
	System.TimeoutException: An asynchronous operation exceeded the…
callstack:
   	at Bru.Web.LayeredHttpApplication.HandleError() in C:\projects\***\lib\Web\Core\LayeredHttpApplication.cs:line 231
   	at System.Web.HttpApplication.RaiseOnError()
   	at System.Web.HttpApplication.RecordError(Exception error)
   	at System.Web.HttpApplication.PipelineStepManager.ResumeSteps(Exception error)
   	at System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb)
   	at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)
   	at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
   	at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
   	at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)
   	at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)
   	at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
   	at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
correlation_id:
	801cb2d8-0000-e900-b63f-84710c7967bb
event_id:
	3
from:
	Bru.Web.LayeredHttpApplication
full_message:
	Необработанное исключение.
	Exception: System.TimeoutException: An asynchronous operation exceeded the page timeout.
   	at System.Web.UI.Page.<ProcessRequestAsync>d__2.MoveNext().
identity:
	Bru.Web:18V24D
level:
	3
message:
	Необработанное исключение.
process_id:
	1052
source:	
	***:/LM/W3SVC/3/ROOT
thread_id:
	87
time:
	959145939.2517
version:
	1.1
```
...and here -- from the email callback:
```
Last messages accounting for this alert:
source: ***:/LM/W3SVC/3/ROOT | message: ?????????????? ??????????. { process_id: 1052 | level: 3 | streams: [55f46a81498e635ce450c949] | callstack: at Bru.Web.LayeredHttpApplication.HandleError() in C:\projects\***\lib\Web\Core\LayeredHttpApplication.cs:line 231
   at System.Web.HttpApplication.RaiseOnError()
   at System.Web.HttpApplication.RecordError(Exception error)
   at System.Web.HttpApplication.PipelineStepManager.ResumeSteps(Exception error)
   at System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb)
   at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
   at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
   at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)
   at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)
   at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
   at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags) | arg_0: System.TimeoutException: An asynchronous operation exceeded the? | gl2_source_input: 55e9aa51498e7098d390de9b | version: 1.1 | thread_id: 87 | event_id: 3 | full_message: ?????????????? ??????????.
Exception: System.TimeoutException: An asynchronous operation exceeded the page timeout.
   at System.Web.UI.Page.<ProcessRequestAsync>d__2.MoveNext(). | identity: Bru.Web:18V24D | correlation_id: 801cb2d8-0000-e900-b63f-84710c7967bb | from: Bru.Web.LayeredHttpApplication | gl2_source_node: 7f9f62e8-3fa7-4a12-9f98-0db7160e0284 | _id: a0921542-5fac-11e5-986d-002590e4fe04 | time: 9.591459392517E8 | timestamp: 2015-09-20T15:31:13.756Z }
```

**Comment by bernd** [comment]
Please check if this is still a problem with Graylog 1.2.1. I am closing this issue, please re-open if the problem still exists. Thank you!

**Comment by igroykt** [comment]
@bernd issue still actual.

> graylog-2.2-repository-1-5.noarch
> graylog-server-2.2.2-1.noarch
