### ISSUE TITLE
Nonexistent aggregation event Group by Field causes error: Invalid format: "(Empty Value)"

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#14375]
[HS 1357286194]
## Description:
When a `Group by Field` for an Aggregation event definition does not exist on any log messages queried by the event, the following exception occurs when the correlation processor runs:

```
Caused by: java.lang.IllegalArgumentException: Invalid format: "(Empty Value)"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945) ~[joda-time-2.10.6.jar:2.10.6]
```

<details>
<summary>Expand for full stacktrace:</summary>
ERROR: org.graylog.events.processor.EventProcessorExecutionJob - Event processor <aggregation-v1/63b880b6c03bed191e30bc94> failed to execute: Couldn't create events for: EventDefinitionDto{scope=DEFAULT, id=63b880b6c03bed191e30bc94, title=Aggregation, description=, priority=2, alert=false, config=AggregationEventProcessorConfig{type=aggregation-v1, query=*, queryParameters=[], streams=[000000000000000000000001], groupBy=[kljhkl], series=[AggregationSeries{id=avg-jkhkhj, function=AVG, field=Optional[jkhkhj]}], conditions=Optional[AggregationConditions{expression=Optional[Greater{expr=>, left=NumberReference{expr=number-ref, ref=avg-jkhkhj}, right=NumberValue{expr=number, value=10.0}}]}], searchWithinMs=15000, executeEveryMs=15000}, fieldSpec={}, keySpec=[], notificationSettings=EventNotificationSettings{gracePeriodMs=0, backlogSize=0}, notifications=[], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]} (retry in 5000 ms)
org.graylog.events.processor.EventProcessorException: Couldn't create events for: EventDefinitionDto{scope=DEFAULT, id=63b880b6c03bed191e30bc94, title=Aggregation, description=, priority=2, alert=false, config=AggregationEventProcessorConfig{type=aggregation-v1, query=*, queryParameters=[], streams=[000000000000000000000001], groupBy=[kljhkl], series=[AggregationSeries{id=avg-jkhkhj, function=AVG, field=Optional[jkhkhj]}], conditions=Optional[AggregationConditions{expression=Optional[Greater{expr=>, left=NumberReference{expr=number-ref, ref=avg-jkhkhj}, right=NumberValue{expr=number, value=10.0}}]}], searchWithinMs=15000, executeEveryMs=15000}, fieldSpec={}, keySpec=[], notificationSettings=EventNotificationSettings{gracePeriodMs=0, backlogSize=0}, notifications=[], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]}
	at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:105) ~[classes/:?]
	at org.graylog.events.processor.EventProcessorExecutionJob.execute(EventProcessorExecutionJob.java:115) ~[classes/:?]
	at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:173) ~[classes/:?]
	at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$2(JobExecutionEngine.java:151) ~[classes/:?]
	at com.codahale.metrics.Timer.time(Timer.java:151) ~[metrics-core-4.1.9.jar:4.1.9]
	at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:151) ~[classes/:?]
	at org.graylog.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:120) ~[classes/:?]
	at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:121) ~[classes/:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [metrics-core-4.1.9.jar:4.1.9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [metrics-core-4.1.9.jar:4.1.9]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Invalid format: "(Empty Value)"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945) ~[joda-time-2.10.6.jar:2.10.6]
	at org.joda.time.DateTime.parse(DateTime.java:160) ~[joda-time-2.10.6.jar:2.10.6]
	at org.joda.time.DateTime.parse(DateTime.java:149) ~[joda-time-2.10.6.jar:2.10.6]
	at org.graylog.events.processor.aggregation.PivotAggregationSearch.extractValues(PivotAggregationSearch.java:322) ~[classes/:?]
	at org.graylog.events.processor.aggregation.PivotAggregationSearch.doSearch(PivotAggregationSearch.java:161) ~[classes/:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.aggregatedSearch(AggregationEventProcessor.java:234) ~[classes/:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:124) ~[classes/:?]
	at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:91) ~[classes/:?]
</details>

## Steps to Reproduce (for bugs)

This issue can be reproduced by creating logs with the Random HTTP message generator input and creating the following aggregation event definition. Note the `field-does-not-exist` group by field.

![image](https://user-images.githubusercontent.com/3423655/211096597-c63fd097-c5c8-474b-a618-50d0d9bc4086.png)

## Workaround

Specify a `Group by Field` that exists on the log messages queried by the aggregation.

## Your Environment

* Graylog Version: 5.0.2
* Java Version:
* Elasticsearch Version: 7.10.2
* MongoDB Version: 5.0.14 
* Operating System:
* Browser version:

**Comment by patrickmann** [comment]
Here's another related scenario, which we should deal with at the same time:
Define an aggregation event, grouped by 2 fields, one of which is valid and the other invalid (field does not occur in any message). This reliably throws the following type of exception:
```
2023-02-15 12:38:05,270 ERROR: org.graylog.events.processor.EventProcessorExecutionJob - Event processor <aggregation-v1/63ea64900e761c129a2a3d15> failed to execute: Couldn't create events for: EventDefinitionDto{scope=DEFAULT, id=63ea64900e761c129a2a3d15, title=test, description=, priority=2, alert=false, config=AggregationEventProcessorConfig{type=aggregation-v1, query=, queryParameters=[], streams=[000000000000000000000001], groupBy=[a;lsdfkjadslfj, action], series=[AggregationSeries{id=avg-xxxxxx, function=AVG, field=Optional[xxxxxx]}], conditions=Optional[AggregationConditions{expression=Optional[Greater{expr=>, left=NumberReference{expr=number-ref, ref=avg-xxxxxx}, right=NumberValue{expr=number, value=2.0}}]}], searchWithinMs=15000, executeEveryMs=15000}, fieldSpec={}, keySpec=[], notificationSettings=EventNotificationSettings{gracePeriodMs=300000, backlogSize=0}, notifications=[], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]} (retry in 5000 ms)
org.graylog.events.processor.EventProcessorException: Couldn't create events for: EventDefinitionDto{scope=DEFAULT, id=63ea64900e761c129a2a3d15, title=test, description=, priority=2, alert=false, config=AggregationEventProcessorConfig{type=aggregation-v1, query=, queryParameters=[], streams=[000000000000000000000001], groupBy=[a;lsdfkjadslfj, action], series=[AggregationSeries{id=avg-xxxxxx, function=AVG, field=Optional[xxxxxx]}], conditions=Optional[AggregationConditions{expression=Optional[Greater{expr=>, left=NumberReference{expr=number-ref, ref=avg-xxxxxx}, right=NumberValue{expr=number, value=2.0}}]}], searchWithinMs=15000, executeEveryMs=15000}, fieldSpec={}, keySpec=[], notificationSettings=EventNotificationSettings{gracePeriodMs=300000, backlogSize=0}, notifications=[], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]}
[...]
Caused by: java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
```
