### ISSUE TITLE
Graylog 5 - Elasticsearch exception [type=illegal_argument_exception, reason=key [types] is not supported in the metadata section]

### ISSUE THREAD

**Issue by codesmaker** [Graylog2/graylog2-server#14542]
Hi,

I have a fresh installation of Graylog v5.0.2-1, MongoDB v5.0.14, and Opensearch v2.0.1 on Ubuntu 20.4.5 LTS following the official documentation. When I go to the 'Search' or 'Alerts' tabs, I get the following error:
```
While retrieving data for this widget, the following error(s) occurred:
Elasticsearch exception [type=illegal_argument_exception, reason=key [types] is not supported in the metadata section].
```

Here is my Graylog config file:
```
is_leader = true
node_id_file = /etc/graylog/server/node-id
password_secret = secret
root_password_sha2 = secret
root_timezone = UTC
bin_dir = /usr/share/graylog-server/bin
data_dir = /var/lib/graylog-server
plugin_dir = /usr/share/graylog-server/plugin
http_bind_address = 192.168.0.130:9000
stream_aware_field_types=false
elasticsearch_hosts = https://admin:password@192.168.0.133:9200,https://admin:password@192.168.0.135:9200
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_disable_version_check = true
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 4
elasticsearch_replicas = 1
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://user:password@192.168.0.130:27017,192.168.0.131:27017,192.168.0.132:27017/graylog?replicaSet=graylog-rep
mongodb_max_connections = 1000
```
Here is the error message I'm getting:
```
2023-01-27T12:00:10.765+01:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: Unable to perform search query
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:155) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:112) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.search(ElasticsearchClient.java:72) ~[?:?]
        at org.graylog.storage.elasticsearch7.MoreSearchAdapterES7.eventSearch(MoreSearchAdapterES7.java:119) ~[?:?]
        at org.graylog.events.search.MoreSearch.eventSearch(MoreSearch.java:94) ~[graylog.jar:?]
        at org.graylog.events.search.EventsSearchService.search(EventsSearchService.java:93) ~[graylog.jar:?]
        at org.graylog.events.rest.EventsResource.search(EventsResource.java:58) ~[graylog.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=key [types] is not supported in the metadata section]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1869) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1626) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.msearch(RestHighLevelClient.java:1118) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.lambda$search$0(ElasticsearchClient.java:72) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:110) ~[?:?]
        ... 32 more
        Suppressed: org.graylog.shaded.elasticsearch7.org.elasticsearch.client.ResponseException: method [POST], host [http://192.168.0.133:9200], URI [/_msearch?typed_keys=true], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"key [types] is not supported in the metadata section"}],"type":"illegal_argument_exception","reason":"key [types] is not supported in the metadata section"},"status":400}
                at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302) ~[?:?]
                at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) ~[?:?]
                at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[?:?]
                at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[?:?]
                at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[?:?]
                at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[?:?]
                at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.msearch(RestHighLevelClient.java:1118) ~[?:?]
                at org.graylog.storage.elasticsearch7.ElasticsearchClient.lambda$search$0(ElasticsearchClient.java:72) ~[?:?]
                at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:110) ~[?:?]
                at org.graylog.storage.elasticsearch7.ElasticsearchClient.search(ElasticsearchClient.java:72) ~[?:?]
                at org.graylog.storage.elasticsearch7.MoreSearchAdapterES7.eventSearch(MoreSearchAdapterES7.java:119) ~[?:?]
                at org.graylog.events.search.MoreSearch.eventSearch(MoreSearch.java:94) ~[graylog.jar:?]
                at org.graylog.events.search.EventsSearchService.search(EventsSearchService.java:93) ~[graylog.jar:?]
                at org.graylog.events.rest.EventsResource.search(EventsResource.java:58) ~[graylog.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
                at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
                at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
                at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
                at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
                at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[graylog.jar:?]
                at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
                at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
                at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
                at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
                at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
                at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
                at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
                at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
                at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
                at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
                at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
                at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
                at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
                at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
                at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
                at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
                at java.lang.Thread.run(Unknown Source) [?:?]
```
I searched everywhere but could not find an answer. I'm not sure if it's a bug related to Opensearch or not. I also tried to disable HTTPS on the Opensearch cluster but it didn't help.

Can you please help me to figure out the root cause?

**Comment by janheise** [comment]
@codesmaker This somehow does not make sense. OpenSearch2 which HTTPS enabled would only work with correct TLS config in graylog. Are you sure, you're connection string is correct? It also looks like Graylog is using the ES7/OS1.3 client - not the OS2 client. Do you have the compatibility mode in OS2 enabled? Can you share your OS2 config, too?

**Comment by janheise** [comment]
And you say, you disabled HTTPS in OS2 only for testing - which means you have TLS configured correctly?

**Comment by linuspahl** [comment]
Hey @codesmaker in addition to what @janheise mentioned, I found the following discussions which might help you with the problem:
- https://github.com/Graylog2/graylog2-server/issues/14542
- https://community.graylog.org/t/graylog-5-with-opensearch-unable-to-start-because-elasticsearch-is-not-installed/26847/6

**Comment by codesmaker** [comment]
@janheise Thanks for the help.

To be honest, I'm not sure how to check the compatibility mode in OS2. Can you please elaborate?

Here is the OS config file of one of the nodes:
```
network.host: 192.168.0.133
node.name: es-01
cluster.name: opensearch-prod
cluster.initial_master_nodes:
        - es-01
        - es-02
        - es-03
discovery.seed_hosts:
        - 192.168.0.133
        - 192.168.0.134
        - 192.168.0.135
node.roles: [ master, data, ingest ]
path.data: /mnt/es-data
path.logs: /var/log/opensearch
http.port: 9200
compatibility.override_main_response_version: true
bootstrap.memory_lock: true
node.max_local_storage_nodes: 3
action.auto_create_index: false
plugins.security.disabled: false
plugins.security.ssl.http.pemcert_filepath: /etc/opensearch/config/certs/es-01.pem
plugins.security.ssl.http.pemkey_filepath: /etc/opensearch/config/certs/es-01-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/opensearch/config/certs/root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.pemcert_filepath: /etc/opensearch/config/certs/es-01.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/opensearch/config/certs/es-01-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/opensearch/config/certs/root-ca.pem
plugins.security.audit.type: internal_opensearch
plugins.security.nodes_dn:
- CN=es-01,OU=IT,O=Org,L=US,C=US
- CN=es-02,OU=IT,O=Org,L=US,C=US
- CN=es-03,OU=IT,O=Org,L=US,C=US
plugins.security.authcz.admin_dn:
- CN=admin,OU=IT,O=Org,L=US,C=US
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"
```
Yes, I have TLS configured correctly for the OS cluster. The logs there are clean and I can send API calls without any issues (cluster health, etc).

On one of the GL nodes, I can see that the 'OpenSearch 2 Support' plugin is there.
![image](https://user-images.githubusercontent.com/6999196/215077332-da6ea39e-2f7b-4e8f-b9b6-489dde6e096f.png)

**Comment by janheise** [comment]
Here you have it: `compatibility.override_main_response_version: true`

**Comment by codesmaker** [comment]
@janheise You're are my hero! :)

It worked as soon as I removed `compatibility.override_main_response_version: true`. I thought it's for supporting the legacy versions of of Filebeats but I was mistaken clearly. 

Now, I'm having this error on the OS cluster:
```
[2023-01-27T12:58:45,795][ERROR][o.o.s.a.s.InternalOpenSearchSink] [es-01] Unable to index audit log {"audit_cluster_name":"opensearch-prod","audit_transport_headers":{"_system_index_access_allowed":"false"},"audit_node_name":"es-01","audit_trace_task_id":"va7dgHerRqyez7HuwFpDjA:3885","audit_transport_request_type":"GetMappingsRequest","audit_category":"INDEX_EVENT","audit_request_origin":"REST","audit_node_id":"va7dgHerRqyez7HuwFpDjA","audit_request_layer":"TRANSPORT","@timestamp":"2023-01-27T11:58:45.794+00:00","audit_format_version":4,"audit_request_remote_address":"192.168.0.130","audit_request_privilege":"indices:admin/mappings/get","audit_node_host_address":"192.168.0.133","audit_request_effective_user":"admin","audit_trace_indices":["graylog_0"],"audit_trace_resolved_indices":["graylog_0"],"audit_node_host_name":"192.168.0.133"} due to
org.opensearch.index.IndexNotFoundException: no such index [security-auditlog-2023.01.27]
        at org.opensearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:289) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.cluster.metadata.IndexNameExpressionResolver.concreteWriteIndex(IndexNameExpressionResolver.java:484) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.bulk.TransportBulkAction$ConcreteIndices.resolveIfAbsent(TransportBulkAction.java:801) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.bulk.TransportBulkAction$BulkOperation.addFailureIfIndexIsUnavailable(TransportBulkAction.java:743) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.bulk.TransportBulkAction$BulkOperation.doRun(TransportBulkAction.java:532) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.bulk.TransportBulkAction.executeBulk(TransportBulkAction.java:774) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.bulk.TransportBulkAction.doInternalExecute(TransportBulkAction.java:361) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:220) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:118) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:204) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.indexmanagement.rollup.actionfilter.FieldCapsFilter.apply(FieldCapsFilter.kt:118) ~[?:?]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:202) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:78) ~[?:?]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:202) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:240) ~[?:?]
        at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:157) ~[?:?]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:202) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:174) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.bulk.TransportSingleItemBulkWriteAction.doExecute(TransportSingleItemBulkWriteAction.java:73) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.bulk.TransportSingleItemBulkWriteAction.doExecute(TransportSingleItemBulkWriteAction.java:53) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:204) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.indexmanagement.rollup.actionfilter.FieldCapsFilter.apply(FieldCapsFilter.kt:118) ~[?:?]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:202) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:78) ~[?:?]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:202) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:240) ~[?:?]
        at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:157) ~[?:?]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:202) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:174) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:102) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:423) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:410) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:63) ~[opensearch-2.0.1.jar:2.0.1]
        at org.opensearch.security.auditlog.sink.InternalOpenSearchSink.doStore(InternalOpenSearchSink.java:78) [opensearch-security-2.0.1.0.jar:2.0.1.0]
        at org.opensearch.security.auditlog.sink.AuditLogSink.doStoreWithRetry(AuditLogSink.java:75) [opensearch-security-2.0.1.0.jar:2.0.1.0]
        at org.opensearch.security.auditlog.sink.AuditLogSink.store(AuditLogSink.java:66) [opensearch-security-2.0.1.0.jar:2.0.1.0]
        at org.opensearch.security.auditlog.routing.AsyncStoragePool.lambda$submit$0(AsyncStoragePool.java:47) [opensearch-security-2.0.1.0.jar:2.0.1.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[2023-01-27T12:58:45,796][INFO ][stdout                   ] [es-01] AUDIT_LOG: {
[2023-01-27T12:58:45,796][INFO ][stdout                   ] [es-01]   "audit_cluster_name" : "opensearch-prod",
[2023-01-27T12:58:45,796][INFO ][stdout                   ] [es-01]   "audit_transport_headers" : {
[2023-01-27T12:58:45,796][INFO ][stdout                   ] [es-01]     "_system_index_access_allowed" : "false"
[2023-01-27T12:58:45,796][INFO ][stdout                   ] [es-01]   },
[2023-01-27T12:58:45,796][INFO ][stdout                   ] [es-01]   "audit_node_name" : "es-01",
[2023-01-27T12:58:45,796][INFO ][stdout                   ] [es-01]   "audit_trace_task_id" : "va7dgHerRqyez7HuwFpDjA:3885",
[2023-01-27T12:58:45,796][INFO ][stdout                   ] [es-01]   "audit_transport_request_type" : "GetMappingsRequest",
[2023-01-27T12:58:45,796][INFO ][stdout                   ] [es-01]   "audit_category" : "INDEX_EVENT",
[2023-01-27T12:58:45,797][INFO ][stdout                   ] [es-01]   "audit_request_origin" : "REST",
[2023-01-27T12:58:45,797][INFO ][stdout                   ] [es-01]   "audit_node_id" : "va7dgHerRqyez7HuwFpDjA",
[2023-01-27T12:58:45,797][INFO ][stdout                   ] [es-01]   "audit_request_layer" : "TRANSPORT",
[2023-01-27T12:58:45,797][INFO ][stdout                   ] [es-01]   "@timestamp" : "2023-01-27T11:58:45.794+00:00",
[2023-01-27T12:58:45,797][INFO ][stdout                   ] [es-01]   "audit_format_version" : 4,
[2023-01-27T12:58:45,797][INFO ][stdout                   ] [es-01]   "audit_request_remote_address" : "192.168.0.130",
[2023-01-27T12:58:45,797][INFO ][stdout                   ] [es-01]   "audit_request_privilege" : "indices:admin/mappings/get",
[2023-01-27T12:58:45,797][INFO ][stdout                   ] [es-01]   "audit_node_host_address" : "192.168.0.133",
[2023-01-27T12:58:45,797][INFO ][stdout                   ] [es-01]   "audit_request_effective_user" : "admin",
[2023-01-27T12:58:45,797][INFO ][stdout                   ] [es-01]   "audit_trace_indices" : [
[2023-01-27T12:58:45,798][INFO ][stdout                   ] [es-01]     "graylog_0"
[2023-01-27T12:58:45,798][INFO ][stdout                   ] [es-01]   ],
[2023-01-27T12:58:45,798][INFO ][stdout                   ] [es-01]   "audit_trace_resolved_indices" : [
[2023-01-27T12:58:45,798][INFO ][stdout                   ] [es-01]     "graylog_0"
[2023-01-27T12:58:45,798][INFO ][stdout                   ] [es-01]   ],
[2023-01-27T12:58:45,798][INFO ][stdout                   ] [es-01]   "audit_node_host_name" : "192.168.0.133"
[2023-01-27T12:58:45,798][INFO ][stdout                   ] [es-01] }
```
If I'm not mistaken, it's because the `security-auditlog-2023.01.27` is missing. How can I create it?

**Comment by codesmaker** [comment]
I figured it out. I needed to remove `action.auto_create_index: false` and now the OS logs are as calm as it should be.

Thanks a lot guys for the awesome help. You rock!
