### ISSUE TITLE
Upgrade from v4.3.12 to v5.0.3 fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by H2Cyber** [Graylog2/graylog2-server#14637]
## Environment information
* Graylog Version: 4.3.12
* MongoDB Version: 5.0.14
* Elasticsearch Version : 7.10.2
* Operating System: Ubuntu 20.04 64 bits

## Steps to upgrade
Here are the steps that I followed to perform the upgrade to 5.0.3 :
```
sudo systemctl stop graylog-server.service
wget https://downloads.graylog.org/repo/packages/graylog-5.0-repository_latest.deb
sudo dpkg -i graylog-5.0-repository_latest.deb
sudo apt-get update
sudo apt-get upgrade graylog-server // opted to keep my existing configuration files (/etc/default/graylog-server and /etc/graylog/server/server.conf)
sudo nano /etc/graylog/server/server.conf // to remove the mongodb_threads_allowed_to_block_multiplier line
sudo nano /etc/default/graylog-server // to comment out the line that specifies JAVA=/[...].
sudo systemctl start graylog-server.service
```
## Results

After upgrading using the steps above, the Graylog service won't start at all, as can be seen in the screenshot below. 
![image](https://user-images.githubusercontent.com/764189/217598423-3d1b070a-5120-4dbf-95c1-61dcca534a8d.png)

There are no new entries in the `/var/log/graylog-server/server.log` log file :
```
2023-02-08T17:40:16.476+01:00 INFO  [FailureHandlingService] Shutting down the service. Processed 0 remaining failure batches.
2023-02-08T17:40:16.476+01:00 INFO  [FailureSubmissionQueue] [FailureHandlerService#shutDown] Total number of submitted batches: 0 (0 failures), total number of consumed batches: 0 (0 failures)
2023-02-08T17:40:16.476+01:00 INFO  [ServiceManagerListener] Services are now stopped.

``` 

How can I troobleshoot this further ? What could be the cause for Graylog service to NOT start after the upgrade ?

**Comment by H2Cyber** [comment]
Update : found this error in the journalctl logs : 

```
-- The job identifier is 3370.
Feb 08 17:16:55 graylog-VM graylog-server[9587]: Error: A JNI error has occurred, please check your installation and try again
Feb 08 17:16:55 graylog-VM graylog-server[9587]: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/graylog2/bootstrap/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.lang.ClassLoader.defineClass1(Native Method)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.security.AccessController.doPrivileged(Native Method)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Feb 08 17:16:55 graylog-VM graylog-server[9587]:         at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
Feb 08 17:16:55 graylog-VM systemd[1]: graylog-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit graylog-server.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Feb 08 17:16:55 graylog-VM systemd[1]: graylog-server.service: Failed with result 'exit-code'.
```

**Comment by mpfz0r** [comment]
https://go2docs.graylog.org/5-0/upgrading_graylog/upgrading_to_graylog_5.0.x.htm

`Graylog 5 is Java 17 only. We no longer support earlier Java versions.`

**Comment by H2Cyber** [comment]
https://go2docs.graylog.org/5-0/upgrading_graylog/upgrading_to_graylog_5.0.x.htm

`The Graylog 5.0 operating system packages bundle version 17 of the JVM, so it's no longer required to install any JVM/Java packages to run Graylog.`

And so I thought I did not have to upgrade or install Java. 

Based on your feedback I've installed Java v17 and was therefore able to start the service. Thanks for the help !

**Comment by bernd** [comment]
> And so I thought I did not have to upgrade or install Java.
> 
@H2Cyber That should be the case.

Did you run into this? Having an enabled `JAVA=/usr/bin/java` in your environment file?

![image](https://user-images.githubusercontent.com/461/218031985-f55e0b1d-d065-4ec2-8d8d-125a63d82341.png)

**Comment by H2Cyber** [comment]
I did comment the line `JAVA=/usr/bin/java` in `/etc/default/graylog-server` (the exact steps that I followed are detailed in the **Steps to upgrade** section of this issue). 

Therefore I had to install Java 17 for the Graylog 5 service to start.
