### ISSUE TITLE
Mongo ?readPreference=secondaryPreferred almost working

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1471]
Hello,

An easy way to highly boost API performances and so web interface experience is to set such configuration in server.conf, if you have multiple mongo replicas:

mongodb_uri = mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/graylog2?readPreference=secondaryPreferred

If benefits can be immediately observed if you are already logged in, this configuration does not allow graylog to create new session document and so block any new connection.

As stream, dashboard edition and more works, i think they are something not clear about session management.

Login attempt log this

```
2015-10-08T15:08:57.111Z ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.RuntimeException: Couldn't load session <e886bb79-8500-4f96-8c60-70a21a1a3810>
	at org.graylog2.security.MongoDbSessionDAO.doUpdate(MongoDbSessionDAO.java:94)
	at org.apache.shiro.session.mgt.eis.CachingSessionDAO.update(CachingSessionDAO.java:277)
	at org.apache.shiro.session.mgt.DefaultSessionManager.onChange(DefaultSessionManager.java:212)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.applyGlobalSessionTimeout(AbstractNativeSessionManager.java:85)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.start(AbstractNativeSessionManager.java:60)
	at org.apache.shiro.mgt.SessionsSecurityManager.start(SessionsSecurityManager.java:121)
	at org.apache.shiro.subject.support.DelegatingSubject.getSession(DelegatingSubject.java:336)
	at org.apache.shiro.subject.support.DelegatingSubject.getSession(DelegatingSubject.java:312)
	at org.graylog2.rest.resources.system.SessionsResource.newSession(SessionsResource.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pdepaepe** [comment]
Mongo side, this is doing the job

mongodb_uri = mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/graylog2?readPreference=secondaryPreferred&w=3&journal=true&wtimeoutMS=5000

**Comment by m4h** [comment]
Just in case somebody still encounter issue with sessions.
For GL2 it is not necessary to read from replica, as replica used due to HA than performance. 
So setup connection string to read/write against PRIMARY will be most convenient and straight forward way:
graylog2?replicaSet=graylog&readPreference=primaryPreferred&w=1&journal=true&wtimeoutMS=5000

Basically it is says - read/write from PRIMARY, write at least 1 time and get an ACK for success.

**Comment by pdepaepe** [comment]
Nice one @m4h, thanks.

**Comment by orlandothoeny** [comment]
Also ran into this, getting the following error when trying to log in:
> Error - the server returned: 500 - There was an error fetching a resource: . Additional information: Couldn't load session

As @m4h already mentioned. Changing our connection string from
`mongodb+srv://graylog-user:graylog-password@mongodb-graylog.example.com/graylog?authSource=admin&readPreference=secondaryPreferred&ssl=false` to `mongodb+srv://graylog-user:graylog-password@mongodb-graylog.example.com/graylog?authSource=admin&readPreference=primaryPreferred&ssl=false` fixed the problem. (`readPreference=secondaryPreferred` => `readPreference=primaryPreferred`)

Running Graylog 4.3.15
