### ISSUE TITLE
API Browser sections do not expand in 5.0.4

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#14856]
Observed in a 5.0.3->5.0.4 upgraded multi-member install, a fresh bone stock 5.0.4 AIO install, and graylog-test50, it's not possible to expand the various sections of the API Browser. 

Screen recording: [https://link.cekkent.net/bc0e48a2-92d7-4f79-baf0-7966f6889149](https://link.cekkent.net/bc0e48a2-92d7-4f79-baf0-7966f6889149)

Single-node view when clicking the API Browser:
![image](https://user-images.githubusercontent.com/2953243/222831335-449a6b56-1387-49b1-88b5-28a608900501.png)

Global view when clicking the API Browser: 
![image](https://user-images.githubusercontent.com/2953243/222831455-ea624e0f-c5c3-4ce2-819f-90dd178e882c.png)

The following appears in server.log when loading the API Browser:
`2023-03-03T16:21:14.791-05:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Conflicting getter definitions for property "username": org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#userName() vs org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#password()
	at org.graylog2.shared.rest.documentation.generator.Generator.schemaForType(Generator.java:561) ~[graylog.jar:?]
	at org.graylog2.shared.rest.documentation.generator.Generator.typeSchema(Generator.java:452) ~[graylog.jar:?]
	at org.graylog2.shared.rest.documentation.generator.Generator.determineParameters(Generator.java:589) ~[graylog.jar:?]
	at org.graylog2.shared.rest.documentation.generator.Generator.generateForRoute(Generator.java:266) ~[graylog.jar:?]
	at org.graylog2.shared.rest.resources.documentation.DocumentationResource.route(DocumentationResource.java:116) ~[graylog.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor290.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Conflicting getter definitions for property "username": org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#userName() vs org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#password()
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:290) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1330) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1468) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectWriter.acceptJsonFormatVisitor(ObjectWriter.java:1143) ~[graylog.jar:?]
	at com.fasterxml.jackson.module.jsonSchema.JsonSchemaGenerator.generateSchema(JsonSchemaGenerator.java:99) ~[graylog.jar:?]
	at org.graylog2.shared.rest.documentation.generator.Generator.schemaForType(Generator.java:548) ~[graylog.jar:?]
	... 30 more
Caused by: java.lang.IllegalArgumentException: Conflicting getter definitions for property "username": org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#userName() vs org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#password()
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getGetter(POJOPropertyBuilder.java:449) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition.getAccessor(BeanPropertyDefinition.java:188) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.removeIgnorableTypes(BeanSerializerFactory.java:763) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:599) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:401) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:294) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:239) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:173) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1495) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1463) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectWriter.acceptJsonFormatVisitor(ObjectWriter.java:1143) ~[graylog.jar:?]
	at com.fasterxml.jackson.module.jsonSchema.JsonSchemaGenerator.generateSchema(JsonSchemaGenerator.java:99) ~[graylog.jar:?]
	at org.graylog2.shared.rest.documentation.generator.Generator.schemaForType(Generator.java:548) ~[graylog.jar:?]
	... 30 more
2023-03-03T16:21:17.054-05:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Conflicting getter definitions for property "username": org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#userName() vs org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#password()
	at org.graylog2.shared.rest.documentation.generator.Generator.schemaForType(Generator.java:561) ~[graylog.jar:?]
	at org.graylog2.shared.rest.documentation.generator.Generator.typeSchema(Generator.java:452) ~[graylog.jar:?]
	at org.graylog2.shared.rest.documentation.generator.Generator.determineParameters(Generator.java:589) ~[graylog.jar:?]
	at org.graylog2.shared.rest.documentation.generator.Generator.generateForRoute(Generator.java:266) ~[graylog.jar:?]
	at org.graylog2.shared.rest.resources.documentation.DocumentationResource.route(DocumentationResource.java:116) ~[graylog.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor290.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Conflicting getter definitions for property "username": org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#userName() vs org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#password()
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:290) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1330) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1468) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectWriter.acceptJsonFormatVisitor(ObjectWriter.java:1143) ~[graylog.jar:?]
	at com.fasterxml.jackson.module.jsonSchema.JsonSchemaGenerator.generateSchema(JsonSchemaGenerator.java:99) ~[graylog.jar:?]
	at org.graylog2.shared.rest.documentation.generator.Generator.schemaForType(Generator.java:548) ~[graylog.jar:?]
	... 30 more
Caused by: java.lang.IllegalArgumentException: Conflicting getter definitions for property "username": org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#userName() vs org.graylog.enterprise.integrations.f5networks.api.requests.F5Request#password()
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getGetter(POJOPropertyBuilder.java:449) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition.getAccessor(BeanPropertyDefinition.java:188) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.removeIgnorableTypes(BeanSerializerFactory.java:763) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:599) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:401) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:294) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:239) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:173) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1495) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1463) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectWriter.acceptJsonFormatVisitor(ObjectWriter.java:1143) ~[graylog.jar:?]
	at com.fasterxml.jackson.module.jsonSchema.JsonSchemaGenerator.generateSchema(JsonSchemaGenerator.java:99) ~[graylog.jar:?]
	at org.graylog2.shared.rest.documentation.generator.Generator.schemaForType(Generator.java:548) ~[graylog.jar:?]
	... 30 more`

**Comment by bernd** [comment]
Fixed in Graylog2/graylog-plugin-enterprise-integrations#1027. The fix will be part of the upcoming 5.0.5 release.
