### ISSUE TITLE
Elasticsearch 2.0.0-rc1.

### ISSUE THREAD

**Issue by ScottJEhas** [Graylog2/graylog2-server#1503]
Looks like Graylog does not want to parse the Elasticsearch string.  Does anyone know if Elasticsearch 2.0 is supported?
```
2015-10-22T13:39:00.023-05:00 WARN  [netty] [Graylog.prod.gigenet.com] Message not fully read (response) for [7] handler org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$4@6b1f095, error [true], resetting
2015-10-22T13:39:00.512-05:00 INFO  [IndexerSetupService] Checking Elasticsearch HTTP API at http://10.201.6.221:9200/
2015-10-22T13:39:00.697-05:00 ERROR [ServiceManager] Service IndexerSetupService [FAILED] has failed in the STARTING state.
java.lang.IllegalArgumentException: unable to parse version 2.0.0-rc1
	at org.elasticsearch.Version.fromString(Version.java:539)
	at org.graylog2.initializers.IndexerSetupService.startUp(IndexerSetupService.java:170)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "0-rc1"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at org.elasticsearch.Version.fromString(Version.java:518)
	... 4 more
```

**Comment by joschi** [comment]
Graylog is not supporting Elasticsearch 2.x for now and we won't add support for it in the 1.x version line.
