### ISSUE TITLE
Graylog 1.3 requires Java 1.8 but should work with 1.7.x

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-server#1509]
Running Graylog 1.3 Snapshots requires Java 1.8 but should work with 1.7.x

`ubuntu@graylog:/tmp/server/graylog-1.3.0-SNAPSHOT-20151012090622$ java -jar graylog.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/graylog2/bootstrap/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)`

**Comment by bernd** [comment]
That was a problem with our snapshot building. Should be fixed with the next builds.

Thank you for the report! :smiley:

**Comment by udomsak** [comment]
# have problem with  alpine-linux  jdk "1.7.0_79"  but on Ubuntu it work fine. :+1: 

## Java version 

```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (Alpine 7.79.2.5.6-r0)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

## Error when running graylog-server 2.0.0 

```
/srv/graylog-server # java -jar graylog.jar -c ./conf/server.conf 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/graylog2/bootstrap/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

```

**Comment by joschi** [comment]
@udomsak Graylog 2.0.0 requires Java 8 (as stated in the system requirements).

**Comment by udomsak** [comment]
:+1:  @joschi  thx
