### ISSUE TITLE
[1.2.2] - IndexRotationThread timeout

### ISSUE THREAD

**Issue by voodoodrul** [Graylog2/graylog2-server#1514]
We run a shared ES cluster and partition Graylog tenants using elasticsearch_index_prefix. Each tenant has a tenant-facing front-end Graylog instance that runs all services except elasticsearch.  One of our 1.2.1 front-end instances was upgraded to 1.2.2. It currently has no data in ES as we're staging it for now. After the upgrade, /var/log/graylog/server/current shows these errors every minute: 
```
2015-10-27_21:29:24.98443 ERROR [IndexRotationThread] Couldn't point deflector to a new index
2015-10-27_21:29:24.98445 org.elasticsearch.ElasticsearchTimeoutException: Timeout waiting for task.
2015-10-27_21:29:24.98447       at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:73)
2015-10-27_21:29:24.98447       at org.graylog2.indexer.elasticsearch.GlobalTimeoutClient$GlobalTimeoutActionFuture.actionGet(GlobalTimeoutClient.java:165)
2015-10-27_21:29:24.98447       at org.graylog2.indexer.elasticsearch.GlobalTimeoutClient$GlobalTimeoutActionFuture.actionGet(GlobalTimeoutClient.java:150)
2015-10-27_21:29:24.98448       at org.graylog2.indexer.indices.Indices.aliasTarget(Indices.java:199)
2015-10-27_21:29:24.98448       at org.graylog2.indexer.Deflector.getCurrentActualTargetIndex(Deflector.java:269)
2015-10-27_21:29:24.98448       at org.graylog2.periodical.IndexRotationThread.checkAndRepair(IndexRotationThread.java:121)
2015-10-27_21:29:24.98448       at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:66)
2015-10-27_21:29:24.98449       at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:83)
2015-10-27_21:29:24.98449       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2015-10-27_21:29:24.98449       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2015-10-27_21:29:24.98450       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2015-10-27_21:29:24.98450       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2015-10-27_21:29:24.98450       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-10-27_21:29:24.98450       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-10-27_21:29:24.98451       at java.lang.Thread.run(Thread.java:745)
2015-10-27_21:29:54.90428 ERROR [IndexRetentionThread] Uncaught exception in periodical
2015-10-27_21:29:54.90431 org.elasticsearch.ElasticsearchTimeoutException: Timeout waiting for task.
2015-10-27_21:29:54.90431       at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:73)
2015-10-27_21:29:54.90432       at org.graylog2.indexer.elasticsearch.GlobalTimeoutClient$GlobalTimeoutActionFuture.actionGet(GlobalTimeoutClient.java:165)
2015-10-27_21:29:54.90432       at org.graylog2.indexer.elasticsearch.GlobalTimeoutClient$GlobalTimeoutActionFuture.actionGet(GlobalTimeoutClient.java:150)
2015-10-27_21:29:54.90432       at org.graylog2.indexer.indices.Indices.getAll(Indices.java:178)
2015-10-27_21:29:54.90432       at org.graylog2.indexer.Deflector.getAllDeflectorIndices(Deflector.java:216)
2015-10-27_21:29:54.90433       at org.graylog2.periodical.IndexRetentionThread.doRun(IndexRetentionThread.java:68)
2015-10-27_21:29:54.90433       at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:83)
2015-10-27_21:29:54.90433       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2015-10-27_21:29:54.90433       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2015-10-27_21:29:54.90433       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2015-10-27_21:29:54.90434       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2015-10-27_21:29:54.90434       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-10-27_21:29:54.90435       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-10-27_21:29:54.90435       at java.lang.Thread.run(Thread.java:745)
2015-10-27_21:29:55.06038 ERROR [UsageStatsClusterPeriodical] Uncaught exception in periodical
2015-10-27_21:29:55.06040 org.elasticsearch.ElasticsearchTimeoutException: Timeout waiting for task.
2015-10-27_21:29:55.06041       at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:73)
2015-10-27_21:29:55.06041       at org.graylog2.indexer.elasticsearch.GlobalTimeoutClient$GlobalTimeoutActionFuture.actionGet(GlobalTimeoutClient.java:165)
2015-10-27_21:29:55.06041       at org.graylog2.indexer.elasticsearch.GlobalTimeoutClient$GlobalTimeoutActionFuture.actionGet(GlobalTimeoutClient.java:150)
2015-10-27_21:29:55.06043       at org.graylog.plugins.usagestatistics.collectors.ElasticsearchCollector.fetchNodeInfos(ElasticsearchCollector.java:146)
2015-10-27_21:29:55.06043       at org.graylog.plugins.usagestatistics.collectors.ElasticsearchCollector.getNodeInfos(ElasticsearchCollector.java:59)
2015-10-27_21:29:55.06044       at org.graylog.plugins.usagestatistics.collectors.ClusterCollector.buildClusterStats(ClusterCollector.java:81)
2015-10-27_21:29:55.06044       at org.graylog.plugins.usagestatistics.collectors.ClusterCollector.getClusterDataSet(ClusterCollector.java:74)
2015-10-27_21:29:55.06044       at org.graylog.plugins.usagestatistics.UsageStatsClusterService$1.get(UsageStatsClusterService.java:52)
2015-10-27_21:29:55.06045       at org.graylog.plugins.usagestatistics.UsageStatsClusterService$1.get(UsageStatsClusterService.java:49)
2015-10-27_21:29:55.06045       at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:192)
2015-10-27_21:29:55.06045       at org.graylog.plugins.usagestatistics.UsageStatsClusterService.buildClusterDataSet(UsageStatsClusterService.java:58)
2015-10-27_21:29:55.06045       at org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical.buildPayload(UsageStatsClusterPeriodical.java:87)
2015-10-27_21:29:55.06046       at org.graylog.plugins.usagestatistics.UsageStatsPeriodical.doRun(UsageStatsPeriodical.java:80)
2015-10-27_21:29:55.06046       at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:83)
2015-10-27_21:29:55.06046       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2015-10-27_21:29:55.06046       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2015-10-27_21:29:55.06046       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2015-10-27_21:29:55.06047       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2015-10-27_21:29:55.06047       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-10-27_21:29:55.06047       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-10-27_21:29:55.06048       at java.lang.Thread.run(Thread.java:745)
```

**Comment by joschi** [comment]
Is Elasticsearch working and responding in a timely manner? It looks like Graylog is connected to the ES cluster but it's not responding within the specified timeout.

**Comment by voodoodrul** [comment]
The ES cluster continues to respond in a timely manner to all other 1.2.1 instances. It is lightly loaded at this point, pushing about 500 msg/sec. The other instances can stream their writes into the cluster without issue and searches appear to be performant. The ES logs on the ES cluster nodes look clean with no mention of anything that would indicate poor performance. This 1.2.2 instance was destroyed and a 1.2.1 instance stood up in its place in order to continue operation, but I will try several passes at joining a 1.2.2 instance to the existing cluster and report back.

**Comment by voodoodrul** [comment]
The problem is repeatable in my case any time I use a t2.medium EC2 instance type. It could be due to lack of memory since these instances only have 4gb RAM, but that should be okay since it's within the requirements for Graylog and ES isn't even running on these. It might be a race condition or perpetual retry due to poor network or EBS volume performance. Since it works without issue on larger instance types - m4.large specifically - and there are too many undefined/unbounded variables, I will close this issue for now.
