### ISSUE TITLE
Server side scripting required for NodeService

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#15152]
With the  refactoring of NodeService, we have introduced the requirement for the server side scripting in mongodb through the `$where` operator.  If server side scripting is disabled, it will manifest with the following exception:

```
2023-04-05T09:17:17.175Z ERROR [CmdLineTool] Startup error:
com.mongodb.MongoCommandException: Command failed with error 2 (BadValue): 'no globalScriptEngine in $where parsing' on server 10.98.160.121:27017. The full response is {"ok": 0.0, "errmsg": "no globalScriptEngine in $where parsing", "code": 2, "codeName": "BadValue", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1680686237, "i": 2}}, "signature": {"hash": {"$binary": {"base64": "+GouQPX4eaq/0f+MIq963lEuLlw=", "subType": "00"}}, "keyId": 7172099873943060482}}, "operationTime": {"$timestamp": {"t": 1680686237, "i": 2}}}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:416) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:340) ~[graylog.jar:?]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:643) ~[graylog.jar:?]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:206) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:119) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:85) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:75) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:293) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:233) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$4(CommandOperationHelper.java:215) ~[graylog.jar:?]
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:356) ~[graylog.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381) ~[graylog.jar:?]
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:355) ~[graylog.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381) ~[graylog.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:354) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$5(CommandOperationHelper.java:213) ~[graylog.jar:?]
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:218) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:199) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CountOperation.execute(CountOperation.java:129) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CountOperation.execute(CountOperation.java:47) ~[graylog.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191) ~[graylog.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:168) ~[graylog.jar:?]
	at com.mongodb.DBCollection.getCount(DBCollection.java:928) ~[graylog.jar:?]
	at com.mongodb.DBCollection.count(DBCollection.java:843) ~[graylog.jar:?]
	at org.graylog2.database.PersistedServiceImpl.count(PersistedServiceImpl.java:94) ~[graylog.jar:?]
	at org.graylog2.cluster.NodeServiceImpl.isOnlyLeader(NodeServiceImpl.java:165) ~[graylog.jar:?]
	at org.graylog2.commands.Server.startNodeRegistration(Server.java:231) ~[graylog.jar:?]
	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:241) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:324) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:260) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:45) [graylog.jar:?]

```

## Current Behavior
Server startup fails if server side scripting is disabled. 

## Possible Solution
Either we can rewrite the NodeService implementation to avoid `$where` or at least we have to document server side scripting as an requirement for the 5.1. release.

Additionally, we should be able to catch this problem sooner if we closely match the mongodb container configuration to the setup used in the cloud instances.

**Comment by dennisoelkers** [comment]
Fixed in #15160.
