### ISSUE TITLE
ERROR [NettyContainer] Uncaught exception during jersey resource handling

### ISSUE THREAD

**Issue by perbly** [Graylog2/graylog2-server#1516]
Hi

We are running 3 graylog servers in a cluster and 4 other elastic servers.
We get the following error message in the graylog server log. We are running 1.2.1
Any clues where to start looking? 

```
2015-10-29_07:54:53.91991 ERROR [NettyContainer] Uncaught exception during jersey resource handling
2015-10-29_07:54:53.91994 java.lang.IllegalArgumentException: empty text
2015-10-29_07:54:53.91994       at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:89)
2015-10-29_07:54:53.91995       at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62)
2015-10-29_07:54:53.91995       at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75)
2015-10-29_07:54:53.91995       at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191)
2015-10-29_07:54:53.91996       at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102)
2015-10-29_07:54:53.91996       at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
2015-10-29_07:54:53.91996       at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
2015-10-29_07:54:53.91997       at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
2015-10-29_07:54:53.91997       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
2015-10-29_07:54:53.91997       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
2015-10-29_07:54:53.91999       at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
2015-10-29_07:54:53.91999       at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
2015-10-29_07:54:53.91999       at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
2015-10-29_07:54:53.92000       at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
2015-10-29_07:54:53.92001       at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
2015-10-29_07:54:53.92002       at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
2015-10-29_07:54:53.92002       at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
2015-10-29_07:54:53.92004       at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
2015-10-29_07:54:53.92005       at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
2015-10-29_07:54:53.92006       at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
2015-10-29_07:54:53.92007       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-10-29_07:54:53.92008       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-10-29_07:54:53.92010       at java.lang.Thread.run(Thread.java:745)
```
/Per

**Comment by joschi** [comment]
There seems to be some client which sends invalid HTTP requests (i. e. with a malformed or missing HTTP header) to Graylog.

If you feel adventurous, you can set the log level for `org.jboss.netty` to `DEBUG` (e. g. in your `log4j.xml`) and see if you can identify the misbehaving client.

**Comment by perbly** [comment]
Hi @joschi 

I don´t have the section org.jboss.netty in my /opt/graylog/conf/log4j.xml file.


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE log4j:configuration PUBLIC "-//APACHE//DTD LOG4J 1.2//EN" "log4j.dtd">
<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">

    
    <appender name="consoleAppender" class="org.apache.log4j.ConsoleAppender">
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern" value="%-5p [%c{1}] %m%n"/>
        </layout>
    </appender>

    
    <logger name="org.graylog2">
        <level value="warn"/>
    </logger>
    <logger name="com.github.joschi.jadconfig">
        <level value="warn"/>
    </logger>
    
    <logger name="org.graylog2.periodical.VersionCheckThread">
        <level value="off"/>
    </logger>
    
    <logger name="org.apache.directory.api.ldap.model.message.BindRequestImpl">
        <level value="error"/>
    </logger>
    
    <logger name="org.elasticsearch.script">
        <level value="warn"/>
    </logger>
    
    <logger name="org.drools.compiler.kie.builder.impl.KieRepositoryImpl">
        <level value="warn"/>
    </logger>
    <logger name="com.joestelmach.natty.Parser">
        <level value="warn"/>
    </logger>
    
    <logger name="kafka.log.Log">
        <level value="warn"/>
    </logger>
    <logger name="kafka.log.OffsetIndex">
        <level value="warn"/>
    </logger>
    
    <root>
        <priority value="warn"/>
        <appender-ref ref="consoleAppender"/>
    </root>

</log4j:configuration>

**Comment by joschi** [comment]
> I don´t have the section org.jboss.netty in my /opt/graylog/conf/log4j.xml file.

Just add an appropriate `<logger>` element.

**Comment by perbly** [comment]
Thanks for you support @joschi 

I´m trying to change the logging level by running the powershell command but the operation times out:

<code>
Invoke-RestMethod -Method Put -Uri http://servername:12900/system/loggers/org.jboss.netty.channel.D
efaultChannelPipeline/level/debug"  -ContentType 'application/json' -Verbose -Credential (get-credential)
</code>

Very strange because this command works just fine.
<code>
Invoke-RestMethod -Method Get -Uri "http://servername:12900/system/loggers/" -ContentType 'application
/json' -Verbose -Credential (get-credential) | ConvertTo-Json
</code>

**Comment by joschi** [comment]
@perbly Maybe your HTTP client in PowerShell is the culprit in the first place? Try using another HTTP client or use the Graylog API browser at http://127.0.0.1/api-browser (replace 127.0.0.1 with the IP address or hostname of your Graylog server).

**Comment by perbly** [comment]
I found the bad guy. Turns out the loadbalancer did some incorrect requests. Thanks  @joschi for all help. Closing this.

**Comment by joschi** [comment]
Great, thanks for your feedback!
