### ISSUE TITLE
Search page intermittently showing TypeError for messages widget

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#15167]
After upgrading from Graylog 5.0.5 to 5.0.6, my search page intermittently shows TypeError for messages widget.

> While rendering this widget, the following error occured:
> 
> TypeError: Cannot destructive property 'isLoading' of 'f.useCntext(...)' as it is undefined.

![image](https://user-images.githubusercontent.com/107503402/230446231-73346414-0b85-430e-acc3-fe46532fdc41.png)

No errors in web requests (via dev tools) and no other obvious errors or issue. No errors in server.log.

## Expected Behavior

Widget loads with out error.

## Current Behavior

Widget intermittently fails to load.

## Steps to Reproduce (for bugs)

I tried but failed to find a reliable way to reproduce this.

I can sometimes get the error when refreshing the entire browser on the search page multiple times. Its pretty much seems random though.

## Your Environment

* Graylog Version: 5.0.6
* Java Version: Bundled JDK
* ~~Elasticsearch~~ OpenSearch Version: 2.6.0
* MongoDB Version: 6.0.5
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Chrome Version 111.0.5563.146 (Official Build) (arm64)

**Comment by drewmiranda-gl** [comment]
Was able to get the console messages:

```
TypeError: Cannot read properties of null (reading 'includes')
    at MessageSummary.tsx:104:52
    at Array.filter (<anonymous>)
    at MessageSummary.tsx:104:6
    at MessageSummary.tsx:123:29
    at Array.map (<anonymous>)
    at X5 (MessageSummary.tsx:116:24)
    at MessageSummary.tsx:154:21
    at Jr (vendor.1e79e27aeb952fbe940b.js:2:810240)
    at _a (vendor.1e79e27aeb952fbe940b.js:2:856166)
    at fb (vendor.1e79e27aeb952fbe940b.js:2:848941)
    at lb (vendor.1e79e27aeb952fbe940b.js:2:848866)
    at ab (vendor.1e79e27aeb952fbe940b.js:2:845896)
    at vendor.1e79e27aeb952fbe940b.js:2:797644
    at exports.unstable_runWithPriority (vendor.1e79e27aeb952fbe940b.js:2:872944)
    at Up (vendor.1e79e27aeb952fbe940b.js:2:797353)
    at $p (vendor.1e79e27aeb952fbe940b.js:2:797589)
    at Kp (vendor.1e79e27aeb952fbe940b.js:2:797524)
    at nb (vendor.1e79e27aeb952fbe940b.js:2:842681)
    at hi (vendor.1e79e27aeb952fbe940b.js:2:814584)
    at z.<anonymous> (connect.tsx:53:9)
    at p.n (vendor.1e79e27aeb952fbe940b.js:2:911149)
    at p.emit (vendor.1e79e27aeb952fbe940b.js:2:56891)
    at z.trigger (vendor.1e79e27aeb952fbe940b.js:2:912030)
    at z._trigger (SearchStore.ts:267:12)
    at SearchStore.ts:248:18
```

```
TypeError: Cannot destructure property 'isLoading' of 'f.useContext(...)' as it is undefined.
    at MessageSummary.tsx:147:11
    at Jr (vendor.1e79e27aeb952fbe940b.js:2:810240)
    at _a (vendor.1e79e27aeb952fbe940b.js:2:856166)
    at fb (vendor.1e79e27aeb952fbe940b.js:2:848941)
    at lb (vendor.1e79e27aeb952fbe940b.js:2:848866)
    at ab (vendor.1e79e27aeb952fbe940b.js:2:845896)
    at vendor.1e79e27aeb952fbe940b.js:2:797644
    at exports.unstable_runWithPriority (vendor.1e79e27aeb952fbe940b.js:2:872944)
    at Up (vendor.1e79e27aeb952fbe940b.js:2:797353)
    at $p (vendor.1e79e27aeb952fbe940b.js:2:797589)
    at Kp (vendor.1e79e27aeb952fbe940b.js:2:797524)
    at nb (vendor.1e79e27aeb952fbe940b.js:2:842681)
    at hi (vendor.1e79e27aeb952fbe940b.js:2:814584)
    at z.<anonymous> (connect.tsx:53:9)
    at p.n (vendor.1e79e27aeb952fbe940b.js:2:911149)
    at p.emit (vendor.1e79e27aeb952fbe940b.js:2:56891)
    at z.trigger (vendor.1e79e27aeb952fbe940b.js:2:912030)
    at z._trigger (SearchStore.ts:267:12)
    at SearchStore.ts:248:18
```

**Comment by drewmiranda-gl** [comment]
Narrowed it down specifically to messages that match the following:

`(gim_event_subcategory:"alert.network alert" OR gim_event_subcategory:alert.default)`
