### ISSUE TITLE
unable to start GELF input on IPv6 address

### ISSUE THREAD

**Issue by dch** [Graylog2/graylog2-server#15177]
Want to have IPv6 input for GELF data.

## Expected Behavior

Input starts successfully

## Current Behavior

```
An input has failed to start (triggered 3 minutes ago)
Input 640bce814232ab7b1843d60f has failed to start on node 2b572ad1-3d43-4707-a729-ccbcf6a16ee9 for this reason: »null«.
```

## Steps to Reproduce (for bugs)

Add an IPv6 address GELF input, and try to start it.

## Context

IPv6 address tried as `[...]` and without `[]`, same result.

```
    bind_address:
     [fca2:927d:4d50:715c:f0b4::5]
    charset_name:
     UTF-8
    decompress_size_limit:
     8388608
    max_message_size:
     2097152
    number_worker_threads:
     4
    override_source:
     <empty>
    port:
     11514
    recv_buffer_size:
     1048576
    tcp_keepalive:
     true
    tls_cert_file:
     <empty>
    tls_client_auth:
     disabled
    tls_client_auth_cert_file:
     <empty>
    tls_enable:
     false
    tls_key_file:
     <empty>
    tls_key_password:
    ********
    use_null_delimiter:
     true
```

## Your Environment

* Graylog Version: 5.0.5
* Java Version: OpenJDK 17
* Elasticsearch Version: OpenSearch 13 1.3.6
* MongoDB Version: 5.0
* Operating System: FreeBSD 13.1-RELEASE amd64
* Browser version: firefox 112

**Comment by dch** [comment]
This used to work, IIRC under graylog 4.x and possibly an older JVM. An acceptable
workaround for me has been to use [socat](http://www.dest-unreach.org/socat/)

```
# /usr/local/etc/socat-instances.conf
[graylog]
flags="-ly TCP6-LISTEN:1514,reuseaddr,fork,reuseport TCP4:127.0.0.1:1514"
```

Which forks a process per inbound connection and proxies from IPv6 to IPv4. This
may not be suitable for environments with many connections, or short-lived ones.

**Comment by dch** [comment]
still broken in 5.1.6

**Comment by NiceRath** [comment]
Greetings!

IPv6 input-listener also not working on 5.0.7 (debian) using GELF-TCP, Syslog-TCP and Syslog-UDP.

```
2023-06-29T11:24:18.331+02:00 INFO  [InputStateListener] Input [Syslog TCP/649d4dc20f63f62fd696a775] is now STARTING
2023-06-29T11:24:18.333+02:00 WARN  [AbstractTcpTransport] Failed to start channel for input SyslogTCPInput{title=test, type=org.graylog2.inputs.syslog.tcp.SyslogTCPInput, nodeId=c434835d-ffa2-44f3-9fd7-d194e476aae8}
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address family not supported by protocol
2023-06-29T11:24:18.333+02:00 ERROR [InputLauncher] The [org.graylog2.inputs.syslog.tcp.SyslogTCPInput] input with ID <649d4dc20f63f62fd696a775> misfired. Reason: bind(..) failed: Address family not supported by protocol.
org.graylog2.plugin.inputs.MisfireException: org.graylog2.plugin.inputs.MisfireException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address family not supported by protocol
        at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:161) ~[graylog.jar:?]
        at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:91) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.graylog2.plugin.inputs.MisfireException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address family not supported by protocol
        at org.graylog2.plugin.inputs.transports.AbstractTcpTransport.launch(AbstractTcpTransport.java:224) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:158) ~[graylog.jar:?]
        ... 7 more
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address family not supported by protocol
2023-06-29T11:24:18.337+02:00 INFO  [InputStateListener] Input [Syslog TCP/649d4dc20f63f62fd696a775] is now FAILED
```

\- Rath

**Comment by NiceRath** [comment]
Interestingly:
Another server with the same version still shows the issue..

Works:
```
# version in WebUI
Graylog 5.1.5+993cd0f on xxx1 (Eclipse Adoptium 17.0.8 on Linux 5.10.0-25-amd64)

apt policy graylog-server 
> graylog-server:
>   Installed: 5.1.5-1
>   Candidate: 5.1.5-1
>   Version table:
>  *** 5.1.5-1 500
>         500 https://packages.graylog2.org/repo/debian stable/5.1 amd64 Packages
```

Does not work:
```
# version in WebUI
Graylog 5.1.5+993cd0f on xxx2 (Debian 17.0.7 on Linux 5.10.0-25-amd64)

apt policy graylog-server
> graylog-server:
>   Installed: 5.1.5-1
>   Candidate: 5.1.5-1
>   Version table:
>  *** 5.1.5-1 500
>         500 https://packages.graylog2.org/repo/debian stable/5.1 amd64 Packages
```

**Comment by NiceRath** [comment]
We were able to solve the `bind(..) failed: Address family not supported by protocol` error by removing & purging graylog and re-installing it:

```bash
apt purge graylog-server
apt purge openjdk-17-jre-headless
# reboot
```
