### ISSUE TITLE
Using 'Add to query' via dashboard widget does not work

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#15176]
Using 'Add to query' via dashboard widget does not work

```
caught (in promise) TypeError: Cannot read properties of undefined (reading 'query')
    at viewSelectors.ts:59:22
    at index.js:67:25
    at E (defaultMemoize.js:123:20)
    at index.js:81:40
    at E (defaultMemoize.js:123:20)
    at AddToQueryHandler.ts:53:52
    at index.js:16:18
    at ue (ActionHandler.tsx:98:55)
    at ActionMenuItem.tsx:146:5
    at P.handleClick (vendor.07b235e42282bd023783.js:663:52815)
    at C.handleClick (vendor.07b235e42282bd023783.js:663:97968)
    at Object.s (vendor.07b235e42282bd023783.js:671:467)
    at m (vendor.07b235e42282bd023783.js:671:617)
    at W (vendor.07b235e42282bd023783.js:671:675)
    at B (vendor.07b235e42282bd023783.js:671:862)
    at L0 (vendor.07b235e42282bd023783.js:672:7688)
    at V1 (vendor.07b235e42282bd023783.js:672:7498)
    at L1 (vendor.07b235e42282bd023783.js:672:7854)
    at fe (vendor.07b235e42282bd023783.js:672:9080)
    at J0 (vendor.07b235e42282bd023783.js:674:18836)
    at D0 (vendor.07b235e42282bd023783.js:671:2222)
    at To (vendor.07b235e42282bd023783.js:672:15168)
    at lo (vendor.07b235e42282bd023783.js:672:14724)
    at l.unstable_runWithPriority (vendor.07b235e42282bd023783.js:681:4046)
    at ir (vendor.07b235e42282bd023783.js:672:36936)
    at f0 (vendor.07b235e42282bd023783.js:674:18687)
    at Ro (vendor.07b235e42282bd023783.js:672:14536)
```

## Expected Behavior

'Add to query' adds to query

## Current Behavior

'Add to query' does not work, error in console

## Steps to Reproduce (for bugs)

1. Login to demo.graylog.cloud
2. Navigate to the 'Illuminate:WatchGuard Firebox Overview' dashboard
3. Using the 'Message Count by Message Name Over Time' widget, click on a value and choose 'Add to query'

## Context

Discovered this while presenting a demo to a prospect.

## Your Environment

* Graylog Version: Graylog Cloud 5.1.0 (373)
* Browser version: Google Chrome Version 112.0.5615.49 (Official Build) (arm64)

**Comment by drewmiranda-gl** [comment]
Let me know if there are any questions or if there is any additional information or testing i can provide.

**Comment by linuspahl** [comment]
Thank you for finding and reporting this problem! It will be fixed with https://github.com/Graylog2/graylog2-server/pull/15182.
