### ISSUE TITLE
Data node permission issues with operating system packages and container images

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#15223]
## Expected Behavior

The OpenSearch process of the data node must not write into read-only parts of the file system.

## Current Behavior

The OpenSearch process tries to write into the read-only `dist/...` directory on startup.

```
2023-04-12T15:40:09.690Z INFO  [CommandLineProcess] Running process from /usr/share/graylog-datanode/dist/opensearch-2.4.1-linux-x64/bin/opensearch
2023-04-12T15:40:10.859Z WARN  [OpensearchProcessImpl] Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
2023-04-12T15:40:10.859Z WARN  [OpensearchProcessImpl] output:
2023-04-12T15:40:10.859Z WARN  [OpensearchProcessImpl] [0.000s][error][logging] Error opening log file 'logs/gc.log': Permission denied
2023-04-12T15:40:10.859Z WARN  [OpensearchProcessImpl] [0.000s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
2023-04-12T15:40:10.860Z WARN  [OpensearchProcessImpl] error:
2023-04-12T15:40:10.860Z WARN  [OpensearchProcessImpl] Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
2023-04-12T15:40:10.860Z WARN  [OpensearchProcessImpl] Error: Could not create the Java Virtual Machine.
2023-04-12T15:40:10.860Z WARN  [OpensearchProcessImpl] Error: A fatal exception has occurred. Program will exit.
2023-04-12T15:40:10.860Z WARN  [OpensearchProcessImpl]  at org.opensearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:125)
2023-04-12T15:40:10.860Z WARN  [OpensearchProcessImpl]  at org.opensearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:87)
2023-04-12T15:40:10.861Z WARN  [OpensearchProcessImpl]  at org.opensearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:70)
2023-04-12T15:40:10.861Z WARN  [OpensearchProcessImpl]  at org.opensearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:150)
2023-04-12T15:40:10.861Z WARN  [OpensearchProcessImpl]  at org.opensearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:108)
2023-04-12T15:40:10.866Z WARN  [OpensearchProcessImpl] Opensearch process failed
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[commons-exec-1.3.jar:1.3]
        at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48) ~[commons-exec-1.3.jar:1.3]
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200) [commons-exec-1.3.jar:1.3]
        at java.lang.Thread.run(Unknown Source) [?:?]
2023-04-12T15:40:11.708Z WARN  [ProcessWatchdog] Process watchdog terminated after too many restart attempts
2023-04-12T15:40:12.721Z WARN  [ProcessWatchdog] Process watchdog terminated
```

```
2023-04-13T13:47:01.365Z WARN  [OpensearchProcessImpl] Exception in thread "main" org.opensearch.bootstrap.BootstrapException
: org.opensearch.cli.UserException: unable to create temporary keystore at [/usr/share/graylog-datanode/dist/opensearch-2.5.0
-linux-x64/config/opensearch.keystore.tmp], write permissions required for [/usr/share/graylog-datanode/dist/opensearch-2.5.0
-linux-x64/config] or run [opensearch-keystore upgrade]
2023-04-13T13:47:01.366Z WARN  [OpensearchProcessImpl] Likely root cause: java.nio.file.AccessDeniedException: /usr/share/gra
ylog-datanode/dist/opensearch-2.5.0-linux-x64/config/opensearch.keystore.tmp
```

## Context

The binaries and distribution files in operating system packages (DEB, RPM) and container images are separated from configuration and runtime data. That means the user a process runs at can not write to paths in the filesystem where binaries and distribution files reside.

## Possible Solution

We need to adjust the configuration we generate for the OpenSearch process not to try to write into distribution paths but to use the runtime data directories or temporary folders.

## Steps to Reproduce (for bugs)

1. Start the data node with a read-only `dist/...` folder

## Your Environment

* Graylog Version: 5.1.0-SNAPSHOT
* Java Version: 17

**Comment by janheise** [comment]
The keystore.tmp file is explicitly written (hardcoded) to the config dir. In this case, I guess, we have to copy the contents of the config dir to a different location first before we can change the setting to point to the new, writeable dir.
