### ISSUE TITLE
Multiple CEF messages are treated as one long timestamp field when a TCP CEF input is used, but not when a UDP CEF input is used

### ISSUE THREAD

**Issue by seanthegeek** [Graylog2/graylog2-server#15231]
## Expected Behavior

CEF logs from a FortiGate should be successfully processed over a CEF TCP input.

## Current Behavior

CEF messages are parsed correctly by Graylog over a CEF UDP input when a FortiGate firewall is configured to send CEF formatted logs over UDP. When the configuration is changed to send CEF logs over a TLS connection to a Graylog  CEF TCP input, the connection is successful, and bytes in and bytes out are shown, but the message count remains at 0. 

The Graylog server.log shows that parsing of the CEF message is failing because multiple CEF messages are being treated by the Graylog CEF parser as the timestamp of a single CEF message.

```text
2023-04-15T16:03:32.467+01:00 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=b0211ff0-db9e-11ed-b17c-0242c81e95c5, messageQueueId=1989011, codec=CEF, payloadSize=332981, timestamp=2023-04-15T15:03:32.463Z, remoteAddress=/REDACTED9:22867} on input <643862a851727d49a5b23ea6>.
2023-04-15T16:03:32.468+01:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=b0211ff0-db9e-11ed-b17c-0242c81e95c5, messageQueueId=1989011, codec=CEF, payloadSize=332981, timestamp=2023-04-15T15:03:32.463Z, remoteAddress=/REDACTED9:22867}
java.lang.IllegalStateException: Could not parse timestamp. '705 <190>Apr 15 15:03:09 gateway CEF:0|Fortinet|Fortigate|v7.2.4|54000|utm:dns dns-query|2|deviceExternalId=REDACTED FTNTFGTeventtime=1681570989531024360 FTNTFGTtz=+0000 FTNTFGTlogid=1500054000 cat=utm:dns FTNTFGTsubtype=dns FTNTFGTeventtype=dns-query FTNTFGTlevel=information FTNTFGTvd=root FTNTFGTpolicyid=0 externalId=33799373 src=REDACTED spt=58665 FTNTFGTsrccountry=Reserved deviceInboundInterface=internal FTNTFGTsrcintfrole=lan dst=REDACTED9 dpt=53 FTNTFGTdstcountry=Reserved deviceOutboundInterface=root FTNTFGTdstintfrole=undefined proto=17 FTNTFGTprofile=default FTNTFGTsrcmac=REDACTED FTNTFGTxid=55650 FTNTFGTqname=www.google.com FTNTFGTqtype=A FTNTFGTqtypeval=1 FTNTFGTqclass=IN909 <189>Apr 15 15:03:09 gateway CEF:0|Fortinet|Fortigate|v7.2.4|54802|utm:dns dns-response|3|deviceExternalId=REDACTED FTNTFGTeventtime=1681570989531135600 FTNTFGTtz=+0000 FTNTFGTlogid=1501054802 cat=utm:dns FTNTFGTsubtype=dns FTNTFGTeventtype=dns-response FTNTFGTlevel=notice FTNTFGTvd=root FTNTFGTpolicyid=0 externalId=33799373 src=REDACTED spt=58665 FTNTFGTsrccountry=Reserved deviceInboundInterface=internal FTNTFGTsrcintfrole=lan dst=REDACTED9 dpt=53 FTNTFGTdstcountry=Reserved deviceOutboundInterface=root FTNTFGTdstintfrole=undefined proto=17 FTNTFGTprofile=default FTNTFGTsrcmac=REDACTED FTNTFGTxid=55650 FTNTFGTqname=www.google.com FTNTFGTqtype=A FTNTFGTqtypeval=1 FTNTFGTqclass=IN FTNTFGTipaddr=108.177.122.104, 108.177.122.105, 108.177.122.103, 108.177.122.106, 108.177.122.147, 108.177.122.99 msg=Domain is monitored act=pass FTNTFGTcat=41 FTNTFGTcatdesc=Search Engines and Portals1267 <189>Apr 15 15:03:09 gateway CEF:0|Fortinet|Fortigate|v7.2.4[...]<190>Apr 15 15:03:31 gateway CEF:0|Fortinet|Fortigate|v7.2.4|44546|event:system|2|deviceExternalId=REDACTED FTNTFGTeventtime=1681571011398864700 FTNTFGTtz=+0000 FTNTFGTlogid=0100044546 cat=event:system FTNTFGTsubtype=system FTNTFGTlevel=information FTNTFGTvd=root FTNTFGTlogdesc=Attribute configured duser=sean sproc=ssh(REDACTED) act=Edit FTNTFGTcfgtid=1013514248 FTNTFGTcfgpath=log.syslogd.setting FTNTFGTcfgattr=port[6514->5555]mode[reliable->udp] msg=Edit log.syslogd.setting 1350 <189>Apr 15 15:03:31'
        at com.github.jcustenborder.cef.CEFParserImpl.parse(CEFParserImpl.java:162) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decodeCEF(CEFCodec.java:128) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:117) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:156) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:94) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:95) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:49) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```
For troubleshooting I replaced the CEF TLS input with a Syslog TCP input and kept the firewall configuration the same. Graylog received the message successfully and logged each CEF message separately as a raw syslog message, so the TLS connection between the firewall and Graylog is fine.

I'm not very familiar with CEF, but at first glance the raw log captured by the syslog input looks like a properly formatted CEF message to me.

![image](https://user-images.githubusercontent.com/44679/232178372-725b80dc-0330-4511-b8de-0b14d4170897.png)

Either the FortiGate is doing something different with the format of the CEF logs when TCP/TLS is used, or some internal Graylog process is breaking when it tries to read CEF from a TCP input, but I'm not sure which is the case. I have opened a case with FortiGate support to hopefully get some help from them. I have also created [a thread](https://community.graylog.org/t/fortigate-i-can-get-cef-logs-over-udp-and-syslog-over-tls-but-not-cef-over-tls-why/28442/2) in the Graylog community support forums.

## Possible Solution

I wish I knew.

## Steps to Reproduce (for bugs)

I'm using a physical FortiGate 60F running firmware version 7.2.4, but you should be able to reproduce the same issue with an [evaluation VM appliance](https://www.fortinet.com/demo-center/fortigate-vm-demo).

I've documented my entire Graylog and FortiGate setup in a tutorial post [on my blog](https://seanthegeek.net/1270/how-to-create-a-single-node-graylog-instance-and-analyze-fortigate-logs/), with the idea of helping others wanting to do the same thing. 

## Context

Firewall logs are among the most important types of logs to collect for both operations and security. I had already made a public [content pack](https://community.graylog.org/t/fortigate-cef-logs/22925) for FortiGate CEF logs years ago, but for now it seems like those logs cannot be collected over a secure channel.  

## Your Environment

* Graylog Version: 5.0.6+51f2df8 installed via the Graylog APT repository
* Java Version: Eclipse Adoptium 17.0.6
* Elasticsearch Version: OpenSearch 2.6.0
* MongoDB Version: 6.0.5
* Operating System: Debian 11 Bullseye
* Browser version: N/A

**Comment by seanthegeek** [comment]
A Graylog employee helpfully pointed me to server.log. Looks like there's an issue with the timestamp

```text
2023-04-15T03:22:33.110+01:00 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=61087542-db34-11ed-91bf-0242c81e95c5, messageQueueId=1544122, codec=CEF, payloadSize=852, timestamp=2023-04-1
5T02:22:33.108Z, remoteAddress=/10.23.1.99:17006} on input <643862a851727d49a5b23ea6>.
2023-04-15T03:22:33.110+01:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=61087540-db34-11ed-91bf-0242c81e95c5, messageQueueId=1544120, codec=CEF, payloadSize=873, timestamp=2023-04-15T02
:22:33.108Z, remoteAddress=/10.23.1.99:17006}
java.lang.IllegalStateException: Could not parse timestamp. '870 <189>Apr 15 02:22:32'
        at com.github.jcustenborder.cef.CEFParserImpl.parse(CEFParserImpl.java:162) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decodeCEF(CEFCodec.java:128) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:117) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:156) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:94) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:95) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:49) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by seanthegeek** [comment]
After more troubleshooting, I have updated this issue title and content with a much more accurate description of the bug. I still don't know if the bug is in the FortiGate Firmware or the Graylog input.

**Comment by seanthegeek** [comment]
Syslog UDP

![image|690x236](upload://u2Zu9BHjXyDNgjJcUftOwn8NwIV.png)

Raw UDP

![image|690x173](upload://nDVe5PlRTWsQb3zLYTCZBq71JNF.png)

Raw TCP (TLS) is treating separate messages like one giant message, just like the kind the CEF parser rejected.

![image|690x204](upload://kP6slR2XQGaYrbzewPNuXvFFyG5.png)

**Comment by seanthegeek** [comment]
Syslog UDP

![image](https://user-images.githubusercontent.com/44679/232251757-b6572af2-dbbe-4ebe-a711-4d231be5d2ec.png)

Raw UDP

![image](https://user-images.githubusercontent.com/44679/232251777-bc307e41-cd6c-4628-9255-f33a84575a82.png)

Raw TCP (TLS) is treating separate messages like one giant message, just like the kind the CEF parser rejected.

![image](https://user-images.githubusercontent.com/44679/232251784-b4a7a7ce-c2cd-4bb4-bc2c-3ac0dd9b449a.png)

**Comment by seanthegeek** [comment]
When I enabled the null byte delimiter on the RAW TCP input, the messages were properly split. However, as shown in this GIF, the throughput of messages kept dropping for some reason, and eventually stopped, even with TCP keepalive enabled, and the global in/out numbers never changed.

![2023-04-15_17-00-28](https://user-images.githubusercontent.com/44679/232253494-e4e9ae69-9230-4bec-bf0c-7c11b146d77b.gif)

```text
2023-04-15T22:10:03.286+01:00 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=e3ada81b-dbd1-11ed-9f68-0242c81e95c5, messageQueueId=2236944, codec=CEF, payloadSize=1, timestamp=2023-04-15T21:10:03.281Z, remoteAddress=/10.23.1.99:2149} on input <643b127b673fff3ab0da76a5>.
2023-04-15T22:10:03.286+01:00 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=e3ada81c-dbd1-11ed-9f68-0242c81e95c5, messageQueueId=2236945, codec=CEF, payloadSize=1, timestamp=2023-04-15T21:10:03.281Z, remoteAddress=/10.23.1.99:2149} on input <643b127b673fff3ab0da76a5>.
2023-04-15T22:10:03.286+01:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=e3ada81b-dbd1-11ed-9f68-0242c81e95c5, messageQueueId=2236944, codec=CEF, payloadSize=1, timestamp=2023-04-15T21:10:03.281Z, remoteAddress=/10.23.1.99:2149}
java.lang.NullPointerException: Cannot invoke "com.github.jcustenborder.cef.Message.extensions()" because "message" is null
        at org.graylog.plugins.cef.parser.MappedMessage.<init>(MappedMessage.java:37) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decodeCEF(CEFCodec.java:128) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:117) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:156) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:94) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:95) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:49) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
2023-04-15T22:10:03.286+01:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=e3ada81c-dbd1-11ed-9f68-0242c81e95c5, messageQueueId=2236945, codec=CEF, payloadSize=1, timestamp=2023-04-15T21:10:03.281Z, remoteAddress=/10.23.1.99:2149}
java.lang.NullPointerException: Cannot invoke "com.github.jcustenborder.cef.Message.extensions()" because "message" is null
        at org.graylog.plugins.cef.parser.MappedMessage.<init>(MappedMessage.java:37) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decodeCEF(CEFCodec.java:128) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:117) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:156) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:94) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:95) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:49) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
2023-04-15T22:10:13.037+01:00 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=e97db190-dbd1-11ed-9f68-0242c81e95c5, messageQueueId=2236946, codec=CEF, payloadSize=33, timestamp=2023-04-15T21:10:13.033Z, remoteAddress=/10.23.1.99:2149} on input <643b127b673fff3ab0da76a5>.
2023-04-15T22:10:13.038+01:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=e97db190-dbd1-11ed-9f68-0242c81e95c5, messageQueueId=2236946, codec=CEF, payloadSize=33, timestamp=2023-04-15T21:10:13.033Z, remoteAddress=/10.23.1.99:2149}
java.lang.NullPointerException: Cannot invoke "com.github.jcustenborder.cef.Message.extensions()" because "message" is null
        at org.graylog.plugins.cef.parser.MappedMessage.<init>(MappedMessage.java:37) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decodeCEF(CEFCodec.java:128) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:117) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:156) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:94) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:95) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:49) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by seanthegeek** [comment]
Looks like this is actually a FortiGate bug https://community.graylog.org/t/fortigate-i-can-get-cef-logs-over-udp-and-syslog-over-tls-but-not-cef-over-tls-why/28442/12?u=seanthegeek
