### ISSUE TITLE
ArrayIndexOutOfBoundsException in Alert

### ISSUE THREAD

**Issue by LatinSuD** [Graylog2/graylog2-server#15316]
I have one alert that is not working. Events are not created despite there are messages matching the query. The log reports an exception.

## Expected Behavior
Events should be craeated.

## Current Behavior
Events are not created.
I get this exception:

```
2023-04-24T10:05:03.867Z ERROR [EventProcessorEngine] Caught an unhandled exception while executing event processor <aggregation-v1/My Example Alert/641b39d698527e77c0109a04> - Make sure to modify the event processor to throw only EventProcessorExecutionException so we get more context!
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.eventsFromAggregationResult(AggregationEventProcessor.java:301) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.aggregatedSearch(AggregationEventProcessor.java:243) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:124) ~[graylog.jar:?]
        at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:91) ~[graylog.jar:?]
        at org.graylog.events.processor.EventProcessorExecutionJob.execute(EventProcessorExecutionJob.java:115) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:173) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$2(JobExecutionEngine.java:151) ~[graylog.jar:?]
        at com.codahale.metrics.Timer.time(Timer.java:151) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:151) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:120) ~[graylog.jar:?]
        at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:121) ~[graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
		
2023-04-24T10:05:03.867Z ERROR [EventProcessorExecutionJob] Event processor <aggregation-v1/641b39d698527e77c0109a04> failed to execute: Couldn't create events for: EventDefinitionDto{scope=DEFAULT, id=641b39d698527e77c0109a04, title=My Example Alert, description=My Description., priority=2, alert=true, config=AggregationEventProcessorConfig{type=aggregation-v1, query=..., queryParameters=[], streams=[64104a206a907a74edb5adf2], groupBy=[oip_geo_country_code, account, cloud_provider, protocol, oip_geo_country_name, oip_geo_continent], series=[AggregationSeries{id=card-account, function=CARD, field=Optional[account]}], conditions=Optional[AggregationConditions{expression=Optional[Greater{expr=>, left=NumberReference{expr=number-ref, ref=card-account}, right=NumberValue{expr=number, value=0.0}}]}], searchWithinMs=7200000, executeEveryMs=5000}, fieldSpec={account=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.account}, requireValues=true}]}, protocol=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.protocol}, requireValues=false}]}, oip=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.oip}, requireValues=false}]}, country_code=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.oip_geo_country_code}, requireValues=false}]}, country_name=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.oip_geo_country_name}, requireValues=false}]}, cloud_provider=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.cloud_provider}, requireValues=false}]}, continent=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.oip_geo_continent}, requireValues=false}]}}, keySpec=[account, country_code], notificationSettings=EventNotificationSettings{gracePeriodMs=0, backlogSize=0}, notifications=[Config{notificationId=642299e798527e77c0209723, notificationParameters=Optional.empty}], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]} (retry in 5000 ms)

org.graylog.events.processor.EventProcessorException: Couldn't create events for: EventDefinitionDto{scope=DEFAULT, id=641b39d698527e77c0109a04, title=My Example Alert, description=My Description., priority=2, alert=true, config=AggregationEventProcessorConfig{type=aggregation-v1, query=..., queryParameters=[], streams=[64104a206a907a74edb5adf2], groupBy=[oip_geo_country_code, account, cloud_provider, protocol, oip_geo_country_name, oip_geo_continent], series=[AggregationSeries{id=card-account, function=CARD, field=Optional[account]}], conditions=Optional[AggregationConditions{expression=Optional[Greater{expr=>, left=NumberReference{expr=number-ref, ref=card-account}, right=NumberValue{expr=number, value=0.0}}]}], searchWithinMs=7200000, executeEveryMs=5000}, fieldSpec={account=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.account}, requireValues=true}]}, protocol=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.protocol}, requireValues=false}]}, oip=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.oip}, requireValues=false}]}, country_code=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.oip_geo_country_code}, requireValues=false}]}, country_name=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.oip_geo_country_name}, requireValues=false}]}, cloud_provider=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.cloud_provider}, requireValues=false}]}, continent=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.oip_geo_continent}, requireValues=false}]}}, keySpec=[account, country_code], notificationSettings=EventNotificationSettings{gracePeriodMs=0, backlogSize=0}, notifications=[Config{notificationId=642299e798527e77c0209723, notificationParameters=Optional.empty}], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]}
        at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:105) ~[graylog.jar:?]
        at org.graylog.events.processor.EventProcessorExecutionJob.execute(EventProcessorExecutionJob.java:115) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:173) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$2(JobExecutionEngine.java:151) ~[graylog.jar:?]
        at com.codahale.metrics.Timer.time(Timer.java:151) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:151) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:120) ~[graylog.jar:?]
        at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:121) ~[graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.eventsFromAggregationResult(AggregationEventProcessor.java:301) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.aggregatedSearch(AggregationEventProcessor.java:243) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:124) ~[graylog.jar:?]
        at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:91) ~[graylog.jar:?]
        ... 12 more
```

## Possible Solution
-

## Steps to Reproduce (for bugs)
I have aggregation on 5 fields.
One of the aggregated fields must be null, but it has to be one of the middle fields (not the latst one).

Eg, the aggregation fields are:

- oip_geo_country_code
- account
- cloud_provider (this value was not present in the events that matched the query)
- protocol
- oip_geo_country_name
- oip_geo_country_continent

## Context
I was trying to define an alert.

## Your Environment
It's a 3 node cluster.

* Graylog Version: Graylog 5.0.5+d61a926
* Java Version: Eclipse Adoptium 17.0.6
* Elasticsearch Version: OpenSearch 2.0.1
* MongoDB Version: 6.0.4
* Operating System: Ubuntu 22.04 LTS
* Browser version: Chrome

**Comment by patrickmann** [comment]
As noted, the exception is thrown when trying to group by a field that does not exist in any of the messages.
We already improved the error message to make it more specific and actionable: #14375
