### ISSUE TITLE
ldap group search filter escaped values

### ISSUE THREAD

**Issue by rasebo** [Graylog2/graylog2-server#1534]
I'm trying to set-up LDAP authentication for graylog 1.2.2-1 (installed on a Debian 8 machine from the packages.graylog2.org repos), and I'm using the following group search filter:
```
(&(objectClass=group)(displayName=*)(|(memberOf:1.2.840.113556.1.4.1941:=CN=\#My Group,OU=groups,OU=myorg,DC=mydomain,DC=com)))
```
However, when I go to LDAP group mapping, it tells me that no groups have been found, and the logs contain this error:
```
2015-11-04T15:57:06.945Z WARN  [LdapConnector] Unable to iterate over user's groups, unable to perform group mapping. 
Graylog does not support LDAP referrals at the moment. Please see http://docs.graylog.org/en/1.2/pages/users_roles.html#troubleshooting for more information.
java.text.ParseException: ERR_04149 Not a valid escaped value
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseAssertionValue(FilterParser.java:264)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseExtensible(FilterParser.java:125)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseItem(FilterParser.java:688)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseFilterComp(FilterParser.java:811)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseFilterInternal(FilterParser.java:844)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseBranchNode(FilterParser.java:715)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseFilterComp(FilterParser.java:799)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseFilterInternal(FilterParser.java:844)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseBranchNode(FilterParser.java:735)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseFilterComp(FilterParser.java:792)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parseFilterInternal(FilterParser.java:844)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parse(FilterParser.java:918)
        at org.apache.directory.api.ldap.model.filter.FilterParser.parse(FilterParser.java:880)
        at org.apache.directory.api.ldap.model.message.SearchRequestImpl.setFilter(SearchRequestImpl.java:172)
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1665)
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1681)
        at org.graylog2.security.ldap.LdapConnector.findGroups(LdapConnector.java:226)
        at org.graylog2.security.ldap.LdapConnector.listGroups(LdapConnector.java:307)
        at org.graylog2.rest.resources.system.ldap.LdapResource.readGroups(LdapResource.java:302)
        at sun.reflect.GeneratedMethodAccessor198.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```
I can see the group members when using the following dsquery command:
```
dsquery * DC=mydomain,DC=com -filter "(&(objectClass=group)(displayName=*)(|(memberOf:1.2.840.113556.1.4.1941:=CN=\#My Group,OU=groups,OU=myorg,DC=mydomain,DC=com)))"
```
I assume that the issue is caused by the CN containing a "#". I've tried without the escaping character, normal escaping, escaping the escaping character, but nothing works. Any ideas?

**Comment by ssbarnea** [comment]
Interesting it seems that I encountered a similar issue when having a hash/pound sign in my filters. Any plans on fixing this? Is quite common to have the the "#" sign on groups.

**Comment by bernd** [comment]
I am unable to reproduce the escaping issue with Graylog 2.x and an Apache Directory server using the following group configuration.

![75pzi1mxd6raaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/461/16842328/5ec3cc48-49dd-11e6-9e2f-62554e399cff.png)

Also I think that the filter you posted is wrong for the "Group Search Pattern" field. The result shouldn't be a list of users but a list of groups.

```
(&(objectClass=group)(displayName=*)(|(memberOf:1.2.840.113556.1.4.1941:=CN=\#My Group,OU=groups,OU=myorg,DC=mydomain,DC=com)))
```

Please check if this is still an issue with Graylog 2.x and re-open the issue with some configuration details. Thanks!
