### ISSUE TITLE
Page size selector broken on Alerts/Events page

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#15414]
## Expected Behavior
When selecting a different page size, it should work.
## Current Behavior
Currently, the page size selector throws a JS error, so you cannot select a different page size.

```
vendor.8a712d83b311029bb0b6.js:672 Uncaught TypeError: o is not a function
    at Events.jsx:164:5
    at EventsSearchBar.jsx:66:5
    at Object.s (vendor.8a712d83b311029bb0b6.js:671:467)
    at m (vendor.8a712d83b311029bb0b6.js:671:617)
    at W (vendor.8a712d83b311029bb0b6.js:671:675)
    at D (vendor.8a712d83b311029bb0b6.js:671:862)
    at g0 (vendor.8a712d83b311029bb0b6.js:672:7688)
    at g1 (vendor.8a712d83b311029bb0b6.js:672:7498)
    at p1 (vendor.8a712d83b311029bb0b6.js:672:7854)
    at ze (vendor.8a712d83b311029bb0b6.js:672:9080)
```

## Steps to Reproduce (for bugs)
1. Got to Alerts
2. Change the page size for the table
3. Observe error in the console

## Your Environment

* Graylog Version: Graylog 5.1.0-beta.3+16b42f1 
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by drewmiranda-gl** [comment]
any eta on this?

FYI was asked about via https://community.graylog.org/t/show-function-doesnt-work/29932
