### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by uttg** [Graylog2/graylog2-server#1545]
We are using the latest allinone docker container (1.2.2) and logging via GELF UDP on an Azure VM (A4 instance with 8 cores and 14Gb Ram). We modified the jvm heap size of the container to 2Gb.

After few hours of operation we invariably hit an OutOfMemory exception:

```
WARN  [ProcessBuffer] Unable to process event MessageEvent{raw=null, message=null, messages=null}, sequence 30729
java.lang.OutOfMemoryError: Java heap space
      at java.util.Arrays.copyOf(Arrays.java:3236)
      at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
      at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
      at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
      at org.graylog2.plugin.Tools.decompressGzip(Tools.java:211)
      at org.graylog2.inputs.codecs.gelf.GELFMessage.getJSON(GELFMessage.java:135)
      at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:109)
      at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136)
      at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82)
      at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58)
      at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
      at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
      at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
```

**Comment by joschi** [comment]
Please try providing a little bit more heap space to the JVM running Graylog (e. g. 3 GiB or 4 GiB).

Could you also verify that you're running Graylog 1.2.2 by posting the output of `curl -X GET -u ${GL_USER}:${GL_PASSWORD} http://127.0.0.1:12900/system?pretty=true` (replace `${GL_USER}` and `${GL_PASSWORD}` with the username and password of the Graylog admin user and `127.0.0.1` with the actual IP address of hostname of your Graylog server).

**Comment by tomtomgod** [comment]
Yes, I confirm that the server is running 1.2.2 (I had my eye on issue #1462 which was fixed in 1.2.2)

```bash
$ curl -X GET -u ${GL_USER}:${GL_PASSWORD} http://127.0.0.1:12900/system?pretty=true 
{
  "facility" : "graylog2-server",
  "codename" : "Augustiner",
  "server_id" : "2fa94641-c70d-4b79-82b8-594ecd7426ea",
  "version" : "1.2.2 (91c7822)",
  "started_at" : "2015-11-10T14:17:14.880Z",
  "hostname" : "1e0e82944e67",
  "lifecycle" : "running",
  "lb_status" : "alive",
  "timezone" : "Etc/UTC",
  "is_processing" : true
}
```

We set the heap to 4GiB and still get OutOfMemoryError.

**Comment by joschi** [comment]
@tomtomgod Do you get the exact same error message with the same sequence ID 30729?

**Comment by tomtomgod** [comment]
@joschi, the sequence ID is different every time.

Here is a trace of the latest 3 exceptions (I only consider the first heap exception after a graylog restart)

```
2015-11-09_18:39:26.73277 WARN  [ProcessBuffer] Unable to process event MessageEvent{raw=null, message=null, messages=null}, sequence 107483
2015-11-09_18:39:26.73282 java.lang.OutOfMemoryError: Java heap space
2015-11-09_18:39:26.73283       at java.util.Arrays.copyOf(Arrays.java:3332)
2015-11-09_18:39:26.73284       at java.lang.StringCoding.safeTrim(StringCoding.java:89)
2015-11-09_18:39:26.73285       at java.lang.StringCoding.decode(StringCoding.java:230)
2015-11-09_18:39:26.73285       at java.lang.String.<init>(String.java:463)
2015-11-09_18:39:26.73286       at java.lang.String.<init>(String.java:515)
2015-11-09_18:39:26.73287       at org.graylog2.plugin.Tools.decompressGzip(Tools.java:213)
2015-11-09_18:39:26.73287       at org.graylog2.inputs.codecs.gelf.GELFMessage.getJSON(GELFMessage.java:135)
2015-11-09_18:39:26.73288       at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:109)
2015-11-09_18:39:26.73289       at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136)
2015-11-09_18:39:26.73290       at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82)
2015-11-09_18:39:26.73290       at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58)
2015-11-09_18:39:26.73291       at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
2015-11-09_18:39:26.73292       at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
2015-11-09_18:39:26.73293       at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
2015-11-09_18:39:26.73294       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-11-09_18:39:26.73294       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-11-09_18:39:26.73295       at java.lang.Thread.run(Thread.java:745)


2015-11-09_21:39:36.95953 WARN  [ProcessBuffer] Unable to process event MessageEvent{raw=null, message=null, messages=null}, sequence 22020
2015-11-09_21:39:36.95958 java.lang.OutOfMemoryError: Java heap space
2015-11-09_21:39:36.95959       at java.util.Arrays.copyOfRange(Arrays.java:3664)
2015-11-09_21:39:36.95960       at java.lang.String.<init>(String.java:207)
2015-11-09_21:39:36.95960       at java.lang.StringBuilder.toString(StringBuilder.java:407)
2015-11-09_21:39:36.95961       at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:356)
2015-11-09_21:39:36.95961       at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:235)
2015-11-09_21:39:36.95962       at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:233)
2015-11-09_21:39:36.95962       at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
2015-11-09_21:39:36.95965       at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
2015-11-09_21:39:36.95966       at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
2015-11-09_21:39:36.95966       at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2262)
2015-11-09_21:39:36.95967       at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:114)
2015-11-09_21:39:36.95969       at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136)
2015-11-09_21:39:36.95969       at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82)
2015-11-09_21:39:36.95970       at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58)
2015-11-09_21:39:36.95971       at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
2015-11-09_21:39:36.95975       at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
2015-11-09_21:39:36.95975       at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
2015-11-09_21:39:36.95976       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-11-09_21:39:36.95977       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-11-09_21:39:36.95977       at java.lang.Thread.run(Thread.java:745)


2015-11-10_00:46:01.77458 WARN  [ProcessBuffer] Unable to process event MessageEvent{raw=null, message=null, messages=null}, sequence 23170
2015-11-10_00:46:01.77463 java.lang.OutOfMemoryError: Java heap space
2015-11-10_00:46:01.77464       at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
2015-11-10_00:46:01.77464       at java.lang.StringBuilder.<init>(StringBuilder.java:101)
2015-11-10_00:46:01.77465       at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:346)
2015-11-10_00:46:01.77465       at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:235)
2015-11-10_00:46:01.77466       at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:233)
2015-11-10_00:46:01.77467       at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
2015-11-10_00:46:01.77467       at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
2015-11-10_00:46:01.77468       at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
2015-11-10_00:46:01.77469       at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2262)
2015-11-10_00:46:01.77469       at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:114)
2015-11-10_00:46:01.77471       at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136)
2015-11-10_00:46:01.77471       at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82)
2015-11-10_00:46:01.77472       at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58)
2015-11-10_00:46:01.77473       at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
2015-11-10_00:46:01.77473       at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
2015-11-10_00:46:01.77474       at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
2015-11-10_00:46:01.77475       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-11-10_00:46:01.77475       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-11-10_00:46:01.77476       at java.lang.Thread.run(Thread.java:745)
```

**Comment by kroepke** [comment]
Does this still happen with 1.3? 
Could some messages contain very large text fields?

Please reopen if you have additional information.

Thanks!
