### ISSUE TITLE
[ Graylog2 - 1.2.2 ] - Excessive logging due to "Connection reset by peer" Error

### ISSUE THREAD

**Issue by onecloudeveloper** [Graylog2/graylog2-server#1546]
Hi,

We started using graylog2 (version in subject) in a production environment with TLS enabled and a valid certificate. There are a larger number of ERROR messages of type "Connection reset by peer" appearing in the server.log with the full Exception stack trace. This is causing disk space to be filled very quickly and during moderate to high load we see an extra overhead due to additional disk IO activity. 

Suggestion: 
Can this error message be identified as WARNING or DEBUG rather than having identified as ERROR, or it would be good to NOT print the entire Exception stack trace if possible. Or alternatively is it possible to pass some command line argument or have some configuration passed to ignore this type of errors appearing in the log?

Cheers,
Mohamed

**Comment by joschi** [comment]
@onecloudeveloper Please post the complete error message you see in your Graylog server logs (ideally with some context around it).

**Comment by onecloudeveloper** [comment]
Thanks for the swift replay. Here is the Error message we're seeing in the server.log

2015-11-09T14:45:02.156Z ERROR [NettyTransport] Error on Input [GELF HTTP/560143bde4b093968233f520] (channel [id: 0xccc1d116, /143.52.XXX.XX:33899 => /10.11.10.6:12280])
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

I located the log4j configuration XML and as you said may be we can add configuration to not log ERRORs for a selected package (ex: org.jboss.netty) and probably we would have to set it to the next level which is 'FATAL' I guess. 

But, my worry is that if we do that we would not see other errors that might get masked out. Is there any way we can apply such logging configuration to a given Gralog Input?

**Comment by kroepke** [comment]
This will be fixed via #1995
