### ISSUE TITLE
Graylog WebUI error: There was an error fetching a resource: Internal Server Error. Additional information: IOException encountered while reading from a byte array input stream

### ISSUE THREAD

**Issue by ErmakovDmitriy** [Graylog2/graylog2-server#15551]
Graylog was upgraded from 5.0.2 to 5.1.0

After that, old Dashboards and Saved Searches cannot be opened with error: 

`There was an error fetching a resource: Internal Server Error. Additional information: IOException encountered while reading from a byte array input stream`

## Expected Behavior

Dashboards and Searches can be opened as before.

## Current Behavior

Web UI returns error, 
Graylog's log shows:

```
2023-05-22 14:02:26,122 ERROR   [AnyExceptionClassMapper] - Unhandled exception in REST resource - {}
java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:67) ~[graylog.jar:?]
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:49) ~[graylog.jar:?]
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:29) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42) ~[graylog.jar:?]
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:53) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42) ~[graylog.jar:?]
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:50) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:538) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:423) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:340) ~[graylog.jar:?]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:643) ~[graylog.jar:?]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:206) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:119) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:85) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:75) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:293) ~[graylog.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:233) ~[graylog.jar:?]
	at com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:332) ~[graylog.jar:?]
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:356) ~[graylog.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381) ~[graylog.jar:?]
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:355) ~[graylog.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381) ~[graylog.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:354) ~[graylog.jar:?]
	at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:329) ~[graylog.jar:?]
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67) ~[graylog.jar:?]
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:340) ~[graylog.jar:?]
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:79) ~[graylog.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191) ~[graylog.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:168) ~[graylog.jar:?]
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:810) ~[graylog.jar:?]
	at com.mongodb.DBCursor.hasNext(DBCursor.java:163) ~[graylog.jar:?]
	at org.mongojack.DBCursor.hasNext(DBCursor.java:255) ~[graylog.jar:?]
	at org.mongojack.JacksonDBCollection.findOne(JacksonDBCollection.java:1375) ~[graylog.jar:?]
	at org.mongojack.JacksonDBCollection.findOne(JacksonDBCollection.java:1345) ~[graylog.jar:?]
	at org.mongojack.JacksonDBCollection.findOneById(JacksonDBCollection.java:1293) ~[graylog.jar:?]
	at org.mongojack.JacksonDBCollection.findOneById(JacksonDBCollection.java:1280) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.db.SearchDbService.get(SearchDbService.java:78) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.SearchDomain.getForUser(SearchDomain.java:54) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.rest.SearchResource.getSearch(SearchResource.java:131) ~[graylog.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "row_limit" (class org.graylog.plugins.views.search.searchtypes.pivot.AutoValue_Pivot$Builder), not marked as ignorable (13 known properties: "query", "name", "timerange", "streams", "series", "filter", "row_groups", "type", "id", "column_groups", "sort", "rollup", "filters"])
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@1184b7ae; pos: 1035] (through reference chain: org.graylog.plugins.views.search.AutoValue_Search$Builder["queries"]->org.graylog.plugins.views.search.AutoValue_Query$Builder["search_types"]->java.util.HashSet[1]->org.graylog.plugins.views.search.searchtypes.pivot.AutoValue_Pivot$Builder["row_limit"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2036) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeFromObject(BuilderBasedDeserializer.java:344) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:240) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:144) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:357) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217) ~[graylog.jar:?]
	at com.fasterxml.jackson.datatype.guava.deser.GuavaImmutableCollectionDeserializer._deserializeContents(GuavaImmutableCollectionDeserializer.java:68) ~[graylog.jar:?]
	at com.fasterxml.jackson.datatype.guava.deser.GuavaImmutableCollectionDeserializer._deserializeContents(GuavaImmutableCollectionDeserializer.java:18) ~[graylog.jar:?]
	at com.fasterxml.jackson.datatype.guava.deser.GuavaCollectionDeserializer.deserialize(GuavaCollectionDeserializer.java:136) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2900) ~[graylog.jar:?]
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:80) ~[graylog.jar:?]
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:64) ~[graylog.jar:?]
	... 73 more
^C

```

## Steps to Reproduce (for bugs)

For us, the bug always reproduces after the upgrade.

## Context

We can not open old Dashboards and Searches.

## Your Environment

* Graylog Version: 5.1.0, Kubernetes
* Opensearch Version: 2.4.1
* MongoDB Version: 6.0.6
* Operating System: Kubernetes container.
* Browser version: Firefox 113.0

**Comment by ErmakovDmitriy** [comment]
An addition: some searches work and some return the error above. 
I can not say what the difference between the searches.

**Comment by ErmakovDmitriy** [comment]
A minor update. I have just connected to MongoDB and could see that some Searches have:
`row_limit` field in their MongoDB definitions and others do not, for example (see the "row_limit" lines):

```
{
  "_id": {
    "$oid": "63e4ae1844d517b0ad7fdcee"
  },
  "queries": [
    {
      "id": "a9022b76-66f7-4293-a2d7-71f3273cfd01",
      "timerange": {
        "from": 300,
        "type": "relative"
      },
      "filter": {
        "type": "or",
        "filters": [
          {
            "type": "stream",
            "id": "63987dc181b9d71f5f35f070"
          }
        ]
      },
      "filters": [],
      "query": {
        "type": "elasticsearch",
        "query_string": ""
      },
      "search_types": [
        {
          "timerange": {
            "from": 300,
            "type": "relative"
          },
          "query": {
            "type": "elasticsearch",
            "query_string": ""
          },
          "streams": [
            "63987dc181b9d71f5f35f070"
          ],
          "id": "79f6f465-f3f7-45d1-9715-6e0395269878",
          "name": "chart",
          "series": [
            {
              "type": "count",
              "id": "count()"
            }
          ],
          "sort": [],
          "rollup": true,
          "type": "pivot",
          "row_groups": [
            {
              "type": "time",
              "field": "timestamp",
              "interval": {
                "type": "auto",
                "scaling": 1
              }
            }
          ],
          "column_groups": [],
          "filters": [],
          "row_limit": null,
          "column_limit": null
        },
        {
          "timerange": null,
          "query": null,
          "streams": [],
          "id": "5fb57d08-abf8-422b-8ee8-f9d8907f17aa",
          "name": "chart",
          "series": [
            {
              "type": "count",
              "id": "Message Count"
            }
          ],
          "sort": [],
          "rollup": true,
          "type": "pivot",
          "row_groups": [
            {
              "type": "values",
              "field": "application_name"
            }
          ],
          "column_groups": [],
          "filters": [],
          "row_limit": 15,
          "column_limit": null
        },
        {
          "timerange": {
            "from": 300,
            "type": "relative"
          },
          "query": {
            "type": "elasticsearch",
            "query_string": ""
          },
          "streams": [
            "63987dc181b9d71f5f35f070"
          ],
          "id": "6b179cff-97d6-4c0f-8149-36b21f737c44",
          "name": null,
          "limit": 150,
          "offset": 0,
          "sort": [
            {
              "field": "timestamp",
              "order": "DESC"
            }
          ],
          "fields": [],
          "decorators": [],
          "type": "messages",
          "filters": []
        }
      ]
    }
  ],
  "parameters": [],
  "requires": {},
  "owner": "its",
  "created_at": {
    "$date": "2023-02-09T08:26:00.729Z"
  }
}
```

I hope that it will help.

**Comment by ErmakovDmitriy** [comment]
Hi dennisoelkers,
thank you for your help!

The `{type: "org.graylog2.migrations.V20230113095300_MigrateGlobalPivotLimitsToGroupingsInViews.MigrationCompleted"}`
is below:

```json
{
  "_id": {
    "$oid": "63dcb370b0856e18342f6151"
  },
  "type": "org.graylog2.migrations.V20230113095300_MigrateGlobalPivotLimitsToGroupingsInViews.MigrationCompleted",
  "payload": {
    "migrated_widgets": 113
  },
  "last_updated": {
    "$date": "2023-02-03T07:10:40.928Z"
  },
  "last_updated_by": "55f4bf4a-f1a4-4d3a-bfed-50dc11346d74"
}
```

and `{type: "org.graylog2.migrations.V20230113095301_MigrateGlobalPivotLimitsToGroupingsInSearches.MigrationCompleted"}`
is:

```json
{
  "_id": {
    "$oid": "63dcb371b0856e18342f61d0"
  },
  "type": "org.graylog2.migrations.V20230113095301_MigrateGlobalPivotLimitsToGroupingsInSearches.MigrationCompleted",
  "payload": {
    "migrated_search_types": 248
  },
  "last_updated": {
    "$date": "2023-02-03T07:10:41.006Z"
  },
  "last_updated_by": "55f4bf4a-f1a4-4d3a-bfed-50dc11346d74"
}
```

**Comment by dennisoelkers** [comment]
Thanks @ErmakovDmitriy!

For further debugging, can you execute the following query in mongo?

```
db.getCollection('views').find({ "search_id": "63e4ae1844d517b0ad7fdcee" })
```

That would help a lot debugging this. If you do not want to post it publicly, you can also send me a mail to the mail address of my profile. Thanks a lot!

**Comment by ErmakovDmitriy** [comment]
Hi Dennis,
I have sent an email to you.

// Dmitrii.

**Comment by dennisoelkers** [comment]
Thanks, got your mail! I have some more questions:

 - When did you update from `5.0.2` to `5.1.0`?
 - Did you update all of the nodes in your cluster at the same time?
 - Did you update to any intermediate versions (`5.0.3`-`5.0.7`)?

The reason I am asking is that the migrations responsible for updating your searches/dashboards to the new structure was running on February 3rd, while the search in question was created on February 9th. The migration was introduced in `5.0.3`.

Do you know how this could have happened?

In any case, we can try to run the migrations again. You can do this by performing the following queries:

```
db.getCollection('cluster_config').remove({ "type": "org.graylog2.migrations.V20230113095300_MigrateGlobalPivotLimitsToGroupingsInViews.MigrationCompleted" })

**Comment by ErmakovDmitriy** [comment]
I did the upgrade yesterday, at 15:00 CET or so.
All the nodes were upgraded sequentially - they are in a Kubernetes StatefulSet, so the containers were restarted one-by-one as soon as a previous marked itself as "healthy".

Yes, I think that at some moment I had 5.0.3 tag by mistake, thank you for pointing to this as the possible cause.

I will try to run the migrations again and report back.

**Comment by ErmakovDmitriy** [comment]
Thank you for your help!

After removing the migration states from MongoDB, I restarted both Graylogs and got in logs:

```
2023-05-23 07:45:06,663 INFO    [ServerBootstrap] - Graylog server 5.1.0+14ba491 starting up - {}
...
2023-05-23 07:45:06,719 INFO    [ServerBootstrap] - Running 53 migrations... - {}
2023-05-23 07:45:07,914 INFO    [PeriodicalsService] - Starting 26 periodicals ... - {}
```

and then when I open some of the "failed Searches", they work well as expected.

I guess that we can close the issue if you do not need any more information or diagnostics for the future, it was my mistake after all.

**Comment by dennisoelkers** [comment]
Glad to hear that, @ErmakovDmitriy! 

Providing the information was very helpful in debugging this issue and making sure it is not a bug. Thanks a lot for that!
