### ISSUE TITLE
[ShiroAuthorizationFilter] User not authorized.

### ISSUE THREAD

**Issue by rlanore** [Graylog2/graylog2-server#1557]
hi,

ii  graylog-server                           1.2.2-1                       all          Graylog server
ii  graylog-web                              1.2.2-1                       all          Graylog web

how to fix this error:
```
2015-11-12T08:39:56.773Z INFO  [ShiroAuthorizationFilter] User not authorized.
org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [indices:failures]
  at org.apache.shiro.authz.ModularRealmAuthorizer.checkPermission(ModularRealmAuthorizer.java:323)
  at org.apache.shiro.mgt.AuthorizingSecurityManager.checkPermission(AuthorizingSecurityManager.java:137)
  at org.apache.shiro.subject.support.DelegatingSubject.checkPermission(DelegatingSubject.java:205)
  at org.apache.shiro.authz.aop.PermissionAnnotationHandler.assertAuthorized(PermissionAnnotationHandler.java:74)
  at org.graylog2.shared.security.ShiroAuthorizationFilter.filter(ShiroAuthorizationFilter.java:52)
  at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
  at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
  at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
  at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:300)
  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
  at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
  at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
  at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
  at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
  at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
  at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
  at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by kroepke** [comment]
Which page are you trying to view?

**Comment by rlanore** [comment]
With nagios request:

curl -s -XGET 'http://nagios:xxxxxx@10.1.23.19:12900/system/index/count?since=2016-02-21'

workarround is to defined nagios user as Admins roles

FYI, all account and role are in LDAP directory

**Comment by dennisoelkers** [comment]
This is not a bug, but intended behavior. If the user is lacking the `indices:failures` permission, this is what the server returns when that user is trying to fetch indexer failures. You need to assign a role that contains this permission to the user you want to use. The `admin` role has this permission, but you should create a role with less privileges for usage with nagios.
