### ISSUE TITLE
Exception raised during index rotation

### ISSUE THREAD

**Issue by SJrX** [Graylog2/graylog2-server#1570]
Seems to be related to: #1002
```
2015-11-16 16:55:06,341 ERROR: org.graylog2.periodical.IndexRotationThread - Couldn't point deflector to a new index
org.elasticsearch.indices.IndexAlreadyExistsException: [graylog2_30] already exists
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:160)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:551)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$200(MetaDataCreateIndexService.java:88)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:230)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:204)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:167)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```
I am running graylog 1.2.2 , Elastisearch 1.7.3. As best I can tell every 10 seconds that error was being logged. In Elastisearch it complained about the File system reaching the high water mark. It was like this for some time ~12 days and no one noticed. The reason I guess 12 days ago is because most indexes seem to be for 3 days, but the previous one was for about 15. Even after fixing the file system issue, and restarting elastisearch and graylog it still threw this error.

Eventually I just deleted the index like this and things kind of have gotten back to normal: https://www.elastic.co/guide/en/elasticsearch/reference/1.4/indices-delete-index.html although I don't know if this was the appropriate thing to do.

The elastisearch error log was:
```
[2015-11-17 18:48:12,862][WARN ][cluster.routing.allocation.decider] [Impala] high disk watermark [90%] exceeded on [(something I removed)][Impala] free: 15.6gb[7.2%], shards will be relocated away from this node
```

**Comment by bernd** [comment]
We fixed some issues regarding index rotation in 1.3. You also had a disk space problem on your ES server which probably triggered this issue. I am closing this ticket now, please re-open if you can still see this problem with a recent release.

Thank you!
