### ISSUE TITLE
Unhandled exception in REST resource java.io.InterruptedIOException: timeout

### ISSUE THREAD

**Issue by shunyong** [Graylog2/graylog2-server#15764]
```
Unhandled exception in REST resource java.io.InterruptedIOException: timeout
Failed to call API on node <426509fb-b000-406d-be85-df4e73b7e20e>, cause: timeout (duration: 5001 ms
```
## Expected Behavior

![image](https://github.com/Graylog2/graylog2-server/assets/24327864/017b58ec-366c-41a5-afe6-54c596d8bf36)

## Current Behavior

```
2023-06-16T17:28:23.833+08:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.io.InterruptedIOException: timeout
        at okhttp3.internal.connection.Transmitter.timeoutExit(Transmitter.java:109) ~[graylog.jar:?]
        at okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:302) ~[graylog.jar:?]
        at okhttp3.internal.connection.Transmitter.noMoreExchanges(Transmitter.java:267) ~[graylog.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:237) ~[graylog.jar:?]
        at okhttp3.RealCall.execute(RealCall.java:81) ~[graylog.jar:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) ~[graylog.jar:?]
        at org.graylog2.rest.resources.cluster.ClusterSystemResource.jvm(ClusterSystemResource.java:90) ~[graylog.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.IOException: Canceled
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:82) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[graylog.jar:?]
        at org.graylog2.rest.RemoteInterfaceProvider.lambda$get$0(RemoteInterfaceProvider.java:74) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[graylog.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[graylog.jar:?]
        ... 30 more
2023-06-16T17:28:26.125+08:00 WARN  [ProxiedResource] Failed to call API on node <426509fb-b000-406d-be85-df4e73b7e20e>, cause: timeout (duration: 5002 ms)
2023-06-16T17:28:31.138+08:00 WARN  [ProxiedResource] Failed to call API on node <426509fb-b000-406d-be85-df4e73b7e20e>, cause: timeout (duration: 5001 ms)
2023-06-16T17:28:36.153+08:00 WARN  [ProxiedResource] Failed to call API on node <426509fb-b000-406d-be85-df4e73b7e20e>, cause: timeout (duration: 5002 ms)
2023-06-16T17:28:41.175+08:00 WARN  [ProxiedResource] Failed to call API on node <426509fb-b000-406d-be85-df4e73b7e20e>, cause: timeout (duration: 5002 ms)
2023-06-16T17:28:46.192+08:00 WARN  [ProxiedResource] Failed to call API on node <426509fb-b000-406d-be85-df4e73b7e20e>, cause: timeout (duration: 5002 ms)
2023-06-16T17:28:51.209+08:00 WARN  [ProxiedResource] Failed to call API on node <426509fb-b000-406d-be85-df4e73b7e20e>, cause: timeout (duration: 5002 ms)
:
```
## Possible Solution

timeout

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:5.1.2
* Java Version:
* Elasticsearch Version:7.10
* MongoDB Version:6.0
* Operating System:ubuntu 20.4
* Browser version:google clome

**Comment by dennisoelkers** [comment]
It looks like one of your nodes is not reachable/times out when called. This does not look like a bug in Graylog, but a misconfiguration of your environment.

**Comment by drewmiranda-gl** [comment]
Hi @shunyong , can you create a post at https://community.graylog.org/ at either myself or one of my coworkers (or others in the community) can troubleshoot this with you?

**Comment by shunyong** [comment]
@drewmiranda-gl I have created the same question in the graylog forum

**Comment by shunyong** [comment]
@dennisoelkers 我使用了代理下载和安装，但是取消了代理后故障依然存在

**Comment by dennisoelkers** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. I hope someone on the community board can help you debugging the underlying issue in your environment. If you discover something that indicates that this is a bug in the product itself, feel free to reopen the issue and add your additional knowledge.
