### ISSUE TITLE
Graylog does not start after upgrade from 4.2.9-1 to 5.1.2-1

### ISSUE THREAD

**Issue by oluoo** [Graylog2/graylog2-server#15854]
While on version 4.2, I imported in the metrics-reporter-prometheus plugin  and restarted the service, and came by the Guice Error. In a bid to resolve, I cleaned out the plugin, shut down all services, and upgraded all components include Graylog Service to the respective compatible versions. 

Right now, Graylog restarts every other second, but gets killed.

## Expected Behavior

Graylog service should run. All other components, MongoDB & Elastic Search are all running.

## Current Behavior

Right now, Graylog restarts every other second, but gets killed. Here is the logs from the /var/log/graylog-server/server.log

```shell
2023-06-30T18:12:13.718Z INFO  [cluster] Cluster description not yet available. Waiting for 30000 ms before timing out
2023-06-30T18:12:13.722Z INFO  [connection] Opened connection [connectionId{localValue:2, serverValue:89}] to localhost:27017
2023-06-30T18:12:13.722Z INFO  [connection] Opened connection [connectionId{localValue:1, serverValue:88}] to localhost:27017
2023-06-30T18:12:13.722Z INFO  [cluster] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=13524816}
2023-06-30T18:12:13.743Z INFO  [connection] Opened connection [connectionId{localValue:3, serverValue:90}] to localhost:27017
2023-06-30T18:12:13.771Z INFO  [MongoDBPreflightCheck] Connected to MongoDB version 5.0.14
2023-06-30T18:12:14.134Z INFO  [SearchDbPreflightCheck] Connected to (Elastic/Open)Search version <Elasticsearch:7.10.2>
2023-06-30T18:12:14.214Z INFO  [Version] HV000001: Hibernate Validator null
2023-06-30T18:12:15.217Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.events.search.MoreSearchAdapter>> was bound.
2023-06-30T18:12:15.217Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.migrations.V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter>> was bound.
2023-06-30T18:12:15.217Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.search.engine.QueryBackend<? extends org.graylog.plugins.views.search.engine.GeneratedQueryContext>>> was bound.
2023-06-30T18:12:15.217Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.search.engine.QuerySuggestionsService>> was bound.
2023-06-30T18:12:15.217Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.search.export.ExportBackend>> was bound.
2023-06-30T18:12:15.218Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.IndexToolsAdapter>> was bound.
2023-06-30T18:12:15.218Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.cluster.ClusterAdapter>> was bound.
2023-06-30T18:12:15.218Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.cluster.NodeAdapter>> was bound.
2023-06-30T18:12:15.218Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.counts.CountsAdapter>> was bound.
2023-06-30T18:12:15.218Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.fieldtypes.IndexFieldTypePollerAdapter>> was bound.
2023-06-30T18:12:15.218Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.fieldtypes.streamfiltered.esadapters.StreamsForFieldRetriever>> was bound.
2023-06-30T18:12:15.218Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.indices.IndicesAdapter>> was bound.
2023-06-30T18:12:15.218Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.messages.MessagesAdapter>> was bound.
2023-06-30T18:12:15.218Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.searches.SearchesAdapter>> was bound.
2023-06-30T18:12:15.218Z ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases$ClusterState>> was bound.
2023-06-30T18:12:15.219Z ERROR [CmdLineTool] Startup error:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<MoreSearchAdapter>> was bound.

Did you mean?
    MoreSearchAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:57)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : MoreSearchAdapterProvider.<init>(MoreSearchAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:57)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter>> was bound.

Did you mean?
    V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:65)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : V20200730000000_AddGl2MessageIdFieldAliasForEventsElasticsearchAdapterProvider.<init>(V20200730000000_AddGl2MessageIdFieldAliasForEventsElasticsearchAdapterProvider.java:34)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:65)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

3) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<QueryBackend<? extends GeneratedQueryContext>>> was bound.

Did you mean?
    QueryBackend<? extends GeneratedQueryContext> bound at VersionAwareStorageModule.bindQueryBackend(VersionAwareStorageModule.java:72)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : ElasticsearchBackendProvider.<init>(ElasticsearchBackendProvider.java:33)
      \_ for 2nd parameter
     at VersionAwareStorageModule.bindQueryBackend(VersionAwareStorageModule.java:72)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

4) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<QuerySuggestionsService>> was bound.

Did you mean?
    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    QuerySuggestionsService bound at ViewsBindings.configure(ViewsBindings.java:245)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : QuerySuggestionsProvider.<init>(QuerySuggestionsProvider.java:31)
      \_ for 2nd parameter
     at ViewsBindings.configure(ViewsBindings.java:245)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

5) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<ExportBackend>> was bound.

Did you mean?
    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    ExportBackend bound at ViewsBindings.registerExportBackendProvider(ViewsBindings.java:255)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : ExportBackendProvider.<init>(ExportBackendProvider.java:31)
      \_ for 2nd parameter
     at ViewsBindings.registerExportBackendProvider(ViewsBindings.java:255)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

6) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<IndexToolsAdapter>> was bound.

Did you mean?
    IndexToolsAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:62)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : IndexToolsAdapterProvider.<init>(IndexToolsAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:62)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

7) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<ClusterAdapter>> was bound.

Requested by:
1  : ClusterAdapterProvider.<init>(ClusterAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:59)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

8) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<NodeAdapter>> was bound.

Requested by:
1  : NodeAdapterProvider.<init>(NodeAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:60)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

9) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<CountsAdapter>> was bound.

Did you mean?
    CountsAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:54)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : CountsAdapterProvider.<init>(CountsAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:54)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

10) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<IndexFieldTypePollerAdapter>> was bound.

Did you mean?
    IndexFieldTypePollerAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:61)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : IndexFieldTypePollerAdapterProvider.<init>(IndexFieldTypePollerAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:61)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

11) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<StreamsForFieldRetriever>> was bound.

Did you mean?
    StreamsForFieldRetriever bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:53)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : StreamsForFieldRetrieverProvider.<init>(StreamsForFieldRetrieverProvider.java:33)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:53)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

12) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<IndicesAdapter>> was bound.

Did you mean?
    IndicesAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:55)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : IndicesAdapterProvider.<init>(IndicesAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:55)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

13) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<MessagesAdapter>> was bound.

Requested by:
1  : MessagesAdapterProvider.<init>(MessagesAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:58)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

14) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<SearchesAdapter>> was bound.

Did you mean?
    SearchesAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:56)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : SearchesAdapterProvider.<init>(SearchesAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:56)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

15) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<V20170607164210_MigrateReopenedIndicesToAliases$ClusterState>> was bound.

Did you mean?
    V20170607164210_MigrateReopenedIndicesToAliases$ClusterState bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:63)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : V20170607164210_MigrateReopenedIndicesToAliasesClusterStateAdapterProvider.<init>(V20170607164210_MigrateReopenedIndicesToAliasesClusterStateAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:63)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

15 errors

======================
Full classname legend:
======================
ClusterAdapter:                                                                 "org.graylog2.indexer.cluster.ClusterAdapter"
ClusterAdapterProvider:                                                         "org.graylog2.storage.providers.ClusterAdapterProvider"
CountsAdapter:                                                                  "org.graylog2.indexer.counts.CountsAdapter"
CountsAdapterProvider:                                                          "org.graylog2.storage.providers.CountsAdapterProvider"
DetectedSearchVersion:                                                          "org.graylog2.storage.DetectedSearchVersion"
ElasticsearchBackendProvider:                                                   "org.graylog2.storage.providers.ElasticsearchBackendProvider"
ElasticsearchModule:                                                            "org.graylog2.bindings.ElasticsearchModule"
ExportBackend:                                                                  "org.graylog.plugins.views.search.export.ExportBackend"
ExportBackendProvider:                                                          "org.graylog.plugins.views.providers.ExportBackendProvider"
GeneratedQueryContext:                                                          "org.graylog.plugins.views.search.engine.GeneratedQueryContext"
IndexFieldTypePollerAdapter:                                                    "org.graylog2.indexer.fieldtypes.IndexFieldTypePollerAdapter"
IndexFieldTypePollerAdapterProvider:                                            "org.graylog2.storage.providers.IndexFieldTypePollerAdapterProvider"
IndexToolsAdapter:                                                              "org.graylog2.indexer.IndexToolsAdapter"
IndexToolsAdapterProvider:                                                      "org.graylog2.storage.providers.IndexToolsAdapterProvider"
IndicesAdapter:                                                                 "org.graylog2.indexer.indices.IndicesAdapter"
IndicesAdapterProvider:                                                         "org.graylog2.storage.providers.IndicesAdapterProvider"
MessagesAdapter:                                                                "org.graylog2.indexer.messages.MessagesAdapter"
MessagesAdapterProvider:                                                        "org.graylog2.storage.providers.MessagesAdapterProvider"
MoreSearchAdapter:                                                              "org.graylog.events.search.MoreSearchAdapter"
MoreSearchAdapterProvider:                                                      "org.graylog2.storage.providers.MoreSearchAdapterProvider"
Named:                                                                          "com.google.inject.name.Named"
NamedConfigParametersModule:                                                    "com.github.joschi.jadconfig.guice.NamedConfigParametersModule"
NodeAdapter:                                                                    "org.graylog2.indexer.cluster.NodeAdapter"
NodeAdapterProvider:                                                            "org.graylog2.storage.providers.NodeAdapterProvider"
Provider:                                                                       "javax.inject.Provider"
QueryBackend:                                                                   "org.graylog.plugins.views.search.engine.QueryBackend"
QuerySuggestionsProvider:                                                       "org.graylog.plugins.views.providers.QuerySuggestionsProvider"
QuerySuggestionsService:                                                        "org.graylog.plugins.views.search.engine.QuerySuggestionsService"
SearchVersion:                                                                  "org.graylog2.storage.SearchVersion"
SearchesAdapter:                                                                "org.graylog2.indexer.searches.SearchesAdapter"
SearchesAdapterProvider:                                                        "org.graylog2.storage.providers.SearchesAdapterProvider"
StreamsForFieldRetriever:                                                       "org.graylog2.indexer.fieldtypes.streamfiltered.esadapters.StreamsForFieldRetriever"
StreamsForFieldRetrieverProvider:                                               "org.graylog2.storage.providers.StreamsForFieldRetrieverProvider"
V20170607164210_MigrateReopenedIndicesToAliases$ClusterState:                   "org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases$ClusterState"
V20170607164210_MigrateReopenedIndicesToAliasesClusterStateAdapterProvider:     "org.graylog2.storage.providers.V20170607164210_MigrateReopenedIndicesToAliasesClusterStateAdapterProvider"
V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter:        "org.graylog.plugins.views.migrations.V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter"
V20200730000000_AddGl2MessageIdFieldAliasForEventsElasticsearchAdapterProvider: "org.graylog2.storage.providers.V20200730000000_AddGl2MessageIdFieldAliasForEventsElasticsearchAdapterProvider"
VersionAwareStorageModule:                                                      "org.graylog2.storage.VersionAwareStorageModule"
ViewsBindings:                                                                  "org.graylog.plugins.views.ViewsBindings"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:568) ~[graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163) ~[graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[graylog.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:87) ~[graylog.jar:?]
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:502) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:306) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:260) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:45) [graylog.jar:?]
``` 

##Plugin List 
v4.2.9
```shell
graylog-plugin-aws-4.2.9.jar       
graylog-plugin-slack-3.1.0.jar              
graylog-plugin-threatintel-4.2.9.jar      
graylog-storage-elasticsearch7-4.2.9.jar
graylog-plugin-collector-4.2.9.jar  
graylog-plugin-slack-notification-1.0.5.jar  
graylog-storage-elasticsearch6-4.2.9.jar

``` 

v.5.1
```shell
graylog-plugin-aws-5.0.8.jar
graylog-plugin-collector-5.0.8.jar
graylog-plugin-integrations-5.0.8.jar
graylog-plugin-slack-3.1.0.jar
 graylog-plugin-slack-notification-1.0.5.jar
 graylog-plugin-threatintel-5.0.8.jar
 graylog-storage-elasticsearch7-5.0.8.jar
 graylog-storage-opensearch2-5.0.8.jar
``` 

## Your Environment

* Graylog Version: 5.1.2
* Java Version: openjdk version "17.0.7" 2023-04-18
* Elasticsearch Version: elasticsearch-oss 7.10.2 
* MongoDB Version: "5.0.14"
* Operating System: Ubuntu 20.04

**Comment by dennisoelkers** [comment]
Hey @oluoo,

thanks for reporting this. Just to make sure: You are mentioning that you are upgrading to ` v5.1.2`, but the plugins you are listing are all `5.0.8`. Is this on purpose?

**Comment by oluoo** [comment]
@dennisoelkers  thanks for your response. Yes I did upgrade using the steps provided and the `5.0.8v` plugins were installed by default alongside the upgrade of Graylog.  Are the versions for the plugins expected to be different?

**Comment by drewmiranda-gl** [comment]
For what its worth, i believe @BlueTeamNinja ran into this about a month ago and reported back with:

> Not specifying the plugin dir caused this startup failure.

@oluoo can you share/verify what your graylog server config file (`server.conf`) has for `plugin_dir`?

Example: `plugin_dir = /usr/share/graylog-server/plugin`

**Comment by BlueTeamNinja** [comment]
That is absolutely how the error presented.  Either Graylog doesn't have permission to read the plugin dir, or in this case, I would venture the plugin directory was pointed somewhere different (conf or container variable/volume) to include the additional plugin and is now missing the original required plugins. 

That's my guess in this situation. Let us know if this helps you resolve this issue. 

Cheers.

**Comment by oluoo** [comment]
@drewmiranda-gl & @BlueTeamNinja , as requested, here a the config line for the plugin_dir

`
# Set plugin directory here (relative or absolute)
plugin_dir = /usr/share/graylog-server/plugin
`

The metrics-reporter-prometheus plugin that was added initially had been removed, and the plugin list restored to default plugin.

**Comment by kroepke** [comment]
The plugin versions should all be the same version as the Graylog version itself, if there are 5.0.8 plugins in there, those will not work.
Maybe there is a mistake in the upgrade docs? Can you point to which instructions you followed so we can check, please?

**Comment by oluoo** [comment]
Sure, @kroepke  - here is a link to the list of upgrade instructions. 

- https://go2docs.graylog.org/5-0/upgrading_graylog/upgrading_graylog_in_ubuntu.htm
- https://bdts.com.au/tips-and-resources/upgrade-graylog-server-from-4-x-to-5.html

I will review the plugin lists, and update it accordingly if necessary

**Comment by BlueTeamNinja** [comment]
Can you also double check the permissions?

What is the result of `ls -lah` in your plugin directory?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
