### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by antongroot** [Graylog2/graylog2-server#1593]
Hi,

Normal small UDP WARNINGS from log4j version 1.2 are send succesfully to Graylog2. 
Larger UDP WARNINGS like java exceptions or stacktraces don't show up in Graylog2 Search.

In the server.log the following exception is shown:
```
2015-11-30T15:56:55.213+01:00 ERROR [NettyTransport] Error on Input [GELF UDP/562f8e3b1170b866fff8148a] (channel [id: 0xa9011387, /xxxxxxxxx:xxxxx])
java.lang.IndexOutOfBoundsException: index 49
        at java.util.concurrent.atomic.AtomicReferenceArray.checkedByteOffset(AtomicReferenceArray.java:78)
        at java.util.concurrent.atomic.AtomicReferenceArray.set(AtomicReferenceArray.java:139)
        at org.graylog2.inputs.codecs.GelfChunkAggregator.checkForCompletion(GelfChunkAggregator.java:142)
        at org.graylog2.inputs.codecs.GelfChunkAggregator.addChunk(GelfChunkAggregator.java:91)
        at org.graylog2.plugin.inputs.transports.NettyTransport$MessageAggregationHandler.messageReceived(NettyTransport.java:297)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.traffic.AbstractTrafficShapingHandler.messageReceived(AbstractTrafficShapingHandler.java:718)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
        at org.graylog2.plugin.inputs.util.PacketInformationDumper.messageReceived(PacketInformationDumper.java:73)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.socket.nio.NioDatagramWorker.read(NioDatagramWorker.java:98)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioDatagramWorker.run(NioDatagramWorker.java:343)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```
I have tried to send messages via TCP. After setting log4j.xml like below but messages still arrive as UDP messages in Graylog2 Search results.
```
    <appender name="GELF" class="org.graylog2.log.GelfAppender">
        <param name="graylogHost" value="tcp:xxxxxxxxxxxx"/>
        <param name="originHost" value="hostname"/>
        <param name="extractStacktrace" value="true"/>
        <param name="addExtendedInformation" value="true"/>
        <param name="facility" value="gelf-java"/>
        <param name="Threshold" value="INFO"/>
        <param name="additionalFields" value="{'environment': 'TEST', 'application': 'GeoServer'}"/>
    </appender>
```
When sent from commandline TCP works fine:
```
echo -e '{"version": "1.1","host":"hostname","short_message":"Short message","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}\0' | nc -w 1 xxxxxxxxxx xxxxx
```
Can you please help out?

- What causes the java.lang.IndexOutOfBoundsException: index 49?
- Why is TCP not working?

Thanks in advance!!

Anton Groot.

**Comment by joschi** [comment]
Which GELF appender for Log4j 1.x are you using? Which exact version of Graylog 1.2.x are you using?

Large UDP messages are split up in multiple packages (GELF chunks) which are sent to the Graylog server which in turn assembles those again (`GelfChunkAggregator`).

**Comment by antongroot** [comment]
Hi joschi,

Thanks for your reply!
I'm using:
- graylog-server-1.2.2-1 
- log4j is log4j-1.2.14-18.2

I've read some articles about the GELF chunks and set some params but this didn't resolve the issue so I reversed it again. Find below the reversed changed params:
For both graylog2 and the client I'd set the following tunables.
net.core.wmem_max = 124928        --> 262144
net.core.rmem_max = 124928         --> 262144
net.core.wmem_default = 124928    --> 262144
net.core.rmem_default = 124928     --> 262144

In Graylog2 GUI GELF INPUT --> UDP input recv_buffer_size: 262144

**Comment by antongroot** [comment]
Issue still exists after upgrading to version
graylog-web-1.3.3-1.noarch
graylog-server-1.3.3-1.noarch

Error in server.log
2016-03-01T09:32:49.546+01:00 ERROR [GelfChunkAggregator] Received duplicate chunk 54 for message 3134353638323131 from null
2016-03-01T09:32:49.557+01:00 ERROR [GelfChunkAggregator] Received duplicate chunk 54 for message 3134353638323131 from null
2016-03-01T09:32:49.558+01:00 ERROR [GelfChunkAggregator] Received duplicate chunk 54 for message 3134353638323131 from null
2016-03-01T09:34:33.263+01:00 ERROR [NettyTransport] Error on Input [GELF UDP/562f8e3b1170b866fff8148a] (channel [id: 0x00eecb25, /xx.xx.xx.xx:xxxxx])
2016-03-01T09:34:33.263+01:00 ERROR [NettyTransport] Error on Input [GELF UDP/562f8e3b1170b866fff8148a] (channel [id: 0x00eecb25, /xx.xx.xx.xx:xxxxx])
2016-03-01T09:34:33.272+01:00 ERROR [NettyTransport] Error on Input [GELF UDP/562f8e3b1170b866fff8148a] (channel [id: 0x00eecb25, /xx.xx.xx.xx:xxxxx])

Stacktrace

2016-03-01T09:36:32.218+01:00 ERROR [NettyTransport] Error on Input [GELF UDP/562f8e3b1170b866fff8148a] (channel [id: 0x00eecb25, /xx.xx.xx.xx:xxxxx])
java.lang.IndexOutOfBoundsException: index 57
        at java.util.concurrent.atomic.AtomicReferenceArray.checkedByteOffset(AtomicReferenceArray.java:78)
        at java.util.concurrent.atomic.AtomicReferenceArray.compareAndSet(AtomicReferenceArray.java:182)
        at org.graylog2.inputs.codecs.GelfChunkAggregator.checkForCompletion(GelfChunkAggregator.java:151)
        at org.graylog2.inputs.codecs.GelfChunkAggregator.addChunk(GelfChunkAggregator.java:98)
        at org.graylog2.plugin.inputs.transports.NettyTransport$MessageAggregationHandler.messageReceived(NettyTransport.java:297)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.traffic.AbstractTrafficShapingHandler.messageReceived(AbstractTrafficShapingHandler.java:718)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
        at org.graylog2.plugin.inputs.util.PacketInformationDumper.messageReceived(PacketInformationDumper.java:73)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.socket.nio.NioDatagramWorker.read(NioDatagramWorker.java:98)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioDatagramWorker.run(NioDatagramWorker.java:343)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by joschi** [comment]
@antongroot Again the same question: Which GELF appender for Log4j 1.x are you using? There are multiple GELF appenders for Log4j 1.x and it looks like the one you're using has a bug (at least in the version you're using).

**Comment by joschi** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
