### ISSUE TITLE
DataNode: startup errors after preflight. OpenSearch in "Yellow"

### ISSUE THREAD

**Issue by janheise** [Graylog2/graylog2-server#16157]
OpenSearch ends up in status`Yellow` after preflight and it is unclear, why.

With current master, I had to add the following lines to get rid of SSL errors:
`OpensearchSecurityConfiguration line` 108 (still in the block where sec config is added) `config.put("plugins.security.nodes_dn", "CN=*");`

and 

`CsrGeneratorline` 72 add another altName `names.add("localhost");`

Old stuff:

The following problem hinders OpenSearch to set the cluster from `Yellow` to `Green` so Graylog complains a lot in it's logs.

```2023-07-11 16:07:25,949 INFO : org.graylog.datanode.management.OpensearchProcessImpl - [2023-07-11T16:07:25,949][INFO ][o.o.n.Node               ] [node1] starting ...
2023-07-11 16:07:26,040 INFO : org.graylog.datanode.management.OpensearchProcessImpl - [2023-07-11T16:07:26,040][INFO ][o.o.t.TransportService   ] [node1] publish_address {jheise-mp.fritz.box/192.168.178.73:9300}, bound_addresses {[::]:9300}
2023-07-11 16:07:26,198 INFO : org.graylog.datanode.management.OpensearchProcessImpl - [2023-07-11T16:07:26,198][INFO ][o.o.b.BootstrapChecks    ] [node1] bound or publishing to a non-loopback address, enforcing bootstrap checks
2023-07-11 16:07:26,201 INFO : org.graylog.datanode.management.OpensearchProcessImpl - [2023-07-11T16:07:26,201][INFO ][o.o.c.c.Coordinator      ] [node1] cluster UUID [18BlxskRRhSpgHhsCl7kNw]
2023-07-11 16:07:26,314 INFO : org.graylog.datanode.management.OpensearchProcessImpl - [2023-07-11T16:07:26,313][WARN ][o.o.t.OutboundHandler    ] [node1] send message failed [channel: Netty4TcpChannel{localAddress=/127.0.0.1:55906, remoteAddress=localhost/127.0.0.1:9300}]
2023-07-11 16:07:26,314 INFO : org.graylog.datanode.management.OpensearchProcessImpl - javax.net.ssl.SSLHandshakeException: No name matching localhost found
2023-07-11 16:07:26,314 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
2023-07-11 16:07:26,314 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:371) ~[?:?]
2023-07-11 16:07:26,314 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:314) ~[?:?]
2023-07-11 16:07:26,314 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:309) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1549) [netty-handler-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1395) [netty-handler-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) [netty-handler-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) [netty-handler-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) [netty-codec-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) [netty-codec-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.86.Final.jar:4.1.86.Final]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at java.lang.Thread.run(Thread.java:833) [?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - Caused by: java.security.cert.CertificateException: No name matching localhost found
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:234) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.util.HostnameChecker.match(HostnameChecker.java:103) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:452) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:426) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:292) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	... 30 more
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - [2023-07-11T16:07:26,313][WARN ][o.o.t.OutboundHandler    ] [node1] send message failed [channel: Netty4TcpChannel{localAddress=/[0:0:0:0:0:0:0:1]:55905, remoteAddress=localhost/[0:0:0:0:0:0:0:1]:9300}]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - javax.net.ssl.SSLHandshakeException: No name matching localhost found
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:371) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:314) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:309) ~[?:?]
2023-07-11 16:07:26,315 INFO : org.graylog.datanode.management.OpensearchProcessImpl - 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357) ~[?:?]
```

**Comment by todvora** [comment]
Partially fixed in https://github.com/Graylog2/graylog2-server/pull/16194. There is a follow-up issue for the hostname verification: https://github.com/Graylog2/graylog2-server/issues/16219
