### ISSUE TITLE
AbstractNioSelector - Unexpected exception in the selector loop

### ISSUE THREAD

**Issue by madiTG** [Graylog2/graylog2-server#1620]
After starting the server i got tons of errors:

``````
2015-12-09 15:00:25,705 WARN : org.jboss.netty.channel.socket.nio.AbstractNioSelector - Unexpected exception in the selector loop.
java.io.IOException: Invalid argument
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:434)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2015-12-09 15:00:26,707 WARN : org.jboss.netty.channel.socket.nio.AbstractNioSelector - Unexpected exception in the selector loop.
java.io.IOException: Invalid argument
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:434)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)```
``````

Process:

```
 /usr/lib64/jvm/jre/bin/java -Djava.library.path=./../lib/sigar -Xms1280m -Xmx1280m -XX:NewRatio=1 -XX:PermSize=128m -XX:MaxPermSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -jar graylog.jar server -f /etc/graylog/server/server.conf -p /tmp/graylog.pid
```

While browsing graylog-web i get 

```
The web interface could not connect to any of the Graylog nodes it has been connected to before.

Please check that the servers shown to the right are running and reachable.
```

frequently

**Comment by joschi** [comment]
@madiTG Which version of Graylog are you running? Which operating-system?

**Comment by madiTG** [comment]
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 0

graylog-web-interface v1.3.0 (04201bb) (Oracle Corporation 1.7.0_91 / Linux 3.12.51-52.31-default)

Server:

graylog-1.3.0

**Comment by joschi** [comment]
This seems to be a common problem with SUSE Linux: https://groups.google.com/d/msg/graylog2/JAF29V1w56k/Yd_nd8o9EAAJ

**Comment by madiTG** [comment]
Found this before. Seems like i have no AppArmor or SELInux or anything enabled. Got any solution?

**Comment by madiTG** [comment]
Moved back to SLES 11 and everything works fine

**Comment by joschi** [comment]
@madiTG Thanks for the update. Seems to be a problem with the kernel used in SLES 12.

**Comment by bernd** [comment]
We switched to a new major version of netty in the meantime. Please open a new issue if this is still a problem for you. Thank you!
