### ISSUE TITLE
 Failed to execute phase [fetch], [reduce]

### ISSUE THREAD

**Issue by evanccnyc** [Graylog2/graylog2-server#1625]
Hi there,

On graylog 1.2 I have recently been getting the following message on a Quick Values chart for a field called "response_code" (its HTTP response values). No other "Quick Values" charts have this problem using the same time range etc.

It seems to happen periodically, with it sometimes returning data sometimes not.

The web frontend returns a 400, with a Bad Request response and no other information.

This is from the logs on the graylog server:

```
2015-12-10T17:03:44.193Z WARN  [SearchResource] Unable to execute search: Failed to execute phase [fetch], [reduce]
2015-12-10T17:03:54.229Z ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
org.elasticsearch.action.search.ReduceSearchPhaseException: Failed to execute phase [fetch], [reduce]
	at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.onFailure(TransportSearchQueryThenFetchAction.java:159)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: org.elasticsearch.search.aggregations.bucket.terms.LongTerms$Bucket cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket
	at org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket.compareTerm(StringTerms.java:85)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$4.compare(InternalOrder.java:87)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$4.compare(InternalOrder.java:83)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$CompoundOrder$CompoundOrderComparator.compare(InternalOrder.java:284)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$CompoundOrder$CompoundOrderComparator.compare(InternalOrder.java:270)
	at org.elasticsearch.search.aggregations.bucket.terms.support.BucketPriorityQueue.lessThan(BucketPriorityQueue.java:37)
	at org.elasticsearch.search.aggregations.bucket.terms.support.BucketPriorityQueue.lessThan(BucketPriorityQueue.java:26)
	at org.apache.lucene.util.PriorityQueue.upHeap(PriorityQueue.java:225)
	at org.apache.lucene.util.PriorityQueue.add(PriorityQueue.java:133)
	at org.apache.lucene.util.PriorityQueue.insertWithOverflow(PriorityQueue.java:149)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms.reduce(InternalTerms.java:195)
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:140)
	at org.elasticsearch.search.aggregations.bucket.InternalSingleBucketAggregation.reduce(InternalSingleBucketAggregation.java:79)
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:140)
	at org.elasticsearch.search.controller.SearchPhaseController.merge(SearchPhaseController.java:407)
	at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.doRun(TransportSearchQueryThenFetchAction.java:147)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	... 3 more
2015-12-10T17:03:59.289Z ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
org.elasticsearch.action.search.ReduceSearchPhaseException: Failed to execute phase [fetch], [reduce]
	at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.onFailure(TransportSearchQueryThenFetchAction.java:159)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: org.elasticsearch.search.aggregations.bucket.terms.LongTerms$Bucket cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket
	at org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket.compareTerm(StringTerms.java:85)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$4.compare(InternalOrder.java:87)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$4.compare(InternalOrder.java:83)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$CompoundOrder$CompoundOrderComparator.compare(InternalOrder.java:284)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$CompoundOrder$CompoundOrderComparator.compare(InternalOrder.java:270)
	at org.elasticsearch.search.aggregations.bucket.terms.support.BucketPriorityQueue.lessThan(BucketPriorityQueue.java:37)
	at org.elasticsearch.search.aggregations.bucket.terms.support.BucketPriorityQueue.lessThan(BucketPriorityQueue.java:26)
	at org.apache.lucene.util.PriorityQueue.upHeap(PriorityQueue.java:225)
	at org.apache.lucene.util.PriorityQueue.add(PriorityQueue.java:133)
	at org.apache.lucene.util.PriorityQueue.insertWithOverflow(PriorityQueue.java:149)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms.reduce(InternalTerms.java:195)
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:140)
	at org.elasticsearch.search.aggregations.bucket.InternalSingleBucketAggregation.reduce(InternalSingleBucketAggregation.java:79)
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:140)
	at org.elasticsearch.search.controller.SearchPhaseController.merge(SearchPhaseController.java:407)
	at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.doRun(TransportSearchQueryThenFetchAction.java:147)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	... 3 more

```

**Comment by evanccnyc** [comment]
Just as a followup, I created a new Index but no change. So no idea why I am getting these errors.

**Comment by magicdude4eva** [comment]
I am getting the same (but on Graylog 1.3):
```
2015-12-21T10:14:52.425+02:00 WARN  [SearchResource] Unable to execute search: Failed to execute phase [fetch], [reduce] 
2015-12-21T10:14:55.421+02:00 WARN  [SearchResource] Unable to execute search: Failed to execute phase [fetch], [reduce] 
```
Interestingly enough, the Quick Values do work for most fields and the error seems to be specific to some fields (I have not been able to figure out a pattern in why some work and others don't).

**Comment by kroepke** [comment]
This usually indicates that some part of the time range you are searching for (i.e. one index the time range spans) has a different dynamic mapping for the field you are looking at.
IOW at some point the field contained a long instead of a string. Without setting a mapping template or adjusting the extractors or making sure that the field is consistent at the senders, there's not much we can do about this.

**Comment by magicdude4eva** [comment]
For what it's worth, I have just updated Graylog and ElasticSearch and the same query functions now perfectly fine for Quick Values:
```
    Updated elasticsearch-1.7.3-1.noarch                @elasticsearch-1.7
    Update                1.7.4-1.noarch                @elasticsearch-1.7
    Updated graylog-server-1.3.0-3.noarch               @graylog
    Update                 1.3.2-1.noarch               @graylog
```

**Comment by evanccnyc** [comment]
If it is something that is just about dynamic mapping, any chance we can alter the error message or make it more obvious?
