### ISSUE TITLE
com.google.inject.CreationException: Unable to create injector

### ISSUE THREAD

**Issue by TianManStar** [Graylog2/graylog2-server#16297]
This is the server log：
   1) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<MoreSearchAdapter>> was bound.

Did you mean?
    MoreSearchAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:60)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : MoreSearchAdapterProvider.<init>(MoreSearchAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:60)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION
how should i solve it？

**Comment by dennisoelkers** [comment]
Hey @TianManStar,

how did you install/start Graylog?

**Comment by TianManStar** [comment]
hey @Member dennisoelkers
started by the compiler

**Comment by TianManStar** [comment]
@dennisoelkers 
Thanks to dennisoelkers, what I am doing now is to pull the source code from the remote warehouse, first run mvn compile, then modify the address of configFile under CmdLineTool.java, map it to the file of server.conf, and configure mongodb in server.conf address and elasticsearch address, and finally encountered the problem of "No implementation for Map<SearchVersion, Provider<MoreSearchAdapter>> was bound"

**Comment by janheise** [comment]
@TianManStar did you open a second ticket for that? #16298

also, what do you mean by you started it with the compiler? if you start the server, you can specify the conf file e.g. via `server -f graylog.conf` why do you modify the code for that?

**Comment by TianManStar** [comment]
I just specified the conf file, still can't work

**Comment by janheise** [comment]
@TianManStar can you please give more info what you're trying to accomplish? If you just want to start/install graylog, I suggest you try one of the regular packages first? You can test a different config file location with the packages, too. Because the Guice bug is probably misleading and just a missing config option/file.

**Comment by dennisoelkers** [comment]
Closing this due to inactivity.
