### ISSUE TITLE
No implementation for Map<SearchVersion, Provider<MoreSearchAdapter>> was bound.

### ISSUE THREAD

**Issue by TianManStar** [Graylog2/graylog2-server#16298]
what I am doing now is to pull the source code from the remote warehouse, first run mvn compile, then modify the address of configFile under CmdLineTool.java, map it to the file of server.conf, and configure mongodb in server.conf address and elasticsearch address, and finally encountered the problem of "No implementation for Map<SearchVersion, Provider<MoreSearchAdapter>> was bound"，the server's log is as follows:
  2023-08-29 15:59:52,092 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.events.search.MoreSearchAdapter>> was bound.
2023-08-29 15:59:52,093 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.migrations.V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter>> was bound.
2023-08-29 15:59:52,093 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.search.engine.QueryBackend<? extends org.graylog.plugins.views.search.engine.GeneratedQueryContext>>> was bound.
2023-08-29 15:59:52,094 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.search.engine.QuerySuggestionsService>> was bound.
2023-08-29 15:59:52,094 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.search.export.ExportBackend>> was bound.
2023-08-29 15:59:52,095 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.IndexToolsAdapter>> was bound.
2023-08-29 15:59:52,095 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.cluster.ClusterAdapter>> was bound.
2023-08-29 15:59:52,096 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.cluster.NodeAdapter>> was bound.
2023-08-29 15:59:52,096 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.counts.CountsAdapter>> was bound.
2023-08-29 15:59:52,096 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.fieldtypes.IndexFieldTypePollerAdapter>> was bound.
2023-08-29 15:59:52,097 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.fieldtypes.streamfiltered.esadapters.StreamsForFieldRetriever>> was bound.
2023-08-29 15:59:52,097 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.indices.IndicesAdapter>> was bound.
2023-08-29 15:59:52,097 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.messages.MessagesAdapter>> was bound.
2023-08-29 15:59:52,099 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.results.MultiChunkResultRetriever>> was bound.
2023-08-29 15:59:52,099 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.searches.SearchesAdapter>> was bound.
2023-08-29 15:59:52,099 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases$ClusterState>> was bound.
2023-08-29 15:59:52,100 ERROR: org.graylog2.bootstrap.CmdLineTool - Startup error:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<MoreSearchAdapter>> was bound.

Did you mean?
    MoreSearchAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:60)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : MoreSearchAdapterProvider.<init>(MoreSearchAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:60)

**Comment by janheise** [comment]
closing this one as we're having the discussion in #16297
