### ISSUE TITLE
The project source code cannot be started

### ISSUE THREAD

**Issue by jks-jks** [Graylog2/graylog2-server#16402]
## Current Behavior

I encountered the following error while compiling the graylog source code using Intellij IDEA after running the mvn compile. I am currently unable to resolve it, and I would like to seek advice. Thank you. The log is included in the content.

## Context

log：2023-09-08 15:55:44,721 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.events.search.MoreSearchAdapter>> was bound.
2023-09-08 15:55:44,721 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.migrations.V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter>> was bound.
2023-09-08 15:55:44,721 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.search.engine.QueryBackend<? extends org.graylog.plugins.views.search.engine.GeneratedQueryContext>>> was bound.
2023-09-08 15:55:44,721 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.search.engine.QuerySuggestionsService>> was bound.
2023-09-08 15:55:44,725 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog.plugins.views.search.export.ExportBackend>> was bound.
2023-09-08 15:55:44,725 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.IndexToolsAdapter>> was bound.
2023-09-08 15:55:44,725 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.cluster.ClusterAdapter>> was bound.
2023-09-08 15:55:44,725 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.cluster.NodeAdapter>> was bound.
2023-09-08 15:55:44,725 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.counts.CountsAdapter>> was bound.
2023-09-08 15:55:44,725 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.fieldtypes.IndexFieldTypePollerAdapter>> was bound.
2023-09-08 15:55:44,725 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.fieldtypes.streamfiltered.esadapters.StreamsForFieldRetriever>> was bound.
2023-09-08 15:55:44,729 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.indices.IndicesAdapter>> was bound.
2023-09-08 15:55:44,729 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.messages.MessagesAdapter>> was bound.
2023-09-08 15:55:44,729 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.results.MultiChunkResultRetriever>> was bound.
2023-09-08 15:55:44,729 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.indexer.searches.SearchesAdapter>> was bound.
2023-09-08 15:55:44,729 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, javax.inject.Provider<org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases$ClusterState>> was bound.
2023-09-08 15:55:44,729 ERROR: org.graylog2.bootstrap.CmdLineTool - Startup error:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<MoreSearchAdapter>> was bound.

Did you mean?
    MoreSearchAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:60)

    SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)
    
    SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

Requested by:
1  : MoreSearchAdapterProvider.<init>(MoreSearchAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:60)

## Expected behavior

The project source code can be successfully launched

## Your Environment：

Graylog Version: 5.1
Java Version: OpenJDK 17
Elasticsearch Version: 7.10.8
MongoDB Version: 4.2

**Comment by dennisoelkers** [comment]
Hey @jks-jks,

if you just want to run Graylog, it would be easier to use OS packages or docker images. What are you trying to do?

**Comment by jks-jks** [comment]
I want to customize and develop some things, such as customizing some API

**Comment by dennisoelkers** [comment]
What exactly do you want to customize? Maybe there is a plugin for it?
