### ISSUE TITLE
graylog-server dies for unknown reasons after running for a period of time. Do not consume kafka data.

### ISSUE THREAD

**Issue by magicgaro** [Graylog2/graylog2-server#16497]
graylog-server dies for unknown reasons after running for a period of time. Do not consume kafka data.
## Current Behavior

It will reproduce this problem from time to time, but the longest time does not exceed one day.
When the problem occurred, both the Input buffer and the Process buffer were full, and it stopped working.

![image](https://github.com/Graylog2/graylog2-server/assets/16775931/a03ffee5-2fc6-4e29-90c1-152916cdef7a)
![image](https://github.com/Graylog2/graylog2-server/assets/16775931/e2f3c62d-4d7b-4c66-b670-11bd7e506eff)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:Graylog 5.1.4
* Java Version:openjdk version "17.0.8" 2023-07-18
* OpenSearch Version:opensearch-2.9.0
* MongoDB Version:MongoDB6.0.9
* Operating System:CentOS Linux release 7.5.1804
* Browser version:

**Comment by magicgaro** [comment]
It had issue with Graylog 4.3.15. During this period, I upgraded it to Graylog 5.1.4, ES was also replaced by opensearch, and the kafka version was also upgraded.

**Comment by magicgaro** [comment]
Is it a BUG in this component?

"processbufferprocessor-19" id=153 state=WAITING
    - waiting on <0x36858d97> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x36858d97> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
    at java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
    at java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
    at java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at app//com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:47)
    at app//com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
    at app//com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148)
    at app//com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
    at java.base@17.0.8/java.lang.Thread.run(Unknown Source)

**Comment by dennisoelkers** [comment]
Hey @magicgaro,

do you see anything in your server logs?

The snippet from `jstack` looks okay, it is one of the processors waiting for the ring buffer to offer a new message for processing.

**Comment by magicgaro** [comment]
> Hey @magicgaro,
> 
> do you see anything in your server logs?
> 
> The snippet from `jstack` looks okay, it is one of the processors waiting for the ring buffer to offer a new message for processing.
hi @dennisoelkers 
There seems to be nothing unusual in the graylog service log, except that a large number of kafka rebalancing and LeaveGroup logs were reported at the time of the problem. like this:
![image](https://github.com/Graylog2/graylog2-server/assets/16775931/19822750-d309-458d-9410-fd81c52bb054)

**Comment by dennisoelkers** [comment]
Do you have any regex configured for stream matching/extractors/pipeline rules? It looks like your node is spending a lot of time for processing.

**Comment by magicgaro** [comment]
> Do you have any regex configured for stream matching/extractors/pipeline rules? It looks like your node is spending a lot of time for processing.

Yes, I have a lot of regular expressions used in these places, and I am also looking at images to troubleshoot this problem, but I don't have enough information to confirm the problem. And I configured another cluster with the same expression and it ran stably. If there is a real regularity issue, how can I quickly and accurately locate the problematic expression?

**Comment by dennisoelkers** [comment]
You can go to `System` -> `Nodes` -> `Metrics` and check the metrics related to `org.graylog.plugins.pipelineprocessor.ast.Rule` for their maximum runtimes.

Alternatively, you can use the API endpoint `POST /api/cluster/metrics/multiple` which takes a `metrics` field in its JSON body, which is a set of metrics you want to look at.

**Comment by magicgaro** [comment]
I think I have found the issue. It may be some special logs that cause problems with the input regular matching I configured.
I'm trying to modify the regex to fix it. Hopefully, specific error messages will be thrown in future versions.

**Comment by magicgaro** [comment]
> You can go to `System` -> `Nodes` -> `Metrics` and check the metrics related to `org.graylog.plugins.pipelineprocessor.ast.Rule` for their maximum runtimes.
> 
> Alternatively, you can use the API endpoint `POST /api/cluster/metrics/multiple` which takes a `metrics` field in its JSON body, which is a set of metrics you want to look at.
hi @dennisoelkers ,
I think I found the problem, I configured grok in the input to split the fields, and I found that the useragent in part of the received log (nginx log) had a large number of spaces. This is the problem caused by this kind of log. My regular configuration is \"%{NGINXLOG:http_user_agent}?\", where NGINXLOG = ([^"]+).
![image](https://github.com/Graylog2/graylog2-server/assets/16775931/1080bd02-c50b-463c-affc-e0b1cbd501d8)
![image](https://github.com/Graylog2/graylog2-server/assets/16775931/02b36797-2eb5-4064-895e-445c6f9b5ec3)

**Comment by dennisoelkers** [comment]
Great to hear you have found the issue!

> Hopefully, specific error messages will be thrown in future versions.

What would be your suggestion for us to log, and when?

**Comment by gddai** [comment]
您好，idea工具运行graylog有相关教程吗？
