### ISSUE TITLE
Could not apply converter [tokenizer] of extractor (because of Multiple entries with same key) ?

### ISSUE THREAD

**Issue by lxf1992521** [Graylog2/graylog2-server#1663]
Hi,

when i convert message which include some "key=value" by tokenizer, it is failed and give this error:

```
2016-01-05T06:04:23.899Z ERROR [Extractor] Could not apply converter [tokenizer] of extractor [3ff68450-b364-11e5-a
9e9-001ec9b3e0ad].
java.lang.IllegalArgumentException: Multiple entries with same key: request_path_hash_usearch=true and request_path
_hash_usearch=true
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
        ......
```

this error says that find the same key in messages, and don't kown how to deal with it.

in my opinion, it is a mistake to report the error instead of overwrite the old same keys.

so please have a look.

**Comment by lasdem** [comment]
We see the same in our deployment and it produces alot of noise in our graylog logs. It would be nice if the extractor would just choose the first or the last value and leave no error message in the logs.

**Comment by fedwmt** [comment]
We're seeing the same as well, running Graylog 2.0.2:

```shell
2016-06-02 22:52:41,051 ERROR: org.graylog2.plugin.inputs.Extractor - Could not apply converter [tokenizer] of extractor [5c29f261-2826-11e6-b408-fa163e2a1323].
java.lang.IllegalArgumentException: Multiple entries with same key: HOST=jdbc:oracle:thin:@(DESCRIPTION//=(LOAD_BALANCE//=on)(ADDRESS//=(PROTOCOL//=TCP)(HOST//=XXXXXXXXXX) and HOST=jdbc:oracle:thin:@(DESCRIPTION//=(LOAD_BALANCE//=on)(ADDRESS//=(PROTOCOL//=TCP)(HOST//=XXXXXXXXXX)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136) ~[graylog.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98) ~[graylog.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84) ~[graylog.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295) ~[graylog.jar:?]
	at org.graylog2.inputs.converters.TokenizerConverter.convert(TokenizerConverter.java:55) ~[graylog.jar:?]
	at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:250) [graylog.jar:?]
	at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:228) [graylog.jar:?]
	at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:62) [graylog.jar:?]
	at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:100) [graylog.jar:?]
	at org.graylog2.buffers.processors.ServerProcessBufferProcessor.handleMessage(ServerProcessBufferProcessor.java:56) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:82) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:61) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

**Comment by wouterhummelink** [comment]
This happens frequently when extracting key-values from iptables logs
java.lang.IllegalArgumentException: Multiple entries with same key: LEN=70 and LEN=90
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136) ~[graylog.jar:?]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98) ~[graylog.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84) ~[graylog.jar:?]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295) ~[graylog.jar:?]
        at org.graylog2.inputs.converters.TokenizerConverter.convert(TokenizerConverter.java:55) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:250) [graylog.jar:?]
        at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:228) [graylog.jar:?]
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:62) [graylog.jar:?]
        at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:100) [graylog.jar:?]
        at org.graylog2.buffers.processors.ServerProcessBufferProcessor.handleMessage(ServerProcessBufferProcessor.java:56) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:82) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:61) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
