### ISSUE TITLE
Periodical Plugin: Error injecting constructor, java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays

### ISSUE THREAD

**Issue by alpha-centauri** [Graylog2/graylog2-server#1669]
There is an issue with injecting the constructor of a periodical plugin. From the logs, I get a java.lang.NoClassDefFoundError for scala/actors/threadpool/Arrays

```
Error injecting constructor, java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
  at ... MyPeriodical.<init>(...)
  while locating ... MyPeriodical
  while locating org.graylog2.plugin.periodical.Periodical annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=144, type=MULTIBINDER, keyType=)
  at org.graylog2.shared.bindings.SharedPeriodicalBindings.configure(SharedPeriodicalBindings.java:30) (via modules: org.graylog2.shared.bindings.SharedPeriodicalBindings -> com.google.inject.multi
bindings.Multibinder$RealMultibinder)
  while locating java.util.Set<org.graylog2.plugin.periodical.Periodical>
    for parameter 2 at org.graylog2.shared.initializers.PeriodicalsService.<init>(PeriodicalsService.java:49)
  at org.graylog2.shared.initializers.PeriodicalsService.class(PeriodicalsService.java:39)
  while locating org.graylog2.shared.initializers.PeriodicalsService
  while locating com.google.common.util.concurrent.Service annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=5, type=MULTIBINDER, keyType=)
  at org.graylog2.shared.bindings.GenericInitializerBindings.configure(GenericInitializerBindings.java:27) (via modules: org.graylog2.shared.bindings.GenericInitializerBindings -> com.google.inject
.multibindings.Multibinder$RealMultibinder)
  while locating java.util.Set<com.google.common.util.concurrent.Service>
    for field at org.graylog2.shared.bindings.providers.ServiceManagerProvider.services(ServiceManagerProvider.java:33)
  while locating org.graylog2.shared.bindings.providers.ServiceManagerProvider
  at org.graylog2.shared.bindings.GenericBindings.configure(GenericBindings.java:67)
  while locating com.google.common.util.concurrent.ServiceManager
Caused by: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
        at ...
```

Basically, this is my Periodical class:

```java
public class MyPeriodical extends Periodical
{
  @Inject
  public MyPeriodical(...)
  { ... }
}
```

My Plugin worked very well for Graylog versions up to 1.0 at least. Since I recompiled it for versions 1.2.1 and later, the exception has been occurring at server startup. What has changed that would cause the injection issues?

**Comment by kroepke** [comment]
This sounds like a bad import to me. Between 1.0 and 1.2.x probably the scala version (via the kafka dependency) has changed, which most likely has seen the scala.actors.threadpool.Arrays class moved.

Without seeing source code (at least the imports) or the entire error message I can't determine what the actual problem is.

The periodical code itself has not changed for a long time, though.

**Comment by alpha-centauri** [comment]
Indeed, it was a bad import and a perfect storm made me overlook it. Thank you for the fast reply!
