### ISSUE TITLE
ERROR [NettyContainer] Uncaught exception during jersey resource handling

### ISSUE THREAD

**Issue by libby2cm** [Graylog2/graylog2-server#1687]
Since upgrading to 1.2, I have had problems with GL server crashing.  It will be serving requests, then just die.  Sometimes it's fine for a couple days, sometimes it dies within a day.  4 core, 7gb ram on VM's.  GL servers are load balanced, one will die, then at some point, other will die too.  Only running about 100 messages/sec at peak.  I am on 1.3.2 now, and issue persists.

Last message in stack trace log is:
```
2016-01-11T15:27:03.849-05:00 ERROR [NettyContainer] Uncaught exception during jersey resource handling
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by joschi** [comment]
This is most likely an aftereffect of the original error. Could you please post the complete log (or at least a reasonable amount of backlog) from your Graylog server node(s)?

**Comment by kroepke** [comment]
Please reopen this issue once you have more information about the problem.

Thank you!
