### ISSUE TITLE
TLS syslog input fails

### ISSUE THREAD

**Issue by ptman** [Graylog2/graylog2-server#1690]
Hi,

I'm testing the graylog docker images. I tried adding a TLS syslog input:

    recv_buffer_size: 1048576
    port: 6514
    tls_key_file: /opt/graylog/conf/nginx/ca/srv.key
    tls_key_password: *******
    tls_enable: true
    tls_client_auth_cert_file: /opt/graylog/conf/nginx/ca/ca.crt
    max_message_size: 2097152
    tls_client_auth: required
    override_source:
    allow_override_date: true
    bind_address: 0.0.0.0
    tls_cert_file: /opt/graylog/conf/nginx/ca/srv.crt

Which starts fine, but when I try to actually send data from rsyslog, I get this stack trace:

    2016-01-13_07:09:28.48970 WARN  [AbstractTcpTransport] client auth configured, but no authorized certificates / certificate authorities configured
    2016-01-13_07:09:28.59464 ERROR [NettyTransport] Error on Input [Syslog TCP/5695f77ce4b0c071128c6d58] (channel [id: 0x6ffd2a64, /10.2.0.5:35467 => /172.17.0.2:6514])
    2016-01-13_07:09:28.59466 javax.net.ssl.SSLHandshakeException: General SSLEngine problem
    2016-01-13_07:09:28.59976   at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431)
    2016-01-13_07:09:28.60346   at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
    2016-01-13_07:09:28.60678   at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
    2016-01-13_07:09:28.60924   at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
    2016-01-13_07:09:28.61766   at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
    2016-01-13_07:09:28.62610   at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
    2016-01-13_07:09:28.63725   at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
    2016-01-13_07:09:28.64147   at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
    2016-01-13_07:09:28.65128   at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    2016-01-13_07:09:28.65581   at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    2016-01-13_07:09:28.66571   at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    2016-01-13_07:09:28.67602   at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    2016-01-13_07:09:28.68477   at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    2016-01-13_07:09:28.68799   at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    2016-01-13_07:09:28.69649   at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    2016-01-13_07:09:28.70011   at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    2016-01-13_07:09:28.73156   at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    2016-01-13_07:09:28.73734   at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    2016-01-13_07:09:28.74729   at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    2016-01-13_07:09:28.75320   at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    2016-01-13_07:09:28.75828   at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    2016-01-13_07:09:28.76107   at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
    2016-01-13_07:09:28.76519   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    2016-01-13_07:09:28.76812   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    2016-01-13_07:09:28.77319   at java.lang.Thread.run(Thread.java:745)
    2016-01-13_07:09:28.77538 Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
    2016-01-13_07:09:28.78122   at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    2016-01-13_07:09:28.78356   at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
    2016-01-13_07:09:28.78714   at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
    2016-01-13_07:09:28.79320   at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
    2016-01-13_07:09:28.79598   at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1882)
    2016-01-13_07:09:28.79841   at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:230)
    2016-01-13_07:09:28.80484   at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
    2016-01-13_07:09:28.80719   at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)
    2016-01-13_07:09:28.82120   at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)
    2016-01-13_07:09:28.82730   at java.security.AccessController.doPrivileged(Native Method)
    2016-01-13_07:09:28.83284   at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)
    2016-01-13_07:09:28.83539   at org.jboss.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1392)
    2016-01-13_07:09:28.84050   at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1255)
    2016-01-13_07:09:28.84278   ... 19 more
    2016-01-13_07:09:28.84738 Caused by: java.security.cert.CertificateException: No X509TrustManager implementation available
    2016-01-13_07:09:28.84740   at sun.security.ssl.DummyX509TrustManager.checkClientTrusted(SSLContextImpl.java:1126)
    2016-01-13_07:09:28.85246   at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1869)
    2016-01-13_07:09:28.85475   ... 27 more

I would've thought that tls_client_auth_cert_file is the certificate authority needed for this.

The version information in the web interface footer says: graylog-web-interface v1.3.2 (e7c49b6) (Oracle Corporation 1.8.0_66 / Linux 3.16.0-4-amd64) on aaee301aa809 , but I'm really just running the graylog2/allinone:latest docker image.

**Comment by mikkolehtisalo** [comment]
Just checking. Is /opt/graylog/conf/nginx/ca/srv.key ordinary PEM? It should probably be in PKCS#8 format. 

```
openssl pkcs8 -nocrypt -topk8 -in /opt/graylog/conf/nginx/ca/srv.key -out /opt/graylog/conf/nginx/ca/srv.pk8
```

**Comment by kroepke** [comment]
Please reopen this issue if the workaround by @mikkolehtisalo does not solve your problem.

Thanks!

**Comment by ptman** [comment]
I'm not sure what has changed. At least the graylog2/allinone docker image isn't the same anymore. But now it works. I used certs generated by easyrsa3. I think that I did that the last time also.
