### ISSUE TITLE
java.lang.ClassCastException: class com.mongodb.BasicDBObject cannot be cast to class

### ISSUE THREAD

**Issue by juliohm1978** [Graylog2/graylog2-server#16912]
## Current Behavior
We are unable to login into one particular Graylog instance we have running. The login screen hangs forever after providing username and password.

In the browser developer tools, we noticed this API call failing with an error 500.

https://GRAYLOG_SERVER/api/users/admin

![image](https://github.com/Graylog2/graylog2-server/assets/4145456/b1656cb7-540a-4af4-b39f-f9ccdf2a1290)

An exception message appears in that API call, wrapped into a json response.

```
{"type":"ApiError","message":"class com.mongodb.BasicDBObject cannot be cast to class [B (com.mongodb.BasicDBObject is in unnamed module of loader 'app'; [B is in module java.base of loader 'bootstrap')"}
```

In the Graylog server container, we see the following error message:

```
2023-10-12 14:10:22,148 ERROR   [ExecutorServiceSessionValidationScheduler] - Error while validating the session - {}
java.lang.ClassCastException: class com.mongodb.BasicDBObject cannot be cast to class [B (com.mongodb.BasicDBObject is in unnamed module of loader 'app'; [B is in module java.base of loader 'bootstrap')
        at org.graylog2.security.MongoDbSession.getAttributes(MongoDbSession.java:71) ~[graylog.jar:?]
        at org.graylog2.security.MongoDBSessionServiceImpl.daoToSimpleSession(MongoDBSessionServiceImpl.java:88) ~[graylog.jar:?]
        at org.graylog2.security.MongoDbSessionDAO.getActiveSessions(MongoDbSessionDAO.java:157) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.DefaultSessionManager.getActiveSessions(DefaultSessionManager.java:244) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.validateSessions(AbstractValidatingSessionManager.java:280) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.ExecutorServiceSessionValidationScheduler.run(ExecutorServiceSessionValidationScheduler.java:120) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

## Steps to Reproduce (for bugs)
I am only able to reproduce this in one of our specific environments. All other Graylog instances are working fine, with pretty much the exact version of Graylog and very similar environments.

## Your Environment

* Graylog Version: graylog/graylog:5.1.7 (container image)
* OpenSearch Version: elasticsearch:7.10.2
* MongoDB Version: mongodb:6.0.3-debian-11-r0
* Operating System: Kubernetes 1.27, Ubuntu 22.04 worker nodes

**Comment by kroepke** [comment]
Which JVM version are you running? The error seems to indicate a problem with module visibility.

**Comment by juliohm1978** [comment]
> Which JVM version are you running? The error seems to indicate a problem with module visibility.

Here it is:
```
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode, sharing)
```
That is the java version packaged with the container image.

**Comment by thll** [comment]
This could be due to a corrupted session in MongoDB.

You can check by running the following query in the MongoDB shell:

```
db.sessions.findOne({"attributes" : {"$not" : {"$type" : "binData"}}})?.attributes
```

This shouldn't return any result because the field is supposed to contain binary data. If you get a result, it would be great if you could share it here, **but only if it does not contain any sensitive information**.

To fix the issue, after creating a backup of your MongoDB, you can try to remove the culprits by running the following query in the mongo shell: 

```
db.sessions.deleteMany({"attributes" : {"$not" : {"$type" : "binData"}}})
```
