### ISSUE TITLE
Nonezero exit value 128

### ISSUE THREAD

**Issue by superkhong** [Graylog2/graylog2-server#1692]
Hi,
I have just built graylog web interface 1.3.2
when I go to localhost:9000,I got this error.Please give me an advice

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 1 Scala source to /home/ubuntu/web-interface/graylog2-web-interface-1.3/target/scala-2.10/classes...
fatal: Not a git repository (or any of the parent directories): .git
java.lang.RuntimeException: Nonzero exit value: 128
    at scala.sys.package$.error(package.scala:27)
    at sbt.AbstractProcessBuilder.getString(ProcessImpl.scala:134)
    at sbt.AbstractProcessBuilder.$bang$bang(ProcessImpl.scala:136)
    at ApplicationBuild$$anonfun$10.apply(Build.scala:54)
    at ApplicationBuild$$anonfun$10.apply(Build.scala:52)
    at sbt.Scoped$RichInitialize$$anonfun$map$1$$anonfun$apply$3.apply(Structure.scala:192)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error] (compile:managedResources) Nonzero exit value: 128
[error] application - 

! @6omi1a71c - Internal server error, for (GET) [/] ->

play.PlayExceptions$UnexpectedException: Unexpected exception[RuntimeException: Nonzero exit value: 128]
    at play.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:51) ~[na:na]
    at play.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
    at play.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
    at play.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
Caused by: java.lang.RuntimeException: Nonzero exit value: 128
    at scala.sys.package$.error(package.scala:27) ~[scala-library.jar:na]
    at sbt.AbstractProcessBuilder.getString(ProcessImpl.scala:134) ~[na:na]
    at sbt.AbstractProcessBuilder.$bang$bang(ProcessImpl.scala:136) ~[na:na]
    at ApplicationBuild$$anonfun$10.apply(Build.scala:54) ~[na:na]
    at ApplicationBuild$$anonfun$10.apply(Build.scala:52) ~[na:na]
[warn] play - No application found at invoker init

**Comment by joschi** [comment]
I'm sorry, but we're not going to debug your development environment.

Feel free to write to [our mailing list](https://groups.google.com/forum/#!forum/graylog2) for further discussion.

**Comment by superkhong** [comment]
I posted this error here,please give me an advice
https://groups.google.com/forum/#!topic/graylog2/8zGeFRIOn5Y
