### ISSUE TITLE
Logstash to GELF Input (UDP) unexpected results

### ISSUE THREAD

**Issue by bane0** [Graylog2/graylog2-server#1694]
Hello,

I´m using logstash to parse a file and send the output to graylog´s gelf input.
The logstash is parsing the file correctly (debug enabled) , graylog communicates with ES without problems (it is able to create the index) and I can see in the Graylog web interface that the input is receiving messages BUT all the messages are going directly to the Journal, so no information in ES besides the created index with 0 messages.Timezones are OK.

How can I debug this problem further ? Graylog/ES/logstash do not show any errors.

Thank you!

**Comment by victoryxs** [comment]
have you update your journal dir ? you can use 12900 interface to see some metrics to local you problem.
some metrics param: 
           1.num store in es: org.graylog2.outputs.ElasticSearchOutput.writes
           2.kafkaJournal read from input: org.graylog2.shared.journal.KafkaJournal.messagesRead
           3.kafkaJournal write to local dir: org.graylog2.shared.journal.KafkaJournal.messagesWritten
           4.read thread from kafka: org.graylog2.shared.journal.JournalReader.readMessages

**Comment by victoryxs** [comment]
ps: if you update your journel dir, you delete all data in that dir, the problem can solve.

**Comment by bane0** [comment]
Thank you guys, but no luck so far.
I´ve stopped the server, deleted the journal and tried to index from scratch...the problem persists.
I can see the input receiving messages (web interface) but no documents are created in ES.
I´ve been reviewing metric through the API browser but there is any information that can help to undertand what is going on. All the components seem to be fine,but no events in the indexes:

Events : {"events":0}
Indexer failures : {"count":0}
Shards :  {"status":"green","shards":{"active":2,"initializing":0,"relocating":0,"unassigned":0}}

Will keep digging ;)

**Comment by joschi** [comment]
@bane0 Any error messages in the logs of your Elasticsearch node(s)?

**Comment by bane0** [comment]
nothing :( actually , I see how Gralog joins the ES cluster, creates an index ... and after that nothinh happens (even if I see my Input in graylog UI receiving messages).

**Comment by joschi** [comment]
@bane0 Please post your Elasticsearch and Graylog log files.

Additionally, please post the output of the following cURL command (replace "localhost" with the actual hostname or IP address of one of your Elasticsearch nodes):
```
# curl -X GET 'http://localhost:9200/_cat/indices?v'
```

**Comment by bane0** [comment]
Of course:

The graylog indexes are always that size, no new documents added (all sent to the journal):

health status index                  pri rep docs.count docs.deleted store.size pri.store.size
yellow open   .kibana                  1   1         15            0     38.3kb         38.3kb
green  open   syslog_logs   1   0   12929793            0     10.4gb         10.4gb
green  open   graylog_2                1   0          0            0       115b           115b
green  open   graylog_1                1   0          0            0       115b           115b

Thanks for your time!

**Comment by joschi** [comment]
Please don't cut off the log files but post them completely and unaltered.

**Comment by bane0** [comment]
ok, I will do that and post the full logs here.  I didn´t see this message before :  "Unexpected end of ZLIB input stream" which suggest that graylog is unable to decompress the journal messages.

Thanks !

**Comment by bane0** [comment]
I did the same test from scratch, all works fine until I start to send mesasges to the input (trough logstash). 
The error (graylog-server.log) is this :

2016-01-15T13:57:48.440+01:00 ERROR [DecodingProcessor] Unable to decode raw message 941a0360-bb87-11e5-b7b7-406186cbef43 (journal offset 251) encoded as gelf received from unknown source.
2016-01-15T13:57:48.441+01:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=941a0360-bb87-11e5-b7b7-406186cbef43, journalOffset=251, codec=gelf, payloadSize=1024, timestamp=2016-01-15T13:57:48.438+01:00}
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.graylog2.plugin.Tools.decompressZlib(Tools.java:196)
	at org.graylog2.inputs.codecs.gelf.GELFMessage.getJSON(GELFMessage.java:55)
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:110)
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136)
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82)
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58)
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-01-15T13:57:48.844+01:00 ERROR [DecodingProcessor] Unable to decode raw message 9457cfb0-bb87-11e5-b7b7-406186cbef43 (journal offset 360) encoded as gelf received from unknown source.
2016-01-15T13:57:48.845+01:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=9457cfb0-bb87-11e5-b7b7-406186cbef43, journalOffset=360, codec=gelf, payloadSize=1024, timestamp=2016-01-15T13:57:48.843+01:00}
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.graylog2.plugin.Tools.decompressZlib(Tools.java:196)
	at org.graylog2.inputs.codecs.gelf.GELFMessage.getJSON(GELFMessage.java:55)
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:110)
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136)
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82)
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58)
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

The logstash configuration is (really simple, a csv with 4 columns) : 

input {
file {
path => "log.csv"
type => "csvlog"
start_position => "beginning"
}
}

filter {
csv {
        columns => ["Date","IP","Country Code","Domain"]
        separator => ","
    }
date {
		match => ["Date", "YYYY-MM-dd HH:mm:ss"]
		target => "Date"
	}
geoip{
 source => "IP"
database => "/opt/GeoLiteCity.dat"
}
}

output {
 gelf {
 host => "127.0.0.1"
 sender => "csvtest"
 }

**Comment by victoryxs** [comment]
Unexpected end of ZLIB input stream,  the data your send to graylog is not zip format, your data's first two bytes is  (byte) 0x78, (byte) 0x9c, but the end of data is zlib format
![image](https://cloud.githubusercontent.com/assets/13211501/12354422/d2611a66-bbd0-11e5-92d9-73b4cb825c1f.png)

![image](https://cloud.githubusercontent.com/assets/13211501/12354444/ed0c1352-bbd0-11e5-8a75-1bfe1f1b88d6.png)


ormat.

**Comment by bane0** [comment]
But shouldn´t this be handled by graylog ? 
I mean , Logstash is sending the data from a CSV source , so raw text...
Isn´t the ZLIB refering to the messages that graylog is trying to extract from the  journal (that shoudn´t happen as we´ve no througput probems, overload,etc..) ?
How can I modify this behaviour ?

Thank you very much for your help.

**Comment by victoryxs** [comment]
when i use Flume to send udp to graylog, i must always write an special sink to send, i remember tcp need to add ‘\0’ at the end, and udp must gzip or zip the message or add chunk header to graylog, the data will be encode and store in es!

**Comment by bane0** [comment]
Thank you very much victoryxs ! I´ll try to figure out how to do that via logstash (I think logstash gelf module only supports UDP). I know this is not the place to discuss this, but can you provide any tricks to "gzip or zip the message or add chunk header" via logstash ? thx++

**Comment by victoryxs** [comment]
you can implement a output of logstash by yourself, inside the output when you send message to graylog2, you compress the messsage. But i think that if you use logstash, you can use grok itself and put the message into es, and display by graylog2, because the graylog2 only do the filter, extract and alter, if you don't need these, you can try this.

**Comment by bane0** [comment]
this is super! I´m going to do some tests and I´ll let you know ;) thx !

**Comment by kroepke** [comment]
Graylog cannot read logstash's indices, you have to send it to Graylog to be able to use our UI.
