### ISSUE TITLE
Data Node: Second Graylog node fails in preflight mode

### ISSUE THREAD

**Issue by thll** [Graylog2/graylog2-server#16976]
## Expected Behavior

For an initial setup with two Graylog nodes, both nodes should reliably enter preflight mode.

## Current Behavior

One Graylog node enters preflight mode, the other node fails with an error. After restarting the node, it successfully entered preflight mode. I tried this a couple of times but could only reproduce the error two times:
<details>
<summary>stacktrace</summary>
<pre>
datanode-graylog-2-1  | 2023-10-18 07:58:45,089 ERROR: org.graylog2.bootstrap.CmdLineTool - Startup error:
datanode-graylog-2-1  | java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {STARTING=[PeriodicalsService [RUNNING]], FAILED=[PreflightJerseyService [FAILED]]}
datanode-graylog-2-1  | 	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:770) ~[graylog.jar:?]
datanode-graylog-2-1  | 	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:582) ~[graylog.jar:?]
datanode-graylog-2-1  | 	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:296) ~[graylog.jar:?]
datanode-graylog-2-1  | 	at org.graylog2.bootstrap.ServerBootstrap.doRunWithPreflightInjector(ServerBootstrap.java:213) ~[graylog.jar:?]
datanode-graylog-2-1  | 	at org.graylog2.bootstrap.ServerBootstrap.runPreflightWeb(ServerBootstrap.java:183) ~[graylog.jar:?]
datanode-graylog-2-1  | 	at org.graylog2.bootstrap.ServerBootstrap.runPreFlightChecks(ServerBootstrap.java:164) ~[graylog.jar:?]
datanode-graylog-2-1  | 	at org.graylog2.bootstrap.ServerBootstrap.beforeInjectorCreation(ServerBootstrap.java:148) ~[graylog.jar:?]
datanode-graylog-2-1  | 	at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:308) ~[graylog.jar:?]
datanode-graylog-2-1  | 	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:260) [graylog.jar:?]
datanode-graylog-2-1  | 	at org.graylog2.bootstrap.Main.main(Main.java:55) [graylog.jar:?]
datanode-graylog-2-1  | 	Suppressed: com.google.common.util.concurrent.ServiceManager$FailedService: PreflightJerseyService [FAILED]
datanode-graylog-2-1  | 	Caused by: java.lang.IllegalStateException: Initial password should be automatically present in the DB, this is an inconsistent state. Please report the problem to Graylog.
datanode-graylog-2-1  | 		at org.graylog2.bootstrap.preflight.PreflightConfigServiceImpl.lambda$getPreflightPassword$2(PreflightConfigServiceImpl.java:67) ~[graylog.jar:?]
datanode-graylog-2-1  | 		at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
datanode-graylog-2-1  | 		at org.graylog2.bootstrap.preflight.PreflightConfigServiceImpl.getPreflightPassword(PreflightConfigServiceImpl.java:67) ~[graylog.jar:?]
datanode-graylog-2-1  | 		at org.graylog2.bootstrap.preflight.PreflightJerseyService.createBasicAuthFilter(PreflightJerseyService.java:203) ~[graylog.jar:?]
datanode-graylog-2-1  | 		at org.graylog2.bootstrap.preflight.PreflightJerseyService.buildResourceConfig(PreflightJerseyService.java:197) ~[graylog.jar:?]
datanode-graylog-2-1  | 		at org.graylog2.bootstrap.preflight.PreflightJerseyService.setUp(PreflightJerseyService.java:223) ~[graylog.jar:?]
datanode-graylog-2-1  | 		at org.graylog2.bootstrap.preflight.PreflightJerseyService.startUpApi(PreflightJerseyService.java:126) ~[graylog.jar:?]
datanode-graylog-2-1  | 		at org.graylog2.bootstrap.preflight.PreflightJerseyService.startUp(PreflightJerseyService.java:96) ~[graylog.jar:?]
datanode-graylog-2-1  | 		at com.google.common.util.concurrent.AbstractIdleService$DelegateService.lambda$doStart$0(AbstractIdleService.java:64) ~[graylog.jar:?]
datanode-graylog-2-1  | 		at com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:105) ~[graylog.jar:?]
datanode-graylog-2-1  | 		at java.lang.Thread.run(Unknown Source) ~[?:?]
</pre>
</details>

## Steps to Reproduce (for bugs)

1. Using docker-compose, set up a cluster with two Graylog nodes and two Data Nodes. Please note that both nodes have `GRAYLOG_LEADER_ELECTION_MODE: automatic` configured. This might be important.
2. Start the cluster with docker compose
3. Notice that the second node dies with above error. (If you are lucky)

## Your Environment

* Graylog Version: 5.2.0-beta.3
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by thll** [comment]
I noticed that I have a stray
```
GRAYLOG_IS_LEADER: false
```
in the config for the second node. That is reliably triggering the issue.
It's a misconfiguration but it shouldn't negatively affect leader election in that way. It's probably an issue with leader election and not with the data node.
