### ISSUE TITLE
Trying to change the "message" field mapping fails with exception

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#16979]
```
2023-10-18 10:53:47,467 INFO : org.graylog2.indexer.MongoIndexSet - Creating target index <graylog_0>.
2023-10-18 10:53:47,469 WARN : org.graylog2.indexer.indices.Indices - Couldn't create index graylog_0. Error: Multiple entries with same key: message={type=text} and message={type=text, analyzer=standard, fielddata=false}
java.lang.IllegalArgumentException: Multiple entries with same key: message={type=text} and message={type=text, analyzer=standard, fielddata=false}
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:378) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:372) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:246) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:133) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:572) ~[guava-32.1.2-jre.jar:?]
```

## Possible Solution
Merge same fields into one?

## Steps to Reproduce (for bugs)
1. Try to change mapping of any of predefined fields `message`, `ful_message`, `timestamp`, `gl2_accounted_message_size`, `gl2_receive_timestamp`, `gl2_processing_timestamp`, `gl2_message_id`, `source` or `streams`, all of them defined in the IndexMapping class.

## Your Environment

* Graylog Version: 5.2 beta

**Comment by todvora** [comment]
The change of mappings fails for all predefined types configured here, because these mappings potentially lead to duplicity in the builder: 

![image](https://github.com/Graylog2/graylog2-server/assets/4102775/60f34afb-9f34-44a0-ba3f-c1a140ab4ed9)
