### ISSUE TITLE
ChunkedRequestAssembler Error & ApiClient TimeoutException

### ISSUE THREAD

**Issue by SamuelBucheliZ** [Graylog2/graylog2-server#1702]
We are running graylog-web and graylog-server, both version 1.3.2. Looking at the graylog-server logs, we see that we have lots of entries of the following kind (non-relevant, application-specific log entries removed), note that the source and destination IP are the same:
```
2016-01-19T10:38:57.347+01:00 ERROR [ChunkedRequestAssembler] Chunks for channel [id: 0x8a6a88f2, /{IpRedacted}:56013 => /{IpRedacted}:12900] couldn't be found, skipping chunk.
...
2016-01-19T10:40:07.347+01:00 ERROR [ChunkedRequestAssembler] Chunks for channel [id: 0x9882c373, /{IpRedacted}:56263 => /{IpRedacted}:12900] couldn't be found, skipping chunk.
...
2016-01-19T10:43:12.638+01:00 ERROR [Messages] Failed to index [1] messages. Please check the index error log in your web interface for the reason. Error: failure in bulk execution:
[7]: index [graylog2_1], type [message], id [0e59f520-be91-11e5-8493-001a4a777b5d], message [IllegalArgumentException[Document contains at least one immense term in field="logMessage" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[109, 101, 115, 115, 97, 103, 101, 82, 101, 99, 101, 105, 118, 101, 100, 40, 116, 105, 109, 101, 100, 97, 116, 101, 61, 84, 117, 101, 32, 74]...', original message: bytes can be at most 32766 in length; got 36260]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 36260]; ]
...
2016-01-19T10:43:27.347+01:00 WARN  [ChunkedRequestAssembler] Error while assembling HTTP request chunks
java.lang.NullPointerException
        at org.graylog2.jersey.container.netty.ChunkedRequestAssembler.assemble(ChunkedRequestAssembler.java:40)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:278)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Looking at a dump of the traffic from port 56013 on port 12900 on this machine, we see the following packets (data payload removed for packets with correct checksum, but are available, if necessary). The (redacted) hostname resolves to the IP address from above:
```
10:38:57.347014 IP (tos 0x0, ttl 64, id 1814, offset 0, flags [DF], proto TCP (6), length 60)
    {HostnameRedacted}.56013 > {HostnameRedacted}.12900: Flags [S], cksum 0x3408 (correct), seq 2428074639, win 65495, options [mss 65495,sackOK,TS val 1134067097 ecr 0,nop,wscale 7], length 0

10:38:57.347029 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    {HostnameRedacted}.12900 > {HostnameRedacted}.56013: Flags [S.], cksum 0x46b3 (correct), seq 700056164, ack 2428074640, win 65483, options [mss 65495,sackOK,TS val 1134067097 ecr 1134067097,nop,wscale 7], length 0

10:38:57.347037 IP (tos 0x0, ttl 64, id 1815, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.56013 > {HostnameRedacted}.12900: Flags [.], cksum 0x6d6f (correct), seq 1, ack 1, win 512, options [nop,nop,TS val 1134067097 ecr 1134067097], length 0

10:38:57.347226 IP (tos 0x0, ttl 64, id 1816, offset 0, flags [DF], proto TCP (6), length 8989)
    {HostnameRedacted}.56013 > {HostnameRedacted}.12900: Flags [P.], cksum 0x635f (incorrect -> 0x8db1), seq 1:8938, ack 1, win 512, options [nop,nop,TS val 1134067097 ecr 1134067097], length 8937
	0x0000:  0000 0304 0006 0000 0000 0000 0000 0800  ................
	0x0010:  4500 231d 0718 4000 4006 d073 ac11 7416  E.#...@.@..s..t.
	0x0020:  ac11 7416 dacd 3264 90b9 7a90 29ba 0265  ..t...2d..z.)..e
	0x0030:  8018 0200 635f 0000 0101 080a 4398 7d99  ....c_......C.}.
	0x0040:  4398 7d99 504f 5354 202f 7379 7374 656d  C.}.POST./system
	0x0050:  2f6d 6574 7269 6373 2f6d 756c 7469 706c  /metrics/multipl
	0x0060:  6520 4854 5450 2f31 2e30 0d0a 436f 6e74  e.HTTP/1.0..Cont
	0x0070:  656e 742d 5479 7065 3a20 6170 706c 6963  ent-Type:.applic
	0x0080:  6174 696f 6e2f 6a73 6f6e 3b20 6368 6172  ation/json;.char
	0x0090:  7365 743d 7574 662d 380d 0a41 6363 6570  set=utf-8..Accep
	0x00a0:  743a 2061 7070 6c69 6361 7469 6f6e 2f6a  t:.application/j
	0x00b0:  736f 6e0d 0a41 6363 6570 743a 2061 7070  son..Accept:.app
	0x00c0:  6c69 6361 7469 6f6e 2f6a 736f 6e3b 2063  lication/json;.c
	0x00d0:  6861 7273 6574 3d75 7466 2d38 0d0a 4163  harset=utf-8..Ac
	0x00e0:  6365 7074 2d43 6861 7273 6574 3a20 7574  cept-Charset:.ut
	0x00f0:  662d 380d 0a58 2d47 7261 796c 6f67 322d  f-8..X-Graylog2-
	0x0100:  4e6f 2d53 6573 7369 6f6e 2d45 7874 656e  No-Session-Exten
	0x0110:  7369 6f6e 3a20 7472 7565 0d0a 436f 6e74  sion:.true..Cont
	0x0120:  656e 742d 4c65 6e67 7468 3a20 3835 3233  ent-Length:.8523
	{...hostname, basic authorization, and request body with metrics list in JSON format redacted}

10:38:57.347255 IP (tos 0x0, ttl 64, id 32764, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.12900 > {HostnameRedacted}.56013: Flags [.], cksum 0x48bd (correct), seq 1, ack 8938, win 969, options [nop,nop,TS val 1134067097 ecr 1134067097], length 0

10:38:57.347389 IP (tos 0x0, ttl 64, id 32765, offset 0, flags [DF], proto TCP (6), length 77)
    {HostnameRedacted}.12900 > {HostnameRedacted}.56013: Flags [P.], cksum 0x408f (incorrect -> 0x1289), seq 1:26, ack 8938, win 969, options [nop,nop,TS val 1134067097 ecr 1134067097], length 25
	0x0000:  0000 0304 0006 0000 0000 0000 0000 0800  ................
	0x0010:  4500 004d 7ffd 4000 4006 7a5e ac11 7416  E..M..@.@.z^..t.
	0x0020:  ac11 7416 3264 dacd 29ba 0265 90b9 9d79  ..t.2d..)..e...y
	0x0030:  8018 03c9 408f 0000 0101 080a 4398 7d99  ....@.......C.}.
	0x0040:  4398 7d99 4854 5450 2f31 2e31 2031 3030  C.}.HTTP/1.1.100
	0x0050:  2043 6f6e 7469 6e75 650d 0a0d 0a         .Continue....

10:38:57.347396 IP (tos 0x0, ttl 64, id 1817, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.56013 > {HostnameRedacted}.12900: Flags [.], cksum 0x4a6d (correct), seq 8938, ack 26, win 512, options [nop,nop,TS val 1134067097 ecr 1134067097], length 0

10:38:57.347407 IP (tos 0x0, ttl 64, id 32766, offset 0, flags [DF], proto TCP (6), length 77)
    {HostnameRedacted}.12900 > {HostnameRedacted}.56013: Flags [P.], cksum 0x408f (incorrect -> 0x1270), seq 26:51, ack 8938, win 969, options [nop,nop,TS val 1134067097 ecr 1134067097], length 25
	0x0000:  0000 0304 0006 0000 0000 0000 0000 0800  ................
	0x0010:  4500 004d 7ffe 4000 4006 7a5d ac11 7416  E..M..@.@.z]..t.
	0x0020:  ac11 7416 3264 dacd 29ba 027e 90b9 9d79  ..t.2d..)..~...y
	0x0030:  8018 03c9 408f 0000 0101 080a 4398 7d99  ....@.......C.}.
	0x0040:  4398 7d99 4854 5450 2f31 2e31 2031 3030  C.}.HTTP/1.1.100
	0x0050:  2043 6f6e 7469 6e75 650d 0a0d 0a         .Continue....

10:38:57.347411 IP (tos 0x0, ttl 64, id 1818, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.56013 > {HostnameRedacted}.12900: Flags [.], cksum 0x4a54 (correct), seq 8938, ack 51, win 512, options [nop,nop,TS val 1134067097 ecr 1134067097], length 0

10:38:57.347431 IP (tos 0x0, ttl 64, id 32767, offset 0, flags [DF], proto TCP (6), length 77)
    {HostnameRedacted}.12900 > {HostnameRedacted}.56013: Flags [P.], cksum 0x408f (incorrect -> 0x1257), seq 51:76, ack 8938, win 969, options [nop,nop,TS val 1134067097 ecr 1134067097], length 25
	0x0000:  0000 0304 0006 0000 0000 0000 0000 0800  ................
	0x0010:  4500 004d 7fff 4000 4006 7a5c ac11 7416  E..M..@.@.z\..t.
	0x0020:  ac11 7416 3264 dacd 29ba 0297 90b9 9d79  ..t.2d..)......y
	0x0030:  8018 03c9 408f 0000 0101 080a 4398 7d99  ....@.......C.}.
	0x0040:  4398 7d99 4854 5450 2f31 2e31 2031 3030  C.}.HTTP/1.1.100
	0x0050:  2043 6f6e 7469 6e75 650d 0a0d 0a         .Continue....

10:38:57.347435 IP (tos 0x0, ttl 64, id 1819, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.56013 > {HostnameRedacted}.12900: Flags [.], cksum 0x4a3b (correct), seq 8938, ack 76, win 512, options [nop,nop,TS val 1134067097 ecr 1134067097], length 0

10:38:57.349037 IP (tos 0x0, ttl 64, id 32768, offset 0, flags [DF], proto TCP (6), length 77)
    {HostnameRedacted}.12900 > {HostnameRedacted}.56013: Flags [P.], cksum 0x408f (incorrect -> 0x1205), seq 76:101, ack 8938, win 1024, options [nop,nop,TS val 1134067099 ecr 1134067097], length 25
	0x0000:  0000 0304 0006 0000 0000 0000 0000 0800  ................
	0x0010:  4500 004d 8000 4000 4006 7a5b ac11 7416  E..M..@.@.z[..t.
	0x0020:  ac11 7416 3264 dacd 29ba 02b0 90b9 9d79  ..t.2d..)......y
	0x0030:  8018 0400 408f 0000 0101 080a 4398 7d9b  ....@.......C.}.
	0x0040:  4398 7d99 4854 5450 2f31 2e31 2031 3030  C.}.HTTP/1.1.100
	0x0050:  2043 6f6e 7469 6e75 650d 0a0d 0a         .Continue....

10:38:57.349052 IP (tos 0x0, ttl 64, id 1820, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.56013 > {HostnameRedacted}.12900: Flags [.], cksum 0x4a1e (correct), seq 8938, ack 101, win 512, options [nop,nop,TS val 1134067099 ecr 1134067099], length 0

10:38:57.349062 IP (tos 0x0, ttl 64, id 32769, offset 0, flags [DF], proto TCP (6), length 77)
    {HostnameRedacted}.12900 > {HostnameRedacted}.56013: Flags [P.], cksum 0x408f (incorrect -> 0x11ea), seq 101:126, ack 8938, win 1024, options [nop,nop,TS val 1134067099 ecr 1134067099], length 25
	0x0000:  0000 0304 0006 0000 0000 0000 0000 0800  ................
	0x0010:  4500 004d 8001 4000 4006 7a5a ac11 7416  E..M..@.@.zZ..t.
	0x0020:  ac11 7416 3264 dacd 29ba 02c9 90b9 9d79  ..t.2d..)......y
	0x0030:  8018 0400 408f 0000 0101 080a 4398 7d9b  ....@.......C.}.
	0x0040:  4398 7d9b 4854 5450 2f31 2e31 2031 3030  C.}.HTTP/1.1.100
	0x0050:  2043 6f6e 7469 6e75 650d 0a0d 0a         .Continue....

10:38:57.349066 IP (tos 0x0, ttl 64, id 1821, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.56013 > {HostnameRedacted}.12900: Flags [.], cksum 0x4a05 (correct), seq 8938, ack 126, win 512, options [nop,nop,TS val 1134067099 ecr 1134067099], length 0

10:38:57.349455 IP (tos 0x0, ttl 64, id 32770, offset 0, flags [DF], proto TCP (6), length 234)
    {HostnameRedacted}.12900 > {HostnameRedacted}.56013: Flags [P.], cksum 0x412c (incorrect -> 0x5df9), seq 126:308, ack 8938, win 1024, options [nop,nop,TS val 1134067099 ecr 1134067099], length 182
	0x0000:  0000 0304 0006 0000 0000 0000 0000 0800  ................
	0x0010:  4500 00ea 8002 4000 4006 79bc ac11 7416  E.....@.@.y...t.
	0x0020:  ac11 7416 3264 dacd 29ba 02e2 90b9 9d79  ..t.2d..)......y
	0x0030:  8018 0400 412c 0000 0101 080a 4398 7d9b  ....A,......C.}.
	0x0040:  4398 7d9b 4854 5450 2f31 2e30 2034 3031  C.}.HTTP/1.0.401
	0x0050:  2055 6e61 7574 686f 7269 7a65 640d 0a43  .Unauthorized..C
	0x0060:  6f6e 7465 6e74 2d4c 656e 6774 683a 2030  ontent-Length:.0
	0x0070:  0d0a 5757 572d 4175 7468 656e 7469 6361  ..WWW-Authentica
	0x0080:  7465 3a20 4261 7369 6320 7265 616c 6d3d  te:.Basic.realm=
	0x0090:  2247 7261 796c 6f67 2053 6572 7665 7222  "Graylog.Server"
	0x00a0:  0d0a 582d 4772 6179 6c6f 672d 4e6f 6465  ..X-Graylog-Node
	0x00b0:  2d49 443a 2035 3737 3132 3139 382d 3532  -ID:.57712198-52
	0x00c0:  6664 2d34 6561 642d 3931 3565 2d38 3934  fd-4ead-915e-894
	0x00d0:  3433 3739 6238 3938 360d 0a58 2d52 756e  4379b8986..X-Run
	0x00e0:  7469 6d65 2d4d 6963 726f 7365 636f 6e64  time-Microsecond
	0x00f0:  733a 2031 3833 0d0a 0d0a                 s:.183....

10:38:57.349461 IP (tos 0x0, ttl 64, id 1822, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.56013 > {HostnameRedacted}.12900: Flags [.], cksum 0x4946 (correct), seq 8938, ack 308, win 521, options [nop,nop,TS val 1134067099 ecr 1134067099], length 0

10:38:57.349478 IP (tos 0x0, ttl 64, id 32771, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.12900 > {HostnameRedacted}.56013: Flags [F.], cksum 0x474e (correct), seq 308, ack 8938, win 1024, options [nop,nop,TS val 1134067099 ecr 1134067099], length 0

10:38:57.349515 IP (tos 0x0, ttl 64, id 1823, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.56013 > {HostnameRedacted}.12900: Flags [F.], cksum 0x4944 (correct), seq 8938, ack 309, win 521, options [nop,nop,TS val 1134067099 ecr 1134067099], length 0

10:38:57.349523 IP (tos 0x0, ttl 64, id 32772, offset 0, flags [DF], proto TCP (6), length 52)
    {HostnameRedacted}.12900 > {HostnameRedacted}.56013: Flags [.], cksum 0x474d (correct), seq 309, ack 8939, win 1024, options [nop,nop,TS val 1134067099 ecr 1134067099], length 0
```

So, it seems that the cause of these problems is graylog-web. Looking at the logs of graylog-web, we see:
```
2016-01-19T10:38:52.347+01:00 - [ERROR] - from org.graylog2.restclient.lib.ApiClient in pool-673-thread-1
API call timed out
java.util.concurrent.TimeoutException: null
        at com.ning.http.client.providers.netty.future.NettyResponseFuture.get(NettyResponseFuture.java:159) ~[com.ning.async-http-client-1.9.31.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.executeOnAll(ApiClientImpl.java:608) ~[org.graylog2.graylog2-rest-client--1.3.2-1.3.2.jar:na]
        at controllers.api.MetricsController$PollingJob.run(MetricsController.java:117) [graylog-web-interface.graylog-web-interface-1.3.2.jar:1.3.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_05]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_05]

2016-01-19T10:39:02.347+01:00 - [ERROR] - from org.graylog2.restclient.lib.ApiClient in pool-673-thread-1
API call timed out
java.util.concurrent.TimeoutException: null
        at com.ning.http.client.providers.netty.future.NettyResponseFuture.get(NettyResponseFuture.java:159) ~[com.ning.async-http-client-1.9.31.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.executeOnAll(ApiClientImpl.java:608) ~[org.graylog2.graylog2-rest-client--1.3.2-1.3.2.jar:na]
        at controllers.api.MetricsController$PollingJob.run(MetricsController.java:117) [graylog-web-interface.graylog-web-interface-1.3.2.jar:1.3.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_05]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_05]

2016-01-19T10:39:22.347+01:00 - [ERROR] - from org.graylog2.restclient.lib.ApiClient in pool-673-thread-1
API call timed out
java.util.concurrent.TimeoutException: null
        at com.ning.http.client.providers.netty.future.NettyResponseFuture.get(NettyResponseFuture.java:159) ~[com.ning.async-http-client-1.9.31.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.executeOnAll(ApiClientImpl.java:608) ~[org.graylog2.graylog2-rest-client--1.3.2-1.3.2.jar:na]
        at controllers.api.MetricsController$PollingJob.run(MetricsController.java:117) [graylog-web-interface.graylog-web-interface-1.3.2.jar:1.3.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_05]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_05]

2016-01-19T10:39:32.348+01:00 - [ERROR] - from org.graylog2.restclient.lib.ApiClient in pool-673-thread-1
API call timed out
java.util.concurrent.TimeoutException: null
        at com.ning.http.client.providers.netty.future.NettyResponseFuture.get(NettyResponseFuture.java:159) ~[com.ning.async-http-client-1.9.31.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.executeOnAll(ApiClientImpl.java:608) ~[org.graylog2.graylog2-rest-client--1.3.2-1.3.2.jar:na]
        at controllers.api.MetricsController$PollingJob.run(MetricsController.java:117) [graylog-web-interface.graylog-web-interface-1.3.2.jar:1.3.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_05]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_05]
```
It seems that this issue has already previously occurred for other people, see https://groups.google.com/forum/#!topic/graylog2/73dhI8mPzwQ and https://github.com/Graylog2/graylog2-server/issues/1259

Is there some configuration error on our side or is this a bug in the communication between graylog-web and graylog-server?

**Comment by SamuelBucheliZ** [comment]
Update:
Note that ```Content-Length``` in the request above is 8523. Looking at the graylog server configuration, we have 
```
# The maximum size of a single HTTP chunk in bytes.
rest_max_chunk_size = 8192

# The maximum size of the HTTP request headers in bytes.
rest_max_header_size = 8192

# The maximal length of the initial HTTP/1.1 line in bytes.
rest_max_initial_line_length = 4096
```
It seems to me that the graylog web api has issues with chunked requests?

**Comment by joschi** [comment]
@SamuelBucheliZ Could you please test if increasing those settings in your Graylog server configuration will fix your issue?

We're currently in the process of phasing out the old web interface for Graylog 2.0.0 and most likely won't release another version of Graylog 1.x (except for really critical bugs).

**Comment by SamuelBucheliZ** [comment]
@joschi Thanks for the info. I just did some experiments and it seems that there's a problem with the AsyncHttpClient. Using a pom similar to
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>graylog2-rest-client-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
                <groupId>org.graylog2</groupId>
                <artifactId>graylog2-rest-client</artifactId>
                <version>1.3.3</version>
            </dependency>
    </dependencies>
</project>
```
and this code
```
import com.ning.http.client.AsyncHttpClient;
import com.ning.http.client.Response;

import java.io.IOException;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;


public class Application2 {
    public static void main(String[] args) throws ExecutionException, InterruptedException, IOException {
        AsyncHttpClient asyncHttpClient = new AsyncHttpClient();
        Future<Response> f =
                asyncHttpClient
                        .preparePost("http://url.to.graylog:12900/system/metrics/multiple")
                        .addHeader("Authorization", "Basic PutBasicAuthHere")
                        .addHeader("Content-Type", "application/json; charset=utf-8")
                        .addHeader("Accept", "application/json; charset=utf-8")
                        .setBody(Messages.someLargeMessage)
                        .execute();

    }
}
```
where ```Messages.someLargeMessage``` exceeds the limit for chunking set in the config will lead to the ChunkedRequestAssembler problem as outlined above (not always, but about once in every ten times). Using a small message, this does not happen.

**Comment by SamuelBucheliZ** [comment]
@joschi Increasing ```rest_max_chunk_size``` to 16384 seems to have solved the problem for now.

**Comment by kroepke** [comment]
Since there is a workaround and the 1.3 web interface is no longer in active development, I'm closing this issue.
