### ISSUE TITLE
Graylog can`s start after upgrade - migrations failed

### ISSUE THREAD

**Issue by gregecslo** [Graylog2/graylog2-server#17045]
Hi.

Upgraded from 5.1.6 to latest beta3.

After server start:

```
2023-10-23T18:37:27.432+02:00 INFO  [ServerBootstrap] Arch: amd64
2023-10-23T18:37:27.536+02:00 INFO  [ServerBootstrap] Running 67 migrations...
2023-10-23T18:37:28.716+02:00 ERROR [ServerBootstrap] Exception while running migrations
java.lang.UnsupportedOperationException: Cannot convert to Seconds as this period contains months and months vary in length
        at org.joda.time.Period.checkYearsAndMonths(Period.java:1571) ~[graylog.jar:?]
        at org.joda.time.Period.toStandardSeconds(Period.java:1523) ~[graylog.jar:?]
        at org.graylog2.indexer.searches.timerangepresets.conversion.PeriodToRelativeRangeConverter.apply(PeriodToRelativeRangeConverter.java:30) ~[graylog.jar:?]
        at org.graylog2.indexer.searches.timerangepresets.conversion.PeriodToRelativeRangeConverter.apply(PeriodToRelativeRangeConverter.java:24) ~[graylog.jar:?]
        at org.graylog2.indexer.searches.timerangepresets.conversion.TimerangeOptionsToTimerangePresetsConversion.lambda$convert$0(TimerangeOptionsToTimerangePresetsConversion.java:46) ~[graylog.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
        at org.graylog2.indexer.searches.timerangepresets.conversion.TimerangeOptionsToTimerangePresetsConversion.convert(TimerangeOptionsToTimerangePresetsConversion.java:49) ~[graylog.jar:?]
        at org.graylog2.migrations.V202305221200_MigrateTimerangeOptionsToTimerangePresets.upgrade(V202305221200_MigrateTimerangeOptionsToTimerangePresets.java:67) ~[graylog.jar:?]
        at org.graylog2.bootstrap.ServerBootstrap.lambda$runMigrations$3(ServerBootstrap.java:390) ~[graylog.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$forEachRemaining$1(CollectSpliterators.java:72) ~[graylog.jar:?]
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:72) ~[graylog.jar:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at org.graylog2.bootstrap.ServerBootstrap.runMigrations(ServerBootstrap.java:387) ~[graylog.jar:?]
        at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:313) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:328) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:260) [graylog.jar:?]
        at org.graylog2.bootstrap.Main.main(Main.java:55) [graylog.jar:?]

```
Maybe has something to do with search ranges I manually added?
Can I delete them somehow and start the server?

Thanks!

**Comment by janheise** [comment]
@gregecslo Hi, thanks for filing a bug report. Can you wait until the fix is released in one of the next pre-releases? If not, we can find a way on how to remove the problematic ranges manually but that takes a bit more time to investigate.
