### ISSUE TITLE
EC2 autodiscovery is not working with graylog2-server

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#171]
Seems like trying to use ElasticSearch EC2 autodiscovery is not working with the graylog2-server elasticsearch.yml config file.

```
org.elasticsearch.discovery - [graylog2-server] waited for 30s and no initial state was set by the discovery
Exception in thread "main" org.elasticsearch.node.NodeClosedException: node closed null
    at org.elasticsearch.action.support.master.TransportMasterNodeOperationAction$3.onClose(TransportMasterNodeOperationAction.java:163)
    at org.elasticsearch.cluster.service.InternalClusterService.doStop(InternalClusterService.java:126)
    at     org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:105)
    at org.elasticsearch.node.internal.InternalNode.stop(InternalNode.java:254)
    at org.elasticsearch.node.internal.InternalNode.close(InternalNode.java:274)
    at     org.graylog2.indexer.EmbeddedElasticSearchClient$2.run(EmbeddedElasticSearchClient.java:94)
ESC[60G[ESC[0;31mFAILEDESC[0;39m]^MException in thread "main" org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class setting [discovery.type] with value [ec2]
    at org.elasticsearch.common.settings.ImmutableSettings.getAsClass(ImmutableSettings.java:243)
    at org.elasticsearch.discovery.DiscoveryModule.spawnModules(DiscoveryModule.java:50)
    at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
    at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:150)
    at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
    at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:166)
    at org.graylog2.indexer.EmbeddedElasticSearchClient.<init>(EmbeddedElasticSearchClient.java:88)
    at org.graylog2.Core.initialize(Core.java:172)
    at org.graylog2.Main.main(Main.java:144)
Caused by: java.lang.ClassNotFoundException: ec2
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at     org.elasticsearch.common.settings.ImmutableSettings.getAsClass(ImmutableSettings.java:227)
    ... 8 more
```

**Comment by chad-upton** [comment]
why was this issue closed, this was never fixed only a timeout added?
