### ISSUE TITLE
rsyslog Failed to bind my adress

### ISSUE THREAD

**Issue by Plaedark** [Graylog2/graylog2-server#1711]
When i configure input syslog udp or tcp i have this message:
```
2016-01-21T11:45:17.635+01:00 ERROR [InputLauncher] The [org.graylog2.inputs.syslog.tcp.SyslogTCPInput] input with ID <56a0b6bd82cec058f8f62d6d> misfired. Reason: Cannot assign requested address.
org.graylog2.plugin.inputs.MisfireException: org.graylog2.plugin.inputs.MisfireException: org.jboss.netty.channel.ChannelException: Failed to bind to: /XXX.XXX.XX.XX:5140
        at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:163)
        at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.graylog2.plugin.inputs.MisfireException: org.jboss.netty.channel.ChannelException: Failed to bind to: /XXX.XXX.XX.XX:5140
        at org.graylog2.plugin.inputs.transports.NettyTransport.launch(NettyTransport.java:161)
        at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:160)
        ... 7 more
Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /XXX.XXX.XX.XX:5140
        at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
        at org.graylog2.plugin.inputs.transports.NettyTransport.launch(NettyTransport.java:147)
        ... 8 more
Caused by: java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:463)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        ... 3 more
2016-01-21T11:45:17.637+01:00 INFO  [InputStateListener] Input [Syslog TCP/56a0b6bd82cec058f8f62d6d] is now STARTING
2016-01-21T11:45:17.637+01:00 INFO  [InputStateListener] Input [Syslog TCP/56a0b6bd82cec058f8f62d6d] is now FAILED
```
Escuse me for my English.

**Comment by joschi** [comment]
> ```
Failed to bind to: /XXX.XXX.XX.XX:5140
```

Either there's already another application listening on this network interface and port, the IP address you've given doesn't exist, or there's a security framework like SELinux, AppArmor or grsecurity preventing Java from binding to that port.

In any case, please move this discussion to [the mailing list](https://groups.google.com/forum/#!forum/graylog2) or to [#graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) as we try to use the GitHub issue tracker exclusively for bug reports and feature requests.
