### ISSUE TITLE
Event Aggregation fails when aggregating on missing fields

### ISSUE THREAD

**Issue by thll** [Graylog2/graylog2-server#17314]
## Expected Behavior

Missing values should be handled gracefully when being aggregated on in event definitions, just like they are handled for aggregations in searches/dashboards.

## Current Behavior

When an event aggregation contains fields in its group-by config that don't exist on the messages, the aggregation fails with the following stack trace:

```
2023-11-15 09:12:58,972 ERROR: org.graylog.events.processor.EventProcessorExecutionJob - Event processor <aggregation-v1/655489174c2ded509efe257d> failed to execute: Couldn't create events for: Test (possibly due to non-existing grouping fields) (retry in 5000 ms)
org.graylog.events.processor.EventProcessorException: Couldn't create events for: Test (possibly due to non-existing grouping fields)
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.eventsFromAggregationResult(AggregationEventProcessor.java:327) ~[graylog.jar:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.aggregatedSearch(AggregationEventProcessor.java:257) ~[graylog.jar:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:126) ~[graylog.jar:?]
	at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:91) ~[graylog.jar:?]
	at org.graylog.events.processor.EventProcessorExecutionJob.execute(EventProcessorExecutionJob.java:115) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:186) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$2(JobExecutionEngine.java:159) ~[graylog.jar:?]
	at com.codahale.metrics.Timer.time(Timer.java:151) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:159) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:128) ~[graylog.jar:?]
	at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:121) ~[graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77) ~[graylog.jar:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.eventsFromAggregationResult(AggregationEventProcessor.java:323) ~[graylog.jar:?]
	... 15 more
```

## Hint for finding the root cause

I noticed that when traversing the tree of buckets in the search result from opensearch, sometimes the order of buckets is different than what seems to be expected [here](https://github.com/Graylog2/graylog2-server/blob/37b4d85633a82ad24d0c16b86c6dd28c54492dbc/graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/buckets/OSValuesHandler.java#L116). This leads to the wrong branch of the tree being selected for further traversal. This leads to all the "columns" after the one containing empty values being missing from the result. That in turn causes the index out of bounds exception.

We should find out what causes the order of the buckets being different.

## Steps to Reproduce (for bugs)

1. Start a Random HTTP Input.
2. Create an event definition that, among others, aggregates on a field that doesn't exist on the messages, like `test` in the following example: 
![image](https://github.com/Graylog2/graylog2-server/assets/886541/a32e081c-1e03-4e25-b46f-f78d454eb844)
3. Notice above exception in the logs
4. Notice that when using the 'replay search' feature on the event definition, the aggregation renders just fine: 
![image](https://github.com/Graylog2/graylog2-server/assets/886541/2de26b08-95f4-4158-83b6-de491e4917bf)

## Context

[HS-2060524646]
[HS-2076124814]

This appears to be the same issue as #14375. However, the bug was not properly addressed, only the error message improved.

## Your Environment

* Graylog Version:
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by patrickmann** [comment]
Proxying the ES requests and responses, I notice that `Replay Search` generates compact buckets that contain all of the group-by field values (keys).
In this example, 2 fields have values (`index`, `GET`) and 2 are missing (`Empty Value`):

>                                     {
>                                         "doc_count": 30,
>                                         "key": "index⸱(Empty Value)⸱GET⸱(Empty Value)",
>                                         "value_count#8fba36a9-5047-4154-81e6-7924bf234f9e-series-count(action)": {
>                                             "value": 30
>                                         }
>                                     },

Whereas the event creation generates deeply nested bucket structures that require a lot of parsing to aggregate. And obviously that parsing sometimes goes wrong. I think that event creation should use the same style of query as `Replay Search`.

**Comment by frantz45** [comment]
I agree the initial fix is not satisfying and the root cause is still present.
I did some tests:

- Configure an Event Definition with 1 grouping field, trigger the Event Definition with this non existing grouping field: issue is not present
- Configure an Event Definition with 2 grouping fields, trigger the Event Definition with these non existing grouping fields: **issue is present**
- Configure an Event Definition with 2 grouping fields, trigger the Event Definition with only the first grouping field (the 2nd is absent): issue is not present
- Configure an Event Definition with 2 grouping fields, trigger the Event Definition with only the 2nd grouping field (the 1st is absent): **issue is present**

So it seems the issue happens only when you have multiple grouping fields and that the 1st grouping fields doesn't exist in the logs which trigger the Event Definition.

Moreover I agree with https://github.com/Graylog2/graylog2-server/issues/17714. Graylog should never enter an infinite loop when an Event Processor encounters an exception. We should be able to configure a maximum number of attemps (if someone want to keep the inifinite loop he could use the value -1).

**Comment by todvora** [comment]
The https://github.com/Graylog2/graylog2-server/pull/17604 is now merged and should fix all edge cases.
