### ISSUE TITLE
Pagination on Search Page is broken

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1759]
* Pagination on the top has a large margin
* Pagination layout at the bottom is broken

![nicxmbagqiviua8lbakm2cbagqiecaaaecbagqiecaaaecbagkasjd84aaaqiecfxbqhhoehagqiaaaqiecbagqiaaaqiecbague0cwsnqqraxeibagedoasldnmncqiaaaqiecbagqiaaaqiecbagqibagqsid8u4elpogaabaqmvidwcfwmtecbagaabagqiecbagaabagqiecbqoglcw9kphz4qiecaqakkca9lsci6riaaaqiecbag](https://cloud.githubusercontent.com/assets/461/12782720/5cb9de04-ca7d-11e5-9d60-4f915607dfe4.png)

**Comment by bernd** [comment]
Heh, and the histogram is not shown as well. :wink: Also expanding message details doesn't work but I guess that's because of the JS errors:

```
Unhandled rejection TypeError: t is not a function
    at r.e.Graph.Renderer.Line.e.Class.create.defaults (http://localhost:9000/vendor.js:490:10183)
    at r.e.Graph.Renderer.e.Class.create.configure (http://localhost:9000/vendor.js:490:9502)
    at r.e.Graph.Renderer.e.Class.create.initialize (http://localhost:9000/vendor.js:490:7795)
    at new r (http://localhost:9000/vendor.js:488:27932)
    at _loadRenderers (http://localhost:9000/vendor.js:488:31590)
    at initialize (http://localhost:9000/vendor.js:488:31040)
    at new e.Graph (http://localhost:9000/vendor.js:489:3653)
    at Object.drawResultGraph (webpack:///./src/legacy/result-histogram.js?:79:27)
    at componentDidMount (webpack:///./src/components/search/LegacyHistogram.jsx?:35:44)
    at r.a.notifyAll (http://localhost:9000/vendor.js:17:8044)
    at r.f.close (http://localhost:9000/vendor.js:409:14672)
    at r.i.closeAll (http://localhost:9000/vendor.js:14:6372)
    at r.i.perform (http://localhost:9000/vendor.js:14:5711)
    at i.perform (http://localhost:9000/vendor.js:14:5628)
    at i.m.perform (http://localhost:9000/vendor.js:12:23344)
    at Object.T (http://localhost:9000/vendor.js:12:23513)
```

**Comment by bernd** [comment]
This seems to happen with the artifact only, dev setup works.

**Comment by dennisoelkers** [comment]
Fixed for now. Including rickshaw in the vendor bundle causes this. Will investigate why and find different way to include more modules in the vendor bundle to save some space in the child chunks.
