### ISSUE TITLE
2.0-beta graylog-ctl reconfigure-as-datanode returns errors

### ISSUE THREAD

**Issue by kitkatneko** [Graylog2/graylog2-server#1769]
Have a 1 node with 2.0-beta as All-in-one node.
Both nodes, IP and DNS already set.

Configuring data-node like this:
```
sudo graylog-ctl set-admin-password xxxxxx
sudo graylog-ctl set-email-config torsmtp
sudo graylog-ctl set-timezone America/Toronto
sudo graylog-ctl set-cluster-master 172.27.xx.xx
sudo graylog-ctl reconfigure-as-datanode
```

but fails:
```
ubuntu@log2:~$ sudo graylog-ctl reconfigure-as-datanode
(eval):24:in `block (2 levels) in load_files': undefined method `[]=' for nil:NilClass (NoMethodError)
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `call'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `block in add_command'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:366:in `run'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/bin/omnibus-ctl:27:in `<top (required)>'
        from /opt/graylog/embedded/bin/omnibus-ctl:23:in `load'
        from /opt/graylog/embedded/bin/omnibus-ctl:23:in `<main>'
```

**Comment by mariussturm** [comment]
Thanks, this is fixed in the latest alpha!
