### ISSUE TITLE
Inputs page does not load

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#1798]
System -> Inputs does not load and I see this error in the browser JS console:

```
Unhandled rejection TypeError: Cannot read property 'requested_configuration' of undefined
    at render (webpack:///./src/components/inputs/InputListItem.jsx?:230:33)
    at M._renderValidatedComponentWithoutOwnerOrContext (http://localhost:9000/vendor.js:408:9437)
    at M._renderValidatedComponent (http://localhost:9000/vendor.js:408:9613)
    at i [as _renderValidatedComponent] (http://localhost:9000/vendor.js:12:21248)
    at M.mountComponent (http://localhost:9000/vendor.js:408:4589)
    at i [as mountComponent] (http://localhost:9000/vendor.js:12:21248)
    at Object.a.mountComponent (http://localhost:9000/vendor.js:13:5381)
    at M.g.Mixin.mountChildren (http://localhost:9000/vendor.js:409:11442)
    at M.Mixin._createContentMarkup (http://localhost:9000/vendor.js:408:21175)
    at M.Mixin.mountComponent (http://localhost:9000/vendor.js:408:20075)
    at Object.a.mountComponent (http://localhost:9000/vendor.js:13:5381)
    at M.mountComponent (http://localhost:9000/vendor.js:408:4685)
    at i [as mountComponent] (http://localhost:9000/vendor.js:12:21248)
    at Object.a.mountComponent (http://localhost:9000/vendor.js:13:5381)
    at M.g.Mixin.mountChildren (http://localhost:9000/vendor.js:409:11442)
    at M.Mixin._createContentMarkup (http://localhost:9000/vendor.js:408:21175)
```

Nothing relevant in `graylog-server` logs.

**Comment by dennisoelkers** [comment]
Are you missing a plugin for that input? Can you poste the content of your `inputs` collection in mongodb or the output of a `/system/inputs` call?
