### ISSUE TITLE
2.0 input start exception

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#1807]
```
2016-02-12 06:28:16,629 WARN : org.graylog2.rest.resources.cluster.ClusterInputStatesResource - Unable to fetch input states from node APCTLOGGL1:
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.InputStreamReader@2ee45228; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1624) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:378) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1494) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1119) ~[graylog.jar:?]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32) ~[graylog.jar:?]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23) ~[graylog.jar:?]
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:213) ~[graylog.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:177) ~[graylog.jar:?]
	at org.graylog2.rest.resources.cluster.ClusterInputStatesResource.lambda$get$0(ClusterInputStatesResource.java:92) ~[graylog.jar:?]
	at java.util.stream.Collectors.lambda$toMap$237(Collectors.java:1321) ~[?:1.8.0_71]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) [?:1.8.0_71]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683) [?:1.8.0_71]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_71]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_71]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747) [?:1.8.0_71]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721) [?:1.8.0_71]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316) [?:1.8.0_71]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_71]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_71]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) [?:1.8.0_71]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) [?:1.8.0_71]
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714) [?:1.8.0_71]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) [?:1.8.0_71]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) [?:1.8.0_71]
	at org.graylog2.rest.resources.cluster.ClusterInputStatesResource.get(ClusterInputStatesResource.java:87) [graylog.jar:?]
	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
```

**Comment by joschi** [comment]
Looks similar to #1771.

I'm hesitant to close it as a duplicate because different HTTP resources are affected, but in the end it might be a problem with Retrofit and how it queries the other Graylog nodes.

**Comment by runningman84** [comment]
One additional note, we are also running graylog behind a nginx proxy.

Our current graylog settings looks like
```
rest_transport_uri = http://10.0.3.140:80/api/
```
Our nginx settings looks like
```
location / { proxy_pass http://gl_web }
location /api { proxy_pass http://gl_api }
```
I think such setting would not work well in a multi node environment. Graylog nodes should internally speak with each other directly.

In our setup we have a bunch of graylog nodes in a separate network. They only access for users is via a nginx layer in front of these graylog servers.

**Comment by SjonHortensius** [comment]
@runningman84; just an FYI in case you missed it in my issue; you can workaround this by creating a temporary hostname (or let nginx proxy on an additional port) so you don't need `/api/` in your path and this 'll work fine.

**Comment by dennisoelkers** [comment]
Closing, as #1808 is a fix for the use case, so `rest_transport_uri` does not need to be changed, graylog nodes can contact each other directly and graylog instances can still be exported to the outside using a proxy.
