### ISSUE TITLE
Attempt to send test alert leads to server disconnection (crash)

### ISSUE THREAD

**Issue by zvonden** [Graylog2/graylog2-server#1810]
Graylog 1.3.3
Pressing Send Test Alert on the Alert page results in server disconnection (crash?). After reconnection Then I can see the problem sending mail (BrokenPipe error). Despite the broken pipe is maybe due to my mail server misbehaviour (thats questionable, as with Graylog 1.2.2 everything was fine), disconnection/crash should not occur.

**Comment by joschi** [comment]
@zvonden Please post the complete error message from the Graylog server logs.

**Comment by zvonden** [comment]
@joschi sorry for a silly question, but where are they? i could not manage to find

**Comment by joschi** [comment]
@zvonden That depends on how you've installed Graylog specifically, but best guess is `/var/log/graylog` (e. g. `/var/log/graylog/server/` in the official virtual appliances).

**Comment by zvonden** [comment]
2016-02-12_15:10:15.78036 ERROR [EmailAlarmCallback] Stream [56bd9870e4b0049b6e10fa8c: "Document acknowledgements"] has alert receivers and is triggered, but sending emails failed
2016-02-12_15:10:15.78039 org.apache.commons.mail.EmailException: Sending the email to the following server failed : srvex01.slb-bank.ch:587
2016-02-12_15:10:15.78040       at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
2016-02-12_15:10:15.78242       at org.apache.commons.mail.Email.send(Email.java:1448)
2016-02-12_15:10:15.78355       at org.graylog2.alerts.StaticEmailAlertSender.sendEmail(StaticEmailAlertSender.java:123)
2016-02-12_15:10:15.78409       at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:257)
2016-02-12_15:10:15.78474       at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:83)
2016-02-12_15:10:15.78540       at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:69)
2016-02-12_15:10:15.78604       at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:168)
2016-02-12_15:10:15.79031       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-02-12_15:10:15.79096       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-02-12_15:10:15.79201       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-02-12_15:10:15.79243       at java.lang.reflect.Method.invoke(Method.java:497)
2016-02-12_15:10:15.79296       at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
2016-02-12_15:10:15.79448       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
2016-02-12_15:10:15.79524       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
2016-02-12_15:10:15.79629       at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
2016-02-12_15:10:15.79702       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
2016-02-12_15:10:15.79901       at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
2016-02-12_15:10:15.80228       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
2016-02-12_15:10:15.80229       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
2016-02-12_15:10:15.80229       at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
2016-02-12_15:10:15.80229       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
2016-02-12_15:10:15.80230       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
2016-02-12_15:10:15.80252       at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
2016-02-12_15:10:15.80314       at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
2016-02-12_15:10:15.80378       at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
2016-02-12_15:10:15.80407       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
2016-02-12_15:10:15.80612       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
2016-02-12_15:10:15.80665       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
2016-02-12_15:10:15.80745       at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
2016-02-12_15:10:15.80816       at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
2016-02-12_15:10:15.80854       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
2016-02-12_15:10:15.80958       at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
2016-02-12_15:10:15.81059       at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
2016-02-12_15:10:15.81094       at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
2016-02-12_15:10:15.81156       at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
2016-02-12_15:10:15.81232       at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
2016-02-12_15:10:15.81316       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-02-12_15:10:15.81352       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-02-12_15:10:15.81412       at java.lang.Thread.run(Thread.java:745)
2016-02-12_15:10:15.81485 Caused by: javax.mail.MessagingException: Can't send command to SMTP host;
2016-02-12_15:10:15.81553   nested exception is:
2016-02-12_15:10:15.81629       java.net.SocketException: Broken pipe
2016-02-12_15:10:15.81727       at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2259)
2016-02-12_15:10:15.81759       at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2246)
2016-02-12_15:10:15.81801       at com.sun.mail.smtp.SMTPTransport.close(SMTPTransport.java:1287)
2016-02-12_15:10:15.82128       at javax.mail.Transport.send0(Transport.java:256)
2016-02-12_15:10:15.82222       at javax.mail.Transport.send(Transport.java:124)
2016-02-12_15:10:15.82258       at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
2016-02-12_15:10:15.82328       ... 38 more
2016-02-12_15:10:15.82824 Caused by: java.net.SocketException: Broken pipe
2016-02-12_15:10:15.82890       at java.net.SocketOutputStream.socketWrite0(Native Method)
2016-02-12_15:10:15.82955       at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
2016-02-12_15:10:15.83040       at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
2016-02-12_15:10:15.83112       at com.sun.mail.util.TraceOutputStream.write(TraceOutputStream.java:128)
2016-02-12_15:10:15.83158       at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
2016-02-12_15:10:15.83263       at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
2016-02-12_15:10:15.83360       at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2257)
2016-02-12_15:10:15.83388       ... 43 more
2016-02-12_15:55:18.72081 INFO  [AbstractValidatingSessionManager] Validating all active sessions...
2016-02-12_15:55:18.72560 INFO  [AbstractValidatingSessionManager] Validating all active sessions...
2016-02-12_15:55:18.73461 INFO  [AbstractValidatingSessionManager] Finished session validation.  No sessions were stopped.
2016-02-12_15:55:18.73646 INFO  [AbstractValidatingSessionManager] Finished session validation.  No sessions were stopped.

**Comment by zvonden** [comment]
And this is what I see after pressing the Send Test Alert:

Graylog Web Interface is disconnected.
The web interface could not connect to any of the Graylog nodes it has been connected to before.
Please check that the servers shown to the right are running and reachable.

**Comment by dennisoelkers** [comment]
@zvonden: Are you sure that your mail server is operating without errors?

There are actually two problems in this issue:

1) The web interface "disconnecting" when the server returns a 500. As we will probably not do any releases for 1.3, we cannot fix this. This is not happening anymore in 2.0 though.

2) "Broken pipe" when communicating with the mail server. This is either an issue with the underlying stack, the remote mail server, devices in between or the used mail library disconnecting because of protocol issues. Are you using SSL/TLS in your mail configuration/on your remote mail server? Are you able to check a packet dump of the SMTP connection to find out at which step it breaks? AFAIK we did not do any fundamental changes to the mail library between 1.2 and 1.3.

**Comment by dennisoelkers** [comment]
Closing this for now, as no further response was received in the last 17 days. Please reopen if this is still an issue/there is additional information.
