### ISSUE TITLE
Getting error 400 while trying to log in

### ISSUE THREAD

**Issue by YannickFricke** [Graylog2/graylog2-server#1829]
I'm using Squid + Windows 7
http://puu.sh/nb7dm/2881dc0167.png

Server details:
Debian 8 (64 Bit)
Installed through [repository](http://docs.graylog.org/en/1.3/pages/installation/operating_system_packages.html#debian-8) (today)

Error in /var/log/graylog-server/server.log
```
2016-02-17T10:59:22.712+01:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669)
        at java.util.zip.ZipFile.access$200(ZipFile.java:60)
        at java.util.zip.ZipFile$ZipEntryIterator.hasNext(ZipFile.java:493)
        at java.util.zip.ZipFile$ZipEntryIterator.hasMoreElements(ZipFile.java:488)
        at java.util.jar.JarFile$JarEntryIterator.hasNext(JarFile.java:253)
        at java.util.jar.JarFile$JarEntryIterator.hasMoreElements(JarFile.java:262)
        at org.reflections.vfs.ZipDir$1$1.computeNext(ZipDir.java:30)
        at org.reflections.vfs.ZipDir$1$1.computeNext(ZipDir.java:26)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at org.reflections.Reflections.scan(Reflections.java:240)
        at org.reflections.Reflections.scan(Reflections.java:204)
        at org.reflections.Reflections.<init>(Reflections.java:129)
        at org.reflections.Reflections.<init>(Reflections.java:170)
        at org.graylog2.shared.rest.documentation.generator.Generator.<init>(Generator.java:89)
        at org.graylog2.shared.rest.resources.documentation.DocumentationResource.overview(DocumentationResource.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

If you need any other information feel free to mention me :)

**Comment by joschi** [comment]
@YannickFricke The exception looks like the JAR file containing the Graylog Java class files has been corrupted. Please verify that the files from the DEB package are still valid, e. g. using [debsums](https://packages.debian.org/jessie/debsums).

Does everything work without Squid as reverse proxy in front of Graylog?

**Comment by YannickFricke** [comment]
@joschi thank you for your help :)
Und du bist Deutscher :D

Wo kann ich das Paket finden wenn es von apt / aptitude installiert worden ist?
Jup auf andere Seiten kann ich problemlos zugreifen

**Comment by joschi** [comment]
@YannickFricke Sorry, but let's keep it in English so that other people have it easier to follow. :wink:

Typically, APT stores the downloaded packages in `/var/cache/apt/archives` if you didn't run `apt-get clean` or `apt-get autoclean` afterwards. But using `debsums` you shouldn't need the original package at all.

Did you install any 3rd party plugins or have any other JAR files on the classpath of Graylog which might be corrupted?

**Comment by YannickFricke** [comment]
@joschi nope didnt installed anything else than [JDK 8](http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html)  and graylog

**Comment by YannickFricke** [comment]
@joschi any news? it doesn't seem to be any error on my side

**Comment by dennisoelkers** [comment]
@YannickFricke: Please make sure that the checksums match. It seems to be related to a corrupt jar file in your installation, as no other user is reporting this issue. To fix this, you could try cleaning your APT cache, redownload the package and reinstall it.
