### ISSUE TITLE
Can't set email sending in stream - java.lang.NullPointerException

### ISSUE THREAD

**Issue by Anim-IT** [Graylog2/graylog2-server#1840]
### Problem description
Hi
I'm trying to configure stream in graylog. I've set my email hostname, email port, no authentication but when I'm trying to send test alert nothing comes to my email client and in graylog server log I found this info:
```
2016-02-19T10:00:08.208+01:00 ERROR [EmailAlarmCallback] Stream [56bb4d16d5de17584b6f9959: "Błedy replikacji AD"] has alert receivers and is triggered, but sending emails failed
java.lang.NullPointerException
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:678)
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:638)
        at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:111)
        at org.apache.commons.mail.Email.createInternetAddress(Email.java:1895)
        at org.apache.commons.mail.Email.setFrom(Email.java:749)
        at org.apache.commons.mail.Email.setFrom(Email.java:732)
        at org.apache.commons.mail.Email.setFrom(Email.java:712)
        at org.graylog2.alerts.StaticEmailAlertSender.sendEmail(StaticEmailAlertSender.java:117)
        at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:257)
        at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:83)
        at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:69)
        at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:171)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

### Steps to reproduce the problem

1. Strem -> manage alerts 
2. Setting email address for receiver
3. Pressing sned test alert
4. Info about succesully sending email appeared
5. Nothing come, errors in graylos log

### Environment

* Graylog Version:  1.3.3-1
* Elasticsearch Version: 1.7.4-1
* MongoDB Version:2.6.11-1.el7
* Operating System: CentOS Linux release 7.2.1511

**Comment by joschi** [comment]
Please make sure that [`transport_email_from_email`](https://github.com/Graylog2/graylog2-server/blob/1.3.3/misc/graylog2.conf#L354) contains a valid email address in your Graylog server configuration file.

**Comment by Anim-IT** [comment]
Hmmm
Working,  simple as that :)
Yes it was a solution for that :)
Thanks
