### ISSUE TITLE
Data node process hangs when missing permissions to OS data folder

### ISSUE THREAD

**Issue by luk-kaminski** [Graylog2/graylog2-server#18715]
## Expected Behavior
Data node process does not hang, but exits cleanly.

## Current Behavior
Data node prints exceptions:
```
2024-03-20 14:10:33,753 INFO : org.graylog.datanode.initializers.JerseyService - Starting Data node REST API
2024-03-20 14:10:33,753 ERROR: org.graylog.datanode.management.OpensearchProcessService - Could not start up data node
org.graylog.datanode.bootstrap.preflight.DatanodeLockFileException: Failed to open channel to lock file /var/lib/opensearch/datanode.lock
	at org.graylog.datanode.bootstrap.preflight.DatanodeDirectoriesLockfileCheck.checkDatanodeLock(DatanodeDirectoriesLockfileCheck.java:71) ~[classes/:?]
	at org.graylog.datanode.management.OpensearchProcessService.startUp(OpensearchProcessService.java:151) ~[classes/:?]
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService.lambda$doStart$0(AbstractIdleService.java:64) ~[guava-33.1.0-jre.jar:?]
	at com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:105) ~[guava-33.1.0-jre.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.nio.file.AccessDeniedException: /var/lib/opensearch/datanode.lock
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181) ~[?:?]
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298) ~[?:?]
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357) ~[?:?]
	at org.graylog.datanode.bootstrap.preflight.DatanodeDirectoriesLockfileCheck.checkDatanodeLock(DatanodeDirectoriesLockfileCheck.java:68) ~[classes/:?]
```

and its process continues running.

When you want to stop it, it hangs (at least if run from IDEA) after logging "Graceful shutdown initiated" and "Goodbye".
You have to kill java process manually to recover.

## Possible Solution

Probably this method should be reimplemented in OpensearchProcessService:
```
    @Override
    protected void startUp() {
        final OpensearchConfiguration config = configurationProvider.get();
        configure();
        if (config.securityConfigured()) {

            try {
                lockfileCheck.checkDatanodeLock(config.datanodeDirectories().getDataTargetDir());
                this.process.start();
            } catch (Exception e) {
                LOG.error("Could not start up data node", e);
            }

        }
    }
```

## Context
When performing Data Node Migration in-place, you are supposed to use a data folder of existing Opensearch.
It is very likely you will miss permissions to access this folder and its files.

## Documentation impact
Maybe we should advise a proper way to start a data node (as opensearch user?) or a way to change permissions to data folder, so that future users do not have to discover this problem themselves?

## Your Environment
* Graylog Version: 6.0
* OpenSearch Version: 2.12
* Operating System: Linux

**Comment by janheise** [comment]
It was ruled out, that we ourselves change the folder permissions via the DataNode. This is a task the user has to manually.
