### ISSUE TITLE
Data Node Docker image with `s3_client_default_access_key` enabled doesn't start

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#18737]
## Expected Behavior

The Data Node Docker image should start when `s3_client_default_access_key` is defined.

## Current Behavior

The Data Node startup fails with the following error. The S3 repository plugin installation tries to write to read-only areas.

There will be a similar issue with the operating system packages.

```
data-node-1  | 2024-03-21T17:34:58.108Z ERROR [ServerBootstrap] Graylog DataNode startup failed. Exiting. Exception was:
data-node-1  | java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {FAILED=[OpensearchProcessService [FAILED]]}
data-node-1  | 	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:772) ~[guava-33.1.0-jre.jar:?]
data-node-1  | 	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:584) ~[guava-33.1.0-jre.jar:?]
data-node-1  | 	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:298) ~[guava-33.1.0-jre.jar:?]
data-node-1  | 	at org.graylog.datanode.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:222) [graylog-datanode.jar:?]
data-node-1  | 	at org.graylog.datanode.bootstrap.CmdLineTool.doRun(CmdLineTool.java:307) [graylog-datanode.jar:?]
data-node-1  | 	at org.graylog.datanode.bootstrap.CmdLineTool.run(CmdLineTool.java:246) [graylog-datanode.jar:?]
data-node-1  | 	at org.graylog.datanode.bootstrap.Main.main(Main.java:57) [graylog-datanode.jar:?]
data-node-1  | 	Suppressed: com.google.common.util.concurrent.ServiceManager$FailedService: OpensearchProcessService [FAILED]
data-node-1  | 	Caused by: java.lang.RuntimeException: Failed to execute opensearch cli/usr/share/graylog-datanode/dist/opensearch-2.12.0-linux-x64/bin/opensearch-plugin
data-node-1  | STDOUT/STDERR: -> Installing file:///usr/share/graylog-datanode/dist/plugins/repository-s3-2.12.0.zip
data-node-1  | -> Downloading file:///usr/share/graylog-datanode/dist/plugins/repository-s3-2.12.0.zip
data-node-1  | -> Failed installing file:///usr/share/graylog-datanode/dist/plugins/repository-s3-2.12.0.zip
data-node-1  | -> Rolling back file:///usr/share/graylog-datanode/dist/plugins/repository-s3-2.12.0.zip
data-node-1  | -> Rolled back file:///usr/share/graylog-datanode/dist/plugins/repository-s3-2.12.0.zip
data-node-1  | Exception in thread "main" java.nio.file.AccessDeniedException: /usr/share/graylog-datanode/dist/opensearch-2.12.0-linux-x64/plugins/.installing-11525244821489467132
data-node-1  | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
data-node-1  | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
data-node-1  | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
data-node-1  | 	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
data-node-1  | 	at java.base/java.nio.file.Files.createDirectory(Files.java:699)
data-node-1  | 	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:134)
data-node-1  | 	at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:171)
data-node-1  | 	at java.base/java.nio.file.Files.createTempDirectory(Files.java:976)
data-node-1  | 	at org.opensearch.plugins.InstallPluginCommand.stagingDirectory(InstallPluginCommand.java:768)
data-node-1  | 	at org.opensearch.plugins.InstallPluginCommand.unzip(InstallPluginCommand.java:716)
data-node-1  | 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:274)
data-node-1  | 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:250)
data-node-1  | 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
data-node-1  | 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
data-node-1  | 	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
data-node-1  | 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
data-node-1  | 	at org.opensearch.cli.Command.main(Command.java:101)
data-node-1  | 	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
data-node-1  | 
data-node-1  | 		at org.graylog.datanode.management.opensearch.cli.AbstractOpensearchCli.runWithStdin(AbstractOpensearchCli.java:104) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.opensearch.cli.AbstractOpensearchCli.runBatch(AbstractOpensearchCli.java:67) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.opensearch.cli.OpensearchPluginCli.installFromZip(OpensearchPluginCli.java:64) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.OpensearchCommandLineProcess.installPlugin(OpensearchCommandLineProcess.java:126) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.OpensearchCommandLineProcess.configureS3RepositoryPlugin(OpensearchCommandLineProcess.java:103) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.OpensearchCommandLineProcess.<init>(OpensearchCommandLineProcess.java:93) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.OpensearchProcessImpl.lambda$configure$1(OpensearchProcessImpl.java:186) ~[graylog-datanode.jar:?]
data-node-1  | 		at java.base/java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
data-node-1  | 		at org.graylog.datanode.management.OpensearchProcessImpl.configure(OpensearchProcessImpl.java:180) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.OpensearchProcessImpl.configure(OpensearchProcessImpl.java:176) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.OpensearchProcessImpl.configure(OpensearchProcessImpl.java:57) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.OpensearchProcessService.configure(OpensearchProcessService.java:188) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.OpensearchProcessService.configure(OpensearchProcessService.java:161) ~[graylog-datanode.jar:?]
data-node-1  | 		at org.graylog.datanode.management.OpensearchProcessService.startUp(OpensearchProcessService.java:147) ~[graylog-datanode.jar:?]
data-node-1  | 		at com.google.common.util.concurrent.AbstractIdleService$DelegateService.lambda$doStart$0(AbstractIdleService.java:64) ~[guava-33.1.0-jre.jar:?]
data-node-1  | 		at com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:105) ~[guava-33.1.0-jre.jar:?]
data-node-1  | 		at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

## Steps to Reproduce (for bugs)

1. Enable the S3 snapshot repository configuration for Data Node
    - `GRAYLOG_DATANODE_S3_CLIENT_DEFAULT_ACCESS_KEY`
    - `GRAYLOG_DATANODE_S3_CLIENT_DEFAULT_SECRET_KEY`
    - `GRAYLOG_DATANODE_S3_CLIENT_DEFAULT_ENDPOINT`
    - Additionally I had to set `GRAYLOG_DATANODE_OPENSEARCH_PLUGINS_LOCATION=/usr/share/graylog-datanode/dist/plugins` so Data Node can find the plugin.
      - https://github.com/Graylog2/graylog-docker/pull/273
      - https://github.com/Graylog2/fpm-recipes/pull/134
2. Start the Data Node container
3. Check the logs

## Your Environment

* Graylog Version: 6.0.0-beta.3
* Data Node Version: 6.0.0-beta.3

**Comment by janheise** [comment]
needs checking, might actually be solved with beta3

**Comment by janheise** [comment]
thx @bernd for re-testing. bug is fixed in beta3
