### ISSUE TITLE
Authorization/Shares api is unusable: invalid hexadecimal representation of an ObjectId: [admin]

### ISSUE THREAD

**Issue by juliohm1978** [Graylog2/graylog2-server#18899]
## Error description

We are unable to view user shares due to an error that comes up in the Authorization/Shares api.

```
java.lang.IllegalArgumentException: invalid hexadecimal representation of an ObjectId: [admin]
	at org.bson.types.ObjectId.parseHexString(ObjectId.java:419) ~[graylog.jar:?]
	at org.bson.types.ObjectId.<init>(ObjectId.java:205) ~[graylog.jar:?]
	at org.graylog2.database.PersistedServiceImpl.get(PersistedServiceImpl.java:62) ~[graylog.jar:?]
	at org.graylog2.users.UserServiceImpl.loadById(UserServiceImpl.java:119) ~[graylog.jar:?]
	at org.graylog.grn.providers.UserGRNDescriptorProvider.get(UserGRNDescriptorProvider.java:37) ~[graylog.jar:?]
	at org.graylog.grn.GRNDescriptorService.getDescriptor(GRNDescriptorService.java:47) ~[graylog.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at org.graylog.grn.GRNDescriptorService.getDescriptors(GRNDescriptorService.java:57) ~[graylog.jar:?]
	at org.graylog.security.shares.GranteeSharesService.getOwners(GranteeSharesService.java:144) ~[graylog.jar:?]
	at org.graylog.security.shares.GranteeSharesService.lambda$getTargetOwners$8(GranteeSharesService.java:139) ~[graylog.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at org.graylog.security.shares.GranteeSharesService.getTargetOwners(GranteeSharesService.java:140) ~[graylog.jar:?]
	at org.graylog.security.shares.GranteeSharesService.getPaginatedSharesFor(GranteeSharesService.java:80) ~[graylog.jar:?]
	at org.graylog.security.rest.EntitySharesResource.get(EntitySharesResource.java:106) ~[graylog.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

The error pops up in the user GUI while trying to load user shares in the user details.

![2024-04-04_13-14-12](https://github.com/Graylog2/graylog2-server/assets/4145456/27c787ca-f75e-465d-b3a6-c58a8d7fdcf6)

Direct access to the endpoint reveals the error message

![image](https://github.com/Graylog2/graylog2-server/assets/4145456/5c3f2cdb-f38b-4182-8175-c0e1a9c11fa3)

## Your Environment

* Graylog Version: 5.15.0-101-generic
* Java Version: openjdk version "17.0.9" 2023-10-1

I wonder if this is somehow a case of corrupted mongodb, since other identical graylog instances we have running are working just fine. Anything I cand o to work around this?

Best regards to everyeone.

**Comment by patrickmann** [comment]
Did you happen to create a new user called "admin"?

**Comment by juliohm1978** [comment]
> @juliohm1978 Did you happen to create a new user called "admin"? What type of entities do you expect to be shared with this user? Knowing that would help narrow things down.

Not really. Oddly enough, I am unable to reproduce this. The error message went away by itself without any intervention on our part.

Will reopen if we see this again. Thank you so much for the support!
