### ISSUE TITLE
Still display pagination when reaching pagination limit in events overview.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#18930]
## Description

It is only possible to search trough the last 10000 events. When you show 100 events per page an you open page 101 you receive no result but the following page.

![image](https://github.com/Graylog2/graylog2-server/assets/46300478/e8da638a-24a7-4c0d-911b-626d6f0a6b4b)

Since we maintain the active page as URL query params `?page=101&pageSize=100` we should still display the pagination in this case to allow the user to easily open the previous page.

## Your Environment

* Graylog Version: 6.0.0 rc1

**Comment by linuspahl** [comment]
While having another look, I did not saw this problem when 
1. Opening the alerts overview
2. Opening page 101

Only when
1. Opening the alerts overview
2. Opening page 101
3. Reloading the page.

In this case the backend seems to return `total_events: 0` for the alerts search request.

**Comment by luk-kaminski** [comment]
The behaviour seems to have changed in the latest versions, we face a notification with error now.

<img width="1915" height="744" alt="Image" src="https://github.com/user-attachments/assets/de234c86-c3f6-442f-be4e-94fd2275d9c4" />

Checked on version  7.1.0.

**Comment by luk-kaminski** [comment]
Corresponding stacktrace:

```
2026-01-09 08:54:41,071 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
org.graylog.shaded.opensearch2.org.opensearch.OpenSearchException: Unable to perform search query
	at org.graylog.storage.opensearch2.OpenSearchClient.exceptionFrom(OpenSearchClient.java:213)
	at org.graylog.storage.opensearch2.OpenSearchClient.firstResponseFrom(OpenSearchClient.java:122)
	at org.graylog.storage.opensearch2.OpenSearchClient.search(OpenSearchClient.java:98)
	at org.graylog.storage.opensearch2.MoreSearchAdapterOS2.eventSearch(MoreSearchAdapterOS2.java:127)
	at org.graylog.events.search.MoreSearch.eventSearch(MoreSearch.java:104)
	at org.graylog.events.search.EventsSearchService.search(EventsSearchService.java:84)
	at org.graylog.plugins.securityapp.events.SecurityEventService.findPaginated(SecurityEventService.java:496)
	at org.graylog.plugins.securityapp.events.SecurityEventService.findPaginated(SecurityEventService.java:198)
	at org.graylog.plugins.securityapp.events.rest.SecurityEventResource.search(SecurityEventResource.java:71)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:470)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:394)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:274)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:374)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:259)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.graylog.shaded.opensearch2.org.opensearch.OpenSearchException$1: OpenSearch exception [type=search_phase_execution_exception, reason=all shards failed]
	at org.graylog.shaded.opensearch2.org.opensearch.OpenSearchException.innerFromXContent(OpenSearchException.java:562)
	at org.graylog.shaded.opensearch2.org.opensearch.OpenSearchException.failureFromXContent(OpenSearchException.java:669)
	at org.graylog.shaded.opensearch2.org.opensearch.action.search.MultiSearchResponse.itemFromXContent(MultiSearchResponse.java:239)
	at org.graylog.shaded.opensearch2.org.opensearch.action.search.MultiSearchResponse.lambda$static$1(MultiSearchResponse.java:77)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.AbstractObjectParser.lambda$declareObjectArray$13(AbstractObjectParser.java:316)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.AbstractObjectParser.lambda$declareFieldArray$22(AbstractObjectParser.java:365)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.AbstractObjectParser.parseArray(AbstractObjectParser.java:447)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.AbstractObjectParser.lambda$declareFieldArray$23(AbstractObjectParser.java:365)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.ObjectParser.lambda$declareField$9(ObjectParser.java:423)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.ObjectParser.parseValue(ObjectParser.java:591)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.ObjectParser.parseArray(ObjectParser.java:585)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.ObjectParser.parseSub(ObjectParser.java:620)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.ObjectParser.parse(ObjectParser.java:356)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:188)
	at org.graylog.shaded.opensearch2.org.opensearch.core.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:180)
	at org.graylog.shaded.opensearch2.org.opensearch.action.search.MultiSearchResponse.fromXContext(MultiSearchResponse.java:218)
	at org.graylog.shaded.opensearch2.org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2235)
	at org.graylog.shaded.opensearch2.org.opensearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$12(RestHighLevelClient.java:1852)
	at org.graylog.shaded.opensearch2.org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1935)
	at org.graylog.shaded.opensearch2.org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1884)
	at org.graylog.shaded.opensearch2.org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1852)
	at org.graylog.shaded.opensearch2.org.opensearch.client.RestHighLevelClient.msearch(RestHighLevelClient.java:1144)
	at org.graylog.storage.opensearch2.OpenSearchClient.lambda$search$0(OpenSearchClient.java:96)
	at org.graylog.storage.opensearch2.OpenSearchClient.execute(OpenSearchClient.java:150)
	at org.graylog.storage.opensearch2.OpenSearchClient.search(OpenSearchClient.java:96)
	... 31 more
	Suppressed: org.graylog.shaded.opensearch2.org.opensearch.OpenSearchException$1: OpenSearch exception [type=illegal_argument_exception, reason=Result window is too large, from + size must be less than or equal to: [10000] but was [10100]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]
		at org.graylog.shaded.opensearch2.org.opensearch.OpenSearchException.innerFromXContent(OpenSearchException.java:562)
		at org.graylog.shaded.opensearch2.org.opensearch.OpenSearchException.fromXContent(OpenSearchException.java:473)
		at org.graylog.shaded.opensearch2.org.opensearch.OpenSearchException.innerFromXContent(OpenSearchException.java:535)
```
