### ISSUE TITLE
Exception when trying to set up data node metrics data stream on fresh install

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#18995]
## Expected Behavior

Data node startup happens with no errors.

## Current Behavior

For a fresh install with three data nodes (configured through pre-flight UI), these errors show up in the logs:

```
datanode1-1  | 2024-04-11T08:31:51.588Z ERROR [OpensearchNodeHeartbeat] Uncaught exception in Periodical
datanode1-1  | org.graylog.shaded.opensearch2.org.opensearch.OpenSearchException: Unable to create ism policy
datanode1-1  | 	at org.graylog.storage.opensearch2.OpenSearchClient.exceptionFrom(OpenSearchClient.java:184) ~[graylog-storage-opensearch2-6.0.0-rc.2.jar:?]
datanode1-1  | 	at org.graylog.storage.opensearch2.OpenSearchClient.execute(OpenSearchClient.java:135) ~[graylog-storage-opensearch2-6.0.0-rc.2.jar:?]
datanode1-1  | 	at org.graylog.storage.opensearch2.ism.IsmApi.perform(IsmApi.java:89) ~[graylog-storage-opensearch2-6.0.0-rc.2.jar:?]
datanode1-1  | 	at org.graylog.storage.opensearch2.ism.IsmApi.createPolicy(IsmApi.java:61) ~[graylog-storage-opensearch2-6.0.0-rc.2.jar:?]
datanode1-1  | 	at org.graylog.storage.opensearch2.DataStreamAdapterOS2.applyIsmPolicy(DataStreamAdapterOS2.java:169) ~[graylog-storage-opensearch2-6.0.0-rc.2.jar:?]
datanode1-1  | 	at org.graylog2.indexer.datastream.DataStreamServiceImpl.createDataStream(DataStreamServiceImpl.java:66) ~[graylog2-server-6.0.0-rc.2.jar:?]
datanode1-1  | 	at org.graylog.datanode.metrics.ConfigureMetricsIndexSettings.lambda$transition$0(ConfigureMetricsIndexSettings.java:86) ~[graylog-datanode.jar:?]
datanode1-1  | 	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[?:?]
datanode1-1  | 	at org.graylog.datanode.metrics.ConfigureMetricsIndexSettings.transition(ConfigureMetricsIndexSettings.java:78) ~[graylog-datanode.jar:?]
datanode1-1  | 	at org.graylog.datanode.metrics.ConfigureMetricsIndexSettings.transition(ConfigureMetricsIndexSettings.java:52) ~[graylog-datanode.jar:?]
datanode1-1  | 	at org.graylog.datanode.management.StateMachineTracerAggregator.lambda$transition$1(StateMachineTracerAggregator.java:45) ~[graylog-datanode.jar:?]
datanode1-1  | 	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
datanode1-1  | 	at org.graylog.datanode.management.StateMachineTracerAggregator.transition(StateMachineTracerAggregator.java:45) ~[graylog-datanode.jar:?]
datanode1-1  | 	at org.graylog.datanode.management.StateMachineTracerAggregator.transition(StateMachineTracerAggregator.java:26) ~[graylog-datanode.jar:?]
datanode1-1  | 	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:227) ~[stateless4j-2.6.0.jar:?]
datanode1-1  | 	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:145) ~[stateless4j-2.6.0.jar:?]
datanode1-1  | 	at org.graylog.datanode.management.OpensearchProcessImpl.onEvent(OpensearchProcessImpl.java:148) ~[graylog-datanode.jar:?]
datanode1-1  | 	at org.graylog.datanode.periodicals.OpensearchNodeHeartbeat.onNodeResponse(OpensearchNodeHeartbeat.java:69) ~[graylog-datanode.jar:?]
datanode1-1  | 	at org.graylog.datanode.periodicals.OpensearchNodeHeartbeat.doRun(OpensearchNodeHeartbeat.java:60) ~[graylog-datanode.jar:?]
datanode1-1  | 	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:99) [graylog2-server-6.0.0-rc.2.jar:?]
datanode1-1  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
datanode1-1  | 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
datanode1-1  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
datanode1-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
datanode1-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
datanode1-1  | 	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
datanode1-1  | Caused by: org.graylog.shaded.opensearch2.org.opensearch.client.ResponseException: method [PUT], host [https://datanode1:9200], URI [/_plugins/_ism/policies/gl-datanode-metrics-ism?format=json], status line [HTTP/1.1 400 Bad Request]
datanode1-1  | {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [.opendistro-ism-config/5Ik-OkSeTJWMnS9NDavISg] already exists","index":".opendistro-ism-config","index_uuid":"5Ik-OkSeTJWMnS9NDavISg"}],"type":"resource_already_exists_exception","reason":"index [.opendistro-ism-config/5Ik-OkSeTJWMnS9NDavISg] already exists","index":".opendistro-ism-config","index_uuid":"5Ik-OkSeTJWMnS9NDavISg"},"status":400}
datanode1-1  | 	at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient.convertResponse(RestClient.java:376) ~[graylog-storage-opensearch2-6.0.0-rc.2.jar:?]
datanode1-1  | 	at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient.performRequest(RestClient.java:346) ~[graylog-storage-opensearch2-6.0.0-rc.2.jar:?]
datanode1-1  | 	at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient.performRequest(RestClient.java:321) ~[graylog-storage-opensearch2-6.0.0-rc.2.jar:?]
datanode1-1  | 	at org.graylog.storage.opensearch2.ism.IsmApi.lambda$perform$0(IsmApi.java:94) ~[graylog-storage-opensearch2-6.0.0-rc.2.jar:?]
datanode1-1  | 	at org.graylog.storage.opensearch2.OpenSearchClient.execute(OpenSearchClient.java:133) ~[graylog-storage-opensearch2-6.0.0-rc.2.jar:?]
datanode1-1  | 	... 24 more
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Duplicate of #18830.
