### ISSUE TITLE
Unable to configure https for graylog-web.

### ISSUE THREAD

**Issue by gosub3000** [Graylog2/graylog2-server#1931]
### Problem description
Following the instructions as [documented](http://docs.graylog.org/en/1.3/pages/installation/manual_setup.html#https) does not configure graylog-web for https.

### Steps to reproduce the problem

1. Create a java keystore in /etc/graylog/web/keystore.jks
```
keytool -genkey -keyalg RSA -alias selfsigned -keystore keystore.jks -storepass password -validity 360 -keysize 2048
```
2. Edit /etc/default/graylog-web to specify https...
```
GRAYLOG_WEB_HTTP_ADDRESS="0.0.0.0"
GRAYLOG_WEB_HTTP_PORT="disabled"
GRAYLOG_WEB_JAVA_OPTS="-Dhttps.port=9001"
GRAYLOG_WEB_JAVA_OPTS="$GRAYLOG_WEB_JAVA_OPTS -Dhttps.keyStore=\"/etc/graylog/web/keystore.jks\""
GRAYLOG_WEB_JAVA_OPTS="$GRAYLOG_WEB_JAVA_OPTS -Dhttps.keyStorePassword=\"password\""
GRAYLOG_WEB_JAVA_OPTS="$GRAYLOG_WEB_JAVA_OPTS -Djava.net.preferIPv4Stack=true"
```
3. Restart graylog-web service:
```
service graylog-web restart
```

4. ps shows settings applied...
```
graylog+ 20881     1 99 12:34 ?        00:00:03 java -Xms1024m -Xmx1024m -XX:MaxPermSize=256m -XX:ReservedCodeCacheSize=128m -Dconfig.file=/etc/graylog/web/web.conf -Dlogger.file=/etc/graylog/web/logback.xml -Dpidfile.path=/dev/null -Dhttp.address=0.0.0.0 -Dhttp.port=disabled -Dhttps.port=9001 -Dhttps.keyStore="/etc/graylog/web/keystore.jks" -Dhttps.keyStorePassword="password" -Djava.net.preferIPv4Stack=true -Duser.dir=/usr/share/graylog-web -cp ...
```
5. Connect with web browser to host at port 9001.
Http is allowed when connecting to http://<host>:9001.  No connection is created when using https://<host>:9001.

### Environment

* Graylog Version: 1.3.3-1
* Elasticsearch Version: 1.5.5
* MongoDB Version: 2.6.11
* Operating System: Ubuntu 14.04.4 LTS
* Browser version: Any, tested with Chromium 48.0.2564.116

**Comment by joschi** [comment]
@gosub3000 Make sure that the Graylog system user is allowed to access the provided key store and check the logs of the web interface for error messages.

Also please refer to https://www.playframework.com/documentation/2.3.x/ConfiguringHttps for details how to configure HTTPS in a Play application (like the Graylog 1.x web interface).

**Comment by gosub3000** [comment]
Thanks @joschi ,
Keystore is globally readable:
-rw-r--r-- 1 root root 2301 Mar 15 09:57 /etc/graylog/web/keystore.jks

Looking at logs shows:
2016-03-15T12:34:30.153Z - [ERROR] - from play in New I/O server boss #34
cannot load SSL context
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_95]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_95]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_95]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_95]
        at play.core.server.ServerSSLEngine$.createScalaSSLEngineProvider(ServerSSLEngine.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.ServerSSLEngine$.createSSLEngineProvider(ServerSSLEngine.scala:31) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.NettyServer$PlayPipelineFactory.liftedTree1$1(NettyServer.scala:118) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.NettyServer$PlayPipelineFactory.sslEngineProvider$lzycompute(NettyServer.scala:117) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.NettyServer$PlayPipelineFactory.sslEngineProvider(NettyServer.scala:116) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.NettyServer$PlayPipelineFactory.getPipeline(NettyServer.scala:92) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134) [io.netty.netty-3.10.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104) [io.netty.netty-3.10.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.10.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42) [io.netty.netty-3.10.4.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.10.4.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.10.4.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_95]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_95]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
Caused by: java.lang.Exception: Unable to find HTTPS keystore at "/usr/share/graylog-web/"/etc/graylog/web/keystore.jks""
        at play.core.server.DefaultSSLEngineProvider.createSSLContext(DefaultSSLEngineProvider.scala:49) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.DefaultSSLEngineProvider.<init>(DefaultSSLEngineProvider.scala:19) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        ... 19 common frames omitted

Looks like a path issue. I'll fiddle with the configs again to see if that helps.

**Comment by gosub3000** [comment]
Ok, found and fixed the config issue.  I had bad quoting around the keystore file path.

Seems to be working as expected now.

Thanks for the prompt response.

**Comment by dokam** [comment]
Hi @gosub3000 ....can you share what was this bad quoting? Because here I am still with the same problem.

**Comment by joschi** [comment]
@dokam Please continue this discussion to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
