### ISSUE TITLE
Execution exception[[Graylog2ServerUnavailableException: null]]

### ISSUE THREAD

**Issue by brandonegbert** [Graylog2/graylog2-server#1940]
### Problem description
Get an error trying to access some pages of the web UI.  In this case it was the Nodes page but it doesn't seem to be consistent.

```
Oops, an error occured
This exception has been logged with id 6pe6hleh9.
```
### Steps to reproduce the problem

1. Occurs intermittently navigating the web UI.

### Environment

* Graylog Version:  1.3.3-1
* Elasticsearch Version: 1.7.4
* MongoDB Version: v3.0.6
* Operating System: jessie/sid 1.3.0 Virtual Appliance
* Browser version: Chrome 49.0.2623.87 (64-bit)

Relevant log section:
```
2016-03-16_20:58:18.63667 ! @6pe6hleh9 - Internal server error, for (GET) [/system/nodes] ->
2016-03-16_20:58:18.63852
2016-03-16_20:58:18.64071 play.api.Application$$anon$1: Execution exception[[Graylog2ServerUnavailableException: null]]
2016-03-16_20:58:18.64161       at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2016-03-16_20:58:18.64294       at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2016-03-16_20:58:18.64450       at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
pply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
ylog-web-interface-1.3.3.jar:1.3.3]
2016-03-16_20:58:18.62630       at Routes$$anonfun$routes$1$$anonfun$applyOrElse$28$$anonfun$apply$532.apply(routes_rout
ing.scala:1862) [graylog-web-interface.graylog-web-interface-1.3.3.jar:na]
2016-03-16_20:58:18.62674 [ESC[31merrorESC[0m] play - Cannot invoke the action, eventually got an error: org.graylog2.re
stclient.lib.Graylog2ServerUnavailableException
2016-03-16_20:58:18.62899 [ESC[31merrorESC[0m] play - Cannot invoke the action, eventually got an error: org.graylog2.re
stclient.lib.Graylog2ServerUnavailableException
2016-03-16_20:58:18.63298 [ESC[31merrorESC[0m] application -
2016-03-16_20:58:18.63530
2016-03-16_20:58:18.63667 ! @6pe6hleh9 - Internal server error, for (GET) [/system/nodes] ->
2016-03-16_20:58:18.63852
2016-03-16_20:58:18.64071 play.api.Application$$anon$1: Execution exception[[Graylog2ServerUnavailableException: null]]
2016-03-16_20:58:18.64161       at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.pla
y_2.10-2.3.10.jar:2.3.10]
2016-03-16_20:58:18.64294       at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.pla
y_2.10-2.3.10.jar:2.3.10]
2016-03-16_20:58:18.64450       at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.a
pply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2016-03-16_20:58:18.64927       at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2016-03-16_20:58:18.65114       at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
2016-03-16_20:58:18.65184 Caused by: org.graylog2.restclient.lib.Graylog2ServerUnavailableException: null
2016-03-16_20:58:18.65705       at org.graylog2.restclient.lib.ServerNodes.all(ServerNodes.java:73) ~[org.graylog2.graylog2-rest-client--1.3.3-1.3.3.jar:na]
2016-03-16_20:58:18.65890       at org.graylog2.restclient.lib.ServerNodes.any(ServerNodes.java:105) ~[org.graylog2.graylog2-rest-client--1.3.3-1.3.3.jar:na]
2016-03-16_20:58:18.66062       at org.graylog2.restclient.lib.ServerNodes.any(ServerNodes.java:101) ~[org.graylog2.graylog2-rest-client--1.3.3-1.3.3.jar:na]
2016-03-16_20:58:18.66154       at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:416) ~[org.graylog2.graylog2-rest-client--1.3.3-1.3.3.jar:na]
2016-03-16_20:58:18.66361       at org.graylog2.restclient.models.NodeService.radios(NodeService.java:90) ~[org.graylog2.graylog2-rest-client--1.3.3-1.3.3.jar:na]
2016-03-16_20:58:18.66420 [ESC[31merrorESC[0m] application -
2016-03-16_20:58:18.66836
2016-03-16_20:58:18.66942 ! @6pe6hleh9 - Internal server error, for (GET) [/system/nodes] ->
2016-03-16_20:58:18.67063
2016-03-16_20:58:18.67520 play.api.Application$$anon$1: Execution exception[[Graylog2ServerUnavailableException: null]]
2016-03-16_20:58:18.67641       at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2016-03-16_20:58:18.67699       at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2016-03-16_20:58:18.69451       at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2016-03-16_20:58:18.69683       at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2016-03-16_20:58:18.69855       at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
2016-03-16_20:58:18.70152 Caused by: org.graylog2.restclient.lib.Graylog2ServerUnavailableException: null
2016-03-16_20:58:18.70306       at org.graylog2.restclient.lib.ServerNodes.all(ServerNodes.java:73) ~[org.graylog2.graylog2-rest-client--1.3.3-1.3.3.jar:na]
2016-03-16_20:58:18.70475       at org.graylog2.restclient.lib.ServerNodes.any(ServerNodes.java:105) ~[org.graylog2.graylog2-rest-client--1.3.3-1.3.3.jar:na]
2016-03-16_20:58:18.70615       at org.graylog2.restclient.lib.ServerNodes.any(ServerNodes.java:101) ~[org.graylog2.graylog2-rest-client--1.3.3-1.3.3.jar:na]
2016-03-16_20:58:18.70707       at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:416) ~[org.graylog2.graylog2-rest-client--1.3.3-1.3.3.jar:na]
2016-03-16_20:58:18.70848       at org.graylog2.restclient.models.NodeService.radios(NodeService.java:90) ~[org.graylog2.graylog2-rest-client--1.3.3-1.3.3.jar:na]
```

**Comment by kroepke** [comment]
This usually happens when the server is overloaded.

Since version 2.0 has a new UI process this code will no longer be updated. In any case, the root cause of this problem are performance issues on the graylog server process.
