### ISSUE TITLE
Graylog 2.0.0 alpha5 - okHttpClient class not found exception.

### ISSUE THREAD

**Issue by fanirama** [Graylog2/graylog2-server#1950]
### Problem description
unable to start graylog alpha v5 version

### Steps to reproduce the problem

 ~/Graylog/graylog-2.0.0-alpha.5]$ ./bin/graylogctl run
Running graylog-server ...
2016-03-18 13:56:48,779 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugins: [Anonymous Usage Statistics 1.1.1 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]]
2016-03-18 13:56:48,848 INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -Djava.library.path=./bin/../lib/sigar -Xms1g -Xmx1g -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow
Exception in thread "main" java.lang.NoClassDefFoundError: com/squareup/okhttp/OkHttpClient
	at org.graylog.plugins.usagestatistics.UsageStatsModule.configure(UsageStatsModule.java:44)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.graylog2.shared.bindings.PluginBindings.configure(PluginBindings.java:42)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:60)
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:377)
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:180)
	at org.graylog2.bootstrap.Main.main(Main.java:44)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.OkHttpClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

### Environment

* Graylog Version: 2.0.0 alpha 5
* Elasticsearch Version: 2.2.1
* MongoDB Version: 2.4.14
* Operating System: RHEL6.7
* Browser version: FF latest

Exception in thread "main" java.lang.NoClassDefFoundError: com/squareup/okhttp/OkHttpClient

**Comment by joschi** [comment]
@fanirama You're running the Anonymous Usage Statistics plugin in an incompatible version. Please use the Anonymous Usage Statistics plugin which is being shipped with Graylog 2.0.0-alpha.5.
