### ISSUE TITLE
cluster information currently unavailable

### ISSUE THREAD

**Issue by purpl3upz** [Graylog2/graylog2-server#1951]
### Problem description
Graylog-Server is unable to connect to elasticsearch cluster. 
The server log gets me: Elasticsearch cluster not available, skipping index retention checks

### Environment
I am running CentOS 7, SELinux disabled.
Here are the most important settings of my config files:

elasticsearch.yml

node.master: true
node.data: true
ES_HEAP_SIZE: 16384
discovery.zen.ping.unicast.hosts: 127.0.0.1:9300
discovery.zen.ping.multicast.enabled: false
cluster.name: cluster01
node.name: node01

server.conf

is_master: true
rest_listen_uri = http://127.0.0.1:12900/
rest_transport_uri = http://127.0.0.1:12900/
elasticsearch_discovery_zen_ping_multicast_enabled = false
cluster.name: cluster01
node.name: node01

Any Firewalls are disabled.
elasticsearch log tells me the following:
for transport - [node01] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
for http - [node01] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}

service elasticsearch/graylog-server/graylog-web status:
all have green status, no errors or warnings

I am able to connect to the web-interface. 
graylog-web and graylog node are connected. But there is this notificaton: Elasticsearch cluster not available.

* Graylog Version: 1.3.4
* Elasticsearch Version: 2.2.1
* MongoDB Version: 3.2.4-1.el7
* Operating System: CentOS 7

**Comment by joschi** [comment]
@purpl3upz Make sure that the cluster name in the Graylog configuration file and in the Elasticsearch configuration file are identical. `cluster.name` and `node.name` are no valid Graylog configuration settings (see https://github.com/Graylog2/graylog2-server/blob/1.3.4/misc/graylog2.conf#L154-L160). Additionally, you have to provide the address of an Elasticsearch node in the Graylog configuration file if you're not using Zen Multicast Discovery (see http://docs.graylog.org/en/1.3/pages/configuring_es.html#discovery-mode).

**Comment by purpl3upz** [comment]
@joschi thankyou for the reply. I updatet my config files with those settings. But I still get the same error. Furthermore I've noticed that if I run "ss -lp |grep 9200", I won't get anything back. Usually I should get something back what tells me that port 9200 is assigned to elasticsearch shouldn't I?

**Comment by joschi** [comment]
@purpl3upz 
> But if I add: elasticsearch_discovery_zen_ping_unicast_hosts = "127.0.0.1:9300" to my server.conf, the graylog-web cannot find any graylog servers... --> No Graylog servers available. Cannot log in

If your Graylog server node doesn't start up when adding this (BTW, remove the quotes around the address), you should find out why by checking the logs for error messages and fix it. That configuration setting is required if you aren't using Zen Multicast Discovery.

Additionally, while it's really only an aesthetic issue, you shouldn't use the same Elasticsearch node name for your Graylog server node and your Elasticsearch nodes. The cluster name on the other hand *must* be identical.

> Furthermore: ss -lp |grep 9200 or ss -lp |grep 9300 --> no result

You are running Elasticsearch on the same system as Graylog, aren't you? Is the Elasticsearch `java` process listed in the outputs of `netstat -tplen` or `lsof -i :9300`?

**Comment by purpl3upz** [comment]
@joschi thankyou. 

> you should find out why by checking the logs for error messages and fix it
I did this. Graylog-web and server do have a connection. But still the same problem with the cluster.

**Log**
/var/log/graylog-server/server.log:
[netty] [node01] Message not fully read (response) for [67] handler org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$4@46e3bb05, error [true], resetting
[unicast] [node01] failed to send ping to [[#zen_unicast_1#][syslog01][inet[/127.0.0.1:9300]]]
org.elasticsearch.transport.RemoteTransportException: Failed to deserialize exception response from stream
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize exception response from stream
        at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:178)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:130)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

Yes, it's all on the same system. Yes java process is listening on port 9300 and 9200.

**Comment by joschi** [comment]
@purpl3upz Please upgrade to Elasticsearch 1.7.5. It looks like ES 1.3.4 (as you mentioned in your first post) doesn't seem to be compatible with more recent versions on a transport protocol level.

**Comment by purpl3upz** [comment]
@joschi 

> Please upgrade to Elasticsearch 1.7.5

I mixed things up in the first post, I am running Elasticsearch 2.2.1 which should be compatible refering to the graylog docs.

**Comment by joschi** [comment]
@purpl3upz Graylog 1.x doesn't work with Elasticsearch 2.x. Downgrade to Elasticsearch 1.7.5 (and check the system requirements for Graylog 1.x at http://docs.graylog.org/en/1.3/pages/installation.html).

**Comment by purpl3upz** [comment]
my fault, I refered to http://docs.graylog.org/en/stable/pages/installation/manual_setup.html

Downgraded and problem solved now.
