### ISSUE TITLE
Upgrading from 5.2 to 6.0 causes fail (Guice/MissingConstructor and Guice/MissingImplementation)

### ISSUE THREAD

**Issue by chalfling** [Graylog2/graylog2-server#19549]
Upgrading from 5.2.5 to 6.0.2 causes the server to not start at all.

I'm not using any custom plugins.
```
2024-06-04 08:22:40,471 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.storage.SearchVersion, jakarta.inject.Provider<org.graylog2.indexer.security.SecurityAdapter>> was bound.
2024-06-04 08:22:40,472 ERROR: org.graylog2.bootstrap.CmdLineTool - Startup error:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<SecurityAdapter>> was bound.

Did you mean?
    * SecurityAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:79)

    * SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    * SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersOverrideModule.registerParameters(NamedConfigParametersOverrideModule.java:109)

Requested by:
1  : SecurityAdapterProvider.<init>(SecurityAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:79)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

1 error

======================
Full classname legend:
======================
DetectedSearchVersion:               "org.graylog2.storage.DetectedSearchVersion"
ElasticsearchModule:                 "org.graylog2.bindings.ElasticsearchModule"
Named:                               "com.google.inject.name.Named"
NamedConfigParametersOverrideModule: "org.graylog2.bindings.NamedConfigParametersOverrideModule"
Provider:                            "jakarta.inject.Provider"
SearchVersion:                       "org.graylog2.storage.SearchVersion"
SecurityAdapter:                     "org.graylog2.indexer.security.SecurityAdapter"
SecurityAdapterProvider:             "org.graylog2.storage.providers.SecurityAdapterProvider"
VersionAwareStorageModule:           "org.graylog2.storage.VersionAwareStorageModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589) ~[graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163) ~[graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[graylog.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:87) ~[graylog.jar:?]
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:530) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:317) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:267) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:55) [graylog.jar:?]
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for Map<SearchVersion, Provider<SecurityAdapter>> was bound.

Did you mean?
    * SecurityAdapter bound at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:79)

    * SearchVersion annotated with interface DetectedSearchVersion bound at ElasticsearchModule.configure(ElasticsearchModule.java:30)

    * SearchVersion annotated with @Named("elasticsearch_version") bound at NamedConfigParametersOverrideModule.registerParameters(NamedConfigParametersOverrideModule.java:109)

Requested by:
1  : SecurityAdapterProvider.<init>(SecurityAdapterProvider.java:31)
      \_ for 2nd parameter
     at VersionAwareStorageModule.configure(VersionAwareStorageModule.java:79)

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

1 error

======================
Full classname legend:
======================
DetectedSearchVersion:               "org.graylog2.storage.DetectedSearchVersion"
ElasticsearchModule:                 "org.graylog2.bindings.ElasticsearchModule"
Named:                               "com.google.inject.name.Named"
NamedConfigParametersOverrideModule: "org.graylog2.bindings.NamedConfigParametersOverrideModule"
Provider:                            "jakarta.inject.Provider"
SearchVersion:                       "org.graylog2.storage.SearchVersion"
SecurityAdapter:                     "org.graylog2.indexer.security.SecurityAdapter"
SecurityAdapterProvider:             "org.graylog2.storage.providers.SecurityAdapterProvider"
VersionAwareStorageModule:           "org.graylog2.storage.VersionAwareStorageModule"
========================
End of classname legend:
========================
```

* Graylog Version: 6.0.2
* Java Version: openjdk version "17.0.4" 2022-08-12
* Elasticsearch Version: 7.10.2
* MongoDB Version: 5.0.12
* Operating System: FreeBSD 13.1

**Comment by dennisoelkers** [comment]
Hey @chalfling!

Thanks for reporting this. Which distribution are you using? Open core or Enterprise? Docker, tarball, deb, rpm?

**Comment by chalfling** [comment]
Hey @dennisoelkers !

I'm using Graylog Open Core since Graylog 2 on FreeBSD =)

**Comment by janheise** [comment]
@chalfling Hi, how is your upgrading process? maybe you still have the old storage module drivers in the plugin directory?

I just started a 6.0.2 with ES 7.10.2 without any problems.
