### ISSUE TITLE
Upgrading to 6.0.2 No injectable constructor for type SyslogOutput.

### ISSUE THREAD

**Issue by user29835461** [Graylog2/graylog2-server#19543]
6.0.2 fails to start, error in the logs:

```
2024-06-04T09:13:18.418+03:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): No injectable constructor for type com.wizecore.graylog2.plugin.SyslogOutput.
2024-06-04T09:13:18.419+03:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): No implementation for com.wizecore.graylog2.plugin.SyslogOutput$Factory was bound.
2024-06-04T09:13:18.419+03:00 ERROR [CmdLineTool] Startup error:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingConstructor]: No injectable constructor for type SyslogOutput.

class SyslogOutput does not have a @Inject annotated constructor or a no-arg constructor.

Requested by:
1  : SyslogOutput.class(SyslogOutput.java:43)
     while locating SyslogOutput
     at SyslogOutput$Factory.create(SyslogOutput.java:271)

Learn more:
  https://github.com/google/guice/wiki/MISSING_CONSTRUCTOR

2) [Guice/MissingImplementation]: No implementation for SyslogOutput$Factory was bound.

Requested by:
1  : Graylog2Module.installOutput(Graylog2Module.java:267)
      \_ installed by: PluginBindings -> SyslogOutputModule

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2 errors

======================
Full classname legend:
======================
Graylog2Module:       "org.graylog2.plugin.inject.Graylog2Module"
PluginBindings:       "org.graylog2.shared.bindings.PluginBindings"
SyslogOutput:         "com.wizecore.graylog2.plugin.SyslogOutput"
SyslogOutput$Factory: "com.wizecore.graylog2.plugin.SyslogOutput$Factory"
SyslogOutputModule:   "com.wizecore.graylog2.plugin.SyslogOutputModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589) ~[graylog.jar:?]
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163) ~[graylog.jar:?]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[graylog.jar:?]
        at com.google.inject.Guice.createInjector(Guice.java:87) ~[graylog.jar:?]
        at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34) ~[graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:530) ~[graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:317) ~[graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:267) [graylog.jar:?]
        at org.graylog2.bootstrap.Main.main(Main.java:55) [graylog.jar:?]
```

* Graylog Version: 6.0.2
* Java Version: Bundled
* OpenSearch Version: N/A
* MongoDB Version: N/A
* Operating System: RHEL (rpm installation)
* Browser version: N/A

**Comment by user29835461** [comment]
Could cause be rpm upgrade from 4.2.6 to 6.0.2 fails to delete this extra file?

```
# ls -lF /usr/share/graylog-server/plugin/
total 64572
-rw-r--r--. 1 root root    33079 Apr 11  2023 graylog-output-syslog-4.2.6.jar
-rw-r--r--. 1 root root 29649115 May 22 16:48 graylog-storage-elasticsearch7-6.0.2.jar
-rw-r--r--. 1 root root 36433611 May 22 16:48 graylog-storage-opensearch2-6.0.2.jar
```

**Comment by thll** [comment]
It looks like the `graylog-output-syslog-4.2.6.jar` is an external plugin installed manually. Graylog 6.0 requires changes for most plugins to stay compatible. If you still rely on the plugin, you can check if they released a compatible version. Otherwise, if you don't need the plugin anymore, removing the file is the correct thing to do.

I can only guess that you were using this plugin: https://github.com/wizecore/graylog2-output-syslog. They have released a new version that seems to be compatible: https://github.com/wizecore/graylog2-output-syslog/releases.

But please keep in mind that this is third-party code that Graylog doesn't support.

**Comment by user29835461** [comment]
Ah yes, 3rd party plugin issue. Thank you.
