### ISSUE TITLE
Could not retrieve index sets. No default index set configured. This is a bug!

### ISSUE THREAD

**Issue by jayyah** [Graylog2/graylog2-server#19567]
```
2024-06-05T21:40:47.149-04:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.IllegalStateException: No default index set configured. This is a bug!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[graylog.jar:?]
	at org.graylog2.indexer.indexset.MongoIndexSetService.getDefault(MongoIndexSetService.java:107) ~[graylog.jar:?]
	at org.graylog2.rest.resources.system.indexer.IndexSetsResource.list(IndexSetsResource.java:133) ~[graylog.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

## Expected Behavior

Graylog web Indices page should have default index.
## Current Behavior

Graylog web Indices page read ‘Could not retrieve index sets’
![image](https://github.com/Graylog2/graylog2-server/assets/20358686/8697e70f-6a28-403f-bde5-7f9e01573db0)
## Possible Solution

restart graylog service and it will recover for a while

## Steps to Reproduce (for bugs)

1.after some time, it will automatically be no default indices

## Your Environment

* Graylog Version:5.2.5
* ElasticSearch Version:7.10.2
* MongoDB Version:6.0.14
* Operating System:CentOS Linux release 7.9.2009 (Core)

**Comment by tellistone** [comment]
Hello jayyah, thanks for raising this

Would it be possible to get a copy of your server.log from shortly after this occours, and your and server.conf (redacting any sensitive info ofc)

**Comment by jayyah** [comment]
@tellistone hi tellistone, i'm sorry i've reinstall the graylog' version to 5.0.13. And i'll check if there's still the problem in a few days. thx for your reply.

**Comment by JohNan** [comment]
After a couple of hours I also get this error message. I'm running graylog 6.1 in a docker compose environment.

**Comment by cliffalbert** [comment]
Same issue happens here, after a few hours the entire setup is foobared. Also graylog 6 in docker with IPFix data coming in.

**Comment by cybafelo** [comment]
Yes BUMP

**Comment by chubi-x** [comment]
I'm likewise having this issue with a graylog setup running in docker compsoe environment

**Comment by todvora** [comment]
You are mentioning that you are using docker/ docker compose. Can you please share your compose file, or at least the mongodb part? Have you restarted your containers meanwhile? 

I am asking because this exception happens if you wipe out your mongodb data. And this can happen if your mongodb container is using non-persistent data storage and is restarted.

**Comment by tellistone** [comment]
As @todvora suggests above, it looks like your MongoDB node is getting wiped and the cause of that wipe is going to be operational (eg. the location you are storing the data is being wiped by the OS , or the container is being restarted while Graylog is running in a way that causes it to clear its previous data). Its difficult for us to troubleshoot that without more information about the state of both services.

If you can get Graylog and MongoDB to each pipe to an log file stored on a persistent volume, replicate the issue, and then provide the log file we should be able to figure it out. Docker Manager and similar store the log files which may be helpful.

**Comment by todvora** [comment]
Thank you! 

Additionally, I'd check if your mongodb isn't exposed to the outside world, as you are not using any auth. If it's exposed, anyone can delete your databases (and most likely will, sooner or later, especially when running with the default port). 

You can also check your docker logs to see if there is any entry like this, which could give you some additional hints:
```
graylog_mongodb  | {"t":{"$date":"2025-04-04T09:10:47.027+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn13","msg":"dropDatabase","attr":{"db":"graylog","numCollectionsDropped":1}}
```

I would also check if there is some other content remaining in the `graylog` db or generally in the database. 

Graylog itself won't delete the content of its database and the 6.1 release is in production for quite some time and on many instances, so it's rather unlikely there is any trivial and so critical bug. It's far more likely there is something wrong with the usage of the mongodb container, its data/persistence or access to the service.

**Comment by chubi-x** [comment]
thanks @todvora. I discovered some logs that looked like the above. Turns out some malicious actor had ransomed the database :) Thankfully it was all testing data so all I had to do was setup auth and wipe it clean, as well as some wider docker security measures. Thanks for your help!
