### ISSUE TITLE
Graylog-web 1.3.4: java.lang.NoSuchMethodError: rg.jboss.netty.handler.codec.http.HttpRequest.getHeader

### ISSUE THREAD

**Issue by manuelluis** [Graylog2/graylog2-server#1962]
### Problem description

When you access to "Systems / User" and do a search for user sometimes you get in ```console.log``` of graylog-web the following backtrace and the graylog-web goes down:

```
Uncaught error from thread [play-akka.actor.default-dispatcher-9] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.getHeader(Ljava/lang/String;)Ljava/lang/String;
	at play.core.server.websocket.WebSocketHandshake$.getWebSocketLocation(WebSocketHandshake.scala:33)
	at play.core.server.websocket.WebSocketHandshake$.shake(WebSocketHandshake.scala:36)
	at play.core.server.netty.WebSocketHandler$class.websocketHandshake(WebSocketHandler.scala:211)
	at play.core.server.netty.PlayDefaultUpstreamHandler.websocketHandshake(PlayDefaultUpstreamHandler.scala:30)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$messageReceived$6.apply(PlayDefaultUpstreamHandler.scala:225)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$messageReceived$6.apply(PlayDefaultUpstreamHandler.scala:217)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[ERROR] [03/22/2016 13:10:55.421] [play-akka.actor.default-dispatcher-9] [ActorSystem(play)] Uncaught error from thread [play-akka.actor.default-dispatcher-9] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.getHeader(Ljava/lang/String;)Ljava/lang/String;
	at play.core.server.websocket.WebSocketHandshake$.getWebSocketLocation(WebSocketHandshake.scala:33)
	at play.core.server.websocket.WebSocketHandshake$.shake(WebSocketHandshake.scala:36)
	at play.core.server.netty.WebSocketHandler$class.websocketHandshake(WebSocketHandler.scala:211)
	at play.core.server.netty.PlayDefaultUpstreamHandler.websocketHandshake(PlayDefaultUpstreamHandler.scala:30)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$messageReceived$6.apply(PlayDefaultUpstreamHandler.scala:225)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$messageReceived$6.apply(PlayDefaultUpstreamHandler.scala:217)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### Steps to reproduce the problem

Access to "Systems / User" and  search for an user, sometimes you get the error.

It seems to be related to: https://github.com/playframework/playframework/issues/4652

With Graylog 1.3.3-1 I cannot reproduce the problem.

### Environment

* Graylog Version: 1.3.4-1
* Elasticsearch Version: 1.7.5-1
* MongoDB Version: 2.6.10-1
* Operating System: RHEL 6.7
* Browser version: Firefox 42
```
# java -version
java version "1.7.0_95"
Java(TM) SE Runtime Environment (build 1.7.0_95-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.95-b01, mixed mode)
```

**Comment by kroepke** [comment]
Graylog 1.3.x will no see any more (planned) updates now that version 2.0 is in beta phase.
Since 2.0 does not use the Play framework anymore this issue no longer applies, thus I'm closing it.

Thanks
