### ISSUE TITLE
UDP buffer size problems (FreeBSD, maybe generally when OS  != Linux)

### ISSUE THREAD

**Issue by borjam** [Graylog2/graylog2-server#19645]
## Expected Behavior
When setting a buffer size for UDP inputs, either on the Graylog config file (udp_recvbuffer_sizes parameter), the value should be provided to the setsockopt() call. The operating system should decide whether the value is legal or not.

## Current Behavior
There are two different issues at play here:

1. At least on FreeBSD there seems to be some buffer size cap to 16 bit (65536) which should not exist. 
2. Due to a known linuxism there seems to be some confusion with how to check whether the setsockopt() call has been successful. 

The behavior on FreeBSD is rather confusing.  Moreover I have found a workaround that suggests a potential fix for *any* operating system. 

On a FreeBSD system configured with a UDP buffer size of 1048576 bytes (1 MB), Graylog gives the following error:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by drewmiranda-gl** [comment]
I was just researching this last week. What i found is that if you're able to configure `net.core.rmem_max` you can make the error go away:

```
# The maximum socket receive buffer size which may be set by using the SO_RCVBUF socket option
# Applies immediately, does not persist after a reboot
sudo sysctl -w net.core.rmem_max=1048576
# persists on reboot, but does not apply immediately
echo 'net.core.rmem_max=1048576' | sudo tee -a /etc/sysctl.conf
```

This may be more of a documentation issue, what do you think?

**Comment by borjam** [comment]
Sorry, different issues.

You are talking about Linux. I am talking about FreeBSD. Not sure about other systems because the problem might be on the netty library or the JDK itself.

So, what happened to me on FreeBSD is this: 

1. systl -w net.inet.udp.recvspace=1048576     # This is the right way on FreeBSD
2. Start Graylog with default configuration (it will try to do a setsockopt(SO_RCVBUG) of 262144 bytes.
3. If I check the listening UDP sockets with netstat -x which, on FreeBSD, gives me the actual buffer size, I find out it has ben capped to 65536 bytes.


Either setting the graylog.conf variable or the input buffer size for a given input to a value greater than 65536 bytes results in the buffer size being actually capped. 

I confirmed that it is *not* a problem in my system writing a silly C program. I will attach it below. 

 Suspecting some kind of buffer size capping I changed the UDP buffer size parameter to 0 on graylog.conf. It is an illegal value of course. But the call fails, as it should, and Graylog just logs a warning and goes on.

The result of the workaround: The buffer size is the one I specified using sysctl net.inet.udp.recvspace.

Now, a small clarification. Not intending to be disrespectful at all, but some people are not aware that FreeBSD is *not* a Linux distribution. It's an entirely different operating system.  Linux also behaves in a really odd way because when you set a buffer size with setsockopt() and you read it back with getsockopt() it returns the specified buffer size multiplied by two.

So, what I think would make all of this work better is:

1. If udp_recvbuffer_sizes is omitted from graylog.conf it would be much better to leave it alone and trust the default values offered by the operating system. 
2. When checking the proper buffer size you should take into account that Linux is behaving oddly. Nowadays getsockopt(SO_RCVBUF) returns 2 * the specified buffer size, tomorrow it might be π * the specified buffer size. Anyway getsockopt(SO_RCVBUF) >= specified_value looks reasonable to me.

It would be nice to document the issue anyway. There should be a way to ensure that Graylog does not mess with the buffer size and trusts whatever size has been configured by the system aministrator. It can work with the workaround I found (udp_recvbuffer_sizes=0) which is an ugly kludge anyway, or it can be done better by changing Graylog's behavior when the udp_recvbuffer_sizes variable is omitted.

Now I am running Graylog with udp_recvbuffer_sizes=0 and making sure I don't specify any buffer size for the UDP inputs and it shows the buffer size I wanted (1 MB).

That 65536 byte limit is worth investigating, anyway. Maybe it happens on other platforms. 


Checking program: checkbuf.c


```
/*
 * checkbuf.c
 * Verifies UDP buffer size
 */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <sys/types.h>
#include <sys/socket.h>


int main(int argc, char **argv)
{
    int s, r;
    unsigned int bufsiz = 0, actual_bufsiz = 0, len = 0;
    
    if ( argc > 1 )
        bufsiz = atoi(argv[1]);
    s = socket(PF_INET, SOCK_DGRAM, 0);
    if ( s < 0 ) {
        perror("socket()");
        exit(1);
    }
    if ( bufsiz > 0 ) {
        r = setsockopt(s, SOL_SOCKET, SO_RCVBUF, &bufsiz, sizeof(bufsiz));
        if ( r < 0 ) {
            perror("setsockopt()");
            exit(1);
        }
    }
    /* Now verify */
    len = sizeof(actual_bufsiz);
    r = getsockopt(s, SOL_SOCKET, SO_RCVBUF, &actual_bufsiz, &len);
    if ( r < 0 ) {
        perror("getsockopt()");
        exit(1);
    }
    if ( bufsiz > 0 )
        printf("SO_RCVBUF: requested: %d, actual: %d\n", bufsiz, actual_bufsiz);
    else
        printf("SO_SCVBUF: %d\n", actual_bufsiz);
    exit(0);
}

```

**Comment by drewmiranda-gl** [comment]
My apologies, you did say BSD :) 

Also for reference, noting the original discussion via the community forum https://community.graylog.org/t/udp-buffer-size-problem-despite-system-configuration/32726

**Comment by borjam** [comment]
Just in case it was a JDK bug I "checked" the netty source code and I don't find anything suspect of capping the value to 16 bit. Relevant variables in the associated C code are defined as "int" which should be 32 bit. 

And looking at the OpenJDK 17 source code, /usr/local/openjdk17/include/freebsd/jni_md.h also defines "jint" as "int". As it should be.

**Comment by borjam** [comment]
At least the workaround is working until someone decides to abort if a setsockopt() with an illegal value returns an error :)

Thanks for your attention!
 👍

**Comment by borjam** [comment]
I see a regression on 7.1.0+. Someone decided not to ignore the buffer size error and promote it to a full error rather than a warning. 

Before 7.1, if you set the buffer size to 0, Graylog just ignored the error code of trying a setsockupt() with value 0. Which was good, because the default buffer size set by the OS was used.

Now it is complaining because of that error. And the problem is, in non Linux systems the value is interpreted differently. For some reason the Java framework you use is capping it (at least on FreeBSD, may affect others) to 65536. 

I think this is a portability issue, I am not sure whether you have decided to make Graylog Linux-only.

**Proposal: It would be best to avoid trying to set a buffer size if the specified buffer size is 0**.

Behaviour on 7.1+:

```
2026-05-25 10:34:21,305 ERROR o.g.s.i.InputLauncher [inputs-5] The [org.graylog2.inputs.syslog.udp.SyslogUDPInput] input [Syslog UDP/robandobuffer/6a1425894458246884aff597] misfired. Reason: Invalid receive size.
org.graylog2.plugin.inputs.MisfireException: org.graylog2.plugin.inputs.MisfireException: java.lang.IllegalArgumentException: Invalid receive size
	at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:166)
	at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:114)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:259)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.graylog2.plugin.inputs.MisfireException: java.lang.IllegalArgumentException: Invalid receive size
	at org.graylog2.inputs.transports.UdpTransport.launch(UdpTransport.java:136)
	at org.graylog2.plugin.inputs.transports.Transport.launch(Transport.java:35)
	at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:163)
	... 7 more
Caused by: java.lang.IllegalArgumentException: Invalid receive size
	at java.base/sun.nio.ch.DatagramSocketAdaptor.setReceiveBufferSize(DatagramSocketAdaptor.java:319)
	at io.netty.channel.socket.DefaultDatagramChannelConfig.setReceiveBufferSize(DefaultDatagramChannelConfig.java:291)
	at io.netty.channel.socket.DefaultDatagramChannelConfig.setOption(DefaultDatagramChannelConfig.java:116)
	at io.netty.channel.socket.nio.NioDatagramChannelConfig.setOption(NioDatagramChannelConfig.java:132)
	at io.netty.bootstrap.AbstractBootstrap.setChannelOption(AbstractBootstrap.java:488)
	at io.netty.bootstrap.AbstractBootstrap.setChannelOptions(AbstractBootstrap.java:480)
	at io.netty.bootstrap.Bootstrap.init(Bootstrap.java:272)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:328)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:292)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:288)
	at org.graylog2.inputs.transports.UdpTransport.launch(UdpTransport.java:131)
	... 9 more
	Suppressed: java.util.concurrent.CompletionException: Rethrowing promise failure cause
		at io.netty.util.concurrent.DefaultPromise.rethrowIfFailed(DefaultPromise.java:686)
		at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:427)
		at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:125)
		at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:30)
		at org.graylog2.inputs.transports.UdpTransport.launch(UdpTransport.java:133)
		... 9 more
2026-05-25 10:34:21,307 INFO o.g.i.InputStateListener [eventbus-handler-0] Input [Syslog UDP/robandobuffer/6a1425894458246884aff597] is now FAILED
```

If I try to set it to a value higher than 65536, like, 262144, it reads back the buffer size and it is returning 65536. 

```
2026-05-25 10:38:54,827 INFO o.g.i.InputStateListener [eventbus-handler-1] Input [Syslog UDP/robandobuffer/6a1425894458246884aff597] is now STARTING
2026-05-25 10:38:54,828 WARN i.n.b.Bootstrap [inputs-6] Unknown channel option 'io.netty.channel.unix.UnixChannelOption#SO_REUSEPORT' for channel '[id: 0xbe0fe653]' of type 'class io.netty.channel.socket.nio.NioDatagramChannel'
2026-05-25 10:38:54,830 WARN o.g.i.t.UdpTransport [netty-transport-0] receiveBufferSize (SO_RCVBUF) for input SyslogUDPInput{title=robandobuffer, type=org.graylog2.inputs.syslog.udp.SyslogUDPInput, nodeId=null} (channel [id: 0xbe0fe653, L:/192.168.1.205:5552]) should be >= 262144 but is 65536.
2026-05-25 10:38:54,832 INFO o.g.i.InputStateListener [eventbus-handler-0] Input [Syslog UDP/robandobuffer/6a1425894458246884aff597] is now RUNNING

```

Indeed, if I check the actual buffer size in the OS, 

```

$  netstat -p udp -n -a -x |fgrep 5552
udp4           0      0 192.168.1.205.5552     *.*                     **65536**   9216      1   2048      0      0 524288  73728

```

In past versions, the error setting up the buffer size was just a WARNING and, indeed, it used the default buffer size.

Example:
```
2024-06-25 11:02:16,014 WARN i.n.b.Bootstrap [inputs-0] Failed to set channel op
tion 'SO_RCVBUF' with value '0' for channel '[id: 0x7a6a4081]'
java.lang.IllegalArgumentException: Invalid receive size
        at java.base/sun.nio.ch.DatagramSocketAdaptor.setReceiveBufferSize(Datag
ramSocketAdaptor.java:360) ~[?:?]
        at io.netty.channel.socket.DefaultDatagramChannelConfig.setReceiveBufferSize(DefaultDatagramChannelConfig.java:291) ~[graylog.jar:?]
        at io.netty.channel.socket.DefaultDatagramChannelConfig.setOption(DefaultDatagramChannelConfig.java:116) ~[graylog.jar:?]
        at io.netty.channel.socket.nio.NioDatagramChannelConfig.setOption(NioDatagramChannelConfig.java:216) ~[graylog.jar:?]
        at io.netty.bootstrap.AbstractBootstrap.setChannelOption(AbstractBootstrap.java:487) [graylog.jar:?]
        at io.netty.bootstrap.AbstractBootstrap.setChannelOptions(AbstractBootstrap.java:479) [graylog.jar:?]
        at io.netty.bootstrap.Bootstrap.init(Bootstrap.java:278) [graylog.jar:?]
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:327) [graylog.jar:?]
        at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:288) [graylog.jar:?]
        at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:284) [graylog.jar:?]
        at org.graylog2.inputs.transports.UdpTransport.launch(UdpTransport.java:131) [graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.Transport.launch(Transport.java:35) [graylog.jar:?]
        at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:163) [graylog.jar:?]
        at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:95) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:212) [graylog.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
2024-06-25 11:02:16,017 WARN i.n.b.Bootstrap [inputs-0] Unknown channel option 'io.netty.channel.unix.UnixChannelOption#SO_REUSEPORT' for channel '[id: 0x7a6a4081]'
2024-06-25 11:02:16,037 INFO o.g.i.InputStateListener [eventbus-handler-0] Input [IPFIX UDP/IPFix frontera/667aa3b7f15f5e291fcc0ef4] is now RUNNING

```

**Comment by borjam** [comment]
Same problem still on 7.1.8. 

Before 7.1, ignoring the input buffer size resulted in the default buffer size being used. 

Again, I would suggest to try ignoring that error returned when trying to set the buffer size (or just show a warning).
