### ISSUE TITLE
 Couldn't find latest deflector target index

### ISSUE THREAD

**Issue by kira8565** [Graylog2/graylog2-server#1979]
### Problem description
```
2016-03-25 14:39:28,133 WARN : org.graylog2.indexer.IndexHelper - Couldn't find latest deflector target index
org.graylog2.database.NotFoundException: Index range for index <graylog_0> not found.
        at org.graylog2.indexer.ranges.MongoIndexRangeService.get(MongoIndexRangeService.java:92) ~[loginsight.jar:?]
        at org.graylog2.indexer.IndexHelper.determineAffectedIndicesWithRanges(IndexHelper.java:113) [loginsight.jar:?]
        at org.graylog2.indexer.searches.Searches.search(Searches.java:233) [loginsight.jar:?]
        at org.graylog2.rest.resources.search.RelativeSearchResource.searchRelative(RelativeSearchResource.java:105) [loginsight.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [loginsight.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [loginsight.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [loginsight.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [loginsight.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [loginsight.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [loginsight.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [loginsight.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [loginsight.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [loginsight.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [loginsight.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [loginsight.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [loginsight.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [loginsight.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [loginsight.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [loginsight.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [loginsight.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [loginsight.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [loginsight.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [loginsight.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [loginsight.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
```

### Steps to reproduce the problem

1. Start The Graylog Server and wait a miniute

### Environment

* Graylog Version: Beta-2
* Elasticsearch Version: 2.1.1
* MongoDB Version: 3.2.0
* Operating System: Mac
* Browser version: Chorm 48

**Comment by bernd** [comment]
Please show us the complete server log file. Thanks!

**Comment by rubao** [comment]
I have the same issue here

```
2016-04-21T10:53:39.448+02:00 WARN  [IndexHelper] Couldn't find latest deflector target index
org.graylog2.database.NotFoundException: Index range for index <graylog2_1> not found.
	at org.graylog2.indexer.ranges.MongoIndexRangeService.get(MongoIndexRangeService.java:99)
	at org.graylog2.indexer.IndexHelper.determineAffectedIndicesWithRanges(IndexHelper.java:113)
	at org.graylog2.indexer.IndexHelper.determineAffectedIndices(IndexHelper.java:92)
	at org.graylog2.indexer.searches.Searches.histogram(Searches.java:461)
	at org.graylog2.rest.resources.search.RelativeSearchResource.histogramRelative(RelativeSearchResource.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

```
2016-04-21T10:53:51.843+02:00 WARN  [IndexHelper] Couldn't find latest deflector target index
org.graylog2.database.NotFoundException: Index range for index <graylog2_1> not found.
	at org.graylog2.indexer.ranges.MongoIndexRangeService.get(MongoIndexRangeService.java:99)
	at org.graylog2.indexer.IndexHelper.determineAffectedIndicesWithRanges(IndexHelper.java:113)
	at org.graylog2.indexer.IndexHelper.determineAffectedIndices(IndexHelper.java:92)
	at org.graylog2.indexer.searches.Searches.count(Searches.java:180)
	at org.graylog2.alerts.types.MessageCountAlertCondition.runCheck(MessageCountAlertCondition.java:83)
	at org.graylog2.alerts.types.MessageCountAlertCondition.runCheck(MessageCountAlertCondition.java:44)
	at org.graylog2.alerts.AlertServiceImpl.triggered(AlertServiceImpl.java:227)
	at org.graylog2.periodical.AlertScannerThread.doRun(AlertScannerThread.java:95)
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by joschi** [comment]
@rubao Which version of Graylog are you using? Does cycling the deflector (see System &rarr; Indices &rarr; Maintenance) help with that problem?

**Comment by rubao** [comment]
@joschi i'm using the last released version. cycling the deflector works for me, thanks! 

the problem begin when the server went out of space.

**Comment by joschi** [comment]
Closing this issue because the original author didn't reply.
