### ISSUE TITLE
when i use kafka input ,graylog server  cannot  display data

### ISSUE THREAD

**Issue by lschao** [Graylog2/graylog2-server#1991]
### Steps to reproduce the problem

1.use  logstash agent to input kafka cluster
[root@xxxx /home/xxx/log-system]# cat kafka.conf 
input {
  file {
    path => "/data/php/log/archive/php_errors.log-20160325"
  }
    file { 
    type => "producer-mail" 
    path => "/var/log/maillog" 
    } 
    file { 
    type => "cron-log" 
    path => "/var/log/cron" 
    } 
}

output {
  stdout {
    codec => dots
  }
  kafka {
     broker_list => "x.x.x.x:9092"
    topic_id => "graylog-topic"
    compression_codec => "snappy"
    request_required_acks => 1
    serializer_class => "kafka.serializer.StringEncoder"
    request_timeout_ms => 10000
    producer_type => 'async'
    message_send_max_retries => 5
    retry_backoff_ms => 100
    queue_buffering_max_ms => 5000
    queue_buffering_max_messages => 10000
    queue_enqueue_timeout_ms => -1
    batch_num_messages => 1000
  }
}

2.The configures  of  graylog inputs 
topic_filter: ^graylog-topic$
fetch_wait_max: 100
threads: 2
override_source:
zookeeper: x.x.x.x:2181
fetch_min_bytes: 5

3.result
Throughput / Metrics
1 minute average rate: 0 msg/s
Network IO: 0B 0B (total: 678.4KB 0B )

We see the data came in,but cannot  display data ,can't see them

4.the log of graylog server
2016-03-30T14:17:03.016+08:00 ERROR [DecodingProcessor] Unable to decode raw message 04e49560-f63f-11e5-a2a4-aa000079b190 (journal offset 138105) encoded as radio-msg received from unknown source.
2016-03-30T14:17:03.018+08:00 ERROR [DecodingProcessor] Unable to decode raw message 04e49565-f63f-11e5-a2a4-aa000079b190 (journal offset 138110) encoded as radio-msg received from unknown source.
2016-03-30T14:17:03.018+08:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=04e49560-f63f-11e5-a2a4-aa000079b190, journalOffset=138105, codec=radio-msg, payloadSize=439, timestamp=2016-03-30T14:17:03.013+08:00}
org.msgpack.MessageTypeException: Expected array, but got integer value
        at org.msgpack.unpacker.Accept.acceptInteger(Accept.java:45)
        at org.msgpack.unpacker.MessagePackUnpacker.readOneWithoutStack(MessagePackUnpacker.java:91)
        at org.msgpack.unpacker.MessagePackUnpacker.readOne(MessagePackUnpacker.java:73)
        at org.msgpack.unpacker.MessagePackUnpacker.readArrayBegin(MessagePackUnpacker.java:508)
        at org.graylog2.plugin.RadioMessage_$$_Template_2099343080_0.read(RadioMessage_$$_Template_2099343080_0.java)
        at org.msgpack.template.AbstractTemplate.read(AbstractTemplate.java:31)
        at org.msgpack.MessagePack.read(MessagePack.java:388)
        at org.msgpack.MessagePack.read(MessagePack.java:371)
        at org.graylog2.inputs.codecs.RadioMessageCodec.decode(RadioMessageCodec.java:57)
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136)
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

### Environment

* Graylog Version:graylog-web-1.3.4-1.noarch ,graylog-server-1.3.4-1.noarch
* Elasticsearch Version:elasticsearch-1.7.3-1.noarch
* MongoDB Version:mongodb30-3.0.8-1.el6.x86_64
* Operating System:CentOS release 6.2 (Final)
* Browser version:chrome

What should I do?Where I can to change.thank you

**Comment by kroepke** [comment]
Hi!

You are using the "Graylog Radio" codec for your Kafka input. Radio is using a special message format that is only internal to Graylog.
In this case you probably want to change your Graylog input to "Kafka Raw/Plaintext" if you are sending messages as single strings.

Best regards,
Kay

**Comment by lschao** [comment]
"Kafka Raw/Plaintext"  and "Syslog Kafka".They can work normally.thank you 
Yesterday I opened and all related kafka input is just the first ("kafka input") receive message, so I didn't see the result
Thank you very much
