### ISSUE TITLE
Missing Messages due to Grok Pattern in Pipeline Rule Failing Silently #67

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#19975]
https://github.com/Graylog2/support/issues/67

**Comment by tellistone** [comment]
issue shows grok pattern in pipeline rule silently failing when the message its run against is very large

org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter - Error evaluating action

2024-07-12 09:35:25,618 WARN : org.glassfish.jersey.server.ServerRuntime$Responder - An exception mapping did not successfully produce and processed a response. Logging the exception propagated to the default exception mapper.
java.lang.StackOverflowError: null
at java.base/java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:?]
at java.base/java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:?]


Checking details with Support.

**Comment by tellistone** [comment]
The failures do not end up in the processing/indexing failures Index. The grok pattern seems to start to work and then breaks down on larger messages with no failure message we can find.
