### ISSUE TITLE
LDAP authentication doesn't work

### ISSUE THREAD

**Issue by omniton** [Graylog2/graylog2-server#2066]
### Problem description
I'm trying to use OpenLDAP server for external authentication in graylog 2.0 instance but it doesn't work properly instead of in 1.3.4 version.

I'm getting this error:
2016-04-05T09:57:52.103Z WARN [SessionsResource] Unable to log in user test 
org.apache.shiro.authc.AuthenticationException: No account information 
found for authentication token 
[org.apache.shiro.authc.UsernamePasswordToken - test, 
rememberMe=false] by this Authenticator instance. Please check that 
it is configured correctly. 
    at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:202) 
~[graylog.jar:?] 
    at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) 
~[graylog.jar:?] 
    at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270) 
~[graylog.jar:?] 
    at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256) 
~[graylog.jar:?] 
    at org.graylog2.rest.resources.system.SessionsResource.newSession(SessionsResource.java:94) 
[graylog.jar:?] 
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77] 
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
~[?:1.8.0_77] 
<skipped>

At same time test login passed with same credentials.

### Steps to reproduce the problem

1. In LDAP configuration define all necessary parameters.
2. Be sure that login test passed successfully.
3. Try to login with ldap user credentials.

### Environment

* Graylog Version: Graylog 2.0.0-beta.2 (a11dced) 
* Elasticsearch Version: 2.3.1
* MongoDB Version:  3.0.11
* Operating System: ubuntu 14.04
* Browser version: Chrome 49

**Comment by kroepke** [comment]
This should be fixed with #2045 and #2046 and will be released in the upcoming beta.3.
Please reopen this issue if the problem persists in that beta release.

Thank you very much for your report!
