### ISSUE TITLE
Error when opening Sidecars page

### ISSUE THREAD

**Issue by ousmaneo** [Graylog2/graylog2-server#20873]
![Image](https://github.com/user-attachments/assets/53fd75d4-ff3f-451f-856f-714eb3b1292d)

```
connect.tsx:45 Uncaught TypeError: store.getInitialState is not a function
    at connect.tsx:45:1
    at mountState (react-dom.development.js:16986:20)
    at Object.useState (react-dom.development.js:17699:16)
    at useState (react.development.js:1623:21)
    at useStore (connect.tsx:45:1)
    at SidecarListContainer (SidecarListContainer.tsx:35:1)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20069:13)
    at beginWork (react-dom.development.js:21582:16)
```

1. goto System/Sidecars
2.
3.
4.

- Include as many relevant details about the environment you experienced the bug in -->

* Graylog Version: 
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by thll** [comment]
@dennisoelkers: can we bump the priority for this, please? I'd like to refactor something related to sidecars and it would be good being able to test it.
