### ISSUE TITLE
ticking or unticking "show event annotations" causes error

### ISSUE THREAD

**Issue by tellistone** [Graylog2/graylog2-server#20932]
![Image](https://github.com/user-attachments/assets/81e83088-df44-42af-a8ed-852fe285ea89)

To reproduce:

1) create aggregation
2) tick or untick "show event annotations"
3) observe error.

If you hit update widget, the widget on the dashboard works.

master build on smd.dev (11-11-2024).

**Comment by dennisoelkers** [comment]
This is the stack trace from smd:
```
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at getFieldNameFromTrace.ts:25:21
    at Array.find (<anonymous>)
    at ao (getFieldNameFromTrace.ts:22:31)
    at chartLayoutGenerators.ts:295:23
    at Array.reduce (<anonymous>)
    at Es (chartLayoutGenerators.ts:293:47)
    at useChartLayoutSettingsWithCustomUnits.ts:47:30
    at BarVisualization.tsx:141:31
    at Object.ji [as useMemo] (vendor.04eca551cbe5973a6f71.js:671:25071)
    at c.useMemo (vendor.04eca551cbe5973a6f71.js:770:6292)
overrideMethod @ hook.js:608
Show 1 more frame
Show lessUnderstand this errorAI
