### ISSUE TITLE
Custom HTTP Notification fails to send if a double quote exists in any included fields (AND fails silently)

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#20955]
Custom HTTP Notification fails to send if a double quote exists in any included fields

```log
ERROR [JobExecutionEngine] Job execution error - trigger=672c3bac4d4cf967b8a986e1 job=66f5b9acfb912e149e67a204
org.graylog.scheduler.JobExecutionException: Failed permanently to execute notification, giving up - <66f5b9acfb912e149e67a202/<notification_name>/http-notification-v2>
	at org.graylog.events.notifications.EventNotificationExecutionJob.execute(EventNotificationExecutionJob.java:158) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:292) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$4(JobExecutionEngine.java:265) ~[graylog.jar:?]
	at com.codahale.metrics.Timer.time(Timer.java:151) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:265) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.handleTriggerWithConcurrencyLimit(JobExecutionEngine.java:237) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.lambda$execute$2(JobExecutionEngine.java:202) ~[graylog.jar:?]
	at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:115) ~[graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:259) [graylog.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.graylog.events.notifications.PermanentEventNotificationException: Expected successful HTTP response [2xx] but got [400]. {"errors":["input was malformed and could not be parsed"],"status":0,"request":"67b3784b-b586-471d-bc48-d049208a384a"}
	at org.graylog.events.notifications.types.HTTPEventNotificationV2.execute(HTTPEventNotificationV2.java:176) ~[graylog.jar:?]
	at org.graylog.events.notifications.EventNotificationExecutionJob.execute(EventNotificationExecutionJob.java:137) ~[graylog.jar:?]
	... 12 more
```

I found this occurred because my payload looks like:

```json
{
    "token": "...",
    "user": "...",
    "message": "${event.message}\\n\\n${event.fields}",
    "title": "${event_definition_title}"
}
```

And my fields look like:
![Image](https://github.com/user-attachments/assets/ce11d88e-222a-4fb1-b398-225a8081fdbe)

I am working around this by using a pipeline rule to replace occurrences of `"` with `'`.

## Expected Behavior

Event/Alert notifications send without error, BUT if they fail to send, a Graylog System error is generated and show in the Graylog UI. There was zero indication this notification was silently failing.

## Current Behavior

Notification fails and fails silently.

## Possible Solution

Automatically escape double quotes (`\"`) anywhere graylog allows users to input a JSON template for notifications.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 6.1.2
* Java Version: Bundled
* OpenSearch Version: 2.15.0
* MongoDB Version: 7.0.14
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 130.0.6723.117 (Official Build) (arm64)

**Comment by kingzacko1** [comment]
@drewmiranda-gl does this still happen? I converted our templating engine to use a JSON safe version in [this PR](https://github.com/Graylog2/graylog2-server/pull/20318) which should be in 6.1 and backported it to 6.0. Ran a test setting a field explicitly with double quotes and it seemed to work fine.

**Comment by drewmiranda-gl** [comment]
Spoke with Zach about this, here is the specific criteria. This only occurs when NOT using aggregations.

![Image](https://github.com/user-attachments/assets/5a927cb9-a556-4d37-b315-32874eff887d)
![Image](https://github.com/user-attachments/assets/c789d0e2-44ec-4a94-8194-59168ff0075d)
![Image](https://github.com/user-attachments/assets/55163783-233e-46ca-bed5-8480eb8aefe1)

**Comment by kingzacko1** [comment]
@tellistone went ahead and took this one as I am very familiar with the issue and figured out a fairly quick resolution.

**Comment by kingzacko1** [comment]
@drewmiranda-gl there definitely should have been a system error notification created for this.. so I'm not sure what the issue was there. 
```java
if (!r.isSuccessful()) {
    final String errorDetail = r.body() == null ? " URL: " + config.url() : " " + r.body().string();
    errorMessage = "Expected successful HTTP response [2xx] but got [" + r.code() + "]." + errorDetail;
    createSystemErrorNotification(errorMessage + " for notification [" + ctx.notificationId() + "]");
    throw new PermanentEventNotificationException(errorMessage);
}
```
But the PR I created should handle this for the Map types `event.fields` field as well as any collection or iterable types that may show up in a message/event.
