### ISSUE TITLE
UI unusable after upgrade 6.1 when using subpath

### ISSUE THREAD

**Issue by colm-murphy-accenture** [Graylog2/graylog2-server#20986]
## Expected Behavior
UI works as before

## Current Behavior
Unexpected Application Error!
Cannot read properties of null (reading 'at')
TypeError: Cannot read properties of null (reading 'at')
    at n (https://dev-connect.scpmtk.com/debug/graylog/assets/app.43699a361c0b3855da5b.js:4886:55268)
    at https://dev-connect.scpmtk.com/debug/graylog/assets/app.43699a361c0b3855da5b.js:4886:55427
    at https://dev-connect.scpmtk.com/debug/graylog/assets/app.43699a361c0b3855da5b.js:5266:2948
    at Oa (https://dev-connect.scpmtk.com/debug/graylog/assets/vendor.437b8293e0632fce4768.js:692:25074)
    at Ts (https://dev-connect.scpmtk.com/debug/graylog/assets/vendor.437b8293e0632fce4768.js:692:43802)
    at z_ (https://dev-connect.scpmtk.com/debug/graylog/assets/vendor.437b8293e0632fce4768.js:692:37793)
    at Ar (https://dev-connect.scpmtk.com/debug/graylog/assets/vendor.437b8293e0632fce4768.js:690:3290)
    at ec (https://dev-connect.scpmtk.com/debug/graylog/assets/vendor.437b8293e0632fce4768.js:692:42596)
    at us (https://dev-connect.scpmtk.com/debug/graylog/assets/vendor.437b8293e0632fce4768.js:692:41562)
    at E_ (https://dev-connect.scpmtk.com/debug/graylog/assets/vendor.437b8293e0632fce4768.js:692:36565)

The browser console shows the following error

vendor.437b8293e0632fce4768.js:827 TypeError: Cannot read properties of null (reading 'at')
    at n (useSendTelemetry.tsx:33:47)
    at useSendTelemetry.tsx:43:19
    at NavigationTelemetry.tsx:29:7
    at Oa (vendor.437b8293e0632fce4768.js:692:25074)
    at Ts (vendor.437b8293e0632fce4768.js:692:43802)
    at z_ (vendor.437b8293e0632fce4768.js:692:37793)
    at Ar (vendor.437b8293e0632fce4768.js:690:3290)
    at ec (vendor.437b8293e0632fce4768.js:692:42596)
    at us (vendor.437b8293e0632fce4768.js:692:41562)
    at E_ (vendor.437b8293e0632fce4768.js:692:36565)

## Your Environment
Telemetry is disabled using the GRAYLOG_TELEMETRY_ENABLED=false property in our docker compose

* Graylog Version: 6.1.2 (docker)

**Comment by drewmiranda-gl** [comment]
Howdy, can you share your steps to reproduce this? Can you share your (redacted) compose file? Are you using a path other than `/` to access graylog?

For example: http://hostname:9000 vs http://hostname:9000/graylog

**Comment by coffee-squirrel** [comment]
FWIW, we've not seen this in `6.1.0`, `6.1.1`, or `6.1.2` (Open and Enterprise) with `GRAYLOG_TELEMETRY_ENABLED: "false"`.

**Comment by drewmiranda-gl** [comment]
Hi @colm-murphy-accenture no worries. I was going to link that issue but glad you found it. This should be fixed in our next bug fix release which is on Wednesday, December 4.

**Comment by dennisoelkers** [comment]
@colm-murphy-accenture: The issue should be fixed in today's `6.1.3` release. It would be nice if you could test and close the issue if it has been fixed for you.

**Comment by colm-murphy-accenture** [comment]
@dennisoelkers: 6.1.3 fixes the issue. Thanks for the fast turnaround.
