### ISSUE TITLE
2.0.0 AWS AMI fails

### ISSUE THREAD

**Issue by rsteckler** [Graylog2/graylog2-server#2153]
### Problem description
A fresh install of the AMI fails with the following error in the browser:
````
Error message
Bad request
Original Request
GET http://172.31.56.67:12900/system/cluster/node
Status code
undefined
Full error message
Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
````

Here is the browser console:
````
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484 OPTIONS http://172.31.56.67:12900/system/sessions net::ERR_CONNECTION_TIMED_OUTRequest.end @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13577tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:18208Promise._resolveFromResolver @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16287Promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:15877Request.promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13576Request.then @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13611init @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86079t @ vendor.js:415e.exports @ vendor.js:415(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86068__webpack_require__ @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:20Session @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:2322getStore @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:2382(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:22273__webpack_require__ @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:20CurrentUser @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:2199getStore @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:2382(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:1979__webpack_require__ @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:20(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:1890__webpack_require__ @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:20(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:1772__webpack_require__ @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:20(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:1552__webpack_require__ @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:20(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:345__webpack_require__ @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:20(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:229__webpack_require__ @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:20(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:57__webpack_require__ @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:20(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:40(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:43
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:14572 Unhandled rejection SuperagentPromiseError: Bad request
    at http://beta2.evmote.com/plugin/org.graylog.plugins.pipelineprocessor.Proces…pipelineprocessor.PipelineProcessorPlugin.62d4f9ed4c4bd0ccbd76.js:13586:19
    at Request.callback (http://beta2.evmote.com/plugin/org.graylog.plugins.pipelineprocessor.Proces….pipelineprocessor.PipelineProcessorPlugin.62d4f9ed4c4bd0ccbd76.js:19328:4)
    at Request.crossDomainError (http://beta2.evmote.com/plugin/org.graylog.plugins.pipelineprocessor.Proces….pipelineprocessor.PipelineProcessorPlugin.62d4f9ed4c4bd0ccbd76.js:19345:9)
    at XMLHttpRequest.xhr.onreadystatechange (http://beta2.evmote.com/plugin/org.graylog.plugins.pipelineprocessor.Proces…pipelineprocessor.PipelineProcessorPlugin.62d4f9ed4c4bd0ccbd76.js:19408:20)
Caused by:  Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at Request.crossDomainError (http://beta2.evmote.com/plugin/org.graylog.plugins.pipelineprocessor.Proces…pipelineprocessor.PipelineProcessorPlugin.62d4f9ed4c4bd0ccbd76.js:19338:14)
    at XMLHttpRequest.xhr.onreadystatechange (http://beta2.evmote.com/plugin/org.graylog.plugins.pipelineprocessor.Proces…pipelineprocessor.PipelineProcessorPlugin.62d4f9ed4c4bd0ccbd76.js:19408:20)
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484 GET http://172.31.56.67:12900/system/cluster/node net::ERR_CONNECTION_TIMED_OUTRequest.end @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13577tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:18208Promise._resolveFromResolver @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16287Promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:15877Request.promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13576Request.then @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13611ping @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86009init @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86003t @ vendor.js:415e.exports @ vendor.js:415(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:85999__webpack_require__ @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:20ServerAvailability @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:2319getStore @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:2382(anonymous function) @ AppFacade.jsx:52(anonymous function) @ AppFacade.jsx:83(anonymous function) @ app.5b57fee….js:22n @ app.5b57fee….js:1(anonymous function) @ index.jsx:15(anonymous function) @ index.jsx:25(anonymous function) @ app.5b57fee….js:1n @ app.5b57fee….js:1(anonymous function) @ app.5b57fee….js:1(anonymous function) @ app.5b57fee….js:1
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484 OPTIONS http://172.31.56.67:12900/system/sessions net::ERR_CONNECTION_TIMED_OUTRequest.end @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13577tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:18208Promise._resolveFromResolver @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16287Promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:15877Request.promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13576Request.then @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13611json @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13457login @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86090n @ vendor.js:415r.emit @ vendor.js:409trigger @ vendor.js:415(anonymous function) @ vendor.js:415(anonymous function) @ vendor.js:408r.run @ vendor.js:405o @ vendor.js:405
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13411 There was an error fetching a resource: Bad request. Additional information: Not availableFetchError @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13411(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13479tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:18208Promise._settlePromiseFromHandler @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16314Promise._settlePromiseAt @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16388Promise._settlePromises @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16504Async._drainQueue @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13794Async._drainQueues @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13804Async.drainQueues @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13686
vendor.js:405 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the LoginPage component.r @ vendor.js:405r @ vendor.js:14enqueueSetState @ vendor.js:14o.setState @ vendor.js:398(anonymous function) @ LoginPage.jsx?./~/react-hot-loader!./~/babel-loader:66
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484 GET http://172.31.56.67:12900/system/cluster/node net::ERR_CONNECTION_TIMED_OUTRequest.end @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13577tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:18208Promise._resolveFromResolver @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16287Promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:15877Request.promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13576Request.then @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13611ping @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86009
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484 GET http://172.31.56.67:12900/system/cluster/node net::ERR_CONNECTION_TIMED_OUTRequest.end @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13577tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:18208Promise._resolveFromResolver @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16287Promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:15877Request.promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13576Request.then @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13611ping @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86009
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484 GET http://172.31.56.67:12900/system/cluster/node net::ERR_CONNECTION_TIMED_OUTRequest.end @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13577tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:18208Promise._resolveFromResolver @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16287Promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:15877Request.promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13576Request.then @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13611ping @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86009
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484 GET http://172.31.56.67:12900/system/cluster/node net::ERR_CONNECTION_TIMED_OUTRequest.end @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13577tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:18208Promise._resolveFromResolver @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16287Promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:15877Request.promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13576Request.then @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13611ping @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86009
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484 GET http://172.31.56.67:12900/system/cluster/node net::ERR_CONNECTION_TIMED_OUTRequest.end @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13577tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:18208Promise._resolveFromResolver @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16287Promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:15877Request.promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13576Request.then @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13611ping @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86009
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484 GET http://172.31.56.67:12900/system/cluster/node net::ERR_CONNECTION_TIMED_OUTRequest.end @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:19484(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13577tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:18208Promise._resolveFromResolver @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:16287Promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:15877Request.promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13576Request.then @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:13611ping @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.62d4f9e….js:86009
````
* Graylog Version: 2.0.0
* Operating System: EC2 AMI
* Browser version: Chrome

**Comment by rsteckler** [comment]
The address it's trying to connect to (http://172.31.56.67:12900) is my AWS internal IP address, so won't be reachable from the browser.  Not sure if that's relevant.

**Comment by rsteckler** [comment]
Other users with what might be the same problem today:
https://groups.google.com/forum/?hl=en#!topic/graylog2/kwd3nIt05DI
https://groups.google.com/forum/?hl=en#!topic/graylog2/OS7TBT7qDZg
https://groups.google.com/forum/?hl=en#!topic/graylog2/oJQ3epRdU-E

**Comment by joschi** [comment]
@rsteckler Did you try setting the public IP address of your EC2 instance(s) explicitly in `rest_listen_uri` and `web_listen_uri`?

**Comment by rsteckler** [comment]
Argh!  I missed that piece of the docs.  I can test later today, but that sounds right.  Is there a way to do that with graylog-ctl?  I don't see that step on the [AWS installation page](http://docs.graylog.org/en/2.0/pages/installation/aws.html) or the [graylog-ctl doc page](http://docs.graylog.org/en/2.0/pages/installation/graylog_ctl.html#graylog-ctl).  Also, the docs still show graylog-ctl as being able to reconfigure as a web interface.  Given my new understanding (thank you!) about the server and web being one, that seems out of date.

After I test later today and verify that's the problem, I'll update the issue and potentially create a new one specifically for the docs.

Thanks!
Ryan

**Comment by rsteckler** [comment]
I believe this was fixed with [this commit](https://github.com/Graylog2/graylog2-images/commit/54bc01615867614b0eabcadff5d1882b30466c58).  I downloaded the new AMIs this morning and they work out of the box!

Thanks,
Ryan

**Comment by mariussturm** [comment]
Also read about the new 'set-external-ip' command: http://docs.graylog.org/en/2.0/pages/installation/aws.html
It was basicaly made for AWS.
