### ISSUE TITLE
GrayLog2 OVA Web page Graylog is restarting... for hour

### ISSUE THREAD

**Issue by matlem037** [Graylog2/graylog2-server#2162]
### Problem description
Hello
I have just install Graylog 2 using OVA.
When i start the OVA, I only got the message "Graylog is restarting..." for hours...

Top give this :  
```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                      
  881 root      20   0  499692 140848   4800 S 120.2  1.7 243:17.45 svloggelfd                                   
  882 root      20   0    4360   1336   1244 S   2.7  0.0   4:32.82 svlogd         
```
In log :
```
2016-04-29_11:49:43.72138       at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [graylog.jar:?]
2016-04-29_11:49:43.72211       at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) [graylog.jar:?]
2016-04-29_11:49:43.72245       at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [graylog.jar:?]
2016-04-29_11:49:43.72315       at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205) [graylog.jar:?]
2016-04-29_11:49:43.72348       at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199) [graylog.jar:?]
2016-04-29_11:49:43.72403       at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) [graylog.jar:?]
2016-04-29_11:49:43.72439       at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199) [graylog.jar:?]
2016-04-29_11:49:43.72496       at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) [graylog.jar:?]
2016-04-29_11:49:43.72533       at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) [graylog.jar:?]
2016-04-29_11:49:43.72587       at com.google.inject.Guice.createInjector(Guice.java:96) [graylog.jar:?]
2016-04-29_11:49:43.72618       at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:60) [graylog.jar:?^C
```
I have try with graylog-ctl reconfigure but still got the problem

### Environment

VM : 4 CPU, 8Gb RAM

Does anyone got an idea ?

Thanks

**Comment by joschi** [comment]
@matlem037 Please provide the full log output of Graylog.

**Comment by matlem037** [comment]
The current file is about 122Mo...I Kept some lines in enclosed file
[log_graylog_current.txt](https://github.com/Graylog2/graylog2-server/files/242411/log_graylog_current.txt)

Some commands :
ubuntu@graylog:~$ sudo graylog-ctl status
run: elasticsearch: (pid 20434) 2168s; run: log: (pid 855) 16486s
run: etcd: (pid 20465) 2167s; run: log: (pid 859) 16486s
run: graylog-server: (pid 23545) 32s; run: log: (pid 861) 16486s
run: mongodb: (pid 20483) 2166s; run: log: (pid 856) 16486s
run: nginx: (pid 20501) 2166s; run: log: (pid 858) 16486s

ubuntu@graylog:~$ sudo graylog-ctl show-config
Starting Chef Client, version 12.6.0
Compiling Cookbooks...
{
  "graylog": {
    "bootstrap": {
      "bootstrapped": false
    },
    "etcd": {
      "enabled": true
    },
    "nginx": {
      "enabled": true
    },
    "mongodb": {
      "enabled": true
    },
    "elasticsearch": {
      "enabled": true
    },
    "graylog-server": null
  }
}
Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 01 seconds

Thanks for help

**Comment by joschi** [comment]
@matlem037 
> ```
2016-04-29_12:20:23.11957 324) Error injecting constructor, java.lang.RuntimeException: kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/opt/graylog/data/journal. A Kafka instance in another process or thread is using this directory.
```
Stop all instances of Graylog (and make sure that none is running), remove `/var/opt/graylog/data/journal/.lock`, and then restart Graylog.

**Comment by matlem037** [comment]
Grrr 

Even with "graymog-ctl stop" still remaining process related to graylog

 runsvdir -P /opt/graylog/service log: ....................................................................
  849 ?        Ss     0:00  \_ runsv mongodb
  862 ?        S      0:00  |   \_ /bin/sh ./run
  873 ?        Sl     0:00  |       \_ /opt/graylog/embedded/bin/svloggelfd -H 127.0.0.1:12201 -s mongodb -e
  874 ?        S      0:00  |       \_ svlogd -tt /var/log/graylog/mongodb
  850 ?        Ss     0:00  \_ runsv nginx
  863 ?        S      0:00  |   \_ /bin/sh ./run
  870 ?        Sl     0:00  |       \_ /opt/graylog/embedded/bin/svloggelfd -H 127.0.0.1:12201 -s nginx -e
  872 ?        S      0:00  |       \_ svlogd -tt /var/log/graylog/nginx
  851 ?        Ss     0:00  \_ runsv elasticsearch
  861 ?        S      0:00  |   \_ /bin/sh ./run
  869 ?        Sl     0:00  |       \_ /opt/graylog/embedded/bin/svloggelfd -H 127.0.0.1:12201 -s elasticsearch -e
  871 ?        S      0:00  |       \_ svlogd -tt /var/log/graylog/elasticsearch
  852 ?        Ss     0:00  \_ runsv graylog-server
  859 ?        S      0:00  |   \_ /bin/sh ./run
  866 ?        Sl     7:44  |       \_ /opt/graylog/embedded/bin/svloggelfd -H 127.0.0.1:12201 -s graylog-server -e
  868 ?        S      0:08  |       \_ svlogd -tt /var/log/graylog/server
  853 ?        Ss     0:00  \_ runsv etcd
  858 ?        S      0:00      \_ /bin/sh ./run
  865 ?        Sl     0:00          \_ /opt/graylog/embedded/bin/svloggelfd -H 127.0.0.1:12201 -s etcd -e
  867 ?        S      0:00          \_ svlogd -tt /var/log/graylog/etcd

And it is still true after a reboot
I am going to make a new vm...

**Comment by kroepke** [comment]
This does not look like a bug. If you have more information please reopen the issue.

Thank you!

**Comment by gordonmurray** [comment]
I have the same issue currently. I thought it was due to low disk space as I only had 2gb left, so I cloned the current volume and started up with a 500gb copy. I am still stuck with 'Graylog is restarting...'

I have stopped graylog and associated services and like @matlem037 above, there are still running processes. Killing them causes them to respawn.

I'd really like to keep my data and not have to start with a new VM.

**Comment by joschi** [comment]
@gordonmurray We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
