### ISSUE TITLE
graylog 2.0 docker image problems 

### ISSUE THREAD

**Issue by pettai** [Graylog2/graylog2-server#2164]
I followed the instructions according to:
http://docs.graylog.org/en/2.0/pages/installation/docker.html
And tested the simplest docker-compose example:
```
pettai@my-debian-jessie:~$ docker-compose up
Starting pettai_some-elasticsearch_1
Starting pettai_some-mongo_1
Starting pettai_graylog_1
Attaching to pettai_some-elasticsearch_1, pettai_some-mongo_1, pettai_graylog_1
some-mongo_1          | 2016-04-30T09:40:37.192+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=11b337edddee
some-mongo_1          | 2016-04-30T09:40:37.193+0000 I CONTROL  [initandlisten] db version v3.2.6
some-mongo_1          | 2016-04-30T09:40:37.193+0000 I CONTROL  [initandlisten] git version: 05552b562c7a0b3143a729aaa0838e558dc49b25
some-mongo_1          | 2016-04-30T09:40:37.193+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
some-mongo_1          | 2016-04-30T09:40:37.193+0000 I CONTROL  [initandlisten] allocator: tcmalloc
some-mongo_1          | 2016-04-30T09:40:37.193+0000 I CONTROL  [initandlisten] modules: none
some-mongo_1          | 2016-04-30T09:40:37.193+0000 I CONTROL  [initandlisten] build environment:
some-mongo_1          | 2016-04-30T09:40:37.193+0000 I CONTROL  [initandlisten]     distmod: debian71
some-mongo_1          | 2016-04-30T09:40:37.193+0000 I CONTROL  [initandlisten]     distarch: x86_64
some-mongo_1          | 2016-04-30T09:40:37.193+0000 I CONTROL  [initandlisten]     target_arch: x86_64
some-mongo_1          | 2016-04-30T09:40:37.193+0000 I CONTROL  [initandlisten] options: {}
some-mongo_1          | 2016-04-30T09:40:37.202+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
some-mongo_1          | 2016-04-30T09:40:37.203+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=18G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
some-mongo_1          | 2016-04-30T09:40:37.759+0000 I CONTROL  [initandlisten]
some-mongo_1          | 2016-04-30T09:40:37.759+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
some-mongo_1          | 2016-04-30T09:40:37.759+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
some-mongo_1          | 2016-04-30T09:40:37.759+0000 I CONTROL  [initandlisten]
some-mongo_1          | 2016-04-30T09:40:37.762+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
some-mongo_1          | 2016-04-30T09:40:37.762+0000 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
some-mongo_1          | 2016-04-30T09:40:37.763+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
some-elasticsearch_1  | [2016-04-30 09:40:39,624][INFO ][node                     ] [Lorna Dane] version[2.3.2], pid[1], build[b9e4a6a/2016-04-21T16:03:47Z]
some-elasticsearch_1  | [2016-04-30 09:40:39,627][INFO ][node                     ] [Lorna Dane] initializing ...
some-elasticsearch_1  | [2016-04-30 09:40:41,747][INFO ][plugins                  ] [Lorna Dane] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
some-elasticsearch_1  | [2016-04-30 09:40:41,830][INFO ][env                      ] [Lorna Dane] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sde1)]], net usable_space [190.3gb], net total_space [229.1gb], spins? [possibly], types [ext4]
some-elasticsearch_1  | [2016-04-30 09:40:41,831][INFO ][env                      ] [Lorna Dane] heap size [989.8mb], compressed ordinary object pointers [true]
some-elasticsearch_1  | [2016-04-30 09:40:47,569][INFO ][node                     ] [Lorna Dane] initialized
some-elasticsearch_1  | [2016-04-30 09:40:47,570][INFO ][node                     ] [Lorna Dane] starting ...
some-elasticsearch_1  | [2016-04-30 09:40:47,874][INFO ][transport                ] [Lorna Dane] publish_address {172.17.0.3:9300}, bound_addresses {[::]:9300}
some-elasticsearch_1  | [2016-04-30 09:40:47,889][INFO ][discovery                ] [Lorna Dane] graylog/umVEjpnySGy8PHCNAZAJXg
graylog_1             | 2016-04-30 09:40:48,501 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugins: [Anonymous Usage Statistics 2.0.0 [org.graylog.plugins.usagestatistics.UsageStatsPlugin], Pipeline Processor Plugin 1.0.0-beta.2 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin], Collector 1.0.0 [org.graylog.plugins.collector.CollectorPlugin], MapWidgetPlugin 1.0.0 [org.graylog.plugins.map.MapWidgetPlugin], Enterprise Integration Plugin 1.0.0 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]]
graylog_1             | 2016-04-30 09:40:48,855 INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -Xms1g -Xmx2g -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configuration=file:///usr/share/graylog/data/config/log4j2.xml -Djava.library.path=/usr/share/graylog/lib/sigar/ -Dgraylog2.installation_source=docker
some-elasticsearch_1  | [2016-04-30 09:40:51,030][INFO ][cluster.service          ] [Lorna Dane] new_master {Lorna Dane}{umVEjpnySGy8PHCNAZAJXg}{172.17.0.3}{172.17.0.3:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
some-elasticsearch_1  | [2016-04-30 09:40:51,197][INFO ][http                     ] [Lorna Dane] publish_address {172.17.0.3:9200}, bound_addresses {[::]:9200}
some-elasticsearch_1  | [2016-04-30 09:40:51,198][INFO ][node                     ] [Lorna Dane] started
some-elasticsearch_1  | [2016-04-30 09:40:51,235][INFO ][gateway                  ] [Lorna Dane] recovered [0] indices into cluster_state
graylog_1             | 2016-04-30 09:40:56,230 INFO : org.graylog2.shared.buffers.InputBufferImpl - Message journal is enabled.
graylog_1             | 2016-04-30 09:40:56,873 INFO : kafka.log.LogManager - Loading logs.
graylog_1             | 2016-04-30 09:40:57,167 INFO : kafka.log.LogManager - Logs loading complete.
graylog_1             | 2016-04-30 09:40:57,169 INFO : org.graylog2.shared.journal.KafkaJournal - Initialized Kafka based journal at /usr/share/graylog/data/journal
graylog_1             | 2016-04-30 09:40:57,213 INFO : org.graylog2.shared.buffers.InputBufferImpl - Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
graylog_1             | 2016-04-30 09:40:57,327 INFO : org.mongodb.driver.cluster - Cluster created with settings {hosts=[mongo:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
graylog_1             | 2016-04-30 09:40:57,593 INFO : org.mongodb.driver.cluster - No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=mongo:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
graylog_1             | 2016-04-30 09:40:57,582 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017
graylog_1             | com.mongodb.MongoSocketException: mongo: unknown error
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) [graylog.jar:?]
graylog_1             | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
graylog_1             | Caused by: java.net.UnknownHostException: mongo: unknown error
graylog_1             | 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getByName(InetAddress.java:1076) ~[?:1.8.0_72-internal]
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[graylog.jar:?]
graylog_1             | 	... 5 more
graylog_1             | 2016-04-30 09:40:58,127 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017
graylog_1             | com.mongodb.MongoSocketException: mongo
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) [graylog.jar:?]
graylog_1             | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
graylog_1             | Caused by: java.net.UnknownHostException: mongo
graylog_1             | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getByName(InetAddress.java:1076) ~[?:1.8.0_72-internal]
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[graylog.jar:?]
graylog_1             | 	... 5 more
graylog_1             | 2016-04-30 09:41:07,637 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017
graylog_1             | com.mongodb.MongoSocketException: mongo: unknown error
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) [graylog.jar:?]
graylog_1             | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
graylog_1             | Caused by: java.net.UnknownHostException: mongo: unknown error
graylog_1             | 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getByName(InetAddress.java:1076) ~[?:1.8.0_72-internal]
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[graylog.jar:?]
graylog_1             | 	... 5 more
graylog_1             | 2016-04-30 09:41:08,139 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017
graylog_1             | com.mongodb.MongoSocketException: mongo
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) [graylog.jar:?]
graylog_1             | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
graylog_1             | Caused by: java.net.UnknownHostException: mongo
graylog_1             | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getByName(InetAddress.java:1076) ~[?:1.8.0_72-internal]
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[graylog.jar:?]
graylog_1             | 	... 5 more
graylog_1             | 2016-04-30 09:41:17,650 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017
graylog_1             | com.mongodb.MongoSocketException: mongo: unknown error
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) [graylog.jar:?]
graylog_1             | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
graylog_1             | Caused by: java.net.UnknownHostException: mongo: unknown error
graylog_1             | 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getByName(InetAddress.java:1076) ~[?:1.8.0_72-internal]
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[graylog.jar:?]
graylog_1             | 	... 5 more
graylog_1             | 2016-04-30 09:41:18,152 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017
graylog_1             | com.mongodb.MongoSocketException: mongo
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[graylog.jar:?]
graylog_1             | 	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) [graylog.jar:?]
graylog_1             | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
graylog_1             | Caused by: java.net.UnknownHostException: mongo
graylog_1             | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_72-internal]
graylog_1             | 	at java.net.InetAddress.getByName(InetAddress.java:1076) ~[?:1.8.0_72-internal]
graylog_1             | 	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[graylog.jar:?]
graylog_1             | 	... 5 more
```
Not much more is happening after that... 

* Graylog Version: 2.0.0-1
* Elasticsearch Version: official docker
* MongoDB Version: official docker
* Operating System: Debian Jessie
* Docker version: 1.11.1-0~jessie

**Comment by joschi** [comment]
@pettai
> ```
Caused by: java.net.UnknownHostException: mongo: unknown error
```

It looks like you've provided the wrong MongoDB server in your Graylog configuration (see [`mongodb_uri`](https://github.com/Graylog2/graylog2-server/blob/2.0.0/misc/graylog.conf#L319-L321)). Make sure that the Docker container running Graylog is able to access the Docker container running MongoDB with the given host name.

**Comment by kroepke** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like it. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
