### ISSUE TITLE
Unable to process event MessageEvent java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by witalisoft** [Graylog2/graylog2-server#2183]
### Problem description

We're experience problem with Java heap space, after couple hours of working the folllowing exeception shows up:

```
2016-05-03T10:57:43.459+02:00 WARN  [ProcessBuffer] Unable to process event MessageEvent{raw=null, message=null, messages=null}, sequence 26320
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at java.lang.StringBuilder.toString(StringBuilder.java:407)
        at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:356)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:235)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:233)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3731)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2272)
        at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:115)
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136)
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

we process large text fields
the problem seems to be related to
https://github.com/Graylog2/graylog2-server/issues/1545

### Environment
```
{
  "facility" : "graylog-server",
  "codename" : "Hansa",
  "server_id" : "85152262-ea7e-4556-a6cb-97091bd8bff3",
  "version" : "1.3.3 (0fda9dc)",
  "started_at" : "2016-05-04T09:22:08.683Z",
  "hostname" : "graylog.local",
  "lifecycle" : "running",
  "lb_status" : "alive",
  "timezone" : "Europe/Warsaw",
  "operating_system" : "Linux 3.16.0-67-generic",
  "is_processing" : true
}

running java:
"Oracle Corporation 1.8.0_74 on Linux 3.16.0-67-generic"

graylog-server started with params:
GRAYLOG_SERVER_JAVA_OPTS="-Djava.net.preferIPv4Stack=true -Xms2g -Xmx2g -XX:NewRatio=1 -XX:PermSize=128m -XX:MaxPermSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow"
```

**Comment by dennisoelkers** [comment]
You need to provide more memory for your Graylog server, 2GB simply seems to be not enough. Also, if you think this is an error, please upgrade to 2.0.0 first before reopening this issue, as we have fixed a lot of issues in between.
