### ISSUE TITLE
Every odd index rolled too early

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2194]
### Problem description
Every second index stays unfilled to configured condition.
![image](https://cloud.githubusercontent.com/assets/17475270/15068944/348faad6-1383-11e6-86ca-186e9db76995.png)
![image](https://cloud.githubusercontent.com/assets/17475270/15068783/49883b7a-1382-11e6-8797-f2f05677583c.png)

### Environment
* Graylog Version: 2.0 GA
* Elasticsearch Version: 2.3.1

**Comment by kroepke** [comment]
Could you append your Graylog server log as well as the corresponding elasticsearch log at the time when an index is wrongly cycled, please?

**Comment by hc4** [comment]
81 indx is wrongly cycled:
![image](https://cloud.githubusercontent.com/assets/17475270/15138683/26831ea4-169a-11e6-85bc-164795a25347.png)

Theres is roll from 80 to 81:
```
2016-05-10T08:23:12.458+03:00 INFO  [AbstractRotationStrategy] Deflector index <graylog2_80> should be rotated, Pointing deflector to new index now!
2016-05-10T08:23:12.458+03:00 INFO  [Deflector] Cycling deflector to next index now.
2016-05-10T08:23:12.499+03:00 INFO  [Deflector] Cycling from <graylog2_80> to <graylog2_81>
2016-05-10T08:23:12.499+03:00 INFO  [Deflector] Creating index target <graylog2_81>...
2016-05-10T08:23:12.531+03:00 INFO  [Indices] Created Graylog index template "graylog-internal" in Elasticsearch.
2016-05-10T08:23:12.758+03:00 INFO  [Deflector] Waiting for index allocation of <graylog2_81>
2016-05-10T08:23:12.899+03:00 INFO  [Deflector] Done!
2016-05-10T08:23:12.899+03:00 INFO  [Deflector] Pointing deflector to new target index....
2016-05-10T08:23:12.946+03:00 INFO  [SystemJobManager] Submitted SystemJob <4a8f1215-166f-11e6-848a-005056b37533> [org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob]
2016-05-10T08:23:12.946+03:00 INFO  [SystemJobManager] Submitted SystemJob <4a8f3922-166f-11e6-848a-005056b37533> [org.graylog2.indexer.SetIndexReadOnlyJob]
2016-05-10T08:23:12.946+03:00 INFO  [SystemJobManager] Submitted SystemJob <4a8f3923-166f-11e6-848a-005056b37533> [org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob]
2016-05-10T08:23:12.946+03:00 INFO  [Deflector] Done!
2016-05-10T08:23:12.946+03:00 INFO  [CreateNewSingleIndexRangeJob] Calculating ranges for index graylog2_80.
2016-05-10T08:23:12.946+03:00 INFO  [CreateNewSingleIndexRangeJob] Calculating ranges for index graylog2_81.
2016-05-10T08:23:12.952+03:00 INFO  [MongoIndexRangeService] Calculated range of [graylog2_81] in [2ms].
2016-05-10T08:23:12.952+03:00 INFO  [CreateNewSingleIndexRangeJob] Created ranges for index graylog2_81.
```
And roll from 81 to 82 (again checks condition for 80).
```
2016-05-10T09:35:02.797+03:00 INFO  [AbstractRotationStrategy] Deflector index <graylog2_80> should be rotated, Pointing deflector to new index now!
2016-05-10T09:35:02.797+03:00 INFO  [Deflector] Cycling deflector to next index now.
2016-05-10T09:35:02.968+03:00 INFO  [Deflector] Cycling from <graylog2_81> to <graylog2_82>
2016-05-10T09:35:02.968+03:00 INFO  [Deflector] Creating index target <graylog2_82>...
2016-05-10T09:35:03.142+03:00 INFO  [Indices] Created Graylog index template "graylog-internal" in Elasticsearch.
2016-05-10T09:35:03.306+03:00 INFO  [Deflector] Waiting for index allocation of <graylog2_82>
2016-05-10T09:35:03.389+03:00 INFO  [Deflector] Done!
2016-05-10T09:35:03.389+03:00 INFO  [Deflector] Pointing deflector to new target index....
2016-05-10T09:35:03.537+03:00 INFO  [SystemJobManager] Submitted SystemJob <53df3610-1679-11e6-848a-005056b37533> [org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob]
2016-05-10T09:35:03.537+03:00 INFO  [CreateNewSingleIndexRangeJob] Calculating ranges for index graylog2_81.
2016-05-10T09:35:03.537+03:00 INFO  [SystemJobManager] Submitted SystemJob <53df3611-1679-11e6-848a-005056b37533> [org.graylog2.indexer.SetIndexReadOnlyJob]
2016-05-10T09:35:03.537+03:00 INFO  [SystemJobManager] Submitted SystemJob <53df3612-1679-11e6-848a-005056b37533> [org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob]
2016-05-10T09:35:03.537+03:00 INFO  [Deflector] Done!
2016-05-10T09:35:03.538+03:00 INFO  [CreateNewSingleIndexRangeJob] Calculating ranges for index graylog2_82.
2016-05-10T09:35:03.547+03:00 INFO  [MongoIndexRangeService] Calculated range of [graylog2_82] in [3ms].
2016-05-10T09:35:03.548+03:00 INFO  [CreateNewSingleIndexRangeJob] Created ranges for index graylog2_82.
2016-05-10T09:35:03.548+03:00 INFO  [SystemJobManager] SystemJob <53df3612-1679-11e6-848a-005056b37533> [org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob] finished in 10ms.
2016-05-10T09:35:09.707+03:00 INFO  [MongoIndexRangeService] Calculated range of [graylog2_81] in [6164ms].
2016-05-10T09:35:09.708+03:00 INFO  [CreateNewSingleIndexRangeJob] Created ranges for index graylog2_81.
2016-05-10T09:35:09.708+03:00 INFO  [SystemJobManager] SystemJob <53df3610-1679-11e6-848a-005056b37533> [org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob] finished in 6170ms.
2016-05-10T09:35:33.538+03:00 INFO  [SetIndexReadOnlyJob] Flushing old index <graylog2_81>.
2016-05-10T09:35:35.302+03:00 INFO  [SetIndexReadOnlyJob] Setting old index <graylog2_81> to read-only.
2016-05-10T09:35:35.444+03:00 INFO  [SystemJobManager] Submitted SystemJob <66e3d543-1679-11e6-848a-005056b37533> [org.graylog2.indexer.indices.jobs.OptimizeIndexJob]
2016-05-10T09:35:35.444+03:00 INFO  [SystemJobManager] SystemJob <53df3611-1679-11e6-848a-005056b37533> [org.graylog2.indexer.SetIndexReadOnlyJob] finished in 1906ms.
2016-05-10T09:35:35.444+03:00 INFO  [OptimizeIndexJob] Optimizing index <graylog2_81>.
```

**Comment by kroepke** [comment]
Thanks!

It looks like the code wrongly sees an older index as the current write index and thus wrongly thinks it should rotate. From re-reading the code there's nothing that's obviously wrong, though.
The only guess we currently have is that somehow an incomplete list of indices comes back. Does your elasticsearch cluster show very high load during those times?
Are there any messages in the elasticsearch logs?

Thanks!

**Comment by hc4** [comment]
Sometimes I have such errors:
```
2016-05-10T09:46:42.348+03:00 ERROR [MessageCountRotationStrategy] Unknown index, cannot perform rotation
org.graylog2.indexer.IndexNotFoundException
	at org.graylog2.indexer.indices.Indices.numberOfMessages(Indices.java:170) ~[graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategy.shouldRotate(MessageCountRotationStrategy.java:67) [graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategy.shouldRotate(MessageCountRotationStrategy.java:33) [graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy.rotate(AbstractRotationStrategy.java:55) [graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.checkForRotation(IndexRotationThread.java:109) [graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_74]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_74]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_74]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
2016-05-10T09:46:42.348+03:00 ERROR [AbstractRotationStrategy] Cannot perform rotation at this moment.
```

**Comment by hc4** [comment]
And yes, my ES node sometimes could be overloaded.

**Comment by kroepke** [comment]
Ok, then it seems like we are missing a check if some shards failed to report back.
We are looking into making this more robust for the next bugfix release.

Thanks

**Comment by hc4** [comment]
Also maybe connected to this issue. I found such message in logs:
`2016-05-10T14:16:32.011+03:00 WARN  [IndexRotationThread] Deflector is pointing to [graylog2_82], not the newest one: [graylog2_81]. Re-pointing.`

It seems it incorrectly repointing, beause index 82 actualy exists.

**Comment by kroepke** [comment]
Yup, that appears to be the same symptom. Getting the index stats is expensive because it needs to look at every shard in the cluster, but we don't actually need that level of detail.
The patch above changes the code to a more lightweight call that returns the relevant information only.

**Comment by hc4** [comment]
But what if new lightweight call will also fail? Will problem remain?

**Comment by kroepke** [comment]
The problem was that the index stats call could return incomplete information and didn't actually fail completely. The new call will either fail completely or return the entire list of indices, so it should fix this problem.

The underlying problem of course is a cluster that is too slow or otherwise broken (not accessible shards).
The change also logs a warning if not all index stats are returned from elasticsearch, but that is only used  to display the System/Indices page now.

**Comment by hc4** [comment]
Thanks, I see now.
