### ISSUE TITLE
Dashboards do not work

### ISSUE THREAD

**Issue by andreasbruns** [Graylog2/graylog2-server#2195]
### Steps to reproduce the problem

1. klick on "Dashboards" shows an Error

Stacktrace

    org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder#execute (ApiClientImpl.java:436)
    org.graylog2.restclient.models.dashboards.DashboardService#getAll (DashboardService.java:58)
    controllers.DashboardsController#index (DashboardsController.java:59)
    Routes$$anonfun$routes$1$$anonfun$applyOrElse$115$$anonfun$apply$689#apply (routes_routing.scala:2182)
    Routes$$anonfun$routes$1$$anonfun$applyOrElse$115$$anonfun$apply$689#apply (routes_routing.scala:2182)
    play.core.Router$HandlerInvokerFactory$$anon$4#resultCall (Router.scala:264)
    play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1#invocation (Router.scala:255)
    play.core.j.JavaAction$$anon$1#call (JavaAction.scala:55)
    play.GlobalSettings$1#call (GlobalSettings.java:67)
    play.mvc.Security$AuthenticatedAction#call (Security.java:44)
    play.core.j.JavaAction$$anonfun$11#apply (JavaAction.scala:82)
    play.core.j.JavaAction$$anonfun$11#apply (JavaAction.scala:82)
    scala.concurrent.impl.Future$PromiseCompletingRunnable#liftedTree1$1 (Future.scala:24)
    scala.concurrent.impl.Future$PromiseCompletingRunnable#run (Future.scala:24)
    play.core.j.HttpExecutionContext$$anon$2#run (HttpExecutionContext.scala:40)
    play.api.libs.iteratee.Execution$trampoline$#execute (Execution.scala:46)
    play.core.j.HttpExecutionContext#execute (HttpExecutionContext.scala:32)
    scala.concurrent.impl.Future$#apply (Future.scala:31)
    scala.concurrent.Future$#apply (Future.scala:485)
    play.core.j.JavaAction$class#apply (JavaAction.scala:82)
    play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1#apply (Router.scala:252)
    play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5#apply (Action.scala:130)
    play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5#apply (Action.scala:130)
    play.utils.Threads$#withContextClassLoader (Threads.scala:21)
    play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4#apply (Action.scala:129)
    play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4#apply (Action.scala:128)
    scala.Option#map (Option.scala:145)
    play.api.mvc.Action$$anonfun$apply$1#apply (Action.scala:128)
    play.api.mvc.Action$$anonfun$apply$1#apply (Action.scala:121)
    play.api.libs.iteratee.Iteratee$$anonfun$mapM$1#apply (Iteratee.scala:483)
    play.api.libs.iteratee.Iteratee$$anonfun$mapM$1#apply (Iteratee.scala:483)
    play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1#apply (Iteratee.scala:519)
    play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1#apply (Iteratee.scala:519)
    play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14#apply (Iteratee.scala:496)
    play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14#apply (Iteratee.scala:496)
    scala.concurrent.impl.Future$PromiseCompletingRunnable#liftedTree1$1 (Future.scala:24)
    scala.concurrent.impl.Future$PromiseCompletingRunnable#run (Future.scala:24)
    akka.dispatch.TaskInvocation#run (AbstractDispatcher.scala:41)
    akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask#exec (AbstractDispatcher.scala:393)
    scala.concurrent.forkjoin.ForkJoinTask#doExec (ForkJoinTask.java:260)
    scala.concurrent.forkjoin.ForkJoinPool$WorkQueue#runTask (ForkJoinPool.java:1339)
    scala.concurrent.forkjoin.ForkJoinPool#runWorker (ForkJoinPool.java:1979)
    scala.concurrent.forkjoin.ForkJoinWorkerThread#run (ForkJoinWorkerThread.java:107)

2016-05-06T11:40:02.058+02:00 ERROR [NettyContainer] Uncaught exception in transport layer. This is likely a bug, closing channel.
java.lang.StackOverflowError
        at com.fasterxml.jackson.databind.SerializerProvider.<init>(SerializerProvider.java:204)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.<init>(DefaultSerializerProvider.java:62)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl.<init>(DefaultSerializerProvider.java:497)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl.createInstance(DefaultSerializerProvider.java:502)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl.createInstance(DefaultSerializerProvider.java:491)
        at com.fasterxml.jackson.databind.ObjectMapper._serializerProvider(ObjectMapper.java:2831)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
        at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
        at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
        at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
        at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
        at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
        at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:239)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
        at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
...

### Environment

* Graylog Version:
Version:
    0.92.4 (0495186) (Moose)
JVM:
    PID 22425, Oracle Corporation 1.7.0_95 on Linux 2.6.32-573.18.1.el6.x86_64
* Elasticsearch Version:
1.4.5
* MongoDB Version:
2.6.11
* Operating System:
CentOS release 6.7
* Browser version:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by dennisoelkers** [comment]
Your Graylog version is very old. It was released over a year ago. Please update to 2.0.0 and try again.
