### ISSUE TITLE
system/fields (500) cannot connect to elasticsearch

### ISSUE THREAD

**Issue by dramones-his** [Graylog2/graylog2-server#2222]
### Problem description
Deploying a new cluster for version 2.0.1-1 using the vmware ova templates after a failed upgrade from our current cluster 1.3.4 to 2.0 corrupted the cluster. 

Upon logging into the system search or the indices pages will not load gives the error message: 

```
Could not load field information
Loading field information failed with status: cannot GET http://<masternode_ip:12900/system/fields (500)
```

Cannot configure inputs or basically do anything in the app without having it timing out. 

### Environment

* Graylog Version: 2.0.1-1 OVA
* Vmware 6
* Browser version: Chrome 50.0.2661.94 m (64-bit)

**Comment by dennisoelkers** [comment]
What does your Graylog server log say?

**Comment by mariussturm** [comment]
There was a misconfiguration in the 2.0 appliances, we just shipped an updated version. Could you please update to 2.0.1-2 and report back?

**Comment by dramones-his** [comment]
if you are talking about /opt/graylog/server/log it is empty.

**Comment by dramones-his** [comment]
@mariussturm its not listed here? https://packages.graylog2.org/appliances/ova

I just downloaded graylog-2.0.1-1.ova this morning.

**Comment by mariussturm** [comment]
Takes some minutes, use this link instead: https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-2.0.1-2.ova

**Comment by anmolnagpal** [comment]
I'm getting same error
Graylog version : Graylog 2.0.1 (81e0187)
OS: Ubuntu

please note it's not **ova** Installed it manually.

**Comment by joschi** [comment]
@anmolnagpal Are there any error messages in the logs of your Graylog node?

**Comment by anmolnagpal** [comment]
@joschi 

```
2016-05-18T09:15:53.407-04:00 WARN  [netty] [graylog-892fbed2-7d8f-4b7e-86fe-ef6ca5905c36] exception caught on transport layer [[id: 0x9029cc35]], closing connection
java.net.SocketException: Network is unreachable
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_91]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_91]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) [graylog.jar:?]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [graylog.jar:?]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2016-05-18T09:15:53.408-04:00 WARN  [netty] [graylog-892fbed2-7d8f-4b7e-86fe-ef6ca5905c36] exception caught on transport layer [[id: 0xcc1c32af]], closing connection
java.net.SocketException: Network is unreachable
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_91]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_91]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) [graylog.jar:?]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [graylog.jar:?]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by joschi** [comment]
@anmolnagpal Are there any error messages in the logs of your Elasticsearch nodes? Are the Elasticsearch nodes up and running?

**Comment by anmolnagpal** [comment]
In Elasticsearch

graylog.log
```
[2016-05-18 09:10:02,608][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
[2016-05-18 09:10:02,949][INFO ][node                     ] [Loss] version[2.3.2], pid[29442], build[b9e4a6a/2016-04-21T16:03:47Z]
[2016-05-18 09:10:02,949][INFO ][node                     ] [Loss] initializing ...
[2016-05-18 09:10:04,305][INFO ][plugins                  ] [Loss] modules [reindex, lang-expression, lang-groovy], plugins [head, kopf, hq], sites [hq, kopf, head]
[2016-05-18 09:10:04,352][INFO ][env                      ] [Loss] using [1] data paths, mounts [[/ (/dev/simfs)]], net usable_space [47.9gb], net total_space [50gb], spins? [possibly], types [simfs]
[2016-05-18 09:10:04,352][INFO ][env                      ] [Loss] heap size [999mb], compressed ordinary object pointers [true]
[2016-05-18 09:10:04,353][WARN ][env                      ] [Loss] max file descriptors [65535] for elasticsearch process likely too low, consider increasing to at least [65536]
[2016-05-18 09:10:07,427][INFO ][node                     ] [Loss] initialized
[2016-05-18 09:10:07,427][INFO ][node                     ] [Loss] starting ...
[2016-05-18 09:10:07,515][INFO ][transport                ] [Loss] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}, {127.0.0.2:9300}
[2016-05-18 09:10:07,520][INFO ][discovery                ] [Loss] graylog/P79uHIuXTuei75iJ1j5Z5A
[2016-05-18 09:10:10,567][INFO ][cluster.service          ] [Loss] new_master {Loss}{P79uHIuXTuei75iJ1j5Z5A}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-05-18 09:10:10,666][INFO ][http                     ] [Loss] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}, {127.0.0.2:9200}
[2016-05-18 09:10:10,667][INFO ][node                     ] [Loss] started
[2016-05-18 09:10:10,670][INFO ][gateway                  ] [Loss] recovered [0] indices into cluster_state
```

**Comment by joschi** [comment]
@anmolnagpal We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by joschi** [comment]
@dramones-his Does the problem still occur on the latest Graylog OVA?

**Comment by pelegrim** [comment]
Same error from graylog-2.0.2-1.qcow2

**Comment by pelegrim** [comment]
BindTransportException[Failed to bind to [9300-9400]]; nested: ChannelException[Failed to bind to: /<OLD IP>:9400]; nested: BindException[Cannot assign requested address];

appears after changing IP

**Comment by rbreaves** [comment]
Same error in graylog-2.0.2-1.ova... looks like between inadequate documentation on the manual install and the OVA not getting packaged well I may just have to use an ELK stack instead.

**Comment by jalogisch** [comment]
@pelegrim you would need to run **graylog-ctl reconfigure** after change of ip address 

@rbreaves 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

@dramones-his 
Unfortunately the issue is not reproducible in the latest release. Please re-open this issue if it still occurs, ideally with a set of reproducible steps. 

Thanks!

**Comment by trajano** [comment]
I just created a new stack, but I used AWS ElasticSearch Service.
