### ISSUE TITLE
Upgrade 1.3 to 2.0.1 lost configurations

### ISSUE THREAD

**Issue by drsharp42** [Graylog2/graylog2-server#2237]
On my DEV instance of 1.3.x Graylog/Elasticsearch1.7/mongodb 3.0;
Went through process of upgrading to 2.0.1 using YUM pulls.

Had 30 (>100m logs) days of of log records in elasticsearch.
Graylog had several defined inputs to accept (GELF from logstash).

Shutdown down Graylog, mongodb, elasticsearch.
Verified elasticsearch was good with migration plugin.
did yum update of elasticsearch
Updated the elasticsearch.yml

Starting elasticsearch on first try looked good; GREEN status.

Performed the cleanup of graylog pivate ino. in elasticsearch.

Did yum remove of both graylog-server anf graylog-web. made copies of config files.

Did a yum install of graylog-server... this worked on second try, as yum cache was trying to pull 1.3.x version.

Made changes to 2.0.1 server.conf based on copy of 1.3 conf file.

Updated from iptables rules for port 12900 access, and created NAT rules, as this is on a vm behind firewall.

On first start of of Graylog 2.0:
2016-05-13T05:10:45.399-07:00 INFO  [RestApiService] Started REST API at <http://127.0.0.1:12900/
>
2016-05-13T05:10:45.400-07:00 INFO  [ServiceManagerListener] Services are healthy
2016-05-13T05:10:45.401-07:00 INFO  [ServerBootstrap] Services started, startup times in ms: {Inp
utSetupService [RUNNING]=7, JournalReader [RUNNING]=64, KafkaJournal [RUNNING]=64, MetricsReporte
rService [RUNNING]=64, BufferSynchronizerService [RUNNING]=74, OutputSetupService [RUNNING]=75, P
eriodicalsService [RUNNING]=117, WebInterfaceService [RUNNING]=2715, IndexerSetupService [RUNNING
]=3823, RestApiService [RUNNING]=6484}
2016-05-13T05:10:45.402-07:00 INFO  [InputSetupService] Triggering launching persisted inputs, no
de transitioned from UninitializedÂ [LB:DEAD] to RunningÂ [LB:ALIVE]
2016-05-13T05:10:45.407-07:00 INFO  [ServerBootstrap] Graylog server up and running.
2016-05-13T05:10:45.478-07:00 WARN  [ExtractorFilter] Unable to load input: Input <56cc88d337ccf1
f3cf737c4f> not found!
2016-05-13T05:10:45.480-07:00 WARN  [StaticFieldFilter] Unable to load input: Input <56cc88d337cc
f1f3cf737c4f> not found!
2016-05-13T05:10:48.960-07:00 INFO  [Deflector] Did not find an deflector alias. Setting one up n
ow.
2016-05-13T05:10:48.968-07:00 INFO  [Deflector] There is no index target to point to. Creating on
e now.
2016-05-13T05:10:48.973-07:00 INFO  [Deflector] Cycling deflector to next index now.
2016-05-13T05:10:48.976-07:00 INFO  [Deflector] Cycling from <none> to <graylogTEST_0>
2016-05-13T05:10:48.977-07:00 INFO  [Deflector] Creating index target <graylogTEST_0>...
2016-05-13T05:10:49.033-07:00 INFO  [Indices] Created Graylog index template "graylog-internal" i
n Elasticsearch.
2016-05-13T05:10:49.046-07:00 ERROR [IndexRotationThread] Couldn't point deflector to a new index
org.elasticsearch.indices.InvalidIndexNameException: Invalid index name [graylogTEST_0], must be
lowercase
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDa
taCreateIndexService.java:153) ~[graylog.jar:?]
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateI
ndexService.java:473) ~[graylog.jar:?]
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$100(MetaDataCreat
eIndexService.java:97) ~[graylog.jar:?]
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreate
IndexService.java:192) ~[graylog.jar:?]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:4
5) ~[graylog.jar:?]
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalC
lusterService.java:468) ~[graylog.jar:?]
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalCluste
rService.java:772) ~[graylog.jar:?]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPr
ioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231) ~[graylog.jar:?]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPr
ioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194) ~[graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8
.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8
.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2016-05-13T05:10:53.960-07:00 INFO  [IndexRangesCleanupPeriodical] Skipping index range cleanup b
ecause the Elasticsearch cluster is unreachable or unhealthy
2016-05-13T05:10:58.958-07:00 INFO  [Deflector] Did not find an deflector alias. Setting one up n
ow.
2016-05-13T05:10:58.961-07:00 INFO  [Deflector] There is no index target to point to. Creating on
e now.
2016-05-13T05:10:58.963-07:00 INFO  [Deflector] Cycling deflector to next index now.
2016-05-13T05:10:58.966-07:00 INFO  [Deflector] Cycling from <none> to <graylogTEST_0>
2016-05-13T05:10:58.966-07:00 INFO  [Deflector] Creating index target <graylogTEST_0>...
2016-05-13T05:10:58.984-07:00 INFO  [Indices] Created Graylog index template "graylog-internal" i
n Elasticsearch.
2016-05-13T05:10:58.993-07:00 ERROR [IndexRotationThread] Couldn't point deflector to a new index
org.elasticsearch.indices.InvalidIndexNameException: Invalid index name [graylogTEST_0], must be
lowercase
----------------------------------------
It repeated the above.
Yes, my index name template was set to "graylogTEST".
Guessed that by setting name to "graylogtest" in server.conf might work... and it did.
Graylog saw all the indexes (graylogtest_27 to _57)
Note: Gray did not find my previous two INPUT definitions:
2016-05-13T05:10:45.478-07:00 WARN  [ExtractorFilter] Unable to load input: Input <56cc88d337ccf1
f3cf737c4f> not found!
2016-05-13T05:10:45.480-07:00 WARN  [StaticFieldFilter] Unable to load input: Input <56cc88d337cc
f1f3cf737c4f> not found!

----------
Was able to login to web interface:
None of my dashboards, no contentpaks, no inputs.
Ran a manual 'recalculate index ranges"; this worked.
----------
On INPUTS page, no inputs.
Recreated a GELF UDP, like old one. Said it created one... but does not display in web page.
No error in server.log file.
On indices page, index shows it is accumulating records (looking at filesystem confirms data added).

But 'search' page does not return results for any new log events.
--------------------
Tried manual recycle index... log shows it worked, but web interface does not see new graylogtest_58.

Since this is index 32, automatic process to delete oldest tried to delete oldest index.
Failed;
2016-05-13T15:00:22.298-07:00 INFO  [AbstractIndexCountBasedRetentionStrategy] Number of indices
(32) higher than limit (31). Running retention for 1 indices.
2016-05-13T15:00:22.320-07:00 INFO  [AbstractIndexCountBasedRetentionStrategy] Running retention
strategy [org.graylog2.indexer.retention.strategies.DeletionRetentionStrategy] for index <graylog
test_27>
2016-05-13T15:00:22.386-07:00 INFO  [DeletionRetentionStrategy] Finished index retention strategy
 [delete] for index <graylogtest_27> in 64ms.
2016-05-13T15:01:10.760-07:00 ERROR [IndicesResource] Index [graylogtest_27] not found.
Message repeats 30 times....
-----------------------------

Hate to blow this away... but it is my DEV.
Would like suggestions, as I need to upgrade PROD.

### Environment

* Graylog Version: 2.0.1-1
* Elasticsearch Version: 2.3.2-1
* MongoDB Version: 3.10.1
* Operating System: CentOS 7.2.1511
* Browser version: IE 11

**Comment by drsharp42** [comment]
Found that if I search over 30+ minutes, do see log results for new log data..
Also Graylog did a automatic daily roll of index 58 to 59. It also deleted old index 28.
Created a test user... But new local user is not displayed in web interface.
But I can logon as new user.

**Comment by drsharp42** [comment]
Looks like visibility of configurations via browser (IE 11) had something to do with browser cache.
This AM, could see changes made on Friday.
Used another Windows desktop /w IE11 and could see configurations, and make updates.
Deleted 'temp internet files'; and browser view is appropriate.
Closing.
