### ISSUE TITLE
Elasticsearch cluster unavailable

### ISSUE THREAD

**Issue by hasifm2010** [Graylog2/graylog2-server#2238]
### Problem description

I am unable to connect to ES server.

IPtables disabled

Selinux disabled

{
  "cluster_name" : "graylog2",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0
}

I am getting graylog server UP and running in Graylog logs. But after that i getting below logs:-

2016-05-16T12:09:17.688+04:00 WARN  [netty] [graylog-81a32787-d358-443b-818d-8b776508b6a1] exception caught on transport layer [[id: 0xa62f51be, /192.168.10.138:13568 => /192.168.10.138:9300]], closing connection
java.lang.NullPointerException
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleException(MessageChannelHandler.java:207) ~[graylog.jar:?]
        at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:202) ~[graylog.jar:?]
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:136) ~[graylog.jar:?]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[graylog.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [graylog.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [graylog.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [graylog.jar:?]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) [graylog.jar:?]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) [graylog.jar:?]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) [graylog.jar:?]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [graylog.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [graylog.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [graylog.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [graylog.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [graylog.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [graylog.jar:?]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

 
### Steps to reproduce the problem

1. ...

### Environment
 
* Graylog Version:  2.0.1
* Elasticsearch Version: 1.7.5
* MongoDB Version:  3.2.6
* Operating System: RHEL 6.8
* Browser version: Chrome 50

**Comment by hasifm2010** [comment]
![image](https://cloud.githubusercontent.com/assets/18568536/15284039/e3347312-1b5f-11e6-9ef0-da0373948288.png)

**Comment by eorochena** [comment]
I encounter similar issue when I upgrade to GrayLog 2.0

I have to set the below parameters in the /etc/graylog/server/server.conf

elasticsearch_discovery_zen_ping_unicast_hosts = 192.168.1.1:9300,192.168.1.2:9300,192.168.1.3:9300
elasticsearch_cluster_name = some_logs
# we don't want the Graylog server to store any data, or be master node
#elasticsearch_node_master = false
#elasticsearch_node_data = false

# use a different port if you run multiple Elasticsearch nodes on one machine
elasticsearch_transport_tcp_port = 9300

**Comment by kroepke** [comment]
Graylog 2.0 requires Elasticsearch 2.3.x, it does not work with previous versions.
You need to update your elasticsearch cluster first.

Please see our documentation: http://docs.graylog.org/en/2.0/pages/upgrade.html

Thanks,
Kay

**Comment by hasifm2010** [comment]
Thank you so much for your support..It worked now after updating to 2.3.1.
