### ISSUE TITLE
Graylog server 2.0.1 could not been started

### ISSUE THREAD

**Issue by magic4u** [Graylog2/graylog2-server#2242]
### Problem description
fresh installed graylog 2.0.1, but could not been started, the error msg is 
"Caused by: java.net.BindException: Cannot assign requested address"

### Steps to reproduce the problem

1. server.conf
rest_listen_uri = http://172.31.82.21:12900/
web_listen_uri = http://172.31.82.21:9000/

2. server.log
2016-05-17 07:48:14,081 ERROR: com.google.common.util.concurrent.ServiceManager - Service RestApiService [FAILED] has failed in the STOPPING state.
javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Cannot assign requested address
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:299) ~[graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:163) ~[graylog.jar:?]
	at org.graylog2.shared.initializers.AbstractJerseyService.setUp(AbstractJerseyService.java:158) ~[graylog.jar:?]
	at org.graylog2.shared.initializers.RestApiService.startUp(RestApiService.java:65) ~[graylog.jar:?]
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:60) [graylog.jar:?]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:100) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_92]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_92]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_92]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_92]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_92]
	at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:131) ~[graylog.jar:?]
	at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:88) ~[graylog.jar:?]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:248) ~[graylog.jar:?]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:228) ~[graylog.jar:?]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:219) ~[graylog.jar:?]
	at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:714) ~[graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:278) ~[graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:296) ~[graylog.jar:?]
	... 6 more
2016-05-17 07:48:14,083 ERROR: org.graylog2.bootstrap.ServerBootstrap - Graylog startup failed. Exiting. Exception was:
java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {STARTING=[RestApiService [STARTING], IndexerSetupService [STARTING]], FAILED=[WebInterfaceService [FAILED]]}
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:713) ~[graylog.jar:?]
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:542) ~[graylog.jar:?]
	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:299) ~[graylog.jar:?]
	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:129) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:209) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]

### Environment

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2.6
* Operating System: centos 6.7
* Browser version:

**Comment by dennisoelkers** [comment]
Could you please double check that the IP used in the `web_listen_uri` configuration directive is assigned to your machine and no other process is listening on port 9000?

**Comment by magic4u** [comment]
thx, dennisoelkers, 
it's my fault. :)
