### ISSUE TITLE
Too many collector configuration inputs make the gui hang

### ISSUE THREAD

**Issue by perbly** [Graylog2/graylog2-server#2247]
### Problem description
Going to collectors>"manage configurations">"choosing one configuration"  makes the gui hang and only "Loading...." show in the gui.

 
### Steps to reproduce the problem

1. I´m not 100% sure but i think the problem appeared when i created more than 5 inputs for a configuration.
I created inputs for IIS logs.

If i use the restAPI http://graylog:12900/plugins/org.graylog.plugins.collector/{id} all inputs are listed correctly so it feels like a GUI problem.

### Environment
collector plugin version: 1.0.1

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.2
* MongoDB Version: 
* Operating System: Win2012R2
* Browser version: Chrome 50.0.26.61.102

**Comment by joschi** [comment]
@perbly Thanks for reporting this! Are there any error messages in the Developer Console of your browser (https://developers.google.com/web/tools/chrome-devtools/debug/console/) or in the logs of your Graylog node(s)?

**Comment by perbly** [comment]
Yes some messages in the console log @joschi 

plugin.org.graylog.plugins.collector.CollectorPlugin.5b76e9d….js:109058 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at _inputFormatter (http://graylog:9000/plugin/org.graylog.plugins.collector.Col…raylog.plugins.collector.CollectorPlugin.5b76e9d123d026932389.js:109058:47)
    at render (http://graylog:9000/plugin/org.graylog.plugins.collector.Col….graylog.plugins.collector.CollectorPlugin.5b76e9d123d026932389.js:2473:24)
    at y._renderValidatedComponentWithoutOwnerOrContext (http://graylog:9000/vendor.js:403:12595)
    at y._renderValidatedComponent (http://graylog:9000/vendor.js:403:12771)
    at i [as _renderValidatedComponent] (http://graylog:9000/vendor.js:12:18757)
    at y.mountComponent (http://graylog:9000/vendor.js:403:7747)
    at i [as mountComponent] (http://graylog:9000/vendor.js:12:18757)
    at Object.a.mountComponent (http://graylog:9000/vendor.js:12:31712)
    at y.v.Mixin.mountChildren (http://graylog:9000/vendor.js:404:14636)
    at y.Mixin._createContentMarkup (http://graylog:9000/vendor.js:403:24339)
    at y.Mixin.mountComponent (http://graylog:9000/vendor.js:403:23239)
    at Object.a.mountComponent (http://graylog:9000/vendor.js:12:31712)
    at y.v.Mixin.mountChildren (http://graylog:9000/vendor.js:404:14636)
    at y.Mixin._createContentMarkup (http://graylog:9000/vendor.js:403:24339)
    at y.Mixin.mountComponent (http://graylog:9000/vendor.js:403:23239)
    at Object.a.mountComponent (http://graylog:9000/vendor.js:12:31712)
    at y.v.Mixin.mountChildren (http://graylog:9000/vendor.js:404:14636)
    at y.Mixin._createContentMarkup (http://graylog:9000/vendor.js:403:24339)
    at y.Mixin.mountComponent (http://graylog:9000/vendor.js:403:23239)
    at Object.a.mountComponent (http://graylog:9000/vendor.js:12:31712)
    at y.v.Mixin.mountChildren (http://graylog:9000/vendor.js:404:14636)
    at y.Mixin._createContentMarkup (http://graylog:9000/vendor.js:403:24339)
    at y.Mixin.mountComponent (http://graylog:9000/vendor.js:403:23239)
    at Object.a.mountComponent (http://graylog:9000/vendor.js:12:31712)
    at y.v.Mixin.mountChildren (http://graylog:9000/vendor.js:404:14636)
    at y.Mixin._createContentMarkup (http://graylog:9000/vendor.js:403:24339)
    at y.Mixin.mountComponent (http://graylog:9000/vendor.js:403:23239)
    at Object.a.mountComponent (http://graylog:9000/vendor.js:12:31712)
    at y.v.Mixin.mountChildren (http://graylog:9000/vendor.js:404:14636)
    at y.Mixin._createContentMarkup (http://graylog:9000/vendor.js:403:24339)
    at y.Mixin.mountComponent (http://graylog:9000/vendor.js:403:23239)
    at Object.a.mountComponent (http://graylog:9000/vendor.js:12:31712)
    at y.mountComponent (http://graylog:9000/vendor.js:403:7843)
    at i [as mountComponent] (http://graylog:9000/vendor.js:12:18757)
    at Object.a.mountComponent (http://graylog:9000/vendor.js:12:31712)
    at y.v.Mixin.mountChildren (http://graylog:9000/vendor.js:404:14636)
    at y.Mixin._createContentMarkup (http://graylog:9000/vendor.js:403:24339)
    at y.Mixin.mountComponent (http://graylog:9000/vendor.js:403:23239)
    at Object.a.mountComponent (http://graylog:9000/vendor.js:12:31712)
    at y.mountComponent (http://graylog:9000/vendor.js:403:7843)

**Comment by perbly** [comment]
I found the issue. Apparently i had one input that missed some information. 


backend    : nxlog
type       : file
name       : iis_w3svc5
properties : @{poll_interval=1; save_position=True; read_last=True; recursive=True; rename_check=False; multiline=False
             ; multiline_start=/^-./; path=C:\\inetpub\\logs\\LogFiles\\W3SVC5\\u_ex*}
input_id   : 573b9128ff52ed9fa0a43fc0
forward_to : 572bb8a9ff52ed9fa0939b79

backend    :
type       :
name       : iis_w3svc6
properties :
input_id   : 573b9136ff52ed9fa0a43fd0
forward_to :

backend    : nxlog
type       : file
name       : iis_w3svc7
properties : @{poll_interval=1; save_position=True; read_last=True; recursive=True; rename_check=False; multiline=False
             ; multiline_start=/^-./; path=C:\\inetpub\\logs\\LogFiles\\W3SVC7\\u_ex*}
input_id   : 573b9145ff52ed9fa0a43fe1
forward_to : 572bb8a9ff52ed9fa0939b79


When i created the inputs i must have added a input wrong in some way.
I remove the input using the restAPI and now it works perfectly.
I tried to reproduce the problem and added a input without type but i got an expected error so i´m not sure how that input could be created. I created the input using 2.0.0 and upgraded to 2.0.1 so maybe the validation is fixed in 2.0.1.

Thanks anyway.

**Comment by dennisoelkers** [comment]
Thanks for the heads up. I am glad you were able to solve your problem on your own and get back to a working state, but the scenario you described seems to trigger a minor issue in the UI code, so I am reopening the issue.

**Comment by edmundoa** [comment]
@perbly did you create the inputs using the REST API? I was able to reproduce the issue by creating an input that uses a non-existing output. I could only do that by using the REST API, that's why I was wondering.

**Comment by edmundoa** [comment]
This was fixed in Graylog2/graylog-plugin-collector#7
