### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by eroji** [Graylog2/graylog2-server#2256]
### Problem description
Unable to start Graylog 2.0.1 on CentOS 6.7 server
### Steps to reproduce the problem

1. Installed Graylog 2.0.1 on CentOS 6.7 server
2. Tried to start Graylog via graylogctl

### Environment

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2
* Operating System: CentOS 6.7
* Browser version:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/graylog2/bootstrap/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by supahgreg** [comment]
Make sure you're using Java 8 ([reference](http://docs.graylog.org/en/2.0/pages/installation.html)).

**Comment by joschi** [comment]
As @supahgreg already mentioned, Graylog 2.x requires Java 8 or higher to run.
