### ISSUE TITLE
Login checks LDAP before local user accounts

### ISSUE THREAD

**Issue by mayrstefan** [Graylog2/graylog2-server#2267]
### Problem description

Graylog is connected to an LDAP-Server. When we login as local administrator (xyz-admin) a ldap user account sync tried for a non-ldap account
1. When a ldap user with the same name is created this might create issues (does this user become a graylog administrator?)
2. Unnecessary exceptions fill the logfile:

```
2016-05-20 10:20:26,104 ERROR: org.graylog2.security.realm.LdapUserAuthenticator - Error during LDAP user account sync. Cannot log in user xyz-admin
java.lang.RuntimeException: ERR_02002_FAILURE_ON_UNDERLYING_CURSOR Failure on underlying Cursor
...
Caused by: org.apache.directory.api.ldap.model.cursor.CursorLdapReferralException
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:164) ~[graylog.jar:?]
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:50) ~[graylog.jar:?]
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:80) ~[graylog.jar:?]
        ... 36 more
```
### Steps to reproduce the problem
1. Install Graylog
2. Configure LDAP
3. Login with root_username defined in graylog.conf
### Environment
- Graylog Version: 2.0.1
- Elasticsearch Version: 2.3.2
- MongoDB Version: 3.2.6
- Operating System: SLES11 SP4
- Browser version: FF 38 / IE 11

**Comment by rkoens** [comment]
I am seeing the same behavior. We use a local account for our zabbix monitoring. The logs get spammed with the following error every few minutes.


`2016-06-14_07:07:47.73585 2016-06-14 09:07:47,695 ERROR: org.graylog2.security.realm.LdapUserAuthenticator - Error during LDAP user account sync. Cannot log in user haproxy
2016-06-14_07:07:47.73644 java.lang.RuntimeException: ERR_02002_FAILURE_ON_UNDERLYING_CURSOR Failure on underlying Cursor.
2016-06-14_07:07:47.73723       at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:86) ~[graylog.jar:?]
2016-06-14_07:07:47.73964       at org.graylog2.security.ldap.LdapConnector.search(LdapConnector.java:139) ~[graylog.jar:?]
2016-06-14_07:07:47.74015       at org.graylog2.security.realm.LdapUserAuthenticator.doGetAuthenticationInfo(LdapUserAuthenticator.java:96) [graylog.jar:?]
2016-06-14_07:07:47.74069       at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:568) [graylog.jar:?]
2016-06-14_07:07:47.74135       at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:219) [graylog.jar:?]
2016-06-14_07:07:47.74390       at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269) [graylog.jar:?]
2016-06-14_07:07:47.74885       at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) [graylog.jar:?]
2016-06-14_07:07:47.74938       at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) [graylog.jar:?]
2016-06-14_07:07:47.74991       at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270) [graylog.jar:?]
2016-06-14_07:07:47.75061       at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256) [graylog.jar:?]
2016-06-14_07:07:47.75152       at org.graylog2.shared.security.ShiroSecurityContext.loginSubject(ShiroSecurityContext.java:98) [graylog.jar:?]
2016-06-14_07:07:47.75277       at org.graylog2.shared.security.ShiroAuthenticationFilter.filter(ShiroAuthenticationFilter.java:48) [graylog.jar:?]
2016-06-14_07:07:47.75325       at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132) [graylog.jar:?]
2016-06-14_07:07:47.75376       at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) [graylog.jar:?]
2016-06-14_07:07:47.75450       at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) [graylog.jar:?]
2016-06-14_07:07:47.75600       at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318) [graylog.jar:?]
2016-06-14_07:07:47.75805       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
2016-06-14_07:07:47.75851       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
2016-06-14_07:07:47.75903       at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
2016-06-14_07:07:47.75983       at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
2016-06-14_07:07:47.76193       at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
2016-06-14_07:07:47.76402       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
2016-06-14_07:07:47.76447       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
2016-06-14_07:07:47.76771       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
2016-06-14_07:07:47.76866       at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
2016-06-14_07:07:47.76937       at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
2016-06-14_07:07:47.77021       at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
2016-06-14_07:07:47.77146       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_77]
2016-06-14_07:07:47.77236       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_77]
2016-06-14_07:07:47.77463       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
2016-06-14_07:07:47.77471 Caused by: org.apache.directory.api.ldap.model.cursor.CursorLdapReferralException
2016-06-14_07:07:47.77616       at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:164) ~[graylog.jar:?]
2016-06-14_07:07:47.77659       at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:50) ~[graylog.jar:?]
2016-06-14_07:07:47.78278       at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:80) ~[graylog.jar:?]
2016-06-14_07:07:47.78279       ... 29 more
`

**Steps to reproduce the problem**

1. Install Graylog
2. Configure LDAP
3. Login with any local user

**Environment**

- Graylog Version: 2.0.2
- Elasticsearch Version: 2.3.2
- MongoDB Version: 3.2.5
- Operating System: OVA Appliance (ubuntu)

**Comment by sandervanburken** [comment]
This is still an issue on graylog 2.4.3 on Ubuntu 16.04.4 LTS.

**Comment by ivazqueza** [comment]
It's happening too in graylog 2.4.6 on Debian Stretch

**Comment by pkaroluk** [comment]
It still occur in v2.5.1, are you going to fix it in graylog v3.x ?

**Comment by edmundoa** [comment]
Did you try changing the default Authentication Provider order? You can already configure which authentication method should be used first:

![authentication-providers](https://user-images.githubusercontent.com/716185/52353975-dcef2380-2a2f-11e9-97e8-fb638ed0ab6e.gif)

**Comment by coffee-squirrel** [comment]
We're seeing this (with a local user for Prometheus) in 3.1.4 and 3.2.4, both of which have LDAP/AD last.

```
{
  "realm_order": [
    "mongodb-session",
    "access-token",
    "mongodb-password",
    "root-user",
    "legacy-ldap"
  ],
  "disabled_realms": []
}
```

```
2020-04-16T10:45:04.234-05:00 ERROR [LdapUserAuthenticator] Error during LDAP user account sync. Cannot log in user prometheus_prod
java.lang.RuntimeException: ERR_02002_FAILURE_ON_UNDERLYING_CURSOR Failure on underlying Cursor.
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:89) ~[graylog.jar:?]
        at org.graylog2.security.ldap.LdapConnector.search(LdapConnector.java:142) ~[graylog.jar:?]
        at org.graylog2.security.realm.LdapUserAuthenticator.searchLdapUser(LdapUserAuthenticator.java:160) ~[graylog.jar:?]
        at org.graylog2.security.realm.LdapUserAuthenticator.doGetAuthenticationInfo(LdapUserAuthenticator.java:110) [graylog.jar:?]
        at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:571) [graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:219) [graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269) [graylog.jar:?]
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) [graylog.jar:?]
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) [graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:274) [graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:260) [graylog.jar:?]
        at org.graylog2.shared.security.ShiroSecurityContext.loginSubject(ShiroSecurityContext.java:107) [graylog.jar:?]
        at org.graylog2.shared.security.ShiroAuthenticationFilter.filter(ShiroAuthenticationFilter.java:48) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: org.apache.directory.api.ldap.model.cursor.CursorLdapReferralException
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:174) ~[graylog.jar:?]
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:52) ~[graylog.jar:?]
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:82) ~[graylog.jar:?]
        ... 30 more
```

**Comment by mayrstefan** [comment]
This happens in org.graylog2.shared.security: subject.login(authToken);

To reproduce:
- create a local user
- reorder realms: move ldap to the end
- enable and configure ldap against a non existing ldap server (e.g. localhost:389)
- login with the created user

Expected:
- no ldap connection is made
- the user logs in successfully

When we change the log level for Shiro to TRACE we find the following in the logs when we (successfully) log in with a local account:

```2020-04-19 01:26:04,609 TRACE: org.apache.shiro.session.mgt.DefaultSessionManager - Creating session for host 127.0.0.1
2020-04-19 01:26:04,609 DEBUG: org.apache.shiro.session.mgt.DefaultSessionManager - Creating new EIS record for new session instance [org.apache.shiro.session.mgt.SimpleSession,id=null]
2020-04-19 01:26:04,613 TRACE: org.apache.shiro.util.ThreadContext - get() - in thread [http-worker-0]
2020-04-19 01:26:04,613 TRACE: org.apache.shiro.subject.support.DelegatingSubject - attempting to get session; create = false; session is null = false; session has id = true
2020-04-19 01:26:04,613 TRACE: org.apache.shiro.authc.AbstractAuthenticator - Authentication attempt received for token [org.graylog2.shared.security.ActorAwareUsernamePasswordToken - demouser, rememberMe=false]
2020-04-19 01:26:04,613 TRACE: org.apache.shiro.authc.pam.ModularRealmAuthenticator - Iterating through 5 realms for PAM authentication
2020-04-19 01:26:04,614 DEBUG: org.apache.shiro.authc.pam.ModularRealmAuthenticator - Realm [org.graylog2.security.realm.SessionAuthenticator@6eb84dbb] does not support token org.graylog2.shared.security.ActorAwareUsernamePasswordToken -
 demouser, rememberMe=false.  Skipping realm.
2020-04-19 01:26:04,614 DEBUG: org.apache.shiro.authc.pam.ModularRealmAuthenticator - Realm [org.graylog2.security.realm.AccessTokenAuthenticator@77ea8eda] does not support token org.graylog2.shared.security.ActorAwareUsernamePasswordTok
en - demouser, rememberMe=false.  Skipping realm.
2020-04-19 01:26:04,614 TRACE: org.apache.shiro.authc.pam.ModularRealmAuthenticator - Attempting to authenticate token [org.graylog2.shared.security.ActorAwareUsernamePasswordToken - demouser, rememberMe=false] using realm [org.graylog2.se
curity.realm.RootAccountRealm@7c4da9bb]
2020-04-19 01:26:04,614 DEBUG: org.apache.shiro.realm.AuthenticatingRealm - Looked up AuthenticationInfo [null] from doGetAuthenticationInfo
2020-04-19 01:26:04,615 DEBUG: org.apache.shiro.realm.AuthenticatingRealm - No AuthenticationInfo found for submitted AuthenticationToken [org.graylog2.shared.security.ActorAwareUsernamePasswordToken - demouser, rememberMe=false].  Returni
ng null.
2020-04-19 01:26:04,615 TRACE: org.apache.shiro.authc.pam.ModularRealmAuthenticator - Attempting to authenticate token [org.graylog2.shared.security.ActorAwareUsernamePasswordToken - demouser, rememberMe=false] using realm [org.graylog2.se
curity.realm.PasswordAuthenticator@2f389f27]
2020-04-19 01:26:04,617 DEBUG: org.apache.shiro.realm.AuthenticatingRealm - Looked up AuthenticationInfo [demouser] from doGetAuthenticationInfo
2020-04-19 01:26:04,617 DEBUG: org.apache.shiro.realm.AuthenticatingRealm - AuthenticationInfo caching is disabled for info [demouser].  Submitted token: [org.graylog2.shared.security.ActorAwareUsernamePasswordToken - demouser, rememberMe=fa
lse].
2020-04-19 01:26:04,716 TRACE: org.apache.shiro.authc.pam.ModularRealmAuthenticator - Attempting to authenticate token [org.graylog2.shared.security.ActorAwareUsernamePasswordToken - demouser, rememberMe=false] using realm [org.graylog2.se
curity.realm.LdapUserAuthenticator@373bb0ce]
2020-04-19 01:26:04,769 INFO : org.apache.directory.api.ldap.codec.osgi.DefaultLdapCodecService - Registered pre-bundled control factory: 1.3.6.1.4.1.18060.0.0.1
2020-04-19 01:26:04,770 INFO : org.apache.directory.api.ldap.codec.osgi.DefaultLdapCodecService - Registered pre-bundled control factory: 2.16.840.1.113730.3.4.7
...
2020-04-19 01:26:04,782 INFO : org.apache.directory.api.ldap.codec.standalone.CodecFactoryUtil - Registered pre-bundled extended operation factory: 1.3.6.1.4.1.1466.20037
2020-04-19 01:26:06,800 ERROR: org.graylog2.security.ldap.LdapConnector - Timed out connecting to LDAP server
com.google.common.util.concurrent.UncheckedTimeoutException: java.util.concurrent.TimeoutException
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:140) ~[graylog.jar:?]
...
2020-04-19 01:26:06,809 DEBUG: org.apache.shiro.realm.AuthenticatingRealm - Looked up AuthenticationInfo [null] from doGetAuthenticationInfo
2020-04-19 01:26:06,809 DEBUG: org.apache.shiro.realm.AuthenticatingRealm - No AuthenticationInfo found for submitted AuthenticationToken [org.graylog2.shared.security.ActorAwareUsernamePasswordToken - demouser, rememberMe=false].  Returning null.
2020-04-19 01:26:06,809 DEBUG: org.apache.shiro.authc.AbstractAuthenticator - Authentication successful for token [org.graylog2.shared.security.ActorAwareUsernamePasswordToken - demouser, rememberMe=false].  Returned account [demouser]
2020-04-19 01:26:06,809 TRACE: org.apache.shiro.mgt.DefaultSecurityManager - Context already contains a SecurityManager instance.  Returning.
2020-04-19 01:26:06,809 TRACE: org.apache.shiro.subject.support.DelegatingSubject - attempting to get session; create = false; session is null = false; session has id = true
2020-04-19 01:26:06,809 DEBUG: org.apache.shiro.mgt.DefaultSecurityManager - Context already contains a session.  Returning.
2020-04-19 01:26:06,809 TRACE: org.apache.shiro.subject.support.DelegatingSubject - attempting to get session; create = false; session is null = false; session has id = true
2
```

We can see how Shiro iterates through all Realms until we get an LDAP exception on the last realm.

**Comment by mayrstefan** [comment]
After some research I think FirstSuccessfulStrategy.setStopAfterFirstSuccess(true) is necessary but I still can't get it to work

**Comment by mayrstefan** [comment]
Looks like [SHIRO-747](https://issues.apache.org/jira/browse/SHIRO-747) and [SHIRO-669](https://issues.apache.org/jira/browse/SHIRO-669) are relevant
