### ISSUE TITLE
graylog-2.0.1 org.elasticsearch.discovery.zen failed to send join request to master elasticsearch

### ISSUE THREAD

**Issue by pmanwatkar** [Graylog2/graylog2-server#2286]
### Problem description
Currently I am stuck on this error and can't figure out the issue in the configurations: 

```
2016-05-25 15:12:57,172 INFO : org.elasticsearch.discovery.zen - [graylog-89437135-dca9-4fcb-9f7f-2ac0dcaff810] failed to send join request to master [{ip-10-2-68-102}{uD1duJ_lToG5Qns60QrHRQ}{10.2.68.102}{10.2.68.102:9300}{aws_availability_zone=us-west-2a, master=true}], reason [RemoteTransportException[[ip-10-2-68-102][10.2.68.102:9300][internal:discovery/zen/join]]; nested: ConnectTransportException[[graylog-89437135-dca9-4fcb-9f7f-2ac0dcaff810][127.0.0.1:9350] connect_timeout[30s]]; nested: NotSerializableExceptionWrapper[connect_exception: Connection refused: /127.0.0.1:9350]; ]
```

### Steps to reproduce the problem

Graylog server: 10.2.93.6
Elasticsearch: 10.2.68.102

graylog-server.conf::
```
is_master = true
node_id_file = /etc/graylog/server/node-id
password_secret = XXXXXXXXXXXXXXX
root_username = admin
root_password_sha2 = YXXXXXXXXXXXXXXXY
plugin_dir = plugin
rest_listen_uri = http://0.0.0.0:12900/
web_listen_uri = http://0.0.0.0:9000/
web_enable_cors = false
rotation_strategy = time
elasticsearch_max_time_per_index = 3d
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 2
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = true
allow_highlighting = false
elasticsearch_cluster_name = graylog
elasticsearch_discovery_zen_ping_unicast_hosts = 10.2.68.102:9300
elasticsearch_discovery_zen_ping_multicast_enabled = false
elasticsearch_cluster_discovery_timeout = 5000
elasticsearch_discovery_initial_state_timeout = 15s
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = data/journal
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://mongodb.test.com:27017/db1
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
content_packs_auto_load = grok-patterns.json
```

elasticsearch.yml
```
cluster.name: graylog
node.master: true
node.data: true
index.number_of_shards: 2
index.number_of_replicas: 0
index.replication: async
index.refresh_interval: 30s
path.data: /var/lib/elasticsearch/data-0, /var/lib/elasticsearch/data-1
path.logs: /var/lib/elasticsearch/logs
bootstrap.mlockall: true
ES_HEAP_SIZE: 3g
MAX_LOCKED_MEMORY: unlimited
transport.tcp.compress: true
http.compression: true
http.cors.enabled: true
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["10.2.68.102:9300"]
discovery.type: ec2
discovery.ec2.host_type: private_ip
discovery.ec2.ping_timeout: 5s
cloud.aws.region:  us-east-1
discovery.ec2.tag.Role:  haystack-es
jmx.create_connector: true
jmx.port: 1099
jmx.domain: elasticsearch
index.search.slowlog.level: DEBUG
index.search.slowlog.threshold.query.warn: 10s
index.search.slowlog.threshold.query.info: 5s
index.search.slowlog.threshold.query.debug: 2s
index.search.slowlog.threshold.query.trace: 500ms
index.search.slowlog.threshold.fetch.warn: 1s
index.search.slowlog.threshold.fetch.info: 800ms
index.search.slowlog.threshold.fetch.debug: 500ms
index.search.slowlog.threshold.fetch.trace: 200ms
index.indexing.slowlog.level: DEBUG
index.indexing.slowlog.threshold.index.warn: 10s
index.indexing.slowlog.threshold.index.info: 5s
index.indexing.slowlog.threshold.index.debug: 2s
index.indexing.slowlog.threshold.index.trace: 500ms
node.name: ${HOSTNAME}
network.bind_host: 0.0.0.0
network.host: 10.2.68.102
cloud.node.auto_attributes: true
cluster.routing.allocation.awareness.attributes: aws_availability_zone
```

Port open on graylog-server:
```
# netstat -nlp|grep 6355
tcp6       0      0 :::12900                :::*                    LISTEN      6355/java           
tcp6       0      0 127.0.0.1:9350          :::*                    LISTEN      6355/java           
tcp6       0      0 ::1:9350                :::*                    LISTEN      6355/java           
tcp6       0      0 :::9000                 :::*                    LISTEN      6355/java   
```

Ports open on elasticsearch server:
```
# netstat -nlp|grep 8092
tcp        0      0 :::9200                     :::*                        LISTEN      8092/java           
tcp        0      0 :::9300                     :::*                        LISTEN      8092/java    
```

Let me know if I need some more info to provide.

### Environment

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.0.2-1.amzn1
* Operating System: graylog on centos-el7.x86_64 | elasticsearch on 4.4.10-22.54.amzn1.x86_64
* Browser version: Chrome 50.0.2661.102

**Comment by joschi** [comment]
@pmanwatkar Make sure that [`elasticsearch_network_host`](https://github.com/Graylog2/graylog2-server/blob/2.0.1/misc/graylog.conf#L245-L250) has been set to the public/external IP address of the EC2 instance (e. g. `10.2.93.6` in your case).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by pmanwatkar** [comment]
@joschi After adding elasticsearch_network_host in graylog-server.conf, I am getting this error: 
```
2016-05-25 15:49:02,883 WARN : org.elasticsearch.transport.netty - [graylog-89437135-dca9-4fcb-9f7f-2ac0dcaff810] exception caught on transport layer [[id: 0xd19da7b2, /10.2.68.102:33772 => /10.2.93.6:9350]], closing connection
java.lang.IllegalStateException: Message not fully read (request) for requestId [1829], action [internal:discovery/zen/join/validate], readerIndex [7039] vs expected [7039]; resetting
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:121) ~[graylog.jar:?]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [graylog.jar:?]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [graylog.jar:?]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) [graylog.jar:?]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) [graylog.jar:?]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) [graylog.jar:?]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [graylog.jar:?]
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [graylog.jar:?]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [graylog.jar:?]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [graylog.jar:?]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [graylog.jar:?]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2016-05-25 15:49:02,886 INFO : org.elasticsearch.discovery.zen - [graylog-89437135-dca9-4fcb-9f7f-2ac0dcaff810] failed to send join request to master [{ip-10-2-68-102}{uD1duJ_lToG5Qns60QrHRQ}{10.2.68.102}{10.2.68.102:9300}{aws_availability_zone=us-west-2a, master=true}], reason [RemoteTransportException[[ip-10-2-68-102][10.2.68.102:9300][internal:discovery/zen/join]]; nested: IllegalStateException[failure when sending a validation request to node]; nested: RemoteTransportException[[graylog-89437135-dca9-4fcb-9f7f-2ac0dcaff810][10.2.93.6:9350][internal:discovery/zen/join/validate]]; nested: IllegalArgumentException[No custom metadata prototype registered for type [licenses], node like missing plugins]; ]
```

Referring to: https://discuss.elastic.co/t/updated-to-2-2-0-and-now-seeing-message-not-fully-read-request/41105

It may be due to conflicts in ES server and client version. 
What version of elasticsearch client is getting used in graylog-2.0.1 ?
I am using elasticsearch server of v2.3.3.

**Comment by pmanwatkar** [comment]
Thanks for the help @joschi . It seems that many after removing elasticsearch plugins: license, watchers and marvel-agent the graylog server can now connect to elasticsearch.

**Comment by marcinkubica** [comment]
@joschi this is actuall bug. Elasticsearch is not allowing clients without license plugin to join the cluster. 

This means you can't use your freebee elastic with Marvel, neither properly supported elasticsearch cluster in the enterprise envinorement.

Funny tho once you remove license plugin, graylog is added, and then you can install license plugin as well. But this is hardly a solution.

**Comment by skubis** [comment]
There's a simple solution (for graylog-server 2.1.1): 

copy the directory /usr/share/elasticsearch/plugins to the graylog-server /usr/share/graylog-server/els.plugins

change directory to /usr/share/graylog-server/els.plugins

inside this directory you see the folders "licence" and "marvel-agent"
change directroy to license
delete following files:
license-*.jar
license-plugin-api-*.jar
license-core-*.jar

download following files:
https://maven.elasticsearch.org/public-releases/org/elasticsearch/plugin/license/2.3.5/license-2.3.5.jar
https://maven.elasticsearch.org/releases/org/elasticsearch/license-plugin-api/2.3.5/license-plugin-api-2.3.5.jar
https://maven.elasticsearch.org/releases/org/elasticsearch/license-core/2.3.5/license-core-2.3.5.jar

edit file plugin-descriptor.properties
change following: 
version=xxxx to version=2.3.5
elasticsearch.version=xxx to elasticsearch.version=2.3.5

change directory to marvel-agent

delete marvel-agent-*.jar
Download the following: 
https://maven.elasticsearch.org/public-releases/org/elasticsearch/plugin/marvel-agent/2.3.5/marvel-agent-2.3.5.jar

again edit file plugin-descriptor.properties
change following: 
version=xxxx to version=2.3.5
elasticsearch.version=xxx to elasticsearch.version=2.3.5

edit file /etc/graylog/server/server.conf
uncomment elasticsearch_config_file = /etc/graylog/server/elasticsearch.yml
copy elasticsearch.yml from an elasticsearch instance to the graylog-server /etc/graylog/server/elasticsearch.yml

edit elasticsearch.yml
change the following:

node.name: graylog-nodexx
path.plugins: /usr/share/graylog-server/els.plugins
node.master: false
node.data: false
bootstrap.mlockall: false

restart graylog-server and watch the logfile

**Comment by 123dev** [comment]
Would this work with Elasticsearch 2.4.1 ?
On the surface it appears to, however, the Elasticsearch cluster every now and then disappears from being detected by Graylog.
```Elasticsearch cluster unavailable```

Thanks
