### ISSUE TITLE
Error log: The buffer cannot hold more than 500 objects.

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#2302]
This error appears in my `graylog-server` (on current `2.0` branch state) log:

```
2016-05-28 15:28:35,699 Service Thread ERROR An exception occurred processing Appender graylog-internal-logs org.apache.commons.collections.BufferOverflowException: The buffer cannot hold more than 500 objects.
	at org.apache.commons.collections.buffer.BoundedFifoBuffer.add(BoundedFifoBuffer.java:237)
	at org.apache.commons.collections.buffer.CircularFifoBuffer.add(CircularFifoBuffer.java:93)
	at org.graylog2.log4j.MemoryAppender.append(MemoryAppender.java:76)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:152)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:125)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:116)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:378)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:362)
	at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:384)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:379)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:362)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:352)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:147)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1022)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:980)
	at org.apache.logging.slf4j.Log4jLogger.warn(Log4jLogger.java:253)
	at org.graylog2.periodical.GarbageCollectionWarningThread$1.handleNotification(GarbageCollectionWarningThread.java:130)
	at sun.management.NotificationEmitterSupport.sendNotification(NotificationEmitterSupport.java:156)
	at sun.management.GarbageCollectorImpl.createGCNotification(GarbageCollectorImpl.java:147)
```

It might be that an upgrade of the `apache-commons` library caused this exception to be thrown. This did not happen in <2.0 versions.

**Comment by kroepke** [comment]
This has been backported to 2.0.3 but not released yet.
