### ISSUE TITLE
Cannot get Messages with offset < 10000 via api

### ISSUE THREAD

**Issue by nabl13** [Graylog2/graylog2-server#2306]
### Problem description
When i try to get 5 Messages with offset 10000 it fails with error:
```
{
  "query": "facility:TEST",
  "begin_column": null,
  "begin_line": null,
  "end_column": null,
  "end_line": null,
  "message": "Unable to execute search",
  "exception_name": "org.elasticsearch.action.search.SearchPhaseExecutionException"
}
```
In graylog this error can be found in logfiles:
```
WARN  [SearchResource] Unable to execute search: all shards failed
```
When i try the same search with offset 9995 im getting 5 Messages, so  the error occurs exactly at 10000 Messages, thats why i guess its this setting from elasticsearch:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html

The Api call is successful if requested as text/csv. So this should be possible through elasticsearch somehow.

### Steps to reproduce the problem

In Swagger under "GET /search/universal/absolute"
define query and time frame with more than 10000 results,
enter 10000 as offset and for example 5 as limit.

### Environment

* Graylog Version: 2.0.2
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.0.12
* Operating System: CentOS release 6.7 (Final)
* Browser version: Chrome 50.0.2661.94 m

**Comment by joschi** [comment]
@nabl13 Please post the complete error/warning message from the logs of your Graylog node(s), including some context.

**Comment by nabl13** [comment]
@joschi This is the only Log Message:
2016-05-30T11:10:49.955+02:00 WARN  [SearchResource] Unable to execute search: all shards failed
In Debug mode there is a bit more:

2016-05-30T11:20:29.383+02:00 DEBUG [search] [graylog-88c17108-31dc-44f6-a90a-182e44f391b3] [graylog2_431][5], node[z-eph3TgRaesZstK_CYKOA], [R], v[3], s[STARTED], a[id=9dnordyoQVOmetk8yz1u6g]: Failed to exe
cute [org.elasticsearch.action.search.SearchRequest@463b305] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [Katherine "Kitty" Pryde][xx.xx.xx.xx:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Result window is too large, from + size must be less than or equal to: [10000] but was [10005]. See the scroll api for a more efficient
 way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.
        at org.elasticsearch.search.internal.DefaultSearchContext.preProcess(DefaultSearchContext.java:212) ~[graylog.jar:?]
        at org.elasticsearch.search.query.QueryPhase.preProcess(QueryPhase.java:103) ~[graylog.jar:?]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:676) ~[graylog.jar:?]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:620) ~[graylog.jar:?]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:371) ~[graylog.jar:?]
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368) ~[graylog.jar:?]
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365) ~[graylog.jar:?]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[graylog.jar:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75) ~[graylog.jar:?]
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300) ~[graylog.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by dennisoelkers** [comment]
Basically the exception says it all. You need to increase the `max_result_window` size for your index/indices. You will find all the info you need here: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html

I am wondering if there is anything we can from Graylog's side to support you. We could switch to the Scroll API for fetching search results, but it is actually a bit clumsy and queries like yours with either a very high offset or very high result size (or a combination of both) are rather uncommon and undesirable.

I am closing this for now, as it might already help solving your issue, but if you still think we should do something from our side, you should elaborate a bit on your specific use case and why it might be more common than we think.
