### ISSUE TITLE
Feature request: Support compressed GELF Kafka payload

### ISSUE THREAD

**Issue by jsmucr** [Graylog2/graylog2-server#2308]
It would be great to support compressed GELF Kafka payload.

Currently it's possible to receive only plain text GELF messages through the Kafka input. Passing a GZIPped message makes Graylog throw exceptions such as

```
2016-05-26 13:45:27,122 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=1a896c10-2348-11e6-a9c4-0242ac120008, journalOffset=82735, codec=gelf, payloadSize=277, timestamp=2016-05-26T13:45:27.121Z}
java.lang.IllegalStateException: Unknown GELF type. Not supported.
    at org.graylog2.inputs.codecs.gelf.GELFMessage.getJSON(GELFMessage.java:62) ~[graylog.jar:?]
    at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:110) ~[graylog.jar:?]
    at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136) ~[graylog.jar:?]
...
```

This feature would be useful as it's pretty common to send GELF encoded messages compressed and implementing Kafka may force system administrator to reconfigure all monitored applications (where even possible).

**Comment by rich-graylog** [comment]
Issue cleanup - closing dormant issue
