### ISSUE TITLE
can't parse nginx logs

### ISSUE THREAD

**Issue by tsgan** [Graylog2/graylog2-server#2332]
### Problem description
graylog-2.0.2-1 can not parse nginx log.
### Steps to reproduce the problem
nginx is configured:
```
log_format  graylog_format  '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" <msec=$msec|connection=$connection|connection_requests=$connection_requests|millis=$request_time>';
access_log syslog:server=192.168.0.110:12201 graylog_format;
error_log syslog:server=192.168.0.110:12201;
```
graylog error:
```
2016-06-03_07:29:37.83076 2016-06-03 07:29:37,830 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Unable to decode raw message ed6a3730-295c-11e6-bebc-000c292c2cea (journal offset 9540) encoded as gelf received from unknown source.
2016-06-03_07:29:37.83329 2016-06-03 07:29:37,832 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=ed6a3730-295c-11e6-bebc-000c292c2cea, journalOffset=9540, codec=gelf, payloadSize=279, timestamp=2016-06-03T07:29:37.827Z}
2016-06-03_07:29:37.83597 com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
2016-06-03_07:29:37.83802  at [Source: <190>Jun  3 16:29:37 bsd3 nginx: 192.168.0.104 - - [03/Jun/2016:16:29:37 +0900] "GET /test/test.html HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0" "-" <msec=1464938977.746|connection=1|connection_requests=1|millis=0.000>; line: 1, column: 2]
2016-06-03_07:29:37.83866 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581) ~[graylog.jar:?]
2016-06-03_07:29:37.84635 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533) ~[graylog.jar:?]
2016-06-03_07:29:37.84797 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462) ~[graylog.jar:?]
2016-06-03_07:29:37.84938 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1624) ~[graylog.jar:?]
2016-06-03_07:29:37.85090 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689) ~[graylog.jar:?]
2016-06-03_07:29:37.85210 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3771) ~[graylog.jar:?]
2016-06-03_07:29:37.85481 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3716) ~[graylog.jar:?]
2016-06-03_07:29:37.85619 	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2272) ~[graylog.jar:?]
2016-06-03_07:29:37.85712 	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:115) ~[graylog.jar:?]
2016-06-03_07:29:37.86582 	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136) ~[graylog.jar:?]
2016-06-03_07:29:37.86781 	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82) [graylog.jar:?]
2016-06-03_07:29:37.86843 	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58) [graylog.jar:?]
2016-06-03_07:29:37.86949 	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
2016-06-03_07:29:37.87158 	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139) [graylog.jar:?]
2016-06-03_07:29:37.87278 	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
2016-06-03_07:29:37.87279 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
2016-06-03_07:29:37.91921 2016-06-03 07:29:37,918 ERROR: org.graylog2.inputs.codecs.GelfCodec - Could not parse JSON, first 400 characters: <190>Jun  3 16:29:37 bsd3 nginx: 192.168.0.104 - - [03/Jun/2016:16:29:37 +0900] "GET /test/flot/examples/examples.css HTTP/1.1" 304 0 "http://192.168.0.87/test/test.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0" "-" <msec=1464938977.836|connection=1|connection_requests=2|millis=0.000>
2016-06-03_07:29:37.92026 com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
2016-06-03_07:29:37.92051  at [Source: <190>Jun  3 16:29:37 bsd3 nginx: 192.168.0.104 - - [03/Jun/2016:16:29:37 +0900] "GET /test/flot/examples/examples.css HTTP/1.1" 304 0 "http://192.168.0.87/test/test.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0" "-" <msec=1464938977.836|connection=1|connection_requests=2|millis=0.000>; line: 1, column: 2]
```

### Environment
graylog-2.0.2-1 ova

* Graylog Version: 
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@tsgan You're trying to send syslog messages (according to your nginx configuration) to a Graylog GELF input (according to the error message).

You have to use a syslog input in order to parse and process syslog messages.
