### ISSUE TITLE
Graylog Server Unhandled exception in REST resource: IndexNotFoundException

### ISSUE THREAD

**Issue by gitfrederic** [Graylog2/graylog2-server#2381]
Running Graylog 2.0.2 and ElasticSearch 2.3.2, i.e.

``` shell
...
16:47:02.100 [main] INFO  org.elasticsearch.node - [graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98] version[2.3.2], pid[5020], build[b9e4a6a/2016-04-21T16:03:47Z]
...
16:47:07.511 [main] INFO  org.graylog2.bootstrap.ServerBootstrap - Graylog server 2.0.2 (4da1379) starting up
16:47:07.511 [main] INFO  org.graylog2.bootstrap.ServerBootstrap - JRE: Oracle Corporation 1.8.0_72 on Linux 3.10.0-123.el7.x86_64
16:47:07.512 [main] INFO  org.graylog2.bootstrap.ServerBootstrap - Deployment: unknown
16:47:07.512 [main] INFO  org.graylog2.bootstrap.ServerBootstrap - OS: CentOS Linux 7 (Core) (centos)
16:47:07.512 [main] INFO  org.graylog2.bootstrap.ServerBootstrap - Arch: amd64
...
```

Found the following exception stack trace in the Graylog Server log:

``` shell
17:25:03.656 [rest-worker-14] ERROR org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
org.elasticsearch.index.IndexNotFoundException: no such index
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:585) ~[graylog.jar:?]
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:133) ~[graylog.jar:?]
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:113) ~[graylog.jar:?]
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.<init>(AbstractSearchAsyncAction.java:99) ~[graylog.jar:?]
    at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.<init>(SearchQueryThenFetchAsyncAction.java:53) ~[graylog.jar:?]
    at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:93) ~[graylog.jar:?]
    at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:47) ~[graylog.jar:?]
    at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:149) ~[graylog.jar:?]
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:137) ~[graylog.jar:?]
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85) ~[graylog.jar:?]
    at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58) ~[graylog.jar:?]
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359) ~[graylog.jar:?]
    at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52) ~[graylog.jar:?]
    at org.graylog2.indexer.elasticsearch.GlobalTimeoutClient.doExecute(GlobalTimeoutClient.java:58) ~[graylog.jar:?]
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359) ~[graylog.jar:?]
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348) ~[graylog.jar:?]
    at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:577) ~[graylog.jar:?]
    at org.graylog2.indexer.elasticsearch.GlobalTimeoutClient.search(GlobalTimeoutClient.java:64) ~[graylog.jar:?]
    at org.graylog2.indexer.counts.Counts.total(Counts.java:41) ~[graylog.jar:?]
    at org.graylog2.rest.resources.count.CountResource.total(CountResource.java:53) ~[graylog.jar:?]
    at org.graylog2.rest.resources.system.indexer.IndexerOverviewResource.index(IndexerOverviewResource.java:109) ~[graylog.jar:?]
    at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
    at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
    at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

Seems like it may be related to metric collection/instrumentation.

**Comment by joschi** [comment]
@gitfrederic Are there any error messages before the `IndexNotFoundException` you've posted?

**Comment by gitfrederic** [comment]
Nothing out of the ordinary:

```shell
16:49:38.055 [kafka-journal-scheduler-0] INFO  kafka.log.Log - Deleting segment 846292805 from log messagejournal-0.
16:49:38.078 [kafka-journal-scheduler-0] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846292805.index.deleted
16:49:38.078 [kafka-journal-scheduler-0] INFO  kafka.log.Log - Deleting segment 846365155 from log messagejournal-0.
16:49:38.079 [kafka-journal-scheduler-1] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846220934.index.deleted
16:49:38.098 [kafka-journal-scheduler-0] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846365155.index.deleted
16:50:37.586 [kafka-journal-scheduler-0] INFO  kafka.log.Log - Deleting segment 846505981 from log messagejournal-0.
16:50:37.586 [kafka-journal-scheduler-1] INFO  kafka.log.Log - Deleting segment 846435854 from log messagejournal-0.
16:50:37.611 [kafka-journal-scheduler-1] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846435854.index.deleted
16:50:37.611 [kafka-journal-scheduler-1] INFO  kafka.log.Log - Deleting segment 846575623 from log messagejournal-0.
16:50:37.612 [kafka-journal-scheduler-0] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846505981.index.deleted
16:50:37.613 [kafka-journal-scheduler-0] INFO  kafka.log.Log - Deleting segment 846645909 from log messagejournal-0.
16:50:37.632 [kafka-journal-scheduler-1] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846575623.index.deleted
16:50:37.632 [kafka-journal-scheduler-1] INFO  kafka.log.Log - Deleting segment 846716202 from log messagejournal-0.
16:50:37.633 [kafka-journal-scheduler-0] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846645909.index.deleted
16:50:37.633 [kafka-journal-scheduler-0] INFO  kafka.log.Log - Deleting segment 846786150 from log messagejournal-0.
16:50:37.652 [kafka-journal-scheduler-1] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846716202.index.deleted
16:50:37.653 [kafka-journal-scheduler-1] INFO  kafka.log.Log - Deleting segment 846859045 from log messagejournal-0.
16:50:37.654 [kafka-journal-scheduler-0] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846786150.index.deleted
16:50:37.655 [kafka-journal-scheduler-0] INFO  kafka.log.Log - Deleting segment 846927816 from log messagejournal-0.
16:50:37.673 [kafka-journal-scheduler-1] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846859045.index.deleted
16:50:37.674 [kafka-journal-scheduler-0] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000846927816.index.deleted
17:00:03.522 [elasticsearch[graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98][scheduler][T#1]] INFO  org.elasticsearch.monitor.jvm - [graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98] [gc][young][769][42] duration [757ms], collections [1]/[1.3s], total [757ms]/[17.3s], memory [5.1gb]->[3gb]/[11.7gb], all_pools {[young] [2.3gb]->[1.9mb]/[2.4gb]}{[survivor] [307.1mb]->[291mb]/[307.1mb]}{[old] [2.4gb]->[2.7gb]/[9gb]}
17:17:52.667 [elasticsearch[graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98][scheduler][T#1]] WARN  org.elasticsearch.monitor.jvm - [graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98] [gc][young][1837][43] duration [1s], collections [1]/[1.8s], total [1s]/[18.4s], memory [5.4gb]->[2.8gb]/[11.7gb], all_pools {[young] [2.3gb]->[630.5kb]/[2.4gb]}{[survivor] [291mb]->[99.7mb]/[307.1mb]}{[old] [2.7gb]->[2.7gb]/[9gb]}
17:25:03.656 [rest-worker-14] ERROR org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
org.elasticsearch.index.IndexNotFoundException: no such index
...
```

Here's another occurrence:
```shell
05:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
05:47:27.651 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
06:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
06:47:27.653 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
07:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
07:47:27.653 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
08:47:27.644 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
08:47:27.650 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
09:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
09:47:27.652 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
10:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
10:47:27.652 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
11:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
11:47:27.655 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
12:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
12:47:27.652 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
13:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
13:47:27.652 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
14:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
14:47:27.651 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
15:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
15:47:27.652 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
16:47:27.644 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
16:47:27.652 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
17:47:27.644 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
17:47:27.652 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
18:40:02.804 [rest-worker-0] ERROR org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
org.elasticsearch.index.IndexNotFoundException: no such index
...
```

The logs after the exceptions are equally uninteresting.

**Comment by joschi** [comment]
@gitfrederic Did you encounter this exception again since opening this issue and adding your last comment?

I couldn't reproduce the error, but from your logs it looks like the Java process suffered some longer GC pauses and the queried Elasticsearch indices (at least one of them) vanished while being the process was being paused, so that it couldn't be found when the actual request was being performed.
