### ISSUE TITLE
Unable to build the code of master on mac os 

### ISSUE THREAD

**Issue by prabhakar349** [Graylog2/graylog2-server#2401]
### Problem description

Unable to build the master branch code on mac OS

Haven maven 3.3.9  and git and Using STS 3.7

Any other special requirements I need to have ?

**Comment by edmundoa** [comment]
Hi,

Please also ensure you are using Java 8 to compile the project. Also, which errors do you see while compiling?

**Comment by prabhakar349** [comment]
Here is the error that I am getting:
```
[INFO] Compiling 1238 source files to /home/pd/git/graylog2-server/graylog2-server/target/classes
An exception has occurred in the compiler (1.8.0_91). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.IllegalStateException: endPosTable already set
	at com.sun.tools.javac.util.DiagnosticSource.setEndPosTable(DiagnosticSource.java:136)
	at com.sun.tools.javac.util.Log.setEndPosTable(Log.java:350)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:667)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:950)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:892)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:921)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1187)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:171)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:886)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] An unknown compilation problem occurred
```

**Comment by kroepke** [comment]
This is a known issue with the Java 8 compiler, where older class files confuse it. Most likely some changes in generic types are the reason.
Typically this happens when incremental compiling is turned on.

If this happens simply do a `mvn clean compile` and the error is gone.

**Comment by prabhakar349** [comment]
Yeah above  error is gone after ```mvn clean``` .

But my earlier problem is some of the test cases are failing when i do a mvn install

```
Running org.graylog2.rest.ValidationExceptionMapperTest
Tests run: 14, Failures: 7, Errors: 0, Skipped: 0, Time elapsed: 55.12 sec <<< FAILURE! - in org.graylog2.indexer.searches.SearchesTest
testHistogram(org.graylog2.indexer.searches.SearchesTest)  Time elapsed: 5.86 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected size:<5> but was:<1> in:
<{1420088400L=2L}>
	at org.graylog2.indexer.searches.SearchesTest.testHistogram(SearchesTest.java:305)

testTermsWithNonExistingIndex(org.graylog2.indexer.searches.SearchesTest)  Time elapsed: 3.655 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[10]L> but was:<[2]L>
	at org.graylog2.indexer.searches.SearchesTest.testTermsWithNonExistingIndex(SearchesTest.java:196)

testFieldHistogram(org.graylog2.indexer.searches.SearchesTest)  Time elapsed: 3.323 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected size:<5> but was:<1> in:
<{1420088400L={"cardinality"=0L, "count"=2L, "max"=4.0, "mean"=3.0, "min"=2.0, "total"=6.0, "total_count"=2L}}>
	at org.graylog2.indexer.searches.SearchesTest.testFieldHistogram(SearchesTest.java:373)

testCount(org.graylog2.indexer.searches.SearchesTest)  Time elapsed: 3.484 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[10]L> but was:<[2]L>
	at org.graylog2.indexer.searches.SearchesTest.testCount(SearchesTest.java:140)

testTerms(org.graylog2.indexer.searches.SearchesTest)  Time elapsed: 2.338 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[10]L> but was:<[2]L>
	at org.graylog2.indexer.searches.SearchesTest.testTerms(SearchesTest.java:164)

testFieldStats(org.graylog2.indexer.searches.SearchesTest)  Time elapsed: 2.263 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected size:<10> but was:<2> in:
<[org.graylog2.indexer.results.ResultMessage@44ccd75c,
    org.graylog2.indexer.results.ResultMessage@61a704d3]>
	at org.graylog2.indexer.searches.SearchesTest.testFieldStats(SearchesTest.java:266)

testHistogramWithNonExistingIndex(org.graylog2.indexer.searches.SearchesTest)  Time elapsed: 2.186 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected size:<5> but was:<1> in:
<{1420088400L=2L}>
	at org.graylog2.indexer.searches.SearchesTest.testHistogramWithNonExistingIndex(SearchesTest.java:338)

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.483 sec - in org.graylog2.rest.ValidationExceptionMapperTest
Running org.graylog2.configuration.MongoDbConfigurationTest
```

**Comment by kroepke** [comment]
I'm unsure what might cause those errors, they complete just fine for me as well as on travis and jenkins.
It shouldn't be related to timing issues, because these tests use specific dates and an embedded elasticsearch.

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
