### ISSUE TITLE
GELF Data from nxlog/collector-sidcar incorrectly parsed in 2.0.3

### ISSUE THREAD

**Issue by roxer2725** [Graylog2/graylog2-server#2411]
• Graylog Version: Graylog 2.0.3 ( f07c170 )
• Elasticsearch Version: 2.3.3-1
• MongoDB Version: 3.2.7-1.el7
• Operating System: Centos 7.0 (3.10.0-327.18.2.el7.x86_6)
• NXlog version:  nxlog-ce-2.9.1504/nxlog-ce-2.9.1504-1.rhel7.x86_64
• Graylog-Collector-Sidecar version: 0.0.8

**ISSUE:** Running a Centos 7.2 three host logging cluster behind a HAProxy server. Originally built using Graylog 2.0.2 from the rpm repo with no issues. Upgraded to 2.0.3 from same repo repository and now Graylog sees some of the GELF data (from Windows or Linux host) as binary and cannot parse. No changes were made to the hosts other than the update. Ran the update and restarted the services just to get the output below in the log file (/var/log/graylog-server/server.log):
```
2016-06-22T10:15:13.732-04:00 ERROR [GelfCodec] Could not parse JSON, first 400 characters: ���vb�      ����wxz�Tv��<�Q���u]?�I�        �z��
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('�' (code 65533 / 0xfffd)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: ���vb�   ����wxz�Tv��<�Q���u]?�I�  �z��; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1624) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonPars
[serverLog.zip](https://github.com/Graylog2/graylog2-server/files/330710/serverLog.zip)
er.java:689) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3771) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3716) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2272) ~[graylog.jar:?]
        at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:115) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
2016-06-22T10:15:13.732-04:00 ERROR [DecodingProcessor] Unable to decode raw message bc89d68a-3883-11e6-a89e-005056934db8 (journal offset 56420554) encoded as gelf received from /10.100.150.89:41076.
```
Thought it might be from HAProxy, so I pointed directly to a Graylog host and got the same issue. Tried with both a Linux and Windows host - Same issue. Built another cluster using 2.0.3-1 from scratch and tried the same test - same results.

Output to newly built 2.0.3 cluster:
```
2016-06-23T13:09:01.840-04:00 ERROR [GelfCodec] Could not parse JSON, first 400 characters: �$��D�Q�ݑ�/[�m��.   umv�6Ӭ�����5>btt��h�Rx��S]o�0�+V�Z�AvBȞ���
�����y��)歷�1ń��x�֌����W-�\�{0V�&��a�]��Nm�

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('�' (code 65533 / 0xfffd)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

 at [Source: �$��D�Q�ݑ�/[�m��.  umv�6Ӭ�����5>btt��h�Rx��S]o�0�+V�Z�AvBȞ���
�����y��)歷�1ń��x�֌����W-; line: 1, column: 2]

        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1624) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3771) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3716) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2272) ~[graylog.jar:?]
        at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:115) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]

2016-06-23T13:09:01.857-04:00 ERROR [DecodingProcessor] Unable to decode raw message 2e97f704-3965-11e6-b0e7-005056930c85 (journal offset 78064) encoded as gelf received from /10.100.1.10:61360.
```

**Comment by kroepke** [comment]
@mariussturm could you take a look please, to see if maybe defaults have changed (from json to gzip or something)? Thanks!

**Comment by electrify** [comment]
having the same issue on 2.0.3-1, how do i check if its json or gzip?

**Comment by mariussturm** [comment]
Sorry I was not able to reproduce this with the latest NXLog version: nxlog-ce-2.9.1716-1_rhel7.x86_64.rpm and GL 2.0.3.
How did you installed nxlog in the first place? From the official packages here https://nxlog.org/products/nxlog-community-edition/download ?

**Comment by roxer2725** [comment]
Yes, downloaded and installed from the nxlog site and installed with sidecar as per the GL site instructions.

**Comment by mariussturm** [comment]
The probelm still exist with the latest nxlog version?

**Comment by roxer2725** [comment]
Just now started the update procedure to latest nxlog version after I saw your post. Not sure which version electrify is using.

**Comment by mariussturm** [comment]
@roxer2725 is this still a problem?

**Comment by roxer2725** [comment]
Yes

**Comment by mariussturm** [comment]
@roxer2725 could you please provide some more informations if you want help on this? Which nxlog version did you test? How does the generated configuration looks like? What's the configuration of the Gelf input?

**Comment by roxer2725** [comment]
Sorry – was in the middle of a system deployment.  I’ll get that to you in a few.

**Comment by mariussturm** [comment]
I tried again and could not reproduce this issue. There is one output option that decides whether the message is compressed or not: `OutputType  GELF` == compressed, suitable for UDP connections, `OutputType GELF_TCP` == no compression, suitable for TCP connection. This is rendered correctly by the Sidecar. If you have detailed instructions on how to reproduce the issue feel free to re-open.
