### ISSUE TITLE
TLS and custom domain causing Graylog server to not start due to address binding problem

### ISSUE THREAD

**Issue by PaulDMendoza** [Graylog2/graylog2-server#2456]
### Problem description
I keep getting an error about not being able to bind to an address when Graylog tries to start. I need help figuring out why my server won't bind to an address. I'm probably not understanding something about how to configure URLs.

I'm using a certificate I purchased from GoDaddy with 5 domains (dev.domain.com, www.domain.com, test.domain.com). Domain.com is not actually what I bought, I just don't want to post the real domain on here. 

So I configured the three URLs in the conf file to bind to https://dev.domain.com

```
web_listen_uri = https://dev.domain.com:9000/
rest_transport_uri = https://dev.domain.com:12900/
rest_listen_uri = https://dev.domain.com:12900/
```

I used a PFX file to generate my certificate files based on the HTTP instructions for PKCS12. 

```
openssl pkcs12 -in keystore.pfx -nokeys -out graylog-certificate.pem

openssl pkcs12 -in keystore.pfx -nocerts -out graylog-pkcs5.pem

openssl pkcs8 -in graylog-pkcs5.pem -topk8 -out graylog-key.pem 
```

With all that configured I get this error in the logs (/var/log/graylog-server/server.log)

```
2016-07-05T11:25:01.932-07:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.UserPermissionMigrationPeriodical] periodical. Not configured to run on this node.
2016-07-05T11:25:01.933-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.AlarmCallbacksMigrationPeriodical] periodical, running forever.
2016-07-05T11:25:01.954-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ConfigurationManagementPeriodical] periodical, running forever.
2016-07-05T11:25:01.956-07:00 INFO  [Periodicals] Starting [org.graylog2.periodical.LdapGroupMappingMigration] periodical, running forever.
2016-07-05T11:25:01.981-07:00 INFO  [Periodicals] Starting [org.graylog.plugins.usagestatistics.UsageStatsNodePeriodical] periodical in [300s], polling every [21600s].
2016-07-05T11:25:01.985-07:00 INFO  [Periodicals] Starting [org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical] periodical in [300s], polling every [21600s].
2016-07-05T11:25:01.985-07:00 INFO  [Periodicals] Starting [org.graylog.plugins.collector.periodical.PurgeExpiredCollectorsThread] periodical in [0s], polling every [3600s].
2016-07-05T11:25:02.198-07:00 INFO  [transport] [graylog-ebb2f5e7-2b8f-4984-9c4a-1aa21cae1f1d] publish_address {127.0.0.1:9350}, bound_addresses {[::1]:9350}, {127.0.0.1:9350}
2016-07-05T11:25:02.214-07:00 INFO  [discovery] [graylog-ebb2f5e7-2b8f-4984-9c4a-1aa21cae1f1d] graylog/Tiler3cdTs-VRAM-QZ67qA
2016-07-05T11:25:02.247-07:00 INFO  [AbstractJerseyService] Enabling CORS for HTTP endpoint
2016-07-05T11:25:04.579-07:00 ERROR [ServiceManager] Service WebInterfaceService [FAILED] has failed in the STARTING state.
javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Cannot assign requested address
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:299) ~[graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:163) ~[graylog.jar:?]
        at org.graylog2.shared.initializers.AbstractJerseyService.setUp(AbstractJerseyService.java:160) ~[graylog.jar:?]
        at org.graylog2.initializers.WebInterfaceService.startUp(WebInterfaceService.java:46) ~[graylog.jar:?]
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:60) [graylog.jar:?]
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:100) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_91]
        at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_91]
        at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_91]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_91]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_91]
        at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:131) ~[graylog.jar:?]
        at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:88) ~[graylog.jar:?]
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:248) ~[graylog.jar:?]
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:228) ~[graylog.jar:?]
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:219) ~[graylog.jar:?]
        at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:714) ~[graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:278) ~[graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:296) ~[graylog.jar:?]
        ... 6 more
2016-07-05T11:25:04.594-07:00 ERROR [InputSetupService] Not starting any inputs because lifecycle is: Uninitialized [LB:DEAD]
2016-07-05T11:25:04.598-07:00 INFO  [LogManager] Shutting down.

```

### Other Info
I was able to start the server without all these URL settings and was able to access the site through the browser when it was just bound to the IP address of the server with no TLS settings. But obviously I want to secure this. 

### Environment

* Graylog Version: 2.0 (I just followed the steps for Ubuntu 16.04)
* Elasticsearch Version: Whatever version came with the Graylog 2.0 on 7/2/2016
* MongoDB Version: Whatever version came with the Graylog 2.0 on 7/2/2016
* Operating System: Ubuntu 16.04

**Comment by lennartkoopmann** [comment]
You have to use IP addresses for the `listen_uri` settings because Graylog will try to bind to it and it cannot bind to URLs. (No program on your operating system can)

You can set all `transport_address` settings to a URL though. This should ensure that all traffic is attempting to go through secured channels.

**Comment by PaulDMendoza** [comment]
That didn't work. BUT what did just work was modifying the hosts file (/etc/hosts) to add an entry for my domain to that. Then Grizzly was able to bind to the address.

**Comment by joschi** [comment]
@PaulDMendoza The domain you're using in `rest_listen_uri`, `rest_transport_uri`, and `web_listen_uri` must be resolvable on the system you're running Graylog. It can't just be any "fantasy" name and doesn't have anything to do with HTTPS/TLS.

**Comment by PaulDMendoza** [comment]
@joschi I realize now why I'm stuck but still not sure how to proceed. 

My server isn't directly exposed to the internet. I'm using port forwarding to forward the request to the server. The IP address of the server is X but the external IP address is actually Y. When I configure the IP address X which is the internal IP, I can get to the web server but the web application thinks it should be hitting X:12900 instead of Y:12900 or better yet it should really try to be hitting mydomain.com. 

Any ideas on how to solve this?

**Comment by PaulDMendoza** [comment]
I will just make a new issue.
