### ISSUE TITLE
Simulator with GELF codec not working, NullPointerException

### ISSUE THREAD

**Issue by tokred** [Graylog2/graylog2-server#2610]
With beta.2, the pipeline simulator does not show simulations results but stays at "Loading" forever, while a NullPointerException is thrown according to server log. Initially occured https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/40

## Expected Behavior

Apply pipeline logic to simulation messages and show results.

## Current Behavior

Tried several raw messages in simulation with GELF codec, simulation result missing, exception thrown in log:
```
2016-08-04T10:57:30.479+02:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
org.graylog.plugins.pipelineprocessor.ast.exceptions.FunctionEvaluationException: java.lang.NullPointerException
        at org.graylog.plugins.pipelineprocessor.ast.expressions.FunctionExpression.evaluateUnsafe(FunctionExpression.java:65) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.ast.expressions.BooleanValuedFunctionWrapper.evaluateBool(BooleanValuedFunctionWrapper.java:35) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.processForResolvedPipelines(PipelineInterpreter.java:320) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.processForPipelines(PipelineInterpreter.java:281) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.process(PipelineInterpreter.java:238) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.rest.SimulatorResource.simulate(SimulatorResource.java:76) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at org.graylog.plugins.pipelineprocessor.functions.FromInput.evaluate(FromInput.java:75) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.functions.FromInput.evaluate(FromInput.java:33) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.ast.expressions.FunctionExpression.evaluateUnsafe(FunctionExpression.java:59) ~[?:?]
        ... 32 more
```

## Steps to Reproduce (for bugs)

1. Messages tried, each with GELF message codec and 127.0.0.1 source
```
{"@timestamp":"2016-08-04T04:31:03.528Z","@version":"1","message":"[10861026.240439] [UFW BLOCK] IN=venet0 OUT= MAC= SRC=104.193.252.230 DST=91.250.117.97 LEN=40 TOS=0x00 PREC=0x00 TTL=244 ID=54321 PROTO=TCP SPT=46901 DPT=21320 WINDOW=65535 RES=0x00 SYN URGP=0 ","host":"box.jalogis.ch","severity":"warning","facility":"kern","programname":"kernel","procid":"-","type":"syslog"}
```
```
{"message":"<131>Aug 04 2016 10:48:54: %ASA-3-713902: Group = CA02L2LGroup, IP = 217.91.22.181, QM FSM error (P2 struct &0x00002aaae27062b0, mess id 0x443a3634)!\n","log_env":"test","log_collector":"log-shipper01","log_type":"log-cisco-asa","log_input_type":"syslog-udp/1514","log_stream":"testlab","host":"172.45.150.124","message_timestamp":"2016-08-04T08:48:54.000Z","log_collector_timestamp":"2016-08-04T08:48:54.169Z"}
```
```
{"message":"{\"message_timestamp\":\"2016-08-04T08:09:40.546Z\",\"syslog_pri\":14,\"path\":\"/isauthenticated\",\"environment\":\"prod\",\"method\":\"GET\",\"params\":{}}\n","log_env":"test","log_collector":"log-shipper02","log_type":"log-nodejs","log_input_type":"syslog-udp/1514","log_stream":"dcn","host":"172.25.235.226","log_collector_timestamp":"2016-08-04T08:09:40.550Z"}
```
2. Simulation result only shows "Loading".
3. Log contains exception, see above.

## Environment

* Graylog Version: 2.1.0-beta.2+ffa3355
* Elasticsearch Version: 2.3.2
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kroepke** [comment]
@tokred Is this with the same rules as in https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/40 ?

**Comment by tokred** [comment]
@kroepke I tried both with and without the mentioned select_jsonpath rule. However, I have 8 connected pipelines overall with 2-3 stages each. All of them work fine and no exceptions are raised during normal operation.

**Comment by tokred** [comment]
Mostly, I use three stages for my pipelines: First stage separates log type based on a certain field value or based on a certain input (GELF-Kafka). Second stage does extraction/normalization of fields, third stage sends to appropriate stream.

Did some digging: The simulator *stops working* as soon I connect a pipeline to the default stream which contains a `from_input()` rule condition instead of `has_field(...) && field==...` . Does this help?

Regards

**Comment by kroepke** [comment]
These things are unfortunately really difficult to debug without actual rules and actual messages.
I'll try to see what's up with the `from_input` function.

**Comment by tokred** [comment]
Idea: Maybe the reason for the NullPointerException is that a simulated message itself does not contain an input? Therefore the comparison of from_input fails as there is not comparable value?

Have a look at https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/master/src/main/java/org/graylog/plugins/pipelineprocessor/functions/FromInput.java#L58-L59
Is it possible that for simulated messages the `messageInput.getTitle().equalsIgnoreCase(name)` fails because `messageInput` is maybe null?

Regards

**Comment by kroepke** [comment]
Good point!
The function was written as one of the first and at that point all messages had an input.

I guess the best option would be to add an additional select box to choose the input the pipeline is being simulated against.
