### ISSUE TITLE
Kafka Error and Process Buffer 100%

### ISSUE THREAD

**Issue by ik-z** [Graylog2/graylog2-server#2716]
Hi,

## Bug

- ERROR [KafkaJournal] Read offset 29048007 before start of log at 29171833, starting to read from the beginning of the journal.
- ERROR [MessageCountRotationStrategy] Unknown index, cannot perform rotation
- WARN  [Errors] The following warnings have been detected: WARNING: Unknown HK2 failure detected
- The process buffer is 100% all time
- The disk journal does'nt decrease

## Error / Warn logs and debugg

[Image Node Disk Journal and Process buffer](http://img4.hostingpics.net/pics/733945graylog.png)

- Graylog logs (2.0.3) :

```
2016-08-18T10:37:42.963+02:00 ERROR [KafkaJournal] Read offset 23472071 before start of log at 23602491, starting to read from the beginning of the journal.
2016-08-18T11:37:25.056+02:00 ERROR [KafkaJournal] Read offset 23605607 before start of log at 23730972, starting to read from the beginning of the journal.
2016-08-18T12:38:37.437+02:00 ERROR [KafkaJournal] Read offset 23733223 before start of log at 23866721, starting to read from the beginning of the journal.
2016-08-18T13:38:21.212+02:00 ERROR [KafkaJournal] Read offset 23869459 before start of log at 23982580, starting to read from the beginning of the journal.
2016-08-18T14:38:23.175+02:00 ERROR [KafkaJournal] Read offset 23985312 before start of log at 24101024, starting to read from the beginning of the journal.
2016-08-18T15:27:43.569+02:00 ERROR [InputServiceImpl] Cannot build extractor from persisted data. Skipping.
2016-08-18T15:27:43.580+02:00 ERROR [InMemoryRolePermissionResolver] Could not find roles collection, no user roles updated.
2016-08-18T15:27:43.586+02:00 ERROR [NodePingThread] Uncaught exception in periodical


2016-08-18T15:27:47.586+02:00 WARN  [Errors] The following warnings have been detected: WARNING: Unknown HK2 failure detected:
2016-08-18T15:27:47.587+02:00 WARN  [Errors] The following warnings have been detected: WARNING: Unknown HK2 failure detected:
2016-08-18T15:27:47.588+02:00 WARN  [Errors] The following warnings have been detected: WARNING: Unknown HK2 failure detected:
2016-08-18T15:27:47.591+02:00 WARN  [ProxiedResource] Unable to call http://X.X.X.X:12900/system/metrics/multiple on node <8ed61024-5c48-440f-83c3-829a6e6a551f>, result: Internal Server Error
2016-08-18T15:27:55.613+02:00 WARN  [ProxiedResource] Unable to call http://X.X.X.X:12900/system/metrics/multiple on node <8ed61024-5c48-440f-83c3-829a6e6a551f>, result: Unauthorized
2016-08-18T15:31:59.349+02:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
```

- Date : Thu Aug 18 15:35:33 CEST 2016

- ntpstat
```
synchronised to NTP server (X.X.X.X) at stratum 4
   time correct to within 53 ms
   polling server every 1024 s
```

- MongoDB :

MongoDB shell version: 3.2.9

```
> show dbs
graylog  0.001GB
local    0.000GB
> use graylog
switched to db graylog
> db.nodes.find()
{ "_id" : ObjectId("56b5b8cfc1d9394178474a02"), "is_master" : true, "hostname" : "hostname", "last_seen" : 1471527321, "transport_address" : "http://X.X.X.X:12900/", "type" : "SERVER", "node_id" : "8ed61024-5c48-440f-83c3-829a6e6a561f" }
```

Last_seen :

```
date -d @1471527321
Thu Aug 18 15:35:21     2016
```

- Elasticsearch :

```
[2016-08-15 13:40:26,477][WARN ][monitor.jvm              ] [Shinchuko Lotus] [gc][young][329545][2735] duration [1.1s], collections [1]/[1.6s], total [1.1s]/[1.8m], memory [645.9mb]->[135.8mb]/[11.9gb], all_pools {[young] [508.7mb]->[1.5mb]/[532.5mb]}{[survivor] [10.7mb]->[8.7mb]/[66.5mb]}{[old] [126.4mb]->[126.6mb]/[11.3gb]}

curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
{
  "cluster_name" : "graylog",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 4,
  "active_shards" : 4,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}

```
Version :

```
curl -XGET 'localhost:9200'
{
  "name" : "Richard Parker",
  "cluster_name" : "graylog",
  "version" : {
    "number" : "2.3.5",
    "build_hash" : "90f439ff60a3c0f497f91663701e64ccd01edbb4",
    "build_timestamp" : "2016-07-27T10:36:52Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
```

- Graylog node info :

Lifecycle state : Running
Marked as ALIVE for load balancers
Input buffer : 0 to 2%
Process buffer : 100% (65536 messages)
Output buffer : 0%
Diskjournal : 
- Path:/data/journal
- Earliest entry:12 hours ago
- Maximum size:5 GB
- Maximum age:12 hours 0 minutes
- Flush policy:Every 1,000,000 messages or 1 minutes 0 seconds

8,046,531 unprocessed messages (25 segments)

Loadaverage server : ~0.9

- RAM : 

```
free -m
              total        used        free      shared  buff/cache   available
Mem:          15886        2950        5131           9        7804       12629
Swap:          8193           0        8193

vmstat
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  0      0 5253916   2724 7991144    0    0     0    15    7    3 15  0 85  0  0
```

## Context 

I have a graylog2 server with ES and MongoDB on the same node.
This machine have 8 cores and 16GB RAM based on CentOS Linux distrib.

I've differents error :
- ERROR [KafkaJournal] Read offset 29048007 before start of log at 29171833, starting to read from the beginning of the journal.
- ERROR [MessageCountRotationStrategy] Unknown index, cannot perform rotation
- WARN  [Errors] The following warnings have been detected: WARNING: Unknown HK2 failure detected
- The process buffer is 100% all time
- The disk journal does'nt decrease

## Your Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.3.5
* MongoDB Version: 3.2.9
* Operating System: CentOS7
* Browser version: Last version of Firefox

Someone could to help me to fix my graylog problems ?

Thanks !!

See ya

**Comment by kroepke** [comment]
Could you please paste the entire error messages?

From the limited amount of information it looks like your system is simply overwhelmed (the "re-registering node" message should never happen in such a setup).

**Comment by ik-z** [comment]
Hi @kroepke,

The entire error messages are in attach files.

My disk journal is 10gb now.

[graylog.txt](https://github.com/Graylog2/graylog2-server/files/430244/graylog.txt)

Do you have an idea ?

Thanks !

**Comment by kroepke** [comment]
There are multiple issues here:

1. Your Graylog server has high garbage collection times, usually this should not happen.
2. It does not seem to write anything out to elasticsearch, is it up and running properly? Check for its cluster state.
3. Were there any completely malformed messages sent to Graylog? There is a bug in 2.0 in which it can happen that no progress can be made. It is an edge case, but it looks similar: https://github.com/Graylog2/graylog2-server/issues/2627

If you stop the server and move the journal away for a test run, do messages get indexed properly?

In general it seems like your system isn't tuned correctly for your work load.

**Comment by ik-z** [comment]
Hi @kroepke 

2. Yes. The ES service is OK (green state). Cluster ? No, in this time, it's a standalone server.

3. No, the input message is the firewall event, avec grok parsers. The grok pattern checker (Manage extractor) work well.

Confirm it : you want :
- I move the /data/graylog/journal to another space
- I restart graylog to see if it's work ?

> In general it seems like your system isn't tuned correctly for your work load.
ie. the sizing server ?

Thanks

**Comment by ik-z** [comment]
hi @kroepke 

I move the graylog/journal/* data to another folder. I start graylog and I have in two hours :
100% process buffer (65k messages) and I already got 700Mb data in the disk journal.

Thanks for your return

**Comment by ik-z** [comment]
Hi

Someone have an idea ?

Thanks

**Comment by jalogisch** [comment]
@ik-z 

I personal have seen this messages most time when the time on the Servers is not in sync, but as you have all on the same Host this can't be an issue. 

Did you checked if you run in the same issue after you had updated Graylog to 2.1?

**Comment by ik-z** [comment]
Hi @jalogisch 

Indeed, I want to upgrade graylog 2.0.3 to 2.1. But I updated graylog repo :
```
wget https://packages.graylog2.org/repo/packages/graylog-2.1-repository_latest.rpm
rpm -Uvh graylog-2.1-repository_latest.rpm
yum update

rpm -qa | grep gray
graylog-server-2.0.3-1.noarch
graylog-2.1-repository-1-3.noarch

yum search graylog
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: fr2.rpmfind.net
 * epel: fr2.rpmfind.net
 * extras: centos.mirror.fr.planethoster.net
 * updates: fr2.rpmfind.net
============================================================================================ N/S matched: graylog =======
graylog-2.0-repository.noarch : Package to install Graylog 2.0 GPG key and repository
graylog-2.1-repository.noarch : Package to install Graylog 2.1 GPG key and repository
graylog-server.noarch : Graylog server
uwsgi-logger-graylog2.x86_64 : uWSGI - Graylog2 logger plugin

yum update graylog-server.noarch
```

But the upgrade package not work. I have yet 2.0.3 version.

**Comment by ik-z** [comment]
Hi @jalogisch @kroepke 

Since the update, I have this error :

`2016-09-05T17:48:09.918+02:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.net.SocketTimeoutException: timeout
        at okio.Okio$3.newTimeoutException(Okio.java:210) ~[graylog.jar:?]
        at okio.AsyncTimeout.exit(AsyncTimeout.java:288) ~[graylog.jar:?]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:242) ~[graylog.jar:?]
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325) ~[graylog.jar:?]
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314) ~[graylog.jar:?]
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210) ~[graylog.jar:?]
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186) ~[graylog.jar:?]
        at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) ~[graylog.jar:?]
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at org.graylog2.rest.RemoteInterfaceProvider.lambda$get$0(RemoteInterfaceProvider.java:59) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) ~[graylog.jar:?]
        at okhttp3.RealCall.execute(RealCall.java:60) ~[graylog.jar:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174) ~[graylog.jar:?]
        at org.graylog2.rest.resources.cluster.ClusterSystemPluginResource.list(ClusterSystemPluginResource.java:73) ~[graylog.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_101]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_101]
        at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[?:1.8.0_101]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_101]
        at okio.Okio$2.read(Okio.java:138) ~[graylog.jar:?]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:238) ~[graylog.jar:?]
        ... 52 more
2016-09-05T17:48:12.358+02:00 WARN  [ProxiedResource] Unable to call http://A.B.C.D:12900/api/system/inputstates on node <8ed61024-5c48-440f-83c3-829a6e6a551f>, caught exception: Read timed out (class java.net.SocketTimeoutException)
2016-09-05T17:48:17.524+02:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.net.SocketTimeoutException: timeout
        at okio.Okio$3.newTimeoutException(Okio.java:210) ~[graylog.jar:?]
        at okio.AsyncTimeout.exit(AsyncTimeout.java:288) ~[graylog.jar:?]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:242) ~[graylog.jar:?]
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325) ~[graylog.jar:?]
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314) ~[graylog.jar:?]
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210) ~[graylog.jar:?]
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186) ~[graylog.jar:?]
        at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) ~[graylog.jar:?]
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at org.graylog2.rest.RemoteInterfaceProvider.lambda$get$0(RemoteInterfaceProvider.java:59) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) ~[graylog.jar:?]
        at okhttp3.RealCall.execute(RealCall.java:60) ~[graylog.jar:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174) ~[graylog.jar:?]
        at org.graylog2.rest.resources.cluster.ClusterJournalResource.get(ClusterJournalResource.java:76) ~[graylog.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:203) ~[?:1.8.0_101]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_101]
        at okio.Okio$2.read(Okio.java:138) ~[graylog.jar:?]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:238) ~[graylog.jar:?]
        ... 52 more
`

Do you have an idea ?

Thanks

**Comment by joschi** [comment]
@ik-z Is `http://A.B.C.D:12900/api/` the correct URI for the Graylog REST API on your system? Graylog has to be able to communicate with that URI (even if it's the same machine).

**Comment by jalogisch** [comment]
@ik-z did you check the Upgrade Documentation before the Upgrade? http://docs.graylog.org/en/2.1/pages/upgrade/graylog-2.1.html

**Comment by ik-z** [comment]
Hi @joschi @jalogisch @kroepke 

I forgot to update the post. Indeed, I change the URI and it's work.
WIth the 2.1 upgrade, the kafka buffer is good \o/

Thanks
