### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by JulioQc** [Graylog2/graylog2-server#2722]
## Expected Behavior
Massage is parsed correctly.

## Current Behavior
Message not parsed.

## Possible Solution
n/a

## Steps to Reproduce (for bugs)

Make some Grok pattern extractor.

## Context
Error in server's log:

`
2016-08-19 11:38:27,901 ERROR: org.graylog2.filters.ExtractorFilter - Could not apply extractor "ExchangeHT Mailbox Logs" (id=d6ad27f0-6575-11e6-b032-005056ae6767) t$
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967) ~[?:1.8.0_77]
        at oi.thekraken.grok.api.Match.cleanString(Match.java:204) ~[graylog.jar:?]
        at oi.thekraken.grok.api.Match.captures(Match.java:171) ~[graylog.jar:?]
        at org.graylog2.inputs.extractors.GrokExtractor.run(GrokExtractor.java:89) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:187) ~[graylog.jar:?]
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:62) [graylog.jar:?]
        at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:100) [graylog.jar:?]
        at org.graylog2.buffers.processors.ServerProcessBufferProcessor.handleMessage(ServerProcessBufferProcessor.java:56) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:82) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:61) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
`

Received log message that generated the error:

`
2016-08-19T15:38:27.832Z,192.168.0.254,ht-m,64.70.94.123,ssljournal.otherdomain.net,08D3BFCC32E1DD56;250 2.6.0  <9aa99ce3-7fc3-4351-a147-81e9@journal.report.generator> Queued mail for delivery,JournalingMTL,SMTP,SEND,13118531,<9aa99ce3-7fc3-4-a147-813f527c3fe9@journal.report.generator>,local-domain07@otherdomain.net,250 2.1.5 local-domain07@otherdomain.net ,14403,1,,,"Hi there,",MicrosoftExchange329e71ec88ce41109e@domain.net,<>,SRV=HT-M.domain.net:TOTAL=1,Originating,,,,
`

Grok pattern:

`
%{TIMESTAMP_ISO8601:datetime},%{NOTCOMMA:client-ip},%{NOTCOMMA:client-hostname},%{NOTCOMMA:server-ip},%{NOTCOMMA:server-hostname},%{SMTPDATA:source-context},%{NOTCOMMA:connector-id},%{NOTCOMMA:source-id},%{NOTCOMMA:event-id},%{NOTCOMMA:internal-message-id},%{NOTCOMMA:message-id},%{NOTCOMMA:recipient-address},%{NOTCOMMA:recipient-status},%{NOTCOMMA:total-bytes},%{NOTCOMMA:recipient-count},%{NOTCOMMA:related-recipient-address},%{NOTCOMMA:reference},%{NOTCOMMA:message-subject},%{SMTPDATA:sender-address},%{SMTPDATA:return-path},%{NOTCOMMA:message-info},%{SMTPDATA:directionality},%{NOTCOMMA:tenant-id},%{NOTCOMMA:original-client-ip},%{NOTCOMMA:original-server-ip},%{SMTPDATA:custom-data}
`

Custom Grok:
`SMTPDATA	%{QUOTEDSTRING:UNWANTED}|%{NOTCOMMA:UNWANTED}`
`NOTCOMMA	[^,]*`

Parsing worked when tested here: http://grokconstructor.appspot.com/do/match

## Your Environment

* Graylog Version: 2.0.3 OVA
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kroepke** [comment]
I've just tried to reproduce this issue in 2.2.0-alpha.1 and it looks like it is fixed:
![screenshot](https://cloud.githubusercontent.com/assets/52014/19434636/e4d417ec-9466-11e6-9178-77892365ec67.png)

There were changes to the underlying Grok library we are using, so most likely 2.1.x should contain the fix as well.

Please note that Graylog uses a different regex library than the various grok debugger sites, so not all of the results are comparable.

Please update to the latest Graylog version and try again. If that doesn't fix this particular issue, please comment again or open another bug report.

Thank you,
Kay

**Comment by JulioQc** [comment]
Yes, has been working with 2.1.1 just fine now :)
Thanks for the update and the fix! Greatly appreciated
