### ISSUE TITLE
Error during LDAP user account sync

### ISSUE THREAD

**Issue by eroji** [Graylog2/graylog2-server#2724]
I am seeing repeated LDAP related error messages in the log after turning it on in the web interface. LDAP based accounts are able to log in just fine but the errors repeat constantly. Both fresh Graylog 2.0 install and upgrade install exhibit the same errors.

`2016-08-19 15:22:18,295 ERROR: org.graylog2.security.realm.LdapUserAuthenticator - Error during LDAP user account sync. Cannot log in user admin
java.lang.RuntimeException: ERR_02002_FAILURE_ON_UNDERLYING_CURSOR Failure on underlying Cursor.
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:86) ~[graylog.jar:?]
        at org.graylog2.security.ldap.LdapConnector.search(LdapConnector.java:139) ~[graylog.jar:?]
        at org.graylog2.security.realm.LdapUserAuthenticator.doGetAuthenticationInfo(LdapUserAuthenticator.java:96) [graylog.jar:?]
        at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:568) [graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:219) [graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269) [graylog.jar:?]
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) [graylog.jar:?]
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) [graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270) [graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256) [graylog.jar:?]
        at org.graylog2.shared.security.ShiroSecurityContext.loginSubject(ShiroSecurityContext.java:98) [graylog.jar:?]
        at org.graylog2.shared.security.ShiroAuthenticationFilter.filter(ShiroAuthenticationFilter.java:48) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: org.apache.directory.api.ldap.model.cursor.CursorLdapReferralException
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:164) ~[graylog.jar:?]
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:50) ~[graylog.jar:?]
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:80) ~[graylog.jar:?]
        ... 29 more
`
## Steps to Reproduce (for bugs)
1. Log into graylog web interface
2. Enable LDAP and fill in the LDAP user login and password
3. Save configuration
4. Tail the graylog.log
## Your Environment
- Graylog Version: 2.0.3
- Elasticsearch Version: 2.3.5
- MongoDB Version: 3.2.1
- Operating System: CentOS 6.7
- Browser version: Chrome 52

**Comment by kroepke** [comment]
see #2714

**Comment by bernd** [comment]
We switched to a new LDAP library in the upcoming 4.0 release. Please open a new issue if you still see this with 4.0. Thank you!

**Comment by Aenima4six2** [comment]
Also removed core LDAP role binding features from non enterprise, so not 4.0 is not a viable upgrade path for many.
