### ISSUE TITLE
TLS Input raised exception

### ISSUE THREAD

**Issue by yves-vogl** [Graylog2/graylog2-server#2752]
I'm not sure if it's an graylog issue…

## Expected Behavior
When I place an pkcs8 file and a (self-signed) certificate on the system and specifiy the path to those files correctly for an input, I'd exspect that an acceptor is created.

## Current Behavior
When starting input it fails:

```
2016-08-28T17:41:49.671+02:00 INFO  [AbstractTcpTransport] Enabled TLS for input [Syslog TCP/57a61059239dfd04c6eea408]. key-file="/etc/pki/tls/private/example.com-graylog.pkcs8" cert-file="/etc/pki/tls/certs/example.com-graylog.crt"
2016-08-28T17:41:49.672+02:00 INFO  [InputStateListener] Input [Syslog TCP/57a61059239dfd04c6eea408] is now STARTING
2016-08-28T17:41:49.675+02:00 INFO  [InputStateListener] Input [Syslog TCP/57a61059239dfd04c6eea408] is now RUNNING
2016-08-28T17:41:52.135+02:00 WARN  [AbstractNioSelector] Failed to initialize an accepted socket.
java.security.cert.CertificateParsingException: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 49)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169) ~[?:1.8.0_101]
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1804) ~[?:1.8.0_101]
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195) ~[?:1.8.0_101]
	at sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:471) ~[?:1.8.0_101]
	at sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:356) ~[?:1.8.0_101]
	at java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:462) ~[?:1.8.0_101]
	at org.graylog2.plugin.inputs.transports.util.KeyUtil.loadCertificates(KeyUtil.java:90) ~[graylog.jar:?]
	at org.graylog2.plugin.inputs.transports.util.KeyUtil.loadCertificates(KeyUtil.java:100) ~[graylog.jar:?]
	at org.graylog2.plugin.inputs.transports.util.KeyUtil.initTrustStore(KeyUtil.java:73) ~[graylog.jar:?]
	at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$1.createSslEngine(AbstractTcpTransport.java:199) ~[graylog.jar:?]
	at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$1.call(AbstractTcpTransport.java:186) ~[graylog.jar:?]
	at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$1.call(AbstractTcpTransport.java:182) ~[graylog.jar:?]
	at org.graylog2.plugin.inputs.transports.NettyTransport$1.getPipeline(NettyTransport.java:110) ~[graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42) [graylog.jar:?]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [graylog.jar:?]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 49)
	at sun.security.util.ObjectIdentifier.<init>(ObjectIdentifier.java:253) ~[?:1.8.0_101]
	at sun.security.util.DerInputStream.getOID(DerInputStream.java:281) ~[?:1.8.0_101]
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:356) ~[?:1.8.0_101]
	at sun.security.x509.CertificateAlgorithmId.<init>(CertificateAlgorithmId.java:79) ~[?:1.8.0_101]
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:646) ~[?:1.8.0_101]
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167) ~[?:1.8.0_101]
	... 21 more

```

## Steps to Reproduce (for bugs)

```
allow_override_date: true
bind_address: 0.0.0.0
expand_structured_data: false
force_rdns: false
max_message_size: 2097152
override_source: <empty>
port: 6514
recv_buffer_size:
store_full_message: false
tcp_keepalive: false
tls_cert_file: /etc/pki/tls/certs/example.com-graylog.crt
tls_client_auth: required
tls_client_auth_cert_file: /etc/pki/tls/graylog-client-certs
tls_enable: true
tls_key_file: /etc/pki/tls/private/example.com-graylog.pkcs8
tls_key_password: ********
use_null_delimiter: false
```

## Context
I created a key by invoking the following commands:

```
# openssl req -nodes -newkey rsa:4096 -keyout /etc/pki/tls/private/example.com-graylog.key -out /etc/pki/tls/certs/example.com-graylog.csr -subj "/C=DE/ST=NRW/L=Dortmund/O=ACME/OU=Example Unit/CN=example.com"

# openssl pkcs8 -topk8 -in /etc/pki/tls/private/example.com-graylog.key -inform pem -out /etc/pki/tls/private/example.com-graylog.pkcs8 -outform pem -nocrypt

# chown graylog.root /etc/pki/tls/private/example.com-graylog.pkcs8
```

The certificate was created using XCA.

```
Owner: CN=example.com, OU=Example Unit, O=ACME, L=Dortmund, ST=NRW, C=DE
Issuer: EMAILADDRESS=mail@example.com, CN=ACME CA, OU=ACME CA, O=ACME, L=Dortmund, ST=NRW, C=DE
Serial number: 1a
Valid from: Sun Aug 28 02:00:00 CEST 2016 until: Sat Aug 28 01:59:59 CEST 2021
Certificate fingerprints:
	 MD5:  A7:72:35:23:D4:DF:E3:DD:F0:24:28:B3:C7:82:6C:53
	 SHA1: 3B:E5:B7:E1:1E:AD:60:2C:A4:F3:4D:0F:1D:6A:A0:1D:6E:DC:70:52
	 SHA256: 00:F4:A3:99:44:F1:BA:40:0C:9B:94:36:9D:09:1F:AB:B0:96:E7:BA:E8:99:A0:70:A6:52:24:E0:74:7B:FB:FD
	 Signature algorithm name: SHA256withRSA
	 Version: 3

Extensions: 

#1: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 44 5E 4E 7D FF 20 0A 3E   0E 31 D8 58 C0 9F 15 6B  D^N.. .>.1.X...k
0010: 36 D7 27 11                                        6.'.
]
[EMAILADDRESS=mail@example.com, CN=ACME CA, OU=ACME CA, O=ACME, L=Dortmund, ST=NRW, C=DE]
SerialNumber: [    01]
]

#2: ObjectId: 2.5.29.19 Criticality=false
BasicConstraints:[
  CA:false
  PathLen: undefined
]

#3: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: ED 84 96 6A 67 7B 1C 3C   02 9B 11 FB BF 75 34 8B  ...jg..<.....u4.
0010: 5B FA F2 41                                        [..A
]
]
```

## Your Environment

* Graylog Version: Graylog 2.0.3 (f07c170), Oracle Corporation 1.8.0_101
* Operating System: CentOS 7 Linux 3.10.0-327.28.2.el7.x86_64

**Comment by joschi** [comment]
@yves-vogl 
> The certificate was created using XCA.

Please attach the generated certificate (it's the public part of the whole TLS thing anyway) or at least the first two lines. Alternatively post the corresponding OpenSSL command which can be used to produce a certificate similar to yours.

Since the error message hints to an invalid X.509 certificate in PEM format, this is most likely the culprit.

**Comment by yves-vogl** [comment]
@joschi 
Thanks for your answer. I've attached the certificate.

[cert.txt](https://github.com/Graylog2/graylog2-server/files/448022/cert.txt)

**Comment by yves-vogl** [comment]
I also tried specifying the certificate in binary format (der) - this leads to the same issue.

```Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 49)
	at sun.security.util.ObjectIdentifier.<init>(ObjectIdentifier.java:253) ~[?:1.8.0_101]
	at sun.security.util.DerInputStream.getOID(DerInputStream.java:281) ~[?:1.8.0_101]
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:356) ~[?:1.8.0_101]
	at sun.security.x509.CertificateAlgorithmId.<init>(CertificateAlgorithmId.java:79) ~[?:1.8.0_101]
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:646) ~[?:1.8.0_101]
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167) ~[?:1.8.0_101]
	... 21 more
```

**Comment by yves-vogl** [comment]
Hey @joschi, can I help to resolve this issue in any way?

**Comment by yves-vogl** [comment]
The issue persists with Graylog 2.1.1 (graylog-server-2.1.1-1.noarch) - now I'll try to generate the certificates without XCA

**Comment by yves-vogl** [comment]
The certificate I created manually works.

[working.cert.txt](https://github.com/Graylog2/graylog2-server/files/499105/working.cert.txt)
