### ISSUE TITLE
Possible file descriptor leak in Graylog Server

### ISSUE THREAD

**Issue by gitfrederic** [Graylog2/graylog2-server#2823]
* Graylog Version: Graylog server 2.0.2 (4da1379)
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.x
* Operating System: CentOS Linux release 7.0.1406 (Core)

We saw an increase/leak (up to 4096 limit) of open file descriptors on the Graylog Server (java) process.  The following exception occurred:

```shell
2016-09-13 06:01:56,988 ERROR: org.graylog2.shared.buffers.JournallingMessageHandler - Unable to write to journal - retrying
kafka.common.KafkaStorageException: I/O exception in append to log 'messagejournal-0'
        at kafka.log.Log.append(Log.scala:266) ~[graylog.jar:?]
        at org.graylog2.shared.journal.KafkaJournal.write(KafkaJournal.java:411) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.writeToJournal(JournallingMessageHandler.java:113) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:96) [graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:45) [graylog.jar:?]
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.io.FileNotFoundException: /app/graylog-server/data/journal/messagejournal-0/00000000007602215471.index (Too many open files)
        at java.io.RandomAccessFile.open0(Native Method) ~[?:1.8.0_72]
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[?:1.8.0_72]
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[?:1.8.0_72]
        at kafka.log.OffsetIndex$$anonfun$resize$1.apply(OffsetIndex.scala:277) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$resize$1.apply(OffsetIndex.scala:276) ~[graylog.jar:?]
        at kafka.utils.Utils$.inLock(Utils.scala:535) ~[graylog.jar:?]
        at kafka.log.OffsetIndex.resize(OffsetIndex.scala:276) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$trimToValidSize$1.apply$mcV$sp(OffsetIndex.scala:265) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$trimToValidSize$1.apply(OffsetIndex.scala:265) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$trimToValidSize$1.apply(OffsetIndex.scala:265) ~[graylog.jar:?]
        at kafka.utils.Utils$.inLock(Utils.scala:535) ~[graylog.jar:?]
        at kafka.log.OffsetIndex.trimToValidSize(OffsetIndex.scala:264) ~[graylog.jar:?]
        at kafka.log.Log.roll(Log.scala:563) ~[graylog.jar:?]
        at kafka.log.Log.maybeRoll(Log.scala:539) ~[graylog.jar:?]
        at kafka.log.Log.append(Log.scala:306) ~[graylog.jar:?]
        ... 7 more
2016-09-13 06:01:56,997 ERROR: org.graylog2.shared.buffers.JournallingMessageHandler - Unable to write to journal - retrying with exponential back-off
kafka.common.KafkaStorageException: I/O exception in append to log 'messagejournal-0'
        at kafka.log.Log.append(Log.scala:266) ~[graylog.jar:?]
        at org.graylog2.shared.journal.KafkaJournal.write(KafkaJournal.java:411) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.writeToJournal(JournallingMessageHandler.java:113) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.access$200(JournallingMessageHandler.java:45) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler$2.call(JournallingMessageHandler.java:104) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler$2.call(JournallingMessageHandler.java:101) ~[graylog.jar:?]
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78) ~[graylog.jar:?]
        at com.github.rholder.retry.Retryer.call(Retryer.java:160) [graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:101) [graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:45) [graylog.jar:?]
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.io.FileNotFoundException: /app/graylog-server/data/journal/messagejournal-0/00000000007602215471.index (Too many open files)
        at java.io.RandomAccessFile.open0(Native Method) ~[?:1.8.0_72]
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[?:1.8.0_72]
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[?:1.8.0_72]
        at kafka.log.OffsetIndex$$anonfun$resize$1.apply(OffsetIndex.scala:277) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$resize$1.apply(OffsetIndex.scala:276) ~[graylog.jar:?]
        at kafka.utils.Utils$.inLock(Utils.scala:535) ~[graylog.jar:?]
        at kafka.log.OffsetIndex.resize(OffsetIndex.scala:276) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$trimToValidSize$1.apply$mcV$sp(OffsetIndex.scala:265) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$trimToValidSize$1.apply(OffsetIndex.scala:265) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$trimToValidSize$1.apply(OffsetIndex.scala:265) ~[graylog.jar:?]
        at kafka.utils.Utils$.inLock(Utils.scala:535) ~[graylog.jar:?]
        at kafka.log.OffsetIndex.trimToValidSize(OffsetIndex.scala:264) ~[graylog.jar:?]
        at kafka.log.Log.roll(Log.scala:563) ~[graylog.jar:?]
        at kafka.log.Log.maybeRoll(Log.scala:539) ~[graylog.jar:?]
        at kafka.log.Log.append(Log.scala:306) ~[graylog.jar:?]
        ... 12 more
2016-09-13 06:01:57,206 ERROR: org.graylog2.shared.journal.KafkaJournal - Cannot write /app/graylog-server/data/journal/graylog2-committed-read-offset to disk.
java.io.FileNotFoundException: /app/graylog-server/data/journal/graylog2-committed-read-offset (Too many open files)
        at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_72]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_72]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_72]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_72]
        at org.graylog2.shared.journal.KafkaJournal$OffsetFileFlusher.run(KafkaJournal.java:723) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_72]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_72]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
2016-09-13 06:01:57,499 ERROR: org.graylog2.shared.buffers.JournallingMessageHandler - Unable to write to journal - retrying with exponential back-off
kafka.common.KafkaStorageException: I/O exception in append to log 'messagejournal-0'
        at kafka.log.Log.append(Log.scala:266) ~[graylog.jar:?]
        at org.graylog2.shared.journal.KafkaJournal.write(KafkaJournal.java:411) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.writeToJournal(JournallingMessageHandler.java:113) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.access$200(JournallingMessageHandler.java:45) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler$2.call(JournallingMessageHandler.java:104) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler$2.call(JournallingMessageHandler.java:101) ~[graylog.jar:?]
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78) ~[graylog.jar:?]
        at com.github.rholder.retry.Retryer.call(Retryer.java:160) [graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:101) [graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:45) [graylog.jar:?]
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.io.FileNotFoundException: /app/graylog-server/data/journal/messagejournal-0/00000000007602215471.index (Too many open files)
        at java.io.RandomAccessFile.open0(Native Method) ~[?:1.8.0_72]
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[?:1.8.0_72]
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[?:1.8.0_72]
        at kafka.log.OffsetIndex$$anonfun$resize$1.apply(OffsetIndex.scala:277) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$resize$1.apply(OffsetIndex.scala:276) ~[graylog.jar:?]
        at kafka.utils.Utils$.inLock(Utils.scala:535) ~[graylog.jar:?]
        at kafka.log.OffsetIndex.resize(OffsetIndex.scala:276) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$trimToValidSize$1.apply$mcV$sp(OffsetIndex.scala:265) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$trimToValidSize$1.apply(OffsetIndex.scala:265) ~[graylog.jar:?]
        at kafka.log.OffsetIndex$$anonfun$trimToValidSize$1.apply(OffsetIndex.scala:265) ~[graylog.jar:?]
        at kafka.utils.Utils$.inLock(Utils.scala:535) ~[graylog.jar:?]
        at kafka.log.OffsetIndex.trimToValidSize(OffsetIndex.scala:264) ~[graylog.jar:?]
        at kafka.log.Log.roll(Log.scala:563) ~[graylog.jar:?]
        at kafka.log.Log.maybeRoll(Log.scala:539) ~[graylog.jar:?]
        at kafka.log.Log.append(Log.scala:306) ~[graylog.jar:?]
        ... 12 more

```

Prior to the exceptions shown above, the only thing that may be indicating a (slow) leak is the following:

```shell
2016-09-12 19:09:08,494 WARN : org.graylog2.outputs.BlockingBatchedESOutput - Error while waiting for healthy Elasticsearch cluster. Not flushing.
java.util.concurrent.TimeoutException: Elasticsearch cluster didn't get healthy within timeout
        at org.graylog2.indexer.cluster.Cluster.waitForConnectedAndHealthy(Cluster.java:179) ~[graylog.jar:?]
        at org.graylog2.indexer.cluster.Cluster.waitForConnectedAndHealthy(Cluster.java:184) ~[graylog.jar:?]
        at org.graylog2.outputs.BlockingBatchedESOutput.flush(BlockingBatchedESOutput.java:112) [graylog.jar:?]
        at org.graylog2.outputs.BlockingBatchedESOutput.write(BlockingBatchedESOutput.java:105) [graylog.jar:?]
        at org.graylog2.buffers.processors.OutputBufferProcessor$1.run(OutputBufferProcessor.java:189) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

```

The above is repeated frequently in the Graylog Server logs.

On the VM, here's what we see (Graylog Server PID is 7464), at a later time (after max open fds has been reached).

```shell
The open fds are mostly sockets.
 
$ sudo ls /proc/7464/fd | wc -l
4096
 
$ netstat -an | grep ESTABLISHED | wc -l
1089
 
$ sudo ls -la /proc/7464/fd | grep socket | wc -l
3797
 
$ sudo lsof -p 7464 | grep TCP | wc -l
3795
 
$ sudo lsof -p 7464 | grep TCP | grep ESTAB | wc -l
1084
 
$ sudo lsof -p 7464
gives:
....
java    7464 root 3822u     sock                0,6         0t0 204879415 protocol: TCP
java    7464 root 3823u     sock                0,6         0t0 204879460 protocol: TCP
java    7464 root 3824u     sock                0,6         0t0 204891220 protocol: TCP
java    7464 root 3825u     sock                0,6         0t0 204879466 protocol: TCP
java    7464 root 3826u     sock                0,6         0t0 204897306 protocol: TCP
...
 
 
$ sudo ls -la /proc/7464/fd | grep socket
gives:
....
lrwx------ 1 root root 64 Sep  9 03:49 438 -> socket:[204102608]
lrwx------ 1 root root 64 Sep  9 03:49 439 -> socket:[204339061]
lrwx------ 1 root root 64 Sep  9 03:49 440 -> socket:[204107234]
lrwx------ 1 root root 64 Sep  9 03:49 441 -> socket:[204090844]
lrwx------ 1 root root 64 Sep  9 03:49 442 -> socket:[204102609]
lrwx------ 1 root root 64 Sep  9 03:49 443 -> socket:[204324536]
lrwx------ 1 root root 64 Sep  9 03:49 444 -> socket:[204102610]
lrwx------ 1 root root 64 Sep  9 03:49 445 -> socket:[204103683]
lrwx------ 1 root root 64 Sep  9 03:49 446 -> socket:[204107235]
....

```

I suspect that the flow genearting the "Error while waiting for healthy Elasticsearch cluster" errors may have something to do with this.

The cluster was doing "fine" until this (i.e. for several days).  It took 8 to 9 hours for the open file descriptors to grow from a (stable) ~1500 up to 4096.

The following stackoverflow post is fairly close to the issue observed: http://serverfault.com/questions/153983/sockets-found-by-lsof-but-not-by-netstat .

**Comment by kroepke** [comment]
@gitfrederic So far I've been unable to reproduce this.

I'm running 2.2.0-SNAPSHOT (current master at f398837aae9e3c220e52320aef419b10685a9d61) with elasticsearch 2.3.3 (no relevant changes according to https://github.com/elastic/elasticsearch/compare/v2.3.2...v2.4.0).

Here's my setup:
* single graylog server
* 3 node elasticsearch cluster
* no replicas, 5 shards
* ~35 msg/sec indexing, default settings
* a global search with an empty query is running once per second (refresh)

The shards are distributed among the nodes, so that whenever one is stopped the server runs into the warning you pasted.

Result:
The open socket count is hovering at 96-99 when 3 nodes are connected. It decreases whenever a node is down, but does not leak in the last hour.

To debug this further, I have a couple of questions:
1. How many graylog servers are in the cluster?
2. How many segments does the journal have?
3. How many elasticsearch nodes are in the cluster?
4. Is the number of elasticsearch nodes varying a lot (i.e. restarts, losing connections etc)?
5. How many inputs are using sockets/files? How many open connections are there and does this vary a lot?
6. How many users are using the cluster and is the graylog server in question serving the web interface?

So far I haven't heard anything about socket leaks in any recent Graylog version, which of course doesn't mean that it isn't a problem. However it might be unrelated to Elasticsearch.

Thanks!

**Comment by kroepke** [comment]
@gitfrederic If you have additional information, please let us know by commenting on this issue.
I'll close it now due to inactivity.
Thank you!

**Comment by vascop** [comment]
We have the same issue. I see an steady increase in open fds resulting in an eventual crash until the process is restarted. FWIW most errors we're seeing are not the Elasticsearch health that gitfrederic reported, instead they're mostly:

2016-12-21T10:45:46.176Z ERROR [NettyTransport] Error in Input [GELF HTTP/57b48de2bfa5c34ad4a1eed9] (channel [id: 0xeb609605, /IP:13581 => /IP:12443])
java.io.IOException: Broken pipe

Another data point is that the increase isn't monotonic, but it does keep growing as the hours pass.

**Comment by jalogisch** [comment]
@vascop please create a new issue and reference to this one and do not highjack an issue and say that your issue looks different.
