### ISSUE TITLE
connection string of mongodb with ipv6

### ISSUE THREAD

**Issue by zaibfridi** [Graylog2/graylog2-server#2853]
I am trying to implement the [Graylog Bigger Setup](http://docs.graylog.org/en/2.0/pages/architecture.html#bigger-production-setup) on **IPV6**

this is my `/var/log/graylog-server/server.log`

```
2016-09-19T11:56:40.177Z INFO  [CmdLineTool] Loaded plugin: Elastic Beats Input 1.1.1 [org.graylog.plugins.beats.BeatsInputPlugin]
2016-09-19T11:56:40.184Z INFO  [CmdLineTool] Loaded plugin: Collector 1.1.1 [org.graylog.plugins.collector.CollectorPlugin]
2016-09-19T11:56:40.185Z INFO  [CmdLineTool] Loaded plugin: Enterprise Integration Plugin 1.1.1 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]
2016-09-19T11:56:40.185Z INFO  [CmdLineTool] Loaded plugin: MapWidgetPlugin 1.1.1 [org.graylog.plugins.map.MapWidgetPlugin]
2016-09-19T11:56:40.185Z INFO  [CmdLineTool] Loaded plugin: Pipeline Processor Plugin 1.1.1 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin]
2016-09-19T11:56:40.185Z INFO  [CmdLineTool] Loaded plugin: Anonymous Usage Statistics 2.1.1 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]
2016-09-19T11:56:40.432Z INFO  [CmdLineTool] Running with JVM arguments: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configurationFile=file:///etc/graylog/server/log4j2.xml -Djava.library.path=/usr/share/graylog-server/lib/sigar -Dgray
log2.installation_source=deb
2016-09-19T11:56:44.292Z INFO  [InputBufferImpl] Message journal is enabled.
2016-09-19T11:56:44.339Z INFO  [NodeId] Node ID: 015f0fd4-3b92-4fe9-bab1-d26e7b67642a
2016-09-19T11:56:44.703Z INFO  [LogManager] Loading logs.
2016-09-19T11:56:44.708Z INFO  [LogManager] Logs loading complete.
2016-09-19T11:56:44.794Z INFO  [LogManager] Created log for partition [messagejournal,0] in /var/lib/graylog-server/journal with properties {file.delete.delay.ms -> 60000, compact -> false, max.message.bytes -> 2147483647, min.insync.replicas -> 1, segment.jitter.ms -> 0, index.interval.bytes -> 4096, min.cleanable.dirty.ratio -> 0.5, unclean.leader.election.enable -> tru
e, retention.bytes -> 5368709120, delete.retention.ms -> 86400000, flush.ms -> 60000, segment.bytes -> 104857600, segment.ms -> 3600000, retention.ms -> 43200000, flush.messages -> 1000000, segment.index.bytes -> 1048576}.
2016-09-19T11:56:44.794Z INFO  [KafkaJournal] Initialized Kafka based journal at /var/lib/graylog-server/journal
2016-09-19T11:56:44.834Z INFO  [InputBufferImpl] Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
2016-09-19T11:56:44.877Z INFO  [cluster] Cluster created with settings {hosts=[[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017], mode=MULTIPLE, requiredClusterType=REPLICA_SET, serverSelectionTimeout='30000 ms', maxWaitQueueSize=5000, requiredReplicaSetName='graylogDist'}
2016-09-19T11:56:44.877Z INFO  [cluster] Adding discovered server [xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017 to client view of cluster
2016-09-19T11:56:44.976Z INFO  [cluster] No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
2016-09-19T11:57:03.029Z INFO  [cluster] Exception in monitor thread while connecting to server [xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:116) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.net.NoRouteToHostException: No route to host
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_101]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_101]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_101]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_101]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_101]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_101]
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[graylog.jar:?]
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[graylog.jar:?]
        ... 3 more
2016-09-19T11:57:14.977Z ERROR [MongoConnectionProvider] Error connecting to MongoDB: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{address=[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017, type=UNKNOWN, state=CONNECTING, exception={com.mong
odb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.NoRouteToHostException: No route to host}}]
2016-09-19T11:57:15.562Z INFO  [node] [graylog-015f0fd4-3b92-4fe9-bab1-d26e7b67642a] version[2.3.5], pid[1883], build[90f439f/2016-07-27T10:36:52Z]
2016-09-19T11:57:15.562Z INFO  [node] [graylog-015f0fd4-3b92-4fe9-bab1-d26e7b67642a] initializing ...
2016-09-19T11:57:15.567Z INFO  [plugins] [graylog-015f0fd4-3b92-4fe9-bab1-d26e7b67642a] modules [], plugins [graylog-monitor], sites []
2016-09-19T11:57:17.417Z INFO  [node] [graylog-015f0fd4-3b92-4fe9-bab1-d26e7b67642a] initialized
2016-09-19T11:57:17.436Z INFO  [cluster] No server chosen by WritableServerSelector from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket},
caused by {java.net.NoRouteToHostException: No route to host}}]}. Waiting for 30000 ms before timing out
2016-09-19T11:57:39.173Z INFO  [cluster] Exception in monitor thread while connecting to server [xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017
com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='jenkins', source='graylog', password=<hidden>, mechanismProperties={}}
        at com.mongodb.connection.SaslAuthenticator.wrapInMongoSecurityException(SaslAuthenticator.java:157) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator.access$200(SaslAuthenticator.java:37) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:66) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:44) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator.doAsSubject(SaslAuthenticator.java:162) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:44) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultAuthenticator.authenticate(DefaultAuthenticator.java:32) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:116) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:116) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server [xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017. The full response is { "ok" : 0.0, "code" : 18, "errmsg" : "Authentication failed." }
        at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:170) ~[graylog.jar:?]
        at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123) ~[graylog.jar:?]
        at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:117) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator.access$000(SaslAuthenticator.java:37) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:50) ~[graylog.jar:?]
        ... 9 more
2016-09-19T11:57:47.524Z INFO  [Version] HV000001: Hibernate Validator 5.2.4.Final
2016-09-19T11:57:47.608Z INFO  [cluster] No server chosen by WritableServerSelector from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating Mong
oCredential{mechanism=null, userName='jenkins', source='graylog', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server [xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017. The full response is { "ok" : 0.0, "code" : 18, "errmsg" : "Authentication failed." }}}]}. Waiting for
30000 ms before timing out
2016-09-19T11:57:50.645Z INFO  [connection] Opened connection [connectionId{localValue:30, serverValue:29}] to [xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017
2016-09-19T11:57:50.647Z INFO  [cluster] Monitor thread successfully connected to server with description ServerDescription{address=[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 9]}, minWireVersion=0, maxWireVersion=4, maxDocumentSize=16777216, roundTripTimeNanos=1321044, setNa
me='graylogDist', canonicalAddress=[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017, hosts=[[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017], passives=[], arbiters=[], primary='[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017', tagSet=TagSet{[]}, electionId=7fffffff0000000000000001, setVersion=1}
2016-09-19T11:57:50.648Z WARN  [event] Exception thrown raising server description changed event to listener com.mongodb.connection.MultiServerCluster$DefaultServerStateListener@53dab84d
java.lang.NumberFormatException: For input string: "1b3b:fffc:0103:7156:a7ec:85ad:e85e]:27017"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
        at com.mongodb.ServerAddress.sameHost(ServerAddress.java:226) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.handleReplicaSetMemberChanged(MultiServerCluster.java:217) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.onChange(MultiServerCluster.java:164) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.access$100(MultiServerCluster.java:46) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster$DefaultServerStateListener.serverDescriptionChanged(MultiServerCluster.java:125) ~[graylog.jar:?]
        at com.mongodb.event.ServerEventMulticaster.serverDescriptionChanged(ServerEventMulticaster.java:92) [graylog.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerStateListener.stateChanged(DefaultServer.java:196) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.sendStateChangedEvent(DefaultServerMonitor.java:197) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2016-09-19T11:57:51.150Z WARN  [event] Exception thrown raising server description changed event to listener com.mongodb.connection.MultiServerCluster$DefaultServerStateListener@53dab84d
java.lang.NumberFormatException: For input string: "1b3b:fffc:0103:7156:a7ec:85ad:e85e]:27017"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
        at com.mongodb.ServerAddress.sameHost(ServerAddress.java:226) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.handleReplicaSetMemberChanged(MultiServerCluster.java:217) ~[graylog.jar:?]
 at com.mongodb.ServerAddress.sameHost(ServerAddress.java:226) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.handleReplicaSetMemberChanged(MultiServerCluster.java:217) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.onChange(MultiServerCluster.java:164) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.access$100(MultiServerCluster.java:46) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster$DefaultServerStateListener.serverDescriptionChanged(MultiServerCluster.java:125) ~[graylog.jar:?]
        at com.mongodb.event.ServerEventMulticaster.serverDescriptionChanged(ServerEventMulticaster.java:92) [graylog.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerStateListener.stateChanged(DefaultServer.java:196) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.sendStateChangedEvent(DefaultServerMonitor.java:197) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2016-09-19T11:57:51.652Z WARN  [event] Exception thrown raising server description changed event to listener com.mongodb.connection.MultiServerCluster$DefaultServerStateListener@53dab84d
java.lang.NumberFormatException: For input string: "1b3b:fffc:0103:7156:a7ec:85ad:e85e]:27017"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
        at com.mongodb.ServerAddress.sameHost(ServerAddress.java:226) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.handleReplicaSetMemberChanged(MultiServerCluster.java:217) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.onChange(MultiServerCluster.java:164) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.access$100(MultiServerCluster.java:46) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster$DefaultServerStateListener.serverDescriptionChanged(MultiServerCluster.java:125) ~[graylog.jar:?]
        at com.mongodb.event.ServerEventMulticaster.serverDescriptionChanged(ServerEventMulticaster.java:92) [graylog.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerStateListener.stateChanged(DefaultServer.java:196) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.sendStateChangedEvent(DefaultServerMonitor.java:197) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2016-09-19T11:57:52.155Z WARN  [event] Exception thrown raising server description changed event to listener com.mongodb.connection.MultiServerCluster$DefaultServerStateListener@53dab84d
java.lang.NumberFormatException: For input string: "1b3b:fffc:0103:7156:a7ec:85ad:e85e]:27017"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
        at com.mongodb.ServerAddress.sameHost(ServerAddress.java:226) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.handleReplicaSetMemberChanged(MultiServerCluster.java:217) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.onChange(MultiServerCluster.java:164) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.access$100(MultiServerCluster.java:46) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster$DefaultServerStateListener.serverDescriptionChanged(MultiServerCluster.java:125) ~[graylog.jar:?]
        at com.mongodb.event.ServerEventMulticaster.serverDescriptionChanged(ServerEventMulticaster.java:92) [graylog.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerStateListener.stateChanged(DefaultServer.java:196) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.sendStateChangedEvent(DefaultServerMonitor.java:197) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2016-09-19T11:57:52.664Z WARN  [event] Exception thrown raising server description changed event to listener com.mongodb.connection.MultiServerCluster$DefaultServerStateListener@53dab84d
java.lang.NumberFormatException: For input string: "1b3b:fffc:0103:7156:a7ec:85ad:e85e]:27017"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
        at com.mongodb.ServerAddress.sameHost(ServerAddress.java:226) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.handleReplicaSetMemberChanged(MultiServerCluster.java:217) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.onChange(MultiServerCluster.java:164) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.access$100(MultiServerCluster.java:46) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster$DefaultServerStateListener.serverDescriptionChanged(MultiServerCluster.java:125) ~[graylog.jar:?]
        at com.mongodb.event.ServerEventMulticaster.serverDescriptionChanged(ServerEventMulticaster.java:92) [graylog.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerStateListener.stateChanged(DefaultServer.java:196) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.sendStateChangedEvent(DefaultServerMonitor.java:197) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2016-09-19T11:57:53.167Z WARN  [event] Exception thrown raising server description changed event to listener com.mongodb.connection.MultiServerCluster$DefaultServerStateListener@53dab84d
java.lang.NumberFormatException: For input string: "1b3b:fffc:0103:7156:a7ec:85ad:e85e]:27017"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
        at com.mongodb.ServerAddress.sameHost(ServerAddress.java:226) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.handleReplicaSetMemberChanged(MultiServerCluster.java:217) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.onChange(MultiServerCluster.java:164) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.access$100(MultiServerCluster.java:46) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster$DefaultServerStateListener.serverDescriptionChanged(MultiServerCluster.java:125) ~[graylog.jar:?]
        at com.mongodb.event.ServerEventMulticaster.serverDescriptionChanged(ServerEventMulticaster.java:92) [graylog.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerStateListener.stateChanged(DefaultServer.java:196) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.sendStateChangedEvent(DefaultServerMonitor.java:197) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2016-09-19T11:57:53.670Z WARN  [event] Exception thrown raising server description changed event to listener com.mongodb.connection.MultiServerCluster$DefaultServerStateListener@53dab84d
java.lang.NumberFormatException: For input string: "1b3b:fffc:0103:7156:a7ec:85ad:e85e]:27017"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
        at com.mongodb.ServerAddress.sameHost(ServerAddress.java:226) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.handleReplicaSetMemberChanged(MultiServerCluster.java:217) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.onChange(MultiServerCluster.java:164) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.access$100(MultiServerCluster.java:46) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster$DefaultServerStateListener.serverDescriptionChanged(MultiServerCluster.java:125) ~[graylog.jar:?]
        at com.mongodb.event.ServerEventMulticaster.serverDescriptionChanged(ServerEventMulticaster.java:92) [graylog.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerStateListener.stateChanged(DefaultServer.java:196) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.sendStateChangedEvent(DefaultServerMonitor.java:197) [graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2016-09-19T11:57:54.181Z WARN  [event] Exception thrown raising server description changed event to listener com.mongodb.connection.MultiServerCluster$DefaultServerStateListener@53dab84d
java.lang.NumberFormatException: For input string: "1b3b:fffc:0103:7156:a7ec:85ad:e85e]:27017"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
        at com.mongodb.ServerAddress.sameHost(ServerAddress.java:226) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.handleReplicaSetMemberChanged(MultiServerCluster.java:217) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.onChange(MultiServerCluster.java:164) ~[graylog.jar:?]
        at com.mongodb.connection.MultiServerCluster.access$100(MultiServerCluster.java:46) ~[graylog.jar:?]
```

but on the mongo db i got this
###### 

2016-09-19T11:46:06.067Z I NETWORK  [initandlisten] connection accepted from 2003:1b3b:fffc:11b:4252:1098:c965:6dd1:43122 #36 (1 connection now open)
2016-09-19T11:46:06.594Z I ACCESS   [conn36] Successfully authenticated as principal jenkins on graylog
2016-09-19T11:46:06.604Z I NETWORK  [initandlisten] connection accepted from 2003:1b3b:fffc:11b:4252:1098:c965:6dd1:43124 #37 (2 connections now open)
2016-09-19T11:46:06.610Z I NETWORK  [conn36] end connection 2003:1b3b:fffc:11b:4252:1098:c965:6dd1:43122 (1 connection now open)
2016-09-19T11:46:06.667Z I ACCESS   [conn37] Successfully authenticated as principal jenkins on graylog
2016-09-19T11:46:20.731Z I NETWORK  [conn37] end connection 2003:1b3b:fffc:11b:4252:1098:c965:6dd1:43124 (0 connections now open)
###### 
## My Environment

- Graylog Version: 2.1.1
- Elasticsearch Version: 2.4.0
- MongoDB Version: 3.2.9
- Operating System: ubuntu 14.04
- Browser version:

**Comment by joschi** [comment]
For reference: https://groups.google.com/d/msg/graylog2/LpoDQfGWe3A/3uuiuDJRBQAJ

**Comment by joschi** [comment]
@zaibfridi Please post the line containing `mongodb_uri` from your Graylog configuration file.

**Comment by jalogisch** [comment]
@zaibfridi 

I have my multi-note environment in dual-stack mode running. Additional I have a working DNS.

My replica set is configured with DNS.

<details>
```

gl01:PRIMARY> rs.status()
{
	"set" : "gl01",
	"date" : ISODate("2016-09-19T15:02:38.930Z"),
	"myState" : 1,
	"term" : NumberLong(2404),
	"heartbeatIntervalMillis" : NumberLong(2000),
	"members" : [
		{
			"_id" : 0,
			"name" : "gm-01-u.fritz.local:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 516088,
			"optime" : {
				"ts" : Timestamp(1474297358, 3),
				"t" : NumberLong(2404)
			},
			"optimeDate" : ISODate("2016-09-19T15:02:38Z"),
			"lastHeartbeat" : ISODate("2016-09-19T15:02:38.918Z"),
			"lastHeartbeatRecv" : ISODate("2016-09-19T15:02:37.628Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "gm-01-c.fritz.local:27017",
			"configVersion" : 3
		},
		{
			"_id" : 1,
			"name" : "gm-01-d.fritz.local:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 516843,
			"optime" : {
				"ts" : Timestamp(1474297356, 3),
				"t" : NumberLong(2404)
			},
			"optimeDate" : ISODate("2016-09-19T15:02:36Z"),
			"lastHeartbeat" : ISODate("2016-09-19T15:02:37.067Z"),
			"lastHeartbeatRecv" : ISODate("2016-09-19T15:02:38.384Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "gm-01-c.fritz.local:27017",
			"configVersion" : 3
		},
		{
			"_id" : 2,
			"name" : "gm-01-c.fritz.local:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 517275,
			"optime" : {
				"ts" : Timestamp(1474297358, 3),
				"t" : NumberLong(2404)
			},
			"optimeDate" : ISODate("2016-09-19T15:02:38Z"),
			"electionTime" : Timestamp(1473781281, 1),
			"electionDate" : ISODate("2016-09-13T15:41:21Z"),
			"configVersion" : 3,
			"self" : true
		}
	],
	"ok" : 1
}

```
</details>

When I use this mongodb_uri connection is working without issue

> mongodb_uri = mongodb://[fe80::3433:66ff:fe36:3531]:27017,[fe80::3037:38ff:fe32:6434]:27017,[fe80::6461:64ff:fe35:6237]:27017/gl01

But I have used this only for testing your issue - I prefer the DNS view as this is for me more human readable.

**Comment by zaibfridi** [comment]
@jalogisch 

for testing i am also having the
one elasticsearch 
one mongodb 
one graylog-server and separate graylog-web

i also have the output
`echo 'rs.status();' | mongo --ipv6 "[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017"
MongoDB shell version: 3.2.9
connecting to: [xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017/test
{
	"set" : "graylogDist",
	"date" : ISODate("2016-09-19T15:57:16.725Z"),
	"myState" : 1,
	"term" : NumberLong(1),
	"heartbeatIntervalMillis" : NumberLong(2000),
	"members" : [
		{
			"_id" : 1,
			"name" : "[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 14382,
			"optime" : {
				"ts" : Timestamp(1474286269, 4),
				"t" : NumberLong(1)
			},
			"optimeDate" : ISODate("2016-09-19T11:57:49Z"),
			"electionTime" : Timestamp(1474286264, 2),
			"electionDate" : ISODate("2016-09-19T11:57:44Z"),
			"configVersion" : 1,
			"self" : true
		}
	],
	"ok" : 1
}
bye`

my question is that why i get the WARNS in graylog-server like you can see on above comment.

**Comment by zaibfridi** [comment]
@joschi 
in /etc/graylog/server/server.conf
mongodb_uri = mongodb://username:password@[xxxx:xxxx:xxxx:xxxx:7156:a7ec:85ad:e85e]:27017/graylog?replicaSet=graylogDist

**Comment by kroepke** [comment]
This issue needs fixes in the MongoDB driver. As soon as there is a version we can update.

**Comment by bernd** [comment]
Closing this. We updated the MongoDB several times since Sep 2016 and it is most probably fixed already. Please re-open if this issue still exists in 2.5 and the upcoming 3.0 releases. Thank you!
