### ISSUE TITLE
ProcessBuffer: fault in a recent unsafe memory access

### ISSUE THREAD

**Issue by kallisti5** [Graylog2/graylog2-server#2928]
Saw an issue with nodes processing roughly 800-1000 eps encountering a "a fault occurred in a recent unsafe memory access operation in compiled Java code" error. One node stopped processing log events until graylog was restarted.

## Current Behavior
Log events were collected, but not processed.  Inbound log data was placed into the message journal until it ran out of space.  Processing buffer was idle at full.

## Possible Solution
Found and restarted graylog-server node

## Steps to Reproduce (for bugs)
Collect logs. Running for a few months. No changes around time of issue.

## Your Environment

* Graylog 2.1.1
* Elasticsearch 2.4.0 (now upgraded to 2.4.1)
* Operating System: CentOS
* Oracle java: 1.8.0_91-b14

Two graylog-server nodes, elasticsearch running on one of those nodes. One UDP syslog input on each node.

Logs leading up to issue attached.  The unsafe memory access error showed up in the logs of both nodes, however only the second node stopped processing at the time of the event.
[graylog-processing-lock.txt](https://github.com/Graylog2/graylog2-server/files/514750/graylog-processing-lock.txt)

There was also a "An I/O error has occurred while writing a response message entity to the container output stream." error that could of been related.

**Comment by joschi** [comment]
```
2016-10-05T00:00:01.743-05:00 WARN  [ProcessBuffer] Unable to process event MessageEvent{raw=null, message=source: CENSORED | message: 2016/10/05 00:00:01.713682 route.go:268: 127.0.0.1:60148 - [][][] - 200 - 259.706715ms - /CENSORED/.* - https://CENSORED { process_id: 25445 | go_script: route.go | level: 6 | gl2_remote_ip: CENSORED | http_response_time: 259.706715 | gl2_remote_port: 44491 | src_ipv4: 127.0.0.1 | uuid_generic: CENSORED | gl2_source_input: 5672f7e5b3a2f2d7c07bb9d5 | gl2_source_node: d2636a89-c572-4717-b7e8-f7cada1266c6 | _id: 927956e1-8ab8-11e6-bcfd-0cc47abce8b5 | facility: syslogd | timestamp: 2016-10-05T00:00:01.713-05:00 | http_response_code: 200 }, messages=null}, sequence 176217855
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at com.maxmind.db.Reader.resolveDataPointer(Reader.java:243) ~[?:?]
        at com.maxmind.db.Reader.get(Reader.java:150) ~[?:?]
        at com.maxmind.geoip2.DatabaseReader.get(DatabaseReader.java:155) ~[?:?]
        at com.maxmind.geoip2.DatabaseReader.city(DatabaseReader.java:206) ~[?:?]
        at org.graylog.plugins.map.geoip.GeoIpResolverEngine.extractGeoLocationInformation(GeoIpResolverEngine.java:99) ~[?:?]
        at org.graylog.plugins.map.geoip.GeoIpResolverEngine.filter(GeoIpResolverEngine.java:77) ~[?:?]
[…]
2016-10-05T00:00:01.766-05:00 WARN  [ProcessBuffer] Unable to process event MessageEvent{raw=null, message=source: CENSORED | message: 2016/10/05 00:00:01.735274 route.go:268: 127.0.0.1:33894 - [][][] - 200 - 256.749849ms - /CENSORED/.* - https://CENSORED { process_id: 17383 | go_script: route.go | level: 6 | gl2_remote_ip: CENSORED | http_response_time: 256.749849 | gl2_remote_port: 49987 | src_ipv4: 127.0.0.1 | uuid_generic: CENSORED | gl2_source_input: 5672f7e5b3a2f2d7c07bb9d5 | gl2_source_node: d2636a89-c572-4717-b7e8-f7cada1266c6 | _id: 927cd950-8ab8-11e6-bcfd-0cc47abce8b5 | facility: syslogd | timestamp: 2016-10-05T00:00:01.735-05:00 | http_response_code: 200 }, messages=null}, sequence 176217856
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at com.maxmind.geoip2.DatabaseReader.city(DatabaseReader.java:206) ~[?:?]
        at org.graylog.plugins.map.geoip.GeoIpResolverEngine.extractGeoLocationInformation(GeoIpResolverEngine.java:99) ~[?:?]
        at org.graylog.plugins.map.geoip.GeoIpResolverEngine.filter(GeoIpResolverEngine.java:77) ~[?:?]
[…]
2016-10-05T00:00:01.801-05:00 WARN  [ProcessBuffer] Unable to process event MessageEvent{raw=null, message=source: CENSORED | message: 2016/10/05 00:00:01.774537 tserver.go:409: Connected: CENSORED:40695 { process_id: 12254 | go_script: tserver.go | level: 6 | gl2_remote_ip: CENSORED | gl2_remote_port: 48660 | src_ipv4: CENSORED | gl2_source_input: 5672f7e5b3a2f2d7c07bb9d5 | gl2_source_node: d2636a89-c572-4717-b7e8-f7cada1266c6 | _id: 92825791-8ab8-11e6-bcfd-0cc47abce8b5 | facility: syslogd | timestamp: 2016-10-05T00:00:01.774-05:00 }, messages=null}, sequence 176217857
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at com.maxmind.geoip2.DatabaseReader.city(DatabaseReader.java:206) ~[?:?]
        at org.graylog.plugins.map.geoip.GeoIpResolverEngine.extractGeoLocationInformation(GeoIpResolverEngine.java:99) ~[?:?]
```

This looks like a bug in the Maxmind GeoIP2 library or the Java VM you're using.

Try upgrading to the latest JRE (Java 8u102 at the time of writing) and make sure that the Maxmind GeoIP database file isn't corrupt.

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
