### ISSUE TITLE
Extractor Not able to load message

### ISSUE THREAD

**Issue by luckyb56** [Graylog2/graylog2-server#2946]
When I try to load a message to add extractors for an input, it doesn't load any message. In chrome's inspect console I see this error:

```
Unhandled rejection Invariant Violation: findComponentRoot(..., .0.2.0.0.0.1.0.0.3.0.1.0.0.0.0.0.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ".
    at n (http://1.1.1.1/vendor.js:405:9453)
    at Object.findComponentRoot (http://1.1.1.1/vendor.js:12:12296)
    at Object.findReactNodeByID (http://1.1.1.1/vendor.js:12:11592)
    at Object.u [as getNode] (http://1.1.1.1/vendor.js:12:4463)
    at y._updateDOMProperties (http://1.1.1.1/vendor.js:403:26765)
    at y.updateComponent (http://1.1.1.1/vendor.js:403:25514)
    at y.receiveComponent (http://1.1.1.1/vendor.js:403:24812)
    at Object.receiveComponent (http://1.1.1.1/vendor.js:13:24)
    at p._updateRenderedComponent (http://1.1.1.1/vendor.js:403:12139)
    at p._performComponentUpdate (http://1.1.1.1/vendor.js:403:11900)
    at p.updateComponent (http://1.1.1.1/vendor.js:403:11178)
    at p.i [as updateComponent] (http://1.1.1.1/vendor.js:12:18757)
    at p.receiveComponent (http://1.1.1.1/vendor.js:403:10216)
    at Object.receiveComponent (http://1.1.1.1/vendor.js:13:24)
    at Object.updateChildren (http://1.1.1.1/vendor.js:403:3283)
    at y._reconcilerUpdateChildren (http://1.1.1.1/vendor.js:404:14379)
    at y._updateChildren (http://1.1.1.1/vendor.js:404:15304)
    at y.updateChildren (http://1.1.1.1/vendor.js:404:15179)
    at y._updateDOMChildren (http://1.1.1.1/vendor.js:403:27437)
    at y.updateComponent (http://1.1.1.1/vendor.js:403:25552)
    at y.receiveComponent (http://1.1.1.1/vendor.js:403:24812)
    at Object.receiveComponent (http://1.1.1.1/vendor.js:13:24)
    at p._updateRenderedComponent (http://1.1.1.1/vendor.js:403:12139)
    at p._performComponentUpdate (http://1.1.1.1/vendor.js:403:11900)
    at p.updateComponent (http://1.1.1.1/vendor.js:403:11178)
    at p.i [as updateComponent] (http://1.1.1.1/vendor.js:12:18757)
    at p.receiveComponent (http://1.1.1.1/vendor.js:403:10216)
    at Object.receiveComponent (http://1.1.1.1/vendor.js:13:24)
    at Object.updateChildren (http://1.1.1.1/vendor.js:403:3283)
    at y._reconcilerUpdateChildren (http://1.1.1.1/vendor.js:404:14379)
    at y._updateChildren (http://1.1.1.1/vendor.js:404:15304)
    at y.updateChildren (http://1.1.1.1/vendor.js:404:15179)
    at y._updateDOMChildren (http://1.1.1.1/vendor.js:403:27437)
    at y.updateComponent (http://1.1.1.1/vendor.js:403:25552)
    at y.receiveComponent (http://1.1.1.1/vendor.js:403:24812)
    at Object.receiveComponent (http://1.1.1.1/vendor.js:13:24)
    at p._updateRenderedComponent (http://1.1.1.1/vendor.js:403:12139)
    at p._performComponentUpdate (http://1.1.1.1/vendor.js:403:11900)
    at p.updateComponent (http://1.1.1.1/vendor.js:403:11178)
    at p.i [as updateComponent] (http://1.1.1.1/vendor.js:12:18757)
    at p.receiveComponent (http://1.1.1.1/vendor.js:403:10216)
```

The example message which I'm trying to load is http://pastebin.com/zj6SL1EX 
## Environment
- Graylog Version: 2.0.3
- Elasticsearch Version: 2.3.3
- MongoDB Version: 
- Operating System: OSX 10.10.5
- Browser version: Chrome 53.0.2785.143

What could be the issue? Any pointers?

**Comment by joschi** [comment]
@luckyb56 Please upgrade to Graylog 2.1.1 and check if the issue exists there as well.

**Comment by luckyb56** [comment]
@joschi I upgraded to 2.1.1, but still get the same error.

**Comment by edmundoa** [comment]
I quickly looked into this using in 2.1.1, and could not reproduce the issue. Basically I sent the JSON message into a Raw TCP input, and then I was able to load that message in the extractor page.

@luckyb56 we need more information on this issue:

- Do you alter the message using extractors or pipelines? If so, how?
- Which input type is receiving the message?
- Does Graylog show any errors when you expand that message in the search page?

**Comment by luckyb56** [comment]
I have created 'nested' mapping for packetbeat_dns_answers. 
The information which you asked for:
- I don't alter the message
- Using beats input plugin for receiving the message
- Did you mean expand on the left column? I have attached a screen shot below how it would look.

![screen shot 2016-10-27 at 12 47 49 am](https://cloud.githubusercontent.com/assets/8121400/19741667/368e0e24-9bdf-11e6-82e2-28ea40a096e1.png)

**Comment by kroepke** [comment]
@edmundoa could you please check this one when you have time?

**Comment by joschi** [comment]
The issue with nested structures in the Beats plugin has been logged here: Graylog2/graylog-plugin-beats#3

**Comment by edmundoa** [comment]
I was playing a bit around and I could reproduce a couple of issues related to what @joschi mentioned, but I'm not entirely sure they are the same issue as this one.

@luckyb56 so far I have tried to reproduce the exception you kindly shared with us by clicking on the "Load message" button in the "Manage extractor" page. Could you please confirm this is exactly where you see that exception in your logs?

**Comment by luckyb56** [comment]
Yes, that's right. I didn't come across anywhere else.

**Comment by edmundoa** [comment]
@luckyb56 as I wasn't able to reproduce this issue so far, would you be so kind as to test if you see this same issue in [Graylog 2.2.0-beta](https://www.graylog.org/blog/77-announcing-graylog-2-2-0-beta-2)? We fixed a couple of other related issues and they may also solve this issue.

Thank you!

**Comment by bernd** [comment]
Closing this due to lack of feedback. Please re-open or create a new issue if you are still running into this.
