### ISSUE TITLE
Rest threads in deadlock

### ISSUE THREAD

**Issue by manuelluis** [Graylog2/graylog2-server#2966]
The graylog servers were not responding, all ``rest-workers``  were in the following backtrace:

```
"rest-worker-14" #542 daemon prio=5 os_prio=0 tid=0x00007fd87c009800 nid=0x420d runnable [0x00007fd60fc00000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        - locked <0x00000006acb3faa0> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        - locked <0x00000006acb402c0> (a sun.security.ssl.AppInputStream)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
        at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
        at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
        at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
        at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
        at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
        at okhttp3.RealCall.getResponse(RealCall.java:241)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
        at org.graylog2.rest.RemoteInterfaceProvider.lambda$get$0(RemoteInterfaceProvider.java:54)
        at org.graylog2.rest.RemoteInterfaceProvider$$Lambda$132/992876663.intercept(Unknown Source)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
        at okhttp3.RealCall.execute(RealCall.java:57)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at org.graylog2.shared.rest.resources.ProxiedResource.lambda$getForAllNodes$0(ProxiedResource.java:72)
        at org.graylog2.shared.rest.resources.ProxiedResource$$Lambda$129/1165443791.apply(Unknown Source)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
        at java.util.stream.Collectors$$Lambda$53/30589523.accept(Unknown Source)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.graylog2.shared.rest.resources.ProxiedResource.getForAllNodes(ProxiedResource.java:65)
        at org.graylog2.shared.rest.resources.ProxiedResource.getForAllNodes(ProxiedResource.java:58)
        at org.graylog2.rest.resources.cluster.ClusterMetricsResource.multipleMetricsAllNodes(ClusterMetricsResource.java:69)
        at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

and the log has multiple messages like this:

    2016-10-17T12:59:13.216+02:00 WARN  [ProxiedResource] Unable to call https://***:12900/system/metrics/multiple on node <6f2a5749-e52c-41b8-8682-835163ffce1b>, caught exception: timeout (class java.net.SocketTimeoutException)

The url and node-id is the same server, and the current machine.

## Possible Solution

The method ``org.graylog2.shared.rest.resources.ProxiedResource.getForAllNodes`` seems to call all nodes via the rest api, this is a problem because it's active on a request occupying a worker and need another worker in the same pool to get the response for this node.

If you have maximum of 16 rest workers, and if you have 16 simultaneous calls that make a call to the rest api (for example in getForAllNodes) in the same node, you would have a deadlock.

A possible solution could be to call the method locally (without making a http request) in the case  the node is the local server.

## Your Environment

Two graylog servers.

* Graylog Version: 2.0.3

**Comment by jalogisch** [comment]
please update to the latest Version of Graylog. 

Additional you can adjust the settings in your configuration: https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog.conf#L122

**Comment by manuelluis** [comment]
When the problem was happening I increased the number of thread from 16 to 32 and the problem continue. The problem stopped happening but I but I do not know root the cause, maybe to many web request o something that make the response slow.

I think that there is problem of starvation with the threads that make another request to the same server, if you have some delay in processing o some load you are in a deadlock. Perhaps I did not explain properly.

If you need, I have a thread dump when the server was locked.

**Comment by sycz** [comment]
Don't you think it's just JDK bug? E.g.: 
[https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8172578](url)
[https://bugs.openjdk.java.net/browse/JDK-8075484](url)
