### ISSUE TITLE
Cannot run Pipeline Processor function plugin when scope is set to 'provided'

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#2978]
When trying to build a Pipeline Processor function as a plugin and setting the `<scope>` to provided like this:

```
<dependency>
  <groupId>org.graylog.plugins</groupId>
  <artifactId>graylog-plugin-pipeline-processor</artifactId>
  <version>${graylog-pipelines.version}</version>
  <scope>provided</scope>
</dependency>
```

... then `graylog-server` will not start up and fail with this exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/graylog/plugins/pipelineprocessor/ast/functions/AbstractFunction
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.graylog.plugins.threatintel.ThreatIntelPluginModule.configure(ThreatIntelPluginModule.java:27)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.graylog2.shared.bindings.PluginBindings.configure(PluginBindings.java:51)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:60)
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379)
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:193)
	at org.graylog2.bootstrap.Main.main(Main.java:44)
Caused by: java.lang.ClassNotFoundException: org.graylog.plugins.pipelineprocessor.ast.functions.AbstractFunction
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
```

It works when not setting `<scope>` to `provided`.

## Your Environment

* Pipeline Processor Plugin: 1.1.1
* Graylog Version: 2.1.1
* Operating System: macOS 10.12 (Sierra)

**Comment by kroepke** [comment]
How does your `graylog-plugin.properties` file look like?

Does it contain 
```
# Do not disable this unless this plugin depends on another plugin!
isolated=true
```

**Comment by lennartkoopmann** [comment]
Thank you. :) Merging Graylog2/graylog-plugin-threatintel#3 now, which fixes this.
