### ISSUE TITLE
Some of the messages sent to Graylog server fails with java.util.zip.ZipException: invalid block type

### ISSUE THREAD

**Issue by yossisht** [Graylog2/graylog2-server#3082]
Hi,

We use Graylog by sending our Java Application logs in development environment to a Graylog Servers.
The error below occurs once or twice per second (which is less then 1% of the messages being sent to Graylog). 

Messages are being sent using UDP through NGNIX server which forward the messages to the Graylog servers.
The error is shown on all Graylog servers in the cluster.

Anyone have a lead on what might be causing it?

## Current Behavior
```
2016-11-10 16:05:03,688 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=70c1f570-a75f-11e6-b620-02799b63a91e, journalOffset=31136, codec=gelf, payloadSize=275, timestamp=2016-11-10T16:05:03.687Z}
java.util.zip.ZipException: invalid block type
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) ~[?:1.8.0_111]
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117) ~[?:1.8.0_111]
	at com.google.common.io.ByteStreams$LimitedInputStream.read(ByteStreams.java:640) ~[graylog.jar:?]
	at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[?:1.8.0_111]
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:110) ~[graylog.jar:?]
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:168) ~[graylog.jar:?]
	at org.graylog2.plugin.Tools.decompressGzip(Tools.java:232) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.gelf.GELFMessage.getJSON(GELFMessage.java:76) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:115) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:146) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:87) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.1.2
* Elasticsearch Version: 2.3.5
* MongoDB Version: 3.2
* Operating System: Docker 1.1 running on CentOS Linux 7
* Browser version: N/A

**Comment by joschi** [comment]
@yossisht How exactly are you sending these logs to Graylog, what kind of input did you create, and how did you configure the input?

**Comment by yossisht** [comment]
Hi @joschi 

We are sending the data over the network using LogBack over UDP into a GELF input,
we are using the following library to structure and send the data in GELF format to Graylog.
https://github.com/Moocar/logback-gelf

The input is configured with:
Decompress limit set to 8388608
Received buffer  is 262144

Thank you!

**Comment by kroepke** [comment]
To verify: test chunked messages vs various ZLIB compression levels.

**Comment by joschi** [comment]
@yossisht I've been looking into this issue but wasn't able to reproduce it.

I've been sending 1,000,000 messages using logback-gelf via GELF UDP into Graylog (also chunked messages) but the error you've mentioned didn't occur.

Make sure that your network is working fine (it looks like some lost or corrupted UDP packets to me) or switch to GELF TCP as described here: https://github.com/Moocar/logback-gelf#tcp

**Issue3082.java**
```java
package org.example.issue3082;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;

public class Issue3082 {
    private static final Logger log = LoggerFactory.getLogger(Issue3082.class);

    @Test
    public void sendMessages() {
        final StringBuilder sb = new StringBuilder(8192);
        for (int size = 0; size < 8192; size++) {
            sb.append((char)('a' + size % 26));
        }
        final String random = sb.toString();
        for (int i = 0; i < 1_000_000; i++) {
            MDC.put("random", random);
            log.info("Test message {}", i);
            MDC.clear();
        }
    }
}
```

**logback.xml**
```xml
<configuration>
    <appender name="gelf-udp" class="me.moocar.logbackgelf.GelfUDPAppender">
        <remoteHost>127.0.0.1</remoteHost>
        <port>12201</port>
        <encoder class="me.moocar.logbackgelf.GZIPEncoder">
            <layout class="me.moocar.logbackgelf.GelfLayout">
                <useLoggerName>true</useLoggerName>
                <useThreadName>true</useThreadName>
                <useMarker>true</useMarker>
                <host>Test</host>
                <includeFullMDC>true</includeFullMDC>
            </layout>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="gelf-udp"/>
    </root>
</configuration>
```
