### ISSUE TITLE
Possible Cause Of Memory Leak Graylog 2(v2.1.2)

### ISSUE THREAD

**Issue by yogeshrao** [Graylog2/graylog2-server#3116]
Hi,

We have just started using graylog2 (2.1.2) on centos 7. I keep getting below exception after few hours 
```
2016-11-24T17:25:13.737+05:30 WARN  [ProxiedResource] Unable to call http://10.101.160.95:9000/api/system on node <b8d88e71-dbbb-44ee-9951-2bcdb45b047a>
java.net.SocketTimeoutException: timeout
        at okio.Okio$3.newTimeoutException(Okio.java:210) ~[graylog.jar:?]
        at okio.AsyncTimeout.exit(AsyncTimeout.java:288) ~[graylog.jar:?]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:242) ~[graylog.jar:?]
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325) ~[graylog.jar:?]
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314) ~[graylog.jar:?]
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210) ~[graylog.jar:?]
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186) ~[graylog.jar:?]
        at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) ~[graylog.jar:?]
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at org.graylog2.rest.RemoteInterfaceProvider.lambda$get$0(RemoteInterfaceProvider.java:59) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) ~[graylog.jar:?]
        at okhttp3.RealCall.execute(RealCall.java:60) ~[graylog.jar:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174) ~[graylog.jar:?]
        at org.graylog2.shared.rest.resources.ProxiedResource.lambda$null$0(ProxiedResource.java:76) ~[graylog.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_102]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_102]
        at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[?:1.8.0_102]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_102]
        at okio.Okio$2.read(Okio.java:138) ~[graylog.jar:?]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:238) ~[graylog.jar:?]
        ... 29 more
2016-11-24T17:25:13.751+05:30 WARN  [jvm] [graylog-b8d88e71-dbbb-44ee-9951-2bcdb45b047a] [gc][old][19743][529] duration [12.4s], collections [1]/[12.6s], total [12.4s]/[10.4m], memory [3.7gb]->[3.7gb]/[3.8gb], all_pools {[young] [1.6gb]->[1.6gb]/[1.6gb]}{[survivor] [188.7mb]->[191.2mb]/[204.7mb]}{[old] [1.9gb]->[1.9gb]/[2gb]}
2016-11-24T17:25:13.821+05:30 INFO  [BeatsCodec]  inside decodeMessagesRawMessage{id=52182873-b20e-11e6-9b98-14feb5ea6076, journalOffset=960249, codec=beats, payloadSize=4169, timestamp=2016-11-24T06:22:05.798Z, remoteAddress=/10.101.160.6:49324}
```

Heap Size set for Graylog2 is 4G, I noticed the heap size jumps up from 1.5G to 4G as soon as the exceptions are encountered, eventually leading to slower GC's and finally ends up unresponsive.

all the buffer processors are set to 1
process_buffer and output buffer are set to 32768

Graylog is configured on a Core 2 Duo machine with 8GB Ram and is pumping data into 3 elasticsearch (clustered) instances.

**Comment by pramodanarase** [comment]
+1

**Comment by kroepke** [comment]
@yogeshrao How many messages per second is this node processing and are the messages very large? (much larger than the 4k mentioned in the log entry)

12.4 seconds of garbage collection will certainly destroy the performance of the system, and the timeout exception is only a symptom of something else.

What kind of inputs are you running?
Any special plugins?

Thanks!

**Comment by yogeshrao** [comment]
Hello @kroepke ,

Thank you for your response

The message size is in the range of 3-4K in JSON format. We push around 4 GB of data to Graylog2 using sidecar collector.

We had a requirement to emit multiple records from the single record received and we used graylog-plugin-beats-1.1.1  for that with very little customization. 

To be honest I too was surprized by the GC times but again thought it was pretty normal for graylog which is processing huge data load.

Do let me know incase you need any more info ...

Thank you!

**Comment by kroepke** [comment]
Typically Graylog does not keep too much data in heap, precisely for this reason.
Depending on your input buffer (which by default is 65k), the other buffers and your message sizes at full utilization Graylog will use `((32 768 * 2) + 65 536) * 4 kb = 524.28800 megabytes` of memory just for the incoming data.
Of course there's overhead from processing and it might need to copy some strings, so that number can easily be twice as high.
We haven't seen an actual memory leak in a long time (which doesn't mean this one cannot be one, of course), so typically we recommend:
* smaller ring_size (which keeps the amount of resident messages low)
* playing with the output batch size to get rid of messages quicker (but this can actually increase memory usage, too!)
* slightly increase the processbuffer number (in your case to 2) to get rid of data faster. Might be useless if you don't actually do processing for beats data, then I'd increase the outputbuffer processors to 2 to get rid of data quicker, if you have write capacity in elasticsearch.

How is the journal size?

**Comment by yogeshrao** [comment]
@kroepke couple of things

1. buffer size is not default (65K) we got it down to 32768
2. Based on the GC time which has been logged we can see that nothing got collected.
3. Journal Size at the beginning was around 4-5GB and then it was declining. 

This very incident happened at the very end of processing around 26k messages to be processed till then only 1.4G Heap was being used as per the metrics. Then there was sudden spike in Heap (which claimed all the remaining space) not sure if graylog-web is the originator for these leaks.

I plan to run the dump over the weekend with web disabled and see if its recurs.

**Comment by yogeshrao** [comment]
I ran the dump with web disabled and noticed that after couple of hours GrayLog didn't go down but was busy running back to back GC's with stalls around 12s to 15s.

If i need to profile to figure out contents of the heap, is there any configuration somewhere which can help me attach Java Flight Recorder or any other profiler?

**Comment by kroepke** [comment]
@yogeshrao Please see https://docs.oracle.com/javacomponents/jmc-5-4/jfr-runtime-guide/run.htm#JFRUH176 for the flags you need to add to the startup script (or set `JAVA_OPTS` if you use the default script from the tarballs).

So far I've only seen this problem with very large messages. Of course I don't know what changes you have made to the beats input, but it seems unlikely that it would trigger such a leak.

**Comment by kroepke** [comment]
@yogeshrao Any updates?

**Comment by yogeshrao** [comment]
@kroepke I didnt get much time last week to work on this.. I should have some update for you by end of this week.

**Comment by yogeshrao** [comment]
@kroepke got some updates of my new run and this time i monitored using VisualVM

Heap Overview
![graylog1](https://cloud.githubusercontent.com/assets/10163027/20954896/ff6b4244-bc64-11e6-8f68-a70dbbaad0a0.JPG)

Per Thread Allocations
![graylog2](https://cloud.githubusercontent.com/assets/10163027/20954913/1e3a73a2-bc65-11e6-86cf-1001d17820d2.JPG)

Heap Contents
![graylog3](https://cloud.githubusercontent.com/assets/10163027/20954922/2f9f744e-bc65-11e6-8a74-11d2055965b8.JPG)

I also looked into Graylog logs during the 21:56 - 21.59 IST timeframe and couldn't find any exception or issues logged, It was working as normal.

Based on above I could only see that the ProcessBufferProcessor was ever growing, not sure if it's designed to release contents. Is the above heap state normal? can you provide me any pointers which can help troubleshoot the issue?

Regards,
-Yogesh

**Comment by yogeshrao** [comment]
@kroepke 

Just checking in case you have any pointers for me...

Regards,
-Yogesh

**Comment by kroepke** [comment]
@yogeshrao Sorry, was off for a few days :)

The charts look like some large messages came in around 9:56pm, and then were broken down into quite a few fields in an extractor.
It's normal that the processbuffer is the source of allocations, because it runs all the extractors and stream matchers. Seems like the immense memory consumption pushed the server into extreme GC cycles from which it couldn't recover any more.

I would look at the metrics for extractors next, to get an idea which ones get really slow. Could very well be a set of messages that suddenly contains lots and lots of fields.
You can find the metrics on the Nodes page in the UI, filter for `extractor`. That gives you all of the timing information for them.

**Comment by yogeshrao** [comment]
@kroepke would it be possible for these metrics to also write to a file? The reason i ask this is because UI gets unresponsive when the Heap expands and GC slows down.

**Comment by kroepke** [comment]
Sure, there are plugins to do just that:
Have a look at the options we provide at https://marketplace.graylog.org/addons/6fef88c7-94f7-488e-a6c5-bd6b71d8343e

**Comment by yogeshrao** [comment]
@kroepke 

Below are the metric figures which i see
![image](https://cloud.githubusercontent.com/assets/10163027/21047240/cc374cb2-be2e-11e6-96d4-beb7c4652aff.png)
![image](https://cloud.githubusercontent.com/assets/10163027/21047211/9eb82798-be2e-11e6-8667-268ec2bb63f2.png)

Let me know if any other metric figure can help here.

**Comment by yogeshrao** [comment]
@kroepke 

any pointer that you would like to suggest...

**Comment by yogeshrao** [comment]
@jalogisch I saw that you have added this to 2.2.0 milestone, does this mean you have identified the issue ?

**Comment by kroepke** [comment]
I don't think there is a bug here.
This looks to me like your extractors are simply slow and stalling everything.
Most likely you are seeing a backtracking regex (at least one took a maximum of 13 seconds for some message, the json extractor took 11 secs).
I would take another look at what those are doing and what types of messages are coming in.

**Comment by yogeshrao** [comment]
@kroepke 

IMO the maximum value from metrics is something which could be polluted and not actually accurate i.e. once the spike in heap happens Graylog tends to slow down (here the maximum of 13 sec and 11 seconds could occur)

**Comment by kroepke** [comment]
Could be, but it's also pretty much impossible to us to debug without having the messages.
There's also no indication why this would happen during processing, when the system ran stable before. Thus it is very likely data-dependent.

**Comment by yogeshrao** [comment]
@kroepke I understand without the messages its difficult to debug and i appreciate all the help you giving me.

I have a question.. The input in my case is 3-4k message in JSON format, we split this message into multiple messages around 10 with each message size around 3K. would this add a lot of burden on the buffers?

**Comment by kroepke** [comment]
Your input is about 3-4 kB which you create 10 x 3kB messages out of? So essentially you are using an order of magnitude more memory where you create these messages.

Decoding protocols happens after reading them out of the journal, and prior to when they are processed. From the point of view of the processing stages, each message is independent. However, since a single message read from the journal will end up producing 10x the messages in the buffers, we might read too many messages from the journal. Given the sizes you quote that shouldn't be much of a deal, though.

I would test with smaller buffer sizes and see if the problem goes away at some point.

**Comment by yogeshrao** [comment]
the out 3kb messages are on the higher end usually it should be around 1-2k size.

Now if i understand this correctly the messages are picked up from journal and then put into input buffer queue. messages are then picked up from input buffer and then decoded and placed into processing buffer. finally the messages move from processing buffer to output buffer.

is this correct?

**Comment by kroepke** [comment]
Sorry, I was out for the holidays.

The messages are taken off the network, placed into the input buffer, written to the journal, read from the journal and put into the process buffer (and after that into the outputbuffer and batched for writing to elasticsearch).

The input and process buffers are completely separate and will never contain the same messages, decoding happens after reading from the journal.
The system is designed to do as little processing as possible on the network side, to maximize the network traffic. Everything after the journal is blocking, so that the journal serves as backpressure buffer.

**Comment by bernd** [comment]
Closing this due to inactivity. Please create a new issue if you are still having this issue. Thank you!
