### ISSUE TITLE
Journal command does not work

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#3126]
```
$ java -jar graylog.jar journal
2016-11-26 18:53:35,596 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for org.graylog2.audit.AuditEventSender was bound.
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.graylog2.audit.AuditEventSender was bound.
  while locating com.google.inject.Provider<org.graylog2.audit.AuditEventSender>
    for the 4th parameter of org.graylog2.plugin.ServerStatus.<init>(ServerStatus.java:71)
  at org.graylog2.shared.bindings.ServerStatusBindings.configure(ServerStatusBindings.java:41)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:60)
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379)
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:193)
	at org.graylog2.bootstrap.Main.main(Main.java:44)
```
## Your Environment

* Graylog Version: 2.1.2

**Comment by kroepke** [comment]
This definitely needs better integration tests, it happened in some 2.0.x version as well 😞
