### ISSUE TITLE
Expected numeric type on field [timestamp], but got [string] Problem?

### ISSUE THREAD

**Issue by Guizas** [Graylog2/graylog2-server#3248]
* Graylog Version: 2.0.3
* Elasticsearch Version: 2.4.3
* MongoDB Version: 3.2.11
* Operating System: Linux version 3.10.0-514.2.2.el7.x86_64
* Browser version: Chrome 55.0.2883.87

Hello i just installed Graylog2 on my system for testing and I have configured syslog to the graylog server that I can see its processing, my issues is when i try to go to "Search" or "Sources" i get the following problem:

`2016-12-23T02:20:01.989Z DEBUG [search] [graylog-7970b671-e88f-4cd6-8620-08c6187cb484] [graylog_0][0], node[q_wtKoJXSYWJcYZNHwOYGw], [P], v[8], s[STARTED], a[id=gAi5DQJ1QaGZZ5wOMqF6fg]: Failed to execute [org.elasticsearch.action.search.SearchRequest@72364da]
org.elasticsearch.transport.RemoteTransportException: [Melissa Gold][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]
Caused by: java.lang.IllegalArgumentException: Expected numeric type on field [timestamp], but got [string]
        at org.elasticsearch.search.aggregations.support.AggregationContext.numericField(AggregationContext.java:161) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.support.AggregationContext.originalValuesSource(AggregationContext.java:145) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.support.AggregationContext.valuesSource(AggregationContext.java:85) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:60) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:102) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createSubAggregators(AggregatorFactories.java:76) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.AggregatorBase.<init>(AggregatorBase.java:69) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.<init>(BucketsAggregator.java:48) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.bucket.SingleBucketAggregator.<init>(SingleBucketAggregator.java:38) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator.<init>(FilterAggregator.java:54) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator$Factory.createInternal(FilterAggregator.java:108) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:102) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:87) ~[graylog.jar:?]
        at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:85) ~[graylog.jar:?]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:111) ~[graylog.jar:?]
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:372) ~[graylog.jar:?]
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:480) ~[graylog.jar:?]
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392) ~[graylog.jar:?]
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389) ~[graylog.jar:?]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[graylog.jar:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77) ~[graylog.jar:?]
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:293) ~[graylog.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

Now I see the `java.lang.IllegalArgumentException: Expected numeric type on field [timestamp], but got [string]` but I have several sources logging to the gray-log server I would expect some to show up? or perhaps its doing this for all sources, is the a way I can fix this, I have tried searching but did not have much luck.

Thanks

**Comment by edmundoa** [comment]
Hi,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
