### ISSUE TITLE
Java Runtime Exception after upgrading from 2.2.0-beta.2 to 2.2.0-beta.3

### ISSUE THREAD

**Issue by mryanb** [Graylog2/graylog2-server#3267]
## Error log snippet /var/log/graylog-server/server.log

```
2016-12-28T01:43:18.905-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-28T01:43:18.905-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-28T01:43:18.905-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
```

## Current Behavior
The current error is causing the web interface to not accept connections on port 9000.

## Steps to Reproduce (for bugs)

1. Previously installed 2.2.0-beta.2 in test environment
2. Sent data via filebeat and metricbeat.
3. Upgraded to 2.2.0-beta.3 via `apt-get update` then `apt-get install graylog-server`
4. Restarted graylog `sudo service graylog-server restart`
5. Web interface is not accessible and errors are reported in /var/log/graylog-server/server.log

## Context

* Graylog Version: 2.2.0-beta.3
* Elasticsearch Version: 2.4.3
* MongoDB Version: 2.4.10-5
* Operating System: Debian 8.6
* Browser version: Chrome Version 55.0.2883.95 (64-bit)

**Comment by bernd** [comment]
Thanks for testing the beta release! Can you please send us the complete log or at least a larger amount including the stack traces?

**Comment by mryanb** [comment]
@bernd Here is the entire snippet from a restart.

```
2016-12-30T00:52:25.293-06:00 INFO  [CmdLineTool] Loaded plugin: Elastic Beats Input 2.2.0-beta.3 [org.graylog.plugins.beats.BeatsInputPlugin]
2016-12-30T00:52:25.296-06:00 INFO  [CmdLineTool] Loaded plugin: Collector 2.2.0-beta.3 [org.graylog.plugins.collector.CollectorPlugin]
2016-12-30T00:52:25.297-06:00 INFO  [CmdLineTool] Loaded plugin: Enterprise Integration Plugin 2.2.0-beta.3 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]
2016-12-30T00:52:25.299-06:00 INFO  [CmdLineTool] Loaded plugin: MapWidgetPlugin 2.2.0-beta.3 [org.graylog.plugins.map.MapWidgetPlugin]
2016-12-30T00:52:25.307-06:00 INFO  [CmdLineTool] Loaded plugin: Pipeline Processor Plugin 2.2.0-beta.3 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin]
2016-12-30T00:52:25.309-06:00 INFO  [CmdLineTool] Loaded plugin: Anonymous Usage Statistics 2.2.0-beta.3 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]
2016-12-30T00:52:25.710-06:00 INFO  [CmdLineTool] Running with JVM arguments: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configurationFile=file:///etc/graylog/server/log4j2.xml -Djava.library.path=/usr/share/graylog-server/lib/sigar -Dgraylog2.installation_source=deb
2016-12-30T00:52:26.052-06:00 INFO  [Version] HV000001: Hibernate Validator null
2016-12-30T00:52:30.489-06:00 INFO  [InputBufferImpl] Message journal is enabled.
2016-12-30T00:52:30.536-06:00 INFO  [NodeId] Node ID: 8ee9b819-c85f-4e39-98bc-376e256d1129
2016-12-30T00:52:30.872-06:00 INFO  [LogManager] Loading logs.
2016-12-30T00:52:30.933-06:00 WARN  [Log] Found a corrupted index file, /var/lib/graylog-server/journal/messagejournal-0/00000000000000000000.index, deleting and rebuilding index...
2016-12-30T00:52:31.003-06:00 INFO  [LogManager] Logs loading complete.
2016-12-30T00:52:31.003-06:00 INFO  [KafkaJournal] Initialized Kafka based journal at /var/lib/graylog-server/journal
2016-12-30T00:52:31.042-06:00 INFO  [InputBufferImpl] Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
2016-12-30T00:52:31.082-06:00 INFO  [cluster] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=5000}
2016-12-30T00:52:31.177-06:00 INFO  [cluster] No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
2016-12-30T00:52:31.219-06:00 INFO  [connection] Opened connection [connectionId{localValue:1, serverValue:35}] to localhost:27017
2016-12-30T00:52:31.226-06:00 INFO  [cluster] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[2, 4, 10]}, minWireVersion=0, maxWireVersion=0, maxDocumentSize=16777216, roundTripTimeNanos=479331}
2016-12-30T00:52:31.235-06:00 INFO  [connection] Opened connection [connectionId{localValue:2, serverValue:36}] to localhost:27017
2016-12-30T00:52:32.065-06:00 INFO  [node] [graylog-8ee9b819-c85f-4e39-98bc-376e256d1129] version[2.4.3], pid[32607], build[d38a34e/2016-12-07T16:28:56Z]
2016-12-30T00:52:32.067-06:00 INFO  [node] [graylog-8ee9b819-c85f-4e39-98bc-376e256d1129] initializing ...
2016-12-30T00:52:32.079-06:00 INFO  [plugins] [graylog-8ee9b819-c85f-4e39-98bc-376e256d1129] modules [], plugins [graylog-monitor], sites []
2016-12-30T00:52:35.016-06:00 INFO  [node] [graylog-8ee9b819-c85f-4e39-98bc-376e256d1129] initialized
2016-12-30T00:52:35.307-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:38.609-06:00 INFO  [RulesEngineProvider] No static rules file loaded.
2016-12-30T00:52:38.840-06:00 INFO  [OutputBuffer] Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:39.171-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:39.301-06:00 INFO  [connection] Opened connection [connectionId{localValue:3, serverValue:37}] to localhost:27017
2016-12-30T00:52:39.366-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:39.630-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:39.745-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:39.894-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:40.552-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:40.651-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:40.786-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:40.901-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:41.105-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:41.233-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:41.430-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:41.562-06:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2016-12-30T00:52:41.708-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.708-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.709-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.709-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.710-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.710-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.710-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.710-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.711-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.711-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.711-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.711-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.711-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.711-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.711-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
2016-12-30T00:52:41.711-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
```

**Comment by svanschie** [comment]
Running into the same issue here, debug logging shows the following:

<pre>
2017-01-02T11:58:42.745+01:00 DEBUG [CmdLineTool] Stacktrace:
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "default" (class org.graylog2.indexer.indexset.AutoValue_IndexSetConfig), not marked as ignorable (17 known properties: "index_optimization_disabled", "index_template_name", "index_wildcard", "index_match_pattern", "rotation_strategy_class", "creation_date", "index_analyzer", "rotation_strategy", "shards", "title", "index_optimization_max_num_segments", "_id", "replicas", "description", "index_prefix", "retention_strategy_class", "retention_strategy"])
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@3fe21d0e; pos: 666] (through reference chain: org.graylog2.indexer.indexset.AutoValue_IndexSetConfig["default"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1477) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1455) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:246) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handlePolymorphic(BeanDeserializerBase.java:1520) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:484) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1198) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3770) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2165) ~[graylog.jar:?]
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:77) ~[graylog.jar:?]
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:64) ~[graylog.jar:?]
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:49) ~[graylog.jar:?]
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:29) ~[graylog.jar:?]
	at com.mongodb.connection.ReplyMessage.<init>(ReplyMessage.java:57) ~[graylog.jar:?]
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:297) ~[graylog.jar:?]
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:54) ~[graylog.jar:?]
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168) ~[graylog.jar:?]
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289) ~[graylog.jar:?]
	at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:212) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:525) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:510) ~[graylog.jar:?]
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:431) ~[graylog.jar:?]
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:404) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:510) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:81) ~[graylog.jar:?]
	at com.mongodb.Mongo.execute(Mongo.java:836) ~[graylog.jar:?]
	at com.mongodb.Mongo$2.execute(Mongo.java:823) ~[graylog.jar:?]
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:870) ~[graylog.jar:?]
	at com.mongodb.DBCursor.hasNext(DBCursor.java:142) ~[graylog.jar:?]
	at org.mongojack.DBCursor.hasNext(DBCursor.java:330) ~[graylog.jar:?]
	at org.mongojack.JacksonDBCollection.findOne(JacksonDBCollection.java:1374) ~[graylog.jar:?]
	at org.mongojack.JacksonDBCollection.findOne(JacksonDBCollection.java:1335) ~[graylog.jar:?]
	at org.mongojack.JacksonDBCollection.findOne(JacksonDBCollection.java:1309) ~[graylog.jar:?]
	at org.graylog2.indexer.indexset.MongoIndexSetService.get(MongoIndexSetService.java:96) ~[graylog.jar:?]
	at org.graylog2.indexer.indexset.MongoIndexSetService.get(MongoIndexSetService.java:87) ~[graylog.jar:?]
	at org.graylog2.streams.StreamServiceImpl.getIndexSet(StreamServiceImpl.java:104) ~[graylog.jar:?]
	at org.graylog2.streams.StreamServiceImpl.getIndexSet(StreamServiceImpl.java:96) ~[graylog.jar:?]
	at org.graylog2.streams.StreamServiceImpl.loadAll(StreamServiceImpl.java:189) ~[graylog.jar:?]
	at org.graylog2.streams.StreamServiceImpl.loadAllEnabled(StreamServiceImpl.java:161) ~[graylog.jar:?]
	at org.graylog2.streams.StreamServiceImpl.loadAllEnabled(StreamServiceImpl.java:155) ~[graylog.jar:?]
	at org.graylog.plugins.pipelineprocessor.functions.messages.RouteToStream.<init>(RouteToStream.java:49) ~[?:?]
	at org.graylog.plugins.pipelineprocessor.functions.messages.RouteToStream$$FastClassByGuice$$cc807c18.newInstance(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[graylog.jar:?]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56) ~[graylog.jar:?]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019) ~[graylog.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[graylog.jar:?]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015) ~[graylog.jar:?]
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104) ~[graylog.jar:?]
	at com.google.inject.multibindings.MapBinder$RealMapBinder$ValueProvider.get(MapBinder.java:821) ~[graylog.jar:?]
	at com.google.inject.multibindings.MapBinder$RealMapBinder$RealMapProvider.get(MapBinder.java:605) ~[graylog.jar:?]
	at com.google.inject.multibindings.MapBinder$RealMapBinder$RealMapProvider.get(MapBinder.java:586) ~[graylog.jar:?]
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81) ~[graylog.jar:?]
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53) ~[graylog.jar:?]
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61) ~[graylog.jar:?]
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45) ~[graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[graylog.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[graylog.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[graylog.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[graylog.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) ~[graylog.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205) ~[graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199) ~[graylog.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) ~[graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199) ~[graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) ~[graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[graylog.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:99) ~[graylog.jar:?]
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:193) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]
</pre>

**Comment by freebsdsa** [comment]
Seeing the same issue when I upgraded from beta-2 to beta-4.

**Comment by kemijoki** [comment]
seeing the same error with beta-6

**Comment by edmundoa** [comment]
@kemijoki beta-6 has not been released (the latest released version is 2.2.0-beta.4). Out of curiosity, where did you saw that version?

**Comment by kemijoki** [comment]
yes, I know, it was a mistake, I changed it already :-)

**Comment by joschi** [comment]
@kemijoki This is a completely different error and looks like a corrupted JAR file.

**Comment by kemijoki** [comment]
I installed beta-2, this is working fine... Do you have an idea how to "repair" this problem?

**Comment by joschi** [comment]
@kemijoki Please don't hijack this issue.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by mryanb** [comment]
Should this issue be resolved in beta5? I just upgraded my broken instance from beta4 to 5 and am still seeing the issue in the logs.
