### ISSUE TITLE
An exception occurred processing Appender rolling-file java.lang.NullPointerException

### ISSUE THREAD

**Issue by tsgan** [Graylog2/graylog2-server#3295]
Following error occurs:

```
[root@centos6 /]# service graylog-server start
Starting graylog-server:                                   [  OK  ]
[root@centos6 /]# 2017-01-04 00:40:12,052 main ERROR An exception occurred processing Appender rolling-file java.lang.NullPointerException
	at java.util.jar.JarInputStream.createZipEntry(JarInputStream.java:229)
	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:298)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
	at java.util.jar.JarInputStream.<init>(JarInputStream.java:83)
	at java.lang.Package.loadManifest(Package.java:611)
	at java.lang.Package.access$100(Package.java:111)
	at java.lang.Package$1.run(Package.java:586)
	at java.lang.Package$1.run(Package.java:570)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.Package.defineSystemPackage(Package.java:570)
	at java.lang.Package.getSystemPackage(Package.java:546)
	at java.lang.Package.getPackage(Package.java:336)
	at java.lang.Class.getPackage(Class.java:796)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.toCacheEntry(ThrowableProxy.java:551)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.toExtendedStackTrace(ThrowableProxy.java:603)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:135)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:117)
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:314)
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61)
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38)
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:294)
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:195)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:180)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:120)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:113)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:104)
	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:86)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:155)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:128)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:119)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:375)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:359)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:349)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.ExtendedLoggerWrapper.logMessage(ExtendedLoggerWrapper.java:217)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960)
	at org.apache.logging.log4j.jul.WrappedLogger.log(WrappedLogger.java:40)
	at org.apache.logging.log4j.jul.ApiLogger.log(ApiLogger.java:127)
	at org.bson.types.ObjectId.createMachineIdentifier(ObjectId.java:495)
	at org.bson.types.ObjectId.<clinit>(ObjectId.java:463)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy83.<clinit>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
	at com.google.inject.assistedinject.FactoryProvider2.<init>(FactoryProvider2.java:328)
	at com.google.inject.assistedinject.FactoryModuleBuilder$1.configure(FactoryModuleBuilder.java:334)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.AbstractModule.install(AbstractModule.java:122)
	at org.graylog2.bindings.ServerBindings.bindFactoryModules(ServerBindings.java:135)
	at org.graylog2.bindings.ServerBindings.configure(ServerBindings.java:112)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:60)
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379)
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:193)
	at org.graylog2.bootstrap.Main.main(Main.java:44)

Exception in thread "Finalizer" java.lang.NullPointerException
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000008090d4b68, pid=1196, tid=0x000000095a504700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b15) (build 1.8.0_111-b15)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b15 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 57  java.lang.System.nanoTime()J (0 bytes) @ 0x00000008090d4b68 [0x00000008090d4a80+0xe8]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1196.log
Compiled method (c1)   11030 4660       3       java.util.concurrent.TimeUnit::x (27 bytes)
 total in heap  [0x0000000809eec8d0,0x0000000809eecc88] = 952
 relocation     [0x0000000809eec9f8,0x0000000809eeca28] = 48
 main code      [0x0000000809eeca40,0x0000000809eecba0] = 352
 stub code      [0x0000000809eecba0,0x0000000809eecc30] = 144
 metadata       [0x0000000809eecc30,0x0000000809eecc38] = 8
 scopes data    [0x0000000809eecc38,0x0000000809eecc50] = 24
 scopes pcs     [0x0000000809eecc50,0x0000000809eecc80] = 48
 dependencies   [0x0000000809eecc80,0x0000000809eecc88] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

**Comment by joschi** [comment]
@tsgan Which version of Graylog and which exact version of Java are you running?

The segmentation fault looks like either an error in the JVM itself, one of the system libraries, or faulty hardware.

**Comment by jalogisch** [comment]
as we did not have any feedback on this we will close this.
