### ISSUE TITLE
Session expiration sometime not properly handled

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#3335]
## Expected Behavior
Log in without errors

## Current Behavior
- Have a 500 error from rest API prompted on log in.
- Click sign in again solves it.

## Possible Solution

- Catch session expiration, auto renew it naturally as credentials are valid
- Seems also related to mongo index error (see) DuplicateKeyException below

## Steps to Reproduce (for bugs)
- Get a user with default session expiration
- Open graylog in a browser, let session expires naturally
- Later, try to login again: Errors.

As this is not always the case, it's quite hard to reproduce, but i think following stack traces may help:

```
2017-01-06T03:12:44.757Z WARN  [ModularRealmAuthenticator] Realm [org.graylog2.security.realm.SessionAuthenticator@23f31640] threw an exception during a multi-realm authentication attempt:
org.apache.shiro.session.ExpiredSessionException: Session with id [807fecfe-1dba-4b02-b092-9bb5ce357d76] has expired. Last access time: 1/5/17 7:12 PM.  Current time: 1/6/17 3:12 AM.  Session timeout is set to 28800 seconds (480 minutes)
        at org.apache.shiro.session.mgt.SimpleSession.validate(SimpleSession.java:292) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doValidate(AbstractValidatingSessionManager.java:186) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.validate(AbstractValidatingSessionManager.java:143) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:120) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:148) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupRequiredSession(AbstractNativeSessionManager.java:152) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getAttribute(AbstractNativeSessionManager.java:249) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.DelegatingSession.getAttribute(DelegatingSession.java:141) ~[graylog.jar:?]
        at org.apache.shiro.session.ProxiedSession.getAttribute(ProxiedSession.java:121) ~[graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSubjectDAO.mergeAuthenticationState(DefaultSubjectDAO.java:244) ~[graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSubjectDAO.saveToSession(DefaultSubjectDAO.java:167) ~[graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSubjectDAO.save(DefaultSubjectDAO.java:147) ~[graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSecurityManager.save(DefaultSecurityManager.java:383) ~[graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:350) ~[graylog.jar:?]
        at org.apache.shiro.subject.Subject$Builder.buildSubject(Subject.java:846) ~[graylog.jar:?]
        at org.graylog2.security.realm.SessionAuthenticator.doGetAuthenticationInfo(SessionAuthenticator.java:57) ~[graylog.jar:?]
        at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:568) ~[graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:219) [graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269) [graylog.jar:?]
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) [graylog.jar:?]
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) [graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270) [graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256) [graylog.jar:?]
        at org.graylog2.shared.security.ShiroSecurityContext.loginSubject(ShiroSecurityContext.java:101) [graylog.jar:?]
        at org.graylog2.shared.security.ShiroAuthenticationFilter.filter(ShiroAuthenticationFilter.java:48) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2017-01-06T03:12:47.387Z ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.NullPointerException
        at org.graylog2.database.PersistedServiceImpl.collection(PersistedServiceImpl.java:113) ~[graylog.jar:?]
        at org.graylog2.database.PersistedServiceImpl.destroy(PersistedServiceImpl.java:160) ~[graylog.jar:?]
        at org.graylog2.security.MongoDbSessionDAO.doDelete(MongoDbSessionDAO.java:119) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.eis.CachingSessionDAO.delete(CachingSessionDAO.java:304) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.DefaultSessionManager.delete(DefaultSessionManager.java:240) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.DefaultSessionManager.afterExpired(DefaultSessionManager.java:207) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.onExpiration(AbstractValidatingSessionManager.java:159) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.validate(AbstractValidatingSessionManager.java:145) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:120) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:148) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupRequiredSession(AbstractNativeSessionManager.java:152) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getAttribute(AbstractNativeSessionManager.java:249) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.DelegatingSession.getAttribute(DelegatingSession.java:141) ~[graylog.jar:?]
        at org.apache.shiro.session.ProxiedSession.getAttribute(ProxiedSession.java:121) ~[graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.getRunAsPrincipalsStack(DelegatingSubject.java:469) ~[graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.getPrincipals(DelegatingSubject.java:153) ~[graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.hasPrincipals(DelegatingSubject.java:126) ~[graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.isPermitted(DelegatingSubject.java:158) ~[graylog.jar:?]
        at org.graylog2.shared.rest.resources.RestResource.isPermitted(RestResource.java:97) ~[graylog.jar:?]
        at org.graylog2.shared.rest.resources.system.MetricsResource.multipleMetrics(MetricsResource.java:123) ~[graylog.jar:?]
        at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2017-01-06T03:12:51.643Z WARN  [ModularRealmAuthenticator] Realm [org.graylog2.security.realm.SessionAuthenticator@23f31640] threw an exception during a multi-realm authentication attempt:
com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'E11000 duplicate key error collection: graylog2.sessions index: _id_ dup key: { : ObjectId('5862669f7e82620001c41f36') }'
        at com.mongodb.operation.BaseWriteOperation.convertBulkWriteException(BaseWriteOperation.java:237) ~[graylog.jar:?]
        at com.mongodb.operation.BaseWriteOperation.access$300(BaseWriteOperation.java:61) ~[graylog.jar:?]
        at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:147) ~[graylog.jar:?]
        at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:134) ~[graylog.jar:?]
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:232) ~[graylog.jar:?]
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:223) ~[graylog.jar:?]
        at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:134) ~[graylog.jar:?]
        at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:61) ~[graylog.jar:?]
        at com.mongodb.Mongo.execute(Mongo.java:827) ~[graylog.jar:?]
        at com.mongodb.Mongo$2.execute(Mongo.java:810) ~[graylog.jar:?]
        at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:333) ~[graylog.jar:?]
        at com.mongodb.DBCollection.updateImpl(DBCollection.java:501) ~[graylog.jar:?]
        at com.mongodb.DBCollection.update(DBCollection.java:455) ~[graylog.jar:?]
        at com.mongodb.DBCollection.update(DBCollection.java:432) ~[graylog.jar:?]
        at com.mongodb.DBCollection.update(DBCollection.java:522) ~[graylog.jar:?]
        at org.graylog2.database.PersistedServiceImpl.save(PersistedServiceImpl.java:199) ~[graylog.jar:?]
        at org.graylog2.database.PersistedServiceImpl.saveWithoutValidation(PersistedServiceImpl.java:207) ~[graylog.jar:?]
        at org.graylog2.security.MongoDbSessionDAO.doUpdate(MongoDbSessionDAO.java:111) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.eis.CachingSessionDAO.update(CachingSessionDAO.java:277) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.DefaultSessionManager.onChange(DefaultSessionManager.java:212) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.DefaultSessionManager.onExpiration(DefaultSessionManager.java:201) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.onExpiration(AbstractValidatingSessionManager.java:156) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.validate(AbstractValidatingSessionManager.java:145) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:120) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:148) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupRequiredSession(AbstractNativeSessionManager.java:152) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getAttribute(AbstractNativeSessionManager.java:249) ~[graylog.jar:?]
        at org.apache.shiro.session.mgt.DelegatingSession.getAttribute(DelegatingSession.java:141) ~[graylog.jar:?]
        at org.apache.shiro.session.ProxiedSession.getAttribute(ProxiedSession.java:121) ~[graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.getRunAsPrincipalsStack(DelegatingSubject.java:469) ~[graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.getPrincipals(DelegatingSubject.java:153) ~[graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.getPrincipal(DelegatingSubject.java:149) ~[graylog.jar:?]
        at org.graylog2.security.realm.SessionAuthenticator.doGetAuthenticationInfo(SessionAuthenticator.java:64) ~[graylog.jar:?]
        at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:568) ~[graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:219) [graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269) [graylog.jar:?]
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) [graylog.jar:?]
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) [graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270) [graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256) [graylog.jar:?]
        at org.graylog2.shared.security.ShiroSecurityContext.loginSubject(ShiroSecurityContext.java:101) [graylog.jar:?]
        at org.graylog2.shared.security.ShiroAuthenticationFilter.filter(ShiroAuthenticationFilter.java:48) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

## Your Environment

* Graylog Version: 2.1.2 (LDAP support)
* Elasticsearch Version: 2.4.1
* MongoDB Version: 3.2.7
* Browser version: chromium

**Comment by kroepke** [comment]
This seems related to https://jira.mongodb.org/browse/SERVER-14322
From our perspective we try to update the session information in mongodb (in this case flagging it as expired). This fails because of the bug above. The parallel requests are very likely from async Javascript requests that get sent for the expired session, which triggers a parallel update in the server.

I'll see if we can simply retry the update if we get this error. This should not make a difference in terms of what is stored, but would get rid of the error message at least.
