### ISSUE TITLE
Parsing error: token_mgr_error: Lexical error encountered: <EOF> after : ""

### ISSUE THREAD

**Issue by madchap** [Graylog2/graylog2-server#3388]
On certain syslog messages coming in, extractor fails and showing the terms on the message itself also fails.

The exception is available [here](https://gist.github.com/madchap/1acf24a25695858955dfe5aae4ae1665)

The message looks like this

> pxxx-xx-002 tmm[13116]: 01010045:5: Bandwidth utilization is 83 Mbps, exceeded 75% of Licensed 25 Mbps

The extractor would look like this:

> %{HOST:f5_host} %{NOTSPACE:f5_uw}: %{NOTSPACE}: Bandwidth utilization is %{NUMBER:f5_bandwidth_used;int} Mbps, exceeded %{NUMBER:f5_bandwidth_limit_pct;int}\% of Licensed %{NUMBER:f5_bandwidth_limit_abs;int} Mbps

It works well with grokdebug.herokuapp.com

## Expected Behavior

I should be able to see the terms and the message should be parsed.

## Current Behavior

Cannot see the terms nor is the message parsed.

## Steps to Reproduce (for bugs)

1. Locate the message (3 or 4 different types from this source)
2. Click on "show terms" - this triggers the 500 error

## Context

Trying to parse F5 WAF appliance syslog.

## Your Environment

* Graylog Version: 2.1.2
* Elasticsearch Version: 2.4.1
* MongoDB Version: 3.2.11
* Operating System: Centos 7
* Browser version: Chrome 55

**Comment by joschi** [comment]
The problem seems to be an unescaped query parameter for the `/messages/{index}/analyze` endpoint.

```text
java.lang.IllegalArgumentException: java.net.URISyntaxException: Malformed escape pair at index 162: http://localhost:9000/api/messages/graylog2_110/analyze?string=pxxx-xx-002%20tmm[13116]:%2001010045:5:%20Bandwidth%20utilization%20is%2083%20Mbps,%20exceeded%2075%%20of%20Licensed%2025%20Mbps
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:491)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:366)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Malformed escape pair at index 162: http://localhost:9000/api/messages/graylog2_110/analyze?string=pxxx-xx-002%20tmm[13116]:%2001010045:5:%20Bandwidth%20utilization%20is%2083%20Mbps,%20exceeded%2075%%20of%20Licensed%2025%20Mbps
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.scanEscape(URI.java:2978)
	at java.net.URI$Parser.scan(URI.java:3001)
	at java.net.URI$Parser.checkChars(URI.java:3019)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.&lt;init&gt;(URI.java:588)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:489)
	... 6 more
```
