### ISSUE TITLE
Streams page does not load when stream rule types are slow

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#3389]
In some situations there is an error while loading the streams page, ending in a loading page:

```
bluebird.js:1542 Unhandled rejection TypeError: Cannot read property 'filterData' of undefined
    at eval (webpack:///./src/components/streams/StreamComponent.jsx?:65:31)
    at eval (webpack:///./src/stores/streams/StreamsStore.ts?:23:13)
From previous event:
    at StreamsStore.load (webpack:///./src/stores/streams/StreamsStore.ts?:22:28)
    at StreamComponent.loadData (webpack:///./src/components/streams/StreamComponent.jsx?:60:18)
    at StreamComponent.loadData (webpack:///./~/react-proxy/modules/createPrototypeProxy.js?:44:30)
    at StreamComponent.componentDidMount (webpack:///./src/components/streams/StreamComponent.jsx?:46:10)
    at StreamComponent.proxiedComponentDidMount [as componentDidMount] (webpack:///./~/react-proxy/modules/createPrototypeProxy.js?:66:40)
    at CallbackQueue.notifyAll (http://localhost:8080/build/vendor.js:11517:23)
    at ReactReconcileTransaction.close (http://localhost:8080/build/vendor.js:45811:27)
    at ReactReconcileTransaction.closeAll (http://localhost:8080/build/vendor.js:10163:26)
    at ReactReconcileTransaction.perform (http://localhost:8080/build/vendor.js:10110:17)
    at ReactUpdatesFlushTransaction.perform (http://localhost:8080/build/vendor.js:10097:21)
    at ReactUpdatesFlushTransaction.perform (http://localhost:8080/build/vendor.js:6224:39)
    at Object.flushBatchedUpdates (http://localhost:8080/build/vendor.js:6285:20)
    at Object.wrapper [as flushBatchedUpdates] (http://localhost:8080/build/vendor.js:6102:22)
    at ReactDefaultBatchingStrategyTransaction.closeAll (http://localhost:8080/build/vendor.js:10163:26)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:8080/build/vendor.js:10110:17)
    at Object.batchedUpdates (http://localhost:8080/build/vendor.js:27564:20)
    at Object.enqueueUpdate (http://localhost:8080/build/vendor.js:6314:23)
    at enqueueUpdate (http://localhost:8080/build/vendor.js:12149:17)
    at Object.enqueueSetState (http://localhost:8080/build/vendor.js:12315:6)
    at StreamsPage.ReactComponent.setState (http://localhost:8080/build/vendor.js:26991:17)
    at EventEmitter.eventHandler (http://localhost:8080/build/vendor.js:56491:23)
    at EventEmitter.emit (http://localhost:8080/build/vendor.js:52073:36)
    at Store.trigger (http://localhost:8080/build/vendor.js:56560:27)
    at eval (webpack:///./src/stores/indices/IndexSetsStore.jsx?:44:20)
From previous event:
    at Store.list (webpack:///./src/stores/indices/IndexSetsStore.jsx?:43:13)
    at EventEmitter.eventHandler (http://localhost:8080/build/vendor.js:56491:23)
    at EventEmitter.emit (http://localhost:8080/build/vendor.js:52073:36)
    at Function.trigger (http://localhost:8080/build/vendor.js:56560:27)
    at http://localhost:8080/build/vendor.js:56571:25
    at module.exports (webpack:///./~/core-js/modules/_invoke.js?:5:25)
    at queue.(anonymous function) (webpack:///./~/core-js/modules/_task.js?:31:7)
    at Number.run (webpack:///./~/core-js/modules/_task.js?:19:5)
    at MessagePort.listener (webpack:///./~/core-js/modules/_task.js?:23:7)
```

Looking into the issue, it seems that the error happens when the stream rule types are loaded after the stream list. In that case, the `StreamComponent.loadData()` will call a method on a `ref` that is not still mounted.

## Steps to Reproduce (for bugs)
1. Make the REST call getting the stream rule types slower (add a sleep or even remove the `this.setState()` that does when loading data
2. Load the streams page
3. See how some elements of the page are loaded, but the stream list is always in a loading state
4. Check your JS console to see the error above

## Your Environment
* Graylog Version: Graylog 2.2.0-beta.6

**Comment by bernd** [comment]
I also see this with 2.2.0-beta.6.

**Comment by edmundoa** [comment]
This is related to #3352.
