### ISSUE TITLE
Graylog eve.json 

### ISSUE THREAD

**Issue by harveys3191** [Graylog2/graylog2-server#3447]
Good Day, 

have a pfsense suricata  pointing to graylog syslog udp input. when we check server.log we have the below error message. 
```
2017-01-29T11:32:13.351-05:00 ERROR [GelfCodec] Could not parse JSON, first 400 characters: | [SNORTIDS[ALERT]: [zt01zn2pf02.cymaticssecurity.com] ] || 2017-01-29 11:14:10.370+-05 2 [1:2013054:2] ET USER_AGENTS PyCurl Suspicious User Agent Outbound || attempted-recon || 6 38.70.1.76 52.49.94.197 || 37953 8080 ||
 |^@
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('|' (code 124)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: | [SNORTIDS[ALERT]: [zt01zn2pf02.cymaticssecurity.com] ] || 2017-01-29 11:14:10.370+-05 2 [1:2013054:2] ET USER_AGENTS PyCurl Suspicious User Agent Outbound || attempted-recon || 6 38.70.1.76 52.49.94.197 || 37953 8080 ||
 |^@; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1823) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:708) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3847) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2332) ~[graylog.jar:?]
        at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:120) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:146) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:87) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

* Graylog Version: 2.1.2
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.2
* Operating System: centos
* Browser version:

**Comment by joschi** [comment]
@harveys3191 It looks like Snort (or whatever the client is) doesn't send valid GELF messages to Graylog.

Make sure that you're sending the messages to a *Syslog* input and not a *GELF* input in Graylog.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
