### ISSUE TITLE
Journal cannot be placed on a different disk

### ISSUE THREAD

**Issue by timwelch** [Graylog2/graylog2-server#3504]
```[root@lpglog01 journal]# rpm -qa|grep graylog
graylog-server-2.0.3-1.noarch
graylog-plugin-slack-2.2.1-1.noarch
graylog-2.0-repository-1-1.noarch
graylog-plugin-pagerduty-1.2.4-1.noarch
```

When changing this variable:

`message_journal_dir = /var/lib/graylog-server/journal`

To be on a separate disk:

`message_journal_dir = /journal`

I get Kafka .lock file issues/errors.  Even if I leave the original path correct, and change the journal folder to a symlink to a new disk, I get the same errors.  EVEN when /journal is set to 777 for permissions. 

Here's the error output after I made it into a symlink pointing to the original /var/lib/graylog-server/journal folder. The error output is identical for both cases, except it would say /journal instead. 

```
322) Error injecting constructor, java.lang.RuntimeException: kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/lib/graylog-server/journal. A Kafka instance in another process or thread is using this directory.
  at org.graylog2.shared.journal.KafkaJournal.<init>(KafkaJournal.java:160)
  at org.graylog2.shared.journal.KafkaJournal.class(KafkaJournal.java:99)
  while locating org.graylog2.shared.journal.KafkaJournal
  at org.graylog2.shared.journal.KafkaJournalModule.configure(KafkaJournalModule.java:25) (via modules: org.graylog2.bindings.ServerBindings -> org.graylog2.shared.journal.KafkaJournalModule)
  while locating org.graylog2.shared.journal.Journal
    for parameter 1 at org.graylog2.shared.buffers.JournallingMessageHandler.<init>(JournallingMessageHandler.java:67)
  while locating org.graylog2.shared.buffers.JournallingMessageHandler
  at org.graylog2.shared.buffers.InputBufferImpl.<init>(InputBufferImpl.java:55)
  at org.graylog2.shared.buffers.InputBufferImpl.class(InputBufferImpl.java:45)
  while locating org.graylog2.shared.buffers.InputBufferImpl
Caused by: java.lang.RuntimeException: kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/lib/graylog-server/journal. A Kafka instance in another process or thread is using this directory.
	at org.graylog2.shared.journal.KafkaJournal.<init>(KafkaJournal.java:283)
	at org.graylog2.shared.journal.KafkaJournal$$FastClassByGuice$$8f50433e.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at org.graylog2.shared.buffers.InputBufferImpl.<init>(InputBufferImpl.java:72)
	at org.graylog2.shared.buffers.InputBufferImpl$$FastClassByGuice$$790e95b9.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:60)
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379)
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:193)
	at org.graylog2.bootstrap.Main.main(Main.java:44)
Caused by: kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/lib/graylog-server/journal. A Kafka instance in another process or thread is using this directory.
	at kafka.log.LogManager$$anonfun$lockLogDirs$1.apply(LogManager.scala:98)
	at kafka.log.LogManager$$anonfun$lockLogDirs$1.apply(LogManager.scala:95)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.log.LogManager.lockLogDirs(LogManager.scala:95)
	at kafka.log.LogManager.<init>(LogManager.scala:57)
	at org.graylog2.shared.journal.KafkaJournal.<init>(KafkaJournal.java:261)
	... 49 more
```

**Comment by joschi** [comment]
@timwelch Which filesystem are you using for `/journal`? How and with which options is it mounted?

Also make sure that there is not more than 1 instance of Graylog running on that system with the same journal directory.

**Comment by timwelch** [comment]
All filesystems are ext4, which is centos6 default.

```cat /etc/fstab|grep ext4
/dev/mapper/VolGroup-lv_root /                       ext4    defaults        1 1
/dev/es/es /es                      ext4    defaults        1 1
/dev/sdf1		/journal	ext4	defaults	1 1
```

/journal is mounted exactly the same as /, which is where /var/lib/graylog-server/journal lives.

We have only 1 graylog instance. I shut it down "service graylog-server stop" and I ensured all java processes were down before issuing "service graylog-server start". 

Even when it 'fails' to obtain the lock, it does successfully write to the /journal with the following files:

```
[root@ddddddd journal]# ls -latr
total 20
-rw-r--r-- 1 graylog graylog    0 Nov  4  2015 .lock
drwxr-xr-x 3 graylog graylog 4096 Feb 15 12:03 ..
-rw-r--r-- 1 graylog graylog   29 Feb 15 13:34 recovery-point-offset-checkpoint
drwxr-xr-x 3 graylog graylog 4096 Feb 15 13:34 .
-rw-r--r-- 1 graylog graylog    7 Feb 15 13:35 graylog2-committed-read-offset
```

Again, it's owned properly, and i even opened it wipe up to 777 and it still failed. 

I ran the reverse sequence (stopping service, pointing config back to /var/lib/graylog-server/journal, and start servicE) and it came up right away. 

I ran that same sequence to move back to /journal and it fails every time.

**Comment by ovotech-admin** [comment]
Instead of making a symlink, have you tried adjusting the config to point to the journal location?

Also, note that you should not have the kafka journal directory saved in the root of the mount point; rather mount the journal disk and create a directory on that filesystem and put the Kafka journal there - Kafka gets out of shape when there are other directories (e.g. lost&found) in it's journal directory.

**Comment by iainmcinnes** [comment]
Instead of making a symlink, have you tried adjusting the config to point to the journal location?

Also, note that you should not have the kafka journal directory saved in the root of the mount point; rather mount the journal disk and create a directory on that filesystem and put the Kafka journal there - Kafka gets out of shape when there are other directories (e.g. lost&found) in it's journal directory.

**Comment by timwelch** [comment]
I tried to use the /journal mount point originally, and it failed. That's when I switched to making a symlink to it in /var/lib/graylog-server... 

It appears that it's the Kafka issue of being in the root of a filesystem.

I made a folder called journal inside of the new mountpoint, and I set graylog-server to use that, and it came up fine.

`message_journal_dir = /journal/journal`

Everything looks fine now. 



Is there documentation for graylog around this that I could have used to point me to this behavior? The blurb in the config file doesn't tell me I can't use the root of a filesystem, just that it shouldn't have any other 'files'. I don't consider lost&found folder an issue as I'm sure most other people wouldn't either.

```# The directory which will be used to store the message journal. The directory must me exclusively used by Graylog and
# must not contain any other files than the ones created by Graylog itself.
#message_journal_dir = /var/lib/graylog-server/journal
message_journal_dir = /journal/journal```

**Comment by joschi** [comment]
@timwelch 
> Is there documentation for graylog around this that I could have used to point me to this behavior? 

The description of the `message_journal_dir` setting is pretty clear about this: 
```
# ATTENTION:
#   If you create a seperate partition for the journal files and use a file system creating directories like 'lost+found'
#   in the root directory, you need to create a sub directory for your journal.
#   Otherwise Graylog will log an error message that the journal is corrupt and Graylog will not start.
```
https://github.com/Graylog2/graylog2-server/blob/2.2.0/misc/graylog.conf#L399-L402
