### ISSUE TITLE
Missing Property in path 'store'

### ISSUE THREAD

**Issue by npdtools-verizon** [Graylog2/graylog2-server#3538]
New install of graylog server. On server startup find this in the Logs continuously

```
2017-02-22T11:26:49.426-06:00 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2017-02-22T11:27:19.428-06:00 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2017-02-22T11:27:26.589-06:00 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=2deaa4b0-f924-11e6-b262-005056bf49c6, journalOffset=20102, codec=jsonpath, payloadSize=232, timestamp=2017-02-22T17:27:26.587Z, remoteAddress=/10.77.182.175:9000} on input <589b5f330b7fc31a73b7f865>.
2017-02-22T11:27:26.589-06:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=2deaa4b0-f924-11e6-b262-005056bf49c6, journalOffset=20102, codec=jsonpath, payloadSize=232, timestamp=2017-02-22T17:27:26.587Z, remoteAddress=/10.77.182.175:9000}
com.jayway.jsonpath.PathNotFoundException: Missing property in path $['store']
	at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:72) ~[graylog.jar:?]
	at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:79) ~[graylog.jar:?]
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62) ~[graylog.jar:?]
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53) ~[graylog.jar:?]
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61) ~[graylog.jar:?]
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187) ~[graylog.jar:?]
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:345) ~[graylog.jar:?]
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:329) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.JsonPathCodec.read(JsonPathCodec.java:81) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.JsonPathCodec.decode(JsonPathCodec.java:70) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:146) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:87) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
```

2. Unable to connect to Elasticsearch instance as well. Logs have the following error
```
2017-02-22T11:36:27.028-06:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:158) ~[graylog.jar:?]
	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedRaiseException(ClusterBlocks.java:144) ~[graylog.jar:?]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.<init>(AbstractSearchAsyncAction.java:94) ~[graylog.jar:?]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.<init>(SearchQueryThenFetchAsyncAction.java:53) ~[graylog.jar:?]
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:93) ~[graylog.jar:?]
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:47) ~[graylog.jar:?]
	at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:149) ~[graylog.jar:?]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:137) ~[graylog.jar:?]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85) ~[graylog.jar:?]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58) ~[graylog.jar:?]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359) ~[graylog.jar:?]
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52) ~[graylog.jar:?]
	at org.graylog2.indexer.elasticsearch.GlobalTimeoutClient.doExecute(GlobalTimeoutClient.java:58) ~[graylog.jar:?]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359) ~[graylog.jar:?]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348) ~[graylog.jar:?]
	at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:577) ~[graylog.jar:?]
	at org.graylog2.indexer.elasticsearch.GlobalTimeoutClient.search(GlobalTimeoutClient.java:64) ~[graylog.jar:?]
	at org.graylog2.indexer.searches.Searches.histogram(Searches.java:459) ~[graylog.jar:?]
	at org.graylog2.rest.resources.search.RelativeSearchResource.histogramRelative(RelativeSearchResource.java:282) ~[graylog.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
```

## Your Environment

* Graylog Version: Graylog 2.1.3+040d371
* Elasticsearch Version:
* MongoDB Version:
* JDK : 1.8
* Operating System: Linux : Ubuntu
* Browser version: All

thanks in advance
krishna

**Comment by joschi** [comment]
@npdtools-verizon These issues aren't related and both don't look like bugs in Graylog.

Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
