### ISSUE TITLE
graylog server restart issue

### ISSUE THREAD

**Issue by pammi22** [Graylog2/graylog2-server#3554]
operating system rhel 7

error:
```
INFO  [ServiceManagerListener] Services are now stopped.
2017-02-28T07:22:09.332-05:00 ERROR [ServerBootstrap] Graylog startup failed. Exiting. Exception was:
java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {FAILED=[JerseyService [FAILED]]}
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:713) ~[graylog.jar:?]
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:542) ~[graylog.jar:?]
	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:299) ~[graylog.jar:?]
	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:147) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:209) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]
2017-02-28T07:22:09.459-05:00 INFO  [Server] SIGNAL received. Shutting down.
2017-02-28T07:22:09.498-05:00 INFO  [GracefulShutdown] Graceful shutdown initiated.
```
elastic search and graylog config has been set but cant find the issue can anyone help?

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by pammi22** [comment]
thanks for quick response got the issue thanks :)

**Comment by sojip** [comment]
please @pammi22 what was the issue you got? i have the same problem

**Comment by DCentos** [comment]
same problem, how did you fixed it guys?
