### ISSUE TITLE
Cannot run quickvalues on fields that contain values with backslashes

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#3566]
I cannot run quickvalues on a field that has values that contains backslashes.

The request fails with

```
2017-03-05T00:45:57.091-06:00 WARN  [SearchResource] No position/token available for ParseException.
org.apache.lucene.queryparser.classic.ParseException: Cannot parse '\': Lexical error at line 1, column 2.  Encountered: <EOF> after : ""
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:122) ~[graylog.jar:?]
	at org.graylog2.rest.resources.search.SearchResource.createRequestExceptionForParseFailure(SearchResource.java:258) [graylog.jar:?]
	at org.graylog2.rest.resources.search.RelativeSearchResource.searchRelative(RelativeSearchResource.java:115) [graylog.jar:?]
	at sun.reflect.GeneratedMethodAccessor335.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 2.  Encountered: <EOF> after : ""
	at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1130) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParser.jj_ntk(QueryParser.java:628) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParser.Modifiers(QueryParser.java:126) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:170) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:160) ~[graylog.jar:?]
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:117) ~[graylog.jar:?]
	... 28 more
```

The field causing this includes the ESSIDs of WiFi networks and has this string value in the result set:

    \x00\x00\x00\x00\x00\x00\x00

When running quickvalues on the result set for this query, it works:

    NOT essid:"\\x00\\x00\\x00\\x00\\x00\\x00\\x00"

A user reports the same here I think: https://community.graylog.org/t/could-not-load-quick-values-on-field/99/3

## Your Environment

* Graylog Version: 2.2.0
* Elasticsearch Version: 2.4.4

**Comment by jalogisch** [comment]
if you have for example requested URLs that is working without any issue:

![graylog_-_rules_of_stream_http_overview](https://cloud.githubusercontent.com/assets/404238/23601994/8e026ce2-024e-11e7-9f17-e33f6f3bf5a1.png)

**Comment by joschi** [comment]
@jalogisch Slash (`/`) vs backslash (`\`). 😉

**Comment by lennartkoopmann** [comment]
FALSE ALARM! It's actually caused by this, which kinda is a worse alarm: #3603

(Thanks for looking into this @jalogisch @joschi)
