### ISSUE TITLE
the field you gave in the aggregation query existed as two different types in two different indices

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#3603]
Urgh, this one is nasty. I have a field that I accidentally stored as a `Number` in the first index before storing as `String`. Since then a week has passed and the index cycled at least 3 times. Searches that should only hit the latest index ("Search in last 5 minutes") are failing with:

```
2017-03-11T12:06:58.176-06:00 DEBUG [search] [graylog-0e01437a-ab2d-474d-a61a-ad469ffe79df] failed to reduce search
org.elasticsearch.action.search.ReduceSearchPhaseException: [reduce] 
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.onFailure(SearchQueryThenFetchAsyncAction.java:146) [graylog.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: org.elasticsearch.search.aggregations.AggregationExecutionException: Merging/Reducing the aggregations failed when computing the aggregation [ Name: gl2_terms, Type: terms ] because: the field you gave in the aggregation query existed as two different types in two different indices
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms.doReduce(InternalTerms.java:185) ~[graylog.jar:?]
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:153) ~[graylog.jar:?]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:170) ~[graylog.jar:?]
	at org.elasticsearch.search.aggregations.bucket.InternalSingleBucketAggregation.doReduce(InternalSingleBucketAggregation.java:93) ~[graylog.jar:?]
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:153) ~[graylog.jar:?]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:170) ~[graylog.jar:?]
	at org.elasticsearch.search.controller.SearchPhaseController.merge(SearchPhaseController.java:411) ~[graylog.jar:?]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.doRun(SearchQueryThenFetchAsyncAction.java:132) ~[graylog.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[graylog.jar:?]
	... 3 more
2017-03-11T12:06:58.177-06:00 WARN  [SearchResource] Unable to execute search: [reduce] 
```

## Your Environment

* Graylog Version: 2.2.2
* Elasticsearch Version: 2.4.4

**Comment by joschi** [comment]
@lennartkoopmann What are the index ranges for the relevant indices?

**Comment by lennartkoopmann** [comment]
@joschi sorry, I deleted them to get my sales demo working again 😿

**Comment by lennartkoopmann** [comment]
@kay I added this to 2.2.3 to make sure we investigate this

**Comment by Alekc** [comment]
As requested I attach my indexes from graylog (see #4061 for previous discussion)

[mappings.zip](https://github.com/Graylog2/graylog2-server/files/1204841/mappings.zip)

Field which is failing for me (I've been searching through 2 or 3 indexes) is "idx"

```
          "idx" : {
            "type" : "long"
          },
```

possible valid values for that index are:

- Empty
- short integer like 123
- longer integer like 222843025

Those values are sourced through several different applications (Golang, Java, Php), so at least in several cases it's possible that they would come in as string and not an int (although not sure about that). 

Let me know if you need some other details.

**Comment by joschi** [comment]
> Those values are sourced through several different applications (Golang, Java, Php), so at least in several cases it's possible that they would come in as string and not an int (although not sure about that).

You have to make sure that this field (or any field you want to run aggregations on) has the same type over the time range you're querying.

You can ensure that by creating a [custom index mapping in Elasticsearch](http://docs.graylog.org/en/2.3/pages/configuration/elasticsearch.html#custom-index-mappings) and converting these fields explicitly in processing pipelines (e. g. via [`to_long`](http://docs.graylog.org/en/2.3/pages/pipelines/functions.html#to-long)).

**Comment by joschi** [comment]
The question is also, how we should handle diverging types of a field when running aggregations.

Not allow the query in the first place? Reducing the time frame so that the types are the same?

**Comment by Alekc** [comment]
@joschi  Thanks for input, will do that (the damned legacy system on php side :( )

Regarding diverging type, in case of that exception being thrown if you have an access to elasticsearch ranges you could do several queries (and show a warning regarding mixed type of data). 

i.e. : last 7 day query, if it's spans over 7 different indexes, do 7 different queries and show combined result (if possible due to mixed int and string). I think people affected by this bug would prefer to have duplicated/a bit imprecise values (due to string/int presence) compared to being locked out entirely
