### ISSUE TITLE
Search page after "no results" page fails to render histogram

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#3653]
The search results histogram does not load correctly when a previous search returned no results. This is how it looks:
<img width="1670" alt="screen shot 2017-03-24 at 15 17 22" src="https://cloud.githubusercontent.com/assets/716185/24298104/498ba32a-10a5-11e7-9129-9987b1f00bb3.png">

And this is the error in the developer console:

```
Unhandled rejection TypeError: Cannot read property 'x' of undefined
    at eval (webpack:///./~/rickshaw/rickshaw.js?:488:56)
    at Array.map (native)
    at Rickshaw.Graph.dataDomain (webpack:///./~/rickshaw/rickshaw.js?:488:26)
    at klass.build (webpack:///./src/legacy/Rickshaw.Graph.Graylog2Selector.js?:147:15)
    at klass.initialize (webpack:///./src/legacy/Rickshaw.Graph.Graylog2Selector.js?:41:10)
    at new klass (webpack:///./~/rickshaw/rickshaw.js?:183:23)
    at Object.drawResultGraph (webpack:///./src/legacy/result-histogram.js?:112:5)
    at Constructor._renderHistogram (webpack:///./src/components/search/LegacyHistogram.jsx?:74:31)
    at Constructor.componentDidMount (webpack:///./src/components/search/LegacyHistogram.jsx?:49:10)
    at CallbackQueue.notifyAll (http://localhost:8080/build/vendor.js:11796:22)
    at ReactReconcileTransaction.close (http://localhost:8080/build/vendor.js:47042:26)
    at ReactReconcileTransaction.closeAll (http://localhost:8080/build/vendor.js:10359:25)
    at ReactReconcileTransaction.perform (http://localhost:8080/build/vendor.js:10306:16)
    at ReactUpdatesFlushTransaction.perform (http://localhost:8080/build/vendor.js:10293:20)
    at ReactUpdatesFlushTransaction.perform (http://localhost:8080/build/vendor.js:6351:38)
    at Object.flushBatchedUpdates (http://localhost:8080/build/vendor.js:6412:19)
    at Object.wrapper [as flushBatchedUpdates] (http://localhost:8080/build/vendor.js:6228:21)
    at ReactDefaultBatchingStrategyTransaction.closeAll (http://localhost:8080/build/vendor.js:10359:25)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:8080/build/vendor.js:10306:16)
    at Object.batchedUpdates (http://localhost:8080/build/vendor.js:28098:19)
    at Object.enqueueUpdate (http://localhost:8080/build/vendor.js:6441:22)
    at enqueueUpdate (http://localhost:8080/build/vendor.js:12434:16)
    at Object.enqueueSetState (http://localhost:8080/build/vendor.js:12600:5)
    at Constructor.ReactComponent.setState (http://localhost:8080/build/vendor.js:27520:16)
    at promise.UniversalSearchStore.search.then._this2.setState.error (webpack:///./src/pages/SearchPage.jsx?./~/babel-loader/lib?%7B%cacheDirectory%22:%cache%22,%22extends%22:%22/Users/edmundoa/Workspace/graylog/project/master/graylog2-server/graylog2-web-interface/.babelrc%22%7D:135:16)
From previous event:
    at Constructor._refreshData (webpack:///./src/pages/SearchPage.jsx?./~/babel-loader/lib?%7B%cacheDirectory%22:%cache%22,%22extends%22:%22/Users/edmundoa/Workspace/graylog/project/master/graylog2-server/graylog2-web-interface/.babelrc%22%7D:133:206)
    at Constructor.componentWillReceiveProps (webpack:///./src/pages/SearchPage.jsx?./~/babel-loader/lib?%7B%cacheDirectory%22:%cache%22,%22extends%22:%22/Users/edmundoa/Workspace/graylog/project/master/graylog2-server/graylog2-web-interface/.babelrc%22%7D:102:12)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:8080/build/vendor.js:43371:14)
    at ReactCompositeComponentWrapper.wrapper [as updateComponent] (http://localhost:8080/build/vendor.js:6228:21)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:8080/build/vendor.js:43318:10)
    at Object.receiveComponent (http://localhost:8080/build/vendor.js:7477:22)
    at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8390:20)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:8080/build/vendor.js:43475:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:8080/build/vendor.js:43457:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:8080/build/vendor.js:43386:12)
    at ReactCompositeComponentWrapper.wrapper [as updateComponent] (http://localhost:8080/build/vendor.js:6228:21)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:8080/build/vendor.js:43318:10)
    at Object.receiveComponent (http://localhost:8080/build/vendor.js:7477:22)
    at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8390:20)
    at Object.updateChildren (http://localhost:8080/build/vendor.js:42816:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:8080/build/vendor.js:46576:39)
    at ReactDOMComponent._updateChildren (http://localhost:8080/build/vendor.js:46711:31)
    at ReactDOMComponent.updateChildren (http://localhost:8080/build/vendor.js:46686:14)
    at ReactDOMComponent._updateDOMChildren (http://localhost:8080/build/vendor.js:44541:12)
    at ReactDOMComponent.updateComponent (http://localhost:8080/build/vendor.js:44370:10)
    at ReactDOMComponent.receiveComponent (http://localhost:8080/build/vendor.js:44315:10)
    at Object.receiveComponent (http://localhost:8080/build/vendor.js:7477:22)
    at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8390:20)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:8080/build/vendor.js:43475:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:8080/build/vendor.js:43457:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:8080/build/vendor.js:43386:12)
    at ReactCompositeComponentWrapper.wrapper [as updateComponent] (http://localhost:8080/build/vendor.js:6228:21)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:8080/build/vendor.js:43318:10)
    at Object.receiveComponent (http://localhost:8080/build/vendor.js:7477:22)
    at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8390:20)
    at Object.updateChildren (http://localhost:8080/build/vendor.js:42816:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:8080/build/vendor.js:46576:39)
    at ReactDOMComponent._updateChildren (http://localhost:8080/build/vendor.js:46711:31)
    at ReactDOMComponent.updateChildren (http://localhost:8080/build/vendor.js:46686:14)
    at ReactDOMComponent._updateDOMChildren (http://localhost:8080/build/vendor.js:44541:12)
    at ReactDOMComponent.updateComponent (http://localhost:8080/build/vendor.js:44370:10)
    at ReactDOMComponent.receiveComponent (http://localhost:8080/build/vendor.js:44315:10)
    at Object.receiveComponent (http://localhost:8080/build/vendor.js:7477:22)
    at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8390:20)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:8080/build/vendor.js:43475:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:8080/build/vendor.js:43457:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:8080/build/vendor.js:43386:12)
    at ReactCompositeComponentWrapper.wrapper [as updateComponent] (http://localhost:8080/build/vendor.js:6228:21)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:8080/build/vendor.js:43318:10)
    at Object.receiveComponent (http://localhost:8080/build/vendor.js:7477:22)
    at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8390:20)
    at Object.updateChildren (http://localhost:8080/build/vendor.js:42816:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:8080/build/vendor.js:46576:39)
    at ReactDOMComponent._updateChildren (http://localhost:8080/build/vendor.js:46711:31)
    at ReactDOMComponent.updateChildren (http://localhost:8080/build/vendor.js:46686:14)
    at ReactDOMComponent._updateDOMChildren (http://localhost:8080/build/vendor.js:44541:12)
    at ReactDOMComponent.updateComponent (http://localhost:8080/build/vendor.js:44370:10)
    at ReactDOMComponent.receiveComponent (http://localhost:8080/build/vendor.js:44315:10)
    at Object.receiveComponent (http://localhost:8080/build/vendor.js:7477:22)
    at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8390:20)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:8080/build/vendor.js:43475:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:8080/build/vendor.js:43457:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:8080/build/vendor.js:43386:12)
    at ReactCompositeComponentWrapper.wrapper [as updateComponent] (http://localhost:8080/build/vendor.js:6228:21)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:8080/build/vendor.js:43318:10)
    at Object.receiveComponent (http://localhost:8080/build/vendor.js:7477:22)
    at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8390:20)
    at Object.updateChildren (http://localhost:8080/build/vendor.js:42816:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:8080/build/vendor.js:46576:39)
    at ReactDOMComponent._updateChildren (http://localhost:8080/build/vendor.js:46711:31)
    at ReactDOMComponent.updateChildren (http://localhost:8080/build/vendor.js:46686:14)
    at ReactDOMComponent._updateDOMChildren (http://localhost:8080/build/vendor.js:44541:12)
```

## Steps to Reproduce (for bugs)
1. Perform a search returning no results, e.g. "asdklsalda"
2. Perform a search that returns results
3. Observe that the histogram is not properly rendered. The rest of the page looks fine

## Your Environment
* Graylog Version: Graylog-2.3.0-SNAPSHOT (4ded9e7a2f477f7657a01ee217794b00ee6f9e69). I could **not** reproduce this issue in Graylog-2.2.2

**Comment by joschi** [comment]
@edmundoa I couldn't reproduce it on latest `master` (645511eca7e20505ce9f879636c12c7b8d5bfda7).
Could you please verify that the problem does or does not occur with that commit?

**Comment by dennisoelkers** [comment]
Same here. I just stumbled across this issue and was not able to reproduce it on master. Can you reverify it and add more instructions how to reproduce it?

**Comment by edmundoa** [comment]
Closing the issue, as I also can't reproduce this in the current master, probably something fixed the issue in between.

**Comment by edmundoa** [comment]
Thank you for looking into it @joschi and @dennisoelkers!

**Comment by de1m** [comment]
I've the same error, but only in Kubernetes, if I use the Ingress Controller (Nginx Reverse Proxy). To fix the error I've added as endpoint /assets
Full example:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: logging.domain.local
  namespace: internal
  annotations:
    kubernetes.io/ingress.class: "internal"
spec:
  rules:
  - host: logging.domain.local
    http:
      paths:
      - path: /
        backend:
          serviceName: logging-domain-local
          servicePort: 9000
      - path: /assets
        backend:
          serviceName: logging-domain-local
          servicePort: 9000
```
