### ISSUE TITLE
elasticsearch dont start

### ISSUE THREAD

**Issue by flapegue** [Graylog2/graylog2-server#3655]
after utpdate and light customize configuration, elasticsearch dont start

**/etc/graylog/server/server.conf**
```
is_master = true
node_id_file = /etc/graylog/server/node-id
password_secret = X
root_password_sha2 = XXXXX
root_timezone = Europe/Paris
plugin_dir = /usr/share/graylog-server/plugin
rest_listen_uri = http://X.X.X.X:9000/api/
rest_transport_uri = http://X.X.X.X:9000/api/
web_listen_uri = http://X.X.X.X:9000/
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 1
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 20
outputbuffer_processors = 15
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://localhost/graylog
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
content_packs_dir = /usr/share/graylog-server/contentpacks
content_packs_auto_load = grok-patterns.json
proxied_requests_thread_pool_size = 32
```

**/etc/default/graylog-server**
```
JAVA=/usr/bin/java
GRAYLOG_SERVER_JAVA_OPTS="-Xms1g -Xmx1g -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow"
GRAYLOG_SERVER_ARGS=""
GRAYLOG_COMMAND_WRAPPER=""
```

**/etc/elasticsearch/elasticsearch.xml**
`cluster.name: graylog`

**/etc/default/elasticsearch**
```
ES_HEAP_SIZE=4g
ES_STARTUP_SLEEP_TIME=5
```

* Graylog Version: 2.2.2-1
* Elasticsearch Version: 2.4.4
* MongoDB Version: 1:2.4.10-5
* Operating System: Linux Debian 8.7

**/var/log/graylog-server/server.log**
```
2017-03-25T23:16:33.553+01:00 INFO  [CmdLineTool] Loaded plugin: Elastic Beats Input 2.2.2 [org.graylog.plugins.beats.BeatsInputPlugin]
2017-03-25T23:16:33.556+01:00 INFO  [CmdLineTool] Loaded plugin: Collector 2.2.2 [org.graylog.plugins.collector.CollectorPlugin]
2017-03-25T23:16:33.557+01:00 INFO  [CmdLineTool] Loaded plugin: Enterprise Integration Plugin 2.2.2 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]
2017-03-25T23:16:33.558+01:00 INFO  [CmdLineTool] Loaded plugin: MapWidgetPlugin 2.2.2 [org.graylog.plugins.map.MapWidgetPlugin]
2017-03-25T23:16:33.568+01:00 INFO  [CmdLineTool] Loaded plugin: Pipeline Processor Plugin 2.2.2 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin]
2017-03-25T23:16:33.568+01:00 INFO  [CmdLineTool] Loaded plugin: Anonymous Usage Statistics 2.2.2 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]
2017-03-25T23:16:33.943+01:00 INFO  [CmdLineTool] Running with JVM arguments: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configurationFile=file:///etc/graylog/server/log4j2.xml -Djava.library.path=/usr/share/graylog-server/lib/sigar -Dgraylog2.installation_source=deb
2017-03-25T23:16:34.235+01:00 INFO  [Version] HV000001: Hibernate Validator null
2017-03-25T23:16:36.548+01:00 INFO  [InputBufferImpl] Message journal is enabled.
2017-03-25T23:16:36.615+01:00 INFO  [NodeId] Node ID: c681d163-7631-4475-9f92-af09b7d48d54
2017-03-25T23:16:36.823+01:00 INFO  [LogManager] Loading logs.
2017-03-25T23:16:37.013+01:00 INFO  [LogManager] Logs loading complete.
2017-03-25T23:16:37.013+01:00 INFO  [KafkaJournal] Initialized Kafka based journal at /var/lib/graylog-server/journal
2017-03-25T23:16:37.028+01:00 INFO  [InputBufferImpl] Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
2017-03-25T23:16:37.050+01:00 INFO  [cluster] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=5000}
2017-03-25T23:16:37.106+01:00 INFO  [cluster] No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
2017-03-25T23:16:37.199+01:00 INFO  [connection] Opened connection [connectionId{localValue:1, serverValue:52}] to localhost:27017
2017-03-25T23:16:37.203+01:00 INFO  [cluster] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[2, 4, 10]}, minWireVersion=0, maxWireVersion=0, maxDocumentSize=16777216, roundTripTimeNanos=458947}
2017-03-25T23:16:37.208+01:00 INFO  [connection] Opened connection [connectionId{localValue:2, serverValue:53}] to localhost:27017
2017-03-25T23:16:37.546+01:00 INFO  [node] [graylog-c681d163-7631-4475-9f92-af09b7d48d54] version[2.4.4], pid[4197], build[fcbb46d/2017-01-03T11:33:16Z]
2017-03-25T23:16:37.546+01:00 INFO  [node] [graylog-c681d163-7631-4475-9f92-af09b7d48d54] initializing ...
2017-03-25T23:16:37.552+01:00 INFO  [plugins] [graylog-c681d163-7631-4475-9f92-af09b7d48d54] modules [], plugins [graylog-monitor], sites []
2017-03-25T23:16:38.983+01:00 INFO  [node] [graylog-c681d163-7631-4475-9f92-af09b7d48d54] initialized
2017-03-25T23:16:39.091+01:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2017-03-25T23:16:40.978+01:00 INFO  [RulesEngineProvider] No static rules file loaded.
2017-03-25T23:16:41.431+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.437+01:00 INFO  [OutputBuffer] Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2017-03-25T23:16:41.493+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.551+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.600+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.643+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.687+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.731+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.777+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.818+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.858+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.897+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.935+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:41.973+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:42.009+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:42.046+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:42.080+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:42.115+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:42.149+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:42.181+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:42.212+01:00 WARN  [GeoIpResolverEngine] GeoIP database file does not exist: /etc/graylog/server/GeoLite2-City.mmdb
2017-03-25T23:16:42.864+01:00 INFO  [ServerBootstrap] Graylog server 2.2.2+691b4b7 starting up
2017-03-25T23:16:42.865+01:00 INFO  [ServerBootstrap] JRE: Oracle Corporation 1.8.0_121 on Linux 3.16.0-4-amd64
2017-03-25T23:16:42.865+01:00 INFO  [ServerBootstrap] Deployment: deb
2017-03-25T23:16:42.865+01:00 INFO  [ServerBootstrap] OS: Debian GNU/Linux 8 (jessie) (debian)
2017-03-25T23:16:42.865+01:00 INFO  [ServerBootstrap] Arch: amd64
2017-03-25T23:16:42.869+01:00 WARN  [DeadEventLoggingListener] Received unhandled event of type <org.graylog2.plugin.lifecycles.Lifecycle> from event bus <AsyncEventBus{graylog-eventbus}>
2017-03-25T23:16:42.889+01:00 INFO  [PeriodicalsService] Starting 26 periodicals ...
2017-03-25T23:16:42.889+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ThroughputCalculator] periodical in [0s], polling every [1s].
2017-03-25T23:16:42.898+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.AlertScannerThread] periodical in [10s], polling every [60s].
2017-03-25T23:16:42.916+01:00 INFO  [node] [graylog-c681d163-7631-4475-9f92-af09b7d48d54] starting ...
2017-03-25T23:16:42.917+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] periodical in [0s], polling every [1s].
2017-03-25T23:16:42.918+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ClusterHealthCheckThread] periodical in [120s], polling every [20s].
2017-03-25T23:16:42.919+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ContentPackLoaderPeriodical] periodical, running forever.
2017-03-25T23:16:42.919+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.GarbageCollectionWarningThread] periodical, running forever.
2017-03-25T23:16:42.920+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.IndexerClusterCheckerThread] periodical in [0s], polling every [30s].
2017-03-25T23:16:42.920+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRetentionThread] periodical in [0s], polling every [300s].
2017-03-25T23:16:42.922+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRotationThread] periodical in [0s], polling every [10s].
2017-03-25T23:16:42.924+01:00 INFO  [IndexRetentionThread] Elasticsearch cluster not available, skipping index retention checks.
2017-03-25T23:16:42.924+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.NodePingThread] periodical in [0s], polling every [1s].
2017-03-25T23:16:42.928+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.VersionCheckThread] periodical in [300s], polling every [1800s].
2017-03-25T23:16:42.928+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
2017-03-25T23:16:42.929+01:00 INFO  [Periodicals] Starting [org.graylog2.events.ClusterEventPeriodical] periodical in [0s], polling every [1s].
2017-03-25T23:16:42.932+01:00 INFO  [Periodicals] Starting [org.graylog2.events.ClusterEventCleanupPeriodical] periodical in [0s], polling every [86400s].
2017-03-25T23:16:42.933+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ClusterIdGeneratorPeriodical] periodical, running forever.
2017-03-25T23:16:42.933+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRangesMigrationPeriodical] periodical, running forever.
2017-03-25T23:16:42.933+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.IndexRangesCleanupPeriodical] periodical in [15s], polling every [3600s].
2017-03-25T23:16:42.950+01:00 INFO  [connection] Opened connection [connectionId{localValue:3, serverValue:54}] to localhost:27017
2017-03-25T23:16:42.969+01:00 INFO  [connection] Opened connection [connectionId{localValue:8, serverValue:59}] to localhost:27017
2017-03-25T23:16:42.970+01:00 INFO  [connection] Opened connection [connectionId{localValue:10, serverValue:61}] to localhost:27017
2017-03-25T23:16:42.975+01:00 INFO  [connection] Opened connection [connectionId{localValue:5, serverValue:56}] to localhost:27017
2017-03-25T23:16:42.975+01:00 INFO  [connection] Opened connection [connectionId{localValue:7, serverValue:58}] to localhost:27017
2017-03-25T23:16:42.975+01:00 INFO  [connection] Opened connection [connectionId{localValue:4, serverValue:55}] to localhost:27017
2017-03-25T23:16:42.974+01:00 INFO  [connection] Opened connection [connectionId{localValue:9, serverValue:60}] to localhost:27017
2017-03-25T23:16:42.981+01:00 INFO  [connection] Opened connection [connectionId{localValue:6, serverValue:57}] to localhost:27017
2017-03-25T23:16:43.009+01:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.UserPermissionMigrationPeriodical] periodical. Not configured to run on this node.
2017-03-25T23:16:43.009+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.AlarmCallbacksMigrationPeriodical] periodical, running forever.
2017-03-25T23:16:43.009+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ConfigurationManagementPeriodical] periodical, running forever.
2017-03-25T23:16:43.015+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.LdapGroupMappingMigration] periodical, running forever.
2017-03-25T23:16:43.016+01:00 INFO  [Periodicals] Starting [org.graylog2.periodical.IndexFailuresPeriodical] periodical, running forever.
2017-03-25T23:16:43.020+01:00 INFO  [Periodicals] Starting [org.graylog.plugins.usagestatistics.UsageStatsNodePeriodical] periodical in [300s], polling every [21600s].
2017-03-25T23:16:43.021+01:00 INFO  [Periodicals] Starting [org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical] periodical in [300s], polling every [21600s].
2017-03-25T23:16:43.037+01:00 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2017-03-25T23:16:43.306+01:00 INFO  [Periodicals] Starting [org.graylog.plugins.pipelineprocessor.periodical.LegacyDefaultStreamMigration] periodical, running forever.
2017-03-25T23:16:43.309+01:00 INFO  [Periodicals] Starting [org.graylog.plugins.collector.periodical.PurgeExpiredCollectorsThread] periodical in [0s], polling every [3600s].
2017-03-25T23:16:43.311+01:00 INFO  [V20161130141500_DefaultStreamRecalcIndexRanges] Cluster not connected yet, delaying migration until it is reachable.
2017-03-25T23:16:43.322+01:00 INFO  [LegacyDefaultStreamMigration] Legacy default stream has no connections, no migration needed.
2017-03-25T23:16:43.382+01:00 INFO  [transport] [graylog-c681d163-7631-4475-9f92-af09b7d48d54] publish_address {127.0.0.1:9350}, bound_addresses {127.0.0.1:9350}
2017-03-25T23:16:43.391+01:00 INFO  [discovery] [graylog-c681d163-7631-4475-9f92-af09b7d48d54] graylog/EOvPSWeVQK-cTyn1zK6pJw
2017-03-25T23:16:43.526+01:00 INFO  [JerseyService] Enabling CORS for HTTP endpoint
2017-03-25T23:16:46.397+01:00 WARN  [discovery] [graylog-c681d163-7631-4475-9f92-af09b7d48d54] waited for 3s and no initial state was set by the discovery
2017-03-25T23:16:46.398+01:00 INFO  [node] [graylog-c681d163-7631-4475-9f92-af09b7d48d54] started
2017-03-25T23:16:51.403+01:00 WARN  [IndexerSetupService] Could not connect to Elasticsearch
2017-03-25T23:16:51.403+01:00 INFO  [IndexerSetupService] If you're using multicast, check that it is working in your network and that Elasticsearch is accessible. Also check that the cluster name setting is correct.
2017-03-25T23:16:51.404+01:00 INFO  [IndexerSetupService] See http://docs.graylog.org/en/2.2/pages/configuration/elasticsearch.html for details.
2017-03-25T23:16:54.284+01:00 INFO  [NetworkListener] Started listener bound to [X.X.X.X:9000]
2017-03-25T23:16:54.285+01:00 INFO  [HttpServer] [HttpServer] Started.
2017-03-25T23:16:54.285+01:00 INFO  [JerseyService] Started REST API at <http://X.X.X.X:9000/api/>
2017-03-25T23:16:54.285+01:00 INFO  [JerseyService] Started Web Interface at <http://X.X.X.X:9000/>
2017-03-25T23:16:54.287+01:00 INFO  [ServiceManagerListener] Services are healthy
2017-03-25T23:16:54.287+01:00 INFO  [ServerBootstrap] Services started, startup times in ms: {InputSetupService [RUNNING]=30, OutputSetupService [RUNNING]=45, BufferSynchronizerService [RUNNING]=57, ConfigurationEtagService [RUNNING]=78, KafkaJournal [RUNNING]=81, JournalReader [RUNNING]=102, StreamCacheService [RUNNING]=151, PeriodicalsService [RUNNING]=442, IndexerSetupService [RUNNING]=8497, JerseyService [RUNNING]=11397}
2017-03-25T23:16:54.289+01:00 INFO  [InputSetupService] Triggering launching persisted inputs, node transitioned from Uninitialized [LB:DEAD] to Running [LB:ALIVE]
2017-03-25T23:16:54.292+01:00 INFO  [ServerBootstrap] Graylog server up and running.
2017-03-25T23:16:54.320+01:00 INFO  [KafkaJournal] Read offset 1584840751 before start of log at 1623733224, starting to read from the beginning of the journal.
2017-03-25T23:16:54.320+01:00 INFO  [InputStateListener] Input [Syslog UDP/585932977cf25703ba10ea88] is now STARTING
2017-03-25T23:16:54.337+01:00 INFO  [InputStateListener] Input [Syslog UDP/585c0e157cf25703ba13eade] is now STARTING
2017-03-25T23:16:54.338+01:00 INFO  [InputStateListener] Input [Syslog UDP/58d6a367c2ae590814eef6d8] is now STARTING
2017-03-25T23:16:54.339+01:00 INFO  [InputStateListener] Input [GELF UDP/58592d4d7cf25703ba10e4f5] is now STARTING
2017-03-25T23:16:54.339+01:00 INFO  [InputStateListener] Input [Syslog UDP/58592c007cf25703ba10e385] is now STARTING
2017-03-25T23:16:54.340+01:00 INFO  [InputStateListener] Input [Syslog TCP/5862e7c57cf2576ac2f152b8] is now STARTING
2017-03-25T23:16:54.353+01:00 WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input SyslogTCPInput{title=PaloAlto-Syslog, type=org.graylog2.inputs.syslog.tcp.SyslogTCPInput, nodeId=c681d163-7631-4475-9f92-af09b7d48d54} should be 1048576 but is 212992.
2017-03-25T23:16:54.429+01:00 WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input SyslogUDPInput{title=Syslog UDP (514), type=org.graylog2.inputs.syslog.udp.SyslogUDPInput, nodeId=c681d163-7631-4475-9f92-af09b7d48d54} should be 262144 but is 212992.
2017-03-25T23:16:54.430+01:00 WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input SyslogUDPInput{title=Syslog UDP (localhost), type=org.graylog2.inputs.syslog.udp.SyslogUDPInput, nodeId=c681d163-7631-4475-9f92-af09b7d48d54} should be 262144 but is 212992.
2017-03-25T23:16:54.430+01:00 WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input GELFUDPInput{title=Windows-NXLog, type=org.graylog2.inputs.gelf.udp.GELFUDPInput, nodeId=c681d163-7631-4475-9f92-af09b7d48d54} should be 262144 but is 212992.
2017-03-25T23:16:54.430+01:00 WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input SyslogUDPInput{title=Syslog UDP (global), type=org.graylog2.inputs.syslog.udp.SyslogUDPInput, nodeId=c681d163-7631-4475-9f92-af09b7d48d54} should be 262144 but is 212992.
2017-03-25T23:16:54.431+01:00 WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input SyslogUDPInput{title=PaloAlto-Syslog, type=org.graylog2.inputs.syslog.udp.SyslogUDPInput, nodeId=c681d163-7631-4475-9f92-af09b7d48d54} should be 262144 but is 212992.
2017-03-25T23:16:54.560+01:00 INFO  [InputStateListener] Input [Syslog TCP/5862e7c57cf2576ac2f152b8] is now RUNNING
2017-03-25T23:16:54.561+01:00 INFO  [InputStateListener] Input [Syslog UDP/58592c007cf25703ba10e385] is now RUNNING
2017-03-25T23:16:54.562+01:00 INFO  [InputStateListener] Input [GELF UDP/58592d4d7cf25703ba10e4f5] is now RUNNING
2017-03-25T23:16:54.566+01:00 INFO  [InputStateListener] Input [Syslog UDP/585932977cf25703ba10ea88] is now RUNNING
2017-03-25T23:16:54.569+01:00 INFO  [InputStateListener] Input [Syslog UDP/58d6a367c2ae590814eef6d8] is now RUNNING
2017-03-25T23:16:54.569+01:00 INFO  [InputStateListener] Input [Syslog UDP/585c0e157cf25703ba13eade] is now RUNNING
2017-03-25T23:16:57.934+01:00 INFO  [IndexRangesCleanupPeriodical] Skipping index range cleanup because the Elasticsearch cluster is unreachable or unhealthy
2017-03-25T23:17:14.309+01:00 WARN  [KafkaJournal] Journal utilization (403.0%) has gone over 95%.
2017-03-25T23:17:14.358+01:00 INFO  [KafkaJournal] Journal usage is 403.00% (threshold 100%), changing load balancer status from ALIVE to THROTTLED
2017-03-25T23:17:43.313+01:00 WARN  [V20161130141500_DefaultStreamRecalcIndexRanges] Interrupted or timed out waiting for Elasticsearch cluster, checking again.
2017-03-25T23:17:44.318+01:00 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2017-03-25T23:17:54.854+01:00 WARN  [BlockingBatchedESOutput] Error while waiting for healthy Elasticsearch cluster. Not flushing.
java.util.concurrent.TimeoutException: Write-active index didn't get healthy within timeout
	at org.graylog2.indexer.cluster.Cluster.waitForConnectedAndDeflectorHealthy(Cluster.java:221) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.Cluster.waitForConnectedAndDeflectorHealthy(Cluster.java:232) ~[graylog.jar:?]
	at org.graylog2.outputs.BlockingBatchedESOutput.flush(BlockingBatchedESOutput.java:121) [graylog.jar:?]
	at org.graylog2.outputs.BlockingBatchedESOutput.writeMessageEntry(BlockingBatchedESOutput.java:114) [graylog.jar:?]
	at org.graylog2.outputs.BlockingBatchedESOutput.write(BlockingBatchedESOutput.java:96) [graylog.jar:?]
	at org.graylog2.buffers.processors.OutputBufferProcessor$1.run(OutputBufferProcessor.java:194) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2017-03-25T23:17:54.873+01:00 INFO  [KafkaJournal] Read offset 1623864443 before start of log at 1639736812, starting to read from the beginning of the journal.
2017-03-25T23:17:55.015+01:00 WARN  [BlockingBatchedESOutput] Error while waiting for healthy Elasticsearch cluster. Not flushing.
java.util.concurrent.TimeoutException: Write-active index didn't get healthy within timeout
	at org.graylog2.indexer.cluster.Cluster.waitForConnectedAndDeflectorHealthy(Cluster.java:221) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.Cluster.waitForConnectedAndDeflectorHealthy(Cluster.java:232) ~[graylog.jar:?]
	at org.graylog2.outputs.BlockingBatchedESOutput.flush(BlockingBatchedESOutput.java:121) [graylog.jar:?]
	at org.graylog2.outputs.BlockingBatchedESOutput.writeMessageEntry(BlockingBatchedESOutput.java:114) [graylog.jar:?]
	at org.graylog2.outputs.BlockingBatchedESOutput.write(BlockingBatchedESOutput.java:96) [graylog.jar:?]
	at org.graylog2.buffers.processors.OutputBufferProcessor$1.run(OutputBufferProcessor.java:194) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

How can i manually start elasticsearch for testing boot ?
How can i repair this ?

**Comment by flapegue** [comment]
it solve, i was force reinstall.
