### ISSUE TITLE
User list not loading after upgrade to Graylog 2.2.2+691b4b7

### ISSUE THREAD

**Issue by wilfrredhariden** [Graylog2/graylog2-server#3660]
Few days ago we upgraded our Graylog server from 2.0.1 to 2.2.2. Now when we go to Authentication  -> Users it stuck on loading animation showing red error below:
```
Could not load user list
Loading user list failed with status: Error: cannot GET http://hostname:12900/users (500)
Got following in graylog server log:
 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to [B
        at org.graylog2.security.MongoDbSession.getAttributes(MongoDbSession.java:62) ~[graylog.jar:?]
        at org.graylog2.security.MongoDbSession.getUsernameAttribute(MongoDbSession.java:92) ~[graylog.jar:?]
        at org.graylog2.rest.resources.users.UsersResource.lambda$listUsers$0(UsersResource.java:146) ~[graylog.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_91]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_91]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_91]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_91]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_91]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_91]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_91]
        at org.graylog2.rest.resources.users.UsersResource.listUsers(UsersResource.java:147) ~[graylog.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[gra                                                                    ylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

# Expected Behavior
User list appears

# Current Behavior
User list page stuck on loading animation with error:
cannot GET http://hostname:12900/users (500)

* Graylog Version: 2.2.2
* Elasticsearch Version: 2.3.4
* MongoDB Version: 3.2.8
* Operating System: Oracle Linux Server release 7.2

**Comment by joschi** [comment]
@wilfrredhariden `http://hostname:12900/` is probably the wrong URI for the Graylog REST API.

Please read the upgrade notes for Graylog 2.1.x and 2.2.x for information about changed default settings: http://docs.graylog.org/en/2.2/pages/upgrade.html

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by wilfrredhariden** [comment]
All other REST calls are working with these settings. Just this one not. If i call: http://10.3.71.74:12900/users/test.user it returns info about this user.

**Comment by erlioniel** [comment]
@joschi thank you for answer, but how it related to the error?
The error produced by Mongo and related to ClassCastException, isn't it?

**Comment by joschi** [comment]
@wilfrredhariden Please move this discussion to the [discussion forums](https://community.graylog.org/) and add your Graylog configuration file, your Graylog server logs, and the output of the following command (replace the variables with your actual credentials):
```
curl -u $ADMIN_USER:$ADMIN_PASSWORD -H 'Accept: application/json' http://10.3.71.74:12900/users
```

**Comment by mevansFCStone** [comment]
Was this solved ever?
