### ISSUE TITLE
Node System Unavailable 

### ISSUE THREAD

**Issue by shann1890** [Graylog2/graylog2-server#3679]
![image](https://cloud.githubusercontent.com/assets/26848550/24598188/ae9c6126-187c-11e7-9acf-2d66e256b242.png)

## Current Behavior

Not showing system nodes status. After full load of the Node page, Input will not be working for 2 minutes. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.2.2
* Elasticsearch Version:2.4
* MongoDB Version:3.4
* Operating System:CentOS7
* Browser version:

**Comment by joschi** [comment]
@shann1890 Are there any error messages in the logs of your Graylog node(s) or in the developer console of your web browser?

**Comment by shann1890** [comment]
![image](https://cloud.githubusercontent.com/assets/26848550/24601023/e8abbb48-1889-11e7-901f-3dd3d3b686b9.png)


![image](https://cloud.githubusercontent.com/assets/26848550/24601043/fc99a868-1889-11e7-8953-91d3c06211ae.png)


This is what i can find from overview.

**Comment by joschi** [comment]
@shann1890 That's not what I've asked for.

See these links for information about how to open the developer console of your web browser:

* https://developers.google.com/web/tools/chrome-devtools/console/
* https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console
* https://msdn.microsoft.com/en-us/library/gg589530(v=vs.85).aspx

Also make sure to check the logs of your Graylog node(s), see http://docs.graylog.org/en/2.2/pages/configuration/file_location.html for specific file locations.

**Comment by shann1890** [comment]
`
bluebird.js:1542 Warning: a promise was rejected with a non-error: [object Object]
    at http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…ipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:257:20483
    at h.callback (http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…ipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:257:25914)
    at h.<anonymous> (http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…ipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:257:22856)
    at h.n.emit (http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…ipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:159:25774)
    at XMLHttpRequest.i.onreadystatechange (http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…ipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:257:26792)
From previous event:
    at h.r.promise (http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…ipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:257:20286)
    at h.r.then (http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…ipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:257:20617)
    at e.value (http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…s.pipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:1:3714)
    at i (http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…s.pipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:1:1711)
    at s (http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…s.pipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:1:1782)
    at t.jvm (http://10.31.22.114:9000/assets/plugin/org.graylog.plugins.pipelineprocesso…ipelineprocessor.PipelineProcessorPlugin.b14de9060a6b59e4c9f6.js:151:31020)
    at n.componentWillMount (http://10.31.22.114:9000/assets/17.17.9f581fc7167d550338b4.js:2:2752)
    at p.mountComponent (http://10.31.22.114:9000/assets/vendor.js:34:5058)
    at p.i [as mountComponent] (http://10.31.22.114:9000/assets/vendor.js:7:19332)
    at Object.mountComponent (http://10.31.22.114:9000/assets/vendor.js:8:200)
    at p._updateRenderedComponent (http://10.31.22.114:9000/assets/vendor.js:34:9758)
    at p._performComponentUpdate (http://10.31.22.114:9000/assets/vendor.js:34:9333)
    at p.updateComponent (http://10.31.22.114:9000/assets/vendor.js:34:8611)
    at p.i [as updateComponent] (http://10.31.22.114:9000/assets/vendor.js:7:19332)
    at performUpdateIfNecessary (http://10.31.22.114:9000/assets/vendor.js:34:7891)
    at Object.performUpdateIfNecessary (http://10.31.22.114:9000/assets/vendor.js:8:693)
    at s (http://10.31.22.114:9000/assets/vendor.js:7:20308)
    at o.perform (http://10.31.22.114:9000/assets/vendor.js:8:25971)
    at r.perform (http://10.31.22.114:9000/assets/vendor.js:8:25971)
    at r.perform (http://10.31.22.114:9000/assets/vendor.js:7:21432)
    at Object.T (http://10.31.22.114:9000/assets/vendor.js:7:21601)
    at Object.i [as flushBatchedUpdates] (http://10.31.22.114:9000/assets/vendor.js:7:19332)
    at o.closeAll (http://10.31.22.114:9000/assets/vendor.js:8:26715)
    at o.perform (http://10.31.22.114:9000/assets/vendor.js:8:26054)
    at Object.batchedUpdates (http://10.31.22.114:9000/assets/vendor.js:29:4842)
    at Object.c [as enqueueUpdate] (http://10.31.22.114:9000/assets/vendor.js:7:20508)
    at o (http://10.31.22.114:9000/assets/vendor.js:9:15819)
    at Object.enqueueSetState (http://10.31.22.114:9000/assets/vendor.js:9:18041)
    at n.o.setState (http://10.31.22.114:9000/assets/vendor.js:28:30617)
    at n.<anonymous> (http://10.31.22.114:9000/assets/app.9f581fc7167d550338b4.js:1:22887)
    at http://10.31.22.114:9000/assets/5.5.9f581fc7167d550338b4.js:16:1030
    at window.webpackJsonp (http://10.31.22.114:9000/assets/app.9f581fc7167d550338b4.js:1:351)
    at http://10.31.22.114:9000/assets/17.17.9f581fc7167d550338b4.js:1:1
O @ bluebird.js:1542
E @ bluebird.js:1258
y @ bluebird.js:1153
n._warn @ bluebird.js:763
o._rejectCallback @ bluebird.js:3198
(anonymous) @ bluebird.js:3212
(anonymous) @ index.js:82
h.callback @ client.js:692
(anonymous) @ client.js:512
n.emit @ index.js:133
i.onreadystatechange @ client.js:772
FetchProvider.js:17 There was an error fetching a resource: cannot GET http://10.31.22.114:9000/api/cluster/4414ebc7-b975-404b-a492-c741ce5f3f0c/jvm (500). Additional information: timeout
t @ FetchProvider.js:17
(anonymous) @ FetchProvider.js:82
r @ bluebird.js:5215
o._settlePromiseFromHandler @ bluebird.js:3238
o._settlePromise @ bluebird.js:3295
o._settlePromise0 @ bluebird.js:3340
o._settlePromises @ bluebird.js:3415
(anonymous) @ bluebird.js:175
vendor.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ShowNodePage component.`

**Comment by shann1890** [comment]
Once i select System/Nodes, the graylog totally won't response and getting INPUTs

**Comment by joschi** [comment]
@shann1890 What's in the logs of your Graylog nodes?

**Comment by shann1890** [comment]
![image](https://cloud.githubusercontent.com/assets/26848550/24609274/c84df528-18ac-11e7-89bd-09d624426de7.png)

**Comment by joschi** [comment]
@shann1890 These are not the logs of your Graylog nodes.

Please check http://docs.graylog.org/en/2.2/pages/configuration/file_location.html for specific file locations of the log files.

**Comment by shann1890** [comment]
2017-04-03T11:03:51.121-04:00 INFO  [zen] [graylog-ca852f3e-0933-4d3b-a0d2-898d1a20e829] failed to send join request to master [{es02}{kDGTS7OISLCP-kW5SM6lFA}{10.31.22.115}{10.31.22.115:9300}], reason [RemoteTransportException[[es02][10.31.22.115:9300][internal:discovery/zen/join]]; nested: ConnectTransportException[[graylog-ca852f3e-0933-4d3b-a0d2-898d1a20e829][127.0.0.1:9350] connect_timeout[30s]]; nested: NotSerializableExceptionWrapper[connect_exception: Connection refused: /127.0.0.1:9350]; ]

![image](https://cloud.githubusercontent.com/assets/26848550/24618798/c6771298-18ca-11e7-88bf-59316e72540f.png)

Is this due to cluster node?

**Comment by joschi** [comment]
@shann1890 It looks like the Elasticsearch nodes aren't able to communicate with the embedded ES node in the Graylog process.

Please read http://docs.graylog.org/en/2.2/pages/configuration/elasticsearch.html#network-setup for details.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
