### ISSUE TITLE
Javascript issues when user has no reading permissions on decorators

### ISSUE THREAD

**Issue by svanschie** [Graylog2/graylog2-server#3696]
## Current Behavior
When logged in as a user without reading permissions on decorators, several component of the web interface are not functioning properly.

For example the following in /streams/x/search:
- Histogram isn't shown
- Log messages cannot be expanded
- 'Add to dashboard' button doesn't work (no dropdown list, 'add count to dashboard' does work for what it's worth)
- Actions on fields don't work, for example 'Generate chart' and 'Quick values'. No error message, simply nothing happens.

Some output of web developer console:

<pre>
client.js:841 GET https://dedacteddomain/api/search/decorators 403 (Forbidden)

bluebird.js:1542 Warning: a promise was rejected with a non-error: [object Object]
    at https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…ipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:257:20483
    at h.callback (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…ipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:257:25914)
    at h.<anonymous> (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…ipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:257:22856)
    at h.n.emit (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…ipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:159:25710)
    at XMLHttpRequest.i.onreadystatechange (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…ipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:257:26792)
From previous event:
    at h.r.promise (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…ipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:257:20286)
    at h.r.then (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…ipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:257:20617)
    at e.value (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…s.pipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:1:3748)
    at i (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…s.pipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:1:1924)
    at Function.<anonymous> (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…s.pipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:1:1836)
    at r.n (https://dedacteddomain/assets/vendor.js:46:10756)
    at r.emit (https://dedacteddomain/assets/vendor.js:39:19459)
    at Function.trigger (https://dedacteddomain/assets/vendor.js:46:11633)
    at https://dedacteddomain/assets/vendor.js:46:11737
    at t.exports (https://dedacteddomain/assets/polyfill.35e28e4da7743596569a.js:1:18591)
    at y.(anonymous function) (https://dedacteddomain/assets/polyfill.35e28e4da7743596569a.js:1:25209)
    at Number.g (https://dedacteddomain/assets/polyfill.35e28e4da7743596569a.js:1:25067)
    at MessagePort.b (https://dedacteddomain/assets/polyfill.35e28e4da7743596569a.js:1:25089)

FetchProvider.js:17 There was an error fetching a resource: cannot GET https://dedacteddomain/api/search/decorators (403). Additional information: Not authorized

vendor.js:46 Uncaught (in promise) Error: cannot GET https://dedacteddomain/api/search/decorators (403)
    at new t (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…s.pipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:1:2804)
    at https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…s.pipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:1:4230
From previous event:
    at h.r.then (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…ipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:257:20641)
    at e.value (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…s.pipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:1:3748)
    at i (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…s.pipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:1:1924)
    at Function.<anonymous> (https://dedacteddomain/assets/plugin/org.graylog.plugins.pipelineproces…s.pipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js:1:1836)
    at r.n (https://dedacteddomain/assets/vendor.js:46:10756)
    at r.emit (https://dedacteddomain/assets/vendor.js:39:19459)
    at Function.trigger (https://dedacteddomain/assets/vendor.js:46:11633)
    at https://dedacteddomain/assets/vendor.js:46:11737
    at t.exports (https://dedacteddomain/assets/polyfill.35e28e4da7743596569a.js:1:18591)
    at y.(anonymous function) (https://dedacteddomain/assets/polyfill.35e28e4da7743596569a.js:1:25209)
    at Number.g (https://dedacteddomain/assets/polyfill.35e28e4da7743596569a.js:1:25067)
    at MessagePort.b (https://dedacteddomain/assets/polyfill.35e28e4da7743596569a.js:1:25089)
t @ FetchProvider.js:12
</pre>

## Steps to Reproduce (for bugs)
1. Create a new user without read permissions on 'decorators' (and log out)
2. Clear browser cache
3. Login as new user
4. Go to search

## Your Environment
Running 3 Graylog machines behind a loadbalancer (haproxy).

* Graylog Version: 2.2.3-1
* Operating System (server): Ubuntu 16.04 LTS

* Operating System (client): OS X El Capitan
* Browser version: Chrome 57.0.2987.133 (64-bit)

**Comment by bernd** [comment]
This should be fixed with the new search page implementation. Please open a new issue if you still see problems. Thank you!
