### ISSUE TITLE
Could not load user list

### ISSUE THREAD

**Issue by triggert** [Graylog2/graylog2-server#3701]
Unable to load the user list.

```
2017-04-11 10:51:48,067 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to [B
	at org.graylog2.security.MongoDbSession.getAttributes(MongoDbSession.java:62) ~[graylog.jar:?]
	at org.graylog2.security.MongoDbSession.getUsernameAttribute(MongoDbSession.java:92) ~[graylog.jar:?]
	at org.graylog2.rest.resources.users.UsersResource.lambda$listUsers$0(UsersResource.java:146) ~[graylog.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_65]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_65]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_65]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_65]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_65]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_65]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_65]
	at org.graylog2.rest.resources.users.UsersResource.listUsers(UsersResource.java:147) ~[graylog.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

## Expected Behavior
User listing to load.

## Current Behavior

> Could not load user list
> Loading user list failed with status: Error: cannot GET https://hostname:12900/users (500)

## Steps to Reproduce (for bugs)
1. Login to graylog using AD authentication
2. Click System/Authentication then Authentication
3. Error occurs

## Your Environment
* Graylog Version: Graylog 2.2.2+691b4b7
* Elasticsearch Version: 2.3.4
* MongoDB Version: 3.2.11
* Operating System: RHEL6.8
* Browser version: Version 57.0.2987.133 (64-bit)

**Comment by joschi** [comment]
@triggert Did you upgrade Graylog recently?

It sounds like a duplicate of #3660 (https://community.graylog.org/t/unable-to-load-user-list-after-upgrade-to-2-2-2/582).

Please clear (purge or delete) the `sessions` collection in MongoDB and see if it helps.

**Comment by triggert** [comment]
```
use graylog
db.sessions.drop()
```

That resolved it.  Thanks!

**Comment by joschi** [comment]
@triggert Thanks for the feedback!

From which Graylog version did you upgrade recently?

**Comment by triggert** [comment]
We recently upgraded from graylog-2.1.2.

**Comment by entrop92** [comment]
`Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: Unhandled exception in REST resource
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to [B
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.graylog2.security.MongoDbSession.getAttributes(MongoDbSession.java:68) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.graylog2.security.MongoDbSession.getUsernameAttribute(MongoDbSession.java:98) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.graylog2.rest.resources.users.UsersResource.lambda$listUsers$0(UsersResource.java:147) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.graylog2.rest.resources.users.UsersResource.listUsers(UsersResource.java:148) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
Mar 12 18:56:31 1.graylog.graylog.pc.odkl.ru graylog-server[3718]: at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
`

Same issue here. Happens on graylog-server-2.4.6.

Dropping the sessions on mongo helps but after a while the problem appears again.

**Comment by fadenb** [comment]
For the record: Just encountered this issue with Graylog 3.3.1.
