### ISSUE TITLE
Search Menu in Web Interface is not showing data

### ISSUE THREAD

**Issue by leomazzo** [Graylog2/graylog2-server#3702]
![Uploading Captura de Tela 2017-04-12 às 08.54.11.png…]()
When click on Search, on Web Menu Interface, i can see loading message.... and data is not showing.

## Expected Behavior
The data must be showed

## Current Behavior
The data is not showed and we can see this error message on server.log (Graylog-Server):

2017-04-12T08:34:22.317-03:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.NullPointerException: null
        at org.graylog2.indexer.searches.Searches.histogram(Searches.java:496) ~[graylog.jar:?]
        at org.graylog2.rest.resources.search.RelativeSearchResource.histogramRelative(RelativeSearchResource.java:282) ~[graylog.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

## Context
How has this issue affected you? What are you trying to accomplish? 
We cannot filter our data to search results, but we can search results directly on Elastic Search at command line:

[root@ip-172-22-3-161 elasticsearch]# curl -XGET 'http://localhost:9200/_search?size=1&pretty=true'
{
  "took" : 14,
  "timed_out" : false,
  "_shards" : {
    "total" : 4,
    "successful" : 4,
    "failed" : 0
  },
  "hits" : {
    "total" : 407669,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "graylog_0",
      "_type" : "message",
      "_id" : "d43f3cc3-1f23-11e7-aba7-02322c54de34",
      "_score" : 1.0,
      "_source" : {
        "Task" : 0,
        "Keywords" : -9223372036854775808,
        "EventType" : "WARNING",
        "Opcode" : "Info",
        "source" : "SRVSEPM.interfile.com.br",
        "hrError" : "0x80070002",
        "gl2_source_input" : "58dab936e4b077291bd1d2ab",
        "SeverityValue" : 3,
        "Version" : 0,
        "UserID" : "S-1-5-18",
        "gl2_source_node" : "a7872ac5-37f4-4a24-8415-9a51bb48f837",
        "ProcessID" : 1904,
        "timestamp" : "2017-04-12 02:00:38.000",
        "Path" : "C:\\Windows\\system32\\config\\systemprofile\\Desktop",
        "OpcodeValue" : 0,
        "SourceModuleType" : "im_msvistalog",
        "level" : 4,
        "Channel" : "Microsoft-Windows-Known Folders API Service",
        "streams" : [ "000000000000000000000001" ],
        "SourceName" : "Microsoft-Windows-KnownFolders",
        "Severity" : "WARNING",
        "FolderId" : "{B4BFCC3A-DB2C-424C-B029-7FE99A87C641}",
        "message" : "Error 0x80070002 occurred while verifying known folder {B4BFCC3A",
        "AccountType" : "User",
        "EventReceivedTime" : "2017-04-11 23:00:39",
        "SourceModuleName" : "in",
        "ProviderGuid" : "{8939299F-2315-4C5C-9B91-ABB86AA0627D}",
        "full_message" : "Error 0x80070002 occurred while verifying known folder {B4BFCC3A-DB2C-424C-B029-7FE99A87C641} with path 'C:\\Windows\\system32\\config\\systemprofile\\Desktop'.",
        "ThreadID" : 4068,
        "EventID" : 1002,
        "Domain" : "NT AUTHORITY",
        "RecordNumber" : 13388,
        "AccountName" : "SYSTEM"
      }
    } ]
  }
}

## Environment
* Graylog Version: Graylog 2.2.3+7adc951
* Elasticsearch Version: elasticsearch-2.4.4-1
* MongoDB Version:db version v3.2.12
* Operating System:CentOS Linux release 7.2.1511 (Core) 
* Browser version: Chrome last version

**Comment by leomazzo** [comment]
After create a new graylog22 cluster, everything is fine.
