### ISSUE TITLE
Beats TLS config causes stacktrace

### ISSUE THREAD

**Issue by EvertMDC** [Graylog2/graylog2-server#3744]
Hello,

I have an Beats input running without TLS. This works great.
When starting a second beats input with TLS on a different port I receive the errors below.
The certificates are self-signed with a newly created CA. If I'm not mistaken the tutorial I followed to achieve this [is here](https://jamielinux.com/docs/openssl-certificate-authority/).

## Expected Behavior
It would be nice to display a message explaining the issue in case there was a configuration error.

## Current Behavior
I am receiving this stack trace
```

2017-04-28 11:26:52,430 DEBUG: org.graylog2.plugin.inputs.transports.util.KeyUtil - Added certificate with alias /usr/share/graylog/data/config/certs/filebeatcerts/ca-chain.cert.pem_0 to trust store: [
[
  Version: V3
... (output trimmed)
]
2017-04-28 11:26:52,435 DEBUG: org.graylog2.plugin.inputs.transports.util.KeyUtil - Added certificate with alias /usr/share/graylog/data/config/certs/filebeatcerts/ca-chain.cert.pem_1 to trust store: [
[
Version: V3
... (output trimmed)
]
2017-04-28 11:26:52,435 DEBUG: org.graylog2.plugin.inputs.transports.util.KeyUtil - Client authentication certificate file: /usr/share/graylog/data/config/certs/filebeatcerts/ca-chain.cert.pem
2017-04-28 11:26:52,435 DEBUG: org.graylog2.plugin.inputs.transports.util.KeyUtil - Aliases: /usr/share/graylog/data/config/certs/filebeatcerts/ca-chain.cert.pem_1,/usr/share/graylog/data/config/certs/filebeatcerts/ca-chain.cert.pem_0
2017-04-28 11:26:52,438 WARN : org.elasticsearch.netty.channel.socket.nio.AbstractNioSelector - Failed to initialize an accepted socket.
java.io.IOException: extra data given to DerValue constructor
        at sun.security.util.DerValue.init(DerValue.java:384) ~[?:1.8.0_72-internal]
        at sun.security.util.DerValue.<init>(DerValue.java:294) ~[?:1.8.0_72-internal]
        at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:84) ~[?:1.8.0_72]
        at org.graylog2.plugin.inputs.transports.util.KeyUtil.createKeySpec(KeyUtil.java:179) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.util.KeyUtil.loadPrivateKey(KeyUtil.java:152) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.util.KeyUtil.initKeyStore(KeyUtil.java:116) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$1.createSslEngine(AbstractTcpTransport.java:205) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$1.call(AbstractTcpTransport.java:186) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$1.call(AbstractTcpTransport.java:182) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.NettyTransport$1.getPipeline(NettyTransport.java:110) ~[graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42) [graylog.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [graylog.jar:?]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

```

## Steps to Reproduce (for bugs)
Here is the input configuration.
![screen shot 2017-04-28 at 12 14 02](https://cloud.githubusercontent.com/assets/19346117/25524758/3aee72e8-2c0c-11e7-9816-ea034a472b78.png)

## Context
I am currently unable to use TLS for bi-directional authentication.

## Your Environment

* Graylog Version: Graylog 2.2.3+7adc951 on a1b13917972c
* Elasticsearch Version: docker container elasticsearch:2
* MongoDB Version: docker container mongo:2
* Operating System: docker container graylog2/server
* Browser version: N/A

I've checked the issues and #1594 came close but does not have the same message.

**Comment by SkinnerJL** [comment]
I've run into the same problem that the OP has experienced. I have a self signed CA and cert and when attempting to send logs via rsyslog using TLS I get the same problem as described above.

Version: Graylog v2.2.3+7adc951
OS: CentOS 7.3
rsyslogd 7.4.7

**Comment by joschi** [comment]
@EvertMDC @SkinnerJL I could reproduce the issue.

The problem is, that the private keys generated in the tutorial https://jamielinux.com/docs/openssl-certificate-authority/index.html are in PKCS#1 format, while Graylog expects them to be in PKCS#8.

See http://docs.graylog.org/en/2.2/pages/configuration/https.html#creating-a-self-signed-private-key-certificate for instructions how to convert a PKCS#1 or PKCS#5 private key to PKCS#8 using OpenSSL.
