### ISSUE TITLE
Error - date extractor

### ISSUE THREAD

**Issue by Vilger** [Graylog2/graylog2-server#3811]
It show with parsing logs :

`2017-05-11T15:08:58.825+02:00 DEBUG [DateConverter] Trying to parse date <11/May/2017:15:10:48 +0200> with pattern <dd/MMM/YYYY:HH:mm:ss Z> and timezone <Etc/UTC>.
2017-05-11T15:08:58.825+02:00 ERROR [Extractor] Could not apply converter [date] of extractor [69c7f1dc-f5b0-472c-9008-eecaac50437c].
java.lang.IllegalArgumentException: Invalid format: "11/May/2017:15:10:48 +0200" is malformed at "May/2017:15:10:48 +0200"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945) ~[graylog.jar:?]
	at org.joda.time.DateTime.parse(DateTime.java:160) ~[graylog.jar:?]
	at org.graylog2.inputs.converters.DateConverter.convert(DateConverter.java:59) ~[graylog.jar:?]
	at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:262) [graylog.jar:?]
	at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:249) [graylog.jar:?]
	at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:73) [graylog.jar:?]
	at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:100) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.handleMessage(ProcessBufferProcessor.java:119) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:105) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:82) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:45) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`

* Graylog Version: graylog-2.2-repository_latest.deb
* Elasticsearch Version: 2.4.5
* MongoDB Version: 2.4.10
* Operating System: Debian Jessie 
* Browser version: N/A

**Comment by Vilger** [comment]
I think it's a system local problem with locale ( was pl_PL.UTF-8 ) after change to en_US.UTF-8 problem disappeared .

**Comment by joschi** [comment]
@Vilger Yes, Graylog is currently using the system locale for parsing the month string.

**Comment by joschi** [comment]
@Vilger Thanks for reporting this!

We've added support for choosing the locale used to parse date strings per Date converter in Graylog 2.3.0.
