### ISSUE TITLE
Error with a SEARCH_RESULT_COUNT widget

### ISSUE THREAD

**Issue by Azenet** [Graylog2/graylog2-server#3841]
## Expected Behavior
A widget created with the "Add count to dashboard" button in a search result should work

## Current Behavior
The widget is never refreshed and /api/dashboards/id/widgets/wid/value replies with a 500 error and the following message: 
```json
{"message":"Unable to perform count query.\n\nrequest does not support [highlight]","details":["request does not support [highlight]"]}
```
No exception is logged.

## Steps to Reproduce
1. Search something
2. Create a widget on a dashboard by clicking on "Add count to dashboard" on the sidebar
3. Go to the dashboard
4. Widget should show "N/A" with a red exclamation triangle

## Context
I am using Graylog with a 2-node Elasticsearch cluster with Docker.
`/api/dashboards/id/widgets/wid` returns this for the widget:
```json
{"id":"ac51e5ec-6b9f-449b-963c-5b6715a4fa17","description":"500 errs","type":"SEARCH_RESULT_COUNT","config":{"timerange":{"type":"relative","range":3600},"lower_is_better":true,"trend":true,"query":"ctxt_response_code:>=500"},"cache_time":10,"creator_user_id":"admin"}
```

## Your Environment
* Graylog Version: 2.3.0-alpha.2+f24e575
* Elasticsearch Version: 5.4.0
* MongoDB Version: 3.4.4
* Operating System: Linux/Debian 8
* Browser version: Chrome 58

**Comment by Azenet** [comment]
I just got this exception. Although it was thrown while processing an alert, it seems related.
```
2017-05-17 16:41:17,609 ERROR: org.graylog2.alerts.AlertScanner - Skipping alert check that threw an exception.
org.graylog2.indexer.ElasticsearchException: Unable to perform count query.

request does not support [highlight]
        at org.graylog2.indexer.cluster.jest.JestUtils.specificException(JestUtils.java:101) ~[graylog.jar:?]
        at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:65) ~[graylog.jar:?]
        at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:70) ~[graylog.jar:?]
        at org.graylog2.indexer.searches.Searches.count(Searches.java:206) ~[graylog.jar:?]
        at org.graylog2.alerts.types.MessageCountAlertCondition.runCheck(MessageCountAlertCondition.java:178) ~[graylog.jar:?]
        at org.graylog2.alerts.types.MessageCountAlertCondition.runCheck(MessageCountAlertCondition.java:52) ~[graylog.jar:?]
        at org.graylog2.alerts.AlertScanner.checkAlertCondition(AlertScanner.java:64) ~[graylog.jar:?]
        at org.graylog2.periodical.AlertScannerThread.lambda$doRun$0(AlertScannerThread.java:63) ~[graylog.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_72-internal]
        at org.graylog2.periodical.AlertScannerThread.doRun(AlertScannerThread.java:63) [graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_72-internal]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_72-internal]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
```
