### ISSUE TITLE
Graylog 2.3 breaks output plugin compatibility

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#3851]
## Expected Behavior

Older output plugins (pre 2.3) should not break with 2.3.

## Current Behavior

Using an output plugin built with 2.2 or earlier does not work anymore and the server does not start.

```
2017-05-19 11:55:33,690 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: ZeroMQ Plugin 1.1.2 [org.graylog.plugin.zeromq.ZeroMQPluginPlugin]
2017-05-19 11:55:33,696 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Elastic Beats Input 2.3.0-alpha.3-SNAPSHOT [org.graylog.plugins.beats.BeatsInputPlugin]
2017-05-19 11:55:33,697 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Collector 2.3.0-alpha.3-SNAPSHOT [org.graylog.plugins.collector.CollectorPlugin]
2017-05-19 11:55:33,698 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Enterprise Integration Plugin 2.3.0-alpha.3-SNAPSHOT [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]
2017-05-19 11:55:33,702 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: MapWidgetPlugin 2.3.0-alpha.3-SNAPSHOT [org.graylog.plugins.map.MapWidgetPlugin]
2017-05-19 11:55:33,703 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: NetFlow Plugin 0.1.0 [org.graylog.plugins.netflow.NetFlowPlugin]
2017-05-19 11:55:33,717 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Pipeline Processor Plugin 2.3.0-alpha.3-SNAPSHOT [org.graylog.plugins.pipelineprocessor.ProcessorPlugin]
2017-05-19 11:55:33,719 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Anonymous Usage Statistics 2.3.0-alpha.3-SNAPSHOT [org.graylog.plugins.usagestatistics.UsageStatsPlugin]
2017-05-19 11:55:33,719 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Slack 2.4.0 [org.graylog2.plugins.slack.callback.SlackAlarmCallback]
2017-05-19 11:55:34,081 INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:37097,suspend=y,server=n -Djava.library.path=lib/sigar-1.6.4 -Xmx1g -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -XX:+PreserveFramePointer -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -Dfile.encoding=UTF-8
2017-05-19 11:55:34,388 INFO : org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.4.1.Final
Exception in thread "main" 2017-05-19 11:55:37,032 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): org.graylog.plugin.zeromq.outputs.ZeroMQGelfOutput has @AssistedInject constructors, but none of them match the parameters in method org.graylog2.plugin.outputs.MessageOutput$Factory.create().  Unable to create AssistedInject factory.
2017-05-19 11:55:37,033 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for org.graylog.plugin.zeromq.outputs.ZeroMQGelfOutput$Factory was bound.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) org.graylog.plugin.zeromq.outputs.ZeroMQGelfOutput has @AssistedInject constructors, but none of them match the parameters in method org.graylog2.plugin.outputs.MessageOutput$Factory.create().  Unable to create AssistedInject factory.
  while locating org.graylog.plugin.zeromq.outputs.ZeroMQGelfOutput
  at org.graylog2.plugin.outputs.MessageOutput$Factory.create(MessageOutput.java:1)

2) No implementation for org.graylog.plugin.zeromq.outputs.ZeroMQGelfOutput$Factory was bound.
  at org.graylog2.plugin.inject.Graylog2Module.installOutput(Graylog2Module.java:252) (via modules: org.graylog2.shared.bindings.PluginBindings -> org.graylog.plugin.zeromq.ZeroMQPluginModule)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34)
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379)
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:193)
	at org.graylog2.bootstrap.Main.main(Main.java:44)
Disconnected from the target VM, address: '127.0.0.1:37097', transport: 'socket'

Process finished with exit code 1
```

## Possible Solution

Revert API change in output system.

## Steps to Reproduce (for bugs)

1. Download latest [zeromq plugin](https://github.com/graylog-labs/graylog-plugin-zeromq/releases/tag/1.1.2)
2. Put plugin into plugin folder
3. Start Graylog server

## Your Environment

* Graylog Version: Graylog 2.3.0-alpha.3-SNAPSHOT 269281c93

**Comment by bernd** [comment]
Caused by https://github.com/Graylog2/graylog2-server/pull/3810
