### ISSUE TITLE
Graylog2 won't start on Windows

### ISSUE THREAD

**Issue by garethky** [Graylog2/graylog2-server#39]
I am cursed with a dearth of Linux boxen to run Graylog2 on in my organization. When trying to run the Graylog2 server on a windows box it tries to run bash presumably to get it's Process Id. It's Java, why do you need to tie it to the platform like this?

<pre>
FATAL: org.graylog2.Tools - Could not determine own PID! Cannot run program "bas
h": CreateProcess error=2, The system cannot find the file specified
java.io.IOException: Cannot run program "bash": CreateProcess error=2, The syste
m cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:460)
        at java.lang.Runtime.exec(Runtime.java:593)
        at java.lang.Runtime.exec(Runtime.java:466)
        at org.graylog2.Tools.getPID(Tools.java:57)
        at org.graylog2.Main.main(Main.java:147)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:81)
        at java.lang.ProcessImpl.start(ProcessImpl.java:30)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:453)
        ... 4 more
FATAL: org.graylog2.Main - Could not write PID file: Could not determine PID.
java.lang.Exception: Could not determine PID.
        at org.graylog2.Main.main(Main.java:149)
</pre>

**Comment by codlife** [comment]
add git bash.exe to system environmetn will be work
