### ISSUE TITLE
Input can not restart itself after extractor changes due to port being in use 

### ISSUE THREAD

**Issue by fadenb** [Graylog2/graylog2-server#3903]
## Expected Behavior
* Have a running input (in my case Beats input)
* Edit GROK extractor on this input
* On extractor change input is stopped and automatically started again

## Current Behavior
* Have a running input (in my case Beats input)
* Edit GROK extractor on this input
* On extractor change input is stopped
* Input can not be restarted due to  "java.net.BindException: Address already in use" error

## Steps to Reproduce (for bugs)

1. Fresh GL install
2. Add Beats input
3. Ensure input is started
4. Add GROK extractor
5. change grok pattern
6. input is stopped but not restarted

```
Jun 12 14:15:31 hetznix graylogctl[4970]: 2017-06-12 14:15:31,552 INFO : org.graylog2.rest.resources.system.inputs.ExtractorsResource - Updated extractor <cbb424a0-4f78-11e7-a2c4-5e193e146121> of type [grok] in input <593d5937bfc060437b083017>.
Jun 12 14:15:32 hetznix graylogctl[4970]: 2017-06-12 14:15:32,488 INFO : org.graylog2.inputs.InputStateListener - Input [Beats/593d5937bfc060437b083017] is now STOPPING
Jun 12 14:15:32 hetznix graylogctl[4970]: 2017-06-12 14:15:32,513 INFO : org.graylog2.inputs.InputStateListener - Input [Beats/593d5937bfc060437b083017] is now STOPPED
Jun 12 14:15:32 hetznix graylogctl[4970]: 2017-06-12 14:15:32,515 INFO : org.graylog2.inputs.InputStateListener - Input [Beats/593d5937bfc060437b083017] is now TERMINATED
Jun 12 14:15:32 hetznix graylogctl[4970]: 2017-06-12 14:15:32,516 INFO : org.graylog2.inputs.InputStateListener - Input [Beats/593d5937bfc060437b083017] is now STOPPING
Jun 12 14:15:32 hetznix graylogctl[4970]: 2017-06-12 14:15:32,517 INFO : org.graylog2.inputs.InputStateListener - Input [Beats/593d5937bfc060437b083017] is now STARTING
Jun 12 14:15:32 hetznix graylogctl[4970]: 2017-06-12 14:15:32,518 INFO : org.graylog2.inputs.InputStateListener - Input [Beats/593d5937bfc060437b083017] is now STOPPED
Jun 12 14:15:32 hetznix graylogctl[4970]: 2017-06-12 14:15:32,518 INFO : org.graylog2.inputs.InputStateListener - Input [Beats/593d5937bfc060437b083017] is now TERMINATED
Jun 12 14:15:32 hetznix graylogctl[4970]: 2017-06-12 14:15:32,571 WARN : org.graylog2.plugin.inputs.transports.NettyTransport - receiveBufferSize (SO_RCVBUF) for input BeatsInput{title=Global Beats, type=org.graylog.plugins.beats.BeatsInput, nodeId=null} should be 1048576 but is 212992.
Jun 12 14:15:32 hetznix graylogctl[4970]: 2017-06-12 14:15:32,574 INFO : org.graylog2.inputs.InputStateListener - Input [Beats/593d5937bfc060437b083017] is now RUNNING
Jun 12 14:16:16 hetznix graylogctl[4970]: 2017-06-12 14:16:16,046 INFO : org.graylog2.inputs.InputStateListener - Input [Beats/593d5937bfc060437b083017] is now STARTING
Jun 12 14:16:16 hetznix graylogctl[4970]: 2017-06-12 14:16:16,055 ERROR: org.graylog2.shared.inputs.InputLauncher - The [org.graylog.plugins.beats.BeatsInput] input with ID <593d5937bfc060437b083017> misfired. Reason: Address already in use.
Jun 12 14:16:16 hetznix graylogctl[4970]: org.graylog2.plugin.inputs.MisfireException: org.graylog2.plugin.inputs.MisfireException: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:5044
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:156) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84) [graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Jun 12 14:16:16 hetznix graylogctl[4970]: Caused by: org.graylog2.plugin.inputs.MisfireException: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:5044
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.graylog2.plugin.inputs.transports.NettyTransport.launch(NettyTransport.java:155) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:153) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         ... 7 more
Jun 12 14:16:16 hetznix graylogctl[4970]: Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:5044
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.graylog2.plugin.inputs.transports.NettyTransport.launch(NettyTransport.java:141) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:153) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         ... 7 more
Jun 12 14:16:16 hetznix graylogctl[4970]: Caused by: java.net.BindException: Address already in use
Jun 12 14:16:16 hetznix graylogctl[4970]:         at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_131]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_131]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_131]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_131]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_131]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[graylog.jar:?]
Jun 12 14:16:16 hetznix graylogctl[4970]:         ... 3 more
Jun 12 14:16:16 hetznix graylogctl[4970]: 2017-06-12 14:16:16,063 INFO : org.graylog2.inputs.InputStateListener - Input [Beats/593d5937bfc060437b083017] is now FAILED

```

## Your Environment

* Graylog Version: 2.3.0-alpha.3+c795033
* Elasticsearch Version: 5.4.0
* MongoDB Version: 3.2.9
* Operating System: NixOS 17.09

**Comment by joschi** [comment]
@fadenb @Bastidias I couldn't reproduce this in a local setup but I found an issue, which could have potentially caused this behavior, i. e. emitting the event to restart the input twice in short succession.

**Comment by fadenb** [comment]
If you happen to have a tarball with a build containing this change I can give it a quick test (in my setup I trigger this almost every time I update a grok rule)

**Comment by joschi** [comment]
@fadenb You can try this one: http://graylog-snapshots.s3.amazonaws.com/graylog-2.3.0-alpha.4-SNAPSHOT-20170613154343-graylog-server-tarball.tar.gz

But beware, it's a bare graylog2-server build without plugins. You could use the JAR file from that tar ball and your existing plugin JARs, though.

**Comment by fadenb** [comment]
Sorry for the late reply, the tarball you provided worked fine for me. I was unable to trigger bug.
Just in the process of updating to 2.3.0-beta.1 and will verify whether it is still working
