### ISSUE TITLE
Internal Server Error java.net.URISyntaxException 

### ISSUE THREAD

**Issue by ak1t4** [Graylog2/graylog2-server#4004]
## Description
Grizzly httpserver is not handling well url encoded chars

## Current Behavior
Internal Server Error handling illegal url encoded chars

## Steps to Reproduce (for bugs)
1. Go to  http://127.0.0.1:9000/%5C
2. You see internal error output

OUTPUT EXAMPLE:

```
Internal Server Error

Reason

java.net.URISyntaxException:

 Illegal character in path at index 22: http://127.0.0.1:9000/\

Stacktrace

java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 22: http://127.0.0.1:9000/\
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:491)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:366)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in path at index 22: http://127.0.0.1:9000/\
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:489)
	... 6 more
```

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version: 
* Operating System: OSX
* Browser version: Safari:10.1.1 (12603.2.4) / Chrome: 59.0.3071.115 (Build oficial) (64 bits) / Firefox: 54.0.1 (64-bit)

**Comment by danotorrey** [comment]
I believe this has been fixed since it was reported. I am now seeing an appropriate Page Not Found error. Feel free to open if there are any concerns with this.

![image](https://user-images.githubusercontent.com/3423655/67048504-f5a0f480-f0f9-11e9-98dc-f7a7fb54f331.png)
