### ISSUE TITLE
Unable to call http://graylog2-server-0:9000/api/system/jobs on node <f77115cb-3266-4ee3-91b1-589154b964cd>, java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by lnshi** [Graylog2/graylog2-server#4025]
My setup with docker stack deploy `graylog2-server-0` service part:
```
graylog2-server-0:
  image: graylog2/server:2.3.0-rc.2-2
  hostname: graylog2-server-0
  environment:
    GRAYLOG_PASSWORD_SECRET: l4dIKl7ocXp1hw2IZdBOCGFwLjdKDsILYxjlGRxlkJvjYVY3sAaSarTZ05gyo4hCuAWXuydO3LGIo3F5WIOWr5gKyeH6F0Gp

    GRAYLOG_ROOT_USERNAME: leonard
    GRAYLOG_ROOT_PASSWORD_SHA2: c775e7b757ede630cd0aa1113bd102661ab38829ca52a6422ab782862f268646
    GRAYLOG_ROOT_EMAIL: leonard.shi@xxx.com
    GRAYLOG_ROOT_TIMEZONE: UTC

    GRAYLOG_WEB_ENABLE_CORS: 'true'
    GRAYLOG_WEB_LISTEN_URI: http://0.0.0.0:9000/
    GRAYLOG_WEB_ENDPOINT_URI: http://${GRAYLOG2_SERVER_HOSTNAME}:64999/api/

    GRAYLOG_REST_ENABLE_CORS: 'true'
    GRAYLOG_REST_LISTEN_URI: http://0.0.0.0:9000/api/
    GRAYLOG_REST_TRANSPORT_URI: http://graylog2-server-0:9000/api/

    GRAYLOG_MONGODB_URI: mongodb://x.x.x.x:27017,x.x.x.x:27017/microservices_graylog
    
    GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch-server-0:9200,http://elasticsearch-server-1:9200,http://elasticsearch-server-2:9200
    GRAYLOG_ELASTICSEARCH_MAX_TOTAL_CONNECTIONS: 9
    GRAYLOG_ELASTICSEARCH_MAX_TOTAL_CONNECTIONS_PER_ROUTE: 3
    GRAYLOG_ELASTICSEARCH_MAX_RETRIES: 100
    GRAYLOG_ELASTICSEARCH_DISCOVERY_ENABLED: 'true'
  networks:
    - default
  ports:
    - mode: host
      target: 9000
      published: 64999
  deploy:
    mode: replicated
    replicas: 1
    resources:
      limits:
        cpus: '0.5'
    placement:
      constraints:
        - node.hostname == ${GRAYLOG2_SERVER_HOSTNAME}
    restart_policy:
      condition: any
```

Then after login keep getting:
```
2017-07-21 03:52:58,999 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Unable to call http://graylog2-server-0:9000/api/system/jobs on node <f77115cb-3266-4ee3-91b1-589154b964cd>
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230) ~[graylog.jar:?]
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285) ~[graylog.jar:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241) ~[graylog.jar:?]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345) ~[graylog.jar:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217) ~[graylog.jar:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211) ~[graylog.jar:?]
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) ~[graylog.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
	at org.graylog2.rest.RemoteInterfaceProvider.lambda$get$0(RemoteInterfaceProvider.java:59) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[graylog.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[graylog.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:69) ~[graylog.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[graylog.jar:?]
	at org.graylog2.shared.rest.resources.ProxiedResource.lambda$getForAllNodes$0(ProxiedResource.java:76) ~[graylog.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_72-internal]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_72-internal]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[?:1.8.0_72-internal]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_72-internal]
	at okio.Okio$2.read(Okio.java:139) ~[graylog.jar:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[graylog.jar:?]
	... 28 more
```

Then I bash into the `graylog2-server-0` docker container:
```
docker run -it --rm \
  --network=gate_services_stack \
  --link 4d3e0a45caa9 \
  --env SERVICE_IGNORE=true \
  graylog2/server:2.3.0-rc.2-2 bash
```
Then call the same API with curl:
```
curl -u leonard:xxxxxxxxxx -H 'Accept: application/json' -X GET 'http://graylog2-server-0:9000/api/system/jobs?pretty=true'
```

Successfully got the response:
```
{
  "jobs" : [ ]
}
```

**Comment by lnshi** [comment]
- I tried in `GRAYLOG_REST_TRANSPORT_URI` use the physical machine's hostname which the container is running on, then use docker
```
extra_hosts:
    - '${GRAYLOG2_SERVER_CORRD_PHY_MACHINE_HOSTNAME}:${GRAYLOG2_SERVER_CORRD_PHY_MACHINE_IP}'
```
to tell the container what is the ip for his hostname, but still keep getting exactly same errors.

- Also tried to just directly use the IP address, still keep getting this errors.

- Then tried to use our well known commercial domain name, still keep getting this errors.

- But in all of the above cases, if I go into the container, i can successfully call the exactly same API with curl....

So I guess definitely this is a bug, @joschi @jalogisch @edmundoa, pls put some time to investigate.

Any details needed just @ me.

**Comment by jalogisch** [comment]
@lnshi you should re-read http://docs.graylog.org/en/2.2/pages/configuration/web_interface.html

The configured `GRAYLOG_REST_TRANSPORT_URI` need to be reachable by Graylog and your Browser. Additional `GRAYLOG_WEB_ENDPOINT_URI` contain the string `api` does not make sense in your posted configuration.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by lnshi** [comment]
First, the commercial domain i used can be accessed from anywhere of this world.

Second, if remove the `api/` in the `GRAYLOG_WEB_ENDPOINT_URI`, then when i sign in from the browser, the rest api get redirected to `http://hostname:9000/system/sessions`, which all return `404 not found`

Third, can u guys simplify do some very simple tests then come here telling ppl this not a bug, not even don't bother to take a look just close the issue!!!

I saw in the issues list, bunches of ppl are complaining this issue, all just get simply get closed, i don't understand the logic here, few issues in Github issues list means few bugs?

**Comment by joschi** [comment]
> few issues in Github issues list means few bugs?

@lnshi No, but misconfiguration isn't a bug. @jalogisch already listed the channels we're using for generic user support. Please post your questions to those.

**Comment by gardner** [comment]
The docs refer to `rest_transport_uri` but they never describe what it is. How can I submit a PR to docs?

**Comment by joschi** [comment]
@gardner You can help to improve the README of the [graylog-docker](https://github.com/Graylog2/graylog-docker) repository or the [documentation](https://github.com/Graylog2/documentation) repository.
