### ISSUE TITLE
REST API NPE when using fields parameter and JSON

### ISSUE THREAD

**Issue by tholu** [Graylog2/graylog2-server#4068]
When trying to use https://github.com/graylog-labs/cli-dashboard I encountered the following exception:

```
graylog_1        | 2017-08-09 07:19:09,217 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
graylog_1        | java.lang.NullPointerException: null
graylog_1        |      at org.graylog2.indexer.searches.Searches.lambda$search$3(Searches.java:272) ~[graylog.jar:?]
graylog_1        |      at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_72-internal]
graylog_1        |      at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_72-internal]
graylog_1        |      at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_72-internal]
graylog_1        |      at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_72-internal]
graylog_1        |      at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_72-internal]
graylog_1        |      at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_72-internal]
graylog_1        |      at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_72-internal]
graylog_1        |      at org.graylog2.indexer.searches.Searches.search(Searches.java:273) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.rest.resources.search.RelativeSearchResource.searchRelative(RelativeSearchResource.java:111) ~[graylog.jar:?]
```

Further investigation suggests it happens when calling the JSON API on `GET /search/universal/relative`, see Steps to Reproduce.

## Expected Behavior
API returns data and 200 status code.

## Current Behavior
API Error with 500 status code.

## Possible Solution
Fix NPE.

## Steps to Reproduce (for bugs)
1. Use Graylog REST API Brower
2. Use JSON version of `GET /search/universal/relative`
3. Enter `*` in `query`, `86400` in `range`, `message` in `fields`
4. Click "Try it out!"
5. Response:
```
{
  "type": "ApiError",
  "message": ""
}
```

## Context
Cannot use `cli-dashboard` tool.

## Your Environment

* Graylog Version: Docker graylog2/server:2.3.0-1,
* Elasticsearch Version: Docker elasticsearch:2
* MongoDB Version: Docker mongo:3
* Operating System: Docker 17.05.0-ce on Debian 8

**Comment by tholu** [comment]
Note: `cli-dashboard` version 1.0.0 was used, the API call seems to be fixed/different in version 1.1.1 there (works).
