### ISSUE TITLE
'Show Received Messages' loading forever

### ISSUE THREAD

**Issue by myaspm** [Graylog2/graylog2-server#4081]
Installed latest Graylog version (Docker) with Elasticsearch 5.5 (not Docker) but it can't show received messages even though it shows that how many messages are coming and active connections etc.  When i click 'Show received messages' it loads forever and in browser console there's an error. Logs are pretty clean but there is nothing about Elasticsearch but if i bring down the Elasticsearch cluster and restart Graylog i see errors about Elasticsearch so i think it is safe to assume that configurations are correct. The browser console error : 

```
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.31a2373cd5652763947c.js:44 Unhandled rejection TypeError: Cannot read property 'end' of undefined
```

Full Trace : 

```
Unhandled rejection TypeError: Cannot read property 'end' of undefined
    at t._determineSearchDuration (http://X:9000/assets/53.8e41d69eb32b36020c26.js:1:3330)
    at t._determineHistogramResolution (http://X:9000/assets/53.8e41d69eb32b36020c26.js:1:3527)
    at promise.H.search.then.e.additional.e.additional.status.t.setState.error (http://X:9000/assets/53.8e41d69eb32b36020c26.js:1:2515)
From previous event:
    at o.p [as _captureStackTrace] (http://X:9000/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.31a2373cd5652763947c.js:44:10310)
    at o._then (http://X:9000/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.31a2373cd5652763947c.js:44:41761)
    at o.then (http://X:9000/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.31a2373cd5652763947c.js:44:40117)
    at s.list (http://X:9000/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.31a2373cd5652763947c.js:104:1120695)
    at o.n (http://X:9000/assets/vendor.39412008ebba2755b8a2.js:28:195783)
    at o.emit (http://X:9000/assets/vendor.39412008ebba2755b8a2.js:23:30345)
    at Function.trigger (http://X:9000/assets/vendor.39412008ebba2755b8a2.js:28:196658)
    at http://X:9000/assets/vendor.39412008ebba2755b8a2.js:28:196762
    at t.exports (http://X:9000/assets/polyfill.8e41d69eb32b36020c26.js:1:18867)
    at y.(anonymous function) (http://X:9000/assets/polyfill.8e41d69eb32b36020c26.js:1:25291)
    at Number.d (http://X:9000/assets/polyfill.8e41d69eb32b36020c26.js:1:25149)
    at MessagePort.g (http://X:9000/assets/polyfill.8e41d69eb32b36020c26.js:1:25171)
```

I tried restarting Elasticsearch and Graylog, cleaning journal files, reinstalling both several times, checking timezones.

## Expected Behavior

Show received messages button lets me see received messages instead of loading forever.

## Current Behavior

'Show received messages' loads forever. No logs about it.

## Steps to Reproduce (for bugs)

1. Install Graylog (Docker) 2.3.0-1.
2. Use the following docker run command
```
docker run -v /data/graylog/journal:/usr/share/graylog/data/journal   \
-v /data/graylog/mongo:/data/db  -p 9000:9000  -p 12201:12201 -p 12202:12202 \
-e GRAYLOG_WEB_ENDPOINT_URI=http://graylog:9000/api    \
-e GRAYLOG_ELASTICSEARCH_HOSTS=http://es:9200   \
-e GRAYLOG_MONGODB_URI=mongodb://mongo:27018/graylog \
--name=graylog   -d graylog2/server:latest
```
3. Launch an input, send a text message and click 'show received messages' in input page.

## Your Environment

* Graylog Version: 2.3.0-1
* Elasticsearch Version: 5.5
* MongoDB Version: 3
* Operating System: Ubuntu 16.04
* Browser version: Chrome

**Comment by myaspm** [comment]
Issue is resolved after reinstalling Elasticsearch with exact same configuration as we had before. So you may wanna close this but it'd be better if atleast i could get some directions about why this happened and how to prevent it in the future.

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
