### ISSUE TITLE
CorruptIndexException each weeks

### ISSUE THREAD

**Issue by vmichalak** [Graylog2/graylog2-server#4091]
Hi all,
Since we have updated Graylog to 2.2.3 we have a problem. Each week the ElasticSearch server turn to red and the log says 

```
[2017-08-11 11:28:54,943][ERROR][index.engine             ] [Impulse] [graylog_2][0] failed to merge
org.apache.lucene.index.CorruptIndexException: codec footer mismatch (file truncated?): actual footer=0 vs expected footer=-1071082520 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/var/lib/elasticsearch/graylog/nodes/0/indices/graylog_2/0/index/_2wa4.cfs") [slice=_2wa4_Lucene50_0.pos]))
	at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:418)
	at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:330)
	at org.apache.lucene.codecs.CodecUtil.checksumEntireFile(CodecUtil.java:451)
	at org.apache.lucene.codecs.lucene50.Lucene50PostingsReader.checkIntegrity(Lucene50PostingsReader.java:1302)
	at org.apache.lucene.codecs.blocktree.BlockTreeTermsReader.checkIntegrity(BlockTreeTermsReader.java:336)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader.checkIntegrity(PerFieldPostingsFormat.java:317)
	at org.apache.lucene.codecs.FieldsConsumer.merge(FieldsConsumer.java:96)
	at org.apache.lucene.index.SegmentMerger.mergeTerms(SegmentMerger.java:193)
	at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:95)
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4086)
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3666)
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:588)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:94)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)
[2017-08-11 11:28:55,126][WARN ][index.engine             ] [Impulse] [graylog_2][0] failed engine [merge failed]
org.apache.lucene.index.MergePolicy$MergeException: org.apache.lucene.index.CorruptIndexException: codec footer mismatch (file truncated?): actual footer=0 vs expected footer=-1071082520 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/var/lib/elasticsearch/graylog/nodes/0/indices/graylog_2/0/index/_2wa4.cfs") [slice=_2wa4_Lucene50_0.pos]))
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler$1.doRun(InternalEngine.java:1237)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.lucene.index.CorruptIndexException: codec footer mismatch (file truncated?): actual footer=0 vs expected footer=-1071082520 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/var/lib/elasticsearch/graylog/nodes/0/indices/graylog_2/0/index/_2wa4.cfs") [slice=_2wa4_Lucene50_0.pos]))
	at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:418)
	at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:330)
	at org.apache.lucene.codecs.CodecUtil.checksumEntireFile(CodecUtil.java:451)
	at org.apache.lucene.codecs.lucene50.Lucene50PostingsReader.checkIntegrity(Lucene50PostingsReader.java:1302)
	at org.apache.lucene.codecs.blocktree.BlockTreeTermsReader.checkIntegrity(BlockTreeTermsReader.java:336)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader.checkIntegrity(PerFieldPostingsFormat.java:317)
	at org.apache.lucene.codecs.FieldsConsumer.merge(FieldsConsumer.java:96)
	at org.apache.lucene.index.SegmentMerger.mergeTerms(SegmentMerger.java:193)
	at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:95)
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4086)
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3666)
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:588)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:94)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)
[2017-08-11 11:28:55,138][DEBUG][action.bulk              ] [Impulse] failed to execute [BulkShardRequest to [graylog_2] containing [5] requests] on [[graylog_2][0]]
[graylog_2][[graylog_2][0]] EngineClosedException[CurrentState[CLOSED] Closed]; nested: MergeException[org.apache.lucene.index.CorruptIndexException: codec footer mismatch (file truncated?): actual footer=0 vs expected footer=-1071082520 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/var/lib/elasticsearch/graylog/nodes/0/indices/graylog_2/0/index/_2wa4.cfs") [slice=_2wa4_Lucene50_0.pos]))]; nested: CorruptIndexException[codec footer mismatch (file truncated?): actual footer=0 vs expected footer=-1071082520 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/var/lib/elasticsearch/graylog/nodes/0/indices/graylog_2/0/index/_2wa4.cfs") [slice=_2wa4_Lucene50_0.pos]))];
	at org.elasticsearch.index.engine.Engine.ensureOpen(Engine.java:329)
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:448)
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:605)
	at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:236)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:657)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:287)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.lucene.index.MergePolicy$MergeException: org.apache.lucene.index.CorruptIndexException: codec footer mismatch (file truncated?): actual footer=0 vs expected footer=-1071082520 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/var/lib/elasticsearch/graylog/nodes/0/indices/graylog_2/0/index/_2wa4.cfs") [slice=_2wa4_Lucene50_0.pos]))
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler$1.doRun(InternalEngine.java:1237)
	... 4 more
```

Each week we delete the index in question but it does not solve the problem. We have tried several techniques found on the internet but no one seems work. That's why we come back to you to found a solution.

Thank you in advance.

## Environment

* Graylog Version: 2.2.3-1 (only 1 node in this cluster)
* Elasticsearch Version: 2.4.5
* MongoDB Version: 2.4.10-5
* Operating System: Debian 9
* Browser version: Google Chrome on Windows

**Comment by jalogisch** [comment]
@vmichalak What did you already tried that you found at the net?

What is your rotation and retention strategy? Did you use curator or any other tool to make some kind of work with the elasticsearch index?

**Comment by vmichalak** [comment]
After some experimentations, we found the solution : the VHDX file of the virtual machine seems to be corrupted. After erased it and recreated it, everything seems good.

**Comment by joschi** [comment]
@vmichalak Thanks for your feedback!

We'll close this issue now.
