### ISSUE TITLE
Gelf AMQP stops Consuming

### ISSUE THREAD

**Issue by haricharan123** [Graylog2/graylog2-server#4100]
## Expected Behavior
Gelf AMQP with RabbitMq should consume messages without exception.

## Current Behavior
Graylog running with GELF AMQP input with RabbitMQ (AMQP 0-9-1), degrades from consuming to stop consuming.

on checking the logs: I find this

```
2017-08-12T10:00:33.356+02:00 ERROR [AmqpConsumer] Could not re-connect to AMQP broker.
java.net.NoRouteToHostException: No route to host (Host unreachable)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_112]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_112]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_112]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_112]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_112]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_112]
        at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:50) ~[graylog.jar:?]
        at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:60) ~[graylog.jar:?]
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:99) ~[graylog.jar:?]
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:900) ~[graylog.jar:?]
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:859) ~[graylog.jar:?]
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:817) ~[graylog.jar:?]
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:954) ~[graylog.jar:?]
        at org.graylog2.inputs.transports.AmqpConsumer.connect(AmqpConsumer.java:176) ~[graylog.jar:?]
        at org.graylog2.inputs.transports.AmqpConsumer$3.shutdownCompleted(AmqpConsumer.java:206) [graylog.jar:?]
        at com.rabbitmq.client.impl.ShutdownNotifierComponent.notifyListeners(ShutdownNotifierComponent.java:77) [graylog.jar:?]
        at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:682) [graylog.jar:?]
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:577) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Further Restarting the nodes fixes the problem, however it degrades after few hours.**

## Your Environment

* Graylog Version:  Graylog 2.2.3+7adc951
* Elasticsearch Version: 2.3.5-1
* MongoDB Version: 3.2.15-1.el7
* Operating System: Centos 7

**Comment by joschi** [comment]
@haricharan123 Please provide more details about your RabbitMQ setup such as number of nodes, configuration of the AMQP input, configuration of RabbitMQ, network setup, etc.

**Comment by joschi** [comment]
@haricharan123 Is DNS stable, i. e. does `qa-mq.spcph.local` always resolve to the same IP address and is this IP address correctly routed?

**Comment by haricharan123** [comment]
Can confim, while log file was being thrashed with "**ERROR [AmqpConsumer] Could not re-connect to AMQP broker.**"

`ping qa-mq.spcph.local ` did work as expected with no packets being lost. Restarted `graylog-server`
no more ERROR  messages.

**Comment by jalogisch** [comment]
I did only see that error in my log files with a flaky connection to the AMQP hosts.
That could include high load on AMQP or Graylog that the connections can't be established. Currently I'm not able to reproduce this.

**Comment by jalogisch** [comment]
the error from Graylog - no route to host - and that we are not able to reproduce this indicate that this problem might be more in your infrastructure. 

If you could provide more information @haricharan123 that we are able to reproduce this error you can reopen this issue.

**Comment by daviskirk** [comment]
Perhaps related: When restarting the rabbitmq broker graylog stops consuming the logs for me as well.

However, the message in the logs is different:

```
ERROR: org.graylog2.inputs.transports.AmqpConsumer - Error while trying to process AMQP message
com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - unknown delivery tag 1, class-id=60, method-id=80)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:198) ~[graylog.jar:?]
	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:312) ~[graylog.jar:?]
	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:306) ~[graylog.jar:?]
	at com.rabbitmq.client.impl.ChannelN.basicAck(ChannelN.java:1165) ~[graylog.jar:?]
	at com.rabbitmq.client.impl.recovery.RecoveryAwareChannelN.basicAck(RecoveryAwareChannelN.java:89) ~[graylog.jar:?]
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicAck(AutorecoveringChannel.java:436) ~[graylog.jar:?]
	at org.graylog2.inputs.transports.AmqpConsumer$2.handleDelivery(AmqpConsumer.java:133) [graylog.jar:?]
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) [graylog.jar:?]
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
```
