### ISSUE TITLE
Temporary key for inputs gets deleted without reason

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#4115]
In random events my /tmp/keyutil_*.crt keys which are created from Inputs getting deleted even when i set the sticky bit.

I trace this now since over a half year and no external events are triggerd that are touching the crts.
I cant find any reason why they get deleted, so I am sorry that i cant provide any more Info on that.

## Expected Behavior
crts souldnt be deleted or if there is no crt set in the gui and no key is found, create a new one.

## Current Behavior
crt or key gets lost, Input stops working.

## Possible Solution
if there is no key, and the option is empty, create  a new one without the need to restart the input.

## Steps to Reproduce (for bugs)
sry i dont know why the disappear.

## Context
crts geting lost, input creates this error and stops working: (and its very noisy!)
```
2017-08-30T15:04:51.636+02:00 WARN  [AbstractNioSelector] Failed to initialize an accepted socket.
java.nio.file.NoSuchFileException: /tmp/keyutil_192.168.100.20:null_650514679431100319.crt
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_141]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_141]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_141]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_141]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_141]
        at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_141]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_141]
        at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_141]
        at org.graylog2.plugin.inputs.transports.util.KeyUtil.initKeyStore(KeyUtil.java:115) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$1.createSslEngine(AbstractTcpTransport.java:205) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$1.call(AbstractTcpTransport.java:186) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.AbstractTcpTransport$1.call(AbstractTcpTransport.java:182) ~[graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.NettyTransport$1.getPipeline(NettyTransport.java:110) ~[graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [graylog.jar:?]
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42) [graylog.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [graylog.jar:?]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```
## Your Environment
Graylog 2.3.0+81f8228 on syslog.xyz.local (Oracle Corporation 1.8.0_141 on Linux 3.10.0-514.26.2.el7.x86_64)

**Comment by gruselglatz** [comment]
Ok, i understand this. But i dont get it to run with own certs. I tried it like its described in the docu, but i always get this:
javax.net.ssl.SSLException: Received fatal alert: unknown_ca

I dont know anymore what i should do, i imported everything and event the CA is in the Java trust store.
I can verify the Cert against the Truststore, but graylog cant. The same Cert is Working for the Web-Gui, so I dont get it, why they make problems on inputs.

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
