### ISSUE TITLE
failed to execute bulk item. No new messages are accepted in beats input.

### ISSUE THREAD

**Issue by vti-uplata** [Graylog2/graylog2-server#4130]
## Current Behavior
I've configured beats input so the new log-files  on test servers will be parsed. As i've discovered later -
 some of these files consisted of debug data from applications and some strings were too large for graylog to reap (images in base-64 and so on..).
Now i have 780 failed indexes like this (http://blah-blah/...system/indices/failures)

2 hours ago | graylog_2 | 086308b2-930f-11e7-ab88-023571bf098d | java.lang.IllegalArgumentException: Document contains at least one immense term in field="ApacheDate" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: '[48, 45, 57, 93, 42, 41, 41, 36, 34, 44, 34, 105, 110, 112, 117, 116, 116, 101, 120, 116, 34, 58, 34, 92, 92, 117, 48, 52, 49, 100]...', original message: bytes can be at most 32766 in length; got 84148
-- | -- | -- | --

Process buffer is full - 65536 messages in process buffer, 100.00% utilized.

67,182 unprocessed messages are currently in the journal, in 2 segments.

/var/log/graylog/elasticsearch/current 
```
2017-09-06_13:02:09.81120 java.lang.IllegalArgumentException: Document contains at least one immense term in field="ApacheDate" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[48, 45, 57, 93, 42, 41, 41, 36, 34, 44, 34, 105, 110, 112, 117, 116, 116, 101, 120, 116, 34, 58, 34, 92, 92, 117, 48, 52, 49, 100]...', original message: bytes can be at most 32766 in length; got 84148
2017-09-06_13:02:09.81658       at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:692)
2017-09-06_13:02:09.81659       at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:365)
2017-09-06_13:02:09.82040       at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:321)
2017-09-06_13:02:09.82125       at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234)
2017-09-06_13:02:09.82173       at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
2017-09-06_13:02:09.82355       at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1477)
2017-09-06_13:02:09.82409       at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1256)
2017-09-06_13:02:09.82461       at org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:527)
2017-09-06_13:02:09.82528       at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:454)
2017-09-06_13:02:09.82720       at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:605)
2017-09-06_13:02:09.83003       at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836)
2017-09-06_13:02:09.83060       at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:236)
2017-09-06_13:02:09.83151       at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
2017-09-06_13:02:09.83154       at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
2017-09-06_13:02:09.83357       at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
2017-09-06_13:02:09.83666       at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:657)
2017-09-06_13:02:09.83752       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
2017-09-06_13:02:09.83794       at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:287)
2017-09-06_13:02:09.83825       at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
2017-09-06_13:02:09.83921       at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
2017-09-06_13:02:09.84185       at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
2017-09-06_13:02:09.84214       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
2017-09-06_13:02:09.84248       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-09-06_13:02:09.84353       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-09-06_13:02:09.84397       at java.lang.Thread.run(Thread.java:745)
2017-09-06_13:02:09.84481 Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 84148
2017-09-06_13:02:09.84522       at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:284)
2017-09-06_13:02:09.84666       at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:150)
2017-09-06_13:02:09.84708       at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:682)
2017-09-06_13:02:09.84769       ... 24 more
```
No new messages are accepted from any source since this happened. 

## Possible Solution
Delete failed indexes so the queue will be freed.

## Your Environment

* Graylog Version: 2.2.2+691b4b7
* Elasticsearch Version: 2.4.2
* MongoDB Version: 3.4.1
* Operating System: Ubuntu 14.04.1 LTS x86_64
* Browser version: Google Chrome 61.0.3163.79

[1724.txt](https://github.com/Graylog2/graylog2-server/files/1281898/1724.txt)

**Comment by joschi** [comment]
@vti-uplata Try stopping Graylog, deleting the journal files, and starting Graylog again.

See http://docs.graylog.org/en/2.3/pages/configuration/file_location.html#omnibus-graylog for the location of the journal files.

**Comment by vti-uplata** [comment]
So i've stopped Graylog, moved journal files to my home dir and started graylog again. Waited for 10 min and saw that it didn't help -  Process buffer was empty and there was a huge queue in Utilization (49,655,208). So I've stopped graylog again, moved journal from my home dir to /var/opt/..., started graylog and deleted an extractor that was assigned to beats input.

Now everything seems ok and messages are appending.

Thank you for your time and concern.
