### ISSUE TITLE
graylog deflector is used before elasticsearch report back success

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#4167]
## Expected Behavior
If Graylogs retention policy cycle the active index it should cycle after the new index is created and available to write.

## Current Behavior
After investigation in https://github.com/Graylog2/graylog2-server/issues/4166 I personal think that the deflector alias is removed from the last index before elasticsearch report success for the new created index.
If that handling would be as written in possible solution I think the following entries would not happen in the Log.

```
{
    "timestamp": "2017-09-17T13:32:19.000Z",
    "letter_id": "a11dbb91-9bac-11e7-9aa5-782bcb5376e0",
    "message": "{\"type\":\"unavailable_shards_exception\",\"reason\":\"[graylog_5728][0] Not enough active copies to meet write consistency of [QUORUM] (have 1, needed 2). Timeout: [1m], request: [BulkShardRequest to [graylog_5728] containing [113] requests]\"}",
    "index": "graylog_5728",
    "type": "message"
  }, {
    "timestamp": "2017-09-17T13:32:19.000Z",
    "letter_id": "a11dbb92-9bac-11e7-9aa5-782bcb5376e0",
    "message": "{\"type\":\"unavailable_shards_exception\",\"reason\":\"[graylog_5728][0] Not enough active copies to meet write consistency of [QUORUM] (have 1, needed 2). Timeout: [1m], request: [BulkShardRequest to [graylog_5728] containing [113] requests]\"}",
    "index": "graylog_5728",
    "type": "message"
  },
```

This will only happen if Elasticsearch is slow for a reason, not on any setup.

## Possible Solution
The *deflector_cycle* should be done in the following way:

1. Create the new index
2. Check if Index is available
3. Cycle deflector if the check was successful
4. Make optimization and calculation for the old index (if configured)

## Your Environment

* Graylog Version: 2.3.1

**Comment by tmedford** [comment]
Any expected timeline for a fix?

**Comment by u2g-tg** [comment]
I'm also using Graylog Server (Docker build) 2.3.2-2 and seeing this issue #4355 when I try to manually rotate the default index. I created the required alias by hand, but then get this error out of the graylog server.

I'm also using ES6.0 which may have changed its API since v5.

```2017-12-07 16:13:44,850 ERROR: org.graylog2.periodical.IndexRotationThread - Couldn't point deflector to a new index
org.graylog2.indexer.ElasticsearchException: Couldn't collect indices for alias graylog_deflector
 {"error":"Incorrect HTTP method for uri [/_all/_aliases] and method [GET], allowed: [PUT]","status":405}
	at org.graylog2.indexer.cluster.jest.JestUtils.specificException(JestUtils.java:91) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:58) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:63) ~[graylog.jar:?]
	at org.graylog2.indexer.indices.Indices.aliasTarget(Indices.java:326) ~[graylog.jar:?]
	at org.graylog2.indexer.MongoIndexSet.getActiveWriteIndex(MongoIndexSet.java:204) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.checkAndRepair(IndexRotationThread.java:144) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:76) ~[graylog.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_72-internal]
	at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_72-internal]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_72-internal]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]```

**Comment by joschi** [comment]
@u2g-tg Graylog currently doesn't support Elasticsearch 6.x.

See http://docs.graylog.org/en/2.3/pages/configuration/elasticsearch.html#elasticsearch-versions for details.

**Comment by u2g-tg** [comment]
Ah yes thanks, I realised this after reporting, happliy working with ES5.6 now :-)

**Comment by trevex** [comment]
I ran into the same issue several times already. The first few times I simply deleted the indices and restarted graylog (running in kubernetes). Recently more and more production data got funnelled into graylog, therefore I was looking for another solution. 

Another solution without dataloss is:
1. create a new index in graylog
2. shutdown graylog
3. remove the new index (e.g. graylog_8)
4. rename graylog_deflector to fit the name of the new index
5. add an alias graylog_deflector

Hopefully this is not an issue anymore in 3.X

**Comment by joschi** [comment]
@jalogisch @trevex Please try to reproduce the issue with automatic index creation in Elasticsearch **disabled**: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-index_.html#index-creation

I suspect that a Graylog slave node tries to index documents into the write-active index alias *before* it was created by the Graylog master node.

**Comment by madchap** [comment]
I experience this behavior with the docker-compose instructions from the graylog site.

**Comment by jam49** [comment]
See the same issue. 
I think it can be reproduced with the rest api in GL 2.5.1
In script, use the rest api to create an index, then the enxt command, create a stream on that index and an active input. the index nearly always becomes a _defector and not a true deflector, and graylog complains.

**Comment by commandline-be** [comment]
this issue has not grown old or gone away, it is terrible and time consuming with no real fix approach

**Comment by bernd** [comment]
Much code has changed in that area, and we haven't heard similar reports recently. I am closing the ticket.
