### ISSUE TITLE
Orphaned Lookup table data adapters

### ISSUE THREAD

**Issue by jtkkex** [Graylog2/graylog2-server#4176]
## Expected Behavior
when deleting a lookup table data adapter from the UI, it should be removed.

## Current Behavior
Sometimes (I could not reproduce it, but it happened to me and another person, see [https://community.graylog.org/t/csv-lookup-table-delete-fails/2561](url)

I created a CSV data adapter, with Graylog 2.3.1. I accidentally misspelled the file name and saved the data adapter setup. This resulted in error in UI (the triangle), due to missing file. I edited the correct filename in the UI, and the error vanished from the UI. But the java exceptions keep occurring in the log file. So I decided to delete the whole lookup data adapter. The adapter vanished from the UI, but - the java exceptions keep occurring on the log file.

I have a setup of 5 Graylog nodes, and don’t see any problems with their connectivity with each other.
```
2017-09-25T15:28:18.778+03:00 ERROR [CSVFileDataAdapter] Couldn't check data adapter <malware-patrol-domain> CSV file /graylog/threatintel/feed_mwp_domain.csv for updates: java.nio.file.NoSuchFileException /graylog/threatintel/feed_mwp_domain.csv
2017-09-25T15:28:45.743+03:00 ERROR [LookupDataAdapter] Couldn't refresh data adapter <malware-domain/59c0f8fd91ad3a0432d9fd30/@5236f163>
java.lang.NullPointerException: null
        at org.graylog2.lookup.adapters.CSVFileDataAdapter.doRefresh(CSVFileDataAdapter.java:102) ~[graylog.jar:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.refresh(LookupDataAdapter.java:89) ~[graylog.jar:?]
        at org.graylog2.lookup.LookupDataAdapterRefreshService.lambda$schedule$0(LookupDataAdapterRefreshService.java:142) ~[graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

After reboot, the null pointer exceptions vanished.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.3.1
* Elasticsearch Version: 5.6.2
* MongoDB Version: 3.4
* Operating System: CentOS7
* Browser version: Chrome

**Comment by bernd** [comment]
@jtkkex Can you please show us the complete server log file? More context makes it easier to debug this. Thank you!

**Comment by jtkkex** [comment]
I cannot provide the whole log, but here is the log from one of the servers from the time the adapter was first made and then changed.  All nodes in the cluster have similar lines in their log files.

```
2017-09-19T14:01:18.759+03:00 INFO  [LookupTableService] Data Adapter malware-patrol-domain/59c0f8fd91ad3a0432d9fd30 [@70351b70] STARTING
2017-09-19T14:01:18.760+03:00 ERROR [LookupDataAdapter] Couldn't start data adapter <malware-patrol-domain/59c0f8fd91ad3a0432d9fd30/@70351b70>
java.nio.file.NoSuchFileException: /graylog/threatintel/feed_mwp_domain.csv
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_141]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_141]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_141]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_141]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_141]
        at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_141]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_141]
        at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_141]
        at org.graylog2.lookup.adapters.CSVFileDataAdapter.parseCSVFile(CSVFileDataAdapter.java:120) ~[graylog.jar:?]
        at org.graylog2.lookup.adapters.CSVFileDataAdapter.doStart(CSVFileDataAdapter.java:91) ~[graylog.jar:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.startUp(LookupDataAdapter.java:59) [graylog.jar:?]
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62) [graylog.jar:?]
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
2017-09-19T14:01:18.776+03:00 INFO  [LookupTableService] Data Adapter malware-patrol-domain/59c0f8fd91ad3a0432d9fd30 [@70351b70] RUNNING
2017-09-19T14:01:18.777+03:00 INFO  [LookupDataAdapterRefreshService] Adding job for <malware-patrol-domain/59c0f8fd91ad3a0432d9fd30/@70351b70> [interval=60000ms]
2017-09-19T14:02:18.778+03:00 ERROR [CSVFileDataAdapter] Couldn't check data adapter <malware-patrol-domain> CSV file /graylog/threatintel/feed_mwp_domain.csv for updates: java.nio.file.NoSuchFileException /graylog/thre\
atintel/feed_mwp_domain.csv
2017-09-19T14:02:45.737+03:00 INFO  [LookupTableService] Data Adapter malware-domain/59c0f8fd91ad3a0432d9fd30 [@5236f163] STARTING
2017-09-19T14:02:45.738+03:00 ERROR [CSVFileDataAdapter] Couldn't parse CSV file /graylog/threatintel/feed_mwd_domain.csv (settings separator=<,> quotechar=<#> key_column=<URL> value_column=<URL>)
java.lang.IllegalStateException: Couldn't detect column number for key or value - check CSV file format
        at org.graylog2.lookup.adapters.CSVFileDataAdapter.parseCSVFile(CSVFileDataAdapter.java:152) [graylog.jar:?]
        at org.graylog2.lookup.adapters.CSVFileDataAdapter.doStart(CSVFileDataAdapter.java:91) [graylog.jar:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.startUp(LookupDataAdapter.java:59) [graylog.jar:?]
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62) [graylog.jar:?]
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
2017-09-19T14:02:45.741+03:00 INFO  [LookupTableService] Data Adapter malware-domain/59c0f8fd91ad3a0432d9fd30 [@5236f163] RUNNING
2017-09-19T14:02:45.741+03:00 INFO  [LookupDataAdapterRefreshService] Adding job for <malware-domain/59c0f8fd91ad3a0432d9fd30/@5236f163> [interval=60000ms]
2017-09-19T14:03:18.778+03:00 ERROR [CSVFileDataAdapter] Couldn't check data adapter <malware-patrol-domain> CSV file /graylog/threatintel/feed_mwp_domain.csv for updates: java.nio.file.NoSuchFileException /graylog/thre\
atintel/feed_mwp_domain.csv
2017-09-19T14:03:31.734+03:00 INFO  [LookupTableService] Data Adapter malware-domain/59c0f8fd91ad3a0432d9fd30 [@2dd814ca] STARTING
2017-09-19T14:03:31.775+03:00 INFO  [LookupTableService] Data Adapter malware-domain/59c0f8fd91ad3a0432d9fd30 [@2dd814ca] RUNNING
2017-09-19T14:03:31.775+03:00 INFO  [LookupDataAdapterRefreshService] Adding job for <malware-domain/59c0f8fd91ad3a0432d9fd30/@2dd814ca> [interval=60000ms]
2017-09-19T14:03:45.742+03:00 ERROR [CSVFileDataAdapter] Couldn't parse CSV file /graylog/threatintel/feed_mwd_domain.csv (settings separator=<,> quotechar=<#> key_column=<URL> value_column=<URL>)
java.lang.IllegalStateException: Couldn't detect column number for key or value - check CSV file format
        at org.graylog2.lookup.adapters.CSVFileDataAdapter.parseCSVFile(CSVFileDataAdapter.java:152) ~[graylog.jar:?]
        at org.graylog2.lookup.adapters.CSVFileDataAdapter.doRefresh(CSVFileDataAdapter.java:109) ~[graylog.jar:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.refresh(LookupDataAdapter.java:89) ~[graylog.jar:?]
        at org.graylog2.lookup.LookupDataAdapterRefreshService.lambda$schedule$0(LookupDataAdapterRefreshService.java:142) ~[graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
2017-09-19T14:04:18.778+03:00 ERROR [CSVFileDataAdapter] Couldn't check data adapter <malware-patrol-domain> CSV file /graylog/threatintel/feed_mwp_domain.csv for updates: java.nio.file.NoSuchFileException /graylog/thre\
atintel/feed_mwp_domain.csv
2017-09-19T14:04:45.742+03:00 ERROR [LookupDataAdapter] Couldn't refresh data adapter <malware-domain/59c0f8fd91ad3a0432d9fd30/@5236f163>
java.lang.NullPointerException: null
        at org.graylog2.lookup.adapters.CSVFileDataAdapter.doRefresh(CSVFileDataAdapter.java:102) ~[graylog.jar:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.refresh(LookupDataAdapter.java:89) ~[graylog.jar:?]
        at org.graylog2.lookup.LookupDataAdapterRefreshService.lambda$schedule$0(LookupDataAdapterRefreshService.java:142) ~[graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
2017-09-19T14:05:18.778+03:00 ERROR [CSVFileDataAdapter] Couldn't check data adapter <malware-patrol-domain> CSV file /graylog/threatintel/feed_mwp_domain.csv for updates: java.nio.file.NoSuchFileException /graylog/thre\
atintel/feed_mwp_domain.csv
2017-09-19T14:05:45.742+03:00 ERROR [LookupDataAdapter] Couldn't refresh data adapter <malware-domain/59c0f8fd91ad3a0432d9fd30/@5236f163>
java.lang.NullPointerException: null
        at org.graylog2.lookup.adapters.CSVFileDataAdapter.doRefresh(CSVFileDataAdapter.java:102) ~[graylog.jar:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.refresh(LookupDataAdapter.java:89) ~[graylog.jar:?]
        at org.graylog2.lookup.LookupDataAdapterRefreshService.lambda$schedule$0(LookupDataAdapterRefreshService.java:142) ~[graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]

```
