### ISSUE TITLE
Graylog2 0.20.0 rc1-1 SMTP AUTH LOGIN failed

### ISSUE THREAD

**Issue by Niok** [Graylog2/graylog2-server#419]
Hi,
I have faced with SMTP authentication issue (i have MS exch 2007 server).

In the console logs i have:
```
ERROR: org.graylog2.alerts.AlertSender - Could not send alert email.
org.apache.commons.mail.EmailException: Sending the email to the following server failed : SERVER:25
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410)
        at org.apache.commons.mail.Email.send(Email.java:1437)
        at org.graylog2.alerts.AlertSender.sendEmail(AlertSender.java:105)
        at org.graylog2.alerts.AlertSender.sendEmails(AlertSender.java:75)
        at org.graylog2.periodical.AlertScannerThread.run(AlertScannerThread.java:77)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
Caused by: javax.mail.AuthenticationFailedException: 535 5.7.3 Authentication unsuccessful

        at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:826)
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:761)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:685)
        at javax.mail.Service.connect(Service.java:317)
        at javax.mail.Service.connect(Service.java:176)
        at javax.mail.Service.connect(Service.java:125)
        at javax.mail.Transport.send0(Transport.java:194)
        at javax.mail.Transport.send(Transport.java:124)
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
        ... 12 more

```
GRAYLOG2 configuration:
```
#Email transport
transport_email_enabled = true
transport_email_hostname = SERVER
transport_email_port = 25
transport_email_use_auth = true
transport_email_use_tls = false
transport_email_use_ssl = false
transport_email_auth_username = "DOMAIN\\USERNAME"
transport_email_auth_password = "PASSWORD"
transport_email_subject_prefix = [syslog]
transport_email_from_email = syslog@DOMAIN
```

I have tried to encode username and password using this commands:
    perl -MMIME::Base64 -e 'print encode_base64("DOMAIN\\USERNAME");'
    perl -MMIME::Base64 -e 'print encode_base64("PASSWORD");'
and connect to the server using telnet:

```
#telnet SERVER 25
Trying SERVER_IP...
Connected to SERVER.
Escape character is '^]'.
220 SERVER Microsoft ESMTP MAIL Service ready
EHLO GRAYLOG2
250-SERVER Hello [GRAYLOG2_IP]
250-SIZE 31457280
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM LOGIN
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250 XRDST
AUTH LOGIN
334 ENCODED
ENCODED_USERNAME
334 ENCODED
ENCODED_PASSWORD
235 2.7.0 Authentication successful
```

in the tcpdump i see that ENCODED_USERNAME/PASSWORD in the telnet and GRAYLOG2 different.

could you please suggest something?
i'm not able to sent email without authentication.

Thank you.

**Comment by bernd** [comment]
Closing this. Please re-open if you still see the problem in Graylog 1.1. Thank you!
