### ISSUE TITLE
org.bson.BsonSerializationException: Document size of 105771598 is larger than maximum of 16793600.

### ISSUE THREAD

**Issue by ichasco** [Graylog2/graylog2-server#4231]
## Expected Behavior
It has to collect logs and then show

## Current Behavior
Logs are collected well because I see the index increasing but they are not showed in graylog. And it doesn't matter what to change that it doesn't works

## Possible Solution
I couldn't find it

## Steps to Reproduce (for bugs)
It is aleatory

## Your Environment

* Graylog Version: 2.3.1
* Elasticsearch Version:5.6
* MongoDB Version:3.2
* Operating System:RHEL 7
* Browser version: Firefox

**Comment by joschi** [comment]
@ichasco Please post the complete logs of your Graylog node.

**Comment by ichasco** [comment]
2017-10-11T10:33:49.762+02:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
org.bson.BsonSerializationException: Document size of 105771598 is larger than maximum of 16793600.
        at org.bson.BsonBinaryWriter.backpatchSize(BsonBinaryWriter.java:376) ~[graylog.jar:?]
        at org.bson.BsonBinaryWriter.doWriteEndArray(BsonBinaryWriter.java:143) ~[graylog.jar:?]
        at org.bson.AbstractBsonWriter.writeEndArray(AbstractBsonWriter.java:347) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.encodeIterable(DBObjectCodec.java:273) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:200) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.encodeMap(DBObjectCodec.java:222) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:198) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:130) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:61) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29) ~[graylog.jar:?]
        at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.writeValue(BsonDocumentCodec.java:136) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:115) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:41) ~[graylog.jar:?]
        at com.mongodb.connection.RequestMessage.addDocument(RequestMessage.java:253) ~[graylog.jar:?]
        at com.mongodb.connection.RequestMessage.addDocument(RequestMessage.java:205) ~[graylog.jar:?]
        at com.mongodb.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:75) ~[graylog.jar:?]
        at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160) ~[graylog.jar:?]
        at com.mongodb.connection.CommandProtocol.sendMessage(CommandProtocol.java:186) ~[graylog.jar:?]
        at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:111) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:176) ~[graylog.jar:?]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216) ~[graylog.jar:?]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:153) ~[graylog.jar:?]
        at com.mongodb.operation.FindAndReplaceOperation$1.call(FindAndReplaceOperation.java:335) ~[graylog.jar:?]
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:422) ~[graylog.jar:?]
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413) ~[graylog.jar:?]
        at com.mongodb.operation.FindAndReplaceOperation.execute(FindAndReplaceOperation.java:331) ~[graylog.jar:?]
        at com.mongodb.Mongo.execute(Mongo.java:845) ~[graylog.jar:?]
        at com.mongodb.Mongo$2.execute(Mongo.java:828) ~[graylog.jar:?]
        at com.mongodb.DBCollection.findAndModify(DBCollection.java:1928) ~[graylog.jar:?]
        at com.mongodb.DBCollection.findAndModify(DBCollection.java:1792) ~[graylog.jar:?]
        at com.mongodb.DBCollection.findAndModify(DBCollection.java:1761) ~[graylog.jar:?]
        at com.mongodb.DBCollection.findAndModify(DBCollection.java:1708) ~[graylog.jar:?]
        at org.mongojack.JacksonDBCollection.findAndModify(JacksonDBCollection.java:847) ~[graylog.jar:?]
        at org.graylog.plugins.collector.collectors.CollectorServiceImpl.save(CollectorServiceImpl.java:74) ~[?:?]
        at org.graylog.plugins.collector.collectors.rest.CollectorResource.register(CollectorResource.java:146) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:8          1) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[g          raylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[          graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatch          erProvider.java:160) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~          [graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by joschi** [comment]
@ichasco This looks like the HTTP request for registering the Graylog Sidecar Collector of one instance is quite large.

Please post the *complete* configuration file of your Graylog Sidecar Collectors.

**Comment by ichasco** [comment]
Hi,
you were right. It was one collector that didn't connect with the server I don't know why. Maybe because in the log path were a lot of files and it couldn't save the conf in the mongo.

Thank you

**Comment by Grokon** [comment]
I have this issue too. I collect log with collector-sidecar and on that server has error: 
`"[UpdateRegistration] Bad response from Graylog server: 500 Internal Server Error"`
in graylog error:
```
"ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
org.bson.BsonSerializationException: Document size of 87555722 is larger than maximum of 16793600.
"
```

I parse  /var/log and have folder with many little files (>50k) and I need parse it too
