### ISSUE TITLE
Graylog works with self-signed cert/key, not with trusted cert/key. 

### ISSUE THREAD

**Issue by mdebord1** [Graylog2/graylog2-server#4352]
I have a fully working Graylog instance which is comprised of 3 docker containers: One for graylog, one for elasticsearch, and one for mongo. 

Everything works fine, but I'm trying to swap my self-signed certs to fully signed certs. I have a wildcard (*.mybusinessname.com) cert from Comodo ready to go that's used on other web servers without issue. 

## Expected Behavior
Graylog should start after swapping out the certs

## Current Behavior
Graylog attempts to start, but ends up with this error, then attempts to restart. 
```2017-11-14 17:30:19,885 ERROR: com.google.common.util.concurrent.ServiceManager - Service JerseyService [FAILED] has failed in the STARTING state.
2017-11-14 17:30:19,885 ERROR: com.google.common.util.concurrent.ServiceManager - Service JerseyService [FAILED] has failed in the STARTING state.
java.security.cert.CertificateException: No certificates found in file: /usr/share/graylog/cert.pem
	at org.graylog2.shared.security.tls.PemReader.readCertificates(PemReader.java:71) ~[graylog.jar:?]
	at org.graylog2.shared.security.tls.PemKeyStore.buildKeyStore(PemKeyStore.java:116) ~[graylog.jar:?]
	at org.graylog2.shared.initializers.JerseyService.buildSslEngineConfigurator(JerseyService.java:387) ~[graylog.jar:?]
	at org.graylog2.shared.initializers.JerseyService.startUpApi(JerseyService.java:208) ~[graylog.jar:?]
	at org.graylog2.shared.initializers.JerseyService.startUp(JerseyService.java:141) ~[graylog.jar:?]
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62) [graylog.jar:?]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

...


2017-11-14 17:30:19,936 ERROR: org.graylog2.bootstrap.ServerBootstrap - Graylog startup failed. Exiting. Exception was:
java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {FAILED=[JerseyService [FAILED]]}
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:742) ~[graylog.jar:?]
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:555) ~[graylog.jar:?]
	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:304) ~[graylog.jar:?]
	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:149) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:209) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]
```

## Steps to Reproduce (for bugs)
I have taken the .crt and .key provided by Comodo and replaced the self signed certs with these trusted new certs. 

I have also attempted to convert the Comodo provided key to the pkcs8 format as defined in the Graylog docs.  `openssl pkcs8 -in server.key -topk8 -nocrypt -out pkcs8-plain.pem` 

The certs are in PEM, as they are readable with a text editor, and they work with other webservers I have on this domain. 

## Your Environment

 * Docker Compose File - As mentioned this works perfectly fine with the self-signed certs. When I swap out the certs to the trusted certs, doesn't work, get above error. 

```version: '2'
services:
  mongodb:
    image: mongo:3
    volumes:
      - /dockerdata/volumes/mongo3/data/db:/data/db
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    volumes:
      - /dockerdata/volumes/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: unless-stopped
  graylog:
    image: graylog/graylog:2.3.2-1
    volumes:
      - /dockerdata/volumes/graylog/usr/share/graylog:/usr/share/graylog
      - /dockerdata/volumes/graylog/etc/ssl/certs/java/cacerts:/etc/ssl/certs/java/cacerts
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=<removed>
      # Password: admin
      - GRAYLOG_WEB_ENDPOINT_URI=https://graylog.mycompany.com:9000/api/
      - GRAYLOG_REST_ENDPOINT_URI=https://graylog.mycompany.com:9000/api/
      - GRAYLOG_REST_ENABLE_TLS=true
      - GRAYLOG_REST_TLS_CERT_FILE=/usr/share/graylog/cert.pem
      - GRAYLOG_REST_TLS_KEY_FILE=/usr/share/graylog/pkcs8-plain.pem
      - GRAYLOG_WEB_ENABLE_TLS=true
      - GRAYLOG_WEB_TLS_CERT_FILE=/usr/share/graylog/cert.pem
      - GRAYLOG_WEB_TLS_KEY_FILE=/usr/share/graylog/pkcs8-plain.pem
      - GRAYLOG_ROOT_PASSWORD_SHA2=<removed>
      - GRAYLOG_REST_TRANSPORT_URI=https://graylog.mycompany.com:9000/api/
    restart: unless-stopped
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp```

**Comment by mikkolehtisalo** [comment]
Did you convert also your certificate, and not just the private key to PKCS8?

**Comment by mdebord1** [comment]
Ok I have this working.

**This is ugly, as I ended up having to use create a .pfx and use that instead of the .crt and .key** 
If there is a way to do this without first converting to pfx please let me know 


```openssl pkcs12 -export -in server.crt -inkey server.key -out server.pfx

openssl pkcs12 -in server.pfx -nokeys -out graylog-certificate.pem

openssl pkcs8 -in server.key -topk8 -nocrypt -out pkcs8-plain.pem
```

After that was done I had a pkcs8-plan.pem and a graylog-certificate.pem that I applied to graylog and it worked loading the web interface. 

The web interface was loading, but my Input listener wouldn't start in Graylog. So that was resolved by importing the signed cert to the java keystore. 

```keytool -import -noprompt -trustcacerts -alias graylog-trusted -file /path/to/graylog-certificate.pem -keystore /path/to/javakeystore/cacerts -storepass changeit```

Would be nice if this stuff was documented regarding signed certs - did I miss it somewhere?

**Comment by mikkolehtisalo** [comment]
http://docs.graylog.org/en/2.3/pages/configuration/https.html?highlight=certificate
