### ISSUE TITLE
Build failed2.3.2

### ISSUE THREAD

**Issue by wlyu** [Graylog2/graylog2-server#4373]
```text
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\graylog2-server-2.3.2\\graylog2-web-interface\\node\\node.exe',
1 verbose cli   'D:\\graylog2-server-2.3.2\\graylog2-web-interface\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.0.3
3 info using node@v6.9.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle graylog-web-interface@2.3.2~prebuild: graylog-web-interface@2.3.2
6 silly lifecycle graylog-web-interface@2.3.2~prebuild: no script for prebuild, continuing
7 info lifecycle graylog-web-interface@2.3.2~build: graylog-web-interface@2.3.2
8 verbose lifecycle graylog-web-interface@2.3.2~build: unsafe-perm in lifecycle true
9 verbose lifecycle graylog-web-interface@2.3.2~build: PATH: D:\graylog2-server-2.3.2\graylog2-web-interface\node\node_modules\npm\bin\node-gyp-bin;D:\graylog2-server-2.3.2\graylog2-web-interface\node_modules\.bin;D:\graylog2-server-2.3.2\graylog2-web-interface\node;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;D:\soft\Java\jdk1.8.0_144\bin;D:\soft\Java\jdk1.8.0_144\jre\bin;D:\soft;D:\soft\Git\cmd;D:\soft\apache-maven-3.5.0\bin;D:\soft\TortoiseSVN\bin;D:\soft\adt-bundle-windows-x86_64-20140702\sdk\platform-tools;D:\soft\adt-bundle-windows-x86_64-20140702\sdk\tools;;D:\aspectj1.8xxxx\bin;D:\soft\gradle-3.3\bin;D:\soft\Python27\;D:\soft\Python27\Scripts\;D:\soft\zookeeper-3.4.8\bin;;
10 verbose lifecycle graylog-web-interface@2.3.2~build: CWD: D:\graylog2-server-2.3.2\graylog2-web-interface
11 silly lifecycle graylog-web-interface@2.3.2~build: Args: [ '/d /s /c',
11 silly lifecycle   'disable_plugins=true webpack --config webpack.bundled.js' ]
12 silly lifecycle graylog-web-interface@2.3.2~build: Returned: code: 1  signal: null
13 info lifecycle graylog-web-interface@2.3.2~build: Failed to exec build script
14 verbose stack Error: graylog-web-interface@2.3.2 build: `disable_plugins=true webpack --config webpack.bundled.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\graylog2-server-2.3.2\graylog2-web-interface\node\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\graylog2-server-2.3.2\graylog2-web-interface\node\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid graylog-web-interface@2.3.2
16 verbose cwd D:\graylog2-server-2.3.2\graylog2-web-interface
17 error Windows_NT 6.1.7601
18 error argv "D:\\graylog2-server-2.3.2\\graylog2-web-interface\\node\\node.exe" "D:\\graylog2-server-2.3.2\\graylog2-web-interface\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.9.2
20 error npm  v4.0.3
21 error code ELIFECYCLE
22 error graylog-web-interface@2.3.2 build: `disable_plugins=true webpack --config webpack.bundled.js`
22 error Exit status 1
23 error Failed at the graylog-web-interface@2.3.2 build script 'disable_plugins=true webpack --config webpack.bundled.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the graylog-web-interface package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     disable_plugins=true webpack --config webpack.bundled.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs graylog-web-interface
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls graylog-web-interface
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by joschi** [comment]
@wlyu Building Graylog on Windows is currently not supported (and we will take no effort to make it work).

Additionally, please consider posting your questions to the Graylog community forums.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
