### ISSUE TITLE
Upgrade to graylog-server-2.4.0-6.beta.4.noarch generates "Invalid configuration" due to file perm.

### ISSUE THREAD

**Issue by jekelundh** [Graylog2/graylog2-server#4427]
Upgrade to graylog-server-2.4.0-6.beta.4.noarch (from beta.3) generates "Invalid configuration" due to file permissions.

Log:
com.github.joschi.jadconfig.ValidationException: Node ID file at path /etc/graylog/server/node-id isn't writable. Please specify the correct path or change the permissions
        at org.graylog2.Configuration$NodeIdFileValidator.validate(Configuration.java:372) ~[graylog.jar:?]
        at org.graylog2.Configuration$NodeIdFileValidator.validate(Configuration.java:345) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.validateParameter(JadConfig.java:215) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:148) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.process(JadConfig.java:99) ~[graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.processConfiguration(CmdLineTool.java:351) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.readConfiguration(CmdLineTool.java:344) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:177) [graylog.jar:?]
        at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]

## Possible Solution
Fix:
**#chown graylog /etc/graylog/server/node-id**

## Steps to Reproduce (for bugs)

1. "service graylog-server restart" fails after upgrade
2.
3.
4.

## Your Environment
Multnode GL

* Graylog Version:  graylog-server-2.4.0-6.beta.4.noarch
* Elasticsearch Version: elasticsearch-5.6.4-1.noarch
* MongoDB Version: mongodb-org-3.2.17-1.el7.x86_64
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Browser version: any

**Comment by bernd** [comment]
@jekelundh Thank you for the report. This regression has been introduced in #4417 and will be fixed in the next beta/rc release.
