### ISSUE TITLE
Unexpected exception "ClosedSelectorException"

### ISSUE THREAD

**Issue by rphlwnk** [Graylog2/graylog2-server#4460]
## Current Behavior

In the Graylog log the following Warning is shown up, i cant find any coherences between tasks in the webinterface and the error message.

2018-01-04T10:50:13.545+01:00 WARN  [DefaultExceptionMonitor] Unexpected exception.
java.nio.channels.ClosedSelectorException: null
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source) ~[?:1.8.0_151]
        at sun.nio.ch.SelectorImpl.select(Unknown Source) ~[?:1.8.0_151]
        at org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:98) ~[graylog.jar:?]
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1075) [graylog.jar:?]
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

Also one index looks like to be cleaned up again and again:
2018-01-05T09:56:28.278+01:00 INFO  [IndexRangesCleanupPeriodical] Removing index range information for unavailable indices: [innnovaphone_0]

Here are some snippets from my logfile: https://pastebin.com/hgQ75GUa

## Steps to Reproduce (for bugs)

None, i found it in the logs.

## Your Environment

* Graylog Version: 2.4.0
* Pipeline Processor plugin version: 2.4.0
* Elasticsearch Version: 5.6.5
* MongoDB Version: 3.6.0
* Operating System: CentOS 7.4

**Comment by bernd** [comment]
We haven't been able to reproduce this, and we also didn't see similar error reports recently. I am closing the issue.
