### ISSUE TITLE
RemoteTransportException... IllegalArgumentException[Expected numeric type on field [...], but got [string]]

### ISSUE THREAD

**Issue by tachtler** [Graylog2/graylog2-server#4487]
## Expected Behavior
**No Exception should occur**

## Current Behavior

Example Exception:
```
Jan 17 14:53:52 vmgraylog elasticsearch[985]: [2018-01-17 14:53:52,518][DEBUG][action.search            ] [Bob] All shards failed for phase: [query_fetch]
Jan 17 14:53:52 vmgraylog elasticsearch[985]: RemoteTransportException[[Bob][10.7.0.110:9300][indices:data/read/search[phase/query+fetch]]]; nested: IllegalArgumentException[Expected numeric type on field [Source_IPv4], but got [string]];
Jan 17 14:53:52 vmgraylog elasticsearch[985]: Caused by: java.lang.IllegalArgumentException: Expected numeric type on field [Source_IPv4], but got [string]
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.support.AggregationContext.numericField(AggregationContext.java:161)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.support.AggregationContext.originalValuesSource(AggregationContext.java:145)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.support.AggregationContext.valuesSource(AggregationContext.java:85)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:60)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:102)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.AggregatorFactories.createSubAggregators(AggregatorFactories.java:76)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.AggregatorBase.<init>(AggregatorBase.java:69)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.<init>(BucketsAggregator.java:48)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.bucket.histogram.HistogramAggregator.<init>(HistogramAggregator.java:66)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.bucket.histogram.HistogramAggregator$Factory.doCreateInternal(HistogramAggregator.java:204)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.bucket.histogram.HistogramAggregator$Factory.doCreateInternal(HistogramAggregator.java:147)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:64)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:102)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:87)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:85)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:111)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:372)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:480)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jan 17 14:53:52 vmgraylog elasticsearch[985]: at java.lang.Thread.run(Thread.java:748)
```

## Possible Solution
BugFix **or** advice, how to configure right, if it is a configuration mistake of mine?

## Steps to Reproduce (for bugs)
1. Created a new Extractor from field message (IPTABLES messages)
```
Extractor configuration
Extractor type:       Regular expression
Source field:         message
Regular expression:   ^.*SRC=([^\s]+)
Condition:            Always try to extract
Store as field:       Source_IPv4
Extraction strategy:  Copy
Extractor title:      Source IPv4
Add converter:        [NONE !!!]
```
2. Create some graph using Source_IPv4 with
```
Widget ID:     e9b3fc5e-706f-4128-aaf3-4c59c02b0881
Dashboard ID:  bc4f2fb6c7df8a24bbf51538
Interval:      minute
Timerange:     { "type": "relative", "range": 3600 }
Query: source: vmgraylog AND application_name: kernel AND facility: kernel
```
OR
```
Widget ID:     88fcd21c-85ba-4351-a0e6-f08daf5850c2
Dashboard ID:  bc4f2fb6c7df8a24bbf51538
Interval:      minute
Timerange:     { "type": "relative", "range": 3600 }
Lower is better: true
Trend:         true
Query: source: vmgraylog AND application_name: kernel AND facility: kernel
```
3. Watch the dashboard
4. Watch the ```/var/log/messages```

## Context

With the extractor, I generate a field as **string** value of an IPv4-address. While I configure a "Dahsboard" to show some "graphs". While opening the "Dahsboard" the exceptions will be logged in ```/var/log/message```

## Your Environment
(Oracle Corporation 1.8.0_151 on Linux 3.10.0-693.11.6.el7.x86_64)

* Graylog Version: ```Graylog 2.4.0+2115a42```
* Elasticsearch Version:
```
{
  "name" : "Bob",
  "cluster_name" : "graylog",
  "cluster_uuid" : "...",
  "version" : {
    "number" : "2.4.6",
    "build_hash" : "...",
    "build_timestamp" : "2017-07-18T12:17:44Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
```
* MongoDB Version: ```mongodb (EPEL) 2.6.12 Release 4.el7```
* Operating System: ```CentOS Linux release 7.4.1708 (Core)```
* Browser version: ```Firefox ESR 52.5.1 from CentOS Linux release 7.4.1708 (Core)```

**Comment by joschi** [comment]
@tachtler The "Source_IPv4" field contained numeric data before you've added the extractor.

Either revert it to that or rotate your active write index (System/Indices/Index Set/Maintenance in the Graylog web interface) and create a custom index mapping (see http://docs.graylog.org/en/2.4/pages/configuration/elasticsearch.html#custom-index-mappings).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by tachtler** [comment]
Hi joschi,

thank you, for your advice!

Klaus.

**Comment by tachtler** [comment]
Hi,

last question - the exception occurs **ONLY** while I'm creating the following widget:
```
Widget ID:
    87ae55f3-9308-4cf5-a06b-231e94edbeca
Dashboard ID:
    bc4f2fb6c7df8a24bbf51538
Valuetype:
    count
Renderer:
    line
Interpolation:
    linear
Timerange:
    { "type": "relative", "range": 3600 }
RangeType:
    relative
Field:
    Source_IPv4
Query:
    source: vmgraylog AND application_name: kernel AND facility: kernel
Interval:
    minute
Relative:
    3600
```

Thank you!
Klaus.

**Comment by joschi** [comment]
@tachtler Depending on the type of widget, it might expect a numeric value in "Source_IPv4" (which it was before your changes).

**Comment by tachtler** [comment]
Hi joschi,

I **SOLVED** it, using the timestamp field as calculation base, and NOT the Source_IPv4.

Thank you!
Klaus.
