### ISSUE TITLE
update Graylog 2.2.3 -> 2.4.0 failed (OVA-based appliance)

### ISSUE THREAD

**Issue by Thomas-1985** [Graylog2/graylog2-server#4490]
Hi

I tried an upgrade from our Graylog appliance 2.3.2 -> 2.4.0 but the update failed and left a non-working state.

## Expected Behavior
it should have worked

## Current Behavior
the VM is broken and had to be restored

## Possible Solution
don't know

## Steps to Reproduce (for bugs)
1. used these update commands http://docs.graylog.org/en/2.4/pages/configuration/graylog_ctl.html#upgrade-graylog-omnibus
```text
graylog-ctl reconfigure failed
...
 * execute[/opt/graylog/embedded/bin/graylog-ctl start graylog-server] action run
    - execute /opt/graylog/embedded/bin/graylog-ctl start graylog-server
  * ruby_block[add node to server list] action run

    ================================================================================
    Error executing action `run` on resource 'ruby_block[add node to server list]'
    ================================================================================

    Errno::ECONNREFUSED
    -------------------
    Connection refused - connect(2) for "127.0.0.1" port 4001

    Cookbook Trace:
    ---------------
    /opt/graylog/embedded/cookbooks/graylog/libraries/registry.rb:17:in `set_master'
    /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:88:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb

     86: ruby_block "add node to server list" do
     87:   block do
     88:     $registry.set_master
     89:     $registry.add_gl_server(node['ipaddress'])
     90:     $registry.add_es_node(node['ipaddress'])
     91:   end
     92:   retries 15
     93: end

    Compiled Resource:
    ------------------
    # Declared in /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:86:in `from_file'

    ruby_block("add node to server list") do
      action [:run]
      retries 15
      retry_delay 2
      default_guard_interpreter :default
      block_name "add node to server list"
      declared_type :ruby_block
      cookbook_name :graylog
      recipe_name "graylog-server"
      block #<Proc:0x000000054027e8@/opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:87>
    end

Recipe: graylog::elasticsearch
  * service[elasticsearch] action restart
    - restart service service[elasticsearch]
Recipe: graylog::graylog-server
  * service[graylog-server] action restart
    - restart service service[graylog-server]

Running handlers:
[2018-01-17T17:22:00+01:00] ERROR: Running exception handlers
Running handlers complete
[2018-01-17T17:22:00+01:00] ERROR: Exception handlers complete
Chef Client failed. 17 resources updated in 01 minutes 55 seconds
[2018-01-17T17:22:00+01:00] FATAL: Stacktrace dumped to /opt/graylog/embedded/cookbooks/cache/chef-stacktrace.out
[2018-01-17T17:22:00+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-01-17T17:22:00+01:00] ERROR: ruby_block[add node to server list] (graylog::graylog-server line 86) had an error: Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 4001
[2018-01-17T17:22:00+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
2. tried this http://docs.graylog.org/en/2.4/pages/configuration/graylog_ctl.html#restore-etcd
3. this worked, etcd could be started
4. rebooted the appliance but still no access to the web-ui
5. graylog-ctl status showed
```
down: elasticsearch: 0s, normally up, want up; run: log: (pid 925) 142s
run: etcd: (pid 938) 142s; run: log: (pid 935) 142s
run: graylog-server: (pid 924) 142s; run: log: (pid 900) 142s
run: mongodb: (pid 937) 142s; run: log: (pid 927) 142s
run: nginx: (pid 5438) 0s; run: log: (pid 899) 142s
```
6. "graylog-ctl start elasticsearch" didn't work
7. /var/log/graylog/elasticsearch/graylog.log contain many exceptions (i don't know if thats related)

## Context
i tried to upgrade my Graylog appliance

## Your Environment

* Graylog Version: 2.3.2
* Elasticsearch Version: ?
* MongoDB Version: ?
* Operating System: Windows 10 x64
* Browser version: Mozilla Firefox 57.0.4 x64

**Comment by Thomas-1985** [comment]
[graylog.txt](https://github.com/Graylog2/graylog2-server/files/1639851/graylog.txt)
/var/log/graylog/elasticsearch/graylog.log

**Comment by joschi** [comment]
@Thomas-1985 Try purging the etcd data as described in https://community.graylog.org/t/upgrade-of-graylog-appliance-omnibus-failed-etcd-issue/1918/4

CC: @mariussturm

**Comment by Thomas-1985** [comment]
Hi

Yes this did the trick (i reverted to my 2.3.2 snapshot after the failed first try)

1. purged etcd data as described
2. http://docs.graylog.org/en/2.4/pages/configuration/graylog_ctl.html#upgrade-graylog-omnibus
3. now graylog-ctl reconfigure doesn't screw up now
4. after a reboot, graylog 2.4.0 update is done

Thanks a lot guys! :)

Best,
Thomy
