### ISSUE TITLE
API call failed GET http://@<ip>:12900/system/cluster/node returned 401 Unauthorized body

### ISSUE THREAD

**Issue by r4yfx** [Graylog2/graylog2-server#4704]
Upgraded graylog to the latest version and now the configured nodes are no longer connected to the graylog-web. This was working before the upgrade........

Looking at the logs I am seeing the following on the application.log
```
2018-04-05T15:29:57.537+01:00 - [ERROR] - from org.graylog2.restclient.lib.ServerNodesRefreshService in servernodes-refresh-0
Resolving configured nodes failed
org.graylog2.restclient.lib.APIException: API call failed GET http://@<ip-address>:12900/system/cluster/node returned 401 Unauthorized body:
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.handleResponse(ApiClientImpl.java:511) ~[org.graylog2.graylog2-rest-client--1.3.4-1.3.4.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.executeOnAll(ApiClientImpl.java:615) ~[org.graylog2.graylog2-rest-client--1.3.4-1.3.4.jar:na]
        at org.graylog2.restclient.lib.ServerNodesRefreshService.resolveConfiguredNodes(ServerNodesRefreshService.java:97) [org.graylog2.graylog2-rest-client--1.3.4-1.3.4.jar:na]
        at org.graylog2.restclient.lib.ServerNodesRefreshService.access$400(ServerNodesRefreshService.java:42) [org.graylog2.graylog2-rest-client--1.3.4-1.3.4.jar:na]
        at org.graylog2.restclient.lib.ServerNodesRefreshService$1.run(ServerNodesRefreshService.java:126) [org.graylog2.graylog2-rest-client--1.3.4-1.3.4.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

on the graylog-server I see the following;

2018-04-05T15:34:17.715+01:00 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2018-04-05T15:34:17.908+01:00 WARN  [V20161130141500_DefaultStreamRecalcIndexRanges] Interrupted or timed out waiting for Elasticsearch cluster, checking again.
2018-04-05T15:34:47.716+01:00 ERROR [Cluster] Couldn't read cluster health for indices [graylog2_*] (Could not connect to http://127.0.0.1:9200)
2018-04-05T15:34:47.716+01:00 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
```
Viewing the graylog-server from the API-Browser and I can all three nodes. 

* Graylog Version: 2.4
* Elasticsearch Version: 1.7
* MongoDB Version: 3.2
* Operating System: CentOS 7
* Browser version: Chrome 65.0.3325.181

**Comment by joschi** [comment]
The standalone Graylog web interface has been deprecated (or better: removed) in Graylog 2.0.0.

Please read the upgrade notes at http://docs.graylog.org/en/2.4/pages/upgrade.html
