### ISSUE TITLE
Getting "java.net.BindException: Address already in use" at graylog startup, but Input ports are bound and logs are coming in

### ISSUE THREAD

**Issue by juliohm1978** [Graylog2/graylog2-server#4760]
Currently using graylog server 2.4.3-3 in a Kubernetes deployment, and we noticed these errors are persistent after restarting the server.

![image](https://user-images.githubusercontent.com/4145456/39198350-3d4f7fdc-47bd-11e8-9e7b-7632bd75abff.png)

Logs show a number of BindExceptions:

```
2018-04-24 15:38:41,137 ERROR: org.graylog2.plugin.inputs.transports.NettyTransport - Error in Input [Syslog UDP/5ada5a7036a02c00011c69db] (channel [id: 0x98e23b6b])
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_72-internal]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_72-internal]
	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:691) ~[?:1.8.0_72-internal]
	at sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:91) ~[?:1.8.0_72-internal]
	at org.jboss.netty.channel.socket.nio.NioDatagramPipelineSink.bind(NioDatagramPipelineSink.java:129) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioDatagramPipelineSink.eventSunk(NioDatagramPipelineSink.java:77) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) [graylog.jar:?]
	at org.jboss.netty.channel.SimpleChannelHandler.bindRequested(SimpleChannelHandler.java:299) [graylog.jar:?]
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:265) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784) [graylog.jar:?]
	at org.jboss.netty.channel.SimpleChannelHandler.bindRequested(SimpleChannelHandler.java:299) [graylog.jar:?]
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:265) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) [graylog.jar:?]
	at org.jboss.netty.channel.Channels.bind(Channels.java:561) [graylog.jar:?]
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:197) [graylog.jar:?]
	at org.jboss.netty.bootstrap.ConnectionlessBootstrap.bind(ConnectionlessBootstrap.java:198) [graylog.jar:?]
	at org.graylog2.plugin.inputs.transports.NettyTransport.launch(NettyTransport.java:136) [graylog.jar:?]
	at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:155) [graylog.jar:?]
	at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
2018-04-24 15:38:41,137 ERROR: org.graylog2.plugin.inputs.transports.NettyTransport - Error in Input [Syslog UDP/5a4bc0be12522a5ae7bf6fb4] (channel [id: 0x71f95b52])
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_72-internal]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_72-internal]
	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:691) ~[?:1.8.0_72-internal]
	at sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:91) ~[?:1.8.0_72-internal]
	at org.jboss.netty.channel.socket.nio.NioDatagramPipelineSink.bind(NioDatagramPipelineSink.java:129) [graylog.jar:?]
	at org.jboss.netty.channel.socket.nio.NioDatagramPipelineSink.eventSunk(NioDatagramPipelineSink.java:77) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) [graylog.jar:?]
	at org.jboss.netty.channel.SimpleChannelHandler.bindRequested(SimpleChannelHandler.java:299) [graylog.jar:?]
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:265) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784) [graylog.jar:?]
	at org.jboss.netty.channel.SimpleChannelHandler.bindRequested(SimpleChannelHandler.java:299) [graylog.jar:?]
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:265) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) [graylog.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) [graylog.jar:?]
	at org.jboss.netty.channel.Channels.bind(Channels.java:561) [graylog.jar:?]
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:197) [graylog.jar:?]
	at org.jboss.netty.bootstrap.ConnectionlessBootstrap.bind(ConnectionlessBootstrap.java:198) [graylog.jar:?]
	at org.graylog2.plugin.inputs.transports.NettyTransport.launch(NettyTransport.java:136) [graylog.jar:?]
	at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:155) [graylog.jar:?]
	at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
```

## Expected Behavior
I expect Graylog to start normally without issuing BindExceptions for Inputs that are correctly configured.

## Current Behavior
Upon configuring Syslog UDP inputs, they start correctly at the moment they are configured. However, when the Graylog server is restarted, it will throw BindExcpetions indicating that Inputs have failed to start.

Interestingly, a netstat in the graylog container shows that ports are actually bound to the graylog process and logs are coming in, even though the graylog interface shows the inputs as failed.

I was able to find an older issue #3903, which seems to deal with a similar problem. That was closed with a merged fix, but I cannot be sure it's related. I can confirm that, in my case, the failed inputs do have extractors configured and the error does not occur for new inputs we create without any extractors.

## Environment

* Kubernetes 1.10.1
* Graylog Version: 2.4.3-3
* Elasticsearch Version: 5.6.6
* MongoDB Version: mongo:3
* Operating System: Docker image graylog2/server:2.4.3-3

**Comment by joschi** [comment]
@juliohm1978 Please provide the complete Kubernetes configuration related to Graylog.

Are you running multiple instances of Graylog on the same pod?

**Comment by juliohm1978** [comment]
The following is a complete log file of the graylog server pod startup.

[graylog.log](https://github.com/Graylog2/graylog2-server/files/1943719/graylog.log)

**Comment by gianluca-valentini** [comment]
I follow this problem because it happens in my environment too 
when I create an input through REST.

The situation is interesting because restarting graylog the input no longer failed

**Comment by juliohm1978** [comment]
Recently upgraded to Graylog Server v3.0.2, and the problem seems to have disappeared, so I'm closing the issue.

Anyone else still seeing this on the current version, feel free to shout for a reopen.

Best regards.
