### ISSUE TITLE
ApiError Duplicate key

### ISSUE THREAD

**Issue by schurd** [Graylog2/graylog2-server#4784]
Hallo,

when I go to Alerts -> Notifications I get the following error:
Could not retrieve available alert notifications

Fetching available alert notification types failed with status: cannot GET http://10.150.150.5:9000/api/alerts/callbacks/types (500)
Then I go to the REST API browser to the function “/alerts/callback/types” and get back this Response:
```
{
"type": "ApiError",
"message": "Duplicate key siser01"
}
```
This might be a bug.
Graylog is latest (2.4.4), everything else works fine.

Thanks in advance,

Dietmar

List of installed Plugins:

```
Installed plugins 16 plugins installed

ArchivePlugin 2.4.4 Graylog, Inc. Archive features for Graylog 
Audit Log 2.4.4 Graylog, Inc. Audit Log 
AWS plugins 2.4.4 Graylog, Inc. Collection of plugins to read data from or interact with the Amazon Web Services (AWS). 
CEF Input 2.4.4 Graylog, Inc. Input plugin to receive CEF (Common Event Format) messages. 
Collector 2.4.4 Graylog, Inc. Collectors plugin 
DnsResolverFilter 1.2.0 Graylog, Inc. Resolves host names of message fields.
Elastic Beats Input 2.4.4 Graylog, Inc. Input plugin for Elastic Beats (Beats/Lumberjack protocol).
Enterprise Integration Plugin 2.4.4 Graylog, Inc Provides basic integration with Graylog Enterprise 
Internal Metrics Graphite Reporter 1.4.0 Graylog, Inc. A plugin for reporting internal Graylog metrics to Graphite.
License Plugin 2.4.4 Graylog, Inc. Graylog Enterprise License Manager
MapWidgetPlugin 2.4.4 Graylog, Inc. Map widget for Graylog
NetFlow Plugin 2.4.4 Graylog, Inc. Provides NetFlow inputs 
Pipeline Processor Plugin 2.4.4 Graylog, Inc. Pluggable pipeline processing framework 
Single Sign-On (SSO) Authentication Provider 2.3.0 Graylog, Inc SSO Authentication provider
SyslogOutputPlugin 1.0.0 Wizecore. Based on work by Intelie. Enables sending messages to syslog via TCP, UDP and TCP over SSL.
Threat Intelligence Plugin 2.4.4 Graylog, Inc. Threat intelligence database lookup functions for the Graylog Pipeline Processor
```

**Log entry for the problem:**
```
2018-05-11T10:04:29.124+02:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.IllegalStateException: Duplicate key siser01
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133) ~[?:1.8.0_121]
        at java.util.HashMap.merge(HashMap.java:1253) ~[?:1.8.0_121]
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[?:1.8.0_121]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_121]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_121]
        at org.graylog2.alarmcallbacks.EmailAlarmCallback.getEnrichedRequestedConfiguration(EmailAlarmCallback.java:220) ~[graylog.jar:?]
        at org.graylog2.rest.resources.alarmcallbacks.AlarmCallbacksResource.getConfigurationRequest(AlarmCallbacksResource.java:161) ~[graylog.jar:?]
        at org.graylog2.rest.resources.alarmcallbacks.AlarmCallbacksResource.available(AlarmCallbacksResource.java:118) ~[graylog.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

[alarmcallbackconfigurations.json.gz](https://github.com/Graylog2/graylog2-server/files/1994539/alarmcallbackconfigurations.json.gz)
* Graylog Version: 2.4.4
* Elasticsearch Version: 5.6.6
* MongoDB Version: 3.6.2
* Operating System: SLES 12 SP2
* Browser version:  IE 11

**Comment by joschi** [comment]
@schurd Thanks for reporting this. The cause of the problem seems to be that there are multiple users with the same name ("siser01") in your system, which in itself is a bug.

As a workaround, please check the "users" collection in MongoDB for duplicate usernames. You can use the following MongoDB query for getting a list of usernames and user IDs which exist more than once in the database:
```
db.users.aggregate([  
    {$group: {
        _id: {username: "$username"},
        uniqueIds: {$addToSet: "$_id"},
        count: {$sum: 1}
        }
    },
    {$match: {"_id" :{ "$ne" : null } , "count" : {"$gt": 1} } }, 
    {$sort: {"count" : -1} }
]);
```

For reference:
https://github.com/Graylog2/graylog2-server/blob/4659dbe9203b953734eaff068e4c069cfb494b44/graylog2-server/src/main/java/org/graylog2/alarmcallbacks/EmailAlarmCallback.java#L219-L220

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
