### ISSUE TITLE
Graylog v2.4.4: Proxy Basic auth problem

### ISSUE THREAD

**Issue by schindlerd** [Graylog2/graylog2-server#4788]
The newly introduced proxy server authentication #4758 seems not to work with BlueCoat proxies.

## Expected Behavior
When defining the correct `http_proxy_uri = http://username:password@proxy.example.com:8080` in `server.conf`it should be possible to access https://api.graylog.com/report via proxy.

## Current Behavior

Proxy authentication fails with java IO exception although the proxy is using BASIC authentication:
```
2018-05-10T00:17:22.167+02:00 WARN  [OkHttpClientProvider$ProxyAuthenticator] Graylog only supports the "Basic" authentication sche
me but the proxy server asks for one of the following: [BASIC]
2018-05-10T00:17:22.167+02:00 WARN  [OkHttpClientProvider] Unable to connect to proxy:
java.io.IOException: Failed to authenticate with proxy
        at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:380) ~[graylog.jar:?]
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:211) ~[graylog.jar:?]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:152) ~[graylog.jar:?]
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256) ~[graylog.jar:?]
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134) ~[graylog.jar:?]
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113) ~[graylog.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[graylog.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[graylog.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) [graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) [graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) [graylog.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) [graylog.jar:?]
        at okhttp3.RealCall.execute(RealCall.java:77) [graylog.jar:?]
		at org.graylog.plugins.license.LicenseReportPeriodical.doRun(LicenseReportPeriodical.java:139) [graylog-plugin-license-2.4.4.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
2018-05-10T00:17:22.169+02:00 WARN  [LicenseReportPeriodical] Unable to connect to license server: Failed to authenticate with proxy.
```

## Possible Solution

Is it a problem that the proxy seems to return "BASIC" (all capital) instead of may be expected "Basic"?

## Steps to Reproduce (for bugs)

1. Edit `server.conf` and add `http_proxy_uri = http://username:password@proxy.example.com:8080`
2. Restart graylog-server
3. Check server log for errors

## Context

This is a lcensing issue. We are trying to access https://api.graylog.com/report via proxy.

## Your Environment

* Graylog Version: 2.4.4
* Elasticsearch Version: 5.6.7
* MongoDB Version: 3.2
* Operating System: Oracle Linux 7.5
* Browser version: Firefox Quantum 60

**Comment by joschi** [comment]
@schindlerd Please check out, if the `graylog.jar` artifact in the tar-ball from http://graylog2public.s3.amazonaws.com/graylog-2.4.5-rc.1%2Bissue-4788-20180513160753-graylog-server-tarball.tar.gz solves your problem.
It's a build of Graylog 2.4.4 with the changes from #4790.

**Comment by schindlerd** [comment]
@joschi That did the trick! Thanks a lot for your efforts.

**Comment by joschi** [comment]
@schindlerd Please keep the issue open until the PRs have been merged. 😉

**Comment by bernd** [comment]
@schindlerd This should be fixed in Graylog 2.4.5.

**Comment by schindlerd** [comment]
@bernd it is working like a charm 👍

**Comment by bernd** [comment]
@schindlerd 

> it is working like a charm

Great! Thanks for the feedback! :+1:
