### ISSUE TITLE
Error finding entity list for dashboards

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#4813]
On the `content_packs` branch, doing a `POST` on `/system/catalog` returns a 500 error. This seems to be somehow related to dashboards, or at least I could make the request work when requesting inputs instead.

Payload:

```
{"entities":[{"id":"58b6cc2f266b272870c801fc","type":"dashboard"},{"id":"5a68b21258ddc87f325a5b7a","type":"dashboard"},{"id":"58a310c5266b2768c0ab7360","type":"dashboard"},{"id":"5909acfc8ce67749fce7a6d2","type":"dashboard"}]}
```

Server log:

```
2018-05-29 14:51:00,009 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_112]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752) ~[?:1.8.0_112]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750) ~[?:1.8.0_112]
	at com.google.common.graph.MapIteratorCache$1$1.next(MapIteratorCache.java:100) ~[guava-24.0-jre.jar:?]
	at org.graylog2.contentpacks.catalogs.CatalogIndex.resolveDependencyGraph(CatalogIndex.java:72) ~[classes/:?]
	at org.graylog2.contentpacks.catalogs.CatalogIndex.resolveDependencyGraph(CatalogIndex.java:87) ~[classes/:?]
	at org.graylog2.contentpacks.catalogs.CatalogIndex.resolveEntities(CatalogIndex.java:64) ~[classes/:?]
	at org.graylog2.rest.resources.system.contentpacks.CatalogResource.resolveEntities(CatalogResource.java:76) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.1.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.28.jar:2.3.28]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [metrics-core-4.0.2.jar:4.0.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

MongoDB `dashboards` collection:

<details>

```
/* 1 */
{
    "_id" : ObjectId("58a310c5266b2768c0ab7360"),
    "creator_user_id" : "hans",
    "created_at" : ISODate("2017-02-14T14:14:29.172Z"),
    "description" : "Dashboard without widget positions",
    "positions" : {
        "a3430681-0dd2-43d6-8a98-bbac82a31a11" : {
            "width" : 4,
            "col" : 1,
            "row" : 19,
            "height" : 2
        },
        "82310d0f-7ffc-4f32-9397-6b93f87d1f80" : {
            "width" : 2,
            "col" : 1,
            "row" : 13,
            "height" : 2
        },
        "9838ccca-4d0c-492e-b5d4-22fc13f53292" : {
            "width" : 4,
            "col" : 1,
            "row" : 15,
            "height" : 2
        },
        "47b8e7fc-2778-40f3-9eb0-98d099ce9b80" : {
            "width" : 2,
            "col" : 1,
            "row" : 1,
            "height" : 6
        },
        "aa5587d9-a65d-4a8f-8ed9-05b640d5dfe6" : {
            "width" : 4,
            "col" : 1,
            "row" : 21,
            "height" : 2
        },
        "61f9814e-9a8f-45f2-85cd-404415098c8b" : {
            "width" : 2,
            "col" : 1,
            "row" : 7,
            "height" : 6
        },
        "9e1769fb-daf6-4738-88cb-f82883f0235c" : {
            "width" : 2,
            "col" : 1,
            "row" : 17,
            "height" : 2
        }
    },
    "title" : "Dynamic dashboard",
    "widgets" : [ 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Search result graph",
            "id" : "aa5587d9-a65d-4a8f-8ed9-05b640d5dfe6",
            "type" : "SEARCH_RESULT_CHART",
            "config" : {
                "interval" : "minute",
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "query" : ""
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Search result count",
            "id" : "9e1769fb-daf6-4738-88cb-f82883f0235c",
            "type" : "SEARCH_RESULT_COUNT",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "lower_is_better" : true,
                "trend" : true,
                "query" : ""
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Search result count",
            "id" : "82310d0f-7ffc-4f32-9397-6b93f87d1f80",
            "type" : "SEARCH_RESULT_COUNT",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "lower_is_better" : false,
                "trend" : false,
                "query" : ""
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "HTTP methods",
            "id" : "47b8e7fc-2778-40f3-9eb0-98d099ce9b80",
            "type" : "QUICKVALUES",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "field" : "http_method",
                "show_pie_chart" : true,
                "query" : "",
                "show_data_table" : false
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Levels",
            "id" : "61f9814e-9a8f-45f2-85cd-404415098c8b",
            "type" : "QUICKVALUES",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "field" : "facility",
                "show_pie_chart" : true,
                "query" : "",
                "show_data_table" : true
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Messages in last 5 minutes",
            "id" : "9838ccca-4d0c-492e-b5d4-22fc13f53292",
            "type" : "SEARCH_RESULT_CHART",
            "config" : {
                "interval" : "minute",
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "query" : ""
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Absolute search",
            "id" : "a3430681-0dd2-43d6-8a98-bbac82a31a11",
            "type" : "SEARCH_RESULT_CHART",
            "config" : {
                "timerange" : {
                    "from" : ISODate("2016-07-04T13:29:00.000Z"),
                    "to" : ISODate("2016-07-04T13:31:01.000Z"),
                    "type" : "absolute"
                },
                "interval" : "minute",
                "query" : ""
            }
        }
    ]
}

/* 2 */
{
    "_id" : ObjectId("58b6cc2f266b272870c801fc"),
    "creator_user_id" : "hans",
    "created_at" : ISODate("2017-03-01T13:27:11.114Z"),
    "description" : "Dashboard with fixed widgets",
    "positions" : {
        "773a22ce-3c17-467e-86cf-ac0f409702e7" : {
            "width" : 4,
            "col" : 1,
            "row" : 5,
            "height" : 4
        },
        "e56a0338-0f49-454e-84fc-fa8ecf5da3ad" : {
            "width" : 2,
            "col" : 5,
            "row" : 1,
            "height" : 6
        },
        "534dba10-18de-43c5-898b-ff540d949537" : {
            "width" : 4,
            "col" : 1,
            "row" : 3,
            "height" : 2
        },
        "7664c1c0-8eed-4b4e-8f66-6144bc82b899" : {
            "width" : 2,
            "col" : 7,
            "row" : 1,
            "height" : 2
        },
        "fef31f91-f787-47fd-be67-c07a9e8c3634" : {
            "width" : 4,
            "col" : 1,
            "row" : 1,
            "height" : 2
        }
    },
    "title" : "Fixed dashboard",
    "widgets" : [ 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Field graph",
            "id" : "534dba10-18de-43c5-898b-ff540d949537",
            "type" : "STACKED_CHART",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "renderer" : "line",
                "interpolation" : "linear",
                "rangeType" : "relative",
                "series" : [ 
                    {
                        "query" : "",
                        "field" : "took_ms",
                        "statistical_function" : "mean"
                    }, 
                    {
                        "query" : "",
                        "field" : "took_ms",
                        "statistical_function" : "max"
                    }
                ],
                "query" : "",
                "interval" : "minute",
                "relative" : 300
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Search result graph",
            "id" : "fef31f91-f787-47fd-be67-c07a9e8c3634",
            "type" : "SEARCH_RESULT_CHART",
            "config" : {
                "interval" : "minute",
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "query" : ""
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Quick values",
            "id" : "e56a0338-0f49-454e-84fc-fa8ecf5da3ad",
            "type" : "QUICKVALUES",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "field" : "user_id",
                "show_pie_chart" : true,
                "query" : "",
                "show_data_table" : true
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Statistical value",
            "id" : "773a22ce-3c17-467e-86cf-ac0f409702e7",
            "type" : "STATS_COUNT",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "field" : "took_ms",
                "trend" : true,
                "query" : "",
                "stats_function" : "std_deviation",
                "lower_is_better" : true
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Search result count",
            "id" : "7664c1c0-8eed-4b4e-8f66-6144bc82b899",
            "type" : "SEARCH_RESULT_COUNT",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "lower_is_better" : false,
                "trend" : true,
                "query" : ""
            }
        }
    ]
}

/* 3 */
{
    "_id" : ObjectId("5909acfc8ce67749fce7a6d2"),
    "creator_user_id" : "hans",
    "description" : "yolo",
    "created_at" : ISODate("2017-05-03T10:12:12.008Z"),
    "positions" : {
        "1fa8a45f-e692-4036-8ce9-86abd8d123a1" : {
            "width" : 4,
            "col" : 1,
            "row" : 1,
            "height" : 4
        },
        "958b9adb-0446-45db-b591-da8ecd6feae4" : {
            "width" : 2,
            "col" : 1,
            "row" : 19,
            "height" : 6
        },
        "a939fee6-b61d-45eb-9123-e26ab19c00ba" : {
            "width" : 4,
            "col" : 3,
            "row" : 5,
            "height" : 4
        },
        "07aed3a8-9b2e-46de-a642-ccdbb3ff3732" : {
            "width" : 2,
            "col" : 1,
            "row" : 5,
            "height" : 6
        },
        "4b61ff70-6ac6-434b-b41b-7e26ebbb04cb" : {
            "width" : 2,
            "col" : 1,
            "row" : 11,
            "height" : 2
        },
        "8c71dc93-3a7a-4a6b-8638-cdf758e0009c" : {
            "width" : 2,
            "col" : 1,
            "row" : 13,
            "height" : 6
        }
    },
    "title" : "Test",
    "widgets" : [ 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Quick values",
            "id" : "07aed3a8-9b2e-46de-a642-ccdbb3ff3732",
            "type" : "QUICKVALUES",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "field" : "pid",
                "show_pie_chart" : true,
                "query" : "",
                "show_data_table" : true
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Locations src_ip",
            "id" : "a939fee6-b61d-45eb-9123-e26ab19c00ba",
            "type" : "org.graylog.plugins.map.widget.strategy.MapWidgetStrategy",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "field" : "src_ip_geolocation",
                "query" : ""
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Kernel messages in last week",
            "id" : "4b61ff70-6ac6-434b-b41b-7e26ebbb04cb",
            "type" : "STREAM_SEARCH_RESULT_COUNT",
            "config" : {
                "timerange" : {
                    "type" : "keyword",
                    "keyword" : "last week"
                },
                "lower_is_better" : false,
                "stream_id" : "58a2e6dc266b2752fa77206d",
                "trend" : false,
                "query" : "facility:kernel AND source:\"dalek\""
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Field graph",
            "id" : "1fa8a45f-e692-4036-8ce9-86abd8d123a1",
            "type" : "FIELD_CHART",
            "config" : {
                "valuetype" : "mean",
                "renderer" : "bar",
                "interpolation" : "linear",
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "rangeType" : "relative",
                "field" : "took_ms",
                "query" : "",
                "interval" : "minute",
                "relative" : 300
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Quick values stacked",
            "id" : "8c71dc93-3a7a-4a6b-8638-cdf758e0009c",
            "type" : "QUICKVALUES",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "field" : "resource",
                "query" : "",
                "show_data_table" : true,
                "limit" : 5,
                "show_pie_chart" : true,
                "sort_order" : "desc",
                "stacked_fields" : "controller",
                "data_table_limit" : 50
            }
        }
    ]
}

/* 4 */
{
    "_id" : ObjectId("5a68b21258ddc87f325a5b7a"),
    "creator_user_id" : "hans",
    "description" : "lolol",
    "created_at" : ISODate("2018-01-24T16:19:30.360Z"),
    "positions" : {
        "4ec67d4d-fa5f-4e67-9d00-ed04b993069f" : {
            "width" : 2,
            "col" : 1,
            "row" : 3,
            "height" : 6
        },
        "b8bc9277-c56e-4ed0-9259-126f8c2f835d" : {
            "width" : 2,
            "col" : 1,
            "row" : 1,
            "height" : 2
        },
        "75bb068f-352a-4e7e-b7b1-8da27b299bc0" : {
            "width" : 4,
            "col" : 1,
            "row" : 9,
            "height" : 2
        },
        "7921ffc8-94b0-4b00-82c7-9cdce88aa9b0" : {
            "width" : 4,
            "col" : 1,
            "row" : 11,
            "height" : 2
        },
        "29927168-df74-4772-a358-7f3577754263" : {
            "width" : 4,
            "col" : 1,
            "row" : 13,
            "height" : 2
        }
    },
    "title" : "Testeria",
    "widgets" : [ 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Search result count",
            "id" : "b8bc9277-c56e-4ed0-9259-126f8c2f835d",
            "type" : "SEARCH_RESULT_COUNT",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "lower_is_better" : false,
                "trend" : false,
                "query" : ""
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Search result graph",
            "id" : "7921ffc8-94b0-4b00-82c7-9cdce88aa9b0",
            "type" : "SEARCH_RESULT_CHART",
            "config" : {
                "interval" : "minute",
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "query" : ""
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Field graph",
            "id" : "75bb068f-352a-4e7e-b7b1-8da27b299bc0",
            "type" : "FIELD_CHART",
            "config" : {
                "valuetype" : "count",
                "renderer" : "bar",
                "interpolation" : "linear",
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "rangeType" : "relative",
                "field" : "ingest_time",
                "query" : "",
                "interval" : "minute",
                "relative" : 300
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Quick values",
            "id" : "4ec67d4d-fa5f-4e67-9d00-ed04b993069f",
            "type" : "QUICKVALUES",
            "config" : {
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "field" : "resource",
                "query" : "",
                "show_data_table" : true,
                "limit" : 5,
                "show_pie_chart" : true,
                "sort_order" : "desc",
                "stacked_fields" : "",
                "data_table_limit" : 50
            }
        }, 
        {
            "creator_user_id" : "hans",
            "cache_time" : 10,
            "description" : "Field graph",
            "id" : "29927168-df74-4772-a358-7f3577754263",
            "type" : "FIELD_CHART",
            "config" : {
                "valuetype" : "count",
                "renderer" : "bar",
                "interpolation" : "linear",
                "timerange" : {
                    "type" : "relative",
                    "range" : 300
                },
                "rangeType" : "relative",
                "field" : "ingest_time",
                "query" : "",
                "interval" : "minute",
                "relative" : 300
            }
        }
    ]
}
```
</details>

**Comment by edmundoa** [comment]
I tried to reproduce this in the current master but I couldn't, so I'm closing the issue.
