### ISSUE TITLE
CEF mapping for "type" leads to error

### ISSUE THREAD

**Issue by cvtienhoven** [Graylog2/graylog2-server#4839]
## Expected Behavior
When parsing a CEF message with the parse_cef() pipeline function, the fields get added to the message correctly. The parsed part of the message looks like this (some fields obfuscated):

```CEF:0|xxxxxx|yyyyyyy|3.1.2|1|SYSTEM|4|date=2018-06-11 time=12:15:28 logid=0106000001 type=event subtype=system level=warning user=system ui=system action=update status=failure  reason=none letype=4 msg=Some error message describing an issue```

In this case, the field ```type``` would have to be added with value ```event```

## Current Behavior
When parsing a CEF message with the parse_cef() pipeline function, the fields get added to the message, except for the field ```type```. That field cannot be parsed and leads to the following stack trace:

```
2018-06-12T09:44:45.117+02:00 WARN  [MappedMessage] Could not transform CEF field [type] according to standard. Skipping.
java.lang.NumberFormatException: For input string: "event"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_172]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_172]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_172]
        at org.graylog.plugins.cef.parser.CEFMapping.convertInteger(CEFMapping.java:233) ~[graylog-plugin-cef-2.4.3.jar:?]
        at org.graylog.plugins.cef.parser.CEFMapping.convertType(CEFMapping.java:258) ~[graylog-plugin-cef-2.4.3.jar:?]
        at org.graylog.plugins.cef.parser.CEFMapping.convert(CEFMapping.java:299) ~[graylog-plugin-cef-2.4.3.jar:?]
        at org.graylog.plugins.cef.parser.MappedMessage.mapExtensions(MappedMessage.java:36) [graylog-plugin-cef-2.4.3.jar:?]
        at org.graylog.plugins.cef.parser.MappedMessage.<init>(MappedMessage.java:21) [graylog-plugin-cef-2.4.3.jar:?]
        at org.graylog.plugins.cef.pipelines.rules.CEFParserFunction.evaluate(CEFParserFunction.java:57) [graylog-plugin-cef-2.4.3.jar:?]
        at org.graylog.plugins.cef.pipelines.rules.CEFParserFunction.evaluate(CEFParserFunction.java:23) [graylog-plugin-cef-2.4.3.jar:?]
        at org.graylog.plugins.pipelineprocessor.ast.expressions.FunctionExpression.evaluateUnsafe(FunctionExpression.java:63) [graylog-plugin-pipeline-processor-2.4.3.jar:?]
        at org.graylog.plugins.pipelineprocessor.ast.expressions.Expression.evaluate(Expression.java:41) [graylog-plugin-pipeline-processor-2.4.3.jar:?]
        at org.graylog.plugins.pipelineprocessor.ast.statements.VarAssignStatement.evaluate(VarAssignStatement.java:33) [graylog-plugin-pipeline-processor-2.4.3.jar:?]
        at org.graylog.plugins.pipelineprocessor.ast.statements.VarAssignStatement.evaluate(VarAssignStatement.java:22) [graylog-plugin-pipeline-processor-2.4.3.jar:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.evaluateStatement(PipelineInterpreter.java:377) [graylog-plugin-pipeline-processor-2.4.3.jar:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.executeRuleActions(PipelineInterpreter.java:364) [graylog-plugin-pipeline-processor-2.4.3.jar:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.evaluateStage(PipelineInterpreter.java:305) [graylog-plugin-pipeline-processor-2.4.3.jar:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.processForResolvedPipelines(PipelineInterpreter.java:263) [graylog-plugin-pipeline-processor-2.4.3.jar:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.process(PipelineInterpreter.java:143) [graylog-plugin-pipeline-processor-2.4.3.jar:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.process(PipelineInterpreter.java:99) [graylog-plugin-pipeline-processor-2.4.3.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.handleMessage(ProcessBufferProcessor.java:114) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:100) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:77) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```
## Possible Solution
I can't see why ```type``` has to be converted to an integer, as the [specs](https://kc.mcafee.com/resources/sites/MCAFEE/content/live/CORP_KNOWLEDGEBASE/78000/KB78712/en_US/CEF_White_Paper_20100722.pdf) don't mention the field ```type```, so perhaps the following could be changed:

**org.graylog.plugins.cef.parser.CEFMapping.java**:

```
private static Integer convertType(String s) {
        //return convertInteger(s);
        return s;
    }
```

## Steps to Reproduce (for bugs)
1. Create a pipeline with a rule that uses the parse_cef() function
2. Run a simulator with the CEF message above
3. Inspect the server.log file

## Context
I'm parsing log messages from a firewall appliance that logs in CEF format, so it's not possible to alter the format of the messages.

## Your Environment
* Graylog Version: 2.4.3

**Comment by joschi** [comment]
@cvtienhoven See Common Event Format v25, page 21:

| CEF Key Name | Full Name | Data Type | Length | Meaning |
|----------------|-----------|-----------|--------|----------|
| type | type | Integer| | 0 means base event 1 means aggregated 2 means correlation and 3 means action. This field can be omitted for base events (type 0). |

https://community.softwaregrp.com/dcvta86296/attachments/dcvta86296/connector-documentation/1197/1/CommonEventFormatV25.pdf

**Comment by cvtienhoven** [comment]
Crap, you're right, I was looking at old specs :)
