### ISSUE TITLE
NetFlow Module not parsing Cisco input

### ISSUE THREAD

**Issue by damn42** [Graylog2/graylog2-server#4865]
Really just a copy of [this](https://github.com/Graylog2/graylog-plugin-netflow/issues/30).

Graylog and Cisco side are both on the latest version available. Here's the output of Graylogs' server.log

> 2018-06-25T13:08:58.537+02:00 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=28730a81-7868-11e8-bb22-000c2990d247, journalOffset=79177789, codec=netflow, payloadSize=1602, timestamp=2018-06-25T11:08:58.536Z, remoteAddress=/172.23.40.10:64899} on input <5b057436f4933f04bf2706b0>.
2018-06-25T13:08:58.537+02:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=28730a81-7868-11e8-bb22-000c2990d247, journalOffset=79177789, codec=netflow, payloadSize=1602, timestamp=2018-06-25T11:08:58.536Z, remoteAddress=/172.23.40.10:64899}
java.lang.NullPointerException: null
        at org.graylog.plugins.netflow.flows.NetFlowFormatter.toMessageString(NetFlowFormatter.java:54) ~[?:?]
        at org.graylog.plugins.netflow.flows.NetFlowFormatter.toMessage(NetFlowFormatter.java:119) ~[?:?]
        at org.graylog.plugins.netflow.codecs.NetFlowCodec.lambda$decodeV9$2(NetFlowCodec.java:160) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_162]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_162]
        at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[?:1.8.0_162]
        at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_162]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_162]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_162]
        at org.graylog.plugins.netflow.codecs.NetFlowCodec.lambda$decodeV9$3(NetFlowCodec.java:161) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_162]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_162]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_162]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_162]
        at org.graylog.plugins.netflow.codecs.NetFlowCodec.decodeV9(NetFlowCodec.java:163) ~[?:?]
        at org.graylog.plugins.netflow.codecs.NetFlowCodec.decodeMessages(NetFlowCodec.java:134) ~[?:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:148) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

The issue kinda got forgotten, or so it seems. Since the plug-in is deprecated and it's stated to add issues here and I couldn't find it on this page, I thought I could post it here again, maybe it gets more attention here. Sorry if I'm mistaken on this part. 

Thanks!

**Comment by jalogisch** [comment]
same as in the other issue is written we would need netflow data to check.

We do not own 'all devices', in addition no vendor is contributing their own specification of free definitions.

Contribute with as much vendor specific information and data to allow to reverse engineer how this need worked with.

**Comment by damn42** [comment]
can i help you with anything? logs? packet captures? ...?

**Comment by jalogisch** [comment]
@damn42 let me quote @joschi from the linked issue

> provide a pcap of the NetFlow packets (recorded with Wireshark or tcpdump) so that we can reproduce the issue?

**Comment by damn42** [comment]
i try to get a pcap..
what i'm seeing just now is that cisco is using a more or less proprietary version of netflow v9  called "NSEL". although, other (or at least some) "open source netflow collectors" seem to support nsel. could that be the root of this problem?

**Comment by joschi** [comment]
@damn42 Maybe, but we'd need a pcap anyway.

**Comment by toro0411** [comment]
@joschi 
[netflow.zip](https://github.com/Graylog2/graylog2-server/files/2207961/netflow.zip)
Here is my pcap file, could you help me?

**Comment by sdanelson** [comment]
I am also experiencing this same issue. My ASA is running older code but graylog is 2.4.6. Let me know if you need an additional pcap or other log files.

**Comment by ebnozn** [comment]
Hi - I'm also experiencing this same issue.  Is there something I can provide to get this re-opened / looked at?  I can submit pcap's, Graylog server.log files, ASA code versions and config details, etc.  Thx!  --Mark

**Comment by ortizleo** [comment]
Same issue here, Netflow inst working with Cisco routers. No logs in server.log, but the input is working (tested with softflowd) and router is sending the flows (checked with tcpdump). Graylog Version 2.4.6.

**Comment by jalogisch** [comment]
Please be aware that we need samples to test our tool. Yes out there are collections like http://packetlife.net/captures/protocol/udp/ but you as user would help us if you provide sample data.

We as developer do not own all the devices you have and do not count on the vendor that they will provide us with the samples of your device.

> provide a pcap of the NetFlow packets (recorded with Wireshark or tcpdump) so that we can reproduce the issue?

This issue is tracked in the initial linked https://github.com/Graylog2/graylog-plugin-netflow/issues/30 that is why I'll close this one.

**Comment by mpfz0r** [comment]
The upcoming 3.0 release contains a couple of fixes that might fix this.
Feel free to download 3.0-beta3 and give us feedback.

@toro0411 Thanks for the pcap, unfortunately it did not capture any template records.
I don't know how often a Cisco device sends these, but without them we don't know how to decode this.
Maybe you could get us a longer capture?
