### ISSUE TITLE
Content packs stuck "loading..."

### ISSUE THREAD

**Issue by wluke1** [Graylog2/graylog2-server#4872]
## Expected Behavior

A list of content packs

## Current Behavior

Under "Select content packs" it says "Loading..." and never loads

## Possible Solution

I had just uploaded a json file from the marketplace. I don't know how to unload it. I assume if I could remove/delete the file it would be happy again.

## Steps to Reproduce (for bugs)

1. Downloaded json file from https://marketplace.graylog.org/addons/499f432f-bca2-4bfe-b973-fd027fba787a
2. Made my edits (Input ID and port #)
3. saved json file to local comptuer
4. uploaded json file

## Context

wondering what the contact pack for Sonicwall does. I hoping it helps turn the log data into information.

## Your Environment

Brand new build on a VM.

App | Version
---|---
 Graylog | 2.4.5+8e18e6a
 Elasticsearch | 5.6.10
 MongoDB | v3.6.5
 Operating | CentOS 7.5.1804
 Browser | Version 67.0.3396.87 (Official Build) (64-bit)

From Browser:
```
client.js:772 GET http://xxx.xxx.xxx.xxx:9000/api/system/bundles 500 (Internal Server Error)
l._end @ client.js:772
l.end @ client.js:676
(anonymous) @ index.js:80
a @ bluebird.js:992
o._resolveFromExecutor @ bluebird.js:3249
o @ bluebird.js:2845
i.promise @ index.js:79
i.then @ index.js:121
value @ FetchProvider.js:57
(anonymous) @ FetchProvider.js:153
s @ FetchProvider.js:154
list @ ConfigurationBundlesStore.jsx:68
n @ vendor.552834c48b86209e305c.js:33
o.emit @ vendor.552834c48b86209e305c.js:28
trigger @ vendor.552834c48b86209e305c.js:33
(anonymous) @ vendor.552834c48b86209e305c.js:33
t.exports @ _invoke.js:5
d.(anonymous function) @ _task.js:35
g @ _task.js:21
m @ _task.js:25

FetchProvider.js:17 There was an error fetching a resource: cannot GET http://xxx.xxx.xxx.xxx:9000/api/system/bundles (500). Additional information: Not available
e @ FetchProvider.js:17
(anonymous) @ FetchProvider.js:82
i @ bluebird.js:5256
o._settlePromiseFromHandler @ bluebird.js:3278
o._settlePromise @ bluebird.js:3335
o._settlePromise0 @ bluebird.js:3380
o._settlePromises @ bluebird.js:3455
(anonymous) @ bluebird.js:175
Promise.then (async)
o @ bluebird.js:4484
c.hasDevTools.r.settlePromises @ bluebird.js:174
o._reject @ bluebird.js:3422
o._rejectCallback @ bluebird.js:3240
(anonymous) @ bluebird.js:3252
(anonymous) @ index.js:93
l.callback @ client.js:611
(anonymous) @ client.js:436
n.emit @ index.js:133
e.onreadystatechange @ client.js:705
XMLHttpRequest.send (async)
l._end @ client.js:772
l.end @ client.js:676
(anonymous) @ index.js:80
a @ bluebird.js:992
o._resolveFromExecutor @ bluebird.js:3249
o @ bluebird.js:2845
i.promise @ index.js:79
i.then @ index.js:121
value @ FetchProvider.js:57
(anonymous) @ FetchProvider.js:153
s @ FetchProvider.js:154
list @ ConfigurationBundlesStore.jsx:68
n @ vendor.552834c48b86209e305c.js:33
o.emit @ vendor.552834c48b86209e305c.js:28
trigger @ vendor.552834c48b86209e305c.js:33
(anonymous) @ vendor.552834c48b86209e305c.js:33
t.exports @ _invoke.js:5
d.(anonymous function) @ _task.js:35
g @ _task.js:21
m @ _task.js:25

bluebird.js:1545 Unhandled rejection Error: cannot GET http://xxx.xxx.xxx.xxx:9000/api/system/bundles (500)
    at new e (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:1:2346)
    at http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:1:3747
    at i (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:37:73003)
    at o._settlePromiseFromHandler (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:37:46325)
    at o._settlePromise (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:37:47125)
    at o._settlePromise0 (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:37:47824)
    at o._settlePromises (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:37:49040)
    at http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:37:2564
From previous event:
    at o.p [as _captureStackTrace] (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:37:10310)
    at o._then (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:37:41772)
    at o.then (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:37:40128)
    at l.i.then (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:104:89483)
    at t.value (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:1:3290)
    at http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:1:1493
    at s (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:1:1510)
    at s.list (http://xxx.xxx.xxx.xxx:9000/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.81cab787bad4ca22b96f.js:104:130374)
    at o.n (http://xxx.xxx.xxx.xxx:9000/assets/vendor.552834c48b86209e305c.js:33:195270)
    at o.emit (http://xxx.xxx.xxx.xxx:9000/assets/vendor.552834c48b86209e305c.js:28:30230)
    at Function.trigger (http://xxx.xxx.xxx.xxx:9000/assets/vendor.552834c48b86209e305c.js:33:196145)
    at http://xxx.xxx.xxx.xxx:9000/assets/vendor.552834c48b86209e305c.js:33:196249
    at t.exports (http://xxx.xxx.xxx.xxx:9000/assets/polyfill.d62de657b1bfcd25ec80.js:1:32795)
    at d.(anonymous function) (http://xxx.xxx.xxx.xxx:9000/assets/polyfill.d62de657b1bfcd25ec80.js:1:25754)
    at Number.g (http://xxx.xxx.xxx.xxx:9000/assets/polyfill.d62de657b1bfcd25ec80.js:1:25612)
    at MessagePort.m (http://xxx.xxx.xxx.xxx:9000/assets/polyfill.d62de657b1bfcd25ec80.js:1:25634)
```

From server.log
```
2018-06-27T13:27:17.822-07:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[graylog.jar:?]
        at com.google.common.collect.ImmutableSetMultimap$Builder.put(ImmutableSetMultimap.java:268) ~[graylog.jar:?]
        at org.graylog2.rest.resources.system.bundles.BundleResource.listBundles(BundleResource.java:102) ~[graylog.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by joschi** [comment]
> ```text
> at org.graylog2.rest.resources.system.bundles.BundleResource.listBundles(BundleResource.java:102) ~[graylog.jar:?]
> ```

https://github.com/Graylog2/graylog2-server/blob/8e18e6aec597bd0895e5525e652995e3d34a1a6b/graylog2-server/src/main/java/org/graylog2/rest/resources/system/bundles/BundleResource.java#L102

@wluke1 Make sure that your custom content packs all have a "category" field.
It looks like there's at least one content pack in the MongoDB database, which doesn't contain a "category" field or the "category" field is `null`.

You can try to identify these content packs in the MongoDB database with the following queries:
```
db.content_packs.find({ "category" : { "$exists" : false } });
db.content_packs.find({ "category" : null });
```

**Comment by wluke1** [comment]
```
[ _@_ ]$ mongo
> use graylog
```
and ran the queries you suggested.

Both commands returned the same block of text:
```
{ "_id" : ObjectId("5b33c11a427e2557cdb77806"), "name" : "Dell SonicWall", "description" : "bla bla bla", "inputs" : [ { "title" : "SonicWall", "configuration" : { "override_source" : null, "recv_buffer_size" : 26214400, "bind_address" : "0.0.0.0", "port" : 1515 }, "static_fields" : {  }, "type" : "org.graylog2.inputs.raw.udp.RawUDPInput", "global" : true, "extractors" : [ { "title" : "Garbage Cleanup and KVP", "type" : "REGEX_REPLACE", "cursor_strategy" : "COPY", "target_field" : "message", "source_field" : "message", "configuration" : { "regex" : "^<\\d+\\>(.*)", "replacement" : "$1", "replace_all" : true }, "converters" : [ { "type" : "TOKENIZER", "configuration" : {  } }, { "type" : "NUMERIC", "configuration" : {  } }, { "type" : "DATE", "configuration" : { "date_format" : "yyyy-MM-dd HH:mm:ss z" } } ], "condition_type" : "NONE", "condition_value" : "", "order" : 0 }, { "title" : "dst_ip", "type" : "SPLIT_AND_INDEX", "cursor_strategy" : "COPY", "target_field" : "dst_ip", "source_field" : "dst", "configuration" : { "index" : 1, "split_by" : ":" }, "converters" : [ ], "condition_type" : "NONE", "condition_value" : "", "order" : 0 }, { "title" : "dst_port", "type" : "SPLIT_AND_INDEX", "cursor_strategy" : "COPY", "target_field" : "dst_port", "source_field" : "dst", "configuration" : { "index" : 2, "split_by" : ":" }, "converters" : [ { "type" : "NUMERIC", "configuration" : {  } } ], "condition_type" : "NONE", "condition_value" : "", "order" : 0 }, { "title" : "dst_if", "type" : "SPLIT_AND_INDEX", "cursor_strategy" : "COPY", "target_field" : "dst_if", "source_field" : "dst", "configuration" : { "index" : 3, "split_by" : ":" }, "converters" : [ ], "condition_type" : "NONE", "condition_value" : "", "order" : 0 }, { "title" : "src_ip", "type" : "SPLIT_AND_INDEX", "cursor_strategy" : "COPY", "target_field" : "src_ip", "source_field" : "src", "configuration" : { "index" : 1, "split_by" : ":" }, "converters" : [ ], "condition_type" : "NONE", "condition_value" : "", "order" : 0 }, { "title" : "src_port", "type" : "SPLIT_AND_INDEX", "cursor_strategy" : "COPY", "target_field" : "src_port", "source_field" : "src", "configuration" : { "index" : 2, "split_by" : ":" }, "converters" : [ { "type" : "NUMERIC", "configuration" : {  } } ], "condition_type" : "NONE", "condition_value" : "", "order" : 0 }, { "title" : "src_if", "type" : "SPLIT_AND_INDEX", "cursor_strategy" : "COPY", "target_field" : "src_if", "source_field" : "src", "configuration" : { "index" : 3, "split_by" : ":" }, "converters" : [ ], "condition_type" : "NONE", "condition_value" : "", "order" : 0 }, { "title" : "proto_type", "type" : "SPLIT_AND_INDEX", "cursor_strategy" : "COPY", "target_field" : "proto_type", "source_field" : "proto", "configuration" : { "index" : 1, "split_by" : "/" }, "converters" : [ { "type" : "LOWERCASE", "configuration" : {  } } ], "condition_type" : "NONE", "condition_value" : "", "order" : 0 }, { "title" : "proto_service", "type" : "SPLIT_AND_INDEX", "cursor_strategy" : "COPY", "target_field" : "proto_service", "source_field" : "proto", "configuration" : { "index" : 2, "split_by" : "/" }, "converters" : [ { "type" : "LOWERCASE", "configuration" : {  } } ], "condition_type" : "NONE", "condition_value" : "", "order" : 0 }, { "title" : "timestamp", "type" : "REGEX", "cursor_strategy" : "COPY", "target_field" : "timestamp", "source_field" : "time", "configuration" : { "regex_value" : "(\\d\\d\\d\\d-\\d\\d-\\d\\d\\s\\d\\d:\\d\\d:\\d\\d)" }, "converters" : [ { "type" : "DATE", "configuration" : { "date_format" : "yyyy-MM-dd HH:mm:ss", "time_zone" : "Etc/UTC" } } ], "condition_type" : "NONE", "condition_value" : "", "order" : 0 }, { "title" : "src_hostname", "type" : "SPLIT_AND_INDEX", "cursor_strategy" : "COPY", "target_field" : "src_hostname", "source_field" : "src", "configuration" : { "index" : 4, "split_by" : ":" }, "converters" : [ ], "condition_type" : "REGEX", "condition_value" : "(.*:.*:.*:.*)", "order" : 0 }, { "title" : "dst_hostname", "type" : "SPLIT_AND_INDEX", "cursor_strategy" : "COPY", "target_field" : "dst_hostname", "source_field" : "dst", "configuration" : { "index" : 4, "split_by" : ":" }, "converters" : [ ], "condition_type" : "REGEX", "condition_value" : "(.*:.*:.*:.*)", "order" : 0 } ] } ], "streams" : [ ], "outputs" : [ ], "dashboards" : [ { "title" : "SonicWall - VPN Audit (24h)", "description" : "VPN Connections from last 24 hours", "dashboard_widgets" : [ { "description" : "Failed VPN Connections", "type" : "SEARCH_RESULT_CHART", "cache_time" : 10, "configuration" : { "interval" : "hour", "timerange" : { "type" : "relative", "range" : 86400 }, "query" : "gl2_source_input:\"5b314df3427e2557cdb4d07f\" AND (msg:\"XAUTH Failed with VPN client,  Authentication failure\" OR m:140)" }, "col" : 1, "row" : 4, "height" : 1, "width" : 2 }, { "description" : "Established VPN Connections", "type" : "SEARCH_RESULT_CHART", "cache_time" : 10, "configuration" : { "interval" : "hour", "timerange" : { "type" : "relative", "range" : 86400 }, "query" : "gl2_source_input:\"5b314df3427e2557cdb4d07f\" AND (msg:\"XAUTH Succeeded with VPN client\" OR m:139)" }, "col" : 1, "row" : 1, "height" : 1, "width" : 2 }, { "description" : "Failed VPN Connections", "type" : "SEARCH_RESULT_COUNT", "cache_time" : 10, "configuration" : { "timerange" : { "type" : "relative", "range" : 86400 }, "lower_is_better" : true, "trend" : true, "query" : "gl2_source_input:\"5b314df3427e2557cdb4d07f\" AND (msg:\"XAUTH Failed with VPN client,  Authentication failure\" OR m:140)" }, "col" : 3, "row" : 4, "height" : 1, "width" : 1 }, { "description" : "Established VPN Connections", "type" : "SEARCH_RESULT_COUNT", "cache_time" : 10, "configuration" : { "timerange" : { "type" : "relative", "range" : 86400 }, "lower_is_better" : false, "trend" : true, "query" : "gl2_source_input:\"5b314df3427e2557cdb4d07f\" AND (msg:\"XAUTH Succeeded with VPN client\" OR m:139)" }, "col" : 3, "row" : 1, "height" : 1, "width" : 1 }, { "description" : "Users who successfully connected", "type" : "QUICKVALUES", "cache_time" : 10, "configuration" : { "timerange" : { "type" : "relative", "range" : 86400 }, "field" : "usr", "show_pie_chart" : false, "query" : "gl2_source_input:\"5b314df3427e2557cdb4d07f\" AND (msg:\"XAUTH Succeeded with VPN client\" OR m:139)", "show_data_table" : true }, "col" : 3, "row" : 2, "height" : 2, "width" : 1 }, { "description" : "Users who failed to connect", "type" : "QUICKVALUES", "cache_time" : 10, "configuration" : { "timerange" : { "type" : "relative", "range" : 86400 }, "field" : "usr", "show_pie_chart" : false, "query" : "gl2_source_input:\"5b314df3427e2557cdb4d07f\" AND (msg:\"XAUTH Failed with VPN client, Authentication failure\" OR m:140)", "show_data_table" : true }, "col" : 3, "row" : 5, "height" : 2, "width" : 1 }, { "description" : "Failed Connection Sources", "type" : "org.graylog.plugins.map.widget.strategy.MapWidgetStrategy", "cache_time" : 10, "configuration" : { "timerange" : { "type" : "relative", "range" : 86400 }, "field" : "src_ip_geolocation", "query" : "gl2_source_input:\"5b314df3427e2557cdb4d07f\" AND (msg:\"XAUTH Failed with VPN client, Authentication failure\" OR m:140)" }, "col" : 1, "row" : 5, "height" : 2, "width" : 2 }, { "description" : "Established Connection Sources", "type" : "org.graylog.plugins.map.widget.strategy.MapWidgetStrategy", "cache_time" : 10, "configuration" : { "timerange" : { "type" : "relative", "range" : 86400 }, "field" : "src_ip_geolocation", "query" : "gl2_source_input:\"5b314df3427e2557cdb4d07f\" AND (msg:\"XAUTH Succeeded with VPN client\" OR m:139)" }, "col" : 1, "row" : 2, "height" : 2, "width" : 2 }, { "description" : "Established Connection IPs", "type" : "QUICKVALUES", "cache_time" : 10, "configuration" : { "timerange" : { "type" : "relative", "range" : 86400 }, "field" : "src_ip", "show_pie_chart" : true, "query" : "gl2_source_input:\"5b314df3427e2557cdb4d07f\" AND (msg:\"XAUTH Succeeded with VPN client\" OR m:139)", "show_data_table" : true }, "col" : 4, "row" : 1, "height" : 3, "width" : 1 }, { "description" : "Failed Connection IPs", "type" : "QUICKVALUES", "cache_time" : 10, "configuration" : { "timerange" : { "type" : "relative", "range" : 86400 }, "field" : "src_ip", "show_pie_chart" : true, "query" : "gl2_source_input:\"5b314df3427e2557cdb4d07f\" AND (msg:\"XAUTH Failed with VPN client, Authentication failure\" OR m:140)", "show_data_table" : true }, "col" : 4, "row" : 4, "height" : 3, "width" : 1 } ] } ], "grok_patterns" : [ ], "lookup_tables" : [ ], "lookup_caches" : [ ], "lookup_data_adapters" : [ ] }
```

For readability:
```
{ "_id" : ObjectId("5b33c11a427e2557cdb77806"),
 "name" : "Dell SonicWall",
 "description" : "bla bla bla",
 "inputs" : [ { "title" : "SonicWall",
 "configuration" : { "override_source" : null,
 "recv_buffer_size" : 26214400,
 "bind_address" : "0.0.0.0",
 "port" : 1515 },
 "static_fields" : {  },
 "type" : "org.graylog2.inputs.raw.udp.RawUDPInput",
 "global" : true,
 "extractors" : [ { "title" : "Garbage Cleanup and KVP",
 "type" : "REGEX_REPLACE",
 "cursor_strategy" : "COPY",
 "target_field" : "message",
 "source_field" : "message",
 "configuration" : { "regex" : "^<\\d+\\>(.*)",
 "replacement" : "$1",
 "replace_all" : true },
 "converters" : [ { "type" : "TOKENIZER",
 "configuration" : {  } },
...
```

I see now that when I trimmed the description down I must have deleted the category line  as you suspected and as the query confirmed.

This is the only custom content pack I have uploaded.

What do you suggest to resolve this? Edit/delete this entry in the db?

**Comment by joschi** [comment]
> What do you suggest to resolve this? Edit/delete this entry in the db?

Yes, either add a "category" field (type string) or remove the invalid content pack.

**Comment by joschi** [comment]
Given that we'll completely rewrite the content packs functionality in Graylog 3.0.0 and it's not a severe or critical bug, I'll close this issue.
