### ISSUE TITLE
org.graylog2.alerts.AlertConditionFactory - Could not load alert condition '邮件报警' <ee25fba0-ad5f-4a6f-a4f6-9921889bb847>, invalid configuration detected.

### ISSUE THREAD

**Issue by ZhangKe4042602** [Graylog2/graylog2-server#4883]
**I add a graylog AlertCondition "邮件报警" to test graylog plugin alert notify.but when i delete this alertCondition after done test.graylog service log always print error info like this:**
`2018-07-04 02:45:12,150 ERROR: org.graylog2.alerts.AlertConditionFactory - Could not load alert condition '邮件报警' <ee25fba0-ad5f-4a6f-a4f6-9921889bb847>, invalid configuration detected.
2018-07-04 02:45:12,150 ERROR: org.graylog2.streams.StreamServiceImpl - Skipping alert condition.
org.graylog2.plugin.configuration.ConfigurationException: Mandatory configuration field query is missing or has the wrong data type
	at org.graylog2.plugin.configuration.ConfigurationRequest.check(ConfigurationRequest.java:117) ~[graylog.jar:?]
	at org.graylog2.alerts.AlertConditionFactory.createAlertCondition(AlertConditionFactory.java:63) ~[graylog.jar:?]
	at org.graylog2.alerts.AlertServiceImpl.fromPersisted(AlertServiceImpl.java:170) ~[graylog.jar:?]
	at org.graylog2.streams.StreamServiceImpl.getAlertConditions(StreamServiceImpl.java:285) [graylog.jar:?]
	at org.graylog2.periodical.AlertScannerThread.doRun(AlertScannerThread.java:55) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
`

 
 **How can i prevent graylog service log always print this error?**

 
  
 Graylog Version:2.4.0

**Comment by joschi** [comment]
@ZhangKe4042602 How exactly did you delete the alert condition?
Are there any other error messages in the logs of your Graylog node(s)?
Does restarting the Graylog node(s) stop the message?

**Comment by joschi** [comment]
@ZhangKe4042602 Any updates?
