### ISSUE TITLE
Document size of 87555722 is larger than maximum of 16793600. 

### ISSUE THREAD

**Issue by Grokon** [Graylog2/graylog2-server#4899]
## Context

 [Issue from 4231](https://github.com/Graylog2/graylog2-server/issues/4231)

I have this issue too. I collect log with collector-sidecar and on that server has error:
"[UpdateRegistration] Bad response from Graylog server: 500 Internal Server Error"
in graylog error:

"ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
org.bson.BsonSerializationException: Document size of 87555722 is larger than maximum of 16793600.
"
I parse /var/log and have folder with many little files (>50k) and I need parse it too

## Your Environment

* Graylog Version: 2.4.5
* Elasticsearch Version: 5.6.10
* MongoDB Version: 4
* Operating System: debian 9
* Browser version:

**Comment by joschi** [comment]
@Grokon Please post the complete logs of your Graylog node or at least the complete error message including the stack trace.

**Comment by mariussturm** [comment]
@Grokon also keep in mind that the `list_log_file` option of the sidecar can create very large documents if you have thousands of files in `/var/log`. This is just a status option and can be disabled. The log collection itself keeps on working if you limit the file list or disable it completely.

**Comment by Grokon** [comment]
@joschi error in logs:
```
2018-07-10 11:28:13,083 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
org.bson.BsonSerializationException: Document size of 87555722 is larger than maximum of 16793600.
        at org.bson.BsonBinaryWriter.backpatchSize(BsonBinaryWriter.java:375) ~[graylog.jar:?]
        at org.bson.BsonBinaryWriter.doWriteEndArray(BsonBinaryWriter.java:143) ~[graylog.jar:?]
        at org.bson.AbstractBsonWriter.writeEndArray(AbstractBsonWriter.java:348) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.encodeIterable(DBObjectCodec.java:273) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:200) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.encodeMap(DBObjectCodec.java:222) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:198) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:130) ~[graylog.jar:?]
        at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:61) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29) ~[graylog.jar:?]
        at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.writeValue(BsonDocumentCodec.java:136) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:115) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:41) ~[graylog.jar:?]
        at com.mongodb.connection.RequestMessage.addDocument(RequestMessage.java:240) ~[graylog.jar:?]
        at com.mongodb.connection.RequestMessage.addDocument(RequestMessage.java:192) ~[graylog.jar:?]
        at com.mongodb.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:58) ~[graylog.jar:?]
        at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:147) ~[graylog.jar:?]
        at com.mongodb.connection.CommandProtocol.sendMessage(CommandProtocol.java:179) ~[graylog.jar:?]
        at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:104) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:176) ~[graylog.jar:?]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216) ~[graylog.jar:?]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:153) ~[graylog.jar:?]
        at com.mongodb.operation.FindAndReplaceOperation$1.call(FindAndReplaceOperation.java:335) ~[graylog.jar:?]
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:424) ~[graylog.jar:?]
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:415) ~[graylog.jar:?]
        at com.mongodb.operation.FindAndReplaceOperation.execute(FindAndReplaceOperation.java:331) ~[graylog.jar:?]
        at com.mongodb.Mongo.execute(Mongo.java:819) ~[graylog.jar:?]
        at com.mongodb.Mongo$2.execute(Mongo.java:802) ~[graylog.jar:?]
        at com.mongodb.DBCollection.findAndModify(DBCollection.java:1931) ~[graylog.jar:?]
        at com.mongodb.DBCollection.findAndModify(DBCollection.java:1795) ~[graylog.jar:?]
        at com.mongodb.DBCollection.findAndModify(DBCollection.java:1764) ~[graylog.jar:?]
        at com.mongodb.DBCollection.findAndModify(DBCollection.java:1711) ~[graylog.jar:?]
        at org.mongojack.JacksonDBCollection.findAndModify(JacksonDBCollection.java:847) ~[graylog.jar:?]
        at org.graylog.plugins.collector.collectors.CollectorServiceImpl.save(CollectorServiceImpl.java:74) ~[?:?]
        at org.graylog.plugins.collector.collectors.rest.CollectorResource.register(CollectorResource.java:146) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

@mariussturm how can I set limit or disable?

**Comment by Grokon** [comment]
have any problems if I can't set "list_log_files"?
