### ISSUE TITLE
After an unclean shutdown, graylog on a restart throws FileAlreadyExistsException

### ISSUE THREAD

**Issue by emanzaman** [Graylog2/graylog2-server#4980]
## Expected Behavior
After an unclean shutdown, the server should not throw FileAlreadyExistsException

## Current Behavior
After an unclean shutdown of Graylog server, the server on a restart throws:
`ServerBootstrap | Could not write PID file: /apps/graylog/graylog-server-service.pid
 java.nio.file.FileAlreadyExistsException: /apps/graylog/graylog-server-service.pid 
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88) ~[?:1.8.0_66]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_66]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_66]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_66]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[?:1.8.0_66]
        at java.nio.file.Files.newOutputStream(Files.java:216) ~[?:1.8.0_66]
        at java.nio.file.Files.write(Files.java:3292) ~[?:1.8.0_66]
        at org.graylog2.bootstrap.ServerBootstrap.savePidFile(ServerBootstrap.java:184) [graylog.jar:?]
        at org.graylog2.bootstrap.ServerBootstrap.beforeStart(ServerBootstrap.java:93) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:188) [graylog.jar:?]
        at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]`

* Graylog Version: 2.4.3
* Elasticsearch Version: 5.6.8
* MongoDB Version: 3.6.2
* Operating System:RHEL7
* Browser version: -

**Comment by jalogisch** [comment]
How did you install Graylog?

Startup scripts handle this, when you run Graylog manually you need to take care of the housekeeping.

In addition the User you run Graylog with must have the UNIX access rights to write the pid file. 

Please provide more input.

**Comment by emanzaman** [comment]
Yes Graylog is installed manually.
The user that is used to run Graylog has the UNIX access rights to write the pid file.
Also when I run Graylog second time, this error doesn't occur.

**Comment by jalogisch** [comment]
That behaviour is true and can't be changed. Unclean Shutdown will leave some traces, including the pid file. 

The first start then will clean everything up and the second is successfull. 

We did not see this as a bug, cause the system might be broken and need attention.
