### ISSUE TITLE
Unable to persist node ID

### ISSUE THREAD

**Issue by Jeff-Ren** [Graylog2/graylog2-server#5026]
360) Error injecting constructor, org.graylog2.plugin.system.NodeIdPersistenceException: **Unable to persist node ID**
  at org.graylog2.plugin.ServerStatus.<init>(ServerStatus.java:71)
  at org.graylog2.shared.bindings.ServerStatusBindings.configure(ServerStatusBindings.java:41)
  while locating org.graylog2.plugin.ServerStatus
    for the 1st parameter of org.graylog2.shared.bindings.providers.NodeIdProvider.<init>(NodeIdProvider.java:32)
  while locating org.graylog2.shared.bindings.providers.NodeIdProvider
  while locating org.graylog2.plugin.system.NodeId
    for the 3rd parameter of org.graylog2.cluster.ClusterConfigServiceImpl.<init>(ClusterConfigServiceImpl.java:66)
  while locating org.graylog2.cluster.ClusterConfigServiceImpl
  at org.graylog2.bindings.ServerBindings.bindSingletons(ServerBindings.java:174)
  while locating org.graylog2.plugin.cluster.ClusterConfigService
    for the 4th parameter of org.graylog2.indexer.indexset.MongoIndexSetService.<init>(MongoIndexSetService.java:58)
  while locating org.graylog2.indexer.indexset.MongoIndexSetService
  while locating org.graylog2.indexer.indexset.IndexSetService
    for the 5th parameter of org.graylog2.streams.StreamServiceImpl.<init>(StreamServiceImpl.java:94)
  while locating org.graylog2.streams.StreamServiceImpl
  while locating org.graylog2.streams.StreamService
    for the 1st parameter of org.graylog2.periodical.AlertScannerThread.<init>(AlertScannerThread.java:40)
  while locating org.graylog2.periodical.AlertScannerThread
  while locating org.graylog2.plugin.periodical.Periodical annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=134, type=MULTIBINDER, keyType=)
  at org.graylog2.shared.bindings.SharedPeriodicalBindings.configure(SharedPeriodicalBindings.java:30) (via modules: org.graylog2.shared.bindings.SharedPeriodicalBindings -> com.google.inject.multibindings.Multibinder$RealMultibinder)
  while locating java.util.Set<org.graylog2.plugin.periodical.Periodical>
    for the 3rd parameter of org.graylog2.shared.initializers.PeriodicalsService.<init>(PeriodicalsService.java:45)
  at org.graylog2.shared.initializers.PeriodicalsService.class(PeriodicalsService.java:36)
  while locating org.graylog2.shared.initializers.PeriodicalsService
Caused by: org.graylog2.plugin.system.NodeIdPersistenceException: Unable to persist node ID
        at org.graylog2.plugin.system.NodeId.generate(NodeId.java:78)
        at org.graylog2.plugin.system.NodeId.readOrGenerate(NodeId.java:56)
        at org.graylog2.plugin.system.NodeId.<init>(NodeId.java:42)
        at org.graylog2.plugin.ServerStatus.<init>(ServerStatus.java:73)

**Comment by Jeff-Ren** [comment]
After using it for half a month, there was no problem, and the redeployment went wrong

**Comment by jalogisch** [comment]
You successfully ignored any template we have implemented for a reason. In addition you did not include any additional information that might be needed to help you with your issue.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
