### ISSUE TITLE
Graylog unable to connect to AWS Elasticsearch cluster

### ISSUE THREAD

**Issue by DeepthiReddy23** [Graylog2/graylog2-server#5034]
I have setup the graylog-server following the instructions here: http://docs.graylog.org/en/2.4/pages/installation/os/ubuntu.html (ubuntu 16.04). Everything works fine. Now, I would like to point the graylog-server to an AWS ES cluster. The only configuration I have changed is this in server.conf -

elasticsearch_hosts = https://vpc-aws-es-cluster.com:443

And this started throwing the below error on web interface -

Could not load field information
Loading field information failed with status: cannot GET https://graylog.xxxx/api/system/fields (500)

This is what  I see in the graylog server logs:
```
ERROR [ConfigurationManagementPeriodical] Error while running migration <V20170607164210_MigrateReopenedIndicesToAliases{2017-06-07T16:42:10Z}>
org.graylog2.indexer.ElasticsearchException: Couldn't read cluster state for reopened indices [graylog_*]
        at org.graylog2.indexer.cluster.jest.JestUtils.specificException(JestUtils.java:95) ~[graylog.jar:?]
        at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:57) ~[graylog.jar:?]
        at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:62) ~[graylog.jar:?]
        at org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases.getReopenedIndices(V20170607164210_MigrateReopenedIndicesToAliases.java:88) ~[graylog.jar:?]
        at org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases.getReopenedIndices(V20170607164210_MigrateReopenedIndicesToAliases.java:135) ~[graylog.jar:?]
        at org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases.lambda$upgrade$0(V20170607164210_MigrateReopenedIndicesToAliases.java:78) ~[graylog.jar:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_181]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
        at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[?:1.8.0_181]
        at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_181]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_181]
        at org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases.upgrade(V20170607164210_MigrateReopenedIndicesToAliases.java:80) ~[graylog.jar:?]
        at org.graylog2.periodical.ConfigurationManagementPeriodical.doRun(ConfigurationManagementPeriodical.java:43) [graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2018-08-29T19:26:01.772Z INFO  [JerseyService] Enabling CORS for HTTP endpoint
2018-08-29T19:26:11.859Z INFO  [NetworkListener] Started listener bound to [127.0.0.1:9000]
2018-08-29T19:26:11.860Z INFO  [HttpServer] [HttpServer] Started.
2018-08-29T19:26:11.860Z INFO  [JerseyService] Started REST API at <http://127.0.0.1:9000/api/>
2018-08-29T19:26:11.861Z INFO  [JerseyService] Started Web Interface at <http://127.0.0.1:9000/>
2018-08-29T19:26:11.862Z INFO  [ServerBootstrap] Services started, startup times in ms: {OutputSetupService [RUNNING]=85, BufferSynchronizerService [RUNNING]=85, KafkaJournal [RUNNING]=102, InputSetupService [RUNNING]=148, StreamCacheService [RUNNING]=196, ConfigurationEtagService [RUNNING]=199, JournalReader [RUNNING]=216, PeriodicalsService [RUNNING]=268, LookupTableService [RUNNING]=363, JerseyService [RUNNING]=10687}
```

Below is the version information -
* Graylog Version: 2.4
* Elasticsearch Version: 5.6

Tried with ES version 2.3 aswell, still the same issue.

Please let me know if I need to make any other configuration changes. 
I do not find clear documentation on integration with AWS ES cluster. Please point to one if it is existing already.

Thank you.

**Comment by jalogisch** [comment]
Did you checked if your Graylog is able to connect to the AWS Elasticsearch cluster? You can use `curl` to check that - If that is possible we would need to get the complete `server.log` from the startup to see the error.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by DeepthiReddy23** [comment]
Yes, I am able to curl the ES cluster and print the health status as follows -
```
{
  "cluster_name" : "xxxx",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 4,
  "active_shards" : 4,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```
I have attached the complete server.log file with this comment.
[server.log](https://github.com/Graylog2/graylog2-server/files/2335015/server.log)

Thank you.
