### ISSUE TITLE
Gmail SMTP relay not working via TLS

### ISSUE THREAD

**Issue by razvanphp** [Graylog2/graylog2-server#5098]
## Expected Behavior
We're trying to setup google gmail smtp relay for graylog alert notifications, but for some reason it does not work.

## Current Behavior
gmail is configured to allow the static NAT IP address without authentication, but we get the following ambiguous error:
```
2018-09-12T16:08:51.544Z ERROR [EmailAlarmCallback] Alarm callback has email recipients and is triggered, but sending emails failed
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp-relay.gmail.com:587
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469) ~[graylog.jar:?]
        at org.apache.commons.mail.Email.send(Email.java:1496) ~[graylog.jar:?]
        at org.graylog2.alerts.FormattedEmailAlertSender.sendEmail(FormattedEmailAlertSender.java:202) ~[graylog.jar:?]
        at org.graylog2.alerts.FormattedEmailAlertSender.sendEmails(FormattedEmailAlertSender.java:227) ~[graylog.jar:?]
        at org.graylog2.alerts.FormattedEmailAlertSender.sendEmails(FormattedEmailAlertSender.java:162) ~[graylog.jar:?]
        at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:105) [graylog.jar:?]
        at org.graylog2.rest.resources.alarmcallbacks.AlarmCallbacksResource.test(AlarmCallbacksResource.java:150) [graylog.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: javax.mail.MessagingException: Can't send command to SMTP host
        at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2324) ~[graylog.jar:?]
        at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2311) ~[graylog.jar:?]
        at com.sun.mail.smtp.SMTPTransport.close(SMTPTransport.java:1351) ~[graylog.jar:?]
        at javax.mail.Transport.send0(Transport.java:257) ~[graylog.jar:?]
        at javax.mail.Transport.send(Transport.java:124) ~[graylog.jar:?]
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459) ~[graylog.jar:?]
        ... 33 more
Caused by: java.net.SocketException: Connection closed by remote host
        at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1565) ~[?:1.8.0_181]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71) ~[?:1.8.0_181]
        at com.sun.mail.util.TraceOutputStream.write(TraceOutputStream.java:138) ~[graylog.jar:?]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_181]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_181]
        at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2322) ~[graylog.jar:?]
        at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2311) ~[graylog.jar:?]
        at com.sun.mail.smtp.SMTPTransport.close(SMTPTransport.java:1351) ~[graylog.jar:?]
        at javax.mail.Transport.send0(Transport.java:257) ~[graylog.jar:?]
        at javax.mail.Transport.send(Transport.java:124) ~[graylog.jar:?]
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459) ~[graylog.jar:?]
        ... 33 more
```
we also tried with SSL true, but we get a different error.

## Current configuration
```
transport_email_enabled = true
transport_email_hostname = smtp-relay.gmail.com
transport_email_port = 587
transport_email_use_auth = false
transport_email_use_tls = true
transport_email_use_ssl = false
transport_email_auth_username = graylog@aaa.de
transport_email_auth_password = nopassword
transport_email_subject_prefix = ['graylog']
transport_email_from_email = graylog@aaa.de
```

## Your Environment

* Graylog Version: 2.4.6+ceaa7e4
* Elasticsearch Version: 5.5.2
* MongoDB Version: 3.2.11
* Operating System: Debian 9, kernel 4.9.0-7-amd64
* Browser version: Latest Chrome

**Comment by jalogisch** [comment]
When you provide `auth_username` and `auth_password` Graylog will try to use those credentials for authentication. 

You might want to look into this on the Community Board: https://community.graylog.org/t/how-to-send-email-alerts-using-gmail/4103

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by razvanphp** [comment]
My bad, IP whitelist was not saved correctly in the google console, I can confirm it works with configuration posted above.
