### ISSUE TITLE
Fix content pack dependency resolving for input entities

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#5105]
Every content pack facade needs to handle the resolving of its own dependencies to make sure the content pack service includes all dependencies when generating a content pack.

The [InputFacade](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java) is currently not doing this for lookup table extractors and converters. A lookup table extractor/converter references a lookup table so the InputFacade needs to make sure to include the lookup table in the dependency graph.

That basically means InputFacade needs to implement [EntityFacade#resolveNativeEntity() and EntityFacade#resolveForInstallation()](https://github.com/Graylog2/graylog2-server/blob/0dbe6f659e79e945662658bc9c2cd468c8922b8c/graylog2-server/src/main/java/org/graylog2/contentpacks/facades/EntityFacade.java#L108-L134) to put the required lookup table into the dependency graph.

The [LookupTableFacade](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java) is basically doing the same for caches and data adapters and can server as an example on how to do this.

**Comment by bernd** [comment]
Due to this bug, installing a content pack with an input that has a lookup table converter and/or extractor doesn't work right now and throws the following error:

```
2018-09-13 18:51:07,854 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
org.graylog2.contentpacks.exceptions.ContentPackException: Failed to install content pack <a0de9fa3-a860-8cfe-08ec-911f513d07c3/1>
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:147) ~[classes/:?]
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:98) ~[classes/:?]
	at org.graylog2.rest.resources.system.contentpacks.ContentPackResource.installContentPack(ContentPackResource.java:273) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.1.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.28.jar:2.3.28]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [metrics-core-4.0.2.jar:4.0.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.RuntimeException: Couldn't create extractors
	at org.graylog2.contentpacks.facades.InputFacade.decode(InputFacade.java:223) ~[classes/:?]
	at org.graylog2.contentpacks.facades.InputFacade.createNativeEntity(InputFacade.java:185) ~[classes/:?]
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:138) ~[classes/:?]
	... 29 more
Caused by: java.lang.IllegalStateException: Configured lookup table <dns-a> doesn't exist
	at org.graylog2.inputs.extractors.LookupTableExtractor.<init>(LookupTableExtractor.java:57) ~[classes/:?]
	at org.graylog2.inputs.extractors.ExtractorFactory.factory(ExtractorFactory.java:72) ~[classes/:?]
	at org.graylog2.contentpacks.facades.InputFacade.addExtractor(InputFacade.java:308) ~[classes/:?]
	at org.graylog2.contentpacks.facades.InputFacade.createExtractors(InputFacade.java:273) ~[classes/:?]
	at org.graylog2.contentpacks.facades.InputFacade.decode(InputFacade.java:221) ~[classes/:?]
	at org.graylog2.contentpacks.facades.InputFacade.createNativeEntity(InputFacade.java:185) ~[classes/:?]
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:138) ~[classes/:?]
	... 29 more
```
