### ISSUE TITLE
Sync behaviour of GELF plugin and Graylog (re: has empty mandatory "short_message")

### ISSUE THREAD

**Issue by hangstl** [Graylog2/graylog2-server#5171]
My setup: Logstash -> GELF -> Graylog 2.4.6

Some of my logfiles contain lines with only whitspace characters (TAB + end of line). This leads to lots of "has empty mandatory "short_message" field" Exceptions in Graylog.

imho this is a bug, because there _is_ a message (the TAB character). GelfCodec.java has this line here:
```
if (StringUtils.isBlank(shortMessageNode.asText()) && StringUtils.isBlank(messageNode.asText())) {
                throw new IllegalArgumentException(prefix + "has empty mandatory \"short_message\" field.");
}
```

Would it make sense to change StringUtils.isBlank() to StringUtils.isEmpty()

If not, I would appreciate to sync the behaviour of the GELF Plugin and the GelfCodec in Graylog. I mean, why send messages to Graylog if it rejects it anyway?

**Comment by jalogisch** [comment]
REF https://community.graylog.org/t/errors-empty-mandatory-short-message-field/7060

**Comment by eduault** [comment]
I have the same problem with my Graylog 2.4.6 server on Linux.
The problematic messages are probably sent by Graylog itself (or a plugin).

**Comment by eduault** [comment]
In GELFMessageTest.java, GELF_JSON has no "short_message".

**Comment by piellick** [comment]
Hi everyone,

there is a workaround to this before waiting the bug correction ?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by alitoufighi** [comment]
Any updates?

**Comment by DilaraSSS** [comment]
I have the same problem with my Graylog 4.0.11+e4e88a4, codename Noir. Any update

Here are the logs :

`2022-01-14 09:48:04,082 ERROR   [DecodingProcessor] - Unable to decode raw message RawMessage{id=119053b1-751f-11ec-96f4-7af235b1e3ab, journalOffset=198692353, codec=gelf, payloadSize=514, timestamp=2022-01-14T09:48:04.075Z, remoteAddress=/10.40.0.0:19396} on input <607e93166eddf7582244c00f>. - {}
2022-01-14 09:48:04,082 ERROR   [DecodingProcessor] - Error processing message RawMessage{id=119053b1-751f-11ec-96f4-7af235b1e3ab, journalOffset=198692353, codec=gelf, payloadSize=514, timestamp=2022-01-14T09:48:04.075Z, remoteAddress=/10.40.0.0:19396} - {}
java.lang.IllegalArgumentException: GELF message <119053b1-751f-11ec-96f4-7af235b1e3ab> (received from <10.40.0.0:19396>) has empty mandatory "short_message" field.
	at org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage(GelfCodec.java:258) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:140) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:149) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:90) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:90) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:47) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]`

**Comment by storm1kk** [comment]
I have a lot of such messages too. I read somewhere that it's kinda a white noise. But can we do something with this? It bothers me when I see [ERROR]...
