### ISSUE TITLE
Messages being dropped with exception

### ISSUE THREAD

**Issue by profhase** [Graylog2/graylog2-server#5327]
We are sending messages from windows servers to graylog using the `nxlog` `gelf tcp` output.
The messages are not being processed by graylog and we can see the following message in the graylog log:

```
 graylog_1_255b69ff749b | com.fasterxml.jackson.core.JsonParseException: Unexpected character ('�' (code 65533 / 0xfffd)): Expected space separating root-level values
 [71B blob data]
 [129B blob data]
 [186B blob data]
 graylog_1_255b69ff749b |         at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[graylog.jar:?]
 graylog_1_255b69ff749b |         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[graylog.jar:?]
 graylog_1_255b69ff749b |         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[graylog.jar:?]
 graylog_1_255b69ff749b |         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:503) ~[graylog.jar:?]
 graylog_1_255b69ff749b |         at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._verifyRootSpace(ReaderBasedJsonParser.java:1668) ~[graylog.jar:?]
 graylog_1_255b69ff749b |         at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parsePosNumber(ReaderBasedJsonParser.java:1311) ~[graylog.jar:?]
 graylog_1_255b69ff749b |         at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:746) ~[graylog.jar:?]
 graylog_1_255b69ff749b |         at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850) ~[graylog.jar:?]
 graylog_1_255b69ff749b |         at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[graylog.jar:?]
 graylog_1_255b69ff749b |         at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2397) ~[graylog.jar:?]
 graylog_1_255b69ff749b |         at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:127) [graylog.jar:?]
 graylog_1_255b69ff749b |         at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:150) [graylog.jar:?]
 graylog_1_255b69ff749b |         at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
 graylog_1_255b69ff749b |         at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
 graylog_1_255b69ff749b |         at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
 graylog_1_255b69ff749b |         at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
 graylog_1_255b69ff749b |         at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
 graylog_1_255b69ff749b |         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
 graylog_1_255b69ff749b | 2018-11-29 12:20:41,324 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Unable to decode raw message RawMessage{id=2ff6868c-f3d1-11e8-be89-0242ac1a0004, journalOffset=442395, codec=gelf, payloadSize=156, timestamp=2018-11-29T12:20:41.320Z, remoteAddress=/123.123.123.123:58094} on input <5bd72e8fd497d20001697617>.

```

## Expected Behavior
- We would like to know what the actual error is
- The message should somehow end up in the database

## Current Behavior

Messages just disappear

## Steps to Reproduce (for bugs)

Send messages with nxlog from windows servers via `gelf tcp` (sorry, hard to tell)

## Your Environment
All dockerized:

* Graylog Version: 2.4.6-1
* Elasticsearch Version: 5.6.3
* MongoDB Version: 3
* Operating System: Docker on CentOs
* Browser version: Irrelevant

**Comment by radykal-com** [comment]
As the first line of the error says, it seems the log you are sending contains invalid characters that graylog cannot process, in this case it's the ('�' (code 65533 / 0xfffd)). Not sure about what are the valid char-sets allowed by Graylog, but if you are able to replace this special char from the system generating the log, Graylog will be able to process them

**Comment by jalogisch** [comment]
@profhase we would need to have the message you actually want to send to Graylog to be able to verify the issue. 

You could, for example, write the output in addition to a log file and provide that to us.

**Comment by profhase** [comment]
@jalogisch thanks, apparently it was an issue in nxlog, with different config options the messages are arriving now. I will close the issue.
