### ISSUE TITLE
Index rotation fails with "couldn't point deflector to a new index", Incorrect HTTP method for /_all/_aliases

### ISSUE THREAD

**Issue by benvanstaveren** [Graylog2/graylog2-server#5370]
Index rotator can't find aliases for indices after upgrading to Graylog 2.5 and updating ES from 5.6.13 to 6.5.1

## Expected Behavior

Index rotation finds aliases and does the proper thing

## Current Behavior

Index rotator can't find aliases with following error message:

```
2018-12-04T14:06:27.360Z ERROR [IndexRotationThread] Couldn't point deflector to a new index
org.graylog2.indexer.ElasticsearchException: Couldn't collect indices for alias microservices_deflector

"Incorrect HTTP method for uri [/_all/_aliases] and method [GET], allowed: [PUT]"
        at org.graylog2.indexer.cluster.jest.JestUtils.specificException(JestUtils.java:95) ~[graylog.jar:?]
        at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:57) ~[graylog.jar:?]
        at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:62) ~[graylog.jar:?]
        at org.graylog2.indexer.indices.Indices.aliasTarget(Indices.java:326) ~[graylog.jar:?]
        at org.graylog2.indexer.MongoIndexSet.getActiveWriteIndex(MongoIndexSet.java:204) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexRotationThread.checkAndRepair(IndexRotationThread.java:144) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:76) ~[graylog.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_181]
        at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```

## Possible Solution

Use the right method to find aliases on ES 6.5 :)

## Context

This has rather negatively impacted our production cluster, and would've expected this to be tested before 2.5 was released...

## Your Environment

Graylog 2.5
Elasticsearch 6.5.1

**Comment by bernd** [comment]
@benvanstaveren Thank you for the report!

We can't reproduce the issue at the moment. Neither with manual index rotation nor with automatic index rotation.

Can you please send us a bit more log lines before and after this error? That will help us trying to reproduce the problem.
Thank you!

**Comment by bernd** [comment]
@benvanstaveren Please check that you actually restarted your Graylog master with 2.5.0.

The `GET /_all/_aliases` should not happen in 2.5 because we changed it to be `GET /_all/_alias`.

**Comment by benvanstaveren** [comment]
@bernd oddly enough, it seems I didn't in fact upgrade to 2.5 - Ansible said yes, but turned out it was no. I did a manual apt-update and apt upgrade run and took it to 2.5.0-3 - now all is fine.

My bad, I was under the distinct impression I had upgraded all nodes. Issue can be closed.

**Comment by bernd** [comment]
@benvanstaveren Thank you for the feedback! Great that it works for you now!
