### ISSUE TITLE
Graylog tries to create deflector aliases as indexes on restart / or faulty log message

### ISSUE THREAD

**Issue by jdagemark** [Graylog2/graylog2-server#5393]
## Current Behavior
After each restart of elastic we get messages similar to this one in the graylog server.log

2018-12-03T13:41:11.195+01:00 WARN [Messages] Failed to index message: index=<del3month_deflector> id= error=<{“type”:“invalid_index_name_exception”,“reason”:“Invalid index name [del3month_deflector], already exists as alias”,“index_uuid”:“na”,“index”:“del3month_deflector”}>

It’s like graylog tries to create the deflector aliases as indexes but fails due to the fact that they already exists as aliases.

I posted a question in the forum (https://community.graylog.org/t/graylog-tries-to-create-deflector-aliases-as-indexes-on-restart/7876) and was asked to file a bug so here I am.

## Expected Behavior
A log message describing what the problem actually is in case it's a faulty log message.

## Steps to Reproduce (for bugs)
1. In my system all I need to do to recreate the bug is to restart elasticsearch. 

## Your Environment

* Single node system
* Graylog Version: 2.4.6+ceaa7e4
* Elasticsearch Version: 5.6.11
* Operating System: CentOS 7 (Linux 3.10.0-862.11.6.el7.x86_64)
* JVM: Oracle Corporation 1.8.0_181 on 

Thanks for your help and let me know if you need any additional information.

**Comment by edmundoa** [comment]
I could reproduce something similar to this (Graylog creating the deflector alias as index) while testing 3.0.0-rc.1 as follows:

1. Create an input on your Graylog server and start sending data there
1. Stop Graylog
1. Delete your ES indices, delete the deflector alias, or start using a new ES prefix
1. Optionally delete the `index_ranges` collection in MongoDB
1. Start the Graylog server as follower (not master)
1. After a little while, Graylog creates a deflector index on ES and starts writing data into it. 

Once a master node joins the cluster, it will see that something is wrong with the deflector and will try to fix it with no success.

These are the logs from the master node (I found nothing relevant in the follower node):
```
2019-02-05 17:42:21,001 ERROR: org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy - Could not find current deflector target of index set <Default index set>. Aborting.
org.graylog2.indexer.NoTargetIndexException: Couldn't get newest index number for indices [graylog-30-es6_deflector]
        at org.graylog2.indexer.MongoIndexSet.getNewestIndexNumber(MongoIndexSet.java:170) ~[graylog.jar:?]
        at org.graylog2.indexer.MongoIndexSet.getNewestIndex(MongoIndexSet.java:146) ~[graylog.jar:?]
        at org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy.rotate(AbstractRotationStrategy.java:61) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexRotationThread.checkForRotation(IndexRotationThread.java:113) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:77) ~[graylog.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_191]
        at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2019-02-05 17:42:21,083 WARN : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Active write index for index set "Default index set" (5c4f070ce0015c6de2433d72) doesn't exist yet
2019-02-05 17:42:26,076 WARN : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Active write index for index set "Default index set" (5c4f070ce0015c6de2433d72) doesn't exist yet
2019-02-05 17:42:30,838 ERROR: org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy - Could not find current deflector target of index set <Default index set>. Aborting.
org.graylog2.indexer.NoTargetIndexException: Couldn't get newest index number for indices [graylog-30-es6_deflector]
        at org.graylog2.indexer.MongoIndexSet.getNewestIndexNumber(MongoIndexSet.java:170) ~[graylog.jar:?]
        at org.graylog2.indexer.MongoIndexSet.getNewestIndex(MongoIndexSet.java:146) ~[graylog.jar:?]
        at org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy.rotate(AbstractRotationStrategy.java:61) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexRotationThread.checkForRotation(IndexRotationThread.java:113) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:77) ~[graylog.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_191]
        at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2019-02-05 17:42:31,075 WARN : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Active write index for index set "Default index set" (5c4f070ce0015c6de2433d72) doesn't exist yet
2019-02-05 17:42:35,864 INFO : org.graylog2.periodical.IndexRangesCleanupPeriodical - Skipping index range cleanup because the Elasticsearch cluster is unreachable or unhealthy
2019-02-05 17:42:36,074 WARN : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Active write index for index set "Default index set" (5c4f070ce0015c6de2433d72) doesn't exist yet
```

In the end the only way of fixing the issue is dropping the deflector index from ES while Graylog is stopped and start a master node first.

**Comment by nagaland88** [comment]
same here only way to overcome this is to delete everything and start from scratch

**Comment by jalogisch** [comment]
We have seen that setting `action.auto_create_index` in the configuration file prevent this. 

https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-index_.html#index-creation

We should add this to the Graylog Template for Elasticsearch.

**Comment by dennisoelkers** [comment]
@edmundoa: Would you consider this to be a bug?

**Comment by edmundoa** [comment]
@dennisoelkers for me it is, since the system can end up in a broken state just by starting the wrong node first. Additionally, it's not trivial restoring the system functionality, it requires fiddling around with ES and some Graylog downtime.
I must also said that I discovered the error while testing 3.0 in a multi-node setup, so I wasn't really trying to reproduce this issue at the time, it occurred accidentally.

**Comment by msafdal** [comment]
Hi,

Still experiencing this problem. Even after upgrading to Graylog 3.1.3 and Elasticsearch 6.8.5.

Added this setting to elasticsearch.yml when upgrading to Elasticsearch 6.8.5.
`action.auto_create_index: .watches,.triggered_watches,.watcher-history-*`

Rotated index after upgrade to Graylog 3.1.3 and Elasticsearch 6.8.5:
```
2019-12-02T09:59:56.990+01:00 INFO  [DeflectorResource] Cycling deflector for index set <5aeffdd77d38a60612c569c1>. Reason: REST request.
2019-12-02T09:59:56.992+01:00 INFO  [MongoIndexSet] Cycling from <default_578> to <default_579>.
2019-12-02T09:59:56.992+01:00 INFO  [MongoIndexSet] Creating target index <default_579>.
2019-12-02T09:59:57.038+01:00 INFO  [Indices] Successfully created index template default-template
2019-12-02T09:59:57.136+01:00 INFO  [MongoIndexSet] Waiting for allocation of index <default_579>.
2019-12-02T09:59:57.142+01:00 INFO  [MongoIndexSet] Index <default_579> has been successfully allocated.
2019-12-02T09:59:57.142+01:00 INFO  [MongoIndexSet] Pointing index alias <default_deflector> to new index <default_579>.
2019-12-02T09:59:57.169+01:00 INFO  [SystemJobManager] Submitted SystemJob <1d1ac700-14e2-11ea-b8c1-98f2b326b090> [org.graylog2.indexer.indices.jobs.SetIndexReadOnlyAndCalculateRangeJob]
2019-12-02T09:59:57.169+01:00 INFO  [MongoIndexSet] Successfully pointed index alias <default_deflector> to index <default_579>.
```

Log is still swamped with messages like this:
```
2019-12-02T12:55:13.325+01:00 WARN  [Messages] Failed to index message: index=<default_deflector> id=<8a65ac44-14fa-11ea-ac32-98f2b326b090> error=<{"type":"index_not_found_exception","reason":"no such index and [action.auto_create_index] ([.watches,.triggered_watches,.watcher-history-*]) doesn't match","index_uuid":"_na_","index":"default_deflector"}>
```

Single node system
Graylog Version: 3.1.3+cda805f
Elasticsearch Version: 6.8.5
Operating System: CentOS 7 (Linux 3.10.0-957.1.3.el7.x86_64)
JVM: Oracle Corporation 1.8.0_191

**Comment by commandline-be** [comment]
Same, even
   action.auto_create_index: false 
as documentation says, does not work as expected.

**Comment by draeath** [comment]
Is there a resolution for this, yet? I have a 3.3 single-node system that is reporting these messages.
