### ISSUE TITLE
Graph can lead to OOM and reload loop

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#5559]
If the search contains a graph which produces too many datapoints,
(Resolution: Minutes, Search in all messages)
It will trigger an OOM:

Request: `https://172.16.1.1:9000/api/search/universal/relative/fieldhistogram?query=%2A&range=0&interval=minute&field=packetbeat_dest_stats_net_bytes_total&cardinality=false`
Result:
```
Internal Server Error
Reason
java.lang.OutOfMemoryError: Java heap space

Stacktrace
org.glassfish.jersey.server.ContainerException: java.lang.OutOfMemoryError: Java heap space
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer$ResponseWriter.rethrow(GrizzlyHttpContainer.java:324)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer$ResponseWriter.failure(GrizzlyHttpContainer.java:306)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:509)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space

```

This will lead to an endless reload loop on the search page:

![search-loop](https://user-images.githubusercontent.com/3034831/51481779-ecfed600-1d94-11e9-8584-6b54f95d5431.gif)

* Graylog Version: 3.0-beta3

**Comment by deeshe** [comment]
Refs #5568
