### ISSUE TITLE
Error while running migration during 2.5 to 3.0 upgrade

### ISSUE THREAD

**Issue by razvanphp** [Graylog2/graylog2-server#5737]
## Expected Behavior

The dashboards should look the same after 3.0 upgrade.

## Current Behavior
We get this error in the logs and the dashboards have huge widgets:
```
2019-02-28T13:49:03.346Z ERROR [ConfigurationManagementPeriodical] Error while running migration <V20180214093600_AdjustDashboardPositionToNewResolution{2018-02-14T09:36:00Z}>
java.lang.NullPointerException: null
	at org.graylog2.dashboards.DashboardImpl.getPositions(DashboardImpl.java:94) ~[graylog.jar:?]
	at org.graylog2.migrations.V20180214093600_AdjustDashboardPositionToNewResolution.upgrade(V20180214093600_AdjustDashboardPositionToNewResolution.java:69) ~[graylog.jar:?]
	at org.graylog2.periodical.ConfigurationManagementPeriodical.doRun(ConfigurationManagementPeriodical.java:43) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

## Steps to Reproduce (for bugs)

1. Upgrade from 2.5 version to 3.0 while having dashboard widgets
2. Check the `server.log`

## Your Environment

* Graylog Version: 3.0.0+db6cf59
* Elasticsearch Version: 5.5 (AWS)
* MongoDB Version: v3.2.11
* Operating System: Debian 9
* Browser version: Chrome (latest)

**Comment by edmundoa** [comment]
Hi @razvanphp,

We tested that migration internally before releasing 3.0 and didn't found any issues with it. Would you be so kind as to share with us the contents of the `dashboards` collection in the Graylog setup where you found the problem? Without more details is hard to tell what went wrong.

Thank you!

**Comment by razvanphp** [comment]
hey @edmundoa, I sent you the dump over email. Looking forward for a fix, upgrading production is on hold because of this. Thank you!

**Comment by kmerz** [comment]
@razvanphp could you add the dump to the issue instead? If there is a problem with that, could you send me the dump as well?

**Comment by razvanphp** [comment]
@kmerz forwarded, thanks!

**Comment by kmerz** [comment]
Thanks I found the rouge entry and will see what I can do!

**Comment by razvanphp** [comment]
Is there anything we can do to manually fix this or we need to wait for the new version to be released to upgrade? Thank you for support!
