### ISSUE TITLE
Direct connection to Apache Kafka

### ISSUE THREAD

**Issue by mommys-little-hacker** [Graylog2/graylog2-server#5778]
## Expected Behavior

When creating a Kafka input the user is asked to input *broker* hosts and consumer group

## Current Behavior

When creating any Kafka input, GrayLog requires to input ZooKeeper host address. Essentially, ZooKeeper is not needed to discover and establish connection to Kafka brokers and generally it is acceptable to have it sealed from outside. For example, in my setup ZooKeeper runs inside Kubernetes and it's service is not published, while Kafka's is available from outside by an aliased security protocol. GrayLog approach does not work in this case.

## Possible Solution

Reworking Kafka connection procedure.

## Steps to Reproduce (for bugs)

Consider the following configuration snippet:
```
"advertised.listeners": "EXTERNAL://kafka-broker.example.com:31090"
"listener.security.protocol.map": "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
```

If I publish the ZooKeeper service and attempt to connect to Kafka, connection will fail since the underlying library does not know about this protocol:
```
2019-03-15 15:48:56,231 INFO    [ZookeeperConsumerConnector] - [graylog2_logs-graylog-0.logs-graylog.tiller.svc.cluster.local-1552664935968-9faee038], exception during rebalance  - {}
kafka.common.KafkaException: Failed to parse the broker info from zookeeper: {"listener_security_protocol_map":{"PLAINTEXT":"PLAINTEXT","EXTERNAL":"PLAINTEXT"},"endpoints":["PLAINTEXT://brok
er-kafka-0.broker-kafka-headless.tiller:9092","EXTERNAL://broker-0.kafka.example.com:31090"],"jmx_port":5555,"host":"broker-kafka-0.broker-kafka-headless.tiller","timestamp":"155265732
5894","port":9092,"version":4}
        at kafka.cluster.Broker$.createBroker(Broker.scala:85) ~[graylog.jar:?]
        at kafka.utils.ZkUtils$$anonfun$getCluster$1.apply(ZkUtils.scala:563) ~[graylog.jar:?]
        at kafka.utils.ZkUtils$$anonfun$getCluster$1.apply(ZkUtils.scala:561) ~[graylog.jar:?]
        at scala.collection.Iterator$class.foreach(Iterator.scala:893) ~[graylog.jar:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336) ~[graylog.jar:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[graylog.jar:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[graylog.jar:?]
        at kafka.utils.ZkUtils.getCluster(ZkUtils.scala:561) ~[graylog.jar:?]
        at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1$$anonfun$apply$mcV$sp$1.apply$mcVI$sp(ZookeeperConsumerConnector.scala:635) [graylog.jar:
?]
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160) [graylog.jar:?]
        at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1.apply$mcV$sp(ZookeeperConsumerConnector.scala:627) [graylog.jar:?]
        at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1.apply(ZookeeperConsumerConnector.scala:627) [graylog.jar:?]
        at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1.apply(ZookeeperConsumerConnector.scala:627) [graylog.jar:?]
        at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33) [graylog.jar:?]
        at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:626) [graylog.jar:?]
        at kafka.consumer.ZookeeperConsumerConnector.kafka$consumer$ZookeeperConsumerConnector$$reinitializeConsumer(ZookeeperConsumerConnector.scala:967) [graylog.jar:?]
        at kafka.consumer.ZookeeperConsumerConnector$WildcardStreamsHandler.<init>(ZookeeperConsumerConnector.scala:1001) [graylog.jar:?]
        at kafka.consumer.ZookeeperConsumerConnector.createMessageStreamsByFilter(ZookeeperConsumerConnector.scala:163) [graylog.jar:?]
        at kafka.javaapi.consumer.ZookeeperConsumerConnector.createMessageStreamsByFilter(ZookeeperConsumerConnector.scala:101) [graylog.jar:?]
        at kafka.javaapi.consumer.ZookeeperConsumerConnector.createMessageStreamsByFilter(ZookeeperConsumerConnector.scala:105) [graylog.jar:?]
        at org.graylog2.inputs.transports.KafkaTransport.doLaunch(KafkaTransport.java:207) [graylog.jar:?]
        at org.graylog2.plugin.inputs.transports.ThrottleableTransport.launch(ThrottleableTransport.java:76) [graylog.jar:?]
        at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:155) [graylog.jar:?]
        at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.kafka.common.protocol.SecurityProtocol.EXTERNAL
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_181]
        at org.apache.kafka.common.protocol.SecurityProtocol.valueOf(SecurityProtocol.java:27) ~[graylog.jar:?]
        at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:48) ~[graylog.jar:?]
        at kafka.cluster.Broker$$anonfun$1.apply(Broker.scala:73) ~[graylog.jar:?]
        at kafka.cluster.Broker$$anonfun$1.apply(Broker.scala:72) ~[graylog.jar:?]
        at scala.collection.immutable.List.map(List.scala:277) ~[graylog.jar:?]
        at kafka.cluster.Broker$.createBroker(Broker.scala:72) ~[graylog.jar:?]
        ... 29 more
```

## Context

Fetching logs from Kafka in different k8s cluster.

## Your Environment

* Graylog Version: 3.0
* Elasticsearch Version: 6.6
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by arsiesys** [comment]
I confirm, exactly the same issue here, with exactly the same context. As long as I added an EXTERNAL listeners, I can't connect anymore :/.
```Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.kafka.common.protocol.SecurityProtocol.EXTERNAL```

**Comment by ceyhunn** [comment]
Hi @florianvolle, when this feature will be implemented? I think this is important feature, because external access for kafka (advertised listeners) doesn't work with graylog, For Graylog security protocol map must be "plaintext:plaintext".

**Comment by kroepke** [comment]
Hi!

If I understand this correctly,this is referring to supporting newer Kafka client versions, right?

We currently do not have any bandwidth to update this, mostly because we have an internal dependency on some core Kafka parts in the server, which makes updating the input much more complex than it should be. (see #5819)

Can you confirm that the advertised address is something from the newer Kafka clients where they don't require access to Zookeeper anymore?

Thanks,
Kay

**Comment by ceyhunn** [comment]
Hi @kroepke ,
Graylog doesn't support following kafka config: 
"listener.security.protocol.map": PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
Please add this feature, this is important feature

**Comment by jacowessels** [comment]
Is there any workaround for this issue? Also running Kafka on containers with EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT config.

**Comment by arsiesys** [comment]
Hello @jacowessels, you can have a look to this PT https://github.com/Graylog2/graylog2-server/pull/4770
You could try to use the newer version of the kafka api. As the PR is not merged for now, I made a "plugin" version of it (thanks to @muralibasani)  for our own usage to avoid to have "compile" graylog at each new releases :
https://github.com/arsiesys/graylog-kafka-plugin

**Comment by jacowessels** [comment]
Thanks a lot, @arsiesys - also used the plugin and can confirm working now.

**Comment by ceyhunn** [comment]
Hi @arsiesys , I got this error , it doesn't work:
` Attempt to heart beat failed since the group is rebalancing, try to re-join group. - {}`
