### ISSUE TITLE
Notify users about corrupt journal

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#5868]
My laptop just crashed and corrupted my journal.

The node details look like this:

![image](https://user-images.githubusercontent.com/3034831/56095112-c5be2d80-5ed9-11e9-9ec2-fdb497bb74db.png)

I think we should find a way to detect broken kafka journals and make these
kind of errors more prominent.

* Graylog Version: 1a1257fb1

Refs #5005

**Comment by gimmic** [comment]
I just wanted to say we have seen this in a production cluster when a single node had a disk issue, for some reason the queue was set to a negative number but the logic only looks for positive integers? I didn't troubleshoot it directly only heard about it second-hand.

Maybe a solution would be a web-UI button to clear/reset the kafka journal on that node?

**Comment by jalogisch** [comment]
The most common situation is that the Kafka journal is configured with a certain size but the disk does have this space exclusive for Kafka.


```
sudo dd if=/dev/zero of=/media/journal.img bs=1M count=4
sudo mkfs -t ext4 /media/journal.img
sudo mkdir /mnt/graylog-journal/
sudo mount -t auto -o loop /media/journal.img /mnt/graylog-journal/
sudo mkdir /mnt/graylog-journal/kafka
sudo chown graylog:graylog /mnt/graylog-journal/kafka
```

configure Graylog (server.conf) to make use of the new journal ( `message_journal_dir = /mnt/graylog-journal/kafka` ) and create one input in Graylog to make messages ingest via Graylog into Elasticsearch. 

Stop processing (`system / nodes`) that the Journal is used. Wait until the journal consumes all available disk space.

Creates the following entry in the Graylog `server.log`

```
2019-06-04T13:08:25.280+02:00 ERROR [JournallingMessageHandler] Unable to write to journal - retrying
kafka.common.KafkaStorageException: I/O exception in append to log 'messagejournal-0'
	at kafka.log.Log.append(Log.scala:318) ~[graylog.jar:?]
	at org.graylog2.shared.journal.KafkaJournal.flushMessages(KafkaJournal.java:534) ~[graylog.jar:?]
	at org.graylog2.shared.journal.KafkaJournal.write(KafkaJournal.java:515) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.JournallingMessageHandler.writeToJournal(JournallingMessageHandler.java:113) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:96) [graylog.jar:?]
	at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:45) [graylog.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [graylog.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_212]
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60) ~[?:1.8.0_212]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_212]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_212]
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211) ~[?:1.8.0_212]
	at kafka.message.ByteBufferMessageSet.writeTo(ByteBufferMessageSet.scala:160) ~[graylog.jar:?]
	at kafka.log.FileMessageSet.append(FileMessageSet.scala:229) ~[graylog.jar:?]
	at kafka.log.LogSegment.append(LogSegment.scala:85) ~[graylog.jar:?]
	at kafka.log.Log.append(Log.scala:360) ~[graylog.jar:?]
	... 9 more
```

Restart Graylog with the corrupt journal does not show any of that in the log:

```
2019-06-04T13:09:31.067+02:00 INFO  [KafkaJournal] Initialized Kafka based journal at /mnt/graylog-journal/kafka
```

As long as the journal disk does not have enough space Graylog logs:

```
2019-06-04T13:11:14.728+02:00 ERROR [JournallingMessageHandler] Unable to write to journal - retrying with exponential back-off
kafka.common.KafkaStorageException: I/O exception in append to log 'messagejournal-0'
        at kafka.log.Log.append(Log.scala:318) ~[graylog.jar:?]
        at org.graylog2.shared.journal.KafkaJournal.flushMessages(KafkaJournal.java:534) ~[graylog.jar:?]
        at org.graylog2.shared.journal.KafkaJournal.write(KafkaJournal.java:515) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.writeToJournal(JournallingMessageHandler.java:113) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.access$200(JournallingMessageHandler.java:45) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler$2.call(JournallingMessageHandler.java:104) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler$2.call(JournallingMessageHandler.java:101) ~[graylog.jar:?]
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78) ~[graylog.jar:?]
        at com.github.rholder.retry.Retryer.call(Retryer.java:160) [graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:101) [graylog.jar:?]
        at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:45) [graylog.jar:?]
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [graylog.jar:?]
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.IOException: No space left on device
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_212]
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60) ~[?:1.8.0_212]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_212]
        at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_212]
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211) ~[?:1.8.0_212]
        at kafka.message.ByteBufferMessageSet.writeTo(ByteBufferMessageSet.scala:160) ~[graylog.jar:?]
        at kafka.log.FileMessageSet.append(FileMessageSet.scala:229) ~[graylog.jar:?]
        at kafka.log.LogSegment.append(LogSegment.scala:85) ~[graylog.jar:?]
        at kafka.log.Log.append(Log.scala:360) ~[graylog.jar:?]
        ... 14 more
```

But Graylog is accepting messages what can create a message lost if that is not seen in the logs.

Should space be added to the journal folder (without deleting anything) you might geht the following on startup

```
2019-06-04T13:13:23.046+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: kafka.common.KafkaException: Failed to acquire lock on file .lock in /mnt/graylog-journal/kafka. A Kafka instance in another process or thread is using this directory.
```

Plus

```
2019-06-04T13:15:39.481+02:00 ERROR [KafkaJournal] Unable to start logmanager.
kafka.common.KafkaException: Failed to acquire lock on file .lock in /mnt/graylog-journal/kafka. A Kafka instance in another process or thread is using this directory.
	at kafka.log.LogManager$$anonfun$lockLogDirs$1.apply(LogManager.scala:98) ~[graylog.jar:?]
	at kafka.log.LogManager$$anonfun$lockLogDirs$1.apply(LogManager.scala:95) ~[graylog.jar:?]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[graylog.jar:?]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[graylog.jar:?]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[graylog.jar:?]
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35) ~[graylog.jar:?]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) ~[graylog.jar:?]
	at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[graylog.jar:?]
	at kafka.log.LogManager.lockLogDirs(LogManager.scala:95) ~[graylog.jar:?]
	at kafka.log.LogManager.<init>(LogManager.scala:57) ~[graylog.jar:?]
	at org.graylog2.shared.journal.KafkaJournal.<init>(KafkaJournal.java:326) [graylog.jar:?]
	at org.graylog2.shared.journal.KafkaJournal.<init>(KafkaJournal.java:191) [graylog.jar:?]
	at org.graylog2.shared.journal.KafkaJournal$$FastClassByGuice$$8f50433e.newInstance(<generated>) [graylog.jar:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) [graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) [graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) [graylog.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) [graylog.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [graylog.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148) [graylog.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) [graylog.jar:?]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62) [graylog.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [graylog.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148) [graylog.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) [graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42) [graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65) [graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) [graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) [graylog.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) [graylog.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050) [graylog.jar:?]
	at org.graylog2.shared.buffers.InputBufferImpl.<init>(InputBufferImpl.java:72) [graylog.jar:?]
	at org.graylog2.shared.buffers.InputBufferImpl$$FastClassByGuice$$790e95b9.newInstance(<generated>) [graylog.jar:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) [graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) [graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) [graylog.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) [graylog.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [graylog.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148) [graylog.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) [graylog.jar:?]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62) [graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42) [graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65) [graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) [graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) [graylog.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) [graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42) [graylog.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65) [graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) [graylog.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) [graylog.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) [graylog.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [graylog.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148) [graylog.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) [graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211) [graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182) [graylog.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109) [graylog.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:87) [graylog.jar:?]
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:194) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:50) [graylog.jar:?]
```

Graylog is continuesly restarting not accepting anything.

**Comment by mpfz0r** [comment]
I think I understand what was happening in my case:
We periodically write the journal offset of our processed logs into the file `graylog2-committed-read-offset`.
Which we also explicitly `fsync(2)` after each write.

Kafka however flushes it's log with it's own interval.
So my assumption is:
 - We write our offset file
 - The OS crashes and reboots
 - The ext4 journal restores a version of the kafka journal that is older than our offset file

After that we are in a state where the diff between our processed logs and the end of the kafka log becomes negative.

The input processing will discard messages until the negative diff is back to `0`.
Which means that it does in fact recover, but will drop `n` messages to get there.

I've reproduced this behavior by manually tweaking the `graylog2-committed-read-offset` file.

**Comment by thll** [comment]
We've come across this again (in HS-513927733).

```
$ java -jar /usr/share/graylog-server/graylog.jar journal show -s -f /etc/graylog/server/server.conf
    [...]
    Number of segments: 2
    Log start offset: 24790363387
    Log end offset: 24790619224
    Number of messages: 255838
    Committed read offset: 57163032316
    [...]
```
In this particular case, the mismatch is a little tot high to support the OS crash theory:

`"Log end offset" - "Committed read offset" = 24790619224 - 57163032316 = -32372413092`

So maybe there's an additional issue which could be causing this.
