### ISSUE TITLE
Dashboard Breaks With '0' in Quick Stats Num Top/Bottom Values

### ISSUE THREAD

**Issue by therealjoshuad** [Graylog2/graylog2-server#5901]
I was creating a new dashboard today and accidentally put a 0 in the **Number of top/bottom values** field. The dashboard fails to load, gives an error: **Cannot read property 'value' of undefined**. I also decided to test a negative number and it also causes the same issue.

## Expected Behavior
The customize option in a Quick Stats widget shouldn't allow you to enter a 0 or negative value

## Current Behavior
The customization wizard allows you to enter 0 or negative values, which causes the dashboard to no longer load.

## Possible Solution
Add some logic in the customization wizard for a Quick Stats chart to not allow 0 or negative numbers. Alternatively add some logic for the dashboard to be able to recover from such a value? As of now I had to delete and re-create the dashboard, luckily I hadn't gotten too far in customization.

## Steps to Reproduce (for bugs)
1. Perform a search and find some data to generate a quick stats chart for.
2. Create the Quick Stats chart, and add to a dashboard.
3. Open the Dashboard, and unlock/edit the dashboard.
4. Use the Customize button on the Quick Stats widget, and enter a 0 or negative number in the Number of top/bottom values field.
5. Save the widget
6. Refresh the dashboard, and you'll be presented with the monkey/banana and the error page.

## Context
This is a bug report, so this may not be directly applicable, but it could prevent having to delete a dashboard if a user unknowingly puts it in.

## Your Environment

* Graylog Version: 3.0.1
* Elasticsearch Version: 6.7.1
* MongoDB Version: 4.0.8
* Operating System: Ubuntu 18.04
* Browser version: Google Chrome 73

**Comment by therealjoshuad** [comment]
Error with 0 value:

`Cannot read property 'value' of undefined


Stack Trace:

TypeError: Cannot read property 'value' of undefined
    at t (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:182950)
    at http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:175713
    at Object.top (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:180955)
    at http://graylog.domain.com:9000/assets/LoggedInPage.dac1b68c62ef0b247bef.js:1:363135
    at g (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:1:6330)
    at Object.d.entries (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:1:6722)
    at http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:51482
    at http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:51545
    at Object.s._doRender (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:51813)
    at Object.s._doRedraw (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:52674)
    at Object.i.redraw (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:11440)
    at b.drawData (http://graylog.domain.com:9000/assets/LoggedInPage.dac1b68c62ef0b247bef.js:1:365773)
    at rb (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:45695)
    at ab (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:45445)
    at kn (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:89372)
    at Tn (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:84934)
    at gn (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:84286)
    at Rn (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:83307)
    at $t (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:82227)
    at Object.enqueueSetState (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:47300)
    at b.W.setState (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:26:1660)
    at http://graylog.domain.com:9000/assets/LoggedInPage.dac1b68c62ef0b247bef.js:1:88767
    at a (http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:88318)
    at A._settlePromiseFromHandler (http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:61004)
    at A._settlePromise (http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:61887)
    at A._settlePromise0 (http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:62627)
    at A._settlePromises (http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:63970)
    at http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:16848

Component Stack:

    in QuickValuesVisualization
    in div
    in Widget
    in div
    in a
    in DraggableCore
    in a
    in div
    in ReactGridLayout
    in a
    in a
    in i
    in div
    in div
    in p
    in span
    in i
    in ShowDashboardPage
    in n
    in div
    in p
    in div
    in p
    in div
    in t
    in div
    in t
    in n
    in withRouter(n)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade`

**Comment by therealjoshuad** [comment]
Error with **-1** in the num of top/bottom value

`Invalid array length
Stack Trace:
RangeError: Invalid array length
    at http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:175637
    at Object.top (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:180955)
    at http://graylog.domain.com:9000/assets/LoggedInPage.dac1b68c62ef0b247bef.js:1:363135
    at g (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:1:6330)
    at Object.d.entries (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:1:6722)
    at http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:51482
    at http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:51545
    at Object.s._doRender (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:51813)
    at Object.i.render (http://graylog.domain.com:9000/assets/vendors~LoggedInPage.dac1b68c62ef0b247bef.js:38:11074)
    at b._renderDataTable (http://graylog.domain.com:9000/assets/LoggedInPage.dac1b68c62ef0b247bef.js:1:363787)
    at b.componentWillReceiveProps (http://graylog.domain.com:9000/assets/LoggedInPage.dac1b68c62ef0b247bef.js:1:359781)
    at Eb (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:48298)
    at zt (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:58297)
    at it (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:63066)
    at Vt (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:78129)
    at Ut (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:78506)
    at Tn (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:84899)
    at gn (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:84286)
    at Rn (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:83307)
    at $t (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:82227)
    at Object.enqueueSetState (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:18:47300)
    at b.W.setState (http://IPADDRESS:9000/assets/vendor.4024e2a8db732781a971.js:26:1660)
    at http://graylog.domain.com:9000/assets/2e726fa8-55.dac1b68c62ef0b247bef.js:1:2261
    at a (http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:88318)
    at A._settlePromiseFromHandler (http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:61004)
    at A._settlePromise (http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:61887)
    at A._fulfillPromises (http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:63493)
    at A._settlePromises (http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:64022)
    at http://IPADDRESS:9000/assets/builtins.dac1b68c62ef0b247bef.js:158:16848
Component Stack:
    in QuickValuesVisualization
    in div
    in Widget
    in div
    in a
    in DraggableCore
    in a
    in div
    in ReactGridLayout
    in a
    in a
    in i
    in div
    in div
    in p
    in span
    in i
    in ShowDashboardPage
    in n
    in div
    in p
    in div
    in p
    in div
    in t
    in div
    in t
    in n
    in withRouter(n)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade`

**Comment by carlrannaberg** [comment]
Had the same issue. You can recover the dashboard by updating the widget through Graylog REST API: http://docs.graylog.org/en/3.0/pages/configuration/rest_api.html

Basically you need to make a PUT request with this configuration:
URL: https://graylog.outfunnel.org/api/dashboards/[dashboard-id]/widgets/[widget-id]
Headers:
* `Authorization: Basic [token]`
* `Content-type: application/json`
* `X-Requested-By: XMLHttpRequest `
Body:
```
{
	"description": "Name",
	"type": "QUICKVALUES",
	"cache_time": 10,
	"config": {
		"timerange": {
			"type": "relative",
			"range": 86400
		},
		"field": "of_request_uri",
		"stream_id": "[sream-id]",
		"query": "",
		"show_data_table": true,
		"limit": 10, // this is the culprit
		"show_pie_chart": false,
		"sort_order": "desc",
		"stacked_fields": "",
		"data_table_limit": 10
	}
}
```

You can get the authorization token and stream ID's by checking browser network tab for `/api/dashboards/[dashboard-id]` request which contains all the necessary information.

**Comment by bernd** [comment]
This has been fixed in the new search page. The aggregation builder doesn't allow a value of `0`.
