### ISSUE TITLE
cannot connect to elasticsearch manged by cloud-on-k8s

### ISSUE THREAD

**Issue by nrobert13** [Graylog2/graylog2-server#6012]
Trying to run graylog on k8s with elasticsearch managed by the [es-operator](https://github.com/elastic/cloud-on-k8s), but graylog cannot connect to elastic. 
## Expected Behavior

can connect to elasticsearch
## Current Behavior

cannot connect to elasticsearch
## Steps to Reproduce (for bugs)

1. deploy an elastic cluster with the cloud-on-k8s operator
2. deploy graylog with the helm charts
3. watch logs
4.

## Context

```
2019-06-13 12:34:58,494 ERROR   [IndexRotationThread] - Couldn't point deflector to a new index - {}
org.graylog2.indexer.IndexNotFoundException: Couldn't collect aliases for index pattern graylog_*

Index not found for query: . Try recalculating your index ranges.
	at org.graylog2.indexer.cluster.jest.JestUtils.buildIndexNotFoundException(JestUtils.java:118) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.specificException(JestUtils.java:84) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:57) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:62) ~[graylog.jar:?]
	at org.graylog2.indexer.indices.Indices.getIndexNamesAndAliases(Indices.java:316) ~[graylog.jar:?]
	at org.graylog2.indexer.MongoIndexSet.getNewestIndexNumber(MongoIndexSet.java:151) ~[graylog.jar:?]
	at org.graylog2.indexer.MongoIndexSet.getNewestIndex(MongoIndexSet.java:146) ~[graylog.jar:?]
	at org.graylog2.indexer.MongoIndexSet.setUp(MongoIndexSet.java:252) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.checkAndRepair(IndexRotationThread.java:138) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:76) ~[graylog.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_181]
	at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2019-06-13 12:35:03,667 INFO    [IndexRangesCleanupPeriodical] - Skipping index range cleanup because the Elasticsearch cluster is unreachable or unhealthy - {}
2019-06-13 12:35:08,586 INFO    [MongoIndexSet] - Did not find a deflector alias. Setting one up now. - {}
2019-06-13 12:35:08,590 ERROR   [IndexRotationThread] - Couldn't point deflector to a new index - {}
org.graylog2.indexer.IndexNotFoundException: Couldn't collect aliases for index pattern graylog_*
```
graylog.conf
```
    node_id_file = /usr/share/graylog/data/journal/node-id
    root_username = admin
    root_email = 
    root_timezone = UTC
    plugin_dir = /usr/share/graylog/plugin
    http_bind_address = 0.0.0.0:9000
    elasticsearch_hosts = https://user:password@general-es:9200
    allow_leading_wildcard_searches = false
    allow_highlighting = false
    output_batch_size = 500
    output_flush_interval = 1
    output_fault_count_threshold = 5
    output_fault_penalty_seconds = 30
    processbuffer_processors = 5
    outputbuffer_processors = 3
    processor_wait_strategy = blocking
    ring_size = 65536
    inputbuffer_ring_size = 65536
    inputbuffer_processors = 2
    inputbuffer_wait_strategy = blocking
    message_journal_enabled = true
    # Do not change `message_journal_dir` location
    message_journal_dir = /usr/share/graylog/data/journal
    lb_recognition_period_seconds = 3
    # Use a replica set instead of a single host
    mongodb_uri = mongodb://user:password@mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/graylog?replicaSet=rs0
    mongodb_max_connections = 1000
    mongodb_threads_allowed_to_block_multiplier = 5
    # Email transport
    transport_email_enabled = false
    transport_email_hostname = 
    transport_email_port = 2587
    transport_email_use_auth = true
    transport_email_use_tls = true
    transport_email_use_ssl = false
    transport_email_auth_username = 
    transport_email_auth_password = 
    transport_email_subject_prefix = [graylog]
    transport_email_from_email = 
    content_packs_dir = /usr/share/graylog/data/contentpacks
    content_packs_auto_load = grok-patterns.json
    proxied_requests_thread_pool_size = 32

```
here's the SubjectAltNames for the elastic certificate:

```
$ openssl s_client -connect general-es:9200 | openssl x509 -text -noout | grep -A1 "X509v3 Subject Alternative Name"
depth=1 OU = 49l52cbw9xrwc8rp, CN = general
verify error:num=19:self signed certificate in certificate chain
            X509v3 Subject Alternative Name: 
                othername:<unsupported>, DNS:general-es-fh9lhl6xsf.node.general.graylog.es.cluster.local, DNS:general-es-fh9lhl6xsf, IP Address:10.244.1.227, IP Address:127.0.0.1, IP Address:10.245.51.154, DNS:general-es, DNS:general-es.graylog.svc.cluster.local, DNS:general-es-discovery, DNS:general-es-discovery.graylog.svc.cluster.local

```

elastic health

```
$ curl -sk https://user:password@general-es:9200/_cat/health?v
epoch      timestamp cluster status node.total node.data shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1560431736 13:15:36  general green           3         3     10   5    0    0        0             0                  -                100.0%

```
## Your Environment

* Graylog Version: 3.0.1, 3.0.2, 2.5.2
* Elasticsearch Version: 6.8.0
* MongoDB Version: 4.0
* Operating System: debian 9
* Browser version: Chrome 72.0.3626.119

**Comment by jalogisch** [comment]
This looks for me like you have enabled ACLs and the user for Graylog does not have the needed rights. 

That is not Graylog having issues here with that Elasticsearch installation - it is Graylog using a restricted user. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by nrobert13** [comment]
@jalogisch , I wouldn't be that sure it's because of ACL, I tried with the built-in elastic superuser, which according to elastic docu 
`Grants full access to the cluster, including all indices and data.`

**Comment by jalogisch** [comment]
To be honest - Graylog just use the provided URL to communicate with Elasticsearch over REST. If the commands are not given that are needed, that Cluster does not provide the REST API as Elasticsearch should. 

That looks like an operational problem and not a problem with Graylog.

**Comment by nrobert13** [comment]
This turned out to be ACL related as @jalogisch suggested. Creating another user solved the issue. Sorry for the late update, and thanks.
