### ISSUE TITLE
Graylog Error once input is launched (java.lang.OutOfMemoryError: unable to create new native thread)

### ISSUE THREAD

**Issue by RiffRaff99** [Graylog2/graylog2-server#6146]
Hi, I posted on the forum: [https://community.graylog.org/t/java-lang-outofmemoryerror-unable-to-create-new-native-thread/11165](https://community.graylog.org/t/java-lang-outofmemoryerror-unable-to-create-new-native-thread/11165) and it was suggested to setup an issue here. Any help/fix is highly appreciated. Please let me know if I can provide further information.

## Expected Behavior

Graylog Webinterface -> Inputs -> Pick Syslog TCP [UDP]
Click "Launch New Input"
Select node [Tick Global]
Change Port to 8514
Click "Save"
Setup rsyslog "*.* @@127.0.0.1:8514;RSYSLOG_SyslogProtocol23Format"
Systemctl restart rsyslog

--> Receive messages

## Current Behavior

On launching an input, the following error is thrown:
```
2019-07-11T23:38:58.498+02:00 INFO [ServerBootstrap] Graylog server up and running.
2019-07-11T23:38:58.547+02:00 INFO [InputStateListener] Input [Syslog TCP/5d27ab900a975a0ecb430e88] is now STARTING
2019-07-11T23:38:58.655+02:00 WARN [AbstractTcpTransport] receiveBufferSize (SO_RCVBUF) for input SyslogTCPInput{title=sys, type=org.graylog2.inputs.syslog.tcp.SyslogTCPInput, nodeId=null} (channel [id: 0x585b2c10, L:/127.0.0.1:10514]) should be 1048576 but is 425984.
2019-07-11T23:39:23.521+02:00 WARN [OutputBuffer] Unable to process event MessageEvent{raw=null, message=source: MY_HOST | message: Starting Clean php session files… { process_id: 1 | level: 6 | gl2_remote_ip: 127.0.0.1 | gl2_remote_port: 36924 | gl2_source_input: 5d27ab900a975a0ecb430e88 | application_name: systemd | gl2_source_node: b3f1c249-3375-4322-a370-e53f38873bd9 | _id: 594828f0-a424-11e9-851f-000000000000 | facility: system daemon | timestamp: 2019-07-11T23:39:23.512+02:00 }, messages=null}, sequence 7
java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start0(Native Method) ~[?:1.8.0_212]
at java.lang.Thread.start(Thread.java:717) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1367) ~[?:1.8.0_212]
at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[?:1.8.0_212]
at com.codahale.metrics.InstrumentedExecutorService.submit(InstrumentedExecutorService.java:72) ~[graylog.jar:?]
at org.graylog2.buffers.processors.OutputBufferProcessor.processMessage(OutputBufferProcessor.java:187) ~[graylog.jar:?]
at org.graylog2.buffers.processors.OutputBufferProcessor.processMessage(OutputBufferProcessor.java:168) ~[graylog.jar:?]
at org.graylog2.buffers.processors.OutputBufferProcessor.onEvent(OutputBufferProcessor.java:135) ~[graylog.jar:?]
at org.graylog2.buffers.processors.OutputBufferProcessor.onEvent(OutputBufferProcessor.java:51) ~[graylog.jar:?]
at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
For SyslogTCP/UDP Input this happens instantly after "Save" is pressed in the WebGui, for Beats Input once messages are sent (or telnet localhost 5044 is executed). 
After the error is thrown, the WebGui is pretty unresponsive, giving lots of 500 errors.

## Possible Solution

none known

## Steps to Reproduce (for bugs)

Please see "Expected behaviour"

## Context

Installed Graylog to read Syslog messages. 
Tried to increase nproc -> Same result
Tried with previous Graylog version (3.01) -> Same result
Tried Beats/Sidecar as Input type -> Same result
Installed Kibana to ingest messages via Filebeat -> works (don't want to use Kibana though). Kibana was installed as a workaround after I couldn't get Graylog to work.

OpenVZ VPS doesn't allow me modify kernel settings. (Elasticsearch suggest to increase vm.max_map_count). No /proc/sys/net/core/rmem* file exist.

Graylog is installed on Ubuntu 18.04LTS, OpenVZ VPS with advertised 12GB ram and 6 vcores.
A running Graylog-server (without Inputs) starts 158 processes ( "ps hH p Graylog_PID |wc -l" = 158).

> The JVM is using 313.3MB of 972.8MB heap space and will not attempt to use more than 972.8MB

when ideling. Its about 700MB max. when collecting messages but moves from 400MB to 700MB, monitored on the same VPS under Ubuntu16.04LTS, where I used Graylog previously.

Community Forum suggested network interface setup could cause an issue, had this warning in the log:
`2019-07-11T23:38:58.592+02:00 WARN [MacAddressUtil] Failed to find a usable hardware address from the network interfaces; using random bytes: 63:56:91:6e:b2:cc:08:6f
`
System has the following ifconfig output:
```
lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536
inet 127.0.0.1 netmask 255.0.0.0
loop txqueuelen 1000 (Lokale Schleife)
RX packets 8877228 bytes 22728067037 (22.7 GB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 8877228 bytes 22728067037 (22.7 GB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

venet0: flags=211<UP,BROADCAST,POINTOPOINT,RUNNING,NOARP> mtu 1500
inet 127.0.0.1 netmask 255.255.255.255 broadcast 0.0.0.0 destination 127.0.0.1
unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 0 (UNSPEC)
RX packets 1500568 bytes 1108783656 (1.1 GB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 1216511 bytes 984146317 (984.1 MB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

venet0:0: flags=211<UP,BROADCAST,POINTOPOINT,RUNNING,NOARP> mtu 1500
inet IP_ADDRESS netmask 255.255.255.255 broadcast IP_ADDRESS destination IP_ADDRESS 
unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 0 (UNSPEC)
```
As I wrote in the community forum, I'm unsure how severe the missing MAC address is.

My Graylog Conf looks like this:
```
is_master = true
node_id_file = /etc/graylog/server/node-id
password_secret = SECRET
root_password_sha2 = SECRET
root_email = "My@Email.Address"
bin_dir = /usr/share/graylog-server/bin
data_dir = /var/lib/graylog-server
plugin_dir = /usr/share/graylog-server/plugin
http_bind_address = 127.0.0.1:9000
trusted_proxies = 127.0.0.1/32
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 4
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://localhost/graylog
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
proxied_requests_thread_pool_size = 32
```

## Your Environment

* Graylog Version:
```
Graylog 3.0.2+1686930 on MY_HOST (Oracle Corporation 1.8.0_212 on Linux 4.15.0)
{
  "aaa140b9-0deb-4972-97ac-9de5efa923b4": {
    "facility": "graylog-server",
    "codename": "Space Moose",
    "node_id": "aaa140b9-0deb-4972-97ac-9de5efa923b4",
    "cluster_id": "0a6a4759-84e0-4e0a-966a-444db1ddb2cb",
    "version": "3.0.2+1686930",
    "started_at": "2019-07-15T17:33:34.203Z",
    "hostname": "h2118376.stratoserver.net",
    "lifecycle": "running",
    "lb_status": "alive",
    "timezone": "Europe/Berlin",
    "operating_system": "Linux 4.15.0",
    "is_processing": true
  }
}
```
* Elasticsearch Version:
```
curl -XGET 'localhost:9200'
{
  "name" : "P2u9l2o",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "nZLnd9J3SnWO4Gjygdlr1A",
  "version" : {
    "number" : "6.8.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "1fad4e1",
    "build_date" : "2019-06-18T13:16:52.517138Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

```
* MongoDB Version:
```
db version v4.0.10
git version: c389e7f69f637f7a1ac3cc9fae843b635f20b766
```
* Operating System: 
Ubuntu 18.04LTS, Apache2, GL via Reverse proxy as per tutorial

* Browser version: 
Firefox 68.0

I use Graylog in a rather small scale and want to monitor Syslogs and Apache Access/Error logs. The VPS runs also the following services (besides OS defaults): Kopano Groupware, Postfix, Fetchmail, Nextcloud:
```
tcp        0      0 127.0.0.1:5601          0.0.0.0:*               LISTEN      121        383632830  2940/node
tcp        0      0 127.0.0.1:10024         0.0.0.0:*               LISTEN      114        242431870  4184/amavisd-new (c
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      119        367116784  30820/mongod
tcp        0      0 127.0.0.1:10025         0.0.0.0:*               LISTEN      0          241156962  2537/master
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      109        241167164  515/mysqld
tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN      0          241213826  2537/master
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      116        241161821  410/redis-server 12
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          712713188  8117/apache2
tcp        0      0 127.0.0.1:9200          0.0.0.0:*               LISTEN      118        378338218  23651/java
tcp        0      0 127.0.0.1:9300          0.0.0.0:*               LISTEN      118        378326577  23651/java
tcp        0      0 0.0.0.0:22           0.0.0.0:*               LISTEN      0          241187049  340/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      0          241213823  2537/master
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      0          712713190  8117/apache2
tcp        0      0 127.0.0.1:9980          0.0.0.0:*               LISTEN      117        606484922  9248/loolwsd
tcp        0      0 127.0.0.1:9981          0.0.0.0:*               LISTEN      117        606445523  9248/loolwsd
tcp6       0      0 :::236                  :::*                    LISTEN      0          241209068  2365/kopano-server
tcp6       0      0 :::110                  :::*                    LISTEN      0          241168820  289/kopano-gateway
tcp6       0      0 :::143                  :::*                    LISTEN      0          241168825  289/kopano-gateway
tcp6       0      0 :::2003                 :::*                    LISTEN      0          241184042  284/kopano-dagent
udp        0      0 0.0.0.0:46874           0.0.0.0:*                           114        606754529  4184/amavisd-new (c
udp        0      0 0.0.0.0:47101           0.0.0.0:*                           114        637700695  16539/amavisd-new (


```

**Comment by RiffRaff99** [comment]
My apologies, this isn't a bug. It turned out Systemd's Max task value was set to 165 as Default.
Adding 
`TasksMax=xxx`

to the [Service] section in the systemd .service file solved the problem. For some reason it is defaulted to 165 on my installation.
