### ISSUE TITLE
Improve handling of Email Notifications with no recipients

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#6163]
Assigning an Email Notification with no recipients to an Event Definition ends up throwing an exception in the Graylog logs:

```
2019-07-18 16:30:28,286 ERROR: org.graylog.events.scheduler.JobExecutionEngine - Job execution error - trigger=5d30824793a96e56fe7574c3 job=5d30683b93a96e4c75f16244
org.graylog.events.scheduler.JobExecutionException: Cannot send emails: empty recipient list.
    at org.graylog.events.notifications.jobs.EmailNotificationJob.execute(EmailNotificationJob.java:111) ~[classes/:?]
    at org.graylog.events.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:117) ~[classes/:?]
    at org.graylog.events.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:95) ~[classes/:?]
    at org.graylog.events.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:70) ~[classes/:?]
    at org.graylog.events.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:93) ~[classes/:?]
    at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [metrics-core-4.0.3.jar:4.0.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
    at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [metrics-core-4.0.3.jar:4.0.3]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: org.graylog.events.notifications.jobs.EmailSender$ConfigurationError: Cannot send emails: empty recipient list.
    at org.graylog.events.notifications.jobs.EmailSender.sendEmails(EmailSender.java:172) ~[classes/:?]
    at org.graylog.events.notifications.jobs.EmailNotificationJob.execute(EmailNotificationJob.java:106) ~[classes/:?]
    ... 9 more
```

Once that exception get thrown, the code will try resending the notification many times and periodically, producing lots of noise in the logs and making it very hard to see anything else that is going on there.

## Expected Behavior
Adding an Email Notification with no recipients should be validated when creating/editing it. The scheduler should log an error if for some reason one of the Notifications still has no recipients, but it should not throw exceptions. In that situation, I'm not sure if there's lot of value in retrying sending the email for too long. Most likely people won't notice that immediately and will end up getting a full inbox with old alerts when they change it.

## Current Behavior
The Notification job throws an exception and we retry many times, making this error very noisy.

**Comment by edmundoa** [comment]
Since https://github.com/Graylog2/graylog2-server/issues/6153 we are validating that Email Notifications have either user or email recipients.
