### ISSUE TITLE
3.1 Beta 3 : error when selecting stream in views

### ISSUE THREAD

**Issue by TiNico22** [Graylog2/graylog2-server#6204]
## Current Behavior

the gui is crashing when selecting "stream" when creating a new view

error message :
Cannot set property 'lastEffect' of null

Stack Trace:

TypeError: Cannot set property 'lastEffect' of null
    at na (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:54637)
    at ia (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:54801)
    at Object.useEffect (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:56158)
    at useEffect (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:26:5163)
    at o (http://192.168.0.21:9000/assets/ExtendedSearchPage.e608f4718a2965f1b86c.js:1:97229)
    at Kr (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:52903)
    at Ea (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:65091)
    at Vo (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:90402)
    at Go (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:90786)
    at Os (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:97643)
    at ks (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:97030)
    at Ts (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:96051)
    at Qo (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:94942)
    at Object.enqueueSetState (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:18:44685)
    at t.b.setState (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:26:1660)
    at t.<anonymous> (http://192.168.0.21:9000/assets/app.e608f4718a2965f1b86c.js:110:264557)
    at n.e (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:10:1321)
    at n.emit (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:90:240708)
    at o.trigger (http://192.168.0.21:9000/assets/vendor.fd563bc4b58b15696f83.js:10:2196)
    at o._trigger (http://192.168.0.21:9000/assets/app.e608f4718a2965f1b86c.js:210:82221)
    at http://192.168.0.21:9000/assets/app.e608f4718a2965f1b86c.js:210:80758
    at a (http://192.168.0.21:9000/assets/app.e608f4718a2965f1b86c.js:110:228053)
    at k._settlePromiseFromHandler (http://192.168.0.21:9000/assets/app.e608f4718a2965f1b86c.js:110:200739)
    at k._settlePromise (http://192.168.0.21:9000/assets/app.e608f4718a2965f1b86c.js:110:201622)
    at k._settlePromise0 (http://192.168.0.21:9000/assets/app.e608f4718a2965f1b86c.js:110:202362)
    at k._settlePromises (http://192.168.0.21:9000/assets/app.e608f4718a2965f1b86c.js:110:203705)
    at http://192.168.0.21:9000/assets/app.e608f4718a2965f1b86c.js:110:156583

Component Stack:

    in o
    in withRouter(o)
    in t
    in withRouter(t)
    in ConnectStoresWrapper[withRouter(t)] stores=view
    in ExtendedSearchPage
    in ConnectStoresWrapper[ExtendedSearchPage] stores=executionState
    in Unknown
    in n
    in o
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in withRouter(n)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in o
    in AppFacade

## Steps to Reproduce (for bugs)

1. select view
2. select create new
3. select  a stream in the list

## Your Environment

* Graylog Version: 3.1 beta 3 (upgraded from 3.0.2 via rpm)
* Elasticsearch Version: 6.8.1_1
* MongoDB Version: 3.6
* Operating System: centos7
* Browser version: chrome 75

**Comment by benoc617** [comment]
Same issue here, My environment:
Graylog Version 3.1.0 beta 3 (from graylog/graylog/3.1.0-beta.3-1 docker container)
Elasticsearch Version: 6.5.4
MongoDB Version: 3.6
Operating System: CoreOS (kernel 4.13.16-coreos-r2)
Browser version: Chrome 75  and Safari 12.1.1 

This error reproduces for me when doing anything in the view (attempting to add/remove a field, change stream, even just execute a search).  Browser cache/cookies cleared and full restart attempted with no effect.

**Comment by bud1979** [comment]
same for me as well,  Anything done in B3 Views, gives this error.

Adding a Tab, Changing time range, select stream.

**Comment by kmerz** [comment]
Refs https://github.com/facebook/react/issues/14014

**Comment by kyleknighted** [comment]
Hey @TiNico22 Thanks for catching and sharing the details to your problem.
We've updated the frontend optimization library to a newer package and seem to have resolved this production build issue in PR #6219 

If you find time, you can grab the [build snapshot](https://graylog2public.s3.amazonaws.com/snapshots/graylog-3.1.0-beta.4-SNAPSHOT-20190730180904-pr-6219-build-4945.zip) and test against it until the next beta is released.

Thanks again!

cc: @benoc617 @bud1979 @kmerz

**Comment by TiNico22** [comment]
I will try to do it this weekend and give you feedback
