### ISSUE TITLE
Exception when saving view

### ISSUE THREAD

**Issue by love01211** [Graylog2/graylog2-server#6319]
## Expected Behavior

Views Edit Success
## Current Behavior

Error!
![微信图片_20190819105559](https://user-images.githubusercontent.com/31766073/63236343-f212fd80-c26f-11e9-85e6-2ce9a5af7b2d.png)
Error Message
```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.


Stack Trace:

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Mo (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:18:77608)
    at Ho (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:18:81584)
    at Xo (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:18:84901)
    at http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:18:98277
    at Object.exports.unstable_runWithPriority (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:35:3284)
    at Os (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:18:98212)
    at Ys (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:18:97988)
    at Ss (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:18:97333)
    at Ls (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:18:96354)
    at Zo (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:18:95228)
    at Object.enqueueSetState (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:18:44755)
    at g.b.setState (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:26:1665)
    at g.<anonymous> (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:102:260361)
    at a.n (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:10:1324)
    at a.emit (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:90:241068)
    at h.trigger (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:10:2199)
    at h._trigger (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:227:360925)
    at h.onCurrentViewStateChange (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:227:359573)
    at a.n (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:10:1324)
    at a.emit (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:90:241068)
    at h.trigger (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:10:2199)
    at h._trigger (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:227:319860)
    at h.onViewStatesStoreChange (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:227:318552)
    at a.n (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:10:1324)
    at a.emit (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:90:240635)
    at h.trigger (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:10:2199)
    at h._trigger (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:227:79914)
    at h.onViewStoreChange (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:227:79189)
    at a.n (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:10:1324)
    at a.emit (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:90:241068)
    at h.trigger (http://192.168.113.91:9000/assets/vendor.91c91d4a31d54d96392a.js:10:2199)
    at h._trigger (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:202:81830)
    at http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:202:80365
    at s (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:102:224951)
    at P._settlePromiseFromHandler (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:102:198233)
    at P._settlePromise (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:102:199033)
    at P._settlePromise0 (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:102:199732)
    at P._settlePromises (http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:102:201059)
    at http://192.168.113.91:9000/assets/app.60a2621478c6c8ca385c.js:102:154681

Component Stack:

    in Unknown
    in u
    in f
    in p
    in ConnectStoresWrapper[p] stores=highlightingRules
    in td
    in tr
    in tbody
    in O
    in Provider
    in table
    in div
    in div
    in div
    in span
    in t
    in ConnectStoresWrapper[t] stores=selectedFields,currentView
    in span
    in div
    in div
    in t
    in s
    in ConnectStoresWrapper[s] stores=colorRules
    in t
    in ConnectStoresWrapper[t] stores=view
    in Provider
    in div
    in t
    in DraggableCore
    in t
    in div
    in ReactGridLayout
    in t
    in o
    in t
    in div
    in div
    in t
    in t
    in ConnectStoresWrapper[t] stores=titles
    in div
    in t
    in span
    in v
    in ConnectStoresWrapper[v] stores=widgets
    in Unknown
    in ConnectStoresWrapper[Unknown/Anonymous] stores=fieldTypes,searches,viewMetadata,viewState
    in div
    in t
    in ExtendedSearchPage
    in ConnectStoresWrapper[ExtendedSearchPage] stores=executionState
    in Unknown
    in t
    in ConnectStoresWrapper[t] stores=executionState
    in Unknown
    in n
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in t
    in withRouter(t)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade
```

## Steps to Reproduce (for bugs)

1.Login Web Page 
2.Click on the views,create new
3.Input search query
4.Save as

## Your Environment

* Graylog Version:graylog-server-3.1.0
* Elasticsearch Version:elasticsearch-6.8.2
* MongoDB Version:mongodb-server-2.6.12
* Operating System:CentOS Linux release 7.3.1611 (Core) 
* Browser version:Google Chrome 75.0.3770.100

**Comment by kmerz** [comment]
Hi @love01211,

Could you please a way to reproduce this error?
From the stack trace it looks like you configured some highlighting is that correct?

Can you please add more information about how you triggered the problem?

Thank you in advance!

**Comment by love01211** [comment]
@kmerz I made some attempts, but I didn't think I could repeat an operation to trigger a problem, but a very random situation.

**Comment by love01211** [comment]
@kmerz A new problem was found in the test, and the load existing, refresh in the view triggers another problem
![image](https://user-images.githubusercontent.com/31766073/63249978-2a7d0080-c29d-11e9-9776-66176f96bc6e.png)
![image](https://user-images.githubusercontent.com/31766073/63250017-3b2d7680-c29d-11e9-8b2f-eab944f4cb19.png)

**Comment by kmerz** [comment]
Thanks a lot. Can you open a separated issue for the second stack trace? Since the stack trace is clear what is happening we can fix that.

For the original issue I need more input. So perhaps someone else runs in that issue or you see a pattern in it, when it happens again!

**Comment by love01211** [comment]
Okay, I'd love to. @kmerz

**Comment by shiyijiufei** [comment]
same problem
![image](https://user-images.githubusercontent.com/20214646/63415525-757b4d00-c430-11e9-955b-bd1c9288cdc4.png)

Cannot read property 'title' of undefined

Stack Trace:

TypeError: Cannot read property 'title' of undefined
    at t._isNewView (http://graylog.chint.com:9000/assets/ExtendedSearchPage.60a2621478c6c8ca385c.js:1:132926)
    at t.render (http://graylog.chint.com:9000/assets/ExtendedSearchPage.60a2621478c6c8ca385c.js:1:133229)
    at ka (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:63009)
    at Sa (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:62804)
    at Da (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:66638)
    at Fo (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:90682)
    at Vo (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:91066)
    at Ys (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:97953)
    at Ss (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:97333)
    at Ls (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:96354)
    at Zo (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:95228)
    at Object.enqueueSetState (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:44755)
    at t.b.setState (http://graylog.chint.com:9000/assets/vendor.91c91d4a31d54d96392a.js:26:1665)
    at http://graylog.chint.com:9000/assets/ShowViewPage.60a2621478c6c8ca385c.js:1:2235
    at s (http://graylog.chint.com:9000/assets/app.60a2621478c6c8ca385c.js:102:224951)
    at P._settlePromiseFromHandler (http://graylog.chint.com:9000/assets/app.60a2621478c6c8ca385c.js:102:198233)
    at P._settlePromise (http://graylog.chint.com:9000/assets/app.60a2621478c6c8ca385c.js:102:199033)
    at P._settlePromise0 (http://graylog.chint.com:9000/assets/app.60a2621478c6c8ca385c.js:102:199732)
    at P._settlePromises (http://graylog.chint.com:9000/assets/app.60a2621478c6c8ca385c.js:102:201059)
    at http://graylog.chint.com:9000/assets/app.60a2621478c6c8ca385c.js:102:154681

Component Stack:

    in ViewActionsMenu
    in ConnectStoresWrapper[ViewActionsMenu] stores=metadata,view,currentUser
    in span
    in span
    in u
    in w
    in ConnectStoresWrapper[w] stores=queries,queryTitles,viewMetadata
    in withRouter(ConnectStoresWrapper[w] stores=queries,queryTitles,viewMetadata)
    in div
    in t
    in ExtendedSearchPage
    in ConnectStoresWrapper[ExtendedSearchPage] stores=executionState
    in Unknown
    in t
    in ConnectStoresWrapper[t] stores=executionState
    in Unknown
    in n
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in t
    in withRouter(t)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade

**Comment by allangood** [comment]
I'm experiencing a very similar error, but when I try to load a View.
If I try to load a View after I create one, then everything works as usual, but if I try to open an "incognito mode" browser (or clean all cookies/cache) try to load any View, the this error occurs.

Steps to reproduce:
1) Login to Graylog
2) Create a View
3) Open a new "incognito mode" browser tab (or clean all cache and cookies)
4) Login to Graylog with this new browser tab
5) Open the View

My environment:
Graylog version: 3.1.0 (LDAP Authentication MS AD)
Elasticsearch: 6.8.2
MongoDB: 4.2.0

Stack trace:
```
e is undefined


Stack Trace:

_isNewView@https://logserver.mycompany/assets/ExtendedSearchPage.60a2621478c6c8ca385c.js:1:132923
render@https://logserver.mycompany/assets/ExtendedSearchPage.60a2621478c6c8ca385c.js:1:133229
ka@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:18:63009
Sa@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:18:62804
Da@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:18:66638
Fo@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:18:90682
Vo@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:18:91066
Ys@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:18:97953
Ss@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:18:97333
Ls@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:18:96354
Zo@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:18:95228
enqueueSetState@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:18:44755
24/b.prototype.setState@https://logserver.mycompany/assets/vendor.91c91d4a31d54d96392a.js:26:1665
t/</<@https://logserver.mycompany/assets/ShowViewPage.60a2621478c6c8ca385c.js:1:2235
s@https://logserver.mycompany/assets/app.60a2621478c6c8ca385c.js:102:224951
o/<[22]</n.exports/P.prototype._settlePromiseFromHandler@https://logserver.mycompany/assets/app.60a2621478c6c8ca385c.js:102:198233
o/<[22]</n.exports/P.prototype._settlePromise@https://logserver.mycompany/assets/app.60a2621478c6c8ca385c.js:102:199033
o/<[22]</n.exports/P.prototype._settlePromise0@https://logserver.mycompany/assets/app.60a2621478c6c8ca385c.js:102:199732
o/<[22]</n.exports/P.prototype._settlePromises@https://logserver.mycompany/assets/app.60a2621478c6c8ca385c.js:102:201059
o/<[2]</u.prototype._drainQueue@https://logserver.mycompany/assets/app.60a2621478c6c8ca385c.js:102:154925
o/<[2]</u.prototype._drainQueues@https://logserver.mycompany/assets/app.60a2621478c6c8ca385c.js:102:154986
u/this.drainQueues@https://logserver.mycompany/assets/app.60a2621478c6c8ca385c.js:102:153209
u@https://logserver.mycompany/assets/polyfill.60a2621478c6c8ca385c.js:1:33700
M/<@https://logserver.mycompany/assets/polyfill.60a2621478c6c8ca385c.js:1:33845
f@https://logserver.mycompany/assets/polyfill.60a2621478c6c8ca385c.js:1:20081


Component Stack:

    in ViewActionsMenu
    in ConnectStoresWrapper[ViewActionsMenu] stores=metadata,view,currentUser
    in span
    in span
    in u
    in w
    in ConnectStoresWrapper[w] stores=queries,queryTitles,viewMetadata
    in withRouter(ConnectStoresWrapper[w] stores=queries,queryTitles,viewMetadata)
    in div
    in t
    in ExtendedSearchPage
    in ConnectStoresWrapper[ExtendedSearchPage] stores=executionState
    in Unknown
    in t
    in ConnectStoresWrapper[t] stores=executionState
    in Unknown
    in n
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in t
    in withRouter(t)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade
```

**Comment by ssstonebraker** [comment]
same issue here, i see the "Cannot read property 'title' of undefined" when trying to load a view that I saved yesterday.
