### ISSUE TITLE
multiline parsing with "parse_json" not working

### ISSUE THREAD

**Issue by shakalandy** [Graylog2/graylog2-server#6425]
## Expected Behavior
Use the "parse_json" function inside a pipeline to parse json messages including multiline messages, e.g. java stracktraces. In Our case multiline messages are sent through filebeat.

## Current Behavior
Overall parsing of normal json messages works as expected - handling multiline messages not and as a result the JSON paylog isn't parsed.

## Possible Solution
let parse_json parse JSON messages or include another option to enable multiline parsing.

## Steps to Reproduce (for bugs)
1. Use filebeat and configure for multiline parsing, e.g.
```    
    multiline.pattern: '^\{\"@timestamp'
    multiline.negate: true
    multiline.match: after
```
2. sent multiline message
```  
{"@timestamp":"2019-09-10T15:09:54.070+0200","thread":"ajp-bio-8009-exec-2","level":"ERROR","loggerName":"ExceptionInterceptor.java","SessionID":"TO-2","message":"Exception 
while accessing http://test.graylog.com/your/beer","endOfBatch":"64","loggerFqcn":"","contextMap":{},"threadId":"","threadPriority":"","stacktrace":"java.lang.NullPoin
terException
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:333)
        at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:218)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:218)
        at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:333)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
"}

```
3. use pipeline parser
```
rule "JSON Parser Graylog" 
when 
  has_field("application") AND (to_string($message.application)) == "java"
then   
  let json = parse_json(to_string($message.message));
  let map = to_map(json);
  set_fields(map);   
 end
```
4. see the message in graylog

**
![image](https://user-images.githubusercontent.com/182060/64622089-0e293b00-d3e7-11e9-9199-5fc5e6435316.png)
**

## Context
We would like for forward stacktraces from java applications  to graylog via our preferred way - as JSON object via filebeat. 
Currently we cannot filter by stacktrace or have to figure out another way handling that.
Issue was opened after initial community posting: https://community.graylog.org/t/parse-json-problems-with-multiline-parsing/11913
## Your Environment

* Graylog Version:  graylog-server-3.0.2-1
* Elasticsearch Version: elasticsearch-6.8.1-1
* MongoDB Version: mongodb-server-2.6.12
* Operating System: Red Hat Enterprise Linux Server release 7.7 - Kernel 3.10.0-1062.1.1.el7.x86_64
* Browser version: Chrome 77

**Comment by jamier9** [comment]
Its the issue of parse_json not supporting any nested json objects.
I think what is tripping it up in your example is: ,"contextMap":{},
If you can remove that field or encapsulate the value  " " then it should be fine.

**Comment by jalogisch** [comment]
@jamier9 parsing nested json is something different. Please check the available issues for that.

@shakalandy we checked the specs of json and the provided log is not a valid json. As you would need to replace new-lines by `\n`. You can validate that over at https://jsonformatter.curiousconcept.com/ yourself.

BUT I can see from a user perspective that it would be one improvement if Graylog could parse this non-valid json too.

**Comment by patrickmann** [comment]
Closing since provided log was not valid JSON.
