### ISSUE TITLE
Exception on server shutdown

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#6504]
This happens occasionally when shutting down the server:

```
Exception in thread "http-worker-15" java.lang.NullPointerException: null value in entry: exception=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:176)
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:285)
        at org.graylog2.rest.GraylogErrorPageGenerator.generate(GraylogErrorPageGenerator.java:69)
        at org.glassfish.grizzly.http.server.util.HtmlHelper.setErrorAndSendErrorPage(HtmlHelper.java:132)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:231)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

## Your Environment

* Graylog Version: 96a748328

**Comment by manpreet26git** [comment]
Hi, I would like to work on this.

**Comment by himadri-mandal** [comment]
@jalogisch Can you please help to review the pull request? let me know if need additional changes.
