### ISSUE TITLE
Exporting Saved Search to Dashboard with Parameters can have errors

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#6736]
## Current Behavior

Saving a Search with Parameters that don't have defaults causes oddities when exporting to Dashboard

## Steps to Reproduce (for bugs)

1. Create new search with `http_method:$action$ AND ingest_time_hour:$hour$`
2. Save search with a default for `hour` but not `action`
3. Load saved search
4. This is where the issues split between changing or crashing

### Change

1. Use `GET` for the `action` parameter
2. Export saved search to dashboard
3. `action` changes to `PUSH`

![Nov-06-2019 10-19-19](https://user-images.githubusercontent.com/122591/68316362-f684d080-007e-11ea-8ce4-971524a6dc04.gif)

### Crash
1. Use `PUSH` for the `action` parameter
2. Export saved search to dashboard
3. Browser starts rendering 500 errors and server logs spit errors

![image](https://user-images.githubusercontent.com/122591/68316443-187e5300-007f-11ea-8c00-c9e44b47a8bb.png)

```
2019-11-06 09:58:35,141 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.IllegalArgumentException: invalid hexadecimal representation of an ObjectId: [new]
    at org.bson.types.ObjectId.parseHexString(ObjectId.java:549) ~[bson-3.6.4.jar:?]
    at org.bson.types.ObjectId.<init>(ObjectId.java:239) ~[bson-3.6.4.jar:?]
    at org.graylog2.database.PersistedServiceImpl.get(PersistedServiceImpl.java:60) ~[classes/:?]
    at org.graylog2.dashboards.DashboardServiceImpl.load(DashboardServiceImpl.java:107) ~[classes/:?]
    at org.graylog2.rest.resources.dashboards.DashboardsResource.get(DashboardsResource.java:138) ~[classes/:?]
    at sun.reflect.GeneratedMethodAccessor1061.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.1.jar:?]
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.1.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.1.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.1.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.1.jar:?]
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.1.jar:?]
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.1.jar:?]
    at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.28.jar:2.3.28]
    at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [metrics-core-4.0.3.jar:4.0.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

## Your Environment

* Graylog Version: `master` branch with `FEATURES=search_3_2` flag
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Unable to reproduce this. It seems like changes between this and the release of `3.2.0` have fixed it. Please reopen the issue if you can still reproduce it!
