### ISSUE TITLE
Non-existent Inputs cause NPE during disk journal processing

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#684]
```
2014-08-20 09:02:25,802 ERROR: org.graylog2.periodical.MasterCacheWorkerThread - Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Input>.
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
            at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
            at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
            at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
            at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
            at org.graylog2.utilities.MessageToJsonSerializer.getMessageInput(MessageToJsonSerializer.java:241)
            at org.graylog2.utilities.MessageToJsonSerializer.deserialize(MessageToJsonSerializer.java:217)
            at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:168)
            at org.graylog2.periodical.MasterCacheWorkerThread.work(MasterCacheWorkerThread.java:117)
            at org.graylog2.periodical.MasterCacheWorkerThread.access$200(MasterCacheWorkerThread.java:46)
            at org.graylog2.periodical.MasterCacheWorkerThread$1.run(MasterCacheWorkerThread.java:83)
            at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
            at org.graylog2.inputs.InputServiceImpl.find(InputServiceImpl.java:91)
            at org.graylog2.utilities.MessageToJsonSerializer$2.load(MessageToJsonSerializer.java:169)
            at org.graylog2.utilities.MessageToJsonSerializer$2.load(MessageToJsonSerializer.java:165)
            at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
            at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
            at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
            at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
            ... 10 more
```

**Comment by Kuckkuck** [comment]
I am also getting this error on graylog2 0.92.3 constantly after restarting graylog2-server. I have disabled the parameter in /etc/graylog2.conf and deleted the cache, but the error still happends:

2015-01-13T19:24:13.957Z ERROR [AbstractCacheWorkerThread] Exception while working on cache: 
java.lang.NullPointerException
2015-01-13T19:24:13.957Z ERROR [AbstractCacheWorkerThread] Exception while working on cache: 
java.lang.NullPointerException
2015-01-13T19:24:13.959Z ERROR [MasterCacheWorkerThread] Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Input>.
java.lang.NullPointerException
2015-01-13T19:24:32.248Z ERROR [AbstractCacheWorkerThread] Exception while working on cache: 
java.lang.NullPointerException
2015-01-13T19:24:32.249Z ERROR [MasterCacheWorkerThread] Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Input>.
java.lang.NullPointerException
2015-01-13T19:24:40.707Z ERROR [AbstractCacheWorkerThread] Exception while working on cache: 
java.lang.NullPointerException
2015-01-13T19:24:40.707Z ERROR [AbstractCacheWorkerThread] Exception while working on cache: 
java.lang.NullPointerException
2015-01-13T19:24:40.708Z ERROR [AbstractCacheWorkerThread] Exception while working on cache: 
java.lang.NullPointerException
2015-01-13T19:24:51.389Z ERROR [AbstractCacheWorkerThread] Exception while working on cache: 
java.lang.NullPointerException
2015-01-13T19:24:51.389Z ERROR [MasterCacheWorkerThread] Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Input>.

Regards,

Olaf

**Comment by nelsonq** [comment]
oops
