### ISSUE TITLE
graylog2-radio 0.20.6-1 hangs as java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by guanqing** [Graylog2/graylog2-server#687]
1. After starting Graylog2-radio, the following two errors repeat thousands times, are those 2 errors acceptable?
```
2014-08-19 18:19:40,258 INFO : org.graylog2.radio.Main - Graylog2 Radio up and running.
2014-08-19 18:19:40,270 INFO : org.graylog2.radio.inputs.InputRegistry - Completed starting [org.graylog2.inputs.gelf.udp.GELFUDPInput] input with ID <53adfc6e1ab4ee9a0160455e>

2014-08-19 18:32:50,118 ERROR: org.graylog2.inputs.gelf.gelf.GELFProcessor - Corrupt or invalid message received:
java.lang.IllegalStateException: Failed to decompress the GELF message payload
        at org.graylog2.inputs.gelf.gelf.GELFMessage.getJSON(GELFMessage.java:150)
        at org.graylog2.inputs.gelf.gelf.GELFProcessor.messageReceived(GELFProcessor.java:66)
        at org.graylog2.inputs.gelf.gelf.GELFChunkManager.run(GELFChunkManager.java:86)
Caused by: java.util.zip.ZipException: invalid distance too far back
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at org.graylog2.plugin.Tools.decompressZlib(Tools.java:153)
        at org.graylog2.inputs.gelf.gelf.GELFMessage.getJSON(GELFMessage.java:137)
        ... 2 more

2014-08-19 18:36:02,916 ERROR: org.graylog2.inputs.gelf.gelf.GELFProcessor - Could not parse JSON!
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.StringReader@55b2fcac; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3029)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1768)
        at org.graylog2.inputs.gelf.gelf.GELFProcessor.parse(GELFProcessor.java:90)
        at org.graylog2.inputs.gelf.gelf.GELFProcessor.messageReceived(GELFProcessor.java:66)
        at org.graylog2.inputs.gelf.GELFDispatcher.messageReceived(GELFDispatcher.java:86)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
        at org.jboss.netty.handler.traffic.AbstractTrafficShapingHandler.messageReceived(AbstractTrafficShapingHandler.java:408)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
        at org.graylog2.inputs.network.PacketInformationDumper.messageReceived(PacketInformationDumper.java:49)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.socket.nio.NioDatagramWorker.read(NioDatagramWorker.java:98)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioDatagramWorker.run(NioDatagramWorker.java:343)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

2. After thousands repeating occurrences of above 2 errors, we got a GELFChucnkManager error as following:

```
2014-08-19 23:27:25,873 ERROR: org.graylog2.inputs.gelf.gelf.GELFChunkManager - Error in GELFChunkManager
java.util.ConcurrentModificationException
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1115)
        at java.util.TreeMap$EntryIterator.next(TreeMap.java:1151)
        at java.util.TreeMap$EntryIterator.next(TreeMap.java:1146)
        at org.graylog2.inputs.gelf.gelf.GELFChunkManager.humanReadableChunkMap(GELFChunkManager.java:198)
        at org.graylog2.inputs.gelf.gelf.GELFChunkManager.run(GELFChunkManager.java:66)
```

3. After above GELFChucnkManager error, the following error repeats thousands times:

```
2014-08-20 00:12:25,949 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception during jersey resource handling
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(SocketSendBufferPool.java:203)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:201)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:146)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
        at org.jboss.netty.channel.Channels.write(Channels.java:725)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
        at org.jboss.netty.channel.Channels.write(Channels.java:704)
        at org.jboss.netty.channel.Channels.write(Channels.java:671)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248)
        at org.graylog2.jersey.container.netty.NettyContainer$NettyResponseWriter.commit(NettyContainer.java:174)
        at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:412)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:645)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:381)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:371)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:262)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:306)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

4. Finally, the GC overhead limit exceeded, the graylog-radio hang

```
2014-08-20 07:24:24,376 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception during jersey resource handling
java.lang.OutOfMemoryError: GC overhead limit exceeded
2014-08-20 07:24:25,740 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception during jersey resource handling
java.lang.OutOfMemoryError: GC overhead limit exceeded
2014-08-20 07:24:37,402 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception during jersey resource handling
java.lang.OutOfMemoryError: GC overhead limit exceeded
2014-08-20 07:24:52,134 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception during jersey resource handling
java.lang.OutOfMemoryError: GC overhead limit exceeded
2014-08-20 07:24:53,596 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception during jersey resource handling
2014-08-20 07:24:55,034 WARN : org.jboss.netty.channel.DefaultChannelPipeline - An exception was thrown by a user handler while handling an exception event ([id: 0x050a87cc, /10.136.56.7:36862 => /10.136.56.15:12950] EXCEPTION: java.lang.OutOfMemoryError: GC overhead limit exceeded)
2014-08-20 07:24:55,724 WARN : org.jboss.netty.channel.DefaultChannelPipeline - An exception was thrown by a user handler while handling an exception event ([id: 0x050a87cc, /10.136.56.7:36862 => /10.136.56.15:12950] EXCEPTION: java.lang.OutOfMemoryError: GC overhead limit exceeded)
java.lang.OutOfMemoryError: Java heap space
2014-08-20 07:24:56,262 WARN : org.jboss.netty.channel.socket.nio.AbstractNioSelector - Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "restapi-boss-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "restapi-worker-5" java.lang.OutOfMemoryError: GC overhead limit exceede
```

Thanks for any help and comment.

**Comment by bernd** [comment]
There are lots of stability and performance improvements in Graylog 1.0.0. Please re-open this issue if you still see this with Graylog 1.0.0. Thank you!
