### ISSUE TITLE
dashboard error

### ISSUE THREAD

**Issue by zino7825** [Graylog2/graylog2-server#6941]
I made a geoip world map dashboard but i got a below error 

I use geoip lookup table for world map 

* error message
```
annot read property 'lat' of null

Stack Trace:

TypeError: Cannot read property 'lat' of null
    at Object.project (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:43:13622)
    at Object.latLngToPoint (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:43:11720)
    at e.project (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:43:36496)
    at e.latLngToLayerPoint (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:43:36753)
    at e._project (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:43:76449)
    at e._reset (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:43:75752)
    at e.onAdd (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:43:75243)
    at e._layerAdd (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:43:64355)
    at e.whenReady (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:43:42235)
    at e.addLayer (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:43:64744)
    at e.componentDidMount (https://graylog.xxxx.com/assets/vendors~LoggedInPage.a5e2fb591e8fd54ee4ef.js:38:116831)
    at kn (https://graylog.xxxx.com/assets/vendor.4024e2a8db732781a971.js:18:89167)
    at Tn (https://graylog.xxxx.com/assets/vendor.4024e2a8db732781a971.js:18:84934)
    at gn (https://graylog.xxxx.com/assets/vendor.4024e2a8db732781a971.js:18:84286)
    at Rn (https://graylog.xxxx.com/assets/vendor.4024e2a8db732781a971.js:18:83307)
    at $t (https://graylog.xxxx.com/assets/vendor.4024e2a8db732781a971.js:18:82227)
    at Object.enqueueSetState (https://graylog.xxxx.com/assets/vendor.4024e2a8db732781a971.js:18:47300)
    at b.W.setState (https://graylog.xxxx.com/assets/vendor.4024e2a8db732781a971.js:26:1660)
    at https://graylog.xxxx.com/assets/LoggedInPage.a5e2fb591e8fd54ee4ef.js:1:88767
    at a (https://graylog.xxxx.com/assets/builtins.a5e2fb591e8fd54ee4ef.js:158:88318)
    at A._settlePromiseFromHandler (https://graylog.xxxx.com/assets/builtins.a5e2fb591e8fd54ee4ef.js:158:61004)
    at A._settlePromise (https://graylog.xxxx.com/assets/builtins.a5e2fb591e8fd54ee4ef.js:158:61887)
    at A._settlePromise0 (https://graylog.xxxx.com/assets/builtins.a5e2fb591e8fd54ee4ef.js:158:62627)
    at A._settlePromises (https://graylog.xxxx.com/assets/builtins.a5e2fb591e8fd54ee4ef.js:158:63970)
    at https://graylog.xxxx.com/assets/builtins.a5e2fb591e8fd54ee4ef.js:158:16848

Component Stack:

    in e
    in div
    in r
    in div
    in MapVisualization
    in div
    in Widget
    in div
    in a
    in DraggableCore
    in a
    in div
    in ReactGridLayout
    in a
    in a
    in i
    in div
    in div
    in p
    in span
    in i
    in ShowDashboardPage
    in n
    in div
    in p
    in div
    in p
    in div
    in t
    in div
    in t
    in n
    in withRouter(n)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade
```

**Comment by bernd** [comment]
@zino7825 Can you please show us the configuration you use to extract the IP location? (either extractor config or pipeline rule) Thank you!
