### ISSUE TITLE
Content pack installation is failing in 3.2 installation

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#7296]
An error occurs when trying to install a content pack in a 3.2 production build. 

## Expected Behavior

The content pack should install successfully.

## Current Behavior

The following stacktrace and exceptions are logged:

<details>
<summary>Log output with exceptions</summary>
2020-01-27 13:29:38,539 WARN : org.graylog2.contentpacks.facades.UnsupportedEntityFacade - Couldn't resolve entity EntityDescriptor{id=68ed2659-ae4e-4a43-8429-cfa93e47cd07, type=ModelType{name=dashboard, version=1}}
2020-01-27 13:29:38,539 WARN : org.graylog2.contentpacks.facades.UnsupportedEntityFacade - Couldn't resolve entity EntityDescriptor{id=291f5fd1-9e40-4587-a6b2-547a5f3751bb, type=ModelType{name=dashboard, version=1}}
2020-01-27 13:29:38,540 WARN : org.graylog2.contentpacks.facades.UnsupportedEntityFacade - Couldn't resolve entity EntityDescriptor{id=5427067d-5413-4a87-b55c-51743e4b298e, type=ModelType{name=dashboard, version=1}}
2020-01-27 13:29:38,540 WARN : org.graylog2.contentpacks.facades.UnsupportedEntityFacade - Couldn't resolve entity EntityDescriptor{id=11154e79-d464-4a61-994f-44f253342de9, type=ModelType{name=dashboard, version=1}}
2020-01-27 13:29:38,540 WARN : org.graylog2.contentpacks.facades.UnsupportedEntityFacade - Couldn't resolve entity EntityDescriptor{id=bdceb18f-aeeb-420c-aa66-3fbc802e3eb0, type=ModelType{name=dashboard, version=1}}
2020-01-27 13:29:38,546 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
org.graylog2.contentpacks.exceptions.ContentPackException: Failed to install content pack <c3ca8b7e-0e5d-46af-aa67-a3ff551f3abf/1>
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:158) ~[graylog.jar:?]
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:99) ~[graylog.jar:?]
	at org.graylog2.rest.resources.system.contentpacks.ContentPackResource.installContentPack(ContentPackResource.java:293) ~[graylog.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.UnsupportedOperationException: Unsupported entity EntityDescriptor{id=68ed2659-ae4e-4a43-8429-cfa93e47cd07, type=ModelType{name=dashboard, version=1}}
	at org.graylog2.contentpacks.facades.UnsupportedEntityFacade.createNativeEntity(UnsupportedEntityFacade.java:46) ~[graylog.jar:?]
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:149) ~[graylog.jar:?]
	... 29 more
2020-01-27 13:29:38,547 ERROR: org.graylog.plugins.auditlog.AuditLogger - Unable to write audit log entry because there is no valid license.
2020-01-27 13:29:39,464 WARN : org.graylog2.filters.StaticFieldFilter - Unable to load input: Input <5e2ee5c295125a0fb43e6a94> not found!
2020-01-27 13:29:39,465 WARN : org.graylog2.inputs.InputEventListener - Received InputCreated event but could not find input 5e2ee5c295125a0fb43e6a94
org.graylog2.database.NotFoundException: Input <5e2ee5c295125a0fb43e6a94> not found!
	at org.graylog2.inputs.InputServiceImpl.find(InputServiceImpl.java:187) ~[graylog.jar:?]
	at org.graylog2.inputs.InputEventListener.inputCreated(InputEventListener.java:62) [graylog.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) [graylog.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) [graylog.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
2020-01-27 13:29:39,465 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <5e2ee5c295125a0fb43e6a94>: Input <5e2ee5c295125a0fb43e6a94> not found!
2020-01-27 13:29:39,465 WARN : org.graylog2.filters.StaticFieldFilter - Unable to load input: Input <5e2ee5c295125a0fb43e6a94> not found!
2020-01-27 13:29:39,465 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <5e2ee5c295125a0fb43e6a94>: Input <5e2ee5c295125a0fb43e6a94> not found!
2020-01-27 13:29:39,465 WARN : org.graylog2.filters.StaticFieldFilter - Unable to load input: Input <5e2ee5c295125a0fb43e6a94> not found!
2020-01-27 13:29:39,465 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <5e2ee5c295125a0fb43e6a94>: Input <5e2ee5c295125a0fb43e6a94> not found!
2020-01-27 13:29:39,465 WARN : org.graylog2.filters.StaticFieldFilter - Unable to load input: Input <5e2ee5c295125a0fb43e6a94> not found!
2020-01-27 13:29:39,466 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <5e2ee5c295125a0fb43e6a94>: Input <5e2ee5c295125a0fb43e6a94> not found!
2020-01-27 13:29:39,466 WARN : org.graylog2.filters.StaticFieldFilter - Unable to load input: Input <5e2ee5c295125a0fb43e6a94> not found!
2020-01-27 13:29:39,468 WARN : org.graylog2.filters.ExtractorFilter - Unable to load input <5e2ee5c295125a0fb43e6a94>: Input <5e2ee5c295125a0fb43e6a94> not found!
</details>

## Steps to Reproduce (for bugs)

This issue is only reproducible in my test lab. I cannot cause it on my development machine, so I am not sure what the reproducible scenario is.

## Your Environment

Graylog Version: 3.2.0-beta.4-SNAPSHOT+cb33786 with a production build
Elasticsearch Version: 6.8.3
MongoDB Version: 3.4.2

**Comment by danotorrey** [comment]
This could be occurring due to something weird happening only in my development environment. I am happy to do more investigation if you have any suggestions on what to check.

**Comment by chalfling** [comment]
@danotorrey Are you trying to Install Dashbord from Graylog 3.1? I have exactly the same error trying to install Dashboards from 3.1 into 3.2(fresh install)

**Comment by kmerz** [comment]
This was fixed with: https://github.com/Graylog2/graylog2-server/issues/7180
