### ISSUE TITLE
Change CEF Parser: Use long for in and out 

### ISSUE THREAD

**Issue by Maheine** [Graylog2/graylog2-server#7371]
I’m forwarding log entries from a firewall in CEF format to graylog. Some entries are skipped, because the value of the field in and out are bigger than java integer.

`CEF:0|Manufacture|Firewall|FW Version|70026|Connection_Progress|0|in=85068772 out=8747876628 app=TSM rt=Jan 14 2020 13:49:37 deviceFacility=Packet Filtering deviceInboundInterface=0 proto=6 dpt=1500 spt=45004 dst=192.168.0.1 src=192.168.0.2
`
```
2020-01-14T13:49:37.727+01:00 WARN [MappedMessage] Could not transform CEF field [out] according to standard. Skipping.
    java.lang.NumberFormatException: For input string: “8747876628”
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_232]
    at java.lang.Integer.parseInt(Integer.java:583) ~[?:1.8.0_232]
    at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_232]
    at org.graylog.plugins.cef.parser.CEFMapping.convertInteger(CEFMapping.java:249) ~[graylog.jar:?]
    at org.graylog.plugins.cef.parser.CEFMapping.convert(CEFMapping.java:314) ~[graylog.jar:?]
    at org.graylog.plugins.cef.parser.MappedMessage.mapExtensions(MappedMessage.java:52) [graylog.jar:?]
    at org.graylog.plugins.cef.parser.MappedMessage.(MappedMessage.java:37) [graylog.jar:?]
    at org.graylog.plugins.cef.codec.CEFCodec.decodeCEF(CEFCodec.java:128) [graylog.jar:?]
    at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:112) [graylog.jar:?]
    at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:150) [graylog.jar:?]
    at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
    at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:86) [graylog.jar:?]
    at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:45) [graylog.jar:?]
    at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
    at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

I also asked the firewall manufacturer:

> In definition of CEF, some fields are defined as integer. For some specific fields valid range is also specified. 
> 
> However CEF documentation DOES NOT specify the integer in more detailed level. So it totally leaves out the question of valid integer range. When it comes to minint and maxint, those are totally implementation dependent. In fact int data type can be promised to be at least 16 bits long. - Other than that it is fully implementation specific even if some languages may have more standardized meaning for it. So if integer is used to describe something presented in ASCII format, it only specified the format but does not specific the valid range. 
> 
> Please note also that clearly integer in the CEF documentation can mean also something longer than 32 bit integer:
> 
> \"CEF supports several variations on time/date formats to accurately identify the time an event occurred. These formats are as follows:
> Milliseconds since January 1, 1970 (integer). (This time format supplies an integer with the count in milliseconds from January 1, 1970 to the time the event occurred.)\"
> 
> If the integer would be limited to 32 bit integer, this would overflow each month. So obviously CEF format must accept also longer integers. at least it must be able to handle numbers up to 1580733301527 (Which was timestamp today) and even larger before it is unable to deal with time values).
> 
> So there is no evidence that values in those fields would violate CEF standard. There is only evidence that graylog developers have made inaccurate assumptions and due to this are unable to deal with those log entries.
> 

Graylog v3.1.3

Is it possible, that the CEF parser uses long instead of integer for the in and out field?

Thanks

**Comment by laakkus** [comment]
Any progress on this bug/issue? Fortigate firewalls here. Lot's of log rows keep on coming..

**Comment by jothoma1** [comment]
Same here with fortinet

**Comment by riskersen** [comment]
+1

**Comment by tbenu** [comment]
Hi there,

still facing this issue in Graylog 4.3.7, logs sent from Check Point firewall via CEF. Took the time now for some deeper analysis.

Example server.log message:
```
2022-10-14T10:37:38.477+02:00 WARN  [MappedMessage] Could not transform CEF field [spt] according to standard. Skipping.
java.lang.NumberFormatException: For input string: "4294967295"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
        at org.graylog.plugins.cef.parser.CEFMapping.convertInteger(CEFMapping.java:249) ~[graylog.jar:?]
        at org.graylog.plugins.cef.parser.CEFMapping.convert(CEFMapping.java:314) ~[graylog.jar:?]
        at org.graylog.plugins.cef.parser.MappedMessage.mapExtensions(MappedMessage.java:52) [graylog.jar:?]
        at org.graylog.plugins.cef.parser.MappedMessage.<init>(MappedMessage.java:37) [graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decodeCEF(CEFCodec.java:128) [graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:117) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:156) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:94) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:95) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:49) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

It seems like Graylog tries to parse the spt (source port, hence technical value range 0-65535) with input string "4294967295", which is the maximum of an unsigned long (same value in all messages I saw regarding this). Besides the problem that spt in such logs obviously is not this huge number, but something in a meaningful range (double checked it), there shouldn't even be a problem in storing a max long in a field already considered a long (since it is the only number date type supported).

For debugging purposes, I started a raw string input for some of the logs. It looks totally fine, according to CEF standards (payload formatted as "key1=value1 key2=value2" etc.). Even the pipeline simulator is capable of parsing the logs completely. Still, I get above message in the logs, which happens for both spt (source port) and dpt (destination port), and also for a field called cnt (which will also be a long, but may really be too large, although it again states that "4294967295" is too big of a value for this field. Nice coincidence if that was really the value to be written to the field ;-)).

Since this problem only occurs every few minutes and there is no indication at all in the server.log regarding what concrete message is raising it, it is really hard to completely narrow down the error message and have a example log leading to the error. Looking at the original firewall log, the dpt and spt fields obviously only hold values in a int16 range (up to 65535).

Although it does not seem like we are losing data through this (we get a lot of firewall logs, so one single missing log is hard to identify with no more information...), is there any new information on this case? Anything that could be derived from the specific line in the java code?

Thanks in advance and best regards :)

**Comment by tellistone** [comment]
Customer raised feature request for this under HS-1158261632

**Comment by tellistone** [comment]
When this has been patched out in a release, can please comment on HS-1158261632 so we can inform customr.

**Comment by ryan-carroll-graylog** [comment]
I've opened a PR for this but had a couple questions before I finalize it.: https://github.com/Graylog2/graylog2-server/pull/13812

Since the CEF specification doesn't limit the size of most of its Integer values (with the exception of a few like port values, direction etc.), should all be able to accommodate longs?
Based on @tbenu 's comment it sounds like there are users who have logs with large values that are technically out of the valid CEF spec range, do we want to accommodate these as well? It seems like users might want that data to appear in the messages even if it's invalid.

**Comment by tellistone** [comment]
My 2c would be that we should support fields containing invalid/longer than expected values, as letting those be ingested is a preferable outcome to such messages failing silently at the input level and leaving the customer none the wiser as to what is happening.

**Comment by ryan-carroll-graylog** [comment]
> My 2c would be that we should support fields containing invalid/longer than expected values, as letting those be ingested is a preferable outcome to such messages failing silently at the input level and leaving the user none the wiser as to what is happening.

This makes the most sense to me. I'll update this to handle large values for all Integer fields.

**Comment by ihe-nu** [comment]
sometimes we have valus for "in" and "out" which is the sum of send/recived bytes. This value sometimes is above the max of 32bit - and it would be nice if we could catch it.

**Comment by bernd** [comment]
@ihe-nu The 4.3.9 release includes a fix to allow larger values for all numerical values. Including `in` and `out`.
