### ISSUE TITLE
Error when upgraded to 0.90 graylog-server: Latest 0.90 release 

### ISSUE THREAD

**Issue by zagros** [Graylog2/graylog2-server#739]
Here is the exception:

     
     2014-10-14 14:29:01,258 ERROR: com.google.common.util.concurrent.ServiceManager - Service ProcessBufferService [FAILED]
     has failed in the STARTING state.
     java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:\C:\graylog2-server\graylog2-server.jar!\blacklist
     .drl
             at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
             at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
             at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
             at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
             at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
             at java.io.File.toPath(File.java:2234)
             at org.graylog2.rules.DroolsEngine.createKJar(DroolsEngine.java:210)
             at org.graylog2.rules.DroolsEngine.createAndDeployJar(DroolsEngine.java:190)
             at org.graylog2.rules.DroolsEngine.deployRules(DroolsEngine.java:165)
             at org.graylog2.rules.DroolsEngine.commitRules(DroolsEngine.java:143)
             at org.graylog2.rules.DroolsEngine.<init>(DroolsEngine.java:67)
             at org.graylog2.rules.DroolsEngine$$FastClassByGuice$$33775601.newInstance(<generated>)
             at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
             at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java
     :60)
             at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
             at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
             at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
             at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
             at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
             at com.google.inject.Scopes$1$1.get(Scopes.java:65)
             at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
             at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
             at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
             at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
             at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
             at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
             at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
             at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
             at com.google.inject.Scopes$1$1.get(Scopes.java:65)
             at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
             at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:53)
             at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
             at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
             at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
             at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
             at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
             at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
             at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
             at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
             at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:326)
             at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:220)
             at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
             at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
             at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
             at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
             at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
             at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
             at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
             at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
             at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:632)
             at com.sun.proxy.$Proxy16.create(Unknown Source)
             at org.graylog2.initializers.ProcessBufferService.startUp(ProcessBufferService.java:63)
             at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
             at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
             at java.lang.Thread.run(Thread.java:744)
     Exception in thread "ProcessBufferService STARTING" java.nio.file.InvalidPathException: Illegal char <:> at index 4: fil
     e:\C:\graylog2-server\graylog2-server.jar!\blacklist.drl
             at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
             at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
             at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
             at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
             at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
             at java.io.File.toPath(File.java:2234)
             at org.graylog2.rules.DroolsEngine.createKJar(DroolsEngine.java:210)
             at org.graylog2.rules.DroolsEngine.createAndDeployJar(DroolsEngine.java:190)
             at org.graylog2.rules.DroolsEngine.deployRules(DroolsEngine.java:165)
             at org.graylog2.rules.DroolsEngine.commitRules(DroolsEngine.java:143)
             at org.graylog2.rules.DroolsEngine.<init>(DroolsEngine.java:67)
             at org.graylog2.rules.DroolsEngine$$FastClassByGuice$$33775601.newInstance(<generated>)
             at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
             at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java
     :60)
             at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
             at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
             at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
             at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
             at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
             at com.google.inject.Scopes$1$1.get(Scopes.java:65)
             at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
             at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
             at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
             at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
             at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
             at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
             at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
             at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
             at com.google.inject.Scopes$1$1.get(Scopes.java:65)
             at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
             at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:53)
             at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
             at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
             at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
             at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
             at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
             at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
             at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
             at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
             at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:326)
             at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:220)
             at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
             at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
             at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
             at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
             at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
             at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
             at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
             at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
             at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:632)
             at com.sun.proxy.$Proxy16.create(Unknown Source)
             at org.graylog2.initializers.ProcessBufferService.startUp(ProcessBufferService.java:63)
             at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
             at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
             at java.lang.Thread.run(Thread.java:744)
     2014-10-14 14:29:01,324 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet.
     Skipping periodic cluster check.
     2014-10-14 14:29:01,332 DEBUG: org.graylog2.periodical.ClusterHealthCheckThread - No input running in cluster!
     2014-10-14 14:29:01,343 DEBUG: org.graylog2.periodical.BatchedElasticSearchOutputFlushThread - Checking for outputs to f
     lush ...
     2014-10-14 14:29:01,344 DEBUG: org.graylog2.periodical.BatchedElasticSearchOutputFlushThread - Flushing output <org.gray
     log2.outputs.BatchedElasticSearchOutput@b383d7>
     2014-10-14 14:29:01,344 DEBUG: org.graylog2.outputs.BatchedElasticSearchOutput - Not flushing empty buffer
     2014-10-14 14:29:01,356 DEBUG: org.graylog2.periodical.IndexRetentionThread - Number of indices (0) lower than limit (20
     ). Not performing any retention actions.
     2014-10-14 14:29:01,359 DEBUG: org.graylog2.initializers.IndexerSetupService - Starting indexer

**Comment by bernd** [comment]
A fix for this is in Graylog 1.0.0. Closing this issue. Please re-open if you still see this with Graylog 1.0.0. Thank you!
