### ISSUE TITLE
Views migration error when series has dash (-) in field name

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#7439]
## Expected Behavior
The views migration should run with a series containing a dash (-) in the field name.

## Current Behavior
The migration breaks up with `unable to parse`.
```
2020-02-11T17:21:08.060+01:00 ERROR [ConfigurationManagementPeriodical] Error while running migration <V20191125144500_MigrateDashboardsToViews{2019-11-25T14:45:00Z}>
java.lang.RuntimeException: Unable to parse function: count(time-taken)
at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.viewwidgets.Series.toSeriesSpec(Series.java:60) ~[graylog.jar:?]
```

## Possible Solution
Fix the regex.

## Context
[z#843137]

## Your Environment
* Graylog Version: 3.2.1

**Comment by kakulacis** [comment]
I do not have dashes but I have underscores in field names of series. Graylog fails to migrate all dashboards. Following error is encountered:
`2020-02-11T10:36:40.194+02:00 ERROR [ConfigurationManagementPeriodical] Error while running migration <V20191125144500_MigrateDashboardsToViews{2019-11-25T14:45:00Z}>
java.lang.RuntimeException: Unable to parse function: avg(time-taken)
at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.viewwidgets.Series.toSeriesSpec(Series.java:60) ~[graylog.jar:?]
at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.AggregationWidget.lambda$toSearchTypes$2(AggregationWidget.java:82) ~[graylog.jar:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_212]
at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[?:1.8.0_212]
at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_212]
at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.AggregationWidget.toSearchTypes(AggregationWidget.java:82) ~[graylog.jar:?]
at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.V20191125144500_MigrateDashboardsToViews.createSearchType(V20191125144500_MigrateDashboardsToViews.java:186) ~[graylog.jar:?]
at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.V20191125144500_MigrateDashboardsToViews.lambda$migrateDashboard$5(V20191125144500_MigrateDashboardsToViews.java:154) ~[graylog.jar:?]
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_212]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_212]
at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.V20191125144500_MigrateDashboardsToViews.migrateDashboard(V20191125144500_MigrateDashboardsToViews.java:155) ~[graylog.jar:?]
at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.V20191125144500_MigrateDashboardsToViews.lambda$upgrade$0(V20191125144500_MigrateDashboardsToViews.java:90) ~[graylog.jar:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_212]
at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:390) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_212]
at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.V20191125144500_MigrateDashboardsToViews.upgrade(V20191125144500_MigrateDashboardsToViews.java:91) ~[graylog.jar:?]
at org.graylog2.periodical.ConfigurationManagementPeriodical.doRun(ConfigurationManagementPeriodical.java:43) [graylog.jar:?]
at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

Is this the same issue or i should open different issue?
Thanks!

**Comment by alex-konn** [comment]
Thanks a ton for your report @kakulacis! No need for a separate issue. I'll look into this and if it's indeed a separate problem will open an issue. In any case, we will aim to get both problems fixed for the 3.2.2 release.

**Comment by kakulacis** [comment]
Just to check that I've understood cause of a problem in this issue/ticket correctly. I'v similar to following series in mongodb:
                ```
"series" : [ 
                    {
                        "query" : "source:mailcleaner\\-gw01\\-prod\\-srv\\-vm\\-lv03.ad.tralala.biz AND Spam_status:is",
                        "field" : "Spam_status",
                        "statistical_function" : "count"
                    }, 
                    {
                        "query" : "source:mailcleaner\\-gw01\\-prod\\-srv\\-vm\\-lv03.ad.tralala.biz AND Spam_status:\"is not\"",
                        "field" : "Spam_status",
                        "statistical_function" : "count"
                    }
                ]
```

**Comment by alex-konn** [comment]
@kakulacis, underscores should work already. Looking at the stacktrace you posted, `Spam_status` doesn't seem to be the culprit, but rather `time-taken`. So you are indeed encountering the same issue.

**Comment by kakulacis** [comment]
Thank you!
When to expect fix? Days, weeks, months? Just want to know to decide if i need to recover mongodb database somehow and revert to version 3.2.1 for graylog or i can just wait for few days if this will be solved soon.

**Comment by alex-konn** [comment]
@kakulacis, 1-2 weeks probably. No guarantee though. :)
