### ISSUE TITLE
Documentation shows that encrypted self signed keys should work but they don't.

### ISSUE THREAD

**Issue by VDAAustin** [Graylog2/graylog2-server#7552]
As shown in the following documentation. It is expected that our private key can be encrypted.

https://docs.graylog.org/en/3.2/pages/configuration/https.html

`$ openssl pkcs8 -in pkcs5-plain.pem -topk8 -out pkcs8-encrypted.pem -passout pass:secret`

But if you use a encrypted key and password and the following configuration file as described in the documentation graylog will fail to start.

```
# Enable HTTPS support for the HTTP interface.
# This secures the communication with the HTTP interface with TLS to prevent request forgery and eavesdropping.
http_enable_tls = true

# The X.509 certificate chain file in PEM format to use for securing the HTTP interface.
http_tls_cert_file = /path/to/graylog-certificate.pem

# The PKCS#8 private key file in PEM format to use for securing the HTTP interface.
http_tls_key_file = /path/to/graylog-key.pem

# The password to unlock the private key used for securing the HTTP interface. (if key is encrypted)
http_tls_key_password = secret

```

If you comment out the password line and use a pkcs8plain key it all works as intended.

## Expected Behavior
I can use a encrypted PKCS8 key with a password

## Current Behavior
Using a encrypted PKCS8 key with a password prevents the system from starting.

## Possible Solution
Find reason encrypted PKCS8 keys break system.

## Steps to Reproduce (for bugs)
Follow documentation linked to.

## Context
Securing my web interface.

**Comment by mpfz0r** [comment]
The cause of this, is that SunJCE neither in Java 8 nor 11 can handle the PKCS#8 
that are encrypted with PBES2.

https://bugs.openjdk.java.net/browse/JDK-8076999
https://bugs.openjdk.java.net/browse/JDK-8202837

leading to this exception:
```	Suppressed: com.google.common.util.concurrent.ServiceManager$FailedService: JerseyService [FAILED]
	Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
		at sun.security.util.ObjectIdentifier.<init>(ObjectIdentifier.java:257) ~[?:1.8.0_252]
		at sun.security.util.DerInputStream.getOID(DerInputStream.java:314) ~[?:1.8.0_252]
		at com.sun.crypto.provider.PBES2Parameters.engineInit(PBES2Parameters.java:267) ~[sunjce_provider.jar:1.8.0_252]
		at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293) ~[?:1.8.0_252]
		at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:137) ~[?:1.8.0_252]
		at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:119) ~[?:1.8.0_252]
		at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:393) ~[?:1.8.0_252]
		at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:95) ~[?:1.8.0_252]
		at org.graylog2.shared.security.tls.PemKeyStore.generateKeySpec(PemKeyStore.java:69) ~[classes/:?]
		at org.graylog2.shared.security.tls.PemKeyStore.buildKeyStore(PemKeyStore.java:98) ~[classes/:?]
		at org.graylog2.shared.initializers.JerseyService.buildSslEngineConfigurator(JerseyService.java:349) ~[classes/:?]
		at org.graylog2.shared.initializers.JerseyService.startUpApi(JerseyService.java:173) ~[classes/:?]
		at org.graylog2.shared.initializers.JerseyService.startUp(JerseyService.java:147) ~[classes/:?]
		at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62) ~[guava-28.2-jre.jar:?]
		at com.google.common.util.concurrent.Callables$4.run(Callables.java:119) ~[guava-28.2-jre.jar:?]
		at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
```

As a workaround, you can create old PBES1 encrypted keys using:
`$ openssl pkcs8 -in pkcs5-plain.pem -topk8 -out pkcs8-encrypted.pem -passout pass:secret -v1 PBE-SHA1-3DES`

I'm preparing a fix that is using Bouncy Castle instead, which can handle both formats properly.
