### ISSUE TITLE
Error while installing dashboard from content pack.

### ISSUE THREAD

**Issue by infosecwatchman** [Graylog2/graylog2-server#7562]
Hello, 
I'm trying to follow the instructions from https://www.graylog.org/post/back-to-basics-enhance-windows-security-with-sysmon-and-graylog. And after I figured out some of the issues with the pipeline rules, I tried to install the dashboard I downloaded from this post, but after I upload it and try to install, I get an error. 
`Error
Installing content pack failed with status: Error: cannot POST http://<IP>:9000/api/system/content_packs/01942853-9750-4a59-848d-289f27dfb46c/0/installations (500). Could not install content pack with ID: 01942853-9750-4a59-848d-289f27dfb46c`

I've tried to install a few dashboards but I get the same error for all dashboards. 
![graylog_error](https://user-images.githubusercontent.com/26226268/75389096-00dc0c00-58b4-11ea-99c9-76678e44e26a.png)

**Comment by dennisoelkers** [comment]
Thanks for reporting this to us, @infosecwatchman!

Can you take a look at the Graylog server logs and check if there is more information about the error, including a stack trace?

**Comment by infosecwatchman** [comment]
@dennisoelkers I'm running graylog on docker, and the log files on not their default location, do you know where they are located? There are no indexing errors logged in the dashboard view in the past 24 hours.

**Comment by infosecwatchman** [comment]
After viewing the docker logs, I was not able to find any error regarding the install, but I was getting messages in the graylog logs with docker, but not in the dashboard. Any tips on fixing these errors? They are flooding the docker. 
`2020-02-24 21:40:13,823 WARN : org.graylog2.indexer.messages.Messages - Failed to index message: index=<graylog_2> id=<3d443fdb-574e-11ea-a1f6-0242ac130004> error=<{"type":"mapper_parsing_exception","reason":"failed to parse field [level] of type [long] in document with id '3d443fdb-574e-11ea-a1f6-0242ac130004'","caused_by":{"type":"illegal_argument_exception","reason":"For input string: \"Information\""}}>
2020-02-24 21:40:13,823 WARN : org.graylog2.indexer.messages.Messages - Failed to index message: index=<graylog_2> id=<3d443fdc-574e-11ea-a1f6-0242ac130004> error=<{"type":"mapper_parsing_exception","reason":"failed to parse field [level] of type [long] in document with id '3d443fdc-574e-11ea-a1f6-0242ac130004'","caused_by":{"type":"illegal_argument_exception","reason":"For input string: \"Information\""}}>
2020-02-24 21:40:13,823 WARN : org.graylog2.indexer.messages.Messages - Failed to index message: index=<graylog_2> id=<3d443fde-574e-11ea-a1f6-0242ac130004> error=<{"type":"mapper_parsing_exception","reason":"failed to parse field [level] of type [long] in document with id '3d443fde-574e-11ea-a1f6-0242ac130004'","caused_by":{"type":"illegal_argument_e^C2020-02-24 21:40:13,823 WARN : org.graylog2.indexer.messages.Messages - Failed to index message: index=<graylog_2> id=<3d443fdd-574e-11ea-a1f6-0242ac130004> error=<{"type":"mapper_parsing_exception","reason":"failed to parse field [level] of type [long] in document with id '3d443fdd-574e-11ea-a1f6-0242ac130004'","caused_by":{"type":"illegal_argument_exception","reason":"For input string: \"Information\""}}>
2020-02-24 21:40:13,823 WARN : org.graylog2.indexer.messages.Messages - Failed to index message: index=<graylog_2> id=<3d443fe2-574e-11ea-a1f6-0242ac130004> error=<{"type":"mapper_parsing_exception","reason":"failed to parse field [level] of type [long] in document with id '3d443fe2-574e-11ea-a1f6-0242ac130004'","caused_by":{"type":"illegal_argument_exception","reason":"For input string: \"Warning\""}}>`

**Comment by infosecwatchman** [comment]
Apologies if you saw my previous post, I was mistaken on the logs, I relooked at the logs, and here is the actual error, from when I try to install the sysmon dashboard. 
`java.lang.IllegalArgumentException: Unsupported content pack version: 0
        at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:101) ~[graylog.jar:?]
        at org.graylog2.rest.resources.system.contentpacks.ContentPackResource.installContentPack(ContentPackResource.java:293) ~[graylog.jar:?]
        at sun.reflect.GeneratedMethodAccessor957.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`
