### ISSUE TITLE
Old dashboard parsing broken after update to 3.2.2

### ISSUE THREAD

**Issue by hasso** [Graylog2/graylog2-server#7583]
After update from 3.1.x to 3.2.2 one of our older dashboards broke Dashboards view in UI – it gave 500 errors. We resolved issue temporarily with removing dashboard at all from dashboards and views collections in mongodb.

Snippet from log:

```
ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:67) ~[graylog.jar:?]
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:49) ~[graylog.jar:?]
        ...
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.graylog.plugins.views.search.searchtypes.pivot.buckets.TimeUnitInterval$Builder`, problem: Time unit must be {quantity}{unit}, where quantity is a positive number and unit [smhdwM].
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@11f5586e; pos: 3165] (through reference chain: org.graylog.plugins.views.search.AutoValue_Search$Builder["queries"]->org.graylog.plugins.views.search.AutoValue_Query$Builder["search_types"]->java.util.HashSet[6]->org.graylog.plugins.views.search.searchtypes.pivot.AutoValue_Pivot$Builder["row_groups"]->java.util.ArrayList[0]->org.graylog.plugins.views.search.searchtypes.pivot.buckets.AutoValue_Time$Builder["interval"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1073) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapInstantiationProblem(BeanDeserializerBase.java:1754) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.finishBuild(BuilderBasedDeserializer.java:178) ~[graylog.jar:?]
        ...
Caused by: java.lang.IllegalArgumentException: Time unit must be {quantity}{unit}, where quantity is a positive number and unit [smhdwM].
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141) ~[graylog.jar:?]
	at org.graylog.plugins.views.search.searchtypes.pivot.buckets.TimeUnitInterval$Builder.build(TimeUnitInterval.java:80) ~[graylog.jar:?]
	at sun.reflect.GeneratedMethodAccessor270.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        ...
```
Slightly anonymized problematic document: [dashboard3.txt](https://github.com/Graylog2/graylog2-server/files/4266427/dashboard3.txt)

* Graylog Version: 3.2.2
* Elasticsearch Version: 6.8.6
* MongoDB Version: Percona v4.0.16-9
* Operating System: Linux x64
* Browser version: Firefox

**Comment by dennisoelkers** [comment]
Hey @hasso! 
Thanks for reporting this and including the required information that will help us reproducing it. We will look into this issue and see if we can fix it for one of the next patch releases.

**Comment by dennisoelkers** [comment]
Hey @hasso,

the document you provided is the dashboard after the migration. Could you provide an anonymized version of the dashboard _before_ the migration? That would help a lot. It is in the `dashboards` collection and has the same id before and after.

**Comment by hasso** [comment]
Here it is from slightly older backup (I don't think that there was any changes since then, but I'm not 100% sure though) - [dashboard4.txt](https://github.com/Graylog2/graylog2-server/files/4297910/dashboard4.txt).
