### ISSUE TITLE
kubernetes helm /etc/graylog/server/GeoLite2-City.mmdb path for the GeoIP plugin is hardcoded. 

### ISSUE THREAD

**Issue by titansmc** [Graylog2/graylog2-server#7647]
## Expected Behavior

When I customize the location (Graylog running under k8s through stable/graylog helm chart) of the MaxMind's GeoLite2-City.mmdb file and enable the plugin with the new location in the configuration, it is expected to work.
## Current Behavior

Instead, the plugin does not work and produces error logs saying the geoip database not found at /etc/graylog/server/GeoLite2-City.mmdb (which is the default path). So it seems that the default path is effectively hardcoded.

##  Steps to Reproduce (for bugs)

   Basic deployment through helm

## Context
The kubernetes helm deployment has a configmap that pulls the DB from a URL and puts it into ```/usr/shar/graylog/geoip/``` . Then it tries to load it from /etc location and doesn't matter if you try to reset a new one from the webUI

```
Current master is 
Self IP is 10.133.84.26
Launching graylog-0 as master
pod/graylog-0 labeled
Downloading Graylog Plugins...
Downloading https://github.com/irgendwr/TelegramAlert/releases/download/v2.3.0/graylog-plugin-telegram-notification-2.3.0.jar ...
Downloading https://github.com/graylog-labs/graylog-plugin-metrics-reporter/releases/download/3.0.0/metrics-reporter-prometheus-3.0.0.jar ...
Downloading Maxmind GeoLite2 ...
GeoLite2-City_20200121/GeoLite2-City.mmdb
Starting graylog
Graylog Home /usr/share/graylog

2020-03-06 10:34:19,331 ERROR   [FileInfo] - Couldn't get file info for path: /etc/graylog/server/GeoLite2-City.mmdb - {}
java.nio.file.NoSuchFileException: /etc/graylog/server/GeoLite2-City.mmdb
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_242]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_242]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_242]
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:1.8.0_242]
```

## Your Environment

    Graylog Version: 3.2.2 (Docker image tag)
    Elasticsearch Version: 6.8.2 (Docker image tag)
    MongoDB Version: 3 (Docker image tag)
    Operating System: Ubuntu 18.04

**Comment by titansmc** [comment]
Hi,
Is there any update on this? Or something I could help with?

Cheers.

**Comment by titansmc** [comment]
@bernd Hi, is there any update on this?

Cheers.
