### ISSUE TITLE
Sharing view and server generates error 

### ISSUE THREAD

**Issue by skwokie** [Graylog2/graylog2-server#7688]
When I try to share a view using the api (/api/api-browser/global/index.html#!/Views/Sharing/create_post_2), the curl command returns `{"type":"ApiError","message":""}`:
```
$ curl --location --request POST 'http://dev-graylog.xxx.com/api/views/5e6aba264234877356fa2282/share' \
> --header 'X-Requested-by: test' \
> --header 'Authorization: Basic xxx'
{"type":"ApiError","message":""}

```

The server generates:
```
graylog_1        | 2020-03-14 21:10:31,765 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
graylog_1        | java.lang.NullPointerException: null
graylog_1        | 	at org.graylog.plugins.views.search.views.sharing.ViewSharingService.create(ViewSharingService.java:51) ~[graylog.jar:?]
graylog_1        | 	at org.graylog.plugins.views.search.rest.ViewSharingResource.create(ViewSharingResource.java:79) ~[graylog.jar:?]
graylog_1        | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
graylog_1        | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
graylog_1        | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
graylog_1        | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
graylog_1        | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
graylog_1        | 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
graylog_1        | 	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
graylog_1        | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
graylog_1        | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
graylog_1        | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

## Context
Here is the detail returned by calling /api/views/{id} on the view:
```
{
    "id": "5e6aba264234877356fa2282",
    "type": "SEARCH",
    "title": "Activity Logs",
    "summary": "",
    "description": "",
    "search_id": "5e6ab5ee4234877356fa2281",
    "properties": [],
    "requires": {},
    "state": {
        "1d67e90c-19d3-43a0-bfff-bd2e2f34bb5a": {
            "selected_fields": null,
            "static_message_list_id": null,
            "titles": {
                "widget": {
                    "4027c8f0-7a8b-441b-af71-560d8750b8f1": "Message Count",
                    "03ca4a43-06d1-4f08-ba7a-323f220ba9e2": "All Messages"
                }
            },
            "widgets": [
                {
                    "id": "03ca4a43-06d1-4f08-ba7a-323f220ba9e2",
                    "type": "messages",
                    "filter": null,
                    "timerange": null,
                    "query": null,
                    "streams": [],
                    "config": {
                        "fields": [
                            "timestamp",
                            "source",
                            "username",
                            "message"
                        ],
                        "show_message_row": true,
                        "decorators": []
                    }
                },
                {
                    "id": "4027c8f0-7a8b-441b-af71-560d8750b8f1",
                    "type": "aggregation",
                    "filter": null,
                    "timerange": null,
                    "query": null,
                    "streams": [],
                    "config": {
                        "row_pivots": [
                            {
                                "field": "timestamp",
                                "type": "time",
                                "config": {
                                    "interval": {
                                        "type": "auto",
                                        "scaling": null
                                    }
                                }
                            }
                        ],
                        "column_pivots": [],
                        "series": [
                            {
                                "config": {
                                    "name": null
                                },
                                "function": "count()"
                            }
                        ],
                        "sort": [],
                        "visualization": "bar",
                        "visualization_config": null,
                        "formatting_settings": null,
                        "rollup": true,
                        "event_annotation": false
                    }
                }
            ],
            "widget_mapping": {
                "4027c8f0-7a8b-441b-af71-560d8750b8f1": [
                    "5d867b6e-bf7d-4268-aacd-833f2d4de4f1"
                ],
                "03ca4a43-06d1-4f08-ba7a-323f220ba9e2": [
                    "158c16ce-cbc2-44c5-b5f6-800155c777e1"
                ]
            },
            "positions": {
                "4027c8f0-7a8b-441b-af71-560d8750b8f1": {
                    "col": 1,
                    "row": 1,
                    "height": 2,
                    "width": "Infinity"
                },
                "03ca4a43-06d1-4f08-ba7a-323f220ba9e2": {
                    "col": 1,
                    "row": 3,
                    "height": 6,
                    "width": "Infinity"
                }
            },
            "formatting": {
                "highlighting": []
            },
            "display_mode_settings": {
                "positions": {}
            }
        }
    },
    "owner": "x@xxx.com",
    "created_at": "2020-03-12T22:21:20.757Z"
}
```

## Your Environment

I'm running the docker-compose file provided in the Graylog docs using the 3.2.2 Graylog image: https://docs.graylog.org/en/3.1/pages/installation/docker.html#persisting-data
* Graylog Version: 3.2.2
* Elasticsearch Version: 6.8.2
* MongoDB Version: 3
* Operating System: Ubuntu 18.04.3 LTS
* Curl version: 7.54.0 (x86_64-apple-darwin18.0)

Thank you!

**Comment by dennisoelkers** [comment]
Thanks for reporting this, @skwokie!

The underlying issue is that you are not supplying a request body when `POST`ing to the endpoint. It expects something like this:

```
{
  "type": "users",
  "view_id": "5e6aba264234877356fa2282",
  "users": ["someuser", "otheruser"]
}
```

Nevertheless, it should not return a NPE but an http 400 and a proper message instead. We are fixing that.

**Comment by skwokie** [comment]
Thanks for your response, @dennisoelkers !
Can you please tell me the definition for "type"? I suppose "users" is for setting who to share with, then what should I set there if I want to share it with all users?

**Comment by skwokie** [comment]
Besides, I've tried the following calls, and they return `{"type":"ApiError","message":"HTTP 415 Unsupported Media Type"}`. Can you please take a look and then me know what I've missed? Thanks.
```
$ curl --location --request POST 'http://dev-graylog.xxx.com/api/views/5e6aba264234877356fa2282/share' \
> --header 'X-Requested-by: test' \
> --header 'Authorization: Basic xxx' \
> --data-raw '{
>   "type": "users",
>   "view_id": "5e6aba264234877356fa2282",
>   "users": ["admin"]
> }'
{"type":"ApiError","message":"HTTP 415 Unsupported Media Type"}
$ curl --location --request POST 'http://dev-graylog.xxx.com/api/views/5e6aba264234877356fa2282/share' --header 'X-Requested-by: test' --header 'Authorization: Basic xxx' --data-raw '{
  "type": "users",
  "view_id": "5e6aba264234877356fa2282",
  "users": ["a@gmail.com"]
}'
{"type":"ApiError","message":"HTTP 415 Unsupported Media Type"}
$ curl --location --request POST 'http://dev-graylog.xxx.com/api/views/5e6aba264234877356fa2282/share' --header 'X-Requested-by: test' --header 'Authorization: Basic xxx' --data-raw '{
  "type": "users",
  "view_id": "5e6aba264234877356fa2282",
  "users": ["*"]
}'
{"type":"ApiError","message":"HTTP 415 Unsupported Media Type"}
```

**Comment by skwokie** [comment]
Hi, sorry didn't mean to rush. Can I follow up on this, please?

**Comment by dennisoelkers** [comment]
These are the different sharing options:

- [With specific Users](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/SpecificUsers.java)
- [With specific Roles](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/SpecificRoles.java)
- [All users of instance](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/AllUsersOfInstance.java)
