### ISSUE TITLE
passwords with space in the configuration file not working

### ISSUE THREAD

**Issue by sajithkc** [Graylog2/graylog2-server#7727]
Graylog is not accepting passwords with space in the configuration file. Its throwing java exception.

## Expected Behavior

Password with space should work

## Current Behavior

Even with quotes or replacing space with \u0020, graylog is not accepting space in the password. From logs, I am getting following error message

Caused by: java.net.URISyntaxException: Illegal character in authority at index 8: https://elastic:password with space@elasticsearch:9200
        at java.net.URI$Parser.fail(URI.java:2848) ~[?:1.8.0_242]
        at java.net.URI$Parser.parseAuthority(URI.java:3186) ~[?:1.8.0_242]
        at java.net.URI$Parser.parseHierarchical(URI.java:3097) ~[?:1.8.0_242]
        at java.net.URI$Parser.parse(URI.java:3053) ~[?:1.8.0_242]
        at java.net.URI.<init>(URI.java:588) ~[?:1.8.0_242]
        at org.graylog2.configuration.converters.URIListConverter.constructURIFromString(URIListConverter.java:64) ~[graylog.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242]
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_242]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_242]
        at org.graylog2.configuration.converters.URIListConverter.convertFrom(URIListConverter.java:48) ~[graylog.jar:?]
        at org.graylog2.configuration.converters.URIListConverter.convertFrom(URIListConverter.java:32) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.convertStringValue(JadConfig.java:167) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:139) ~[graylog.jar:?]

## Steps to Reproduce (for bugs)

Change password of elasticsearch which contains spaces
Update the password in server.conf
Restart graylog
Graylog throws URISyntaxException for Illegal character.

## Your Environment

* Graylog Version: 3.2.3-1
* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.0.17
* Operating System: Ubuntu 18.04.4
* Browser version:

**Comment by sajithkc** [comment]
Closing this issue as this was opened as duplicate of #6571
