### ISSUE TITLE
Handle null `query` when migrating dashboards

### ISSUE THREAD

**Issue by Aluxima** [Graylog2/graylog2-server#7781]
## Expected Behavior

Dashboards should be migrated after Graylog 3.2 upgrade from 3.1.

## Current Behavior

The migration fails because of a null QuickValuesConfig.query.

```
2020-03-30T11:31:29.204+02:00 ERROR [ConfigurationManagementPeriodical] Error while running migration <V20191125144500_MigrateDashboardsToViews{2019-11-25T14:45:00Z}>
java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
        at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:67) ~[graylog.jar:?]
        at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:49) ~[graylog.jar:?]
        at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:29) ~[graylog.jar:?]
        at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52) ~[graylog.jar:?]
        at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[graylog.jar:?]
        at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101) ~[graylog.jar:?]
        at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[graylog.jar:?]
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[graylog.jar:?]
        at com.mongodb.connection.ReplyMessage.<init>(ReplyMessage.java:51) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:301) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255) ~[graylog.jar:?]
        at com.mongodb.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:98) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:441) ~[graylog.jar:?]
        at com.mongodb.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:80) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:189) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:264) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:126) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:118) ~[graylog.jar:?]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:226) ~[graylog.jar:?]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:217) ~[graylog.jar:?]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:120) ~[graylog.jar:?]
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:717) ~[graylog.jar:?]
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:711) ~[graylog.jar:?]
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:471) ~[graylog.jar:?]
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:415) ~[graylog.jar:?]
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:711) ~[graylog.jar:?]
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:83) ~[graylog.jar:?]
        at com.mongodb.Mongo$3.execute(Mongo.java:826) ~[graylog.jar:?]
        at com.mongodb.Mongo$3.execute(Mongo.java:813) ~[graylog.jar:?]
        at com.mongodb.DBCursor.initializeCursor(DBCursor.java:877) ~[graylog.jar:?]
        at com.mongodb.DBCursor.hasNext(DBCursor.java:144) ~[graylog.jar:?]
        at org.mongojack.DBCursor.hasNext(DBCursor.java:330) ~[graylog.jar:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:115) ~[?:1.8.0_201]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_201]
        at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.V20191125144500_MigrateDashboardsToViews.upgrade(V20191125144500_MigrateDashboardsToViews.java:91) ~[graylog.jar:?]
        at org.graylog2.periodical.ConfigurationManagementPeriodical.doRun(ConfigurationManagementPeriodical.java:43) [graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.dashboardwidgets.QuickValuesConfig`, problem: Null query
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@402e1f10; pos: 1783] (through reference chain: org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.Dashboard["widgets"]->java.util.ArrayList[2])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:484) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:503) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:116) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromObject(AsArrayTypeDeserializer.java:61) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.ExternalTypeHandler._deserializeAndSet(ExternalTypeHandler.java:372) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.ExternalTypeHandler.handlePropertyValue(ExternalTypeHandler.java:191) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeWithExternalTypeId(BuilderBasedDeserializer.java:731) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeWithExternalTypeId(BuilderBasedDeserializer.java:695) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeFromObject(BuilderBasedDeserializer.java:293) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:195) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3985) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2343) ~[graylog.jar:?]
        at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:80) ~[graylog.jar:?]
        at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:64) ~[graylog.jar:?]
        ... 46 more
Caused by: java.lang.NullPointerException: Null query
        at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.dashboardwidgets.AutoValue_QuickValuesConfig.<init>(AutoValue_QuickValuesConfig.java:48) ~[graylog.jar:?]
Caused by: java.lang.NullPointerException: Null query
        at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.dashboardwidgets.AutoValue_QuickValuesConfig.<init>(AutoValue_QuickValuesConfig.java:48) ~[graylog.jar:?]
        at org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.dashboardwidgets.QuickValuesConfig.create(QuickValuesConfig.java:198) ~[graylog.jar:?]
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call(AnnotatedMethod.java:109) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:116) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromObject(AsArrayTypeDeserializer.java:61) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.ExternalTypeHandler._deserializeAndSet(ExternalTypeHandler.java:372) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.ExternalTypeHandler.handlePropertyValue(ExternalTypeHandler.java:191) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeWithExternalTypeId(BuilderBasedDeserializer.java:731) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeWithExternalTypeId(BuilderBasedDeserializer.java:695) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeFromObject(BuilderBasedDeserializer.java:293) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:195) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3985) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2343) ~[graylog.jar:?]
        at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:80) ~[graylog.jar:?]
        at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:64) ~[graylog.jar:?]
        ... 46 more
```

## Possible Solution

The same problem was issued and fixed for null fields in SavedSearches: https://github.com/Graylog2/graylog2-server/issues/7362   

## Your Environment

* Graylog Version: 3.2.4

**Comment by dennisoelkers** [comment]
Hey @Aluxima,

thanks for reporting this! Is there a chance that you could provide a JSON of your (anonymized) dashboard as retrieved from mongodb? This would help us a lot debugging and fixing this issue.

**Comment by Aluxima** [comment]
Hi @dennisoelkers thank you for your quick response,

Here is the json of one of the dashboards with an empty query:

```
{
        "_id" : ObjectId("REMOVED"),
        "creator_user_id" : "REMOVED",
        "description" : "REMOVED",
        "created_at" : ISODate("2016-10-27T09:59:08.709Z"),
        "positions" : {
                "REMOVED" : {
                        "width" : 2,
                        "col" : 1,
                        "row" : 1,
                        "height" : 6
                },
                "REMOVED" : {
                        "width" : 2,
                        "col" : 1,
                        "row" : 7,
                        "height" : 4
                },
                "REMOVED" : {
                        "width" : 2,
                        "col" : 3,
                        "row" : 1,
                        "height" : 6
                },
                "REMOVED" : {
                        "width" : 2,
                        "col" : 5,
                        "row" : 1,
                        "height" : 6
                }
        },
        "title" : "REMOVED",
        "widgets" : [
                {
                        "creator_user_id" : "REMOVED",
                        "cache_time" : 10,
                        "description" : "REMOVED",
                        "id" : "REMOVED",
                        "type" : "QUICKVALUES",
                        "config" : {
                                "timerange" : {
                                        "type" : "relative",
                                        "range" : 3600
                                },
                                "field" : "tagid",
                                "stream_id" : "REMOVED",
                                "query" : "",
                                "show_data_table" : true,
                                "show_pie_chart" : true
                        }
                },
                {
                        "creator_user_id" : "REMOVED",
                        "cache_time" : 10,
                        "description" : "REMOVED",
                        "id" : "REMOVED",
                        "type" : "QUICKVALUES",
                        "config" : {
                                "timerange" : {
                                        "type" : "relative",
                                        "range" : 3600
                                },
                                "field" : "log_module",
                                "stream_id" : "REMOVED",
                                "query" : "",
                                "show_data_table" : true,
                                "show_pie_chart" : true
                        }
                },
                {
                        "creator_user_id" : "REMOVED",
                        "cache_time" : 10,
                        "description" : "REMOVED",
                        "id" : "REMOVED",
                        "type" : "QUICKVALUES",
                        "config" : {
                                "timerange" : {
                                        "type" : "relative",
                                        "range" : 3600
                                },
                                "field" : "segs",
                                "stream_id" : "REMOVED",
                                "query" : "",
                                "show_data_table" : true,
                                "show_pie_chart" : true
                        }
                },
                {
                        "creator_user_id" : "REMOVED",
                        "cache_time" : 10,
                        "description" : "REMOVED",
                        "id" : "REMOVED",
                        "type" : "QUICKVALUES",
                        "config" : {
                                "timerange" : {
                                        "type" : "relative",
                                        "range" : 3600
                                },
                                "field" : "loglevel",
                                "stream_id" : "REMOVED",
                                "query" : "",
                                "show_data_table" : true,
                                "show_pie_chart" : false
                        }
                }
        ]
}

```

Thank you

**Comment by dennisoelkers** [comment]
Are you sure that this is the dashboard producing the error? Because all widgets of this dashboard have an empty (`""`) query field, but it's not `null`.

**Comment by Aluxima** [comment]
You're right.
I was able to retrieve all dashboards that have no `widgets.config.query` or no `widgets` at all.
I hope it helps :

```
{
	"_id" : ObjectId("5820867b3aca0005d24d6323"),
	"creator_user_id" : "REMOVED",
	"description" : "REMOVED",
	"created_at" : ISODate("2016-11-07T13:49:47.014Z"),
	"title" : "REMOVED"
}
{
	"_id" : ObjectId("589a06093ee8ce0c162eca04"),
	"creator_user_id" : "REMOVED",
	"description" : "REMOVED",
	"created_at" : ISODate("2017-02-07T17:38:17.430Z"),
	"title" : "REMOVED"
}
{
	"_id" : ObjectId("58cbf6023ee8ce08aafa5f22"),
	"creator_user_id" : "REMOVED",
	"description" : "REMOVED",
	"created_at" : ISODate("2017-03-17T14:43:14.741Z"),
	"positions" : {
		"b94e5942-6050-4752-91af-3ceaab515a31" : {
			"width" : 4,
			"col" : 1,
			"row" : 1,
			"height" : 2
		},
		"316a054c-a752-436a-b29f-8b7019116bbf" : {
			"width" : 4,
			"col" : 1,
			"row" : 3,
			"height" : 2
		},
		"af6e04f8-9dd2-4c8a-8265-5c98c3f1f7b4" : {
			"width" : 2,
			"col" : 7,
			"row" : 7,
			"height" : 2
		},
		"fe6898f6-345e-4cee-bf59-c3e29e835a63" : {
			"width" : 2,
			"col" : 3,
			"row" : 7,
			"height" : 2
		},
		"d7a24ba7-1064-47c0-924e-abfa6f14e919" : {
			"width" : 2,
			"col" : 5,
			"row" : 7,
			"height" : 2
		},
		"13135d92-1731-4846-ab03-94cab273c8cd" : {
			"width" : 2,
			"col" : 5,
			"row" : 1,
			"height" : 6
		},
		"e4652d71-fdcd-4bc1-9a24-cb04544354f0" : {
			"width" : 2,
			"col" : 7,
			"row" : 1,
			"height" : 6
		},
		"921c36de-50ab-47f6-a02c-a0e4394e7bee" : {
			"width" : 2,
			"col" : 9,
			"row" : 1,
			"height" : 6
		},
		"2a225087-442e-48e0-b6a0-46577d0e4cbb" : {
			"width" : 4,
			"col" : 1,
			"row" : 5,
			"height" : 2
		}
	},
	"title" : "REMOVED",
	"widgets" : [
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "b94e5942-6050-4752-91af-3ceaab515a31",
			"type" : "SEARCH_RESULT_CHART",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 86400
				},
				"interval" : "day",
				"stream_id" : "58c7bfabac710408ae5b60b7"
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "316a054c-a752-436a-b29f-8b7019116bbf",
			"type" : "SEARCH_RESULT_CHART",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 604800
				},
				"interval" : "day",
				"stream_id" : "58c7bfabac710408ae5b60b7"
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "13135d92-1731-4846-ab03-94cab273c8cd",
			"type" : "QUICKVALUES",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 86400
				},
				"field" : "type",
				"show_pie_chart" : true,
				"stream_id" : "58c7bfabac710408ae5b60b7",
				"show_data_table" : true
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "e4652d71-fdcd-4bc1-9a24-cb04544354f0",
			"type" : "QUICKVALUES",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 604800
				},
				"field" : "type",
				"show_pie_chart" : true,
				"stream_id" : "58c7bfabac710408ae5b60b7",
				"show_data_table" : true
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "fe6898f6-345e-4cee-bf59-c3e29e835a63",
			"type" : "STREAM_SEARCH_RESULT_COUNT",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 86400
				},
				"lower_is_better" : false,
				"trend" : false,
				"stream_id" : "58c7bfabac710408ae5b60b7",
				"query" : "NOT type:r"
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "d7a24ba7-1064-47c0-924e-abfa6f14e919",
			"type" : "STREAM_SEARCH_RESULT_COUNT",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 604800
				},
				"lower_is_better" : false,
				"trend" : false,
				"stream_id" : "58c7bfabac710408ae5b60b7",
				"query" : "NOT type:r"
			}
		}
	]
}
{
	"_id" : ObjectId("58cbfc063ee8ce08aafa6581"),
	"creator_user_id" : "REMOVED",
	"description" : "REMOVED",
	"created_at" : ISODate("2017-03-17T15:08:54.881Z"),
	"positions" : {
		"45fddafb-2528-4fc2-84cd-7e4213e1a04d" : {
			"width" : 4,
			"col" : 1,
			"row" : 3,
			"height" : 2
		},
		"3a7f4742-b11f-45a5-9311-d00ab4b6dd92" : {
			"width" : 2,
			"col" : 3,
			"row" : 7,
			"height" : 2
		},
		"b00b31b4-66b4-4b09-95d6-588e72d524ca" : {
			"width" : 2,
			"col" : 9,
			"row" : 1,
			"height" : 6
		},
		"1c8ef63d-af90-4f5a-aee2-21870fa87f1c" : {
			"width" : 2,
			"col" : 5,
			"row" : 1,
			"height" : 6
		},
		"701cfde5-b884-4029-a5f3-51bd4e537451" : {
			"width" : 2,
			"col" : 7,
			"row" : 7,
			"height" : 2
		},
		"fd0f6680-1871-4108-8917-d1aa4f9a4c9a" : {
			"width" : 2,
			"col" : 7,
			"row" : 1,
			"height" : 6
		},
		"b7aaaca8-dd2f-4924-9bf4-8390ff0d60e4" : {
			"width" : 4,
			"col" : 1,
			"row" : 5,
			"height" : 2
		},
		"72bb1535-d942-490f-acc0-6942913a481b" : {
			"width" : 4,
			"col" : 1,
			"row" : 1,
			"height" : 2
		},
		"6120d73e-b65c-4bf7-ac8b-9efc9007c577" : {
			"width" : 2,
			"col" : 5,
			"row" : 7,
			"height" : 2
		}
	},
	"title" : "REMOVED",
	"widgets" : [
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "1c8ef63d-af90-4f5a-aee2-21870fa87f1c",
			"type" : "QUICKVALUES",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 86400
				},
				"field" : "type",
				"show_pie_chart" : true,
				"stream_id" : "58c7cce7ac710408ae5b6dfb",
				"show_data_table" : true
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "b00b31b4-66b4-4b09-95d6-588e72d524ca",
			"type" : "QUICKVALUES",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 604800
				},
				"field" : "type",
				"show_pie_chart" : true,
				"stream_id" : "58c7cce7ac710408ae5b6dfb",
				"show_data_table" : true
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "fd0f6680-1871-4108-8917-d1aa4f9a4c9a",
			"type" : "QUICKVALUES",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 2592000
				},
				"field" : "type",
				"show_pie_chart" : true,
				"stream_id" : "58c7cce7ac710408ae5b6dfb",
				"show_data_table" : true
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "72bb1535-d942-490f-acc0-6942913a481b",
			"type" : "SEARCH_RESULT_CHART",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 86400
				},
				"interval" : "day",
				"stream_id" : "58c7cce7ac710408ae5b6dfb"
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "45fddafb-2528-4fc2-84cd-7e4213e1a04d",
			"type" : "SEARCH_RESULT_CHART",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 604800
				},
				"interval" : "day",
				"stream_id" : "58c7cce7ac710408ae5b6dfb"
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "b7aaaca8-dd2f-4924-9bf4-8390ff0d60e4",
			"type" : "SEARCH_RESULT_CHART",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 2592000
				},
				"interval" : "day",
				"stream_id" : "58c7cce7ac710408ae5b6dfb"
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "3a7f4742-b11f-45a5-9311-d00ab4b6dd92",
			"type" : "STREAM_SEARCH_RESULT_COUNT",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 86400
				},
				"lower_is_better" : false,
				"trend" : false,
				"stream_id" : "58c7cce7ac710408ae5b6dfb",
				"query" : "NOT type:r"
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "6120d73e-b65c-4bf7-ac8b-9efc9007c577",
			"type" : "STREAM_SEARCH_RESULT_COUNT",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 604800
				},
				"lower_is_better" : false,
				"trend" : false,
				"stream_id" : "58c7cce7ac710408ae5b6dfb",
				"query" : "NOT type:r"
			}
		},
		{
			"creator_user_id" : "REMOVED",
			"cache_time" : 10,
			"description" : "REMOVED",
			"id" : "701cfde5-b884-4029-a5f3-51bd4e537451",
			"type" : "STREAM_SEARCH_RESULT_COUNT",
			"config" : {
				"timerange" : {
					"type" : "relative",
					"range" : 2592000
				},
				"lower_is_better" : false,
				"trend" : false,
				"stream_id" : "58c7cce7ac710408ae5b6dfb",
				"query" : "NOT type:r"
			}
		}
	]
}
{
	"_id" : ObjectId("58ef66a73ee8ce2866ee7e91"),
	"creator_user_id" : "REMOVED",
	"description" : "REMOVED",
	"created_at" : ISODate("2017-04-13T11:53:11.274Z"),
	"title" : "REMOVED"
}
{
	"_id" : ObjectId("59199c513ee8ce915f3f983f"),
	"creator_user_id" : "REMOVED",
	"description" : "REMOVED",
	"created_at" : ISODate("2017-05-15T12:17:21.254Z"),
	"title" : "REMOVED"
}
{
	"_id" : ObjectId("5c0a517e296a83087954fb35"),
	"creator_user_id" : "REMOVED",
	"description" : "REMOVED",
	"created_at" : ISODate("2018-12-07T10:54:54.768Z"),
	"title" : "REMOVED"
}
{
	"_id" : ObjectId("5c5d8875296a8381707e3d14"),
	"creator_user_id" : "REMOVED",
	"description" : "REMOVED",
	"created_at" : ISODate("2019-02-08T13:47:33.454Z"),
	"title" : "REMOVED"
}
{
	"_id" : ObjectId("5cffa4b13ee8ce88e53f49a4"),
	"creator_user_id" : "REMOVED",
	"description" : "REMOVED",
	"created_at" : ISODate("2019-06-11T12:55:13.553Z"),
	"title" : "REMOVED"
}
```
