### ISSUE TITLE
Service loading order is wrong

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#803]
When starting with a clean ES you get a lot of error messages until the deflector has been setup successfully. Can be reproduced by starting against a clean ES setup.

```
2014-12-08 09:51:23,651 ERROR: org.graylog2.outputs.BatchedElasticSearchOutput - Unable to flush message buffer
org.elasticsearch.indices.IndexMissingException: [graylog2_deflector] missing
	at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:735)
	at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:673)
	at org.elasticsearch.cluster.metadata.MetaData.concreteSingleIndex(MetaData.java:717)
	at org.elasticsearch.action.bulk.TransportBulkAction.executeBulk(TransportBulkAction.java:209)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:158)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:65)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:65)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:51)
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:85)
	at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:154)
	at org.graylog2.indexer.messages.Messages.bulkIndex(Messages.java:113)
	at org.graylog2.outputs.ElasticSearchOutput.write(ElasticSearchOutput.java:100)
	at org.graylog2.outputs.BatchedElasticSearchOutput.synchronousFlush(BatchedElasticSearchOutput.java:98)
	at org.graylog2.outputs.BatchedElasticSearchOutput.access$000(BatchedElasticSearchOutput.java:41)
	at org.graylog2.outputs.BatchedElasticSearchOutput$1.run(BatchedElasticSearchOutput.java:112)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
2014-12-08 09:51:24,126 INFO : org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.0.0.Final
2014-12-08 09:51:24,610 ERROR: org.graylog2.outputs.BatchedElasticSearchOutput - Unable to flush message buffer
org.elasticsearch.indices.IndexMissingException: [graylog2_deflector] missing
	at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:735)
	at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:673)
	at org.elasticsearch.cluster.metadata.MetaData.concreteSingleIndex(MetaData.java:717)
	at org.elasticsearch.action.bulk.TransportBulkAction.executeBulk(TransportBulkAction.java:209)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:158)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:65)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:65)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:51)
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:85)
	at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:154)
	at org.graylog2.indexer.messages.Messages.bulkIndex(Messages.java:113)
	at org.graylog2.outputs.ElasticSearchOutput.write(ElasticSearchOutput.java:100)
	at org.graylog2.outputs.BatchedElasticSearchOutput.synchronousFlush(BatchedElasticSearchOutput.java:98)
	at org.graylog2.outputs.BatchedElasticSearchOutput.access$000(BatchedElasticSearchOutput.java:41)
	at org.graylog2.outputs.BatchedElasticSearchOutput$1.run(BatchedElasticSearchOutput.java:112)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
2014-12-08 09:51:25,609 INFO : org.graylog2.indexer.Deflector - Did not find an deflector alias. Setting one up now.
2014-12-08 09:51:25,609 INFO : org.graylog2.indexer.Deflector - There is no index target to point to. Creating one now.
2014-12-08 09:51:25,610 ERROR: org.graylog2.outputs.BatchedElasticSearchOutput - Unable to flush message buffer
org.elasticsearch.indices.IndexMissingException: [graylog2_deflector] missing
	at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:735)
	at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:673)
	at org.elasticsearch.cluster.metadata.MetaData.concreteSingleIndex(MetaData.java:717)
	at org.elasticsearch.action.bulk.TransportBulkAction.executeBulk(TransportBulkAction.java:209)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:158)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:65)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:65)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:51)
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:85)
	at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:154)
	at org.graylog2.indexer.messages.Messages.bulkIndex(Messages.java:113)
	at org.graylog2.outputs.ElasticSearchOutput.write(ElasticSearchOutput.java:100)
	at org.graylog2.outputs.BatchedElasticSearchOutput.synchronousFlush(BatchedElasticSearchOutput.java:98)
	at org.graylog2.outputs.BatchedElasticSearchOutput.access$000(BatchedElasticSearchOutput.java:41)
	at org.graylog2.outputs.BatchedElasticSearchOutput$1.run(BatchedElasticSearchOutput.java:112)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
2014-12-08 09:51:25,611 INFO : org.graylog2.indexer.Deflector - Cycling deflector to next index now.
2014-12-08 09:51:25,611 INFO : org.graylog2.indexer.Deflector - Cycling from <none> to <graylog2_0>
2014-12-08 09:51:25,611 INFO : org.graylog2.indexer.Deflector - Creating index target <graylog2_0>...
2014-12-08 09:51:26,541 INFO : org.graylog2.indexer.Deflector - Done!
```

**Comment by kroepke** [comment]
this was fixed in https://github.com/Graylog2/graylog2-server/commit/535109456cfab6c977d9a0005ab9ad076706778d
