### ISSUE TITLE
migration failed on update (3.2 > 3.3)

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#8170]
## Current Behavior
Every restart gives me this error. 
```
2020-05-20T15:36:15.669+02:00 ERROR [ConfigurationManagementPeriodical] Error while running migration <V20190705071400_AddEventIndexSetsMigration{2019-07-05T07:14:00Z}>
java.lang.IllegalStateException: Index prefix conflict: a non-events index-set with prefix <gl-events> already exists. Configure a different <default_events_index_prefix> value in the server config file.
	at org.graylog2.migrations.V20190705071400_AddEventIndexSetsMigration.checkIndexPrefixConflicts(V20190705071400_AddEventIndexSetsMigration.java:130) ~[graylog.jar:?]
	at org.graylog2.migrations.V20190705071400_AddEventIndexSetsMigration.ensureEventsStreamAndIndexSet(V20190705071400_AddEventIndexSetsMigration.java:111) ~[graylog.jar:?]
	at org.graylog2.migrations.V20190705071400_AddEventIndexSetsMigration.upgrade(V20190705071400_AddEventIndexSetsMigration.java:84) ~[graylog.jar:?]
	at org.graylog2.periodical.ConfigurationManagementPeriodical.doRun(ConfigurationManagementPeriodical.java:43) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

## Your Environment

* Graylog Version: 3.3.0 rc
* MongoDB Version: 4.0.18

**Comment by kroepke** [comment]
The error message might be misleading, the check failed but everything is as it is supposed to be.

For anyone seeing the same output: This bug hasn't been reproduced yet but does not break anything.

**Comment by mpfz0r** [comment]
@jalogisch could you get me the output of 
`mongo graylog --eval 'db.index_sets.find().toArray()'` 

Thanks

**Comment by jalogisch** [comment]
```
MongoDB server version: 4.0.18
[
	{
		"_id" : ObjectId("5cb0a53ac793163f14e60120"),
		"title" : "Default index set",
		"description" : "The Graylog default index set",
		"index_prefix" : "graylog",
		"shards" : 1,
		"replicas" : 0,
		"rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.SizeBasedRotationStrategy",
		"rotation_strategy" : {
			"type" : "org.graylog2.indexer.rotation.strategies.SizeBasedRotationStrategyConfig",
			"max_size" : NumberLong(524288000)
		},
		"retention_strategy_class" : "org.graylog.plugins.archive.indexer.retention.strategies.ArchiveRetentionStrategy",
		"retention_strategy" : {
			"type" : "org.graylog.plugins.archive.indexer.retention.strategies.ArchiveRetentionStrategyConfig",
			"max_number_of_indices" : 5,
			"index_action" : "DELETE"
		},
		"creation_date" : ISODate("2019-04-12T14:48:26.298Z"),
		"index_analyzer" : "standard",
		"index_template_name" : "graylog-internal",
		"index_template_type" : null,
		"index_optimization_max_num_segments" : 1,
		"index_optimization_disabled" : true,
		"field_type_refresh_interval" : NumberLong(30000),
		"writable" : true
	},
	{
		"_id" : ObjectId("5cb0a9a2c7931641a00dc775"),
		"title" : "Restored Archives",
		"description" : "Indices which have been restored from an archive.",
		"index_prefix" : "restored-archive",
		"index_match_pattern" : "restored-archive\\S*",
		"index_wildcard" : "restored-archive*",
		"shards" : 1,
		"replicas" : 0,
		"rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategy",
		"rotation_strategy" : {
			"type" : "org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategyConfig",
			"max_docs_per_index" : 2147483647
		},
		"retention_strategy_class" : "org.graylog2.indexer.retention.strategies.NoopRetentionStrategy",
		"retention_strategy" : {
			"type" : "org.graylog2.indexer.retention.strategies.NoopRetentionStrategyConfig",
			"max_number_of_indices" : 2147483647
		},
		"creation_date" : ISODate("2019-04-12T15:07:12.142Z"),
		"index_analyzer" : "standard",
		"index_template_name" : "restored-archive-template",
		"index_template_type" : null,
		"index_optimization_max_num_segments" : 1,
		"index_optimization_disabled" : false,
		"field_type_refresh_interval" : NumberLong(60000),
		"writable" : false
	},
	{
		"_id" : ObjectId("5cb2d44ac793160e2bf1e8dd"),
		"title" : "packetbeat",
		"description" : "packetbeat",
		"index_prefix" : "packetbeat",
		"shards" : 1,
		"replicas" : 0,
		"rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.SizeBasedRotationStrategy",
		"rotation_strategy" : {
			"type" : "org.graylog2.indexer.rotation.strategies.SizeBasedRotationStrategyConfig",
			"max_size" : NumberLong(524288000)
		},
		"retention_strategy_class" : "org.graylog.plugins.archive.indexer.retention.strategies.ArchiveRetentionStrategy",
		"retention_strategy" : {
			"type" : "org.graylog.plugins.archive.indexer.retention.strategies.ArchiveRetentionStrategyConfig",
			"max_number_of_indices" : 5,
			"index_action" : "DELETE"
		},
		"creation_date" : ISODate("2019-04-14T06:33:46.658Z"),
		"index_analyzer" : "standard",
		"index_template_name" : "packetbeat-template",
		"index_template_type" : null,
		"index_optimization_max_num_segments" : 1,
		"index_optimization_disabled" : true,
		"field_type_refresh_interval" : NumberLong(30000),
		"writable" : true
	},
	{
		"_id" : ObjectId("5cb2d471c793160e2bf1e90f"),
		"title" : "filebeat",
		"description" : "filebeat",
		"index_prefix" : "filebeat",
		"shards" : 1,
		"replicas" : 0,
		"rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.SizeBasedRotationStrategy",
		"rotation_strategy" : {
			"type" : "org.graylog2.indexer.rotation.strategies.SizeBasedRotationStrategyConfig",
			"max_size" : NumberLong(524288000)
		},
		"retention_strategy_class" : "org.graylog.plugins.archive.indexer.retention.strategies.ArchiveRetentionStrategy",
		"retention_strategy" : {
			"type" : "org.graylog.plugins.archive.indexer.retention.strategies.ArchiveRetentionStrategyConfig",
			"max_number_of_indices" : 5,
			"index_action" : "DELETE"
		},
		"creation_date" : ISODate("2019-04-14T06:34:25.773Z"),
		"index_analyzer" : "standard",
		"index_template_name" : "filebeat-template",
		"index_template_type" : null,
		"index_optimization_max_num_segments" : 1,
		"index_optimization_disabled" : true,
		"field_type_refresh_interval" : NumberLong(30000),
		"writable" : true
	},
	{
		"_id" : ObjectId("5d5d11b5c793162a09c184de"),
		"title" : "Graylog Events",
		"description" : "Stores Graylog events.",
		"index_prefix" : "gl-events",
		"shards" : 1,
		"replicas" : 0,
		"rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.SizeBasedRotationStrategy",
		"rotation_strategy" : {
			"type" : "org.graylog2.indexer.rotation.strategies.SizeBasedRotationStrategyConfig",
			"max_size" : NumberLong(262144000)
		},
		"retention_strategy_class" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategy",
		"retention_strategy" : {
			"type" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategyConfig",
			"max_number_of_indices" : 4
		},
		"creation_date" : ISODate("2019-08-21T09:41:08.917Z"),
		"index_analyzer" : "standard",
		"index_template_name" : "gl-events-template",
		"index_template_type" : null,
		"index_optimization_max_num_segments" : 1,
		"index_optimization_disabled" : true,
		"field_type_refresh_interval" : NumberLong(60000),
		"writable" : true
	},
	{
		"_id" : ObjectId("5d5d11b5c793162a09c184e2"),
		"title" : "Graylog System Events",
		"description" : "Stores Graylog system events.",
		"index_prefix" : "gl-system-events",
		"shards" : 1,
		"replicas" : 0,
		"rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.SizeBasedRotationStrategy",
		"rotation_strategy" : {
			"type" : "org.graylog2.indexer.rotation.strategies.SizeBasedRotationStrategyConfig",
			"max_size" : NumberLong(262144000)
		},
		"retention_strategy_class" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategy",
		"retention_strategy" : {
			"type" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategyConfig",
			"max_number_of_indices" : 4
		},
		"creation_date" : ISODate("2019-08-21T09:41:09.268Z"),
		"index_analyzer" : "standard",
		"index_template_name" : "gl-system-events-template",
		"index_template_type" : null,
		"index_optimization_max_num_segments" : 1,
		"index_optimization_disabled" : true,
		"field_type_refresh_interval" : NumberLong(60000),
		"writable" : true
	},
	{
		"_id" : ObjectId("5e4fb2e9c7931638e80aac07"),
		"title" : "RAW",
		"description" : "RAW Testing",
		"index_prefix" : "raw",
		"shards" : 1,
		"replicas" : 0,
		"rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategy",
		"rotation_strategy" : {
			"type" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategyConfig",
			"rotation_period" : "PT1H"
		},
		"retention_strategy_class" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategy",
		"retention_strategy" : {
			"type" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategyConfig",
			"max_number_of_indices" : 8
		},
		"creation_date" : ISODate("2020-02-21T10:37:29.731Z"),
		"index_analyzer" : "standard",
		"index_template_name" : "raw-template",
		"index_template_type" : null,
		"index_optimization_max_num_segments" : 1,
		"index_optimization_disabled" : false,
		"field_type_refresh_interval" : NumberLong(30000),
		"writable" : true
	},
	{
		"_id" : ObjectId("5e568f81c793163fea1b32b7"),
		"title" : "boulder",
		"description" : "boulder",
		"index_prefix" : "boulder",
		"shards" : 1,
		"replicas" : 0,
		"rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategy",
		"rotation_strategy" : {
			"type" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategyConfig",
			"rotation_period" : "P7D"
		},
		"retention_strategy_class" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategy",
		"retention_strategy" : {
			"type" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategyConfig",
			"max_number_of_indices" : 60
		},
		"creation_date" : ISODate("2020-02-26T15:32:17.304Z"),
		"index_analyzer" : "standard",
		"index_template_name" : "boulder-template",
		"index_template_type" : null,
		"index_optimization_max_num_segments" : 1,
		"index_optimization_disabled" : false,
		"field_type_refresh_interval" : NumberLong(30000),
		"writable" : true
	}
]
```

**Comment by mpfz0r** [comment]
This comes from the fact that the event index sets don't have a `index_template_type` set.

The only explanation I've got for this, is that the event index sets were either created manually,
or by an early 3.1 beta release.

You can fix this by deleting both the event streams, then both event index sets and
then restart the server so the migration creates the correct ones.
Alternatively you can also tweak the `index_template_type` to `events` within mongodb manually.

Closing this.

**Comment by jalogisch** [comment]
setting this for `Graylog events` and `Graylog system events` index sets and all are gone
