### ISSUE TITLE
[0.92] Self-signed SSL/TLS generation errors

### ISSUE THREAD

**Issue by mmcguinn** [Graylog2/graylog2-server#818]
(I realize I posted to the mailing list previously, but after I confirmed that the auto generate was being triggered I thought here might be more appropriate)

I've been trying to use the ability to autogenerate an SSL cert introduced in 0.92, but I've been unable to get it to work. I changed my config URIs to https, set rest_enable_tls to true, and did not set any other SSL/TLS config information. From the server log:

```
2014-12-15T16:13:15.497-05:00 INFO  [RestApiService] rest_tls_cert_file or rest_tls_key_file is empty. Using self-signed certificates instead.
2014-12-15T16:13:15.513-05:00 INFO  [RestApiService] Started REST API at <https://10.50.0.35:12900/>
2014-12-15T16:13:15.515-05:00 INFO  [ServiceManagerListener] Services are healthy
2014-12-15T16:13:15.517-05:00 INFO  [InputSetupService] Triggering launching persisted inputs, node transitioned from Uninitialized [LB:DEAD] to Running [LB:ALIVE]
2014-12-15T16:13:15.520-05:00 INFO  [Main] Services started, startup times in ms: {InputSetupService [RUNNING]=6, MetricsReporterService [RUNNING]=15, GroovyShellSetupService [RUNNING]=15, PeriodicalsService [RUNNING]=32, OutputSetupServ
ice [RUNNING]=34, BufferSynchronizerService [RUNNING]=35, DashboardRegistryService [RUNNING]=50, ProcessBufferService [RUNNING]=1824, IndexerSetupService [RUNNING]=3373, RestApiService [RUNNING]=7131}
2014-12-15T16:13:15.525-05:00 INFO  [Main] Graylog2 Server up and running.
```
... (inputs start up etc) ...

Then this repeatedly:
```
2014-12-15T16:13:25.196-05:00 ERROR [NettyContainer] Uncaught exception during jersey resource handling
org.jboss.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f73797374656d2f636c75737465722f6e6f646520485454502f312e310d0a486f73743a2031302e35302e302e33353a31323930300d0a4163636570743a206170706c69636174696f6e2f6a736f6e0d0a4163636570743a206170706c69636174696f6e2f6a736f6e3b20636861727365743d7574662d380d0a4163636570742d436861727365743a207574662d380d0a436f6e6e656374696f6e3a20636c6f73650d0a557365722d4167656e743a20677261796c6f67322d7765622f302e39322e300d0a0d0a
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:923)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
        at java.lang.Thread.run(Thread.java:744)
```

I've had a look at the commit that added the auto generate support, and I don't think I'm missing anything in the config (and the log indicating it is trying to self-sign in there). Let me know if any other specific information would be helpful and I'd be happy to provide it. The install was done using the RPMs via the chef cookbook.

**Comment by kroepke** [comment]
Did you set the url in the web interface config to https?
The only reference I could find to an error like this is was about [doing http instead of https](http://qnalist.com/questions/5687131/https-request-is-not-detected-automatically) on the request

**Comment by mmcguinn** [comment]
I'm fairly certain that I did yes, though I will try again to verify when I have some time and report back.

**Comment by bernd** [comment]
I have been able to reproduce the error message:

```
2015-01-14 21:07:14,880 ERROR: org.graylog2.jersey.container.netty.NettyContainer - Uncaught exception during jersey resource handling
org.jboss.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f73797374656d2f636c75737465722f6e6f646520485454502f312e310d0a486f73743a203132372e302e302e313a31323930300d0a4163636570743a206170706c69636174696f6e2f6a736f6e0d0a4163636570743a206170706c69636174696f6e2f6a736f6e3b20636861727365743d7574662d380d0a4163636570742d436861727365743a207574662d380d0a436f6e6e656374696f6e3a20636c6f73650d0a557365722d4167656e743a20677261796c6f67322d7765622f312e302e302d626574612e31202866373230303766290d0a0d0a
	at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:923)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
```

This happened when I had `http://127.0.0.1:12900/` in my web interface config. Once I changed it to a `https://...` URL it worked.

I am closing this, please re-open if you still see the issue with a `https://` URL in your web interface config. Thanks!

**Comment by mmcguinn** [comment]
I can confirm that I had only set up the new URIs in the server config, not in the web config. Works fine now (though I feel like quite an idiot for not noticing). Thanks!

**Comment by kroepke** [comment]
Thanks for the feedback!
