### ISSUE TITLE
rename of role creates 500 error

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#8362]
## Expected Behavior
It should be possible to rename roles without a problem

## Current Behavior
![image](https://user-images.githubusercontent.com/404238/84878579-4d796c00-b08a-11ea-82bf-6dd104923ac0.png)

```
2020-06-17T11:04:13.570+02:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.RuntimeException: com.mongodb.MongoCommandException: Command failed with error 11000 (DuplicateKey): 'E11000 duplicate key error collection: graylog.roles index: _id_ dup key: { : ObjectId('5ee9db1f840e5f2b50ed4ad6') }' on server graylog.z.jalogis.ch:27017. The full response is {"ok": 0.0, "errmsg": "E11000 duplicate key error collection: graylog.roles index: _id_ dup key: { : ObjectId('5ee9db1f840e5f2b50ed4ad6') }", "code": 11000, "codeName": "DuplicateKey"}
	at org.graylog2.database.MongoDBUpsertRetryer.run(MongoDBUpsertRetryer.java:64) ~[graylog.jar:?]
	at org.graylog2.users.RoleServiceImpl.save(RoleServiceImpl.java:191) ~[graylog.jar:?]
	at org.graylog2.users.RoleServiceImpl.save(RoleServiceImpl.java:53) ~[graylog.jar:?]
	at org.graylog2.rest.resources.roles.RolesResource.update(RolesResource.java:155) ~[graylog.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: com.mongodb.MongoCommandException: Command failed with error 11000 (DuplicateKey): 'E11000 duplicate key error collection: graylog.roles index: _id_ dup key: { : ObjectId('5ee9db1f840e5f2b50ed4ad6') }' on server graylog.z.jalogis.ch:27017. The full response is {"ok": 0.0, "errmsg": "E11000 duplicate key error collection: graylog.roles index: _id_ dup key: { : ObjectId('5ee9db1f840e5f2b50ed4ad6') }", "code": 11000, "codeName": "DuplicateKey"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:303) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:259) ~[graylog.jar:?]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450) ~[graylog.jar:?]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:226) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123) ~[graylog.jar:?]
	at com.mongodb.operation.CommandOperationHelper$13.call(CommandOperationHelper.java:710) ~[graylog.jar:?]
	at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:501) ~[graylog.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeRetryableCommand(CommandOperationHelper.java:703) ~[graylog.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeRetryableCommand(CommandOperationHelper.java:695) ~[graylog.jar:?]
	at com.mongodb.operation.BaseFindAndModifyOperation.execute(BaseFindAndModifyOperation.java:70) ~[graylog.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:213) ~[graylog.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:182) ~[graylog.jar:?]
	at com.mongodb.DBCollection.findAndModify(DBCollection.java:2036) ~[graylog.jar:?]
	at com.mongodb.DBCollection.findAndModify(DBCollection.java:1891) ~[graylog.jar:?]
	at com.mongodb.DBCollection.findAndModify(DBCollection.java:1858) ~[graylog.jar:?]
	at com.mongodb.DBCollection.findAndModify(DBCollection.java:1801) ~[graylog.jar:?]
	at org.mongojack.JacksonDBCollection.findAndModify(JacksonDBCollection.java:881) ~[graylog.jar:?]
	at org.graylog2.users.RoleServiceImpl.lambda$save$0(RoleServiceImpl.java:192) ~[graylog.jar:?]
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78) ~[graylog.jar:?]
	at com.github.rholder.retry.Retryer.call(Retryer.java:160) ~[graylog.jar:?]
	at org.graylog2.database.MongoDBUpsertRetryer.run(MongoDBUpsertRetryer.java:57) ~[graylog.jar:?]
	... 30 more

```

## Steps to Reproduce (for bugs)
1. Create a new role & save
2. Edit the new role and change the name

## Your Environment
* Graylog Version: 3.3.1
* MongoDB: 4.0.19

[Z#843600]

**Comment by bernd** [comment]
Since we refactored the role system for the upcoming 4.0 release, this form doesn't exist anymore because it's not possible anymore to edit roles in the UI. Searches, streams and dashboards can now be shared using the "share" buttons. Closing this issue.
