### ISSUE TITLE
Input cache just keeps growing.

### ISSUE THREAD

**Issue by bubo77** [Graylog2/graylog2-server#844]
I have 0.92.3 graylog running with elasticsearch 1.3.4
> GET /system/buffers?pretty=true HTTP/1.1
{
  "buffers" : {
    "output" : {
      "utilization_percent" : 100.0,
      "utilization" : 1024
    },
    "input" : {
      "utilization_percent" : 100.0,
      "utilization" : 1024
    }
  },
  "master_caches" : {
    "output" : {
      "size" : 0
    },
    "input" : {
      "size" : 10510072
    }
  }

It seems to be never flushing the input cache. I dont see any indication why this is happening.
This is repeatedly coming in the graylog error log
2015-01-06T11:03:38.275Z ERROR [AbstractCacheWorkerThread] Exception while working on cache:
java.lang.NullPointerException
2015-01-06T11:03:38.288Z ERROR [MasterCacheWorkerThread] Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Input>.
java.lang.NullPointerException

my graylog.conf

is_master = true
node_id_file = /etc/graylog2/server/node-id
password_secret = xxxxxxxxxxxx
root_password_sha2 = xxxxxxxxxx
plugin_dir = /usr/share/graylog2-server/plugin
rest_listen_uri = http://127.0.0.1:12900/
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 4
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog2
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard
output_batch_size = 25
output_flush_interval = 1
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = yielding
ring_size = 1024
dead_letters_enabled = true
lb_recognition_period_seconds = 3
mongodb_useauth = true
mongodb_user = graylog
mongodb_password = xxxxxxxx
mongodb_host = xxxxxxxxxxx
#mongodb_replica_set = localhost:27017,localhost:27018,localhost:27019
mongodb_database = graylog
mongodb_port = 27017
mongodb_max_connections = 100
mongodb_threads_allowed_to_block_multiplier = 5
message_cache_spool_dir = /var/lib/elasticsearch/graylog2-server/message-cache-spool
message_cache_commit_interval = 1000
#input_cache_max_size = 0
disable_output_cache = true

**Comment by joschi** [comment]
refs https://github.com/Graylog2/graylog2-server/issues/835#issuecomment-68694688

**Comment by bubo77** [comment]
increased the ring size to 8192 and these as well
processbuffer_processors = 10
outputbuffer_processors = 8
I've added debug as well restarted the server at the moment the input cache is 12Gb
2015-01-06T12:50:45.821Z DEBUG [DiskJournalCache] Committing input-cache (entries 13756968)
2015-01-06T12:50:45.823Z INFO  [DiskJournalCache] Compacting off-heap message cache database files (input-cache)

**Comment by bubo77** [comment]
reenabled the outputcache as i couldn't get rid of the out of capacity message and my box is 4core cpu with 8Gb memory and can't raise the processors anymore

2015-01-06T13:50:55.258Z DEBUG [OutputBuffer] Out of capacity. Writing to cache.

Now output cache is growing rapidly but input cache is decreasing nicely

{
  "buffers" : {
    "output" : {
      "utilization_percent" : 100.0,
      "utilization" : 8192
    },
    "input" : {
      "utilization_percent" : 100.0,
      "utilization" : 8192
    }
  },
  "master_caches" : {
    "output" : {
      "size" : 3064392
    },
    "input" : {
      "size" : 11994518
    }
  }

**Comment by bubo77** [comment]
2015-01-06T14:04:18.550Z ERROR [MasterCacheWorkerThread] Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Output>.
java.lang.NullPointerException
        at org.mapdb.Queues$SimpleQueue.peek(Queues.java:117)
        at org.mapdb.Queues$SimpleQueue.isEmpty(Queues.java:287)
        at org.graylog2.caches.DiskJournalCache.isEmpty(DiskJournalCache.java:242)
        at org.graylog2.periodical.MasterCacheWorkerThread.work(MasterCacheWorkerThread.java:102)
        at org.graylog2.periodical.MasterCacheWorkerThread.access$200(MasterCacheWorkerThread.java:43)
        at org.graylog2.periodical.MasterCacheWorkerThread$2.run(MasterCacheWorkerThread.java:87)
        at java.lang.Thread.run(Thread.java:745)

**Comment by kroepke** [comment]
The disk cache is completely new in the upcoming version and there's no easy fix for 0.92, unfortunately, so I'll close this one.
Sorry for the inconvenience :(
