### ISSUE TITLE
Inputs missing after server restart

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#851]
I have several inputs in my MongoDB but only the `Random HTTP message generator/54490014d4c61dd75709229` is starting.

```
2015-01-08 16:57:42,664 INFO : org.graylog2.inputs.InputStateListener - Input [Random HTTP message generator/54490014d4c61dd75709229e] is now STARTING
2015-01-08 16:57:42,666 ERROR: com.google.common.util.concurrent.ServiceManager - Service InputSetupService [FAILED] has failed in the RUNNING state.
java.lang.RuntimeException: Unable to instantiate MessageInput from input: 
	at org.graylog2.inputs.PersistedInputsImpl$_Iterator.next(PersistedInputsImpl.java:60)
	at org.graylog2.inputs.PersistedInputsImpl$_Iterator.next(PersistedInputsImpl.java:43)
	at org.graylog2.shared.inputs.InputLauncher.launchAllPersisted(InputLauncher.java:131)
	at org.graylog2.shared.initializers.InputSetupService.run(InputSetupService.java:92)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.graylog2.shared.inputs.NoSuchInputTypeException: There is no input of type <com.graylog2.input.AWSInput> registered.
	at org.graylog2.shared.inputs.MessageInputFactory.create(MessageInputFactory.java:41)
	at org.graylog2.inputs.InputServiceImpl.getMessageInput(InputServiceImpl.java:305)
	at org.graylog2.inputs.PersistedInputsImpl$_Iterator.next(PersistedInputsImpl.java:58)
	... 6 more
2015-01-08 16:57:42,667 INFO : org.graylog2.inputs.InputStateListener - Input [Random HTTP message generator/54490014d4c61dd75709229e] is now RUNNING
Exception in thread "InputSetupService" java.lang.RuntimeException: Unable to instantiate MessageInput from input: 
	at org.graylog2.inputs.PersistedInputsImpl$_Iterator.next(PersistedInputsImpl.java:60)
	at org.graylog2.inputs.PersistedInputsImpl$_Iterator.next(PersistedInputsImpl.java:43)
	at org.graylog2.shared.inputs.InputLauncher.launchAllPersisted(InputLauncher.java:131)
	at org.graylog2.shared.initializers.InputSetupService.run(InputSetupService.java:92)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.graylog2.shared.inputs.NoSuchInputTypeException: There is no input of type <com.graylog2.input.AWSInput> registered.
	at org.graylog2.shared.inputs.MessageInputFactory.create(MessageInputFactory.java:41)
	at org.graylog2.inputs.InputServiceImpl.getMessageInput(InputServiceImpl.java:305)
	at org.graylog2.inputs.PersistedInputsImpl$_Iterator.next(PersistedInputsImpl.java:58)
	... 6 more
```

**Comment by bernd** [comment]
I ran into a similar issue and traced it down to commit cf70962. Before that a missing input class would just log a warning. Now it throws a `RuntimeException`.

It works again with the following diff. (kinda) The problem is that `next()` will return `null` if the last input in the iterator cannot be created. So I vote for reverting cf70962 for now unless that fixed another issue. Then we have to find a solution.

```diff
--- graylog2-server/src/main/java/org/graylog2/inputs/PersistedInputsImpl.java
+++ graylog2-server/src/main/java/org/graylog2/inputs/PersistedInputsImpl.java
@@ -16,7 +16,6 @@
  */
 package org.graylog2.inputs;
 
-import com.google.common.collect.Lists;
 import org.graylog2.database.NotFoundException;
 import org.graylog2.plugin.ServerStatus;
 import org.graylog2.plugin.inputs.MessageInput;
@@ -27,7 +26,6 @@ import org.slf4j.LoggerFactory;
 
 import javax.inject.Inject;
 import java.util.Iterator;
-import java.util.List;
 
 public class PersistedInputsImpl implements PersistedInputs {
     private static final Logger LOG = LoggerFactory.getLogger(PersistedInputsImpl.class);
@@ -54,11 +52,19 @@ public class PersistedInputsImpl implements PersistedInputs {
 
         @Override
         public MessageInput next() {
-            try {
-                return inputService.getMessageInput(iterator.next());
-            } catch (NoSuchInputTypeException e) {
-                throw new RuntimeException("Unable to instantiate MessageInput from input: ", e);
+            MessageInput input = null;
+            while (input == null && iterator.hasNext()) {
+                Input io = iterator.next();
+                try {
+                    input = inputService.getMessageInput(io);
+                } catch (NoSuchInputTypeException e) {
+                    LOG.warn("Cannot instantiate persisted input. No such type [{}].", io.getType());
+                } catch (Throwable e) {
+                    throw new RuntimeException("Unable to instantiate MessageInput from input: ", e);
+                }
             }
+
+            return input;
         }
```

**Comment by kroepke** [comment]
I would actually just revert that commit because fixing it looks like even more work to me, and I'm not sure we really need to have this to be lazy here. We aren't likely to have hundreds of inputs, I guess.
