### ISSUE TITLE
Unable to start radio node.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-server#854]
Hi,

Running graylog2-0.93.0-SNAPSHOT-20150110114358. Graylog2 server itself works fine. 
But i'm unable to start radio server. Here's startup errors:

```
# cat log/graylog2-radio.log
2015-01-11 15:45:09,276 INFO : org.graylog2.shared.system.stats.SigarService - Failed to load SIGAR. Falling back to JMX implementations.
2015-01-11 15:45:09,767 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: No implementation for java.net.URI annotated with @com.google.inject.name.Named(value=http_proxy_uri) was bound.
2015-01-11 15:45:09,767 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: No implementation for org.elasticsearch.node.Node was bound.
2015-01-11 15:45:09,767 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: No implementation for org.elasticsearch.node.Node was bound.
2015-01-11 15:45:09,767 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: No implementation for org.graylog2.indexer.SetIndexReadOnlyJob$Factory was bound.
2015-01-11 15:45:09,767 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: No implementation for org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob$Factory was bound.
2015-01-11 15:45:09,767 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: No implementation for org.graylog2.indexer.ranges.RebuildIndexRangesJob$Factory was bound.
Exception in thread "main" com.google.inject.CreationException: Guice creation errors:

1) No implementation for java.net.URI annotated with @com.google.inject.name.Named(value=http_proxy_uri) was bound.
  while locating java.net.URI annotated with @com.google.inject.name.Named(value=http_proxy_uri)
    for parameter 3 at org.graylog2.telemetry.TelemetryPeriodical.<init>(TelemetryPeriodical.java:62)
  at org.graylog2.plugin.PluginModule.addPeriodical(PluginModule.java:51)

2) No implementation for org.elasticsearch.node.Node was bound.
  while locating org.elasticsearch.node.Node
    for parameter 0 at org.graylog2.indexer.counts.Counts.<init>(Counts.java:35)
  while locating org.graylog2.indexer.counts.Counts
    for parameter 1 at org.graylog2.telemetry.TelemetryService.<init>(TelemetryService.java:59)
  at org.graylog2.telemetry.TelemetryModule.configure(TelemetryModule.java:17)

3) No implementation for org.elasticsearch.node.Node was bound.
  while locating org.elasticsearch.node.Node
    for parameter 0 at org.graylog2.indexer.indices.Indices.<init>(Indices.java:86)
  while locating org.graylog2.indexer.indices.Indices
    for parameter 6 at org.graylog2.indexer.Deflector.<init>(Deflector.java:71)
  while locating org.graylog2.indexer.Deflector
    for parameter 1 at org.graylog2.indexer.counts.Counts.<init>(Counts.java:35)
  while locating org.graylog2.indexer.counts.Counts
    for parameter 1 at org.graylog2.telemetry.TelemetryService.<init>(TelemetryService.java:59)
  at org.graylog2.telemetry.TelemetryModule.configure(TelemetryModule.java:17)

4) No implementation for org.graylog2.indexer.SetIndexReadOnlyJob$Factory was bound.
  while locating org.graylog2.indexer.SetIndexReadOnlyJob$Factory
    for parameter 4 at org.graylog2.indexer.Deflector.<init>(Deflector.java:71)
  while locating org.graylog2.indexer.Deflector
    for parameter 1 at org.graylog2.indexer.counts.Counts.<init>(Counts.java:35)
  while locating org.graylog2.indexer.counts.Counts
    for parameter 1 at org.graylog2.telemetry.TelemetryService.<init>(TelemetryService.java:59)
  at org.graylog2.telemetry.TelemetryModule.configure(TelemetryModule.java:17)

5) No implementation for org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob$Factory was bound.
  while locating org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob$Factory
    for parameter 5 at org.graylog2.indexer.Deflector.<init>(Deflector.java:71)
  while locating org.graylog2.indexer.Deflector
    for parameter 1 at org.graylog2.indexer.counts.Counts.<init>(Counts.java:35)
  while locating org.graylog2.indexer.counts.Counts
    for parameter 1 at org.graylog2.telemetry.TelemetryService.<init>(TelemetryService.java:59)
  at org.graylog2.telemetry.TelemetryModule.configure(TelemetryModule.java:17)

6) No implementation for org.graylog2.indexer.ranges.RebuildIndexRangesJob$Factory was bound.
  while locating org.graylog2.indexer.ranges.RebuildIndexRangesJob$Factory
    for parameter 3 at org.graylog2.indexer.Deflector.<init>(Deflector.java:71)
  while locating org.graylog2.indexer.Deflector
    for parameter 1 at org.graylog2.indexer.counts.Counts.<init>(Counts.java:35)
  while locating org.graylog2.indexer.counts.Counts
    for parameter 1 at org.graylog2.telemetry.TelemetryService.<init>(TelemetryService.java:59)
  at org.graylog2.telemetry.TelemetryModule.configure(TelemetryModule.java:17)

6 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:59)
        at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
        at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:331)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:164)
        at org.graylog2.bootstrap.Main.main(Main.java:58)
```

Looks like a bug?

**Comment by kroepke** [comment]
How did you start it?

**Comment by timukas** [comment]
Added "JAVA_CMD=$(which java)" radioctl script and run "./bin/radioctl start" from graylog folder.

**Comment by joschi** [comment]
Looks like a problem with the Telemetry plugin in combination with graylog2-radio.

@timukas Please remove the plugin from your plugins directory (it's in there by default since last week) and restart graylog2-radio.

**Comment by timukas** [comment]
Removing graylog2-telemetry-plugin helped.
Radio is now up.
