### ISSUE TITLE
Graylog server unable to connect to its own API

### ISSUE THREAD

**Issue by Sinagot** [Graylog2/graylog2-server#8543]
## Expected Behavior
I started a few weeks ago with a new instance of Graylog 3.0.2 on CENTOS7. I need this version because of the Airbus Wizard plugin for alerting. All was working well, with almost 5Gb of logs/day. I set Java memory to 10Gb.

Elasticsearch is installed on another server, and running well.

## Current Behavior
Since this morning, the server is becoming unstable without any reason and no change in the configuration. I'm currently unable to connect to the API. When I restart the graylog service, I encounter no error, but when I try to connect to the API, I have this message in the Graylog logfile :

```
2020-07-14T16:44:39.787Z WARN  [ProxiedResource] Unable to call http://Graylog_IP:9000/api/system on node <xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232) ~[graylog.jar:?]
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285) ~[graylog.jar:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241) ~[graylog.jar:?]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355) ~[graylog.jar:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227) ~[graylog.jar:?]
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215) ~[graylog.jar:?]
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) ~[graylog.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[graylog.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[graylog.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[graylog.jar:?]
	at org.graylog2.rest.RemoteInterfaceProvider.lambda$get$0(RemoteInterfaceProvider.java:61) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[graylog.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[graylog.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[graylog.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[graylog.jar:?]
	at org.graylog2.shared.rest.resources.ProxiedResource.lambda$getForAllNodes$0(ProxiedResource.java:78) ~[graylog.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204) ~[?:1.8.0_252]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_252]
	at okio.Okio$2.read(Okio.java:140) ~[graylog.jar:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[graylog.jar:?]
	... 28 more
```

## Steps to Reproduce (for bugs)
No Idea on how to reproduce bug. And no idea how it happened.

## Your Environment

* Graylog Version:3.0.2
* Elasticsearch Version:6.8
* MongoDB Version:
* Operating System:CENTOS7
* Browser version:Firefox 68

All HTTP URI in server.conf are with local IP used to connect to Graylog.

**Comment by amgrice** [comment]
I'm running 3.3.2 and am experiencing the same behavior. I'm still able to use the GUI, but the app's responsiveness is horrible and attempting to get anything from the system endpoint results in a timeout. My box has plenty of heap to spare and CPU is practically idle.

**Comment by Sinagot** [comment]
Fortunaly I Found out a solution. It is a DNS issue. A workaround is to add an entry with your server IP and server hostname to the /etc/hosts file.
Worked like a charm for all my servers.

**Comment by amgrice** [comment]
Hm, I've already got an entry for the host in /etc/hosts. Thanks for following up though, I appreciate it.

**Comment by Sinagot** [comment]
Does your dns entry matches with the IP you use to connect to your API ?

**Comment by amgrice** [comment]
Indeed, the entry does match as does the DNS entry for the domain.

**Comment by Sinagot** [comment]
Mmmh ok, because when I write hostname, I mean the fqdn. The hostname without domain name is not enough

**Comment by amgrice** [comment]
I figured you did mean FQDN, which is what I have i.e. graylog.example.org

**Comment by edmundoa** [comment]
Hi there, is this still an issue? In the end I'm not sure if it got resolved or not. Thank you!
