### ISSUE TITLE
Misleading error

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#858]
If the elasticserach cluster isn't reachable graylog2-server produces errors like Exception while working on cache: java.lang.IllegalStateException: Error while accessing database.
This is confusing and should be caught by an Exception handler...

```
2015-01-12T09:24:38.377Z ERROR [Main] Graylog2 startup failed. Exiting. Exception was:
java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {STARTING=[RestApiService [STARTING]], FAILED=[IndexerSetupService [FAILED]]}
        at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:710)
        at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:535)
        at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:301)
        at org.graylog2.Main.main(Main.java:275)
2015-01-12T09:24:38.391Z INFO  [Main] SIGNAL received. Shutting down.
2015-01-12T09:24:38.392Z ERROR [AbstractCacheWorkerThread] Exception while working on cache: 
java.lang.IllegalStateException: Error while accessing database
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:191)
        at org.graylog2.periodical.AbstractCacheWorkerThread.drainMessagesEnqueue(AbstractCacheWorkerThread.java:75)
        at org.graylog2.periodical.AbstractCacheWorkerThread.work(AbstractCacheWorkerThread.java:58)
        at org.graylog2.periodical.InputCacheWorkerThread$1.run(InputCacheWorkerThread.java:60)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: already closed
        at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.Atomic$Long.get(Atomic.java:315)
        at org.mapdb.Queues$SimpleQueue.poll(Queues.java:127)
        at org.mapdb.Queues$SimpleQueue.take(Queues.java:243)
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:181)
        ... 4 more
2015-01-12T09:24:38.398Z ERROR [AbstractCacheWorkerThread] Exception while working on cache: 
java.lang.IllegalStateException: Error while accessing database
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:191)
        at org.graylog2.periodical.AbstractCacheWorkerThread.drainMessagesEnqueue(AbstractCacheWorkerThread.java:75)
        at org.graylog2.periodical.AbstractCacheWorkerThread.work(AbstractCacheWorkerThread.java:58)
        at org.graylog2.periodical.OutputCacheWorkerThread$1.run(OutputCacheWorkerThread.java:60)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: already closed
        at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.Atomic$Long.get(Atomic.java:315)
        at org.mapdb.Queues$SimpleQueue.poll(Queues.java:127)
        at org.mapdb.Queues$SimpleQueue.take(Queues.java:243)
        at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:181)
        ... 4 more
2015-01-12T09:24:38.432Z INFO  [GracefulShutdown] Graceful shutdown initiated.
2015-01-12T09:24:38.432Z INFO  [GracefulShutdown] Node status: [Halting?[LB:DEAD]]. Waiting <3sec> for possible load balancers to recognize state change.
2015-01-12T09:24:42.435Z INFO  [GracefulShutdown] Goodbye.
```

**Comment by kroepke** [comment]
This entire code path is gone from 1.0 and handled differently, so while this is a problem, we will not change this in 0.92.x anymore and I will close this now.
