### ISSUE TITLE
graylog can not work by logs report org.graylog2.indexer.NoTargetIndexException: Couldn't find any indices for wildcard graylog_*

### ISSUE THREAD

**Issue by diaojunxian** [Graylog2/graylog2-server#8698]
## Expected Behavior

we had setting 8 es node, and 4 mongo and 3 graylog node, and then 
first, docker start 8 es node, and can see the es node work fine
then, docker start 4 mongodb and also no error log can found
at last, docker start one graylog master, then can see the log
```
 ERROR: org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy - Could not find current deflector target of index set <Default index set>. Aborting.
org.graylog2.indexer.NoTargetIndexException: Couldn't find any indices for wildcard graylog_*
	at org.graylog2.indexer.MongoIndexSet.getNewestIndexNumber(MongoIndexSet.java:154) ~[graylog.jar:?]
	at org.graylog2.indexer.MongoIndexSet.getNewestIndex(MongoIndexSet.java:146) ~[graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy.rotate(AbstractRotationStrategy.java:61) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.checkForRotation(IndexRotationThread.java:113) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:77) ~[graylog.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_232]
	at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
2020-08-05 04:14:39,296 WARN : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Active write index for index set "Default index set" (5f2a2c844756c6000f2cc1bd) doesn't exist yet
2020-08-05 04:14:44,295 WARN : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Active write index for index set "Default index set" (5f2a2c844756c6000f2cc1bd) doesn't exist yet
2020-08-05 04:14:47,981 ERROR: org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategy - Unknown index, cannot perform rotation
org.graylog2.indexer.IndexNotFoundException: Couldn't check stats of index graylog_0

Index not found for query: graylog_0. Try recalculating your index ranges.
	at org.graylog2.indexer.cluster.jest.JestUtils.buildIndexNotFoundException(JestUtils.java:118) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.specificException(JestUtils.java:84) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:57) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:62) ~[graylog.jar:?]
	at org.graylog2.indexer.indices.Indices.indexStats(Indices.java:252) ~[graylog.jar:?]
	at org.graylog2.indexer.indices.Indices.numberOfMessages(Indices.java:212) ~[graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategy.shouldRotate(MessageCountRotationStrategy.java:66) ~[graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategy.shouldRotate(MessageCountRotationStrategy.java:34) ~[graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy.rotate(AbstractRotationStrategy.java:67) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.checkForRotation(IndexRotationThread.java:113) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:77) ~[graylog.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_232]
	at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
2020-08-05 04:14:47,981 ERROR: org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy - Cannot perform rotation of index <graylog_0> in index set <Default index set> with strategy <org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategy> at this moment
```
## Steps to Reproduce (for bugs)

1.docker start 8 es node, and can see the es node work fine
2.docker start 4 mongodb and also no error log can found
3.docker start one graylog master, then can see the log, graylog can not work and input messages
4.

## Your Environment

* Graylog Version: 3.0
* Java Version:
* Elasticsearch Version: 6.8.11
* MongoDB Version:3
* Operating System:
* Browser version:

**Comment by makstock** [comment]
@diaojunxian You can take look at similar issue on our community link and let us know if you have any further issues on it.
https://community.graylog.org/t/graylog-2-3-2-shards-and-deflectors-errors/3492/7

**Comment by diaojunxian** [comment]
@makstock it can not work

as I had run the command `curl -XDELETE http://l0.10.0.22:9200/*` and the it also reports
```
org.graylog2.indexer.IndexNotFoundException: Couldn't check stats of index graylog_0

Index not found for query: graylog_0. Try recalculating your index ranges.
	at org.graylog2.indexer.cluster.jest.JestUtils.buildIndexNotFoundException(JestUtils.java:118) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.specificException(JestUtils.java:84) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:57) ~[graylog.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:62) ~[graylog.jar:?]
	at org.graylog2.indexer.indices.Indices.indexStats(Indices.java:252) ~[graylog.jar:?]
	at org.graylog2.indexer.indices.Indices.numberOfMessages(Indices.java:212) ~[graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategy.shouldRotate(MessageCountRotationStrategy.java:66) ~[graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategy.shouldRotate(MessageCountRotationStrategy.java:34) ~[graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy.rotate(AbstractRotationStrategy.java:67) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.checkForRotation(IndexRotationThread.java:113) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:77) ~[graylog.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_232]
	at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
2020-08-05 12:35:35,789 ERROR: org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy - Cannot perform rotation of index <graylog_0> in index set <Default index set> with strategy <org.graylog2.indexer.rotation.strategies.MessageCountRotationStrategy> at this moment
2020-08-05 12:35:36,351 WARN : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Active write index for index set "Default index set" (5f2aa11e519151000eebf6d2) doesn't exist yet
2020-08-05 12:35:41,356 WARN : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Active write index for index set "Default index set" (5f2aa11e519151000eebf6d2) doesn't exist yet
2020-08-05 12:35:45,768 WARN : org.graylog2.periodical.IndexRotationThread - Deflector is not up. Not trying to point to another index.
2020-08-05 12:35:45,779 ERROR: org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy - Could not find current deflector target of index set <Default index set>. Aborting.
org.graylog2.indexer.NoTargetIndexException: Couldn't find any indices for wildcard graylog_*
	at org.graylog2.indexer.MongoIndexSet.getNewestIndexNumber(MongoIndexSet.java:154) ~[graylog.jar:?]
	at org.graylog2.indexer.MongoIndexSet.getNewestIndex(MongoIndexSet.java:146) ~[graylog.jar:?]
	at org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy.rotate(AbstractRotationStrategy.java:61) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.checkForRotation(IndexRotationThread.java:113) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:77) ~[graylog.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_232]
	at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by makstock** [comment]
@diaojunxian You can run “curl -XGET localhost:9200/_cluster/state?pretty” and share your ES logs which give you something that can trace to the cause of it.
