### ISSUE TITLE
Graylog2-server 0.20.x keeps crashing (Java heap space)

### ISSUE THREAD

**Issue by neilferreira** [Graylog2/graylog2-server#877]
Hi all

My Graylog2-server running 0.20.6 keeps crashing, I would like to avoid upgrading my version of elastic search at this time so I'm hoping I can just have this issue resolved.  Does anyone have any idea what might be causing this issue? the bin/graylog2ctl script does not set any java memory options when running the server.

```
2015-01-14 09:49:31,431 WARN : org.jboss.netty.channel.DefaultChannelPipeline - An exception was thrown by a user handler while handling an exception event ([id: 0xc0e2b013, /127.0.0.1:39511 :> /127.0.0.1:12900] EXCEPTION: java.lang.OutOfMemoryError: Java heap space)
2015-01-14 09:49:32,958 WARN : org.jboss.netty.channel.DefaultChannelPipeline - An exception was thrown by a user handler while handling an exception event ([id: 0xc0e2b013, /127.0.0.1:39511 :> /127.0.0.1:12900] EXCEPTION: java.lang.OutOfMemoryError: Java heap space)
2015-01-14 09:49:40,834 WARN : org.elasticsearch.transport.netty - [graylog2-server] Message not fully read (response) for [274791] handler org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction$4@176e9696, error [false], resetting
Exception in thread "restapi-worker-0" java.lang.NullPointerException
        at org.apache.log4j.Priority.isGreaterOrEqual(Priority.java:123)
        at org.apache.log4j.Logger.isTraceEnabled(Logger.java:209)
        at org.slf4j.impl.Log4jLoggerAdapter.isTraceCapable(Log4jLoggerAdapter.java:83)
        at org.slf4j.impl.Log4jLoggerAdapter.<init>(Log4jLoggerAdapter.java:78)
        at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:68)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
        at org.slf4j.bridge.SLF4JBridgeHandler.getSLF4JLogger(SLF4JBridgeHandler.java:204)
        at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:291)
        at java.util.logging.Logger.log(Logger.java:616)
        at java.util.logging.Logger.doLog(Logger.java:641)
        at java.util.logging.Logger.logp(Logger.java:841)
        at org.jboss.netty.logging.JdkLogger.warn(JdkLogger.java:80)
        at org.jboss.netty.logging.InternalLoggerFactory$1.warn(InternalLoggerFactory.java:128)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:321)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
2015-01-14 09:49:52,020 ERROR: org.graylog2.streams.StreamRouter - Processing of stream <539fbf32e4b0921410c2f509> failed to return within 2000ms for more than 3 times. Disabling stream.
2015-01-14 09:49:52,020 ERROR: org.graylog2.streams.StreamRouter - Processing of stream <539fbf32e4b0921410c2f509> failed to return within 2000ms for more than 3 times. Disabling stream.
2015-01-14 09:49:55,262 ERROR: org.graylog2.streams.StreamRouter - Processing of stream <539fbf32e4b0921410c2f509> failed to return within 2000ms for more than 3 times. Disabling stream.
2015-01-14 09:49:56,050 ERROR: org.graylog2.streams.StreamRouter - Processing of stream <539fbf32e4b0921410c2f509> failed to return within 2000ms for more than 3 times. Disabling stream.
2015-01-14 09:49:57,572 WARN : org.elasticsearch.transport.netty - [graylog2-server] exception caught on transport layer [[id: 0x38006725, /10.243.11.143:49711 :> /10.243.11.143:9350]], closing connection
java.lang.OutOfMemoryError: Java heap space
2015-01-14 09:50:01,657 ERROR: org.graylog2.indexer.Indexer - Failed to index [1] messages. Please check the index error log in your web interface for the reason.
2015-01-14 09:50:02,482 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
2015-01-14 09:50:20,528 ERROR: com.lmax.disruptor.FatalExceptionHandler - Exception processing: 329121 org.graylog2.plugin.buffers.MessageEvent@4d35ba91
java.lang.OutOfMemoryError: Java heap space
Exception in thread "processbufferprocessor-1" java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
        at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:152)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.OutOfMemoryError: Java heap space
2015-01-14 09:50:22,074 ERROR: org.graylog2.streams.StreamRouter - Processing of stream <53996e47e4b0d6c5cf8beba7> failed to return within 2000ms for more than 3 times. Disabling stream.
2015-01-14 09:50:22,087 ERROR: org.graylog2.streams.StreamRouter - Processing of stream <53996e47e4b0d6c5cf8beba7> failed to return within 2000ms for more than 3 times. Disabling stream.
2015-01-14 09:50:24,695 ERROR: org.graylog2.streams.StreamRouter - Processing of stream <53996e47e4b0d6c5cf8beba7> failed to return within 2000ms for more than 3 times. Disabling stream.
2015-01-14 09:50:28,618 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
2015-01-14 09:50:40,444 ERROR: org.graylog2.indexer.Indexer - Failed to index [1] messages. Please check the index error log in your web interface for the reason.
2015-01-14 09:50:44,557 ERROR: org.graylog2.indexer.Indexer - Failed to index [1] messages. Please check the index error log in your web interface for the reason.
2015-01-14 09:50:53,174 ERROR: org.graylog2.indexer.Indexer - Failed to index [4] messages. Please check the index error log in your web interface for the reason.
2015-01-14 09:50:56,307 ERROR: org.graylog2.indexer.Indexer - Failed to index [3] messages. Please check the index error log in your web interface for the reason.
2015-01-14 10:04:21,599 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
```

**Comment by joschi** [comment]
Could you please upgrade to Graylog2 0.90.3 (available in the [download archive](https://www.graylog2.org/download/archive)) and check if the errors still occur?

Graylog2 0.90.3 still works with Elasticsearch 0.90.10.

**Comment by neilferreira** [comment]
Will do.  Is it just matter of replacing all of the files when upgrading to 0.90.3?  Or are there upgrade instructions I need to follow?

**Comment by joschi** [comment]
It's pretty much a drop-in replacement, see https://www.graylog2.org/news/post/0005-graylog2-v0-90-has-been-released for details (and don't get confused with the upgrade instructions for Graylog2 0.91.0 which required an Elasticsearch upgrade).

**Comment by neilferreira** [comment]
Upgrading to 0.90.3 has fixed it. Thankyou.
