### ISSUE TITLE
Graylog2 Quick Setup Unable to write configuration.

### ISSUE THREAD

**Issue by midi-abdel** [Graylog2/graylog2-server#878]
Hi,
I am trying to use Graylog2 Quick Setup, but it seems unable to write the configuration before the last step, I have MongoDB installed and mongod running.

```

23:03:53.568 [main                    ] INFO  org.graylog2.setup.Unpacker - Found graylog2 server at packages/graylog2-server-0.92.4.tgz
23:03:53.578 [main                    ] INFO  org.graylog2.setup.Unpacker - Found graylog2 web interface at packages/graylog2-web-interface-0.92.4.tgz
23:03:53.579 [main                    ] INFO  org.graylog2.setup.Unpacker - Found elasticsearch at packages/elasticsearch-1.4.2.tar.gz
23:03:53.597 [main                    ] INFO  org.graylog2.setup.Unpacker - Unpacking /root/graylog2/graylog2-setup/packages/graylog2-server-0.92.4.tgz to tmp
23:03:53.598 [main                    ] INFO  org.graylog2.setup.Unpacker - Expanding: /root/graylog2/graylog2-setup/packages/graylog2-server-0.92.4.tgz into tmp
23:03:55.158 [main                    ] INFO  org.graylog2.setup.Unpacker - Unpacking /root/graylog2/graylog2-setup/packages/graylog2-web-interface-0.92.4.tgz to tmp
23:03:55.159 [main                    ] INFO  org.graylog2.setup.Unpacker - Expanding: /root/graylog2/graylog2-setup/packages/graylog2-web-interface-0.92.4.tgz into tmp
23:03:55.979 [main                    ] INFO  org.graylog2.setup.Unpacker - Unpacking /root/graylog2/graylog2-setup/packages/elasticsearch-1.4.2.tar.gz to tmp
23:03:55.979 [main                    ] INFO  org.graylog2.setup.Unpacker - Expanding: /root/graylog2/graylog2-setup/packages/elasticsearch-1.4.2.tar.gz into tmp
23:03:57.760 [Thread-0                ] INFO  spark.webserver.SparkServer - == Spark has ignited ...
23:03:59.188 [Thread-0                ] INFO  spark.webserver.SparkServer - >> Listening on 0.0.0.0:10000
23:03:59.193 [Thread-0                ] INFO  org.eclipse.jetty.server.Server - jetty-9.0.z-SNAPSHOT
23:03:59.309 [Thread-0                ] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@3923193{HTTP/1.1}{0.0.0.0:10000}
23:15:11.158 [qtp1930072075-15        ] ERROR o.g.setup.processes.Graylog2Server - Unable to create graylog2 user account
com.mongodb.MongoTimeoutException: Timed out while waiting to connect after 10000 ms
        at com.mongodb.BaseCluster.getDescription(BaseCluster.java:131) ~[graylog2-setup.jar:na]
        at com.mongodb.DBTCPConnector.getClusterDescription(DBTCPConnector.java:396) ~[graylog2-setup.jar:na]
        at com.mongodb.DBTCPConnector.getType(DBTCPConnector.java:569) ~[graylog2-setup.jar:na]
        at com.mongodb.DBTCPConnector.getReplicaSetStatus(DBTCPConnector.java:364) ~[graylog2-setup.jar:na]
        at com.mongodb.Mongo.getReplicaSetStatus(Mongo.java:465) ~[graylog2-setup.jar:na]
        at com.mongodb.DB.getCommandReadPreference(DB.java:86) ~[graylog2-setup.jar:na]
        at com.mongodb.DB.command(DB.java:314) ~[graylog2-setup.jar:na]
        at com.mongodb.DB.command(DB.java:296) ~[graylog2-setup.jar:na]
        at com.mongodb.DB.command(DB.java:371) ~[graylog2-setup.jar:na]
        at com.mongodb.DB.command(DB.java:243) ~[graylog2-setup.jar:na]
        at com.mongodb.DBCollection.drop(DBCollection.java:1014) ~[graylog2-setup.jar:na]
        at com.mongodb.DBCollectionImpl.drop(DBCollectionImpl.java:285) ~[graylog2-setup.jar:na]
        at org.graylog2.setup.processes.Graylog2Server.createDbUser(Graylog2Server.java:212) [graylog2-setup.jar:na]
        at org.graylog2.setup.processes.Graylog2Server.writeConfiguration(Graylog2Server.java:179) [graylog2-setup.jar:na]
        at org.graylog2.setup.handler.CheckConfigHandler.handle(CheckConfigHandler.java:92) [graylog2-setup.jar:na]
        at org.graylog2.setup.handler.CheckConfigHandler.handle(CheckConfigHandler.java:40) [graylog2-setup.jar:na]
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [graylog2-setup.jar:na]
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:144) [graylog2-setup.jar:na]
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:54) [graylog2-setup.jar:na]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179) [graylog2-setup.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [graylog2-setup.jar:na]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [graylog2-setup.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [graylog2-setup.jar:na]
"setup.log" 545L, 51924C
```

Any idea how can I fix that, or am I missing something?

Thanks

**Comment by kroepke** [comment]
did the setup tool successfully connect to mongodb at all?

**Comment by bernd** [comment]
Closing this. Please re-open if you still see this with Graylog quick-setup 1.0.0. Thank you!

**Comment by arvindarsh** [comment]
I am able to connect Mongodb but next step I am not able to proceed:
 ERROR o.g.setup.processes.Graylog2Server - Unable to create graylog2 user account
com.mongodb.MongoTimeoutException: Timed out while waiting to connect after 10000 ms
        at com.mongodb.BaseCluster.getDescription(BaseCluster.java:131) ~[graylog-setup.jar:na]
        at com.mongodb.DBTCPConnector.getClusterDescription(DBTCPConnector.java:396) ~[graylog-setup.jar:na]
        at com.mongodb.DBTCPConnector.getType(DBTCPConnector.java:569) ~[graylog-setup.jar:na]
        at com.mongodb.DBTCPConnector.getReplicaSetStatus(DBTCPConnector.java:364) ~[graylog-setup.jar:na]
        at com.mongodb.Mongo.getReplicaSetStatus(Mongo.java:465) ~[graylog-setup.jar:na]
        at com.mongodb.DB.getCommandReadPreference(DB.java:86) ~[graylog-setup.jar:na]

**Comment by arvindarsh** [comment]
Please help
