### ISSUE TITLE
Graylog2 with elasticsearch on AWS VPC

### ISSUE THREAD

**Issue by amos6224** [Graylog2/graylog2-server#881]
HI all,

I have been dealing with an issue where i am unable to have my graylog2 server talk to any of my elasticsearch on the same vpc please help. i am not sure what to do anymore.
this is a test of my elasticsearch from my local machine
```
curl -XGET 'http://54.88.183.187:9200/_cluster/health?pretty=true'
{
  "cluster_name" : "graylog2",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0
}
```
the state of my elasticsearch
```
[2015-01-15 15:53:35,261][INFO ][node                     ] [ES1] initialized
[2015-01-15 15:53:35,261][INFO ][node                     ] [ES1] starting ...
[2015-01-15 15:53:35,341][INFO ][transport                ] [ES1] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/10.0.3.153:9300]}
[2015-01-15 15:53:35,349][INFO ][discovery                ] [ES1] graylog2/ic6vf2VURVS2uNZSGQEpTA
[2015-01-15 15:54:05,349][WARN ][discovery                ] [ES1] waited for 30s and no initial state was set by the discovery
[2015-01-15 15:54:05,354][INFO ][http                     ] [ES1] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.0.3.153:9200]}
[2015-01-15 15:54:05,354][INFO ][node                     ] [ES1] started
[2015-01-15 15:55:05,507][INFO ][cluster.service          ] [ES1] new_master [ES1][ic6vf2VURVS2uNZSGQEpTA][localhost][inet[/10.0.3.153:9300]]{master=true}, reason: zen-disco-join (elected_as_master)
[2015-01-15 15:55:05,523][INFO ][gateway                  ] [ES1] recovered [0] indices into cluster_state
```
the log of my graylog
################################################################################
```
2015-01-15 15:57:19,587 ERROR: com.google.common.util.concurrent.ServiceManager - Service IndexerSetupService [FAILED] has failed in the STARTING state.
java.lang.IllegalStateException
	at org.graylog2.UI.exitHardWithWall(UI.java:39)
	at org.graylog2.initializers.IndexerSetupService.startUp(IndexerSetupService.java:149)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:745)
2015-01-15 15:57:19,594 DEBUG: org.graylog2.shared.initializers.InputSetupService - Lifecycle is now Failed [LB:DEAD]
2015-01-15 15:57:19,594 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.IndexRetentionThread].
2015-01-15 15:57:19,599 ERROR: org.graylog2.shared.initializers.InputSetupService - Not starting any inputs because lifecycle is: Uninitialized [LB:DEAD]
2015-01-15 15:57:19,599 DEBUG: org.graylog2.shared.initializers.InputSetupService - Stopping InputSetupService
2015-01-15 15:57:19,599 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.IndexRetentionThread] complete, took <0ms>.
2015-01-15 15:57:19,599 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.IndexerClusterCheckerThread].
2015-01-15 15:57:19,594 INFO : org.graylog2.shared.initializers.RestApiService - Shutting down REST API at <http://127.0.0.1:12900/>
2015-01-15 15:57:19,599 DEBUG: org.graylog2.shared.initializers.InputSetupService - Stopped InputSetupService
2015-01-15 15:57:19,600 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.IndexerClusterCheckerThread] complete, took <0ms>.
2015-01-15 15:57:19,601 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.AlertScannerThread].
2015-01-15 15:57:19,601 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.AlertScannerThread] complete, took <0ms>.
2015-01-15 15:57:19,601 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.IndexRotationThread].
2015-01-15 15:57:19,601 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.IndexRotationThread] complete, took <0ms>.
2015-01-15 15:57:19,601 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread].
2015-01-15 15:57:19,601 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] complete, took <0ms>.
2015-01-15 15:57:19,601 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.ClusterHealthCheckThread].
2015-01-15 15:57:19,601 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.ClusterHealthCheckThread] complete, took <0ms>.
2015-01-15 15:57:19,606 DEBUG: org.graylog2.initializers.BufferSynchronizerService - Stopping BufferSynchronizerService
2015-01-15 15:57:19,606 WARN : org.graylog2.initializers.BufferSynchronizerService - Elasticsearch is unavailable. Not waiting to clear buffers and caches, as we have no healthy cluster.
2015-01-15 15:57:19,606 DEBUG: org.graylog2.initializers.BufferSynchronizerService - Stopped BufferSynchronizerService
2015-01-15 15:57:19,606 INFO : org.graylog2.initializers.OutputSetupService - Stopping output org.graylog2.outputs.BatchedElasticSearchOutput
2015-01-15 15:57:19,606 DEBUG: org.graylog2.initializers.IndexerSetupService - Shutting down ES client after buffer synchronizer has terminated.
2015-01-15 15:57:19,606 INFO : org.elasticsearch.node - [graylog2-server] stopping ...
2015-01-15 15:57:19,609 INFO : org.elasticsearch.discovery.zen - [graylog2-server] failed to send join request to master [[ES1][ic6vf2VURVS2uNZSGQEpTA][localhost][inet[/10.0.3.153:9300]]{master=true}], reason [org.elasticsearch.ElasticsearchIllegalStateException: Future got interrupted; java.lang.InterruptedException]
2015-01-15 15:57:19,614 INFO : org.graylog2.shared.initializers.ServiceManagerListener - Services are now stopped.
2015-01-15 15:57:19,614 ERROR: org.graylog2.Main - Graylog2 startup failed. Exiting. Exception was:
java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {FAILED=[IndexerSetupService [FAILED]]}
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:710)
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:535)
	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:301)
	at org.graylog2.Main.main(Main.java:275)
2015-01-15 15:57:19,618 ERROR: org.graylog2.periodical.AbstractCacheWorkerThread - Exception while working on cache: 
java.lang.IllegalStateException: Error while accessing database
	at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:191)
	at org.graylog2.periodical.AbstractCacheWorkerThread.drainMessagesEnqueue(AbstractCacheWorkerThread.java:75)
	at org.graylog2.periodical.AbstractCacheWorkerThread.work(AbstractCacheWorkerThread.java:58)
	at org.graylog2.periodical.OutputCacheWorkerThread$1.run(OutputCacheWorkerThread.java:60)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: already closed
	at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.Atomic$Long.get(Atomic.java:315)
	at org.mapdb.Queues$SimpleQueue.poll(Queues.java:127)
	at org.mapdb.Queues$SimpleQueue.take(Queues.java:243)
	at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:181)
	... 4 more
2015-01-15 15:57:19,619 INFO : org.elasticsearch.node - [graylog2-server] stopped
2015-01-15 15:57:19,619 INFO : org.elasticsearch.node - [graylog2-server] closing ...
2015-01-15 15:57:19,625 INFO : org.elasticsearch.node - [graylog2-server] closed
2015-01-15 15:57:19,631 INFO : org.graylog2.Main - SIGNAL received. Shutting down.
2015-01-15 15:57:19,631 ERROR: org.graylog2.periodical.AbstractCacheWorkerThread - Exception while working on cache: 
java.lang.IllegalStateException: Error while accessing database
	at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:191)
	at org.graylog2.periodical.AbstractCacheWorkerThread.drainMessagesEnqueue(AbstractCacheWorkerThread.java:75)
	at org.graylog2.periodical.AbstractCacheWorkerThread.work(AbstractCacheWorkerThread.java:58)
	at org.graylog2.periodical.InputCacheWorkerThread$1.run(InputCacheWorkerThread.java:60)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: already closed
	at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.Atomic$Long.get(Atomic.java:315)
	at org.mapdb.Queues$SimpleQueue.poll(Queues.java:127)
	at org.mapdb.Queues$SimpleQueue.take(Queues.java:243)
	at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:181)
	... 4 more
2015-01-15 15:57:19,687 INFO : org.graylog2.system.shutdown.GracefulShutdown - Graceful shutdown initiated.
2015-01-15 15:57:19,687 INFO : org.graylog2.system.shutdown.GracefulShutdown - Node status: [Halting [LB:DEAD]]. Waiting <3sec> for possible load balancers to recognize state change.
2015-01-15 15:57:23,689 INFO : org.graylog2.system.shutdown.GracefulShutdown - Goodbye.
```

**Comment by kroepke** [comment]
Check that your IP addresses are set up correctly.

The Elasticsearch address is 55.xx.zz.yy and the graylog2 server says it's using 10.0.0.x. This indicates that it binds to some other interface, or someone advertises a wrong address (check the network.publish_host for elasticsearch).

If you feel there is a bug in here somewhere, please reopen this report.
Otherwise it might be a good idea to ask for help on the mailing list.

Thanks,
Kay
