### ISSUE TITLE
OSSEC integration

### ISSUE THREAD

**Issue by Speirs47** [Graylog2/graylog2-server#8869]
Hi. I'm testing OSSEC in my network and I wanted to integrate it with my Graylog instance - output alerts from OSSEC in CEF format. Alerts from OSSEC seem to reach Graylog (they appear in Input metrics) but no messages are parsed.

In Graylog log file I get this entry:
`java.lang.IllegalStateException: Could not parse timestamp. 'Aug 19 11:17:33'`

And that's an example message that cannot be parsed (I fetched it with wireshark):
`2>Aug 19 11:17:33 CEF:0|OSSEC Foundation|OSSEC HIDS|v3.6.0|503|Ossec agent started.|3|dvc=nrv02 classification= ossec, msg=ossec: Agent started: 'norm16->192.168.10.0'.`

I'm not sure if I'm right but that timestamp doesn't look right for me too. Where's the year?

I've posted exactly the same issue on OSSEC's github but I didn't get any response in 2 days now. I realize it's more likely issue with OSSEC but I was hoping that maybe there's some workaround in Graylog.

* Graylog Version: 3.3.5+6436f1b 
* Java Version: IcedTea 1.8.0_252
* Elasticsearch Version: 6.8.12-1
* MongoDB Version: 4.0.14-1.suse12
* Operating System: openSUSE Leap 15.1 (kernel 4.12.14-lp151.28.59-default)

**Comment by jalogisch** [comment]
he @Speirs47 

the possible workaround would be to point the OSSEC messages to a Graylog RAW/Plaintext input - this way it will accept anything that is send to this input. 

After that you have the option with the processing pipeline to parse the message into its bits and pieces.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by elanfer** [comment]
Hi,

for me, it looks like, that OSSEC is sending proper CEF messages and that there might be an issue in the parsing module (c.f. https://raffy.ch/blog/wp-content/uploads/2007/06/CEF.pdf). I am running Graylog 4.2.1.

The issue occurred today, with starting the new month, interestingly the CEF parsing for those messages worked through November…  A message where the exception will be thrown looks like this:
```
<132>Dec  1 13:06:15 CEF:0|OSSEC Foundation|OSSEC HIDS|v3.6.0|5710|[...]
```

The exact error:
```
2021-12-01T14:02:12.297+01:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=e6447e60-52a6-11ec-ad0c-00163e1100a0, messageQueueId=4032168, codec=CEF, payloadSize=408, timestamp=2021-12-01T13:02:12.294Z, remoteAddress=/131.173.17.112:57074}
java.lang.IllegalStateException: Could not parse timestamp. 'Dec  1 13:02:07'
        at com.github.jcustenborder.cef.CEFParserImpl.parse(CEFParserImpl.java:114) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decodeCEF(CEFCodec.java:128) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:112) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:153) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:94) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:95) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:49) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

Thank you!

**Comment by elanfer** [comment]
Never mind! I solved the issue, the problem was a wrong system locale... (German it expected Dez instead of Dec in data parsing) Changing the locale to en_US.utf8 solved the problem for me.
