### ISSUE TITLE
Creating alert condition broken

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#891]
Creating an alert condition is broken.

```
2015-01-16 18:23:57,990 ERROR: org.graylog2.plugin.rest.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.IllegalArgumentException: The template variable 'conditionId' has no value
	at org.glassfish.jersey.uri.UriTemplate$1ValuesFromArrayStrategy.valueFor(UriTemplate.java:1017)
	at org.glassfish.jersey.uri.UriTemplate.resolveTemplate(UriTemplate.java:706)
	at org.glassfish.jersey.uri.UriTemplate.createUriComponent(UriTemplate.java:1027)
	at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:961)
	at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:906)
	at org.glassfish.jersey.uri.UriTemplate.createURI(UriTemplate.java:871)
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder._build(JerseyUriBuilder.java:906)
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder.build(JerseyUriBuilder.java:823)
	at org.graylog2.rest.resources.streams.alerts.StreamAlertConditionResource.create(StreamAlertConditionResource.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
```

The alert condition will be created, but the generation of the url is broken.

**Comment by bernd** [comment]
Fixed in acacb43.
