### ISSUE TITLE
Graylog version 3.3.5 and an error occurs Unsupported Elasticsearch version: 7.8.1

### ISSUE THREAD

**Issue by vldanch** [Graylog2/graylog2-server#8931]
Good afternoon, I install graylog version 3.3.5 and an error occurs Unsupported Elasticsearch version: 7.8.1
```
2020-09-08T08:57:31.516Z ERROR [IndexRotationThread] Couldn't point deflector to a new index
org.graylog2.indexer.ElasticsearchException: Unsupported Elasticsearch version: 7.8.1
	at org.graylog2.indexer.IndexMappingFactory.indexMappingFor(IndexMappingFactory.java:51) ~[graylog.jar:?]
	at org.graylog2.indexer.IndexMappingFactory.createIndexMapping(IndexMappingFactory.java:42) ~[graylog.jar:?]
	at org.graylog2.indexer.indices.Indices.ensureIndexTemplate(Indices.java:364) ~[graylog.jar:?]
	at org.graylog2.indexer.indices.Indices.create(Indices.java:411) ~[graylog.jar:?]
	at org.graylog2.indexer.indices.Indices.create(Indices.java:397) ~[graylog.jar:?]
	at org.graylog2.indexer.MongoIndexSet.cycle(MongoIndexSet.java:293) ~[graylog.jar:?]
	at org.graylog2.indexer.MongoIndexSet.setUp(MongoIndexSet.java:261) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.checkAndRepair(IndexRotationThread.java:138) ~[graylog.jar:?]
	at org.graylog2.periodical.IndexRotationThread.lambda$doRun$0(IndexRotationThread.java:76) ~[graylog.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at org.graylog2.periodical.IndexRotationThread.doRun(IndexRotationThread.java:73) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
how to solve this problem?

**Comment by hulkk** [comment]
You should've read the installation documentation. Elasticsearch 7.x is not yet supported.

https://docs.graylog.org/en/3.3/pages/installation.html

**Comment by dennisoelkers** [comment]
Thanks, @hulkk.

@vldanch: 4.0 will support ES 7.x. Please stick with 6.x for now and bear with us for a little bit until 4.x is out.
