### ISSUE TITLE
Return proper errors for invalid grok patterns

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#905]
If the users enters an invalid grok pattern or an invalid name for a pattern, the server responds with a 500 instead of a 400 with a proper JSON error response.

Also there is no error indicator in the web interface. It just silently fails.
```
2015-01-20 11:41:37,950 WARN : org.graylog2.grok.GrokPatternServiceImpl - Invalid regular expression syntax for '%{RANDOMHTTP}' with pattern %{NOTSPACE:mymethod}
java.util.regex.PatternSyntaxException: Illegal repetition near index 0
%{(null)}
^
	at java.util.regex.Pattern.error(Pattern.java:1924)
	at java.util.regex.Pattern.closure(Pattern.java:3104)
	at java.util.regex.Pattern.sequence(Pattern.java:2101)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.compile(Pattern.java:1665)
	at java.util.regex.Pattern.<init>(Pattern.java:1337)
	at java.util.regex.Pattern.compile(Pattern.java:1047)
	at com.google.code.regexp.Pattern.buildStandardPattern(Unknown Source)
	at com.google.code.regexp.Pattern.<init>(Unknown Source)
	at com.google.code.regexp.Pattern.compile(Unknown Source)
	at oi.thekraken.grok.api.Grok.compile(Grok.java:376)
	at org.graylog2.grok.GrokPatternServiceImpl.validate(GrokPatternServiceImpl.java:87)
	at org.graylog2.grok.GrokPatternServiceImpl.save(GrokPatternServiceImpl.java:74)
	at org.graylog2.rest.resources.system.GrokResource.createPattern(GrokResource.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:172)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dennisoelkers** [comment]
I took a quick look at this and from my perspective there is no clean way to fix(!) this at the moment, where a fix would include two things:

1) Proper indication that the attempt to create a new grok pattern failed because the pattern is invalid and not because the server is not reachable/returning something strange/the connection died in the middle etc. pp.
2) Marking (only) the field(s) which failed. This includes returning a proper data structure for failed validations while creating the grok pattern.

At the moment we are not able to do this and it would be much too much for a bug fix for 1.1, so I would suggest moving this to 1.2.0, implementing proper entity validation for creates/updates and supporting this in our configuration forms. For now (1.1) I would add a message to the javascript alert recommending to check the grok pattern and server connectivity.

**Comment by bernd** [comment]
Agreed, moving to 1.2.0. Thanks for checking!

**Comment by bernd** [comment]
The 2.0 web interface show an error for this. Closing the issue.
