### ISSUE TITLE
Navigating to system/nodes ( active node > details ) throws an error

### ISSUE THREAD

**Issue by commandline-be** [Graylog2/graylog2-server#9054]
Navigating to system/nodes ( active node > details ) throws an error: Cannot read property 'org.graylog2.buffers.input.usage' of undefined

## Expected Behavior
No error thrown

## Current Behavior
Navigate to [ system/nodes ] [ nodes ] [ details ] throws an error per below

## Possible Solution
no solution was investigated looks like a Graylog internal error

## Steps to Reproduce (for bugs)
Navigate to [ system/nodes ] [ nodes ] [ details ] throws an error per below

## Context
not much, like many such errors gone after refreshing the page

## Your Environment
Browser with Graylog 3.3

* Graylog Version: 3.3
* Java Version: 
* Elasticsearch Version: 6.8-oss 
* MongoDB Version: 
* Operating System: Microsoft WX
* Browser version: Brave (most recent)

----------------------------

Cannot read property 'org.graylog2.buffers.input.usage' of undefined

Stack Trace:

TypeError: Cannot read property 'org.graylog2.buffers.input.usage' of undefined
    at t.render (http://my.host.tld:800/assets/0c1a66a2-19.1ec71fc30880f2142b45.js:1:21988)
    at Wi (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:69874)
    at Pi (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:69669)
    at Ms (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:105468)
    at uc (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:96715)
    at sc (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:96640)
    at Qs (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:93670)
    at http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:45312
    at exports.unstable_runWithPriority (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:42:3988)
    at Xo (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:45021)
    at Ko (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:45257)
    at Uo (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:45192)
    at Gs (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:90455)
    at Object.enqueueSetState (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:26:48977)
    at t.y.setState (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:34:1296)
    at a.n (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:18:2700)
    at a.emit (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:133:220231)
    at f.trigger (http://my.host.tld:800/assets/vendor.043dd426065882df527b.js:18:3581)
    at http://my.host.tld:800/assets/builtins.1ec71fc30880f2142b45.js:35:261498
    at c (http://my.host.tld:800/assets/builtins.1ec71fc30880f2142b45.js:35:249359)
    at I._settlePromiseFromHandler (http://my.host.tld:800/assets/builtins.1ec71fc30880f2142b45.js:35:222297)
    at I._settlePromise (http://my.host.tld:800/assets/builtins.1ec71fc30880f2142b45.js:35:223097)
    at I._settlePromise0 (http://my.host.tld:800/assets/builtins.1ec71fc30880f2142b45.js:35:223796)
    at I._settlePromises (http://my.host.tld:800/assets/builtins.1ec71fc30880f2142b45.js:35:225148)
    at u (http://my.host.tld:800/assets/builtins.1ec71fc30880f2142b45.js:35:176320)
    at s (http://my.host.tld:800/assets/builtins.1ec71fc30880f2142b45.js:35:176259)
    at a._drainQueues (http://my.host.tld:800/assets/builtins.1ec71fc30880f2142b45.js:35:177373)
    at drainQueues (http://my.host.tld:800/assets/builtins.1ec71fc30880f2142b45.js:35:176193)

Component Stack:

    in BufferUsage
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in a
    in div
    in i
    in ShowNodePage
    in n
    in div
    in t
    in div
    in t
    in t
    in AppWithoutSearchBar__StyledRow
    in div
    in t
    in div
    in t
    in AppContentGrid__Container
    in u
    in St
    in div
    in wt
    in o
    in Unknown
    in withRouter(Component)
    in d
    in ft
    in ConnectStoresWrapper[ft] stores=currentUser
    in c
    in RouterContext
    in Router
    in ra
    in la
    in Unknown
    in n
    in Y
    in ConnectStoresWrapper[Y] stores=currentUser,server,sessionId
    in t
    in p

**Comment by bernd** [comment]
This has been fixed in #9316 and will be part of the upcoming 3.3.9 and 4.0.0 releases.
