### ISSUE TITLE
NullPointer in MasterCacheWorkerThread

### ISSUE THREAD

**Issue by whitew1nd** [Graylog2/graylog2-server#910]
Hello! 
We are using simple one-node setup with Graylog version 0.92.3 and recently notice following exceptions in server logs:
```
2015-01-21 12:41:47,987 ERROR: org.graylog2.periodical.MasterCacheWorkerThread - Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Input>.
java.lang.NullPointerException
	at org.mapdb.Queues$SimpleQueue.poll(Queues.java:135)
	at org.mapdb.Queues$SimpleQueue.take(Queues.java:240)
	at org.graylog2.caches.DiskJournalCache.pop(DiskJournalCache.java:181)
	at org.graylog2.periodical.MasterCacheWorkerThread.work(MasterCacheWorkerThread.java:114)
	at org.graylog2.periodical.MasterCacheWorkerThread.access$200(MasterCacheWorkerThread.java:43)
	at org.graylog2.periodical.MasterCacheWorkerThread$1.run(MasterCacheWorkerThread.java:80)
	at java.lang.Thread.run(Thread.java:745)
2015-01-21 12:41:49,383 ERROR: org.graylog2.periodical.MasterCacheWorkerThread - Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Input>.
java.lang.NullPointerException
2015-01-21 12:56:04,924 ERROR: org.graylog2.periodical.MasterCacheWorkerThread - Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Input>.
java.lang.NullPointerException
2015-01-21 12:56:07,810 ERROR: org.graylog2.periodical.AbstractCacheWorkerThread - Exception while working on cache:
java.lang.NullPointerException
```
I can't provide any steps to reproduce this, it just happens sometimes. There is no message per second peaks (~100m/s on one node)
Server is running on Ubuntu 12.04
```
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
```
Do you need some extra info on this error?

**Comment by whitew1nd** [comment]
Just found, that Kuckkuck in https://github.com/Graylog2/graylog2-server/issues/684 already reported this

**Comment by joschi** [comment]
This part of Graylog has been completely overhauled in Graylog 1.0.0. We also won't do another Graylog2 0.92.x release, so I'll close this issue.
