### ISSUE TITLE
ClusterCheckerThread errors when starting with an empty Elasticsearch node

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#9147]
I just started a new Graylog test setup (MongoDB and ES empty) and got the following error in the logs:

```
2020-10-13 15:12:44,723 ERROR: org.graylog2.periodical.IndexerClusterCheckerThread - Uncaught exception in periodical
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: An error occurred: 
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:106) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:76) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:69) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.indicesExist(ClusterAdapterES7.java:270) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.clusterHealth(ClusterAdapterES7.java:249) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.health(ClusterAdapterES7.java:64) ~[classes/:?]
	at org.graylog2.indexer.cluster.Cluster.health(Cluster.java:70) ~[classes/:?]
	at org.graylog2.periodical.IndexerClusterCheckerThread.doRun(IndexerClusterCheckerThread.java:58) ~[classes/:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.IllegalArgumentException: indices are mandatory
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesRequestConverters.indicesExist(IndicesRequestConverters.java:555) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1609) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1598) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:974) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.lambda$indicesExist$12(ClusterAdapterES7.java:270) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:74) ~[classes/:?]
	... 15 more
2020-10-13 15:12:44,720 ERROR: org.graylog2.periodical.IndexRetentionThread - Uncaught exception in periodical
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: An error occurred: 
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:106) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:76) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:69) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.indicesExist(ClusterAdapterES7.java:270) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.clusterHealth(ClusterAdapterES7.java:249) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.health(ClusterAdapterES7.java:64) ~[classes/:?]
	at org.graylog2.indexer.cluster.Cluster.health(Cluster.java:70) ~[classes/:?]
	at org.graylog2.indexer.cluster.Cluster.isHealthy(Cluster.java:125) ~[classes/:?]
	at org.graylog2.periodical.IndexRetentionThread.doRun(IndexRetentionThread.java:65) ~[classes/:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.IllegalArgumentException: indices are mandatory
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesRequestConverters.indicesExist(IndicesRequestConverters.java:555) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1609) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1598) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:974) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.lambda$indicesExist$12(ClusterAdapterES7.java:270) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:74) ~[classes/:?]
	... 16 more
2020-10-13 15:12:44,721 ERROR: org.graylog2.periodical.IndexRangesMigrationPeriodical - Uncaught exception in periodical
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: An error occurred: 
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:106) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:76) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:69) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.indicesExist(ClusterAdapterES7.java:270) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.clusterHealth(ClusterAdapterES7.java:249) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.health(ClusterAdapterES7.java:64) ~[classes/:?]
	at org.graylog2.indexer.cluster.Cluster.health(Cluster.java:70) ~[classes/:?]
	at org.graylog2.indexer.cluster.Cluster.isHealthy(Cluster.java:125) ~[classes/:?]
	at org.graylog2.periodical.IndexRangesMigrationPeriodical.doRun(IndexRangesMigrationPeriodical.java:88) ~[classes/:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.IllegalArgumentException: indices are mandatory
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesRequestConverters.indicesExist(IndicesRequestConverters.java:555) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1609) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1598) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:974) ~[elasticsearch7-7.9.1-0.jar:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.lambda$indicesExist$12(ClusterAdapterES7.java:270) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:74) ~[classes/:?]
	... 9 more
```

We probably need to add some checks to avoid these errors when indices haven't been created yet.

**Comment by dennisoelkers** [comment]
This should not happen anymore. Please reopen the issue if it still does!
