### ISSUE TITLE
IndexFieldTypePollerPeriodical errors on server shutdown

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#9157]
## Expected Behavior

The server should not throw exceptions during shutdown.

## Current Behavior

I frequently see the following errors when the server is shutting down. This doesn't happen if you start the server and quickly stop it again. I mostly see this after the server has been running for some time. But then I see it almost every time.

```
2020-10-13 19:46:12,810 INFO : kafka.log.LogManager - Shutdown complete.
2020-10-13 19:46:12,810 INFO : org.graylog2.lookup.LookupTableService - Data Adapter dns-lookup/5c18d3723b08a31570fc4578 [@2536d609] TERMINATED, was STOPPING
2020-10-13 19:46:12,835 INFO : org.graylog2.shared.journal.JournalReader - Stopping.
2020-10-13 19:46:16,617 ERROR: org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Couldn't update field types for index set <Default index set/582f3c4e43761335e4859f72>
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: An error occurred: 
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:106) ~[classes/:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:76) ~[classes/:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:69) ~[classes/:?]
        at org.graylog.storage.elasticsearch7.IndicesAdapterES7.resolveAlias(IndicesAdapterES7.java:119) ~[classes/:?]
        at org.graylog2.indexer.indices.Indices.aliasTarget(Indices.java:146) ~[classes/:?]
        at org.graylog2.indexer.MongoIndexSet.getActiveWriteIndex(MongoIndexSet.java:204) ~[classes/:?]
        at org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical.lambda$schedule$4(IndexFieldTypePollerPeriodical.java:214) ~[classes/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
        at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [?:1.8.0_265]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:1.8.0_265]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.RuntimeException: Request cannot be executed; I/O reactor status: STOPPED
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:857) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:259) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesClient.getAlias(IndicesClient.java:1315) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.storage.elasticsearch7.IndicesAdapterES7.lambda$resolveAlias$2(IndicesAdapterES7.java:119) ~[classes/:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:74) ~[classes/:?]
        ... 13 more
Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.graylog.shaded.elasticsearch7.org.apache.http.util.Asserts.check(Asserts.java:46) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:255) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesClient.getAlias(IndicesClient.java:1315) ~[elasticsearch7-7.9.1-0.jar:?]
        at org.graylog.storage.elasticsearch7.IndicesAdapterES7.lambda$resolveAlias$2(IndicesAdapterES7.java:119) ~[classes/:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:74) ~[classes/:?]
        ... 13 more
```

## Steps to Reproduce (for bugs)

1. Start server
2. Let the server run for a while
3. Stop the server
4. Watch server log

## Your Environment

* Graylog Version: 4.0.0-SNAPSHOT

**Comment by dennisoelkers** [comment]
Fixed in #9177.
