### ISSUE TITLE
Alert Notifications not displayed API error 500

### ISSUE THREAD

**Issue by ntimo** [Graylog2/graylog2-server#9262]
## Expected Behavior
Graylog should display configured alert notifications.

## Current Behavior
The API at endpoint `/api/events/notifications` returns a 500 with this error message:
```
{"type":"ApiError","message":"IOException encountered while reading from a byte array input stream"}
```

The log contains the folowing error:
```
graylog_1        |  at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@35b8f291; pos: 104] (through reference chain: org.graylog.events.notifications.AutoValue_NotificationDto$Builder["config"]->org.graylog.events.notifications.EventNotificationConfig$FallbackNotificationConfig["type"])
graylog_1        | 	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:167) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:269) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3985) ~[graylog.jar:?]
graylog_1        | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2343) ~[graylog.jar:?]
graylog_1        | 	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:80) ~[graylog.jar:?]
graylog_1        | 	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:64) ~[graylog.jar:?]
graylog_1        | 	... 74 more
graylog_1        | 2020-10-23 15:53:50,887 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
graylog_1        | java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
graylog_1        | 	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:67) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:49) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:29) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60) ~[graylog.jar:?]
graylog_1        | 	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[graylog.jar:?]
graylog_1        | 	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[graylog.jar:?]
graylog_1        | 	at org.bson.internal.LazyCodec.decode(LazyCodec.java:48) ~[graylog.jar:?]
graylog_1        | 	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63) ~[graylog.jar:?]
graylog_1        | 	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[graylog.jar:?]
graylog_1        | 	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:413) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:309) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:259) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:226) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:731) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:725) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.FindOperation.execute(FindOperation.java:725) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.operation.FindOperation.execute(FindOperation.java:89) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:196) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:177) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:989) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.DBCursor.hasNext(DBCursor.java:172) ~[graylog.jar:?]
graylog_1        | 	at org.mongojack.DBCursor.hasNext(DBCursor.java:330) ~[graylog.jar:?]
graylog_1        | 	at java.util.Iterator.forEachRemaining(Iterator.java:115) ~[?:1.8.0_265]
graylog_1        | 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_265]
graylog_1        | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265]
graylog_1        | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
graylog_1        | 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_265]
graylog_1        | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
graylog_1        | 	at java.util.stream.LongPipeline.reduce(LongPipeline.java:461) ~[?:1.8.0_265]
graylog_1        | 	at java.util.stream.LongPipeline.sum(LongPipeline.java:419) ~[?:1.8.0_265]
graylog_1        | 	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:593) ~[?:1.8.0_265]
graylog_1        | 	at org.graylog2.database.PaginatedDbService.findPaginatedWithQueryFilterAndSort(PaginatedDbService.java:158) ~[graylog.jar:?]
graylog_1        | 	at org.graylog.events.notifications.DBNotificationService.searchPaginated(DBNotificationService.java:39) ~[graylog.jar:?]
graylog_1        | 	at org.graylog.events.rest.EventNotificationsResource.listNotifications(EventNotificationsResource.java:101) ~[graylog.jar:?]
graylog_1        | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
graylog_1        | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
graylog_1        | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
graylog_1        | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
graylog_1        | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
graylog_1        | 	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
graylog_1        | 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
graylog_1        | 	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
graylog_1        | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
graylog_1        | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
graylog_1        | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
graylog_1        | Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "type" (class org.graylog.events.notifications.EventNotificationConfig$FallbackNotificationConfig), not marked as ignorable (0 known properties: ])
```

## Steps to Reproduce (for bugs)
1. Setup Graylog docker stack with mongo 4.0
2. Go to Alerts -> Noficiations

## Your Environment

* Graylog Version: 3.3.8 (docker)
* Elasticsearch Version: 6.8.9
* MongoDB Version: 4.0
* Browser version: Chrome

**Comment by zshahan** [comment]
Curious.  Were you able to fix the issue, and if so, how?  I am having the same problem on Graylog 4.0.8.

**Comment by PetrF0X** [comment]
Just hit this issue too.
We had some Slack Notifications configured and redeployed the Graylog server (Docker). As part of the redeployment the plugin containing support for Slack Notifications was removed (and not restored). As a result, Graylog couldn't read the stored Slack Notification configuration (hence falling back to using `FallbackNotificationConfig` but failing to map the stored config data to the model class).

To fix this, make sure the `graylog-integrations-plugins` is added to the Graylog installation.
