### ISSUE TITLE
IOException encountered while reading from a byte array input stream

### ISSUE THREAD

**Issue by LRCHOME** [Graylog2/graylog2-server#9274]
curl -i -u pav.sar:censored -H 'Content-Type: application/json' -H 'X-Requested-By: cli' 'http://log1.ruspetrol.yito.ru:9000/api/system/content_packs'

HTTP/1.1 500 Internal Server Error
X-Graylog-Node-ID: 02ea94e0-15d5-4ce4-8206-e844a78f80e5
X-Runtime-Microseconds: 104817
Content-Type: application/json
Date: Mon, 26 Oct 2020 12:24:59 GMT
Connection: close
Content-Length: 100

{"type":"ApiError","message":"IOException encountered while reading from a byte array input stream"}
## Expected Behavior

try to get list of content packs

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 3.3.8 (docker)
* Java Version:
* Elasticsearch Version:
* MongoDB Version: 4.0 (docker)
* Operating System:
* Browser version:

**Comment by florianpopp** [comment]
Hi @LRCHOME could you please provide the stack trace?

**Comment by LRCHOME** [comment]
2020-10-26 13:22:09,493 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:67) ~[graylog.jar:?]
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:49) ~[graylog.jar:?]
	at com.mongodb.DBDecoderAdapter.decode(DBDecoderAdapter.java:29) ~[graylog.jar:?]
	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52) ~[graylog.jar:?]
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[graylog.jar:?]
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:48) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101) ~[graylog.jar:?]
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[graylog.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[graylog.jar:?]
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:413) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:309) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:259) ~[graylog.jar:?]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450) ~[graylog.jar:?]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:226) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123) ~[graylog.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343) ~[graylog.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334) ~[graylog.jar:?]
	at com.mongodb.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:731) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:725) ~[graylog.jar:?]
	at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:725) ~[graylog.jar:?]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:89) ~[graylog.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:196) ~[graylog.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:177) ~[graylog.jar:?]
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:989) ~[graylog.jar:?]
	at com.mongodb.DBCursor.hasNext(DBCursor.java:172) ~[graylog.jar:?]
	at org.mongojack.DBCursor.hasNext(DBCursor.java:330) ~[graylog.jar:?]
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:268) ~[graylog.jar:?]
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:257) ~[graylog.jar:?]
	at org.graylog2.contentpacks.ContentPackPersistenceService.loadAll(ContentPackPersistenceService.java:71) ~[graylog.jar:?]
	at org.graylog2.rest.resources.system.contentpacks.ContentPackResource.listContentPacks(ContentPackResource.java:103) ~[graylog.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "requires" (class org.graylog2.contentpacks.model.AutoValue_ContentPackV1$Builder), not marked as ignorable (13 known properties: "entities", "rev", "summary", "vendor", "parameters", "name", "url", "v", "_id", "id", "description", "created_at", "server_version"])
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@1a87a14d; pos: 610] (through reference chain: org.graylog2.contentpacks.model.AutoValue_ContentPackV1$Builder["requires"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeFromObject(BuilderBasedDeserializer.java:320) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:216) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3985) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2343) ~[graylog.jar:?]
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:80) ~[graylog.jar:?]
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:64) ~[graylog.jar:?]
	... 66 more

**Comment by DanielBloemer** [comment]
We got the same error after upgrading graylog 3.3.8 to 4.0.1.
Trying to access the streams page result in this error.

**Comment by nilroy** [comment]
We are also facing the same issue after upgrade from 3.3.0 to 4.0.1. Anyone is working on it?

**Comment by bernd** [comment]
@DanielBloemer @nilroy Can you both please post the track traces from the logs? If you access the streams page, it will be something different.

**Comment by LRCHOME** [comment]
I got this error in docker container, when i reinstall greylog to native virtual machine, all work fine.
Do you use docker ?

**Comment by gwbou** [comment]
Same here, Graylog 4.0.1 installed via deb on a virtual server.

[graylog-error.log](https://github.com/Graylog2/graylog2-server/files/5874742/graylog-error.log)

**Comment by jpdstan** [comment]
We had the same error - the downstream error for us was:
```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "last_name" (class org.graylog2.users.AutoValue_UserOverviewDTO$Builder), not marked as ignorable (13 known properties: "client_address", "account_status", "session_active", "read_only", "username", "last_activity", "_id", "full_name", "email", "roles", "external_user", "auth_service_uid", "auth_service_id"])
```

To fix it we ran:
```
db.users.update({last_name: {$exists: true}}, {$unset: {last_name: "", first_name:""}})
```
in the mongo instance.

It seems like the data model changed and the UI doesn't expect those fields anymore.

**Comment by thll** [comment]
@LRCHOME sorry for the delay. The error you posted indicates that a content pack is present in MongoDB with a different data model than what is expected. During the `3.0.0-alpha` releases, content packs used to have a `requires` property, which has however been removed for the final `3.0.0` version. It looks as if this could be causing the problem. Is it possible that you used one of the alpha versions at some point in time?

**Comment by thll** [comment]
> Same here, Graylog 4.0.1 installed via deb on a virtual server.
> 
> [graylog-error.log](https://github.com/Graylog2/graylog2-server/files/5874742/graylog-error.log)

@gwbou thanks for the stack trace! It indicates a different cause, which is is related to streams, not content packs. We have created https://github.com/Graylog2/graylog2-server/issues/10514 for this.

**Comment by thll** [comment]
> We had the same error - the downstream error for us was:
> 
> ```
> Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "last_name" (class org.graylog2.users.AutoValue_UserOverviewDTO$Builder), not marked as ignorable (13 known properties: "client_address", "account_status", "session_active", "read_only", "username", "last_activity", "_id", "full_name", "email", "roles", "external_user", "auth_service_uid", "auth_service_id"])
> ```
> 
> To fix it we ran:
> 
> ```
> db.users.update(
>   {last_name: {$exists: true}},
>   {$unset: {last_name: "", first_name:""}},
>   {multi: true}
> )
> ```
> 
> in the mongo instance.
> 
> It seems like the data model changed and the UI doesn't expect those fields anymore. I only see "Full Name" in the UI. Graylog v4.0.6 here

@jpdstan Thanks for the report! Do you still have the complete stack trace by any chance? Also: do you remember the context (i.e. page in the UI, API request, server start etc.) this was happening? Was it also related to content packs as with the original report in this issue?

You were updating to version `4.0.6` right? For pinpointing the problem, it will help to know the exact previous version you were running Graylog with. Could you please share that as well? Thanks!

**Comment by boosty** [comment]
I am closing this due to missing feedback. We can reopen if needed.
