### ISSUE TITLE
Disk Journal needs better error message

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/graylog2-server#931]
When the directory for the disk journal is unaccessable the error message should be more clear about the problem. At the moment you get in some cases a message like this:

```
2015-01-28_18:56:06.33786 2015-01-28 18:56:06,337 INFO : org.graylog2.buffers.OutputBuffer - Initialized OutputBuffer with ring size <1024> and wait strategy <BlockingWaitStrategy>.
2015-01-28_18:56:06.35660 2015-01-28 18:56:06,356 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Tried proxying org.graylog2.outputs.OutputRegistry to support a circular dependency, but it is not an interface.
2015-01-28_18:56:06.35663 2015-01-28 18:56:06,356 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error in custom provider, java.lang.NullPointerException
2015-01-28_18:56:06.35667 2015-01-28 18:56:06,356 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error injecting constructor, java.lang.RuntimeException: java.io.IOException: No such file or directory
2015-01-28_18:56:06.35668 2015-01-28 18:56:06,356 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error injecting constructor, java.lang.IllegalArgumentException: A metric named org.graylog2.shared.journal.KafkaJournal.writeTime already exists
2015-01-28_18:56:06.35672 2015-01-28 18:56:06,356 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error injecting constructor, java.lang.IllegalArgumentException: A metric named org.graylog2.shared.journal.KafkaJournal.writeTime already exists
2015-01-28_18:56:06.35679 2015-01-28 18:56:06,356 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error injecting constructor, java.lang.IllegalArgumentException: A metric named org.graylog2.shared.journal.KafkaJournal.writeTime already exists
2015-01-28_18:56:06.35680 2015-01-28 18:56:06,356 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error injecting constructor, java.lang.IllegalArgumentException: A metric named org.graylog2.shared.journal.KafkaJournal.writeTime already exists
2015-01-28_18:56:06.35682 2015-01-28 18:56:06,356 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error injecting constructor, java.lang.IllegalArgumentException: A metric named org.graylog2.shared.journal.KafkaJournal.writeTime already exists
2015-01-28_18:56:06.35751 Exception in thread "main" com.google.inject.CreationException: Guice creation errors:
2015-01-28_18:56:06.37611
2015-01-28_18:56:06.37613 1) Tried proxying org.graylog2.outputs.OutputRegistry to support a circular dependency, but it is not an interface.
2015-01-28_18:56:06.37614   at org.graylog2.outputs.OutputRegistry.class(OutputRegistry.java:49)
2015-01-28_18:56:06.37614   while locating org.graylog2.outputs.OutputRegistry
2015-01-28_18:56:06.37615     for parameter 2 at org.graylog2.streams.OutputServiceImpl.<init>(OutputServiceImpl.java:48)
2015-01-28_18:56:06.37616   while locating org.graylog2.streams.OutputServiceImpl
2015-01-28_18:56:06.37616   while locating org.graylog2.streams.OutputService
2015-01-28_18:56:06.37617     for parameter 1 at org.graylog2.outputs.OutputRegistry.<init>(OutputRegistry.java:69)
2015-01-28_18:56:06.37617   at org.graylog2.outputs.OutputRegistry.class(OutputRegistry.java:49)
2015-01-28_18:56:06.37618   while locating org.graylog2.outputs.OutputRegistry
2015-01-28_18:56:06.37619     for parameter 1 at org.graylog2.outputs.OutputRouter.<init>(OutputRouter.java:36)
2015-01-28_18:56:06.37619   while locating org.graylog2.outputs.OutputRouter
2015-01-28_18:56:06.37620     for parameter 4 at org.graylog2.buffers.processors.OutputBufferProcessor.<init>(OutputBufferProcessor.java:76) 
```

**Comment by joschi** [comment]
Related thread on the mailing list: https://groups.google.com/forum/#!topic/graylog2/WTWZHEm5FIU

**Comment by kroepke** [comment]
output is now:

```
2015-02-02 17:12:42,620 ERROR: org.graylog2.shared.journal.KafkaJournal - Cannot create journal directory at /tmp/data/journal, please check the permissions
2015-02-02 17:12:42,621 ERROR: org.graylog2.shared.journal.KafkaJournal - Cannot create journal directory at /tmp/data/journal, please check the permissions
2015-02-02 17:12:42,622 ERROR: org.graylog2.shared.journal.KafkaJournal - Cannot create journal directory at /tmp/data/journal, please check the permissions
2015-02-02 17:12:42,622 ERROR: org.graylog2.shared.journal.KafkaJournal - Cannot create journal directory at /tmp/data/journal, please check the permissions
2015-02-02 17:12:42,642 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): Tried proxying org.graylog2.outputs.OutputRegistry to support a circular dependency, but it is not an interface.
2015-02-02 17:12:42,642 DEBUG: org.graylog2.bootstrap.CmdLineTool -  Stacktrace:
2015-02-02 17:12:42,642 ERROR: org.graylog2.bootstrap.CmdLineTool - 

################################################################################

ERROR: Unable to access file /tmp/data/journal: Could not create journal directory.

Need help?

* Official documentation: http://graylog2.org/resources/documentation
* Community support: http://graylog2.org/resources/community-support
* Commercial support: http://graylog2.org/products

Terminating. :(

################################################################################
```
