### ISSUE TITLE
Unable to start graylog-1.0.0-rc.2 with telemetry plugin.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-server#941]
Hi,

I'm running graylog-1.0.0-rc2 (default configuration). Graylog is not starting up if "plugin/graylog-telemetry-plugin-1.0.0-beta.3.jar" exists. Here's server error logs:
```
2015-02-04 10:02:15,138 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): Error injecting constructor, java.la
ng.NullPointerException: Null loaderFlags
2015-02-04 10:02:15,138 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): Error injecting constructor, java.la
ng.NullPointerException: Null loaderFlags
Exception in thread "main" com.google.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NullPointerException: Null loaderFlags
  at org.graylog2.system.stats.mongo.MongoProbe.<init>(MongoProbe.java:44)
  at org.graylog2.system.stats.mongo.MongoProbe.class(MongoProbe.java:44)
  while locating org.graylog2.system.stats.mongo.MongoProbe
    for parameter 1 at org.graylog2.system.stats.ClusterStatsService.<init>(ClusterStatsService.java:55)
  at org.graylog2.system.stats.ClusterStatsService.class(ClusterStatsService.java:55)
  while locating org.graylog2.system.stats.ClusterStatsService
    for parameter 0 at org.graylog2.telemetry.server.TelemetryClusterService.<init>(TelemetryClusterService.java:30)
  at org.graylog2.telemetry.server.TelemetryServerModule.configure(TelemetryServerModule.java:30)
  while locating org.graylog2.telemetry.server.TelemetryClusterService
    for parameter 0 at org.graylog2.telemetry.server.TelemetryClusterPeriodical.<init>(TelemetryClusterPeriodical.java:35)
  at org.graylog2.telemetry.server.TelemetryClusterPeriodical.class(TelemetryClusterPeriodical.java:25)
  while locating org.graylog2.telemetry.server.TelemetryClusterPeriodical
  while locating org.graylog2.plugin.periodical.Periodical annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=117)
  at org.graylog2.shared.bindings.SharedPeriodicalBindings.configure(SharedPeriodicalBindings.java:30)
  while locating java.util.Set<org.graylog2.plugin.periodical.Periodical>
    for parameter 2 at org.graylog2.shared.initializers.PeriodicalsService.<init>(PeriodicalsService.java:50)
  at org.graylog2.shared.initializers.PeriodicalsService.class(PeriodicalsService.java:40)
  while locating org.graylog2.shared.initializers.PeriodicalsService
  while locating com.google.common.util.concurrent.Service annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=3)
  at org.graylog2.shared.bindings.GenericInitializerBindings.configure(GenericInitializerBindings.java:30)
  while locating java.util.Set<com.google.common.util.concurrent.Service>
    for field at org.graylog2.shared.bindings.providers.ServiceManagerProvider.services(ServiceManagerProvider.java:33)
  while locating org.graylog2.shared.bindings.providers.ServiceManagerProvider
  at org.graylog2.shared.bindings.GenericBindings.configure(GenericBindings.java:70)
  while locating com.google.common.util.concurrent.ServiceManager
Caused by: java.lang.NullPointerException: Null loaderFlags
        at org.graylog2.system.stats.mongo.AutoValue_BuildInfo.<init>(AutoValue_BuildInfo.java:47)
        at org.graylog2.system.stats.mongo.BuildInfo.create(BuildInfo.java:75)
        at org.graylog2.system.stats.mongo.MongoProbe.createBuildInfo(MongoProbe.java:100)
        at org.graylog2.system.stats.mongo.MongoProbe.<init>(MongoProbe.java:50)
        at org.graylog2.system.stats.mongo.MongoProbe$$FastClassByGuice$$1d626bf1.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:326)
        at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:220)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:326)
        at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:220)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:53)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:59)
        at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
        at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:353)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:175)
        at org.graylog2.bootstrap.Main.main(Main.java:58)

2) Error injecting constructor, java.lang.NullPointerException: Null loaderFlags
  at org.graylog2.system.stats.mongo.MongoProbe.<init>(MongoProbe.java:44)
  at org.graylog2.system.stats.mongo.MongoProbe.class(MongoProbe.java:44)
  while locating org.graylog2.system.stats.mongo.MongoProbe
    for parameter 1 at org.graylog2.system.stats.ClusterStatsService.<init>(ClusterStatsService.java:55)
  at org.graylog2.system.stats.ClusterStatsService.class(ClusterStatsService.java:55)
  while locating org.graylog2.system.stats.ClusterStatsService
    for parameter 0 at org.graylog2.telemetry.server.TelemetryClusterService.<init>(TelemetryClusterService.java:30)
  at org.graylog2.telemetry.server.TelemetryServerModule.configure(TelemetryServerModule.java:30)
  while locating org.graylog2.telemetry.server.TelemetryClusterService
Caused by: java.lang.NullPointerException: Null loaderFlags
        at org.graylog2.system.stats.mongo.AutoValue_BuildInfo.<init>(AutoValue_BuildInfo.java:47)
        at org.graylog2.system.stats.mongo.BuildInfo.create(BuildInfo.java:75)
        at org.graylog2.system.stats.mongo.MongoProbe.createBuildInfo(MongoProbe.java:100)
        at org.graylog2.system.stats.mongo.MongoProbe.<init>(MongoProbe.java:50)
        at org.graylog2.system.stats.mongo.MongoProbe$$FastClassByGuice$$1d626bf1.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:59)
        at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
        at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:353)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:175)
        at org.graylog2.bootstrap.Main.main(Main.java:58)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:183)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:59)
        at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
        at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:353)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:175)
        at org.graylog2.bootstrap.Main.main(Main.java:58)
```

After i've removed "plugin/graylog-telemetry-plugin-1.0.0-beta.3.jar" file, graylog starts without any problems.

P.s. graylog server is running with radio server.

**Comment by bernd** [comment]
Thanks for the report! Which MongoDB version are you running?

**Comment by timukas** [comment]
I'm using 2.2.6

**Comment by joschi** [comment]
Which operating system is your MongoDB running on?

**Comment by bernd** [comment]
I can reproduce this with MongoDB 2.2.7 on Ubuntu 14.04.

**Comment by timukas** [comment]
Mongo is running on RHEL 6.3 (64bit)

**Comment by joschi** [comment]
Seems like the `loaderFlags` field in MongoDB's `buildInfo` (http://docs.mongodb.org/manual/reference/command/buildInfo/) output was only added later.

Could you please post the output of the MongoDB command `db.runCommand( { buildInfo: 1 } );` on your system?

**Comment by timukas** [comment]
Here you go:

> db.runCommand( { buildInfo: 1});
{
        "version" : "2.2.6",
        "gitVersion" : "d626379119a6de9f2fb390780cf2fc336dfd540d",
        "sysInfo" : "Linux ip-10-2-29-40 2.6.21.7-2.ec2.v1.2.fc8xen #1 SMP Fri Nov 20 17:48:28 EST 2009 x86_64 BOOST_LIB_VERSION=1_49",
        "versionArray" : [
                2,
                2,
                6,
                0
        ],
        "bits" : 64,
        "debug" : false,
        "maxBsonObjectSize" : 16777216,
        "ok" : 1
}

**Comment by joschi** [comment]
@timukas Great, thanks!

In order to catch all these differences it would be great if you could post the outputs of the following MongoDB commands as well:
* `db.runCommand( { dbStats: 1 } );` (http://docs.mongodb.org/manual/reference/command/dbStats/)
* `db.runCommand( { serverStatus: 1 } );` (http://docs.mongodb.org/manual/reference/command/serverStatus/)
* `db.runCommand( { hostInfo: 1 } );` (http://docs.mongodb.org/manual/reference/command/hostInfo/)

**Comment by timukas** [comment]
db.runCommand( { dbStats: 1 } );

Response from server:
{
   "retval": {
     "db": "admin",
     "collections": NumberInt(3),
     "objects": NumberInt(5),
     "avgObjSize": 56,
     "dataSize": NumberInt(280),
     "storageSize": NumberInt(16384),
     "numExtents": NumberInt(3),
     "indexes": NumberInt(1),
     "indexSize": NumberInt(8176),
     "fileSize": NumberInt(201326592),
     "nsSizeMB": NumberInt(16),
     "ok": 1
  },
   "ok": 1
}

**Comment by timukas** [comment]
db.runCommand( { serverStatus: 1 } );

Response from server:
{
   "retval": {
     "host": "xxxxxxx",
     "version": "2.2.6",
     "process": "mongod",
     "pid": NumberInt(56741),
     "uptime": 5591699,
     "uptimeMillis": NumberLong(5591699364),
     "uptimeEstimate": 5516383,
     "localTime": ISODate("2015-02-04T09:58:18.843Z"),
     "locks": {
       ".": {
         "timeLockedMicros": {
           "R": NumberLong(666144333),
           "W": NumberLong(9275211881)
        },
         "timeAcquiringMicros": {
           "R": NumberLong(621997819),
           "W": NumberLong(153676396)
        }
      },
       "admin": {
         "timeLockedMicros": {
           "r": NumberLong(22777566),
           "w": NumberLong(0)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(194028),
           "w": NumberLong(0)
        }
      },
       "local": {
         "timeLockedMicros": {
           "r": NumberLong(54009609),
           "w": NumberLong(12008776781)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(516238987),
           "w": NumberLong(7546127535)
        }
      },
       "gl2-0201": {
         "timeLockedMicros": {
           "r": NumberLong(8154666),
           "w": NumberLong(0)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(545271),
           "w": NumberLong(0)
        }
      },
       "gl2-0202": {
         "timeLockedMicros": {
           "r": NumberLong(7020903),
           "w": NumberLong(0)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(290099),
           "w": NumberLong(0)
        }
      },
       "gl2-0202-rc1": {
         "timeLockedMicros": {
           "r": NumberLong(2200133027),
           "w": NumberLong(8062986757)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(7589304742),
           "w": NumberLong(2710887552)
        }
      },
       "gl2-0205": {
         "timeLockedMicros": {
           "r": NumberLong(6462903),
           "w": NumberLong(0)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(840394),
           "w": NumberLong(0)
        }
      },
       "gl2-10": {
         "timeLockedMicros": {
           "r": NumberLong(3092266714),
           "w": NumberLong(1345607062)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(7760283080),
           "w": NumberLong(516151981)
        }
      },
       "gl2-92": {
         "timeLockedMicros": {
           "r": NumberLong(871795690),
           "w": NumberLong(1343778921)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(19931007404),
           "w": NumberLong(458751582)
        }
      },
       "gl2-93": {
         "timeLockedMicros": {
           "r": NumberLong(28415186791),
           "w": NumberLong(10990575100)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(85797914168),
           "w": NumberLong(3727017887)
        }
      },
       "gl2-93x": {
         "timeLockedMicros": {
           "r": NumberLong(25963842),
           "w": NumberLong(44761622)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(1520112717),
           "w": NumberLong(14460990)
        }
      },
       "gl2-ng": {
         "timeLockedMicros": {
           "r": NumberLong(4611480075),
           "w": NumberLong(2347794618)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(13684293596),
           "w": NumberLong(615092930)
        }
      },
       "gl2-prod": {
         "timeLockedMicros": {
           "r": NumberLong(5871612),
           "w": NumberLong(0)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(296989),
           "w": NumberLong(0)
        }
      },
       "gl2-snap": {
         "timeLockedMicros": {
           "r": NumberLong(8366607),
           "w": NumberLong(0)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(309489),
           "w": NumberLong(0)
        }
      },
       "gl2x": {
         "timeLockedMicros": {
           "r": NumberLong(3072984),
           "w": NumberLong(0)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(155081),
           "w": NumberLong(0)
        }
      },
       "graylog1": {
         "timeLockedMicros": {
           "r": NumberLong(5856316),
           "w": NumberLong(0)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(262569),
           "w": NumberLong(0)
        }
      },
       "graylog2": {
         "timeLockedMicros": {
           "r": NumberLong(8063086),
           "w": NumberLong(0)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(398641),
           "w": NumberLong(0)
        }
      },
       "test": {
         "timeLockedMicros": {
           "r": NumberLong(2089),
           "w": NumberLong(0)
        },
         "timeAcquiringMicros": {
           "r": NumberLong(757),
           "w": NumberLong(0)
        }
      }
    },
     "globalLock": {
       "totalTime": NumberLong(5591699364000),
       "lockTime": NumberLong(9275211881),
       "currentQueue": {
         "total": NumberInt(0),
         "readers": NumberInt(0),
         "writers": NumberInt(0)
      },
       "activeClients": {
         "total": NumberInt(1),
         "readers": NumberInt(0),
         "writers": NumberInt(1)
      }
    },
     "mem": {
       "bits": NumberInt(64),
       "resident": NumberInt(90),
       "virtual": NumberInt(37381),
       "supported": true,
       "mapped": NumberInt(18536),
       "mappedWithJournal": NumberInt(37072)
    },
     "connections": {
       "current": NumberInt(34),
       "available": NumberInt(19966)
    },
     "extra_info": {
       "note": "fields vary by platform",
       "heap_usage_bytes": NumberInt(80609848),
       "page_faults": NumberInt(126750)
    },
     "indexCounters": {
       "btree": {
         "accesses": NumberInt(343694029),
         "hits": NumberInt(343583406),
         "misses": NumberInt(0),
         "resets": NumberInt(0),
         "missRatio": 0
      }
    },
     "backgroundFlushing": {
       "flushes": NumberInt(93191),
       "total_ms": NumberInt(3026671),
       "average_ms": 32.478147031366,
       "last_ms": NumberInt(3),
       "last_finished": ISODate("2015-02-04T09:58:01.39Z")
    },
     "cursors": {
       "totalOpen": NumberInt(0),
       "clientCursors_size": NumberInt(0),
       "timedOut": NumberInt(0)
    },
     "network": {
       "bytesIn": 54510845177,
       "bytesOut": 245307123224,
       "numRequests": NumberInt(759316165)
    },
     "repl": {
       "ismaster": true
    },
     "opcounters": {
       "insert": NumberInt(1334),
       "query": NumberInt(651256949),
       "update": NumberInt(20787267),
       "delete": NumberInt(30885193),
       "getmore": NumberInt(1),
       "command": NumberInt(57721810)
    },
     "asserts": {
       "regular": NumberInt(0),
       "warning": NumberInt(0),
       "msg": NumberInt(0),
       "user": NumberInt(2),
       "rollovers": NumberInt(0)
    },
     "writeBacksQueued": false,
     "dur": {
       "commits": NumberInt(30),
       "journaledMB": 0.065536,
       "writeToDataFilesMB": 0.006152,
       "compression": 8.8778108913574,
       "commitsInWriteLock": NumberInt(0),
       "earlyCommits": NumberInt(0),
       "timeMs": {
         "dt": NumberInt(3076),
         "prepLogBuffer": NumberInt(0),
         "writeToJournal": NumberInt(5),
         "writeToDataFiles": NumberInt(0),
         "remapPrivateView": NumberInt(0)
      }
    },
     "recordStats": {
       "accessesNotInMemory": NumberInt(45444),
       "pageFaultExceptionsThrown": NumberInt(412),
       "admin": {
         "accessesNotInMemory": NumberInt(0),
         "pageFaultExceptionsThrown": NumberInt(0)
      },
       "gl2-0201": {
         "accessesNotInMemory": NumberInt(0),
         "pageFaultExceptionsThrown": NumberInt(0)
      },
       "gl2-0202": {
         "accessesNotInMemory": NumberInt(0),
         "pageFaultExceptionsThrown": NumberInt(0)
      },
       "gl2-0202-rc1": {
         "accessesNotInMemory": NumberInt(64),
         "pageFaultExceptionsThrown": NumberInt(54)
      },
       "gl2-0205": {
         "accessesNotInMemory": NumberInt(0),
         "pageFaultExceptionsThrown": NumberInt(0)
      },
       "gl2-10": {
         "accessesNotInMemory": NumberInt(71),
         "pageFaultExceptionsThrown": NumberInt(47)
      },
       "gl2-92": {
         "accessesNotInMemory": NumberInt(33),
         "pageFaultExceptionsThrown": NumberInt(32)
      },
       "gl2-93": {
         "accessesNotInMemory": NumberInt(282),
         "pageFaultExceptionsThrown": NumberInt(210)
      },
       "gl2-93x": {
         "accessesNotInMemory": NumberInt(0),
         "pageFaultExceptionsThrown": NumberInt(0)
      },
       "gl2-ng": {
         "accessesNotInMemory": NumberInt(27),
         "pageFaultExceptionsThrown": NumberInt(23)
      },
       "gl2-prod": {
         "accessesNotInMemory": NumberInt(0),
         "pageFaultExceptionsThrown": NumberInt(0)
      },
       "gl2-snap": {
         "accessesNotInMemory": NumberInt(0),
         "pageFaultExceptionsThrown": NumberInt(0)
      },
       "graylog1": {
         "accessesNotInMemory": NumberInt(0),
         "pageFaultExceptionsThrown": NumberInt(0)
      },
       "graylog2": {
         "accessesNotInMemory": NumberInt(0),
         "pageFaultExceptionsThrown": NumberInt(0)
      },
       "local": {
         "accessesNotInMemory": NumberInt(44923),
         "pageFaultExceptionsThrown": NumberInt(8)
      },
       "test": {
         "accessesNotInMemory": NumberInt(0),
         "pageFaultExceptionsThrown": NumberInt(0)
      }
    },
     "ok": 1
  },
   "ok": 1
}

**Comment by timukas** [comment]
db.runCommand( { hostInfo: 1 } );

Response from server:
{
   "retval": {
     "system": {
       "currentTime": ISODate("2015-02-04T09:59:43.896Z"),
       "hostname": "xxxxx",
       "cpuAddrSize": NumberInt(64),
       "memSizeMB": NumberInt(32102),
       "numCores": NumberInt(16),
       "cpuArch": "x86_64",
       "numaEnabled": true
    },
     "os": {
       "type": "Linux",
       "name": "Red Hat Enterprise Linux Server release 6.3 (Santiago)",
       "version": "Kernel 2.6.32-279.14.1.el6.x86_64"
    },
     "extra": {
       "versionString": "Linux version 2.6.32-279.14.1.el6.x86_64 (mockbuild@x86-002.build.bos.redhat.com) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Mon Oct 15 13:44:51 EDT 2012",
       "libcVersion": "2.12",
       "kernelVersion": "2.6.32-279.14.1.el6.x86_64",
       "cpuFrequencyMHz": "2933.437",
       "cpuFeatures": "fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm ida arat epb dts",
       "pageSize": NumberInt(4096),
       "numPages": NumberInt(8218120),
       "maxOpenFiles": NumberInt(65535)
    },
     "ok": 1
  },
   "ok": 1
}

**Comment by timukas** [comment]
mongo database name i'm using is "gl2-10"
