### ISSUE TITLE
Share button error on Dashboards's Page Graylog 4.0.0

### ISSUE THREAD

**Issue by chalfling** [Graylog2/graylog2-server#9525]
## Current Behavior

I had migrated from 3.3.8 to 4.0.0 and two of my Dashboards can't use new "role" assign from "Share Button". I got this error:
>Error
>Preparing shares for My Dashboad XXX "dashboard" failed with status: Null title - cannot POST http://XXX:9000/api/authz/shares/entities/grn::::dashboard:XXX/prepare (500)

Then I look into log files and got this:

>2020-11-17 16:31:59,592 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
>java.lang.NullPointerException: Null title
        at org.graylog.security.entities.AutoValue_EntityDescriptor$Builder.title(AutoValue_EntityDescriptor.java:107) ~[graylog.jar:?]
        at org.graylog.security.entities.EntityDescriptor.create(EntityDescriptor.java:49) ~[graylog.jar:?]
        at org.graylog.security.entities.EntityDependencyResolver.lambda$resolve$3(EntityDependencyResolver.java:77) ~[graylog.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_252]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_252]
        at org.graylog.security.entities.EntityDependencyResolver.resolve(EntityDependencyResolver.java:82) ~[graylog.jar:?]
        at org.graylog.security.shares.EntitySharesService.checkMissingPermissionsOnDependencies(EntitySharesService.java:299) ~[graylog.jar:?]
        at org.graylog.security.shares.EntitySharesService.prepareShare(EntitySharesService.java:108) ~[graylog.jar:?]
        at org.graylog.security.rest.EntitySharesResource.prepareShare(EntitySharesResource.java:123) ~[graylog.jar:?]
        at sun.reflect.GeneratedMethodAccessor1067.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
>
I tried to "Save as" from inside Dashboard page and then Share the new one, but same error.

## Steps to Reproduce (for bugs)

1. Go to /dashboards page
2. Click on "Share" button of some Dashboard with permission by old role based

## Your Environment

* Graylog Version: 4.0.0
* Java Version: 1.8.0_252
* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.2
* Operating System: FreeBSD 12.1

**Comment by bernd** [comment]
@chalfling Thank you for the report!

I created a new `graylog.jar` with the following patch to avoid the `NullPointerException` and to log a warning to the server log, so are able to debug this further. Can you please replace the existing `graylog.jar` in your installation with this one and reproduce the issue?

Once you shared one of the dashboards that failed before, can you please check the server log for one or more "Missing entity excerpt" warnings and post that here? Thank you!

Download: https://downloads.graylog.org/nightly-builds/hot-fixes/issue-9525/graylog.jar

<details>
<summary>EntityDependencyResolver patch (click to show details)</summary>

```diff
diff --git graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
index efe1a90bde..71a4c3d9ce 100644
--- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
+++ graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
@@ -27,6 +27,8 @@ import org.graylog2.contentpacks.ContentPackService;
 import org.graylog2.contentpacks.model.ModelId;
 import org.graylog2.contentpacks.model.ModelType;
 import org.graylog2.contentpacks.model.entities.EntityExcerpt;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 import javax.annotation.Nullable;
 import javax.inject.Inject;
@@ -38,6 +40,8 @@ import java.util.stream.Collectors;
 import static com.google.common.base.MoreObjects.firstNonNull;
 
 public class EntityDependencyResolver {
+    private static final Logger LOG = LoggerFactory.getLogger(EntityDependencyResolver.class);
+
     private final ContentPackService contentPackService;
     private final GRNRegistry grnRegistry;
     private final GRNDescriptorService descriptorService;
@@ -74,11 +78,18 @@ public class EntityDependencyResolver {
         final Map<GRN, Set<GRN>> targetOwners = grantService.getOwnersForTargets(dependencies);
 
         return dependencies.stream()
-                .map(dependency -> EntityDescriptor.create(
-                        dependency,
-                        entityExcerpts.get(dependency),
-                        getOwners(targetOwners.get(dependency))
-                ))
+                .map(dependency -> {
+                    String title = entityExcerpts.get(dependency);
+                    if (title == null) {
+                        LOG.warn("Missing entity excerpt for <{}>", dependency);
+                        title = dependency.toString();
+                    }
+                    return EntityDescriptor.create(
+                            dependency,
+                            title,
+                            getOwners(targetOwners.get(dependency))
+                    );
+                })
                 .collect(ImmutableSet.toImmutableSet());
     }
 
```

</details>

**Comment by chalfling** [comment]
> @chalfling Thank you for the report!
> 
> I created a new `graylog.jar` with the following patch to avoid the `NullPointerException` and to log a warning to the server log, so we are able to debug this further. Can you please replace the existing `graylog.jar` in your installation with this one and reproduce the issue?
> 
> Once you shared one of the dashboards that failed before, can you please check the server log for one or more "Missing entity excerpt" warnings and post that here? Thank you!
> 
> Download: https://downloads.graylog.org/nightly-builds/hot-fixes/issue-9525/graylog.jar
> 
> EntityDependencyResolver patch (click to show details)

Thank you @bernd I'll run graylog.jar that o shared. Need I to upgrade all nodes in cluster with this one?

Additional details on Users Role Page(on System -> Roles):
![Screenshot_20201118_170058](https://user-images.githubusercontent.com/9088569/99581887-1f44e300-29c0-11eb-80d4-238855f89994.png)

I changed the HASH of dashboards on "Inspect" from my Browser.

The dashboard that I'm the owner is a new one created on Graylog 4.0.0

**Comment by chalfling** [comment]
Hello @bernd !

I was able to use the "Share" button with your new graylog.jar. And now got this error:
>`2020-11-18 17:20:04,990 WARN : org.graylog.security.entities.EntityDependencyResolver - Missing entity excerpt for <grn::::stream:5e46d0ecbe052a54dcf5ad7f>`
