### ISSUE TITLE
Cannot read property 'analysis_disabled_fields' of undefined

### ISSUE THREAD

**Issue by paladox** [Graylog2/graylog2-server#9591]
One of our users reported this (we've restricted their access to certain streams and they have the 'read' right): 

(They went to /search)

```
Cannot read property 'analysis_disabled_fields' of undefined


Stack Trace:

TypeError: Cannot read property 'analysis_disabled_fields' of undefined
    at https://graylog.miraheze.org/assets/app.333c3fdac03b8317da4b.js:2:2362474
    at m._genProps (https://graylog.miraheze.org/assets/app.333c3fdac03b8317da4b.js:2:2495763)
    at m.value (https://graylog.miraheze.org/assets/app.333c3fdac03b8317da4b.js:2:2496960)
    at Hi (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:293781)
    at Ri (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:293576)
    at Ls (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:329190)
    at Mc (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:320631)
    at mc (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:320556)
    at sc (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:317586)
    at https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:269227
    at exports.unstable_runWithPriority (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:780503)
    at Ua (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:268936)
    at Za (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:269172)
    at Va (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:269107)
    at nc (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:314371)
    at yi (https://graylog.miraheze.org/assets/vendor.594b2a39cb22b445205e.js:2:286183)
    at https://graylog.miraheze.org/assets/StreamSearchPage.333c3fdac03b8317da4b.js:1:3129

Component Stack:

    in ConnectStoresWrapper[Provider] stores=view,configs
    in Tu
    in Zu
    in Ju
    in bu
    in ConnectStoresWrapper[bu] stores=view
    in lf
    in Unknown
    in hf
    in mf
    in Unknown
    in Unknown
    in Unknown
    in n
    in div
    in af
    in t
    in t
    in div
    in Lt
    in o
    in dt
    in h
    in Rt
    in t
    in t
    in c
    in t
    in Ir
    in Unknown
    in ConnectStoresWrapper[Unknown/Anonymous] stores=streams
    in je
    in T
    in f
    in v
    in b
    in Unknown
    in n
    in F
    in ConnectStoresWrapper[F] stores=currentUser,server,sessionId
    in je
    in T
    in Z
```

## Expected Behavior
JS shouldn't be throwing an error.

## Your Environment

* Graylog Version: 4.0
* Java Version: 11.0.9
* Elasticsearch Version: 7.10
* MongoDB Version: 4.4
* Operating System: Debian 10
* Browser version: Chrome, 86.0.4240.193 (Official Build) (64-bit)

**Comment by HGCH81** [comment]
Hello, i'm facing same issue in version 3.3.16
