### ISSUE TITLE
Unhandled exception while executing event processor

### ISSUE THREAD

**Issue by aim4r** [Graylog2/graylog2-server#9638]
Periodically, we get a few ERROR entries in the Graylog server.log file that says "Unhandled exception while executing event processor" (see log sample below). I have searched in the documentation but couldn't find an indication on how to interpret this error or how to troobleshoot it further. 

Can anyone help explaining what these are or how to address them ?

`2020-11-27T16:14:56.872+01:00 ERROR [EventProcessorEngine] Caught an unhandled exception while executing event processor <aggregation-v1/REDACTED/5f36423060848518575ae77f> - Make sure to modify the event processor to throw only EventProcessorExecutionException so we get more context!
org.graylog2.indexer.ElasticsearchException: Unable to scroll indices.
        at org.graylog.storage.elasticsearch6.jest.JestUtils.execute(JestUtils.java:54) ~[?:?]
        at org.graylog.storage.elasticsearch6.jest.JestUtils.execute(JestUtils.java:65) ~[?:?]
        at org.graylog.storage.elasticsearch6.Scroll.scroll(Scroll.java:45) ~[?:?]
        at org.graylog.storage.elasticsearch6.Scroll.scroll(Scroll.java:41) ~[?:?]
        at org.graylog.storage.elasticsearch6.MoreSearchAdapterES6.scrollEvents(MoreSearchAdapterES6.java:163) ~[?:?]
        at org.graylog.events.search.MoreSearch.scrollQuery(MoreSearch.java:147) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.filterSearch(AggregationEventProcessor.java:210) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:121) ~[graylog.jar:?]
        at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:92) ~[graylog.jar:?]
        at org.graylog.events.processor.EventProcessorExecutionJob.execute(EventProcessorExecutionJob.java:115) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:166) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$2(JobExecutionEngine.java:144) ~[graylog.jar:?]
        at com.codahale.metrics.Timer.time(Timer.java:151) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:144) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:119) ~[graylog.jar:?]
        at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:110) ~[graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_275]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_275]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_275]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_275]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[graylog.jar:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[graylog.jar:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282) ~[graylog.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[graylog.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[graylog.jar:?]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[graylog.jar:?]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[graylog.jar:?]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165) ~[graylog.jar:?]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[graylog.jar:?]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[graylog.jar:?]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[graylog.jar:?]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[graylog.jar:?]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[graylog.jar:?]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[graylog.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[graylog.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[graylog.jar:?]
        at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:151) ~[?:?]
        at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:77) ~[?:?]
        at org.graylog.storage.elasticsearch6.jest.JestUtils.execute(JestUtils.java:49) ~[?:?]
        ... 20 more
2020-11-27T16:14:56.874+01:00 ERROR [EventProcessorExecutionJob] Event processor <aggregation-v1/5f36423060848518575ae77f> failed to execute: Couldn't create events for: EventDefinitionDto{id=5f36423060848518575ae77f, title=REDACTED, description=, priority=3, alert=true, config=AggregationEventProcessorConfig{type=aggregation-v1, query="REDACTED", queryParameters=[], streams=[], groupBy=[], series=[], conditions=Optional[AggregationConditions{expression=Optional.empty}], searchWithinMs=120000, executeEveryMs=120000}, fieldSpec={}, keySpec=[], notificationSettings=EventNotificationSettings{gracePeriodMs=120000, backlogSize=50}, notifications=[Config{notificationId=5ee0e355eaec315f0aaa582e, notificationParameters=Optional.empty}], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]} (retry in 5000 ms)
org.graylog.events.processor.EventProcessorException: Couldn't create events for: EventDefinitionDto{id=5f36423060848518575ae77f, title=REDACTED, description=, priority=3, alert=true, config=AggregationEventProcessorConfig{type=aggregation-v1, query="High Availability status changed", queryParameters=[], streams=[], groupBy=[], series=[], conditions=Optional[AggregationConditions{expression=Optional.empty}], searchWithinMs=120000, executeEveryMs=120000}, fieldSpec={}, keySpec=[], notificationSettings=EventNotificationSettings{gracePeriodMs=120000, backlogSize=50}, notifications=[Config{notificationId=5ee0e355eaec315f0aaa582e, notificationParameters=Optional.empty}], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]}
        at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:106) ~[graylog.jar:?]
        at org.graylog.events.processor.EventProcessorExecutionJob.execute(EventProcessorExecutionJob.java:115) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:166) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$2(JobExecutionEngine.java:144) ~[graylog.jar:?]
        at com.codahale.metrics.Timer.time(Timer.java:151) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:144) ~[graylog.jar:?]
        at org.graylog.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:119) ~[graylog.jar:?]
        at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:110) ~[graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: org.graylog2.indexer.ElasticsearchException: Unable to scroll indices.
        at org.graylog.storage.elasticsearch6.jest.JestUtils.execute(JestUtils.java:54) ~[?:?]
        at org.graylog.storage.elasticsearch6.jest.JestUtils.execute(JestUtils.java:65) ~[?:?]
        at org.graylog.storage.elasticsearch6.Scroll.scroll(Scroll.java:45) ~[?:?]
        at org.graylog.storage.elasticsearch6.Scroll.scroll(Scroll.java:41) ~[?:?]
        at org.graylog.storage.elasticsearch6.MoreSearchAdapterES6.scrollEvents(MoreSearchAdapterES6.java:163) ~[?:?]
        at org.graylog.events.search.MoreSearch.scrollQuery(MoreSearch.java:147) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.filterSearch(AggregationEventProcessor.java:210) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:121) ~[graylog.jar:?]
        at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:92) ~[graylog.jar:?]
        ... 12 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_275]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_275]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_275]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_275]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[graylog.jar:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[graylog.jar:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282) ~[graylog.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[graylog.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[graylog.jar:?]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[graylog.jar:?]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[graylog.jar:?]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165) ~[graylog.jar:?]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[graylog.jar:?]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[graylog.jar:?]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[graylog.jar:?]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[graylog.jar:?]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[graylog.jar:?]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[graylog.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[graylog.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[graylog.jar:?]
        at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:151) ~[?:?]
        at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:77) ~[?:?]
        at org.graylog.storage.elasticsearch6.jest.JestUtils.execute(JestUtils.java:49) ~[?:?]
        at org.graylog.storage.elasticsearch6.jest.JestUtils.execute(JestUtils.java:65) ~[?:?]
        at org.graylog.storage.elasticsearch6.Scroll.scroll(Scroll.java:45) ~[?:?]
        at org.graylog.storage.elasticsearch6.Scroll.scroll(Scroll.java:41) ~[?:?]
        at org.graylog.storage.elasticsearch6.MoreSearchAdapterES6.scrollEvents(MoreSearchAdapterES6.java:163) ~[?:?]
        at org.graylog.events.search.MoreSearch.scrollQuery(MoreSearch.java:147) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.filterSearch(AggregationEventProcessor.java:210) ~[graylog.jar:?]
        at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:121) ~[graylog.jar:?]
        at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:92) ~[graylog.jar:?]
        ... 12 more`

## Your Environment
* Graylog Version: 4.0.1
* Elasticsearch Version: 6
* Operating System: Ubuntu

**Comment by sowhatim** [comment]
@aim4r  - what exact es 6 version you are using ?

**Comment by aim4r** [comment]
@sowhatim I'm on 6.8.13 :

```
curl -XGET 'http://localhost:9200'
{
  "version" : {
    "number" : "6.8.13",
    "build_flavor" : "oss",
    "build_type" : "deb",
    "build_hash" : "be13c69",
    "build_date" : "2020-10-16T09:09:46.555371Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.3",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
}
```

**Comment by dennisoelkers** [comment]
Hey @aim4r,

thanks for reporting this! The key here is `Caused by: java.net.SocketTimeoutException: Read timed out at` in your logs. It looks like the request to ES is timing out for some reason. Maybe digging in your ES logs will yield some actionable insights?

**Comment by aim4r** [comment]
Thanks for the response. There are no errors whatsoever in the ES logs. However, given yhe number of EPSs in my setup (5000+ events per second) and the volume of logs managed by ES, I am thinking about increasing the following value in Graylog's server.conf from the default 10s to perhaps 20s :

`elasticsearch_connect_timeout = 20s`

**Comment by sowhatim** [comment]
My suggestion will be to check other es tuning params that are available in graylog like total max_connections, etc.
Also this part from the logs that you pasted - 

`org.graylog.events.processor.EventProcessorException: Couldn't create events for: EventDefinitionDto{id=5f36423060848518575ae77f, title=REDACTED, description=, priority=3, alert=true, config=AggregationEventProcessorConfig{type=aggregation-v1, query="High Availability status changed", queryParameters=[], streams=[], groupBy=[], series=[], conditions=Optional[AggregationConditions{expression=Optional.empty}], searchWithinMs=120000, executeEveryMs=120000}, fieldSpec={}, keySpec=[], notificationSettings=EventNotificationSettings{gracePeriodMs=120000, backlogSize=50}, notifications=[Config{notificationId=5ee0e355eaec315f0aaa582e, notificationParameters=Optional.empty}], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]} at`

 indicates a probable issue with mongodb. Maybe check if the user has proper permission or if there is any resource contention on the mongodb cluster.

**Comment by aim4r** [comment]
It looks like this issue has been resolved by adding some CPU horsepower to the ES backend.
Thanks all for the support, I'm closing the issue.
