### ISSUE TITLE
13 errors when starting a new graylog 4.0 installation

### ISSUE THREAD

**Issue by Azertooth** [Graylog2/graylog2-server#9639]
I'm using docker compose and just upgrading the graylog image to version 4.0 it gives me this:

graylog                  | 13 errors
graylog                  |      at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
graylog                  |      at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
graylog                  |      at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
graylog                  |      at com.google.inject.Guice.createInjector(Guice.java:87)
graylog                  |      at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34)
graylog                  |      at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:381)
graylog                  |      at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:196)
graylog                  |      at org.graylog2.bootstrap.Main.main(Main.java:50)

## Expected Behavior
It should start like the previous version do, no problem at all with 3.8 image

## Your Environment
docker compose

* Graylog Version: 4.0
* Java Version: bundled in graylog image
* Elasticsearch Version: 7.10.0
* MongoDB Version: 3

**Comment by Azertooth** [comment]
solved thanks to this thread:

https://github.com/Graylog2/graylog2-server/issues/9521#issuecomment-730203573
