### ISSUE TITLE
Upgraded from using Docker from 3.3.9 to 4.0 and Graylog keeps restarting with Java Errors

### ISSUE THREAD

**Issue by markpsullivan** [Graylog2/graylog2-server#9645]
2020-11-30 20:55:33,919 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.events.search.MoreSearchAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog.events.search.MoreSearchAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:54)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

2020-11-30 20:55:33,920 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.plugins.views.migrations.V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog.plugins.views.migrations.V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:62)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

2020-11-30 20:55:33,920 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.plugins.views.search.engine.QueryBackend<? extends org.graylog.plugins.views.search.engine.GeneratedQueryContext>>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog.plugins.views.search.engine.QueryBackend<? extends org.graylog.plugins.views.search.engine.GeneratedQueryContext> bound  at org.graylog2.storage.VersionAwareStorageModule.bindQueryBackend(VersionAwareStorageModule.java:69)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)
2020-11-30 20:55:33,920 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.plugins.views.search.export.ExportBackend>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)
    org.graylog.plugins.views.search.export.ExportBackend bound  at org.graylog.plugins.views.ViewsBindings.registerExportBackendProvider(ViewsBindings.java:184)

2020-11-30 20:55:33,920 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.IndexToolsAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog2.indexer.IndexToolsAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:59)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

2020-11-30 20:55:33,920 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.cluster.ClusterAdapter>> was bound.
2020-11-30 20:55:33,920 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.cluster.NodeAdapter>> was bound.
2020-11-30 20:55:33,921 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.counts.CountsAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog2.indexer.counts.CountsAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:51)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

2020-11-30 20:55:33,921 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.fieldtypes.IndexFieldTypePollerAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog2.indexer.fieldtypes.IndexFieldTypePollerAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:58)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

2020-11-30 20:55:33,921 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.indices.IndicesAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog2.indexer.indices.IndicesAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:52)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

2020-11-30 20:55:33,921 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.messages.MessagesAdapter>> was bound.
2020-11-30 20:55:33,921 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.searches.SearchesAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog2.indexer.searches.SearchesAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:53)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

2020-11-30 20:55:33,921 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases$ClusterState>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases$ClusterState bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:60)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.events.search.MoreSearchAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog.events.search.MoreSearchAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:54)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.events.search.MoreSearchAdapter>>
    for the 2nd parameter of org.graylog2.storage.providers.MoreSearchAdapterProvider.<init>(MoreSearchAdapterProvider.java:31)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:54)

2) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.plugins.views.migrations.V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog.plugins.views.migrations.V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:62)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.plugins.views.migrations.V20200730000000_AddGl2MessageIdFieldAliasForEvents$ElasticsearchAdapter>>
    for the 2nd parameter of org.graylog2.storage.providers.V20200730000000_AddGl2MessageIdFieldAliasForEventsElasticsearchAdapterProvider.<init>(V20200730000000_AddGl2MessageIdFieldAliasForEventsElasticsearchAdapterProvider.java:34)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:62)

3) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.plugins.views.search.engine.QueryBackend<? extends org.graylog.plugins.views.search.engine.GeneratedQueryContext>>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

    org.graylog.plugins.views.search.engine.QueryBackend<? extends org.graylog.plugins.views.search.engine.GeneratedQueryContext> bound  at org.graylog2.storage.VersionAwareStorageModule.bindQueryBackend(VersionAwareStorageModule.java:69)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.plugins.views.search.engine.QueryBackend<? extends org.graylog.plugins.views.search.engine.GeneratedQueryContext>>>
    for the 2nd parameter of org.graylog2.storage.providers.ElasticsearchBackendProvider.<init>(ElasticsearchBackendProvider.java:33)
  at org.graylog2.storage.VersionAwareStorageModule.bindQueryBackend(VersionAwareStorageModule.java:69)

4) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.plugins.views.search.export.ExportBackend>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)
    org.graylog.plugins.views.search.export.ExportBackend bound  at org.graylog.plugins.views.ViewsBindings.registerExportBackendProvider(ViewsBindings.java:184)

  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.plugins.views.search.export.ExportBackend>>
    for the 2nd parameter of org.graylog.plugins.views.providers.ExportBackendProvider.<init>(ExportBackendProvider.java:31)
  at org.graylog.plugins.views.ViewsBindings.registerExportBackendProvider(ViewsBindings.java:184)

5) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.IndexToolsAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
    org.graylog2.indexer.IndexToolsAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:59)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.IndexToolsAdapter>>
    for the 2nd parameter of org.graylog2.storage.providers.IndexToolsAdapterProvider.<init>(IndexToolsAdapterProvider.java:31)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:59)

6) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.cluster.ClusterAdapter>> was bound.
  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.cluster.ClusterAdapter>>
    for the 2nd parameter of org.graylog2.storage.providers.ClusterAdapterProvider.<init>(ClusterAdapterProvider.java:31)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:56)

7) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.cluster.NodeAdapter>> was bound.
  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.cluster.NodeAdapter>>
    for the 2nd parameter of org.graylog2.storage.providers.NodeAdapterProvider.<init>(NodeAdapterProvider.java:31)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:57)

8) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.counts.CountsAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

    org.graylog2.indexer.counts.CountsAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:51)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.counts.CountsAdapter>>
    for the 2nd parameter of org.graylog2.storage.providers.CountsAdapterProvider.<init>(CountsAdapterProvider.java:31)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:51)

9) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.fieldtypes.IndexFieldTypePollerAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

    org.graylog2.indexer.fieldtypes.IndexFieldTypePollerAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:58)
    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.fieldtypes.IndexFieldTypePollerAdapter>>
    for the 2nd parameter of org.graylog2.storage.providers.IndexFieldTypePollerAdapterProvider.<init>(IndexFieldTypePollerAdapterProvider.java:31)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:58)

10) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.indices.IndicesAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

    org.graylog2.indexer.indices.IndicesAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:52)

    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.indices.IndicesAdapter>>
    for the 2nd parameter of org.graylog2.storage.providers.IndicesAdapterProvider.<init>(IndicesAdapterProvider.java:31)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:52)

11) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.messages.MessagesAdapter>> was bound.
  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.messages.MessagesAdapter>>
    for the 2nd parameter of org.graylog2.storage.providers.MessagesAdapterProvider.<init>(MessagesAdapterProvider.java:31)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:55)

12) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.searches.SearchesAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

    org.graylog2.indexer.searches.SearchesAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:53)

    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.indexer.searches.SearchesAdapter>>
    for the 2nd parameter of org.graylog2.storage.providers.SearchesAdapterProvider.<init>(SearchesAdapterProvider.java:31)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:53)

13) No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases$ClusterState>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

    org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases$ClusterState bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:60)

    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)

  while locating java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog2.migrations.V20170607164210_MigrateReopenedIndicesToAliases$ClusterState>>
    for the 2nd parameter of org.graylog2.storage.providers.V20170607164210_MigrateReopenedIndicesToAliasesClusterStateAdapterProvider.<init>(V20170607164210_MigrateReopenedIndicesToAliasesClusterStateAdapterProvider.java:31)
  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:60)

13 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34)
        at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:381)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:196)
        at org.graylog2.bootstrap.Main.main(Main.java:50)

**Comment by markpsullivan** [comment]
Found answer here: https://github.com/Graylog2/graylog2-server/issues/9521 had mounted plugins folder and was missing needed storage plugin.
