### ISSUE TITLE
Thread dump broken in some cases

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#9915]
## Expected Behavior

Thread dump should work

## Current Behavior

In some cases when thread dump would help with bug reports it does not work and gives HTTP 500

![Screenshot 2021-01-15 at 15 37 52 - thread dump 500 copy](https://user-images.githubusercontent.com/24830359/104748537-84b41680-575a-11eb-922c-1b792d1f11ba.png)

## Steps to Reproduce (for bugs)

1. Bug triggers
2. Try to Get thread dump

## Your Environment

* Graylog Version: 3.3.8
* Java Version: openjdk version "1.8.0_272"

**Comment by bernd** [comment]
@hulkk Can you please include the stack trace from the logs when that happens? Thank you!

**Comment by hulkk** [comment]
The screenshot's timestamp is `Screenshot 2021-01-15 at 15.37.52.png`.

There is no relevant stack trace in the logs.

```
2021-01-15T15:37:19.840+02:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
2021-01-15T15:37:38.790+02:00 ERROR [Version] Unable to read org.sherzberg.graylog.plugins.graylog-plugin-s3/graylog-plugin.properties, this build has no version number.
com.github.zafarkhaja.semver.UnexpectedCharacterException: null
        at com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516) ~[graylog.jar:?]
        at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:259) ~[graylog.jar:?]
        at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195) ~[graylog.jar:?]
        at com.github.zafarkhaja.semver.Version.valueOf(Version.java:265) ~[graylog.jar:?]
        at org.graylog2.plugin.Version.fromClasspathProperties(Version.java:219) [graylog.jar:?]
        at org.graylog2.plugin.Version.fromPluginProperties(Version.java:163) [graylog.jar:?]
        at org.sherzberg.graylog.aws.plugin.S3InputPluginMetaData.getVersion(S3InputPluginMetaData.java:39) [graylog-plugin-s3-2.3.0.2.jar:?]
        at org.graylog2.shared.rest.resources.system.SystemPluginResource.list(SystemPluginResource.java:62) [graylog.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
2021-01-15T15:37:52.739+02:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
2021-01-15T15:38:13.190+02:00 INFO  [Server] SIGNAL received. Shutting down.
2021-01-15T15:38:13.192+02:00 INFO  [GracefulShutdown] Graceful shutdown initiated.
```

**Comment by bernd** [comment]
Thanks for the input. This doesn't seem to be related to the error, though.

I guess this is some kind of race condition in high load scenarios. We need to investigate.
