### ISSUE TITLE
Quick Setup: Failure to install on rhel7.0

### ISSUE THREAD

**Issue by gzcwnk** [Graylog2/graylog2-server#993]
the failure message I get is,

```
Please open http://vuwunicoradius1.ods.vuw.ac.nz:10000/ in your browser to get started.



Starting elasticsearch with the following command:
	ES_HEAP_SIZE=2g elasticsearch/bin/elasticsearch -p run/elasticsearch.pid -Des.config=conf/elasticsearch.yml
13:10:57.988 [Thread-15               ] ERROR o.g.s.h.StartAllProcessesHandler - Timed out starting process Elasticsearch
Starting graylog server with the following command:
	java -Xms1g -Xmx1g -XX:PermSize=128m -XX:MaxPermSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Djava.net.preferIPv4Stack=true -Djava.library.path=lib/sigar -jar graylog/graylog.jar server -p run/graylog.pid -f conf/graylog.conf
13:11:50.950 [Thread-15               ] ERROR o.g.s.h.StartAllProcessesHandler - Timed out starting process Graylog2Server


Error: Failed to start Graylog. Please see the setup.log file for errors.
```
```
[root@vuwunicoradius1 graylog-setup]# tail -100f setup.log 
13:13:46.522 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:46,521 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
13:13:46.552 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:46,552 INFO : org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks.
13:13:46.637 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:46,552 INFO : org.elasticsearch.node - [graylog2-server] starting ...
13:13:46.931 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:46,931 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
13:13:48.345 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:48,344 INFO : org.elasticsearch.transport - [graylog2-server] bound_address {inet[/0.0.0.0:9350]}, publish_address {inet[/10.100.32.53:9350]}
13:13:48.735 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:48,726 INFO : org.elasticsearch.discovery - [graylog2-server] graylog2/XQedQNOhQGqp8VOTg8vNFw
13:13:48.817 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:48,817 WARN : org.graylog2.indexer.esplugin.ClusterStateMonitor - No Elasticsearch data nodes in cluster, cluster is completely offline.
13:13:48.874 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:48,867 INFO : org.reflections.Reflections - Reflections took 2286 ms to scan 1 urls, producing 2 keys and 2 values 
13:13:51.810 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:51,808 WARN : org.elasticsearch.discovery - [graylog2-server] waited for 3s and no initial state was set by the discovery
13:13:51.810 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:51,809 INFO : org.elasticsearch.node - [graylog2-server] started
13:13:56.334 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:56,333 ERROR: org.graylog2.periodical.AlertScannerThread - Indexer is not running, not checking streams for alerts.
13:13:56.821 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:56,817 INFO : org.graylog2.initializers.IndexerSetupService - Checking Elasticsearch HTTP API at http://127.0.0.1:9200/
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,212 ERROR: org.graylog2.initializers.IndexerSetupService - Could not connect to Elasticsearch at http://127.0.0.1:9200/, is it running?
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - java.net.ConnectException: Connection refused: /127.0.0.1:9200 to http://127.0.0.1:9200/_nodes
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:104)
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:431)
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:422)
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:384)
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
13:13:57.216 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at java.lang.Thread.run(Thread.java:745)
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:9200
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	... 8 more
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,215 ERROR: org.graylog2.UI - 
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - ################################################################################
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - ERROR: Could not successfully connect to Elasticsearch, if you use multicast check that it is working in your network and that Elasticsearch is running properly and is reachable. Also check that the cluster.name setting is correct.
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - Need help?
13:13:57.217 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - * Official documentation: https://www.graylog.org/documentation/intro/
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - * Community support: https://www.graylog.org/community-support/
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - * Commercial support: https://www.graylog.com/support/
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - But we also got some specific help pages that might help you in this case:
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - * https://www.graylog.org/documentation/setup/elasticsearch/
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - Terminating. :(
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 
13:13:57.218 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - ################################################################################
13:13:57.248 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 
13:13:57.249 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,231 ERROR: com.google.common.util.concurrent.ServiceManager - Service IndexerSetupService [FAILED] has failed in the STARTING state.
13:13:57.249 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - java.lang.IllegalStateException
13:13:57.249 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.graylog2.UI.exitHardWithWall(UI.java:36)
13:13:57.249 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.graylog2.initializers.IndexerSetupService.startUp(IndexerSetupService.java:171)
13:13:57.249 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
13:13:57.249 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
13:13:57.249 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at java.lang.Thread.run(Thread.java:745)
13:13:57.627 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,418 INFO : org.graylog2.shared.journal.JournalReader - Stopping.
13:13:57.630 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,343 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.AlertScannerThread].
13:13:57.630 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,628 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.AlertScannerThread] complete, took <0ms>.
13:13:57.630 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,628 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread].
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,628 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] complete, took <0ms>.
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,628 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.ClusterHealthCheckThread].
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,628 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.ClusterHealthCheckThread] complete, took <0ms>.
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,628 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.IndexerClusterCheckerThread].
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,628 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.IndexerClusterCheckerThread] complete, took <0ms>.
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,628 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.IndexRetentionThread].
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,628 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.IndexRetentionThread] complete, took <0ms>.
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,628 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.IndexRotationThread].
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,629 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.IndexRotationThread] complete, took <0ms>.
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,629 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.VersionCheckThread].
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,629 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.VersionCheckThread] complete, took <0ms>.
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,629 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.ThrottleStateUpdaterThread].
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,629 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.ThrottleStateUpdaterThread] complete, took <0ms>.
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,543 ERROR: org.graylog2.shared.initializers.InputSetupService - Not starting any inputs because lifecycle is: Uninitialized [LB:DEAD]
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,502 WARN : org.graylog2.initializers.BufferSynchronizerService - Elasticsearch is unavailable. Not waiting to clear buffers and caches, as we have no healthy cluster.
13:13:57.631 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,629 INFO : org.elasticsearch.node - [graylog2-server] stopping ...
13:13:57.820 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,817 INFO : org.graylog2.initializers.OutputSetupService - Stopping output org.graylog2.outputs.BlockingBatchedESOutput
13:13:57.861 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,856 INFO : org.elasticsearch.node - [graylog2-server] stopped
13:13:57.861 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,856 INFO : org.elasticsearch.node - [graylog2-server] closing ...
13:13:57.925 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:13:57,925 INFO : org.elasticsearch.node - [graylog2-server] closed
13:14:15.039 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:14:15,033 INFO : org.graylog2.shared.initializers.RestApiService - Adding security context factory: <org.graylog2.security.ShiroSecurityContextFactory@485ac68d>
13:14:15.097 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:14:15,097 INFO : org.graylog2.shared.initializers.RestApiService - Started REST API at <http://127.0.0.1:12900/>
13:14:15.226 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:14:15,223 INFO : org.graylog2.shared.initializers.RestApiService - Shutting down REST API at <http://127.0.0.1:12900/>
13:14:15.232 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:14:15,232 INFO : org.graylog2.shared.initializers.ServiceManagerListener - Services are now stopped.
13:14:15.233 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:14:15,232 ERROR: org.graylog2.bootstrap.ServerBootstrap - Graylog startup failed. Exiting. Exception was:
13:14:15.233 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {STARTING=[RestApiService [STARTING]], FAILED=[IndexerSetupService [FAILED]]}
13:14:15.233 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:710)
13:14:15.233 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:535)
13:14:15.233 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:301)
13:14:15.233 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:113)
13:14:15.233 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:196)
13:14:15.233 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 	at org.graylog2.bootstrap.Main.main(Main.java:58)
13:14:15.277 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:14:15,266 INFO : org.graylog2.bootstrap.commands.Server - SIGNAL received. Shutting down.
13:14:15.303 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:14:15,302 INFO : org.graylog2.system.shutdown.GracefulShutdown - Graceful shutdown initiated.
13:14:15.303 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:14:15,303 INFO : org.graylog2.system.shutdown.GracefulShutdown - Node status: [Halting [LB:DEAD]]. Waiting <3sec> for possible load balancers to recognize state change.
13:14:19.318 [Thread-123              ] INFO  org.graylog2.setup.ProcessHandler - 2015-02-24 13:14:19,317 INFO : org.graylog2.system.shutdown.GracefulShutdown - Goodbye.
```

**Comment by gzcwnk** [comment]
=======log======
13:39:09.204 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 12 times
13:39:10.221 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 13 times
13:39:10.445 [Thread-2882             ] INFO  org.graylog2.setup.ProcessHandler - [2015-02-24 13:39:10,435][INFO ][node                     ] [graylog2_elasticsearch] version[1.4.3], pid[15348], build[36a29a7/2015-02-11T14:23:15Z]
13:39:10.445 [Thread-2882             ] INFO  org.graylog2.setup.ProcessHandler - [2015-02-24 13:39:10,435][INFO ][node                     ] [graylog2_elasticsearch] initializing ...
13:39:10.445 [Thread-2882             ] INFO  org.graylog2.setup.ProcessHandler - [2015-02-24 13:39:10,440][INFO ][plugins                  ] [graylog2_elasticsearch] loaded [], sites []
13:39:11.239 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 14 times
13:39:12.244 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 15 times
13:39:13.249 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 16 times
13:39:14.254 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 17 times
13:39:15.272 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 18 times
13:39:16.293 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 19 times
13:39:17.299 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 20 times
13:39:18.313 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 21 times
13:39:19.321 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 22 times
13:39:20.326 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 23 times
13:39:21.347 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 24 times
13:39:22.355 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 25 times
13:39:23.367 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 26 times
13:39:24.376 [Thread-2879             ] INFO  o.g.s.h.StartAllProcessesHandler - Tried to connect to Graylog2Server 27 times
=====log=======

**Comment by bernd** [comment]
It looks like the quick setup app was not able to start Elasticsearch. Can you check if you can start elasticsearch manually via `ES_HEAP_SIZE=2g elasticsearch/bin/elasticsearch -p run/elasticsearch.pid -Des.config=conf/elasticsearch.yml`?

**Comment by gzcwnk** [comment]
this is the complete command?

**Comment by gzcwnk** [comment]
======
[root@vuwunicoradius1 bin]# pwd
/root/graylog/graylog-setup/elasticsearch/bin
[root@vuwunicoradius1 bin]# cd ../..
[root@vuwunicoradius1 graylog-setup]# ES_HEAP_SIZE=2g elasticsearch/bin/elasticsearch -p run/elasticsearch.pid -Des.config=conf/elasticsearch.yml
[2015-02-25 08:39:48,823][INFO ][node                     ] [graylog2_elasticsearch] version[1.4.3], pid[12266], build[36a29a7/2015-02-11T14:23:15Z]
[2015-02-25 08:39:48,824][INFO ][node                     ] [graylog2_elasticsearch] initializing ...
[2015-02-25 08:39:48,861][INFO ][plugins                  ] [graylog2_elasticsearch] loaded [], sites []

[2015-02-25 08:40:05,614][INFO ][node                     ] [graylog2_elasticsearch] initialized
[2015-02-25 08:40:05,614][INFO ][node                     ] [graylog2_elasticsearch] starting ...
[2015-02-25 08:40:05,838][INFO ][transport                ] [graylog2_elasticsearch] bound_address {inet[/127.0.0.1:10101]}, publish_address {inet[/127.0.0.1:10101]}
[2015-02-25 08:40:05,870][INFO ][discovery                ] [graylog2_elasticsearch] graylog2/qp-YiuP3S7OJ1IRGyt_04g
[2015-02-25 08:40:08,918][INFO ][cluster.service          ] [graylog2_elasticsearch] new_master [graylog2_elasticsearch][qp-YiuP3S7OJ1IRGyt_04g][vuwunicoradius1.ods.vuw.ac.nz][inet[/127.0.0.1:10101]], reason: zen-disco-join (elected_as_master)
[2015-02-25 08:40:09,007][INFO ][http                     ] [graylog2_elasticsearch] bound_address {inet[/127.0.0.1:10102]}, publish_address {inet[/127.0.0.1:10102]}
[2015-02-25 08:40:09,008][INFO ][node                     ] [graylog2_elasticsearch] started
[2015-02-25 08:40:09,021][INFO ][gateway                  ] [graylog2_elasticsearch] recovered [0] indices into cluster_state

=======
?

**Comment by gzcwnk** [comment]
So how do I clean this up and make it robust?

Is graylog not ready for RHEL7? ie am I better going back to RHEL6?

**Comment by joschi** [comment]
@gzcwnk We've had reports from users that Graylog (and Elasticsearch) are running fine on RHEL7/CentOS 7 (e. g. by using our official RPM packages), so I suspect that this is a bug or some incompatibility in the quick setup application.

**Comment by bernd** [comment]
@gzcwnk Also, the quick setup app is not meant to create a production setup. It can be used to setup a demo system quickly for testing.

If you want a robust production setup, you should rather use the operating system packages.
http://docs.graylog.org/en/1.0/pages/installation.html#operating-system-packages

We do not show RHEL 7 on that page, but the CentOS 6 packages should work fine. (https://packages.graylog2.org/el/6Server/1.0/x86_64)

**Comment by gzcwnk** [comment]
I have given up on the quick setup.   Now I am trying to setup manually, but this is only to briefly try it, a rather poor impression to start with.

**Comment by bernd** [comment]
Sorry to hear that the quick setup application did not work out for you. :disappointed:

We just tried to run it on CentOS 7 (compatible with RHEL 7) to make sure there is not problem with that OS in general.
